apache/geode

gemfire-spark-connector/gemfire-spark-connector/src/it/scala/ittest/io/pivotal/gemfire/spark/connector/testkit/GemFireRunner.scala

Spark Geode Connector now uses gfsh from current Geode build.

GEODE-115 Change gfsh path for integration tests

---

gemfire-core/src/main/java/com/gemstone/gemfire/distributed/DistributedSystem.java
gemfire-core/src/main/java/com/gemstone/gemfire/distributed/internal/AbstractDistributionConfig.java
gemfire-core/src/main/java/com/gemstone/gemfire/distributed/internal/DistributionConfig.java
gemfire-core/src/main/java/com/gemstone/gemfire/distributed/internal/DistributionConfigImpl.java
gemfire-core/src/main/java/com/gemstone/gemfire/internal/redis/Coder.java
gemfire-core/src/main/java/com/gemstone/gemfire/internal/redis/ExecutionHandlerContext.java
gemfire-core/src/main/java/com/gemstone/gemfire/internal/redis/RedisCommandType.java
gemfire-core/src/main/java/com/gemstone/gemfire/internal/redis/RedisConstants.java
gemfire-core/src/main/java/com/gemstone/gemfire/internal/redis/executor/AuthExecutor.java
gemfire-core/src/main/java/com/gemstone/gemfire/management/internal/cli/commands/LauncherLifecycleCommands.java
gemfire-core/src/main/java/com/gemstone/gemfire/management/internal/cli/i18n/CliStrings.java
gemfire-core/src/main/java/com/gemstone/gemfire/redis/GemFireRedisServer.java
gemfire-core/src/test/java/com/gemstone/gemfire/redis/AuthJUnitTest.java
gemfire-core/src/test/resources/com/gemstone/gemfire/codeAnalysis/sanctionedSerializables.txt

Also added Geode property "redis-password" so the authentication password can be set by xml or through GFSH

GEODE-83 Add support for Redis AUTH command

---

gemfire-core/src/main/java/com/gemstone/gemfire/internal/redis/Coder.java

Previously encoding a response would not be able to handle the case
where an entry was concurrently destroyed. The fix is to catch the
EntryDestroyedException gracefully

GEODE-222 Allow redis adapter to handle live entry objects

---

gemfire-core/src/main/java/com/gemstone/gemfire/internal/cache/tier/sockets/command/CommitCommand.java
gemfire-core/src/test/java/com/gemstone/gemfire/internal/cache/tier/sockets/command/CommitCommandTest.java

A fix for the NullPointerException thrown in TX_SYNCHRONIZATION command processing of AFTER_COMPLETION event during JTA transaction rollback.

GEODE-537 Fix NPE in AFTER_COMPLETION processing during JTA transaction rollback

---

gemfire-site/website/content/index.html

The first sentence on the http://geode.incubator.apache.org/ web page means something different than intended. The sentence says
"Solving low latency data management problems at very high concurrency since 2002."
Low latency modifies data management problems. Because of this, the sentence implies that the problems being solved are ones that exhibit low latency. This is the opposite of what is intended.
This pull request implements a better wording for that sentence:
Providing low latency, high concurrency data management solutions since 2002.

GEODE-655 Website sentence needs improvement

---

gemfire-assembly/src/test/java/com/gemstone/gemfire/management/internal/cli/commands/LauncherLifecycleCommandsJUnitTest.java

Updated JUNIT to assert appropriate Spring and SDG versions.

GEODE-893: CI failure: LauncherLifecycleCommandsJUnitTest.testGetSpringJars

---

geode-examples/README.md

GEODE-1523: Improve examples README.md markdown
This PR fixes addresses both GEODE-1525 and GEODE-1523, as they
both change the contents of the same file: geode-examples/README.md.
- Each example will likely use a scripts/setEnv.sh script to set
the path to gfsh. The script depends on a GEODE_HOME environment
variable, so this top level of instructions for setting up
the examples now tells the user to set a GEODE_HOME env variable
directly after the installation.
- Implement a more strict markdown that displays correctly for a
wide variety of markdown implementations.
- Put in links for the 3 references.
- Improve the prose.

GEODE-1525: Examples README.md should set env variable

---

geode-assembly/build.gradle

This makes starting a server with Redis actually work, at least on my machine.

Add geode-redis to assembly.

---

geode-docs/tools_modules/gfsh/command-pages/start.html.md.erb

reference page.
- the optional http-service-port defaults to 7070
- both http-service-port and http-service-bind-address
are available for gfsh start server and gfsh start locator
New PR for the doc task.  @kirklund @joeymcallister @davebarnes97 @kohlmu-pivotal  please review.

GEODE-2103 Update gfsh start server|locator command

---

geode-lucene/src/main/java/org/apache/geode/cache/lucene/LuceneQueryFactory.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneQueryFactoryImpl.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneSearchIndexFunction.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/EvictionDUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/ExpirationDUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneIndexDestroyDUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneQueriesAccessorBase.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/MixedObjectIndexDUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/PaginationDUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/LuceneQueryFactoryImplJUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneSearchIndexFunctionJUnitTest.java

* Renamed LuceneQueryFactory.getResult to setLimit()
* This is done to match the cwiki documents

GEODE-2637: Refactored LuceneQueryFactory.setResultLimit()

---

geode-client-protobuf/src/main/java/org/apache/geode/protocol/client/ProtobufProtocolMessageHandler.kt
geode-client-protobuf/src/main/proto/clientProtocol.proto
geode-client-protobuf/src/main/proto/region_API.proto
geode-client-protobuf/src/main/proto/server_API.proto
geode-client-protobuf/src/test/java/org/apache/geode/protocol/client/ProtobufProtocolIntegrationTest.kt

These are mostly unimplemented, and some, especially GetServers, may not
make it through in this form. It's a good sketch for feature parity with
the REST API, though.
This is on a feature branch, so I'm going to skip the normal test list. Please review and comment. @udo @hiteshk25 @bschuchardt and Brian and Alexander, whose github names I can't seem to find.

Add a bunch of .proto definitions to the new protocol.

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/ConnectionFactoryImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/HandShake.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/misc/GatewayLegacyAuthenticationRegressionTest.java

* add GatewayLegacyAuthenticationRegressionTest to reproduce bug
* fix authentication of Gateway sender/receiver with
SECURITY_CLIENT_AUTHENTICATOR
- [x ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?
- [x ] Is your initial contribution a single, squashed commit?
- [x ] Does `gradlew build` run cleanly?
- [x ] Have you written or updated unit tests to verify your changes? …

GEODE-3117: fix Gateway authentication with legacy security

---

geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/GfshStartLocatorLogTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java
geode-core/src/main/java/org/apache/geode/internal/AbstractConfig.java
geode-core/src/main/java/org/apache/geode/internal/Banner.java
geode-core/src/main/java/org/apache/geode/internal/i18n/LocalizedStrings.java
geode-core/src/main/java/org/apache/geode/internal/logging/LogWriterFactory.java
geode-core/src/main/java/org/apache/geode/internal/logging/log4j/LogWriterAppenders.java
geode-core/src/test/java/org/apache/geode/internal/logging/TestLogWriterFactory.java
geode-core/src/test/java/org/apache/geode/test/dunit/SerializableCallable.java

[View the JIRA ticket here.](https://issues.apache.org/jira/browse/GEODE-2601)
The original fix (#582) fixed the security banner logging twice, but not the startup configurations. This PR finishes the fix. Note that only the startup configurations in `InternalLocator.java` were deleted, since in #582 it was determined that an internal locator would not exist without an internal distributed system, and therefore, the startup configurations could be logged exclusively in `InternalDistributedSystem.java`.
**_Precheckin status: completed successfully_**
**_Additional testing done: Manually verified that both the banner and the startup configs only log once; also working on writing a test with @pdxrunner to verify changes_**

GEODE-2601: Fixing startup configurations logging twice

---

geode-core/src/main/java/org/apache/geode/distributed/LocatorLauncher.java
geode-core/src/main/java/org/apache/geode/distributed/ServerLauncher.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommand.java
geode-core/src/test/java/org/apache/geode/distributed/LauncherIntegrationTestCase.java
geode-core/src/test/java/org/apache/geode/distributed/LocatorLauncherLocalIntegrationTest.java
geode-core/src/test/java/org/apache/geode/distributed/LocatorLauncherRemoteIntegrationTest.java
geode-core/src/test/java/org/apache/geode/distributed/ServerLauncherLocalIntegrationTest.java
geode-core/src/test/java/org/apache/geode/distributed/ServerLauncherRemoteIntegrationTest.java
geode-core/src/test/java/org/apache/geode/distributed/ServerLauncherTest.java
geode-core/src/test/java/org/apache/geode/test/dunit/rules/GfshShellConnectionRule.java

Updated tests for changes in the error constructors for ServerState and
LocatorState.
Minor spelling corrections.
This reintroduces changes that were reverted due to merge conflicts with
the previous state of the develop branch
* Precheckin ran green with all but one cut-and-paste error (line ServerLauncher:2613) that was corrected before pushing to github. 
* Precheckin re-run is in progress after correcting the above error.

GEODE-3277: Fix error path constructors of Launcher inner State classess

---

geode-core/src/test/java/org/apache/geode/distributed/internal/deadlock/GemFireDeadlockDetectorDUnitTest.java

When a cache has already been created and closed in the current JVM,
`TypeRegistry` will have a flag set that stops a distributed system from
sending messages. This means we can't connect to a distributed system,
even though there doesn't seem to be any reason to disallow it. This is
to stop the test failing; a real fix will come later.

GEODE-3580: patch test to avoid the current failure.

---

geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/ConnectCommandWithSSLTest.java

This should correct the failure observed in the nightly-build 953

GEODE-3615: Added CleanupDUnitVMsRule to ConnectCommandWithSSLTest

---

geode-assembly/src/test/java/org/apache/geode/rest/internal/web/GeodeRestClient.java
geode-assembly/src/test/java/org/apache/geode/rest/internal/web/RestServersJUnitTest.java
geode-junit/src/main/java/org/apache/geode/test/junit/categories/RestAPITest.java

This should correct the Jenkins nightly failures we have seen recently.
====

GEODE-3426: Ignore RestServersJUnitTest when default port is unavailable.

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/ConnectionImpl.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderOperationsDUnitTest.java

The gateway sender shutdown code calls connection.destroy to interrupt the ack
reader thread. Connection.destroy was calling socket.shutDownOutput.
SSLSockets do not support socket.shutDownOutput() resulting in connections not
being destroyed. This left the AckReaderThread stuck on read holding a
readLock, which prevented the stopper thread from getting a writeLock.

GEODE-3636: Fixing hang shutting down gateway sender with SSL

---

geode-core/src/main/java/org/apache/geode/cache/PartitionAttributes.java
geode-core/src/main/java/org/apache/geode/cache/PartitionAttributesFactory.java

GEODE-2719 : Deprecated setTotalMaxMemory and getTotalMaxMemory and updated their javadocs.

---

geode-core/src/main/java/org/apache/geode/internal/cache/snapshot/RegionSnapshotServiceImpl.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ImportDataIntegrationTest.java

A relative path provided for the location of a snapshot, where the relative path contained no parent would fail. This fix converts the path to absolute before finding the parent.
@jaredjstewart

GEODE-3626: Fix relative path support for snapshots

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/PoolImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/AcceptorImpl.java

Use one CommunicationMode variable, not 3.
Also, refactor the selector and not-selector cases into separate
methods.
I'm not changing the `ServerConnectionFactory` because it more or less
passes straight through to `ServerConnection`, and there's too much
legacy code there to change easily.

GEODE-3609 Small AcceptorImpl refactor

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionFactory.java
geode-protobuf/src/main/java/org/apache/geode/protocol/protobuf/statistics/ProtobufClientStatisticsImpl.java
geode-protobuf/src/test/java/org/apache/geode/protocol/acceptance/CacheConnectionJUnitTest.java
geode-protobuf/src/test/java/org/apache/geode/protocol/acceptance/LocatorConnectionDUnitTest.java

- Enhance and rename test of basic messages and statistics to use the statistics directly.
- Fix protobuf client statistics to properly update messages sent and received statistics.
- Remove another use of stats file.
Signed-off-by: Galen O'Sullivan <gosullivan@pivotal.io> …

GEODE-3083: Fix geode-protobuf stats.

---

build.gradle
geode-old-versions/build.gradle

Modified the geode-old-versions build to now pull down the from the maven repository instead of a mirror.  This zip should now be cached locally.

GEODE-3629: Old versions will be pulled from the Apache Maven Repo

---

build.gradle
geode-concurrency-test/build.gradle
geode-concurrency-test/src/main/java/java/net/InetAddress.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/ConcurrentTestRunner.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/ParallelExecutor.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/RunnableWithException.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/Runner.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/annotation/ConcurrentTestConfig.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/jpf/JpfRunner.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/jpf/JpfRunnerConfig.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/jpf/ParallelExecutorImpl.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/jpf/logging/EmptyLogger.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/jpf/peers/JPF_java_util_concurrent_locks_ReentrantReadWriteLock.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/jpf/peers/JPF_org_apache_geode_distributed_internal_InternalDistributedSystem.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/jpf/peers/JPF_org_apache_geode_internal_logging_LogService.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/jpf/peers/JPF_org_apache_geode_internal_logging_log4j_LogMarker.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/jpf/peers/JPF_org_apache_logging_log4j_LogManager.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/loop/LoopRunner.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/loop/LoopRunnerConfig.java
geode-core/build.gradle
geode-core/src/jpfTest/java/org/apache/geode/internal/cache/FilterProfileConcurrencyTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/FilterProfile.java
gradle/rat.gradle
settings.gradle

Added a new junit runner, ConcurrentTestRunner, for running a test that
has parallel threads.
The runner currently runs the test using Java PathFinder, which will
run the test with all interleavings of the threads.
Added an example test to geode-core for the FilterProfile serialization
logic.

Adding a new framework for concurrency testing in geode

---

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneCreateIndexFunction.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneDescribeIndexFunction.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneDestroyIndexFunction.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneListIndexFunction.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneSearchIndexFunction.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneCreateIndexFunctionJUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneDescribeIndexFunctionJUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneDestroyIndexFunctionJUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneListIndexFunctionJUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneSearchIndexFunctionJUnitTest.java

Removed the static lookup of a cache from gfsh related functions in the
lucene module.

GEODE-3680 - Removing static cache lookup from lucene functions

---

geode-docs/managing/security/implementing_authorization.html.md.erb

@sbawaska @jinmeiliao @PurelyApplied @jaredjstewart @davebarnes97 @joeymcallister Please review.
Note that I also moved CqQuery execute() and executeWithInitialResults() methods to reside within the table for JMX operations, as they were misplaced.

GEODE-3578 Revise docs for CQ authorization level change

---

geode-core/src/main/java/org/apache/geode/cache/query/internal/DerivedInfo.java
geode-core/src/test/java/org/apache/geode/cache/query/JoinQueriesIntegrationTest.java

* Queries with two join condition were entering duplciate entries into the final result set
* We do not add the new result entry in derieved info if the entry is already present.

GEODE-3707: Removal of duplicate entries

---

geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/utilities/ProtobufUtilities.java

We used to have
```
warning - Tag @link: reference not found: BasicTypes.Entry
```
Planning to merge this as soon as PR build goes green.

GEODE-3684: fix a warning during javadoc generation.

---

geode-core/src/main/java/org/apache/geode/internal/io/MainWithChildrenRollingFileHandler.java
geode-core/src/test/java/org/apache/geode/test/dunit/rules/LocatorServerStartupRule.java
geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/ConfigCommandDUnitTest.java

Added new tests.
Fixes problem in LocatorServerStartupRule where a faiulure due to
suspect strings caused dunit VM cleanup to be skipped.
Verified new tests with before and after fix runs.
Precheckin is running

GEODE-3620: check for null argument to prevent NPE

---

geode-core/src/test/java/org/apache/geode/test/junit/rules/MemberStarterRule.java

ConnectCommandWithSSLTest fails often in precheckin and nightly due to some previous tests leaving behind Non-SSL SocketCreators resulting in this test's locator starting up with non-ssl tcpServer. 
Fix is to add the close clause in the MemberStarterRule.

GEODE-3720: clean up SocketCreators in each test VM properly

---

geode-docs/tools_modules/gfsh/command-pages/search.html.md.erb
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/LuceneCliStrings.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommands.java

Supporting --queryString and --queryStrings in the search lucene command.

GEODE-3722: Fixing typo in lucene query command

---

geode-cq/src/test/java/org/apache/geode/internal/cache/tier/sockets/DurableClientTestCase.java

These tests were marked ignored referencing some pre-geode bug.
Reenabling them. The tests are not failing for me after fixing the way the tests get ports.

GEODE-3721: Renabling durable client tests that were ignored

---

geode-assembly/src/test/java/org/apache/geode/session/tests/CargoTestBase.java
geode-assembly/src/test/java/org/apache/geode/session/tests/ContainerManager.java
geode-assembly/src/test/java/org/apache/geode/session/tests/ServerContainer.java

The session replication tests were generating logs files that were
getting deleted. In order to debug issues with the session state tests
we need to information in the log files to show up in the test output.

GEODE-3613: Dumping container logs files in session replication tests

---

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/distributed/LuceneQueryFunction.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/distributed/WaitUntilFlushedFunction.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/results/LuceneGetPageFunction.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneClientSecurityDUnitTest.java

Changing the permissions on the LuceneQueryFunction to only require
DATA:READ

GEODE-3628: Lucene query only needs DATA:READ

---

geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionDataStore.java
geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionAttributesMutatorTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionDataStoreJUnitTest.java

Partitioned region attributes mutation can fail to be applied to
buckets created concurrently. Preventing bucket creation during the
mutation of attributes solves this issue.

GEODE-3647: Fix race condition

---

extensions/geode-modules-tomcat8/src/test/java/org/apache/geode/modules/session/Tomcat8SessionsClientServerDUnitTest.java

Changing this test to use a random port for the geode server.

GEODE-3441: Use random port in Tomcat8SessionsClientServerDUnitTest

---

geode-core/src/main/java/org/apache/geode/examples/security/ExampleSecurityManager.java

It's security-manager = org.apache.geode.examples.security.ExampleSecurityManager not org.apache.geode.security.examplesExampleSecurityManager
https://stackoverflow.com/questions/46548293/geode-securitymanager-implementation
Yeah
I don't know
No!

Fix the path error in the Javadoc

---

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/LuceneCliStrings.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommands.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexDetails.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexInfo.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneCreateIndexFunction.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsDUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsJUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneCreateIndexFunctionJUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/configuration/LuceneClusterConfigurationDUnitTest.java

gfsh create index now supports a LuceneSerializer and the serializer is
persisted in cluster configuration.

GEODE-3242, GEODE-3243: Add gfsh support for LuceneSerializer

---

geode-core/src/main/java/org/apache/geode/distributed/ServerLauncher.java
geode-core/src/test/java/org/apache/geode/distributed/ServerLauncherBuilderTest.java

Because this flag is set incorrectly, resulting in two cache servers been added while applying the cluster config xml.

GEODE-3567: correctly set the serverPortSetByUser flag

---

geode-core/src/main/java/org/apache/geode/cache/wan/GatewayReceiver.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheCreation.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/GatewayReceiverCreation.java
geode-wan/src/main/java/org/apache/geode/internal/cache/wan/GatewayReceiverImpl.java
geode-wan/src/test/java/org/apache/geode/cache/CacheXml70GatewayDUnitTest.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/GatewayReceiverImplJUnitTest.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/misc/WANConfigurationJUnitTest.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/wancommand/CreateGatewayReceiverCommandDUnitTest.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/wancommand/WANCommandTestBase.java

- bind-address specified in gemfire.properties is now used to configure Profile and ServerLocations
- removed host field (previously calculated at config time based on hostname-for-sender and bind-address parameters)
with result then passed to CacheServerImpl.start()
- replaced host field with hostnameForSenders, which is now used (when set) to set hostnameForClients in CacheServerImpl.
- replaced getHost with getHostnameForSenders
- associated tests, including those to set bind-address and server-bind-address through gemfire.properties …

GEODE-3687: GatewayReceiverImpl constructor and create method updates

---

geode-core/src/test/java/org/apache/geode/test/dunit/examples/BeforeClassExampleTest.java
geode-core/src/test/java/org/apache/geode/test/dunit/examples/LocatorPortClusterExampleTest.java
geode-core/src/test/java/org/apache/geode/test/dunit/rules/tests/DistributedTestRuleTest.java
geode-core/src/test/java/org/apache/geode/test/dunit/rules/tests/SharedCountersRuleTest.java
geode-core/src/test/java/org/apache/geode/test/dunit/rules/tests/SharedErrorCollectorTest.java

* use getVMCount instead of 4
These are dunit infrastructure tests that attempted to assert that the default VM count is 4 or attempted some unrelated assertion which would fail if the test class runs after any other dunit test that uses more than the default number of VMs.
This should prevent any further intermittent failures of any of the tests in this change set.

GEODE-3755: make resilient to variable number of dunit VMs

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientUpdater.java
geode-core/src/main/java/org/apache/geode/internal/i18n/LocalizedStrings.java

This is logging changes that should already exist.
The change to CacheClientNotifier logs a warning on the serverin the one place that was logged before when the responseByte is not successful like:
```
[warn 2017/10/04 15:45:04.879 PDT <Handshaker 0.0.0.0/0.0.0.0:29869 Thread 0> tid=0x6e] A previous connection attempt from this client is still being processed: identity(192.168.2.5(28918:loner):52814:275690e9,connection=1,durableAttributes=DurableClientAttributes[id=testBug40165ClientReconnects_client; timeout=60])
```
The change to CacheClientUpdater logs and rethrows the ServerRefusedConnectionException on the client like:
```
[warn 2017/10/04 15:45:04.880 PDT <main> tid=0x1] Cache Client Updater Thread  on boglesbymac-2(28921)<v2>:32770 port 29869 (localhost:29869): Caught following …
```

GEODE-3742: Added logging to help identify this issue

---

geode-core/src/test/java/org/apache/geode/internal/process/FileProcessControllerIntegrationTest.java

* main thread was completing the test and tearDown before
the executor thread could return the status

GEODE-3778: fix flakiness with Awaitility

---

geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb
geode-docs/topologies_and_comm/multi_site_configuration/setting_up_a_multisite_system.html.md.erb

The gfsh create gateway-receiver command now accepts a
hostname-for-senders option.
@ladyVader @upthewaterspout @davebarnes97 @joeymcallister Please review.

GEODE-3612 Document new gfsh option

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/AlterRuntimeConfigFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/ChangeLogLevelFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/ContinuousQueryFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/CreateAsyncEventQueueFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/CreateDefinedIndexesFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/CreateDiskStoreFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/CreateIndexFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DeployFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DestroyDiskStoreFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DestroyIndexFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/ExportConfigFunction.java

To simplify reviews, the changes required for this refactoring will
be broken up into separate commitss.
This commit is the first set of refactored Functions to get the Cache
reference from the the FunctionContext parameter.

GEODE_3299: Refactor Gfsh functions to acquire Cache from FunctionContex

---

geode-core/src/test/java/org/apache/geode/internal/cache/ReplicateCacheListenerInvocationTest.java

New JUnit 4 version of an old test. Some methods are protected because the next PR contains two tests that extend this one.

GEODE-3790: add new test for CacheListener invocations

---

geode-core/src/test/java/org/apache/geode/internal/cache/PRCacheListenerInvocationTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/PRCacheListenerWithInterestPolicyAllInvocationTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/ReplicateCacheListenerInvocationTest.java

Note: We also changed the getOldValue assertions in the base test to match the javadocs which say that it may return the old value or null.

GEODE-3791: add new tests for CacheListener on PartionedRegion

---

geode-core/src/test/java/org/apache/geode/cache30/CacheStatisticsDUnitTest.java

This test can fail when the last modified time and last accessed time are set in different milliseconds (i.e. when the time it takes between the setting the value of last modified time and getting a timestamp from the clock for the last accessed time span the change in the value of the clock).

GEODE-3805: Use correct timestamplto check last modified time

---

geode-core/src/test/java/org/apache/geode/management/internal/cli/result/CommandResultTest.java

Replace explicit newline in expected strings with
SystemUtils.LINE_SEPARATOR so tests can run on Windows

GEODE-3826: Use system independent expected strings

---

geode-assembly/src/test/java/org/apache/geode/session/tests/TomcatClientServerTest.java

We saw a test fail where the cache server failed to connect to the
locator. Increasing the member timeout in hopes that the failure was due
to a lack of resources on the machine.

GEODE-3500: Increase member timeout in tomcat session tests

---

geode-core/src/test/java/org/apache/geode/test/dunit/rules/CleanupDUnitVMsRule.java

Bounce the VMs once at the beginning of the test so they start clean.
Rules in the test ensure the VMs are cleaned up after each test method.

GEODE-3720: Bounce DUnit VMs to give the test a clean environment

---

geode-core/src/test/java/org/apache/geode/internal/cache/RemoteOperationMessageTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/PartitionMessageTest.java

I also made all variables private, organized imports and changed the test method signatures to throw Exception.
Reviewers + @nreich

GEODE-2046: use CALLS_REAL_METHODS instead of internal method

---

geode-core/src/main/java/org/apache/geode/management/DistributedSystemMXBean.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateIndexCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DefineIndexCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeRegionCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DisconnectCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/GetCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/GfshCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/LocateEntryCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/PutCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/RemoveCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ShowMetricsCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/converters/RegionPathConverter.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/shell/Gfsh.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommandDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommandTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/IndexCommandsIntegrationTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/RemoveCommandDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/converters/RegionPathConverterJUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/shell/GfshJunitTest.java
geode-core/src/test/java/org/apache/geode/test/dunit/rules/MemberVM.java
geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshShellConnectionRule.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneServiceImpl.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommands.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneDestroyIndexFunction.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/ValidateCommandParametersTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsDUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneDestroyIndexFunctionJUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/configuration/LuceneClusterConfigurationDUnitTest.java

* added the if-exists option for destroy region
* refactor the RegionPathConverter for better validation of regionPath
* cleaned up commands that uses the RegionPathConverter to not do unnecessary validation
* reworked DestroyRegionCommandDUnitTest
* added more tests

GEODE-2563: destroy region should be idempotent

---

geode-docs/configuring/cluster_config/export-import.html.md.erb
geode-docs/configuring/cluster_config/persisting_configurations.html.md.erb
geode-docs/tools_modules/gfsh/command-pages/export.html.md.erb

gfsh command 'export cluster-configuration' no longer takes a '--dir' option. The '--zip-file-name' option does it all.
Request reviews from @jaredjstewart , @karensmolermiller , @joeymcallister

GEODE-2405 Update docs with changes to export cluster-configuration

---

geode-lucene/src/main/java/org/apache/geode/cache/lucene/LuceneSerializer.java

User's may want to create LuceneSerializers that only support specific
types, eg LuceneSerializer<MyDomainObject>. Adding a parameterized type
to the LuceneSerializer interface.

Parameterizing LuceneSerializer with a type

---

geode-docs/configuring/running/running_the_cacheserver.html.md.erb
geode-docs/tools_modules/gfsh/command-pages/start.html.md.erb

Also corrected a typo and improved wording in the
gfsh start server command reference page.

GEODE-3538 Update doc section Running Geode Server Processes

---

geode-core/src/main/java/org/apache/geode/admin/jmx/internal/AgentLauncher.java
geode-core/src/test/java/org/apache/geode/admin/jmx/internal/DeprecatedAgentLauncherIntegrationTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/DeprecatedCacheServerLauncherIntegrationTest.java

Two more old tests that have been reworked and are passing consistently. These can be deleted only when we finally delete these deprecated classes:
* org.apache.geode.admin.jmx.internal.AgentLauncher
* org.apache.geode.internal.cache.CacheServerLauncher

GEODE-3866: add integration tests for deprecated launchers

---

gradle/dependency-versions.properties

Precheckin for this change is GREEN. No code changes were required -- just updating the version number in the build.

GEODE-3847: upgrade to AssertJ 3.8.0

---

geode-wan/src/test/java/org/apache/geode/internal/cache/wan/concurrent/ConcurrentParallelGatewaySenderOperation_1_DUnitTest.java

* The exception occured when in the tear down.
* The test is very simple and there are a lot of other similar tests which are not flaky.
* This test was a part of improvements made to the WAN test base.
* Test tear down involving senders was also fixed as a part of GEODE-3276

GEODE-1772: Removal of flaky tag.

---

geode-core/src/main/java/org/apache/geode/admin/internal/AdminDistributedSystemImpl.java
geode-core/src/main/java/org/apache/geode/admin/internal/BackupStatusImpl.java

Fixed by having the legacy class hold a copy of the new class and delegate requests to that instance.

GEODE-3885: Fix backup from AdminDistributedSystem

---

geode-wan/src/test/java/org/apache/geode/internal/cache/wan/misc/PDXNewWanDUnitTest.java

* After the receiver's region size is checked, immediately the afterAcknowledgement stat is checked in the sender
* In a slow system, the ack may not have arrived, or was not yet processed enough to call the listeners at the moment when the stats were checked.
* Waiting for a little more time may result in the stat to be updated and test not failing.

GEODE-1319: Awaitility clause added.

---

geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PersistentMemberManager.java

- Fix typo in javadoc for PersistentMemberManager.addRevocationListener

GEODE-3880: Fix typo in Javadoc

---

geode-core/src/main/java/org/apache/geode/internal/cache/execute/FunctionContextImpl.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/GetRegionDescriptionFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/ShowMissingDiskStoresFunction.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/ShowMissingDiskStoresFunctionJUnitTest.java

Throw the exception when cache == null instead of returning the null.
Gfsh functions handle CacheClosedException, whereas
NullPointerExceptions that resulted from returning null are not.

GEODE-3299: throw CacheClosedException in FunctionContext.getCache()

---

geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegionMap.java
geode-core/src/test/java/org/apache/geode/internal/cache/DestroyEntryWithConcurrentOperationJUnitTest.java

* Add test case for heap region as well as offheap region.
* Rename the test.

GEODE-3190: Fix a race by checking if region is destroyed

---

ci/docker/Dockerfile
ci/docker/cache_dependencies.sh
ci/pipelines/develop.yml
ci/pipelines/docker-images.yml
ci/pipelines/meta.yml
ci/scripts/build.sh

* Implements GEODE-3942.
* Add pipelines for develop, building the docker images that builds geode,
and updating those those pipelines.
* Add build script.
* Add Dockerfile for building geode in Concourse.
- [ N/A ] If adding new dependencies to …

Add files necessary for Concourse CI infrastructure.

---

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeConnectionCommandJUnitTest.java
geode-core/src/test/java/org/apache/geode/test/junit/assertions/GfshShellConnectionRuleAssert.java

GEODE-3539: Add missing test coverage for 'describe connection' command.

---

geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/AbstractRegionJUnitTest.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneIndexFactoryImpl.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneIndexImpl.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneRegionListener.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneServiceImpl.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/xml/LuceneIndexCreation.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneIndexCreationDUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneIndexCreationIntegrationTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/LuceneIndexFactoryImplJUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/LuceneServiceImplJUnitTest.java

- This is currently just an internal method to create the index on an existing
region.  It does not actually index the existing data in the region.
- Adding a parameter to LuceneIndexFactoryImpl.create to allow creation on
an existing region.

GEODE-3930: Create lucene index on an existing region

---

geode-core/src/test/java/org/apache/geode/management/RegionManagementDUnitTest.java

With the DUnit test framework there should be a locator, and a manager
and 3 members created in the test. (expectedCount = 5)
Remove Flaky tags

GEODE-3335: Fix expected member count

---

geode-core/src/main/java/org/apache/geode/internal/cache/TXCommitMessage.java

Now uses getDistributionManager on region instead.

GEODE-3601: remove getExisting call

---

geode-core/src/main/java/org/apache/geode/distributed/internal/DM.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionManager.java
geode-core/src/main/java/org/apache/geode/distributed/internal/LonerDistributionManager.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/SearchLoadAndWriteProcessor.java
geode-core/src/test/java/org/apache/geode/test/fake/Fakes.java

DM.getCache is now used instead of getInstance.

GEODE-3594: remove calls of getInstance

---

geode-core/src/main/java/org/apache/geode/distributed/internal/DM.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionManager.java
geode-core/src/main/java/org/apache/geode/distributed/internal/LonerDistributionManager.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXCommitMessage.java
geode-core/src/test/java/org/apache/geode/test/fake/Fakes.java

DM.getCache is now used instead of getInstance

GEODE-3593: remove call to getInstance

---

geode-core/src/test/java/org/apache/geode/internal/cache/CommitFunction.java

Now uses FunctionContext.getCache instead.

GEODE-3592: remove getAnyInstance call

---

geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/security/LogoutHandler.java
geode-pulse/src/test/java/org/apache/geode/tools/pulse/internal/security/LogoutHandlerUnitTest.java

. Added JUnit tests.
. Removed unnecessary logging in LogoutHandler.
. Removed unnecessary downcasting in LogoutHandler.

GEODE-3951: PULSE Logout exception when using the defaults.

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateDefinedIndexesCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/CreateDefinedIndexesFunction.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateDefinedIndexesCommandDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateDefinedIndexesCommandTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/CreateDefinedIndexesFunctionTest.java
geode-core/src/test/java/org/apache/geode/test/fake/Fakes.java

GEODE-3898: Defined Indexes are not Persisted in Cluster Configuration.
. Added JUnit and DUnit tests.
. CreateDefinedIndexesFunction returns a list of CliFunctionResult and XmlEntity with the indexes created.
. CreateDefinedIndexesCommand parses the list of results and persists the changes in the cluster configuration service. This is done only once per region whenever at least one member was able to successfully create the index on the region.
email to …

Fix for GEODE-3898: Defined Indexes are not Persisted in Cluster Configuration.

---

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ShowMetricsCommandIntegrationTest.java

*The commit (`69143c...`) did not rename `GfshShellConenectionRule` to `GfshCommandRule`, resulting in build failure after rebasing.
---

GEODE-3961: Correct test after bad rebase.

---

geode-core/src/test/java/org/apache/geode/security/query/QuerySecurityBase.java
geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqSecurityAuthorizedUserDUnitTest.java

* Test failure was attributed to an incompatible cache present in the system.
* The @After method will close the cache after each test.

GEODE-3935: Closing down the cache after each test.

---

geode-wan/src/test/java/org/apache/geode/internal/cache/wan/misc/WanValidationsDUnitTest.java

* Refactoring the test base class occured in a different ticket.

GEODE-1019: Removing the flaky tag

---

geode-core/src/main/antlr/org/apache/geode/cache/query/internal/parse/oql.g
geode-core/src/test/java/org/apache/geode/cache/query/QueryServiceJUnitTest.java
geode-core/src/test/java/org/apache/geode/cache/query/internal/parse/OQLParserTest.java

GEODE-3938: Allow query parameters within the to_date preset query function.
. Added unit tests.
. Changed oql.g to allow both 'stringLiteral' and 'queryParam' within the do_date preset function definition.

Fix for GEODE-3938

---

geode-core/src/test/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgrade2DUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgradeDUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscDUnitTest.java
geode-core/src/test/java/org/apache/geode/test/dunit/standalone/DUnitLauncher.java
geode-core/src/test/java/org/apache/geode/test/dunit/standalone/ProcessManager.java
geode-cq/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscBCDUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneSearchWithRollingUpgradeDUnit.java
geode-wan/src/test/java/org/apache/geode/cache/wan/WANRollingUpgradeDUnitTest.java

* getVM(int index) call will not roll the vm back to current version.

GEODE-3985: rolling upgrade tests is prone to accidentally roll the vms back to current version

---

geode-core/src/main/java/org/apache/geode/cache/query/internal/index/MemoryIndexStore.java
geode-core/src/test/java/org/apache/geode/cache/query/internal/index/MemoryIndexStoreJUnitTest.java

Setting the cache from the memory index store instead of GemFireCacheImpl.getInstance().

GEODE-3982: MemoryIndexStoreIterator should not call GemFireCacheImpl

---

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeConnectionCommandJUnitTest.java

Due to a critical oversight on my part, the test committed in ``a1b9725a7cb351299a5239a79f96daed9d88865b` and reverted in `70b4327b196630c638a6e7aef608405d2d73db98` did not account for testing environments that resolve the host address to an alias given in `/etc/hosts`.
This commit restores the test, accounting for this possible output.
Precheckin running.
--

GEODE-3539: Restore test coverage for 'describe connection' command.

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListRegionCommand.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/HeadlessGfsh.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeRegionDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeRegionIntegrationTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListRegionDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListRegionIntegrationTest.java
geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshCommandRule.java

* Mutually exclusive options --group and --member checked in interceptor instead of failing server-side
* Command logic flattened to stream.
* Testing of 'list region' and 'describe region' separated into distinct DUnit and Integration tests
* Removed @Flaky annotation from 'describe region' DUnit test.

GEODE-3539: Add missing test coverage for 'list regions' and 'describe region' commands

---

geode-core/src/test/java/org/apache/geode/internal/process/lang/AvailablePidTest.java

The extra findAvailablePids calls result in flaky results on
Windows.

GEODE-3980: Remove unneeded additional findAvailablePids calls

---

geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/LauncherLifecycleCommandsDUnitTest.java

The heap size for test014GemFireServerJvmProcessTerminatesOnOutOfMemoryError
is marginally increased from 10M to 12M. This should allow sufficient
memory to start the servers, but not so much that the test takes too long
to force the OutOfMemoryError.

GEODE-3999: Prevent prematurely running out of heap

---

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/AlterDiskStoreDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/AlterDiskStoreIntegrationTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/AlterDiskStoreJUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsDUnitTest.java

* Remove flaky testing from DiskStoreCommandsDUnitTest, converted to AlterDiskStoreDUnitTest
* Added AlterDiskStoreIntegrationTest for testing of option conflict
---

GEODE-3539: Add test coverage to 'alter disk-store'.

---

geode-core/src/test/java/org/apache/geode/test/dunit/rules/tests/CacheRuleTest.java

GEODE-4014 only occurs if one of the previously run dunit tests (within fork every 30) used more than the default four VMs. This change will keep CacheRuleTest passing no matter how many VMs are available to dunit.

GEODE-4014: use getVMCount instead of hardcoding number of VMs

---

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeDiskStoreCommandIntegrationTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListDiskStoreCommandIntegrationTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListRegionIntegrationTest.java
geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshCommandRule.java

* reduce the default timeout
* add ability to configure the timeout at construction time.

GEODE-3539: enhance GfshCommandRule. Rename method for consistency.

---

geode-core/src/main/java/org/apache/geode/cache/execute/FunctionContext.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateAsyncEventQueueCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyDiskStoreCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/GfshCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/RegionCreateFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/RegionDestroyFunction.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateAsyncEventQueueCommandTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommandDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommandTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/RegionDestroyFunctionTest.java

* use tabular result display for destroy region command.
* status to reflect at least one region is created/deleted and cluser config is updated.

GEODE-4049: refactor CreateRegionCommand and DestoryRegionCommand status

---

geode-core/src/test/java/org/apache/geode/internal/cache/backup/BackupDistributedTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/PersistentColocatedPartitionedRegionDUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/fixed/FixedPartitioningTestBase.java
geode-core/src/test/java/org/apache/geode/internal/cache/wan/AsyncEventQueueTestBase.java
geode-core/src/test/java/org/apache/geode/test/dunit/cache/internal/JUnit4CacheTestCase.java
geode-core/src/test/java/org/apache/geode/test/dunit/internal/JUnit4DistributedTestCase.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/WANTestBase.java

Avoid hangs due to leftover disk files by making sure that all tests
that use JUnit4DistributedCase have their disk files cleaned up after
the test, including a locators ConfigDiskDir_

GEODE-4058: Always delete disk files after every test runs

---

geode-client-protocol/src/main/java/org/apache/geode/internal/protocol/operations/OperationHandler.java
geode-client-protocol/src/main/java/org/apache/geode/internal/protocol/state/ConnectionShiroAuthorizingStateProcessor.java
geode-client-protocol/src/main/java/org/apache/geode/internal/protocol/state/ConnectionStateProcessor.java
geode-client-protocol/src/main/java/org/apache/geode/internal/protocol/state/ConnectionTerminatingStateProcessor.java
geode-client-protocol/src/main/java/org/apache/geode/internal/protocol/state/exception/OperationNotAuthorizedException.java
geode-core/src/main/java/org/apache/geode/internal/cache/client/protocol/ClientProtocolProcessor.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/GenericProtocolServerConnection.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/ProtobufCachePipeline.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/ProtobufLocatorPipeline.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/ProtobufOpsProcessor.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/HandshakeRequestOperationHandler.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/security/AuthenticationRequestOperationHandler.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/AuthenticationIntegrationTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/HandshakeIntegrationTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/acceptance/CacheConnectionTimeoutJUnitTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/GetAllRequestOperationHandlerJUnitTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/GetAvailableServersOperationHandlerJUnitTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/GetRegionNamesRequestOperationHandlerJUnitTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/HandshakeRequestOperationHandlerJUnitTest.java

@PivotalSarge @galen-pivotal @bschuchardt @upthewaterspout 
This will cause the connection to be closed whenever a handshake or
authentication message fails.
The connection will also be broken if we ever receive an unexpected handshake or
authenticantication message.
Signed-off-by: Brian Rowe <browe@pivotal.io>

GEODE-4007: Authentication/Handshake errors should close the socket

---

geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreMonitor.java
geode-core/src/test/java/org/apache/geode/internal/cache/DiskUsageTest.java

The message in the exception thrown when the disk monitor
detects we have gone critical (i.e. run out of space) will
now also tell why it went critical.
It will either say something like this:
the file system is 2% full, which exceeds the critical threshold of 1.9%.
or something like this:
the file system only has 98 bytes free which is below the minimum of 1048576.
Also added unit test for DiskUsage class.

GEODE-3976: improve exception message

---

geode-wan/src/main/java/org/apache/geode/internal/cache/wan/GatewaySenderEventRemoteDispatcher.java

* The global connection variable may be set to null by another thread.
* Assign the local variable to the connection variable and then perform all the null checks on that local variable.

GEODE-4072: Fixed race condition in AckThreadReader shutdown.

---

geode-core/src/main/java/org/apache/geode/distributed/internal/ReplyProcessor21.java

Add an extra level of logging if a view doesn't come back during severe
alert processing.
Some cleanup; the important stuff is lines 721..726 .
Signed-off-by: Galen O'Sullivan <gosullivan@pivotal.io>

GEODE-3964: More logging for suspect processing.

---

geode-core/src/main/java/org/apache/geode/internal/cache/eviction/AbstractEvictionList.java
geode-core/src/main/java/org/apache/geode/internal/cache/eviction/LRUListWithAsyncSorting.java
geode-core/src/main/java/org/apache/geode/internal/cache/eviction/LRUListWithSyncSorting.java
geode-core/src/test/java/org/apache/geode/internal/cache/eviction/AbstractEvictionListTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/eviction/LRUListWithAsyncSortingTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/eviction/LRUListWithSyncSortingIntegrationTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/eviction/RegionEntryEvictionIntegrationTest.java

While code review found that the refactoring moved "evictionNode.unsetRecentlyUsed()" to
"appendEntry()" which gets call by other places (adding entry into the list); this causes
the recently used entry to be evicted early.

GEODE-3869: Fix early eviction.

---

geode-core/src/main/java/org/apache/geode/internal/cache/eviction/LRUListWithAsyncSorting.java

The threads created to do background eviction scanning
will now be named "LRUListWithAsyncSortingThreadNNN".
The will now be daemon threads.
They now have an unhandled exception handler.
Their group is named "LRUListWithAsyncSorting Threads".

GEODE-4091: add ThreadFactory for evictor

---

geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/SizeMessage.java

It is normal for a SizeMessage to arrive and either the
partitioned region to not yet be initialized or it could
have been destroyed. In either case a warning is not needed.
So the warning message has been changed to debug.

GEODE-4099: change warning to debug

---

geode-docs/reference/topics/gemfire_properties.html.md.erb

GEODE-3923 Document the 2 new properties serializable-object-filter

---

geode-core/src/main/java/org/apache/geode/cache/query/IndexType.java
geode-core/src/main/java/org/apache/geode/cache/query/QueryService.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/HashIndex.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheXml.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java

* Added deprecated tags on HashIndex class
* Deprecated createHashIndex calls in QueryService
* Deprecated HASH type in IndexType
* Added to the help text in gfsh create index mentioning hash index being deprecated since Apache Geode 1.4.0

GEODE-4079: Deprecated Hash Index

---

geode-core/src/main/java/org/apache/geode/internal/cache/eviction/LRUListWithAsyncSorting.java

If LRUListWithAsyncSorting is used a info log message now says so.

GEODE-4109: add log message

---

geode-docs/developing/query_index/create_multiple_indexes.html.md.erb
geode-docs/developing/query_index/creating_an_index.html.md.erb
geode-docs/developing/query_index/creating_hash_indexes.html.md.erb
geode-docs/developing/query_index/query_index.html.md.erb

I have marked all subsections on hash indexes as deprecated, and I have removed all examples (java code, XML, and gfsh commands) that demonstrated how to do things with hash indexes.

GEODE-4079 Identify hash indexes as deprecated in docs

---

geode-core/src/test/resources/org/apache/geode/internal/cache/xmlcache/CacheXmlParserJUnitTest.testSimpleClientCacheXml.cache.xml

This change speeds up the test to run in just over 2 seconds instead of taking over 2 minutes to complete.

GEODE-4117: use loopback instead of non-existent server host

---

geode-core/src/main/java/org/apache/geode/cache/client/ClientCacheFactory.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateDefinedIndexesCommandDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DeployCommandRedeployDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommandDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/ImportClusterConfigDistributedTest.java
geode-core/src/test/java/org/apache/geode/management/internal/security/MultiClientDUnitTest.java
geode-core/src/test/java/org/apache/geode/security/ClientAuthDUnitTest.java
geode-core/src/test/java/org/apache/geode/security/ClientDestroyInvalidateAuthDUnitTest.java
geode-core/src/test/java/org/apache/geode/test/dunit/rules/ClientVM.java
geode-core/src/test/java/org/apache/geode/test/dunit/rules/LocatorServerStartupRule.java
geode-core/src/test/java/org/apache/geode/test/dunit/rules/MemberVM.java
geode-core/src/test/java/org/apache/geode/test/junit/rules/ClientCacheRule.java
geode-core/src/test/java/org/apache/geode/test/junit/rules/VMProvider.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/wancommand/CreateDestroyGatewaySenderCommandDUnitTest.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/wancommand/CreateGatewayReceiverCommandDUnitTest.java

* created a new ClientCacheRule to create a client cache in current VM.
* have lcoatorserverStartupRule to use that rule to start up a client VM.

GEODE-4110: extend LocatorServerStartupRule to start a client VM.

---

ci/scripts/test-archive.sh
ci/scripts/test-run.sh

Take 2: Escaping forward-declared functions makes the variables have
content when you need it!
When the pipeline fails, the email subject contains the pipeline name
and the job name.
Signed-off-by: Owen Nichols <onichols@pivotal.io> …

[GEODE-4123] - Improve output email of concourse.apachegeodeci.info

---

geode-core/src/test/java/org/apache/geode/internal/cache/versions/RegionVersionVectorTest.java

By using an ExecutorService, tearDown can invoke shutdownNow which will interrupt any Executor task threads including the hung thread in doesNotHangIfOtherThreadChangedVersion.

GEODE-4134: use ExecutorService for CompletableFuture

---

geode-docs/tools_modules/gfsh/command-pages/destroy.html.md.erb

Documented the gfsh command `destroy async-event-queue`.
While I was at it, added documentation for the `--if-exists` option for some other destroy commands.

GEODE-2665: Document Gfsh command to delete async event queues

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartMemberUtils.java

GEODE-4097 allow to take geode-core jar from class path, change hard coded value in getGemFireJarPath

GEODE-4097 allow to take geode-core jar from classpath

---

geode-assembly/src/test/java/org/apache/geode/tools/pulse/PulseConnectivityTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/PRCacheListenerInvocationTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/PRCacheListenerWithInterestPolicyAllInvocationTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/wan/GatewayReceiverXmlParsingValidationsJUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ChangeLogLevelCommandDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/GcCommandDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ShowLogCommandDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/converters/BaseStringConverterJUnitTest.java
geode-core/src/test/java/org/apache/geode/security/query/IndexSecurityDUnitTest.java
geode-core/src/test/java/org/apache/geode/security/query/PartitionedIndexSecurityDUnitTest.java
geode-core/src/test/java/org/apache/geode/security/query/PdxPartitionedQuerySecurityAllowedQueriesDUnitTest.java
geode-core/src/test/java/org/apache/geode/security/query/PdxQuerySecurityAllowedQueriesDUnitTest.java
geode-core/src/test/java/org/apache/geode/security/query/PdxQuerySecurityRestrictedQueriesDUnitTest.java
geode-core/src/test/java/org/apache/geode/security/query/QuerySecurityUnauthorizedUserBindParameterDUnitTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/acceptance/CacheConnectionJUnitTest.java
geode-pulse/src/test/java/org/apache/geode/tools/pulse/internal/security/LogoutHandlerUnitTest.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/GatewayReceiverFactoryImplJUnitTest.java
geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/ClusterConfigurationDUnitTest.java

* Optimize imports in touched files.
* Fix small error in GcCommandDUnitTest in error phrasing
* The following will be corrected in separate tickets:
* - QueryCommandTest
* - ShutdownCommandDUnitTest
* - CacheServerSSLConnectionDUnitTest
---

GEODE-4122: Add runner annotation to avoid skipping tests with Parameterized

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/FunctionContextArgumentProvider.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/xml/JdbcConnectorServiceXmlGenerator.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/xml/JdbcConnectorServiceXmlParser.java
geode-connectors/src/main/resources/META-INF/services/schemas/geode.apache.org/schema/jdbc/jdbc-1.0.xsd
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/JdbcClusterConfigDistributedTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/xml/JdbcConnectorServiceXmlGeneratorIntegrationTest.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/domain/XmlEntity.java

The JdbcConnectorService usage of XmlEntity was resulting in multiple jdbc connector service elements being written to cluster config. This then results in already exists exceptions during startup.
JdbcClusterConfigDistributedTest reproduced the problem we saw during manual testing and verifies the fix.

GEODE-4146: fix XmlEntity matching for JdbcConnectorService

---

geode-wan/src/main/java/org/apache/geode/internal/cache/wan/GatewaySenderEventRemoteDispatcher.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/GatewaySenderEventRemoteDispatcherJUnitTest.java

* Information on how the race condition occurs is provided in the GEODE-4096 ticket.
* getConnection before returning null and clearing out the global variable connection calls stop on the dispatcher.
* This makes sure that AckReaderThreads for the dispatcher is shutdown and prevents lingering threads holding the connection life cycle lock.

GEODE-4096: Fixed race condition for connection global variable

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommand.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommandIntegrationTest.java

If the jdbc-mapping had no field to column items,
then describe jdbc-mapping would fail with an NPE.

GEODE-4161: fix gfsh describe jdbc-mapping

---

geode-core/src/main/java/org/apache/geode/cache/query/internal/index/PartitionedIndex.java
geode-core/src/test/java/org/apache/geode/cache/query/internal/index/PartitionedIndexJUnitTest.java

* mapIndexKeys was a HashSet and concurrent access to it resulted in inconsistent data to be present.
* Changed to a set with a concurrent hash map as a backing store.

GEODE-4184: Handled concurrent access of HashSet

---

geode-wan/src/test/java/org/apache/geode/internal/cache/wan/WANTestBase.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/misc/PDXNewWanDUnitTest.java

* Additional awaitility added to check for the region size
* Modified the test structure.

GEODE-4135: Awaitility condition added

---

ci/scripts/update-passing-ref.sh

[GEODE-4185]
The endpoint is changed to
http://files.apachegeode-ci.info/<branch>/passing.txt …

Fix script so passing.txt is branch-dependent.

---

geode-core/src/test/java/org/apache/geode/test/dunit/standalone/DUnitLauncher.java

Modified DUnitLauncher.getVM(int n) to again allow -1 to get at the debugging VM.
@upthewaterspout  @jhuynh1 @nabarunnag

GEODE-4221: Restore the ability to access the debugging VM.

---

ci/scripts/test-run.sh

* If the container running the tests is killed, the error function
* setting up the email contents will never run. Pre-populate the email
* contents with text indicating the task timeout was hit.
[GEODE-4247]
- [ N/A ] If adding new dependencies to …

GEODE-4247: Pre-populate email subject and body files

---

geode-core/src/main/java/org/apache/geode/internal/cache/StateFlushOperation.java
geode-core/src/test/java/org/apache/geode/internal/cache/StateMarkerMessageTest.java

One of the calls in StateMarkerMessage process would not end
up sending a reply if waitForCurrentOperations threw an exception.
It now has a finally block that makes sure the reply message is
always sent.

GEODE-4051: change StateMarkerMessage to always reply

---

extensions/geode-modules/src/main/java/org/apache/geode/modules/util/BootstrappingFunction.java
extensions/geode-modules/src/main/java/org/apache/geode/modules/util/CreateRegionFunction.java
extensions/geode-modules/src/main/java/org/apache/geode/modules/util/RegionSizeFunction.java
extensions/geode-modules/src/main/java/org/apache/geode/modules/util/TouchPartitionedRegionEntriesFunction.java
extensions/geode-modules/src/main/java/org/apache/geode/modules/util/TouchReplicatedRegionEntriesFunction.java
extensions/geode-modules/src/test/java/org/apache/geode/modules/util/ModuleFunctionsSecurityTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/RegionCreateFunction.java

GEODE-3974: Improve permissions for geode-modules functions

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/xml/JdbcConnectorServiceXmlGenerator.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommandDUnitTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/xml/JdbcConnectorServiceXmlGeneratorIntegrationTest.java

When field mapping is not provided, cluster configuration for
region mapping was not working.

GEODE-4241: Write region mapping to cluster configuration

---

geode-core/src/test/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java

this is just an enhancement, 
sometimes if user id a VM vm = cluster.getVM(n, "130"), and later on, wants to get the same vm again, they probably would just do a cluster.getVM(n), but this call would bounce the VM to current version without the fix.

GEODE-4225: getVM(n) call does not accidentally bounce the VM with current version

---

geode-wan/src/test/java/org/apache/geode/internal/cache/wan/misc/WANConfigurationJUnitTest.java

Since GatewayReceiverImpl uses a much less brittle string comparison now, the case that this mandatory failure was trying to avoid no longer exists.
@jhuynh1 @nabarunnag

GEODE-4255: Remove mandatory failure on macOS.

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/AlterConnectionFunction.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/AlterMappingFunction.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateConnectionFunction.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingFunction.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeConnectionFunction.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingFunction.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyConnectionFunction.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyMappingFunction.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/JdbcCliFunction.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/ListConnectionFunction.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/ListMappingFunction.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/JDBCConnectorFunctionsSecurityTest.java

GEODE-3974: Improve permissions for geode-connectors functions

---

buildSrc/src/main/groovy/org/apache/geode/gradle/TestPropertiesWriter.groovy

@upthewaterspout @bschuchardt @WireBaron @galen-pivotal

GEODE-4246: Skip setting the mcast-port property.

---

geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandTest.java
geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartServerCommandTest.java

StartServerCommandTest failed in CI build, but the assertion that failed
didn't provide any useful debugging information
Change the assertion to use assertj so more information will be lgged
regarding mismatches between expected and actual command arguments.
Also changed expectedCommandLineElements to only contain the command args that
we really care about - those that are specific to the command. Other arguments
maythat are dependant on the test environment may vary and ignored in
these tests. …

GEODE-4101: Only check for specific command line arguments

---

geode-assembly/src/test/java/org/apache/geode/tools/pulse/PulseJmxPasswordFileTest.java
geode-core/src/main/java/org/apache/geode/management/internal/ManagementAgent.java

GEODE-4293: Pulse works correctly when jmx-manager-password-file is set

---

gradle/publish.gradle

Updated `scm refs` with appropriate github URLs.

GEODE-4292: Update scm refs in maven pom to github

---

geode-core/src/main/java/org/apache/geode/distributed/ServerLauncher.java

Backwards compatability was inadvertently broken.  This restores the lost method's publicity.

GEODE-4298: Restore public access to StartServer method.

---

geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java

Avoid seeking user inputs on missing SSL parameters in SocketCreator instead 
use default values so that client does not have to include SpringShell dependency
in the class path.
For Gfsh, ConnectCommand checks for missing parameters and prompts user inputs.
For other clients, consider possible default values.

GEODE-4291: Avoid asking user input in SocketCreator

---

geode-core/src/test/java/org/apache/geode/internal/cache/OplogJUnitTest.java

Added a countdown latch to enforce serialization of actions in test to prevent race condition that resulted in values being read before the final writes occured.

GEODE-527: Fix race condition that caused sporadic test failure

---

geode-core/src/main/java/org/apache/geode/pdx/internal/PeerTypeRegistration.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/misc/PDXNewWanDUnitTest.java

If we are unable to find a PDX type during a get, will we get a
distributed lock and try again. This prevents races where the type may
be in the middle of distribution.
Adding a dunit test for the race condition that requires this fix.
@PivotalSarge

GEODE-4285: Get a distributed lock if we can't find a PDX type

---

geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegionMap.java
geode-core/src/main/java/org/apache/geode/internal/cache/AbstractUpdateOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistTXState.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistTXStateOnCoordinator.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistributedPutAllOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRemoveAllOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/EntryEventImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/InitialImageOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegionDataView.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionDataStore.java
geode-core/src/main/java/org/apache/geode/internal/cache/RemotePutAllMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/RemoteRemoveAllMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXEntryState.java
geode-core/src/main/java/org/apache/geode/internal/cache/entries/AbstractRegionEntry.java
geode-core/src/main/java/org/apache/geode/internal/cache/entries/DiskEntry.java
geode-core/src/test/java/org/apache/geode/internal/cache/AbstractRegionJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/ClientServerInvalidAndDestroyedEntryDUnitTest.java

The concurrencyChecksEnabled is now always accessed using
getConcurrencyChecksEnabled and setConcurrencyChecksEnabled.

GEODE-4305: encapsulate the concurrencyChecksEnabled field

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerImpl.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/ConnectionPoolImplJUnitTest.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerJUnitTest.java

I moved the application of the variance from the pool implementation to the connection manager implementation to avoid impacting too much of the code, which lead to some failing tests.
For some reason the combination of IntelliJ and Spotless expanded some wildcard import statements but I left those as-is.
@upthewaterspout @bschuchardt @WireBaron @galen-pivotal 
Please ensure that once the PR is submitted, you check travis-ci for …

GEODE-4147: Add variability to client rebalance logic.

---

extensions/geode-modules/src/main/java/org/apache/geode/modules/util/CreateRegionFunction.java
extensions/geode-modules/src/main/java/org/apache/geode/modules/util/TouchPartitionedRegionEntriesFunction.java
extensions/geode-modules/src/main/java/org/apache/geode/modules/util/TouchReplicatedRegionEntriesFunction.java
extensions/geode-modules/src/test/java/org/apache/geode/modules/util/ModuleFunctionsSecurityTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/JDBCConnectorFunctionsSecurityTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/deadlock/GemFireDeadlockDetector.java
geode-core/src/main/java/org/apache/geode/internal/cache/MemberFunctionStreamingMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/snapshot/ClientExporter.java
geode-core/src/main/java/org/apache/geode/internal/cache/snapshot/RegionSnapshotServiceImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/snapshot/WindowedExporter.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/QueryDataFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/ExportDataFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/FetchRegionAttributesFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/ImportDataFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/UserFunctionExecution.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/functions/GetClusterConfigurationFunction.java
geode-core/src/main/java/org/apache/geode/security/ResourcePermission.java
geode-core/src/test/java/org/apache/geode/internal/cache/execute/FunctionServiceBase.java
geode-core/src/test/java/org/apache/geode/internal/cache/functions/TestFunction.java
geode-core/src/test/java/org/apache/geode/security/ClientExecuteFunctionAuthDUnitTest.java
geode-core/src/test/java/org/apache/geode/test/junit/assertions/CommandResultAssert.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/test/LuceneFunctionSecurityTest.java

* function executed on a local member does not log out user accidentally
* Mark some internal functions as InternalEntity
* test refactor

GEODE-3974: function security improvement

---

geode-core/src/test/java/org/apache/geode/cache/management/MemoryThresholdsDUnitTest.java

* This test could fail if two messages are sent close enough in time that
* they are processed out of order, as the test expects each message to be
* processed in order, though there is no product requirement for that
* behavior

GEODE-427: Prevent out of order message processing

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartMemberUtils.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/StartMemberUtilsTest.java

GEODE-4275: Improved StartMemberUtils.addMaxHeap
- Added test methods.
- Modified the method to avoid adding `"-XX:+UseConcMarkSweepGC"` if
the user already specified parameter as a jvm argument.
- Modified the logic to avoid setting the default value for
`"-XX:CMSInitiatingOccupancyFraction="` if the user already specified
one as a jvm argument.

GEODE-4275: Improved StartMemberUtils.addMaxHeap

---

geode-core/src/test/java/org/apache/geode/cache30/CacheXml70DUnitTest.java
geode-core/src/test/java/org/apache/geode/cache30/CacheXmlTestCase.java
geode-core/src/test/java/org/apache/geode/test/dunit/cache/internal/JUnit4CacheTestCase.java

GEODE-4312: Wait for rebalancing to complete as part of teardown

---

geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartLocatorAcceptanceTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommand.java

GEODE-4332: Gfsh start locator should not retrieve cluster status when --connect=false

---

geode-core/src/main/java/org/apache/geode/management/internal/ManagementAgent.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/FileUploader.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/FileUploaderMBean.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/shell/JmxOperationInvoker.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt
geode-core/src/test/java/org/apache/geode/management/internal/beans/FileUploaderTest.java

- This flips the deployment of jars from a pull (by server) to a push (from
gfsh).

GEODE-4379: Move RemoteOutputStreamServer from gfsh to the manager

---

geode-core/src/main/java/org/apache/geode/cache/query/internal/index/CompactRangeIndex.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/MemoryIndexStore.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/DistributedSystemBridge.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/ManagementAdapter.java
geode-core/src/test/java/org/apache/geode/cache/query/internal/index/MemoryIndexStoreJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/ColocationHelperTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/control/RebalanceOperationDUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/wan/parallel/ParallelQueueRemovalMessageJUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/beans/DistributedSystemBridgeJUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/ShowMissingDiskStoresFunctionJUnitTest.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/AckReaderThreadJUnitTest.java

These calls were trying to set the instance variable to a mock instance.
None of them were actually needed.
@WireBaron

GEODE-4387: Removing calls to setInstanceForTests

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/ShutDownFunction.java
geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/ShutdownCommandOverHttpDUnitTest.java

- This adds a small delay in the async shutdown function so that any client
responses can be sent. This avoids client getting some form of disconnect
exception during shutdown.

GEODE-4374: Allow client calls to complete before shutting down

---

geode-core/src/test/java/org/apache/geode/internal/statistics/DiskSpaceLimitIntegrationTest.java

Paired with @jdeppe-pivotal to fix this. The validation was overly precise in two spots. It was sampling until rollover but the stat file size allows it to potentially rollover twice. This is not important for the test -- it just requires at least one rollover and then it requires that the oldest file is deleted due to disk-space-limit.

GEODE-3205: GEODE-2790: fix flakiness in file number validation

---

geode-core/src/test/java/org/apache/geode/cache30/MultiVMRegionTestCase.java

GEODE-4149: Replace CacheFactory.getInstance(getSystem()) with JUnit4CacheTestCase.getCache().

---

geode-core/src/main/java/org/apache/geode/admin/internal/CacheServerImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/CacheServerImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/OriginalServerConnection.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ProtobufServerConnection.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionFactory.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionFactoryTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/cache/tier/sockets/OutputCapturingServerConnectionTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/cache/tier/sockets/ProtobufServerConnectionTest.java

- Rename LegacyServerConnection to OriginalServerConnection.
- Rename GenericProtocolServerConnection to ProtocolServerConnection.
- Rename GenericProtocolServerConnectionTest to ProtocolServerConnectionTest.
@WireBaron @galen-pivotal …

GEODE-4368: Rename server connection classes.

---

geode-core/src/main/java/org/apache/geode/cache/CacheFactory.java
geode-core/src/main/java/org/apache/geode/distributed/DistributedSystem.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/statistics/HostStatSampler.java
geode-core/src/test/java/org/apache/geode/pdx/internal/MultipleCacheJUnitTest.java

If the system property gemfire.ALLOW_MULTIPLE_SYSTEMS is set, then we will
allow multiple caches in the same JVM. Otherwise, the we will have the
same behavior as before.
If the system property is set, we will not retain any static instance of
the cache or distributed system.
Removed the static instance variables from GemFireCacheImpl.
GemFireCacheImpl.getInstance calls now look up the cache instance from
the distributed system.
Note that a single distributed system can still only have a single
cache. Users should create caches and distributed systems using
CacheFactory.create. …

GEODE-4308: Allow two caches in the same JVM if a feature flag is on

---

geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySenderEventProcessor.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/concurrent/ConcurrentParallelGatewaySenderDUnitTest.java

GEODE-3653: Remove testHook from AGSEP
- Removed `TEST_HOOK` from AbstractGatewaySenderEventProcessor.
- The property `numEventsDispatched` was being used only by test
classes, no functionality impact.
- Updated `ConcurrentParallelGatewaySenderDUnitTest`, removed unused
imports and verified that current tests finish correctly.

GEODE-3653: Remove testHook from AGSEP

---

geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreFactoryImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalCache.java
geode-core/src/main/java/org/apache/geode/internal/cache/Oplog.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionDataStore.java
geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupService.java
geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupTask.java
geode-core/src/main/java/org/apache/geode/internal/cache/backup/FileSystemBackupDestination.java
geode-core/src/main/java/org/apache/geode/internal/cache/backup/FinishBackup.java
geode-core/src/main/java/org/apache/geode/internal/cache/backup/PrepareBackup.java
geode-core/src/main/java/org/apache/geode/internal/cache/backup/TemporaryBackupFiles.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheCreation.java
geode-core/src/main/java/org/apache/geode/internal/i18n/LocalizedStrings.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/MemberMBeanBridge.java
geode-core/src/test/java/org/apache/geode/internal/cache/DiskStoreImplIntegrationTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/backup/BackupIntegrationTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/backup/BackupServiceTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/backup/FinishBackupRequestTest.java
geode-core/src/test/java/org/apache/geode/management/internal/beans/DistributedSystemBridgeJUnitTest.java

For each backup request, instead of creating BackupManager, the request is passed to a BackupService.

GEODE-3800: Replace BackupManager with BackupService

---

geode-core/src/main/java/org/apache/geode/internal/cache/client/protocol/ClientProtocolService.java
geode-protobuf-messages/src/main/proto/v1/clientProtocol.proto
geode-protobuf-messages/src/main/proto/v1/function_API.proto
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/LocatorMessageExecutionContext.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/MessageExecutionContext.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/ProtobufProtocolService.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/ProtobufSerializationService.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/ServerMessageExecutionContext.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/ExecuteFunctionOnRegionRequestOperationHandler.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/registry/ProtobufOperationContextRegistry.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/TestExecutionContext.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/FunctionExecutionIntegrationTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/ExecuteFunctionOnRegionRequestOperationHandlerJUnitTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/GetAllRequestOperationHandlerJUnitTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/GetRegionNamesRequestOperationHandlerJUnitTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/GetRegionRequestOperationHandlerJUnitTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/GetRequestOperationHandlerJUnitTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/GetServerOperationHandlerJUnitTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/OperationHandlerJUnitTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/PutAllRequestOperationHandlerJUnitTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/PutRequestOperationHandlerJUnitTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/RemoveRequestOperationHandlerJUnitTest.java

This only supports function execution on a region so far. It assumes the
default result collector, which returns a list of results.
* MessageExecutionContext uses InternalCache instead of Cache
* Remove super.setUp calls from operation handlers because the
@Before annotation already ensures these are called before the
@Before methods of child classes.
For review, I'm particularly interested in what edge cases I may have missed.

GEODE-3127: add function execution to new client protocol.

---

geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegionMap.java
geode-core/src/main/java/org/apache/geode/internal/cache/map/RegionMapDestroy.java
geode-core/src/test/java/org/apache/geode/internal/cache/map/RegionMapDestroyTest.java

This change breaks up the monolithic RegionMapDestroy.destroy method into many methods.

GEODE-4397: refactor RegionMapDestroy destroy operation

---

geode-core/src/main/java/org/apache/geode/internal/offheap/DataType.java
geode-core/src/test/java/org/apache/geode/internal/offheap/DataTypeJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/offheap/OutOfOffHeapMemoryDUnitTest.java

One test was using the singletons just to confirm the cache had been shutdown. It was easy to change that test to not confirm the singleton was null but to instead ask if the test's cache was closed.
The other test was testing DataType which is product code that is only used by tests to inspect what is stored in offheap memory. The test was mocking the singleton methods because the product DataType was using the singleton to decode a serialized PDX. I changed DataType to just do less decoding of pdx. Now it will just say it was a pdx and give you the type number.

GEODE-4487: Remove singleton calls from offheap package

---

geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegionMap.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/RegionMapOwner.java
geode-core/src/main/java/org/apache/geode/internal/util/concurrent/ConcurrentMapWithReusableEntries.java
geode-core/src/main/java/org/apache/geode/internal/util/concurrent/CustomEntryConcurrentHashMap.java

Instead of looking up the waiting pool executor
from a singleton, it is now passed in based on
the owner of the AbstractRegionMap.

GEODE-4590: pass executor in to clear

---

geode-core/src/test/java/org/apache/geode/internal/cache/OplogJUnitTest.java

In turning on by default the new eviction algorithm, this test has begun intermittently failing. We want to continue having the new algorithm testing in the CI pipeline, so we will mark this test as flaky while we determine the root cause (and not cause the pipeline to be broken).

GEODE-4618: Mark test as flaky while root cause is investigated

---

geode-core/src/test/java/org/apache/geode/cache30/DiskRegionDUnitTest.java

These tests need to be rewritten so that they make valid assumptions about how our LRUs function.

GEODE-4629: Ignore tests that assume non-approximate LRU

---

geode-core/src/main/java/org/apache/geode/internal/shared/NativeCallsJNAImpl.java

getAnyInstance was being used to get the old logger.
Now the class declares a static log4j logger and uses it

GEODE-4583: remove getAnyInstance calls

---

geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java

- Since the default for "ack-severe-alert-threshold"
is zero, there is a code path where the target member
is null at the point of logging. So check for null.

GEODE-2569: Avoid unhelpful log message via a null check.

---

geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/management/JMXNotificationType.java
geode-core/src/main/java/org/apache/geode/management/internal/ManagementConstants.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/ManagementAdapter.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/ManagementListener.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/wancommand/DestroyGatewaySenderCommandDUnitTest.java

GatewaySender MX bean is unregistered when destroyed.

GEODE-3540: unable to gfsh destroy gateway-sender

---

geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySender.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheCreation.java

Changed getInternalDistributedSystem to throw an exception if it is called.
It appears that this method is never used on a CacheCreation but because this
class implements the InternalCache interface it has to have an implementation.

GEODE-4575: remove getAnyInstance call in CacheCreation

---

etc/eclipse-java-google-style.xml

This will preserve
```
/* A human readable block comment
* Does A
* Then B
* Then C
*/
```
when spotless is run, instead of it being reformatted to 
```
/* A human readable block comment Does A Then
* B Then C
*/
```
All existing comments are unaffected.
---
Left unsquashed until committing for ease of review.  
---
- [n/a - editor settings] Have you written or updated unit tests to verify your changes?
Please ensure that once the PR …

GEODE-4636: Update Style XML to allow human-readable spacing in comments

---

geode-core/src/test/java/org/apache/geode/cache/query/internal/types/TypeUtilsJUnitTest.java

@jujoramos 
It appears to be an intermittent thing, but passing `anyInt()` or similar argument matchers to non-mock classes can result in a test failing.  See the Travis for a recent PR of mine
https://travis-ci.org/apache/geode/builds/339119584?utm_source=github_status&utm_medium=notification
or the JIRA
https://issues.apache.org/jira/browse/GEODE-4642
I also refactored this class, drive predominantly by IDE inspections.  For instance, it's beyond the scope of this class to make sure that `new Boolean` returns a `Boolean`.  Consequently, there was a lot of unnecessary parameter boxing and variable instantiation only to call `.getClass()`.
Inner classes should not be interspersed with methods.  Put them either at the beginning or the end of the class, whichever is more appropriate for …

GEODE-4642: Remove PowerMock any() method calls from non-mock invocations.

---

geode-core/src/main/java/org/apache/geode/cache/Region.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ServerRegionProxy.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/RegisterInterestIntegrationTest.java

This PR is to deprecate and implement (non optimal) implementations of the new registerInterestAllKeys and registerInterestForKeys(Iterable).
Before releasing 2.0, we can then remove the warnings and the existing behavior.  We can also improve the implementation of registerInterestForKeys(Iterable) to pass the entire iterable to the server instead of registeringInterest per key from the client

GEODE-3813: Deprecating RegisterInterest ALL_KEYS and List behavior

---

docker/Dockerfile
docker/README.md

This also adds SHA256 and GPG verification of the downloaded binary artifacts.
See also https://github.com/docker-library/official-images/pull/3685#issuecomment-356382172 and the following discussion.
> I was able to use this to successfully launch the `gfsh` shell, and the resulting image is only ~184MB (thanks to being based on Alpine Linux).
>
> Doing something similar `FROM` the Debian-based `openjdk:8-jre-slim` image would be fairly trivial also (due to not having `apk add --virtual`, would require slightly more shell scripting to add/remove fetch dependencies, but not much).
- yep! GEODE-3921
- N/A
- N/A (updated docs, at least!)
- N/A, AFAIK

GEODE-3921 Adjust Dockerfile to be Alpine-based for size

---

geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/entries/AbstractRegionEntry.java
geode-core/src/test/java/org/apache/geode/internal/cache/eviction/TransactionsWithOverflowTest.java

When the transaction marks a region entry as no
longer being used by the transaction, it no longer
added it back to the eviction list if the entry
is removed or destroyed.

GEODE-4651: fix transactional destroy entry leak

---

geode-core/src/main/java/org/apache/geode/internal/cache/snapshot/ClientExporter.java
geode-core/src/main/java/org/apache/geode/internal/cache/snapshot/RegionSnapshotServiceImpl.java

The region is now used to obtain the InternalDistributedSystem
instead of calling getAnyInstance.

GEODE-4585: remove getAnyInstance call

---

ci/pipelines/develop.yml
ci/scripts/capture-call-stacks.sh

* Adjust capture-call-stacks.sh to handle non-dunit tests.
* Add callstacks capture to FlakyTest
- [ N/A ] If adding new dependencies to the code, are these dependencies licensed in a way that is …

[GEODE-4676] Add callstack processing to non-dunit tests.

---

geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/HARegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalCache.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/SearchLoadAndWriteProcessor.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheCreation.java
geode-core/src/test/java/org/apache/geode/pdx/PdxInstanceLoaderIntegrationTest.java

If a loader returns a PdxInstance, and if
the cache has pdx-read-serialized false,
then the PdxInstance is now deserialized
by calling PdxInstance.getObject.
So a "get" of a loaded PdxInstance will now
only be a PdxInstance if pdx-read-serialized
is true or if PdxInstance.getObject returns
a PdxInstance.

GEODE-4295: convert loaded PdxInstance

---

geode-core/src/test/java/org/apache/geode/cache/query/partitioned/PRBasicIndexCreationDeadlockDUnitTest.java
geode-core/src/test/java/org/apache/geode/cache/query/partitioned/PRColocatedEquiJoinDUnitTest.java
geode-core/src/test/java/org/apache/geode/cache/query/partitioned/PRQueryDUnitHelper.java

* Removed CacheFactory.getAnyInstance() from PRQueryDUnitHelper and PRColocatedEquiJoinDUnitTest
* Removed GemFireCacheImpl.getInstance() from PRBasicIndexCreationDeadlockDUnitTest

GEODE-4467: Removed instances of singleton usage

---

geode-core/src/test/java/org/apache/geode/test/dunit/standalone/ProcessManager.java

Removing debug flags from ProcessManager that aren't recognized by JDK
9.

GEODE-4671: Removing flags that aren't recognized by JDK 9

---

geode-core/src/main/java/org/apache/geode/internal/shared/NativeCalls.java
geode-core/src/main/java/org/apache/geode/internal/shared/NativeCallsJNAImpl.java

JDK9 logs a warning about doing reflection on these classes. The methods
doing the reflection are not being used.

GEODE-4670: Removing unused reflection of JDK methods

---

geode-core/src/test/java/org/apache/geode/management/internal/cli/NetstatDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/AlterCompressorDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ConnectCommandDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateAsyncEventQueueCommandDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateDefinedIndexesCommandDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ExportLogsOnServerManagerDUnit.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ExportLogsStatsDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ExportLogsWithMemberGroupDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/IndexCommandsShareConfigurationDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/util/MergeLogsDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/ClusterConfigStartMemberDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/ClusterConfigWithSecurityDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/security/MultiGfshDUnitTest.java
geode-core/src/test/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java
geode-core/src/test/java/org/apache/geode/test/dunit/rules/MemberVM.java
geode-core/src/test/java/org/apache/geode/test/dunit/rules/tests/ClusterStartupRuleCanSpecifyOlderVersionsDUnitTest.java
geode-core/src/test/java/org/apache/geode/test/junit/rules/MemberStarterRule.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsDUnitTest.java
geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/AlterRuntimeCommandDUnitTest.java
geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeConfigCommandDUnitTest.java
geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/ExportConfigCommandDUnitTest.java
geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/ExportLogsStatsOverHttpDUnitTest.java

* get rid of withTempWorkingDir in ClusterStartupRule
* cleanup more ClusterStartupRule API to use lamda on MemberStartupRule

GEODE-4180: get rid of withTempWorkingDir in ClusterStartupRule

---

geode-core/src/main/java/org/apache/geode/internal/cache/execute/util/FindRestEnabledServersFunction.java

* Removed InternalDistributedSystem.getAnyInstance() call from FindRestEnabledServersFunction in the package org.apache.geode.internal.cache.execute.util

GEODE-4579: Removed singleton instance

---

geode-core/src/test/java/org/apache/geode/memcached/ConnectionWithOneMinuteTimeoutFactory.java
geode-core/src/test/java/org/apache/geode/memcached/DomainObjectsAsValuesJUnitTest.java
geode-core/src/test/java/org/apache/geode/memcached/GemcachedDevelopmentJUnitTest.java
geode-core/src/test/java/org/apache/geode/memcached/IntegrationJUnitTest.java

The Gemcached tests were using the default timeout of 2.5 seconds.
Changing that to 1 minute.

GEODE-4968: Increasing the client timeout in Gemcached tests

---

geode-core/src/test/java/org/apache/geode/cache30/MultiVMRegionTestCase.java

Note that most of these diffs are indentation changes. "txId" needed to be final so I added some curly braces. The key changes in these areas was to use a Runnable to call assertCacheCallbackEvents

GEODE-4713: remote getInstance calls from from MultiVMRegionTestCase

---

geode-core/src/test/java/org/apache/geode/cache30/CacheSerializableRunnable.java
geode-core/src/test/java/org/apache/geode/cache30/CachedAllEventsDUnitTest.java
geode-core/src/test/java/org/apache/geode/cache30/CallbackArgDUnitTest.java
geode-core/src/test/java/org/apache/geode/cache30/ClientMembershipDUnitTest.java
geode-core/src/test/java/org/apache/geode/cache30/ClientServerCCEDUnitTest.java
geode-core/src/test/java/org/apache/geode/cache30/ClientServerTestCase.java
geode-core/src/test/java/org/apache/geode/cache30/DistributedNoAckRegionCCEDUnitTest.java
geode-core/src/test/java/org/apache/geode/cache30/ProxyDUnitTest.java
geode-core/src/test/java/org/apache/geode/cache30/RegionMembershipListenerDUnitTest.java
geode-core/src/test/java/org/apache/geode/cache30/RegionReliabilityTestCase.java
geode-core/src/test/java/org/apache/geode/cache30/TXOrderDUnitTest.java

GEODE-4464: Remove singleton calls from all tests in org.apache.geode.cache30

---

geode-core/src/test/java/org/apache/geode/internal/cache/control/TestMemoryThresholdListener.java

removed InternalDistributedSystem.getAnyInstance call
by using a static log4j logger

GEODE-4493: remove getAnyInstance calls from all tests in org.apache.geode.internal.cache.control

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImpl.java

Some tests wait for this callback to be notified of new locators before
killing old locators. But The callback is called before the internal
state on the client is updated. So there was a race condition where the
test would know about the new locator, but the client code itself would
not use it yet.

GEODE-3523: Update locatorDiscoveryCallback after updating state

---

geode-docs/tools_modules/gfsh/command-pages/alter.html.md.erb
geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb

- cache-listener, cache-loader, and cache-writer command-line
options can add a JSON specification to the fq class name that are
used to populate the init method's parameter for those classes
that implement Declarable
- see GEODE-4737 for the task to document what the JSON should
look like

GEODE-3915 Document use of JSON spec for gfsh create and alter region

---

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneEventListener.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/LuceneEventListenerJUnitTest.java

* In the lucene event listener's process events method the flag pdxReadSerialized is reset to the initial value then to rather change it to false.

GEODE-4725: PdxReadSerialized reset

---

geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneIndexMaintenanceIntegrationTest.java

* The assert check for the lucene commit checks have been modified to address the fact that it is not deterministic
* The reindex thread may be faster than the puts being done by the test hence the number of commits may different depending on whether the puts were faster or the reindexing thread.

GEODE-4745: Stat check asserts modified

---

geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/Failure.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/ProtobufOpsProcessor.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/AbstractFunctionRequestOperationHandler.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/PutRequestOperationHandler.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/security/AuthenticationRequestOperationHandler.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/state/ProtobufConnectionAuthorizingStateProcessor.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/state/exception/ExceptionWithErrorCode.java
geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/state/exception/OperationNotAuthorizedException.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/AuthenticationIntegrationTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/acceptance/LocatorConnectionAuthenticationDUnitTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/PutRequestOperationHandlerJUnitTest.java

Catching exceptions that happen before sending a response to the
protobuf client and sending an error message to the client instead of
closing the connection.
Cleaning up extraneous catch blocks.

GEODE-4746: Handle exceptions and return failures to protobuf clients

---

geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsDUnitTest.java

* Commit and update stats are removed as they are not deterministic.
* Depends when the afterPrimary or the Lucene bucket listeners are kicked off

GEODE-4740: Removed the stat checks

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListMembersCommand.java

Help string should be: Group name for which members will be displayed.

GEODE-4756: Restore the correct help string for the --group option

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/JdbcAsyncWriter.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/JdbcConnectorException.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/JdbcLoader.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/JdbcWriter.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/HikariJdbcDataSourceFactory.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/SqlHandler.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/TableKeyColumnManager.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/JdbcAsyncWriterTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/JdbcLoaderTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/JdbcWriterTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/SqlHandlerTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/TableKeyColumnManagerTest.java

* This runtime exception is used to warp failures in comminication with
an exernal database when using a JDBC data source

GEODE-4182: Add JdbcConnectorException

---

geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterConfigurationService.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java
geode-core/src/main/java/org/apache/geode/internal/cache/ClusterConfigurationLoader.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/ClusterConfigLocatorRestartDUnitTest.java
geode-core/src/test/java/org/apache/geode/test/junit/rules/MemberStarterRule.java

- This helps when a locator is reconnecting to the distributed system and isn't
fully ready yet.
- During reconnect, pass a fresh cache to the ClusterConfigurationService -
this fixes the 'DLock destroyed' issue.
- Also fixes GEODE-4730

GEODE-4765: Add retries when retrieving cluster config

---

geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneIndexMaintenanceIntegrationTest.java

* Lucene reindexing thread may be ahead of the put operation by the test
* The asyc event listener will still process the event.

GEODE-4767: Lucene stat assert modification

---

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/CreateLuceneCommandParametersValidator.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneServiceImpl.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneCreateIndexFunction.java
geode-lucene/src/main/resources/org/apache/geode/internal/sanctioned-geode-lucene-serializables.txt
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/ValidateCommandParametersTest.java

* Enum completedly moved to a new class
* Changed the name to CreateLuceneCommandParametersValidator
* Additional tests added to validate the Lucene index name.

GEODE-4696: Refactored validateCommandParameters

---

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneServiceImpl.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/LuceneServiceImplJUnitTest.java

* Don't add the aeq to the region until the data region has been created
* When iterating over list of local primary bucketIds (during reindexing), check for null return value when retrieving a specific bucket
* Added tests for same.

GEODE-4764: Address NPEs during Lucene index creation on existing region

---

geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterConfigurationService.java
geode-core/src/main/java/org/apache/geode/internal/cache/ClusterConfigurationLoader.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/FileUploader.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DeployFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/web/controllers/AbstractCommandsController.java

- This lets jar deployment work on Windows
- Unify creation of temporary staging directory

GEODE-4755: Use a more portable File permission API

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/JdbcConnectorException.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/JdbcLoader.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/JdbcWriter.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/TableKeyColumnManager.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/JdbcConnectorExceptionTest.java

* SQLExceptions that come from underlying sql drivers may not be availale
on clients or locators and will not be deserializable. When these
exceptions are contained in a JdbcConnectorException, the stack trace
is instead converted to a string to ensure safe serialization

GEODE-4266: Make JdbcConnectionException safely serializable to clients

---

ci/docker/Dockerfile
ci/scripts/concourse_job_performance.sh

* install python3 and python3-pip. …

[GEODE-4835] Add python3 to ci docker image.

---

geode-core/src/main/java/org/apache/geode/internal/process/MBeanOrFileProcessController.java
geode-core/src/main/java/org/apache/geode/internal/process/ProcessControllerFactory.java
geode-core/src/test/java/org/apache/geode/internal/process/ProcessControllerFactoryIntegrationTest.java
geode-core/src/test/java/org/apache/geode/internal/process/ProcessControllerFactoryTest.java

The MBeanProcessController has some logic to attach to a started locator
or server process and look for the location of JDK jars. Under JDK 9,
this logic does not work.
This fix allows us to fall back on the FileProcessController if the
mbean one fails, rather than silently hanging forever.

GEODE-4669: Fall back on file controller if mbean controller fails

---

geode-core/src/test/java/org/apache/geode/internal/cache/wan/GatewayReceiverXmlParsingValidationsJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/wan/parallel/WaitUntilParallelGatewaySenderFlushedCoordinatorJUnitTest.java

* WaitUntilParallelGatewaySenderFlushedCoordinatorJUnitTest marked as WanTest.
* This was missed when the tests in geode-wan module was categorized.

GEODE-4797: Categorized WanTest

---

geode-assembly/src/test/java/org/apache/geode/tools/pulse/PulseConnectivityTest.java
geode-assembly/src/test/java/org/apache/geode/tools/pulse/PulseDataExportTest.java
geode-assembly/src/test/java/org/apache/geode/tools/pulse/PulseJmxPasswordFileTest.java
geode-assembly/src/test/java/org/apache/geode/tools/pulse/PulseSecurityIntegrationTest.java
geode-assembly/src/test/java/org/apache/geode/tools/pulse/PulseSecurityTest.java
geode-assembly/src/test/java/org/apache/geode/tools/pulse/PulseSecurityWithSSLTest.java
geode-junit/src/main/java/org/apache/geode/test/junit/categories/PulseTest.java
geode-pulse/src/test/java/org/apache/geode/tools/pulse/controllers/PulseControllerJUnitTest.java

Created PulseTest interface for annotating tests.
Added the new Category annotation for Pulse Intergration tests.
Added the SecurityTest annotation for Pulse tests that included security
features.

GEODE-4785: Add test category annotation to Pulse tests

---

geode-core/src/main/java/org/apache/geode/internal/cache/ColocationListener.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionRegionConfig.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/PartitionRegionConfigJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionCreationJUnitTest.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/IndexRepositoryFactory.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneFileRegionColocationListener.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneServiceImpl.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/PartitionedRepositoryManager.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/RawIndexRepositoryFactory.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/RawLuceneRepositoryManager.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/test/IndexRepositorySpy.java

* PartitionRegion can now add a colocation listener to itself which is triggered when the colocation is completed.
* Lucene indexRepositoryFactory adds colocation complete listener to the file region
* when the colocation of the file region is completed the compute repository is called

GEODE-4689: Colocation complete listeners added

---

geode-core/src/main/java/org/apache/geode/internal/cache/FilterProfile.java
geode-core/src/test/java/org/apache/geode/internal/cache/FilterProfileNullCqBaseRegionJUnitTest.java

* Log level set to info when FilterProfile gets an exception while registering CQ
* Before, when there is an exception while registering cq like while cache closing the cq's base region is null
* There is an exception which is logged in debug level but execution continues and adds the cq to the cp map with base region set to null
* This results in a NullPointerException while closing cq as methods are executed on null region
* Now the operation to put the cq into the cq map is inside a if check for null cq base region. …

GEODE-4827: CQ should not be added to cq map on exception

---

geode-core/src/test/java/org/apache/geode/internal/cache/wan/AsyncEventQueueTestBase.java
geode-wan/src/test/java/org/apache/geode/internal/cache/UpdateVersionDUnitTest.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/CacheClientNotifierDUnitTest.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/Simple2CacheServerDUnitTest.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/WANTestBase.java

This change is to start locator members with LOCATOR_DM_TYPE using the InternalLocator.FORCE_LOCATOR_DM_TYPE system property. This is the same property that InternalLocator startLocator uses. This affects several DUnit tests.
I did some refactoring as part of this change.
AsyncEventQueueTestBase - changed to use system property
UpdateVersionDUnitTest - changed to use system property and  also a bunch of refactoring to reduce duplicate code
CacheClientNotifierDUnitTest - changed to make the locator member just a locator and not create regions also
Simple2CacheServerDUnitTest - same as CacheClientNotifierDUnitTest
WANTestBase - changed to use system property and also a bunch of refactoring to reduce duplicate code

GEODE-4815: Forced test locator members to be LOCATOR_DM_TYPES

---

geode-core/src/test/java/org/apache/geode/management/JMXMBeanDUnitTest.java
geode-core/src/test/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java
geode-cq/src/test/java/org/apache/geode/security/ClientCQAuthDUnitTest.java

Move dunit launch from constructor to before in ClusterStartupRule.
Precheckin is still running but I did confirm that these tests pass by running them individually:
* org.apache.geode.management.internal.cli.commands.ShowLogCommandDUnitTest
* org.apache.geode.internal.cache.rollingupgrade.RollingUpgradeDUnitTest
* org.apache.geode.security.ClientAuthenticationPart2DUnitTest
* org.apache.geode.cache.lucene.LuceneCommandsSecurityDUnitTest
* org.apache.geode.management.internal.configuration.ClusterConfigurationIndexWithFromClauseDUnitTest
* org.apache.geode.internal.cache.tier.sockets.ClientServerMiscBCDUnitTest
* org.apache.geode.cache.lucene.LuceneSearchWithRollingUpgradeDUnit
* org.apache.geode.cache.wan.WANRollingUpgradeDUnitTest
* …

GEODE-4885: launch DUnit from before instead of constructor

---

geode-core/src/test/java/org/apache/geode/internal/cache/CacheWriterGetOldValueIntegrationTest.java

* Use TemporaryFolder for DiskStore.
* Use TestName to create uniquely named Region.

GEODE-4832: use TemporaryFolder in CacheWriterGetOldValueIntegrationTest

---

geode-core/src/main/java/org/apache/geode/internal/cache/FilterProfile.java

* While the servers are shutting down, getInstance may result in a null cache.
* This may result in NPE.
* NULL checks are added.

GEODE-4827: null check for the cache.

---

geode-core/src/main/java/org/apache/geode/management/cli/GfshCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/InternalGfshCommand.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/GfshCommandJUnitTest.java

- Remove unnecessary findMembersWithAsyncEventQueue method which was
inadvertently included.

GEODE-4943: Move isConnectedAndReady method to public class

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/SqlHandler.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/SqlToPdxInstanceCreator.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/JdbcDUnitTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/JdbcLoaderIntegrationTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/SqlHandlerTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/SqlToPdxInstanceCreatorTest.java

When writing a java.util.Date the column type will be used
to convert it to a java.sql.Date, java.sql.Time, or java.sql.Timestamp.
When reading a pdx DATE field, the column type will be used to
decide if getDate, getTime, or getTimestamp is called.
When reading a pdx OBJECT field, if getObject returns an instance of
java.sql.Date, java.sql.Time, or java.sql.Timestamp then it will be
converted to java.util.Date and that will be stored in the pdx field.
email …

GEODE-4922: handle Date conversion

---

geode-core/src/main/java/org/apache/geode/cache/AttributesFactory.java
geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreAttributes.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/persistence/DefaultDiskDirs.java
geode-core/src/main/java/org/apache/geode/internal/cache/persistence/InternalDiskStoreFactory.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheXmlGenerator.java
geode-core/src/main/java/org/apache/geode/internal/lang/SystemPropertyHelper.java
geode-core/src/test/java/org/apache/geode/internal/cache/PRAccessorWithOverflowRegressionTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/persistence/DefaultDiskDirsIntegrationTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/persistence/DefaultDiskDirsTest.java
geode-core/src/test/java/org/apache/geode/test/dunit/rules/DistributedDiskDirRule.java
geode-core/src/test/java/org/apache/geode/test/junit/rules/DiskDirRule.java
geode-junit/src/main/java/org/apache/geode/test/junit/rules/DescribedExternalResource.java
geode-junit/src/main/java/org/apache/geode/test/junit/rules/serializable/SerializableTemporaryFolder.java
geode-junit/src/main/java/org/apache/geode/test/junit/rules/serializable/SerializableTestName.java

* System property geode.defaultDiskDirs is used to specify some dir
other than "."
* DiskDirRule can be used by IntegrationTests
* DistributedDiskDirRule can be used by DistributedTests
* Update BucketRegionSizeWithOverflowRegressionTest to use
DistributedDiskDirRule

GEODE-4929: Add ability for tests to overide the default DiskDirs

---

geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpServer.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/AcceptorImpl.java
geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
geode-core/src/main/java/org/apache/geode/internal/tcp/TCPConduit.java
geode-core/src/test/java/org/apache/geode/internal/net/DummySocketCreator.java
geode-core/src/test/java/org/apache/geode/internal/net/SSLSocketIntegrationTest.java
geode-core/src/test/java/org/apache/geode/internal/net/SocketCreatorJUnitTest.java

Also close newly accepted sockets in TcpConduit.run() if SSL configuration fails (or any other IOException).
I'm not sure the best way to test the `run()` method itself, so I haven't attempted it here. l'm not sure what the best way to do that is and leaks are hard to test in general. Let me know if you have ideas.

GEODE-3563: use a timeout for newly created sockets in TcpConduit.run()

---

geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/HARegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalCache.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/SearchLoadAndWriteProcessor.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheCreation.java
geode-core/src/test/java/org/apache/geode/internal/cache/DistributedRegionSearchLoadJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/SearchLoadAndWriteProcessorTest.java
geode-core/src/test/java/org/apache/geode/pdx/PdxInstanceLoaderIntegrationTest.java

The preferCD flag is now passed down to convertPdxInstanceIfNeeded.
If preferCD is true then the caller wants the serialized form back
from the load and in that case the PdxInstances bytes are wrapped
in a PreferBytesCachedDeserializable and it is returned.
So now the PdxInstance will only be deserialized if a local get is
done and pdx-read-serialized is false.

GEODE-4840: do not deserialize PdxInstances for remote gets

---

extensions/geode-modules-tomcat8/build.gradle
geode-core/build.gradle
geode-old-client-support/build.gradle
geode-old-versions/build.gradle
geode-old-versions/src/main/java/org/apache/geode/test/dunit/standalone/VersionManager.java
geode-old-versions/src/test/java/org/apache/geode/test/dunit/standalone/VersionManagerJUnitTest.java
geode-protobuf/build.gradle
geode-web/build.gradle

- This will facilitate other modules being able to use VersionManager;
specifically geode-junit.

GEODE-4972: Move VersionManager to geode-old-versions module

---

build.gradle

- This version is forked at
github.com/jdeppe-pivotal/gradle-dockerized-test-plugin and the artifacts
have been published to s3://geode-maven.

GEODE-5024: Use debug version of gradle-dockerized-test-plugin

---

geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneClientSecurityDUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneClientSecurityWithRegionCreatedBeforeIndexDUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneCommandsSecurityDUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneCommandsSecurityWithRegionCreatedBeforeIndexDUnitTest.java

* Extended existing tests with and without gfsh to create region prior to creating lucene index.

GEODE-4909: Additional lucene reindex tests with security

---

geode-core/src/main/java/org/apache/geode/internal/cache/PartitionRegionConfig.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/RegionAlterFunction.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneServiceImpl.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneIndexCreationDUnitTest.java
geode-wan/src/test/java/org/apache/geode/management/internal/configuration/WANClusterConfigurationDUnitTest.java

* Alter region to add a new gateway sender will update the PartitionRegionConfig
* This will  allow validateParallelGatewaySenderIds to be executed in alter region command and not just create region
* This will prevent gateway senders to be added to non colocated regions

GEODE-4919: Alter region will update PRConfig

---

geode-core/src/main/java/org/apache/geode/distributed/internal/InternalClusterConfigurationService.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java
geode-core/src/main/java/org/apache/geode/internal/cache/ClusterConfigurationLoader.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/functions/GetClusterConfigurationFunction.java
geode-core/src/test/java/org/apache/geode/internal/cache/ClusterConfigurationLoaderIntegrationTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/functions/GetClusterConfigurationFunctionTest.java

GEODE-4990: Cluster Config StartUp Race Condition
- Added unit test for `GetClusterConfigurationFunction`.
- Added integration tests for `ClusterConfigurationLoader`.
- Set 'InternalLocator.isSharedConfigurationEnabled()' visibility
as `public`.
- Set `ClusterConfigurationLoader.requestConfigurationFromOneLocator()`
visibility as `protected`.
- `GetClusterConfigurationFunction` now throws an exception if the
cluster configuraiton service is not enabled on the locator.
- `GetClusterConfigurationFunction` now returns null if the cluster
configuraiton service is enabled but not yet started. The caller can
decide whether to retry or fail fast.
to ensure the following steps …

GEODE-4990: Cluster Config StartUp Race Condition

---

gradle/test.gradle

- Exclude distributed tests from using java.io.tmpdir as they appear
to need /tmp.

GEODE-5035: Explicitly pass java.io.tmpdir to JVMs invoked by Gradle.

---

geode-core/src/main/java/org/apache/geode/cache/configuration/CacheConfig.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalClusterConfigurationService.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateJndiBindingCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeJndiBindingCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ExportImportClusterConfigurationCommands.java
geode-core/src/test/java/org/apache/geode/distributed/internal/InternalClusterConfigurationServiceTest.java

fixed a bug in getCacheConfig and updateCacheConfig
to support non-existing group
Signed-off-by: Jinmei Liao <jiliao@pivotal.io>

GEODE-4856: Public API for retrieving/persisting Cluster Configuration

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/json/GfJsonObject.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/result/CommandResult.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateDefinedIndexesCommandTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateIndexCommandTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeRegionDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeRegionJUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListJndiBindingCommandDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ShowMetricsJUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/lifecycle/GfshStatusCommandsIntegrationTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/result/ResultBuilderTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/ClusterConfigImportDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/security/GfshCommandsSecurityTest.java
geode-core/src/test/java/org/apache/geode/management/internal/security/MultiGfshDUnitTest.java
geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshCommandRule.java

- Methods getGfJsonObject() and getTableContent() are now private.
- getContent() is still public but only used by CommandResponseBuilder. This
will change in subsequent PRs.

GEODE-5069: Reduce direct exposure of GfJsonObject from CommandResult

---

geode-docs/getting_started/installation/install_standalone.html.md.erb
geode-docs/getting_started/system_requirements/host_machine.html.md.erb

- Also updated a few places that called out a specific version 8
update, and changed them to use a variable instead of a specific
version
- Found a typo in a Windows set JAVA_HOME command.  It needed double quotes due to a space in the path name.

GEODE-5086 Clarify docs: we need version 8 Java

---

ci/scripts/update-passing-ref.sh

When we update the passing reference file, display the SHA, and ensure the file isn't cached. …

GEODE-5104 - Output git SHA when updating passing reference file.

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/OriginalServerConnection.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ProtobufServerConnection.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionFactory.java
geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/ProtobufChannel.java
geode-protobuf/src/test/java/org/apache/geode/internal/cache/tier/sockets/OutputCapturingServerConnectionTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/cache/tier/sockets/ProtobufServerConnectionTest.java

Based on the stats all protobuf requests and responses were being sent
as two packets. Using a BufferedOutputStream to make sure we only send 1
packet

GEODE-5043: Buffering protobuf output to avoid multiple packet sends

---

geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneSearchWithRollingUpgradeDUnit.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneSearchWithRollingUpgradeReindexFlagEnabledDUnitTest.java

* Lucene Rolling upgrade tests are now executed with the reindex flag enabled

GEODE-5102: Lucene rolling test with REINDEX

---

geode-docs/reference/statistics_list.html.md.erb

New statistics are
- eventsDroppedDueToPrimarySenderNotRunning
- eventsProcessedByPQRM

GEODE-4624 Add docs for 2 new gateway sender statistics

---

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/PartitionedRepositoryManager.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/distributed/LuceneQueryFunction.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/repository/RepositoryManager.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneSearchWithRollingUpgradeDUnit.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/distributed/LuceneQueryFunctionJUnitTest.java

* If all the servers are above the 1.6.0 version then the LuceneIndexCreationInProgressException will be propogated up to the servers
* If there are servers which are lower than 1.6.0 then get repository will be re-executed but it will wait till the indexes are available.

GEODE-5055: Handle index creation in progress.

---

geode-lucene/src/main/java/org/apache/geode/cache/lucene/LuceneIndex.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneIndexForPartitionedRegion.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneRawIndex.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommands.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexDetails.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexStatus.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneListIndexFunction.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/xml/LuceneIndexCreation.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/xml/LuceneIndexXmlGenerator.java
geode-lucene/src/main/resources/org/apache/geode/internal/sanctioned-geode-lucene-serializables.txt
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsDUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsJUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsWithReindexAllowedDUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneListIndexFunctionJUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/configuration/LuceneClusterConfigurationDUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/xml/LuceneIndexXmlGeneratorJUnitTest.java

* list lucene index gfsh command will now display on of three states
* NOT_INITIALIZED if the index is present in only in defined map
* INITIALIZED if the index is present in the index map
* INDEXING_IN_PROGRESS if the index creation is in progress.

GEODE-5047: list lucene index result modified

---

geode-core/src/main/java/org/apache/geode/internal/Assert.java
geode-core/src/test/java/org/apache/geode/distributed/LocatorDUnitTest.java
geode-core/src/test/java/org/apache/geode/distributed/LocatorUDPSecurityDUnitTest.java

There's not a whole lot going on here but I got mad at deprecated code and some no-longer-best-practices and decided to do some cleanup.
* Extend timeout to account for issues in CI
* Remove usage of Assert.fail()
* Don't use invoke try-catch-throw paradigm.
* Remove dead code

GEODE-2542: Extend timeouts from 10s to 30; cleanup

---

geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledIteratorDef.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/QueryMonitor.java
geode-core/src/test/java/org/apache/geode/cache/query/internal/index/EquiJoinIntegrationTest.java
geode-cq/src/test/java/org/apache/geode/cache/query/dunit/QueryMonitorDUnitTest.java
geode-cq/src/test/java/org/apache/geode/internal/cache/ha/CQListGIIDUnitTest.java

* Modified product to have cq's ignore the query timeout - not sure if that was expected originally, from the tests it sounds like it shouldn't have been
* Was wrapping cancelled exceptions in TypeMismatch exceptions under certain scenarios
* Enabled ignored tests and removed flaky tag
* Removed creating an instance of a different test inside this test case
* Tests can be further pruned and refactored but this was a first step
* Removed some queries combinations that shouldn't be the responsibility of the QueryMonitorDUnitTest to test …

GEODE-577: Refactored QueryMonitorDUnitTest to use new rules

---

geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpServer.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/AcceptorImpl.java
geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
geode-core/src/main/java/org/apache/geode/internal/tcp/TCPConduit.java
geode-core/src/test/java/org/apache/geode/internal/net/DummySocketCreator.java
geode-core/src/test/java/org/apache/geode/internal/net/SSLSocketIntegrationTest.java
geode-core/src/test/java/org/apache/geode/internal/net/SocketCreatorJUnitTest.java

Modified the handshake method to establish a timeout and revert it when done.
Added testing to ensure the timeout is being established and honored.

GEODE-3563 SSL socket handling problems in TCPConduit run

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/AlterConnectionCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/AlterMappingCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateConnectionCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyConnectionCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyMappingCommand.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/AlterConnectionCommandTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/AlterConnectionFunctionTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/AlterMappingCommandTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/AlterMappingFunctionTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/CreateConnectionFunctionTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingFunctionTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeConnectionFunctionTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingFunctionTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyConnectionFunctionTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyMappingCommandFunctionTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/ListConnectionFunctionTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/ListMappingFunctionTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/CliFunctionResult.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/CreateIndexFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/result/ResultBuilder.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/result/model/ResultModel.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateIndexCommandDUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateJndiBindingCommandTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyJndiBindingCommandTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommandTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/CliFunctionResultTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/GatewayReceiverCreateFunctionTest.java
geode-core/src/test/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt

- The intention of this is to avoid needing to pass 'skip-if-exists' or
'if-not-exists' flags to any command function. The function should set this
flag if it determines that the construct it is dealing with either already
exists or does not exist depending on the action. The calling command will
then be able to use this information to display and set status appropriately.

GEODE-5206: Add an 'ignoreFailure' flag to CliFunctionResult

---

geode-core/src/main/java/org/apache/geode/pdx/internal/ClientTypeRegistration.java
geode-core/src/main/java/org/apache/geode/pdx/internal/LonerTypeRegistration.java
geode-core/src/main/java/org/apache/geode/pdx/internal/NullTypeRegistration.java
geode-core/src/main/java/org/apache/geode/pdx/internal/PeerTypeRegistration.java
geode-core/src/main/java/org/apache/geode/pdx/internal/TypeRegistration.java
geode-core/src/main/java/org/apache/geode/pdx/internal/TypeRegistry.java
geode-core/src/test/java/org/apache/geode/cache/query/dunit/PdxQueryDUnitTest.java
geode-core/src/test/java/org/apache/geode/distributed/internal/membership/gms/MembershipManagerHelper.java
geode-core/src/test/java/org/apache/geode/pdx/PdxSerializableJUnitTest.java

* Add @Deprecated to a test hook in the hope that others won't accidentally use it.
* delete some comments and make some methods less public
It would nice to get a second pair of eyes to approve the last commit, which changes a test in a way that should be safe.

GEODE-5208 remove test hooks from TypeRegistration

---

geode-core/src/main/java/org/apache/geode/cache/wan/GatewaySender.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java
geode-test/src/main/java/org/apache/geode/test/dunit/rules/MemberVM.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/misc/WANConfigurationJUnitTest.java
geode-wan/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandDUnitTest.java

- Added unit and distribution tests.
- Squashed all changes derived from reviews.
- Removed references to old bug tracking system.
- Removed unused `throws Exception` clause from `MemberVM.waitTilGatewaySendersAreReady()`.
- `DistributedRegion` creation fails ealier whenever the associated `async-event-queue` / `gateway-sender` is configured as `parallel`.
- Added `InternalRegion.preInitialize` method to execute validation before initializing the region, empty implementation by default.
submit an update to your PR as soon as possible. If …

GEODE-5220: Validate Region Attributes Earlier

---

geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/acceptance/CacheMaxConnectionJUnitTest.java

- ran 210 passes which revealed nothing
- talked to other developers and learned that there have been a number of changes since original bug
- Removing flaky flag in order to get it back into test. …

GEODE-3733: Removed flaky flag

---

geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/acceptance/CacheMaxConnectionJUnitTest.java

- a new fixed thread pool was being allocated but not shutdown. This fixes that omission.
@upthewaterspout @WireBaron @galen-pivotal @bschuchardt @PivotalSarge

GEODE-5250: Repaired a threadpool leak

---

geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegionMap.java
geode-core/src/main/java/org/apache/geode/internal/cache/map/RegionMapDestroy.java
geode-core/src/test/java/org/apache/geode/internal/cache/AbstractRegionMapTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/map/RegionMapDestroyTest.java

A number of places existed in which even though the entry had already been destroyed; it could be destroyed again. In those cases the statistic would decremented an extra time.
In one place the stat was incremented when doing txApplyDestroy even though an entry was not being added to the region.
Unit tests were added for all these places that failed before the code was fixed.
@dhemery

GEODE-5265: fix dataStoreEntryCount statistic

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/PooledConnection.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/pooling/PooledConnectionJUnitTest.java
geode-wan/src/main/java/org/apache/geode/internal/cache/wan/GatewaySenderEventRemoteDispatcher.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/GatewaySenderEventRemoteDispatcherJUnitTest.java

* Shutting down the ackThreadReader on stop processing.
* closing the input stream on closing the connection by stomper thread.

GEODE-5270: Closing the connection.

---

geode-core/src/main/java/org/apache/geode/internal/cache/execute/FunctionStreamingResultCollector.java

* ForceReattemptException is not wrapped in another ForceReattemptException.

GEM-2068: Prevent unnecessary chaining of exception.

---

geode-core/src/main/java/org/apache/geode/management/internal/beans/ManagementAdapter.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/ManagementListener.java
geode-core/src/test/java/org/apache/geode/management/internal/beans/ManagementAdapterTest.java

Fixed a race condition which causes creation of MBeans to fail while
handling resource lifecycle change notifications.
* A readwrite lock is added to synchronize between handling notifications
of cache creation/removal and handling other notifications.
* Added a test which to test the synchronization for a fixed amount of time.

GEODE-5252: Race in management adapter could fail to create MXBeans.

---

geode-cq/src/test/java/org/apache/geode/cache/query/dunit/QueryMonitorDUnitTest.java

* Reducing the timeout as running the tests on faster machines resulted in the query being completed before the timeout

GEODE-577: Reducing the timeout

---

geode-core/src/main/java/org/apache/geode/cache/query/internal/ResultsCollectionPdxDeserializerWrapper.java
geode-core/src/test/java/org/apache/geode/cache/query/PdxStringQueryJUnitTest.java
geode-core/src/test/java/org/apache/geode/cache/query/dunit/PdxQueryDUnitTest.java

GEODE-5290: Fixes NPE with default constructor of ResultsCollectionPdxDeserializerWrapper and getting an iterator from it.
Additionally adds a test to validate that for aggregate queries(`SUM`, `AVERAGE`, `COUNT` etc) with no results, `results.asList()` does not result in an error as reported by a user.

GEODE-5290: Fixes NPE with ResultsCollectionPdxDeserializerWrapper

---

geode-core/src/main/java/org/apache/geode/internal/cache/DiskRegion.java
geode-core/src/test/java/org/apache/geode/cache/ConcurrentRegionOperationIntegrationTest.java

For a region that has been configured with off-heap storage and overflow
to disk, memory can be leaked if
- region clear
- region destroy
- region replace
all happen concurrently. The root cause appears to be region clear
modifying entries for values stored on disk without synchronizing the
entries. This prevents replace from freeing the off-heap memory for the
new value when the replace fails because the region is being destroyed.
This commit adds an integration test that uses spies on a region entry
to trigger the concurrent events during a replace operation and checks
for orphaned off-heap memory.
The proposed fix is to not modify the region entries on disk while
performing a clear operation.
Signed-off-by: Dan Smith <dsmith@pivotal.io>
Thank you for submitting a contribution to Apache …

GEODE-5292: Fix memory leak for off heap regions with overflow

---

geode-core/src/main/java/org/apache/geode/internal/cache/ProxyBucketRegion.java

[GEODE-5301]
If Geode member is disconnected, it will throw DistributedSystemDisconnectedException, instead of an assertion error at ProxyBucketRegion.setBucketRegion().

GEODE-5301: Check readiness and closed before assertion

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateDefinedIndexesCommand.java
geode-wan/src/test/java/org/apache/geode/management/internal/configuration/ClusterConfigurationIndexWithFromClauseDUnitTest.java

* Incase of entrySet being used in the from clause while defining an index
* the region name extracted should not include entrySet part.
* Including the entrySet causes updates to cluster config to fail.

GEODE-5318: Extract the valid region name

---

geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshCommandRule.java
geode-core/src/test/java/org/apache/geode/test/junit/rules/MemberStarterRule.java
geode-wan/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandDUnitTest.java

CreateRegionCommandDUnit test contained a race condition that caused a
test to fail if the GatewaySenders were created faster than the 100ms
poll rate of Awaitility. We actually expect two GatewaySenders, one for
each server in the cluster.
The wait was updated to use an assertion for better error messages when
the test fails.
[#158341308]
Co-Authored-by: Bradford D. Boyle <bboyle@pivotal.io>

Update expected number of gateway senders

---

geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshCommandRule.java

Move creation of temp folder to a helper method and call from no-arg
constructor and before. The creation of the folder is idempotent so it
can be called multiple times. Calling this method in before() allows
tests to be run multiple times in IntelliJ.

Create temp folder in two places

---

geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/JdbcDistributedTest.java
geode-core/src/test/java/org/apache/geode/security/ClientAuthDUnitTest.java
geode-core/src/test/java/org/apache/geode/security/ClientAuthorizationLegacyConfigurationDUnitTest.java
geode-core/src/test/java/org/apache/geode/security/ClientDataAuthorizationUsingLegacySecurityDUnitTest.java
geode-core/src/test/java/org/apache/geode/security/ClientDataAuthorizationUsingLegacySecurityWithFailoverDUnitTest.java
geode-core/src/test/java/org/apache/geode/test/dunit/SerializableConsumerIF.java
geode-core/src/test/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java
geode-core/src/test/java/org/apache/geode/test/dunit/rules/tests/ClusterStartupRuleCanSpecifyOlderVersionsDUnitTest.java
geode-cq/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeClientCommandDUnitTest.java

Adds a `SerializableConsumerIF` which helps with creating Serializable version of Lamdba expressions. For eg, a client calling the rule this way:
```
startupRule.startClientVM(2, new Properties(), (Serializable & Consumer<ClientCacheFactory>) cf -> {
...
})
```
can do this instead now:
```
startupRule.startClientVM(2, new Properties(), cf -> {
...
})
```

GEODE-5332: Introduces Serializable version of Consumer - for ClusterStartupRule

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/ConnectionConnector.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ConnectionFactoryImpl.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/ConnectionConnectorTest.java

Added unit test for new functionality in ConnectionConnector
Refactored ConnectionFactoryImpl, ConnectionConnector, and
ClientSideHandshakeImpl improve testability of ConnectionConnector

GEODE-5333: Destroy failed connection in ConnectionConnector

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/NetstatFunction.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/NetstatDUnitTest.java

- This avoids long command pauses (or failures) if DNS is slow or
misconfigured.
- Add more netstat tests

GEODE-5335: Do not resolve addresses when calling netstat and lsof

---

geode-docs/developing/transactions/about_transactions.html.md.erb

I welcome reviews and input from the wider Geode community on this PR.  It replaces the introductory doc material on transactions with updated prose.  I attempted to revise this prose to be useful for app developers. I hope that reviewers will weigh in on technical accuracy and identify items that are missing from this introductory prose.

GEODE-5296 Rewrite introductory prose on transactions

---

geode-docs/developing/expiration/configuring_data_expiration.html.md.erb
geode-docs/managing/statistics/chapter_overview.html.md.erb
geode-docs/managing/statistics/how_statistics_work.html.md.erb
geode-docs/managing/statistics/setting_up_statistics.html.md.erb
geode-docs/tools_modules/gfsh/command-pages/alter.html.md.erb
geode-docs/tools_modules/gfsh/command-pages/start.html.md.erb

level to differentiate between 'statistics' at the Server or Cluster level, which if enabled will NOT allow Expiration functionality.

GEODE-5350: User Guide: Specifying that 'statistics-enabled' parameter for region

---

ci/pipelines/deploy_meta.sh
ci/pipelines/meta.yml
ci/pipelines/pull-request/base.yml
ci/pipelines/pull-request/deploy_pr_pipeline.sh
ci/pipelines/pull-request/pr-template.yml
ci/scripts/build.sh
ci/scripts/test-archive.sh
ci/scripts/test-run.sh

Single pipeline that runs all GitHub PRs. Status of each job is posted
back as a 'status' to the commit of the PR as they complete, like
Travis.
Runs in parallel.
PRs have links directly to their job in Concourse.
I hate yaml.
So close no matter how far
Couldn't be much more from the heart
forever trusting who we are
and whitespace just matters.

GEODE-5380: create PR pipeline that integrates with GitHub pull requests

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/AcceptorImpl.java

Using shutdownNow interrupts the threads in these pools. These threads
may be doing IO on sockets, so shutdownNow will interrupt the threads
and potentially cause issues shutting down.

GEODE-5360: Removing the use of shutdownNow from AcceptorImpl pools

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsUtils.java

If you edit the gfsh script to specify a custom log4j2 xml
configuration file, this change will propagate that custom
config file to any forked disk store commands.

GEODE-5430: Allow disk store commands to use custom log4j2 config

---

ci/docker/initdocker

Current versions of docker have an issue under linux causing it to fail.
This workaround addresses the problem. Once Docker fixes the problem on
their end this might need to be removed.

[GEODE-5378] Adjust initdocker script to implement workaround.

---

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ConcurrentDeployDUnitTest.java

the most recent failure is a legitimate failure which was later corrected. Removing the flaky category for this test.

GEODE-4803: remove flaky category

---

geode-wan/src/test/java/org/apache/geode/internal/cache/wan/WANTestBase.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/disttx/DistTXWANDUnitTest.java

Check that the data is propagated through WAN before checking the
status of the event queues. This test was flaky because the event queues
were being checked before the events had been added to the event queue,
so the queue was changing as it was being checked. By checking that the
data has been propaged to the other cluster first, we can know that all
events have been added.
email to …

GEODE-5383: Check that data propagated earlier

---

geode-core/src/test/java/org/apache/geode/cache/ConcurrentRegionOperationIntegrationTest.java

This theoretically fixes a broken test.
Signed-off-by: Dan Smith <dsmith@pivotal.io>

[GEODE-5292] Actually destroy the region instead of pretending to.

---

geode-docs/tools_modules/gfsh/command-pages/remove.html.md.erb

In addition to documenting that the --all option is not available for use with partitioned regions:
- removed an unneeded table caption
- removed an incorrect "error" message
- revised region names so they did not specify subregions in the example commands

GEODE-5408 Update docs for gfsh remove --all

---

build.gradle
geode-old-versions/build.gradle

GEODE-5423 Defer download and copy tasks to execution stage of Gradle
Custom tasks for fetching and unpacking geode-old-versions was doing
filesystem work during configure, every time a build was executed,
regardless of changes or targets requested. Reorganizing this task and
its dependencies several benefits:
- moves the blocking IO heavy operation into the execution stage
- allows parallel tasks to execute during the download and unzip
- does not do IO checks for non-build targets like `gradlew tasks`
- will not re-trigger the task on subsequent builds …

GEODE-5423 gradle configuration is much faster

---

ci/pipelines/pull-request/base.yml
ci/pipelines/pull-request/deploy_pr_pipeline.sh
ci/pipelines/pull-request/pr-template.yml

Add tags to PR pipeline jobs so that they will run on separately
allocated workers. Also limit the number of instances of a given job in
the PR pipeline to 5.

[GEODE-5427] Isolate PR pipeline jobs from other pipelines.

---

geode-docs/managing/security/implementing_authorization.html.md.erb

gfsh commands that needed permission levels listed:
create jndi-binding
describe jndi-binding
destroy jndi-binding
list jndi-binding
@kattino Would you please review this PR?

GEODE-4965 Add gfsh/jndi-binding permission levels to docs

---

geode-core/src/test/java/org/apache/geode/cache/ConcurrentRegionOperationIntegrationTest.java

This test was modifying the concurrent region map to introduce a spy,
but there was a concurrent thread overflowing entries to disk at the
same time. An interaction between the spy and the async flush caused the
ref count to go to 0, and the test to fail before it even got to the
point of clearing the region.
Flushing the disk before introducing the spy.
@balesh2 @FSOUTHERLAND

 GEODE-5292: Flushing to disk in test before introducing spy in test

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentRecoveryOrderDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentReplicatedTestBase.java

The test was not allowing enough time to wait in in some circumstances.
Doubled the time to ensure there is enough the next time and with GC etc.

GEODE-1703: Lengthened a timeout to fix a flakey test.

---

gradle/ide.gradle

Intellij currently can't compile test files because it doesn't recognize
the dependency from one test source set to another test source set.
To work around this we can make intellij consider everything production
source code until we can fix the actual source layout.

Tell intellij to consider all source code as production code

---

geode-core/src/main/java/org/apache/geode/internal/cache/BucketPersistenceAdvisor.java
geode-core/src/main/java/org/apache/geode/internal/cache/CacheDistributionAdvisor.java
geode-core/src/main/java/org/apache/geode/internal/cache/DiskInitFile.java
geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PersistenceAdvisorImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PersistentMemberID.java
geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PersistentMemberPattern.java
geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PersistentStateQueryMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PersistentStateQueryMessageSenderFactory.java
geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PersistentStateQueryResults.java
geode-core/src/main/java/org/apache/geode/internal/sequencelog/RegionLogger.java
geode-core/src/main/java/org/apache/geode/internal/util/TransformUtils.java
geode-core/src/test/java/org/apache/geode/internal/cache/persistence/PersistenceAdvisorImplTest.java

Disk recovery can hang when every member is waiting for other members to recover first and no member will proceed. 
When the last known state of a member is written to the oplogs and the member is killed before the older state of the member is removed from the oplogs, then on recovery there is more than one state for a persistent member. Recovery was stuck waiting for the persistent member with the older timestamp.
There are 3 changes:
1) In PersistenceAdvisorImpl make equalMembers thread safe by making it a CopyOnWriteHashSet.
2) If a remote member is initializing and the current member believes the remote member should wait for the current member, then the current member removes the remote member from the set of members to wait for.
3) If the set of members to wait for contains multiple …

GEODE_5402 Disk recovery hangs after killing members

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/fixed/FixedPartitioningDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/fixed/FixedPartitioningTestBase.java
geode-core/src/integrationTest/java/org/apache/geode/test/dunit/internal/JUnit4DistributedTestCase.java

This test appears like it was trying to test what happens if a put
happens when data store creation is at a particular point.
Unfortunately, it failed to do so correctly because it just spun off the
data store creation in separate threads and then did the put. The wait
criterion used was also completely wrong, so the test would always wait
for 1 minute.
Finally, there were some race conditions caused by passing the same
array list to multiple async task.
Changed the code to wait until the data stores are at the given point in
region creation and then do the put.
@balesh2 @mhansonp

GEODE-567: Wait for async datastore creation to reach appropriate point

---

geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb

Please see the GEODE-5436 JIRA for details.  This update does a bit more than just document the --if-not-exists option.

GEODE-5436 Update create gateway receiver docs with if-not-exists

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/tier/sockets/CacheServerTestUtil.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/EndpointManager.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientCrashDUnitTest.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientSimpleDUnitTest.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientTestCase.java

A test was failing due to a timeout being not long enough. Other cleanup done to remove compiler warnings and deprecations.

GEODE-5428: Fix test and cleanup of warnings.

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/PersistentPartitionedRegionDistributedTest.java

catch DistributedSystemDisconnectedException and continue the test. This
makes the test reliably pass, however it is indicative of a race
condition in production code. A new GEODE ticket will be added with more
details, however these two errors are essentially equivalent to the
system and to users.

GEODE-5325: catch DistributedSystemDisconnectedException

---

geode-docs/managing/security/enable_security.html.md.erb

To alleviate user uncertainty, add some specifics about how to properly specify the security-manager property.

GEODE-5461 - Docs: Specifying the security-manager property

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/commands/StartServerCommandAcceptanceTest.java
geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartServerCommandAcceptanceTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/ReconnectWithCacheXMLDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/StartServerWithXmlDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/ServerLauncherBuilderIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/ServerLauncherIntegrationTestCase.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/ServerLauncherLocalFileIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/ServerLauncherLocalIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/ServerLauncherRemoteFileIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/ServerLauncherRemoteIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/ServerLauncherRemoteIntegrationTestCase.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/ServerLauncherWithProviderRegressionTest.java
geode-core/src/integrationTest/java/org/apache/geode/test/dunit/rules/DistributedTestRule.java
geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
geode-core/src/main/java/org/apache/geode/distributed/ServerLauncher.java
geode-core/src/main/java/org/apache/geode/distributed/ServerLauncherParameters.java
geode-core/src/main/java/org/apache/geode/internal/cache/CacheServerLauncher.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheCreation.java
geode-core/src/test/java/org/apache/geode/distributed/ServerLauncherBuilderTest.java
geode-core/src/test/java/org/apache/geode/distributed/ServerLauncherTest.java
geode-core/src/test/java/org/apache/geode/distributed/ServerLauncherWaitOnServerMultiThreadedTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/xmlcache/CacheCreationJUnitTest.java

Configuration options set as part of the `start server` command now
take precedence over those configured in the `cache.xml` file, the
`cluster-configuration-service` and defaults.
- Removed unused `throws` clauses from tests.
- Renamed `ServerLauncherIntegrationTest` to
`ServerLauncherBuilderIntegrationTest`.
- Added tests for `ServerLauncher` and `CacheCreation`.
- Added acceptance tests for `gfsh start server` command.
- Fixed `ServerLauncher.parseArguments` method, it was wrongly calling
`setMaxConnections` for other unrelated parameters (maxMessageCount,
messageTimeToLive and sockerBufferSize).
- The `ServerLauncher` class now sets all the relevent startup
parameters during initialization within the static `parameters` field
on `CacheServerLauncher` class. The `CacheCreation` class, …

GEODE-5256: Parameters Precedence in Start Server

---

extensions/geode-modules-assembly/build.gradle

Task depends on jars for tomcat7 and tomcat8, but did not wait for those
tasks to execute.

GEODE-5477 Fix `distTomcat` dependencies in geode assembly

---

geode-core/src/main/java/org/apache/geode/internal/datasource/GemFireBasicDataSource.java
geode-core/src/test/java/org/apache/geode/internal/datasource/GemFireBasicDataSourceJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/datasource/TestDriver.java

Added protection against NullPointerExceptions being thrown by
GemFireBasicDataSource.getConnection() in the event the default username or password
were null. Also added tests to confirm this is working as intended.
[GEODE-5450]
Co-authored-by: Patrick Johnson <kcirtap1324@gmail.com>

GEODE-5450: Added protection for NPE in GemFireBasicDataSource with no credentials

---

geode-core/src/integrationTest/java/org/apache/geode/redis/HashesJUnitTest.java

This test was generating random strings, but some strings were invalid
regions names, for example strings starting with __. Limiting the
strings the alphabet.

GEODE-1942: Limiting random strings to [A-Z] chars

---

ci/pipelines/geode-build/test-stubs/acceptance.yml
ci/pipelines/geode-build/test-stubs/integration.yml
ci/pipelines/geode-build/test-stubs/ui.yml

All jobs YML allows parallel running if enabled via Gradle property

GEODE-5488 - Enable YML changes for parallel testing

---

geode-assembly/build.gradle
geode-core/build.gradle
geode-old-versions/build.gradle
geode-pulse/build.gradle
gradle/java.gradle

- distZip and distTar tasks wait for all 'jar' tasks to finish
- geode-assembly:docs depends on all project's javadoc task
- geode-core 'jar' depends on the version properties file
- version properties file runs after compileJava
- geode-pulse 'war' depends on the webJar, instead of only including it
- fixed download of geode-old-versions to run after clean, even when
specified backwards on the command line
- srcJar no longer includes the IntelliJ output directory …

GEODE-5492 Fix gradle dependencies to enable reliable parallel build

---

ci/scripts/rsync_code_down.sh

* Add the combineReports task as an explicit step in the ensured block
* Make all build artifacts visible to avoid errors during rsync
Co-authored-by: Dick Cavender<dcavender@pivotal.io>
----
email …

GEODE-5507: Update rsync_code_down script for stability.

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/ha/HARegionQueueIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/ha/HARegionQueueJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifierIntegrationTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/HARegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/ha/HAContainerMap.java
geode-core/src/main/java/org/apache/geode/internal/cache/ha/HARegionQueue.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxy.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/HAEventWrapper.java

- Updated putInProgress boolean in HAWrapper to a counter to prevent prematurely setting ClientUpdateMessage to null when events are temporarily queued during a GII or message dispatcher initialization
- decAndRemoveFromHAContainer only removes when putInProgress counter and ref count are 0
- Refactored putEventInHARegion/putConditionallyInHAContainer to prevent overwriting an existing entry in the HAContainer.  Also reduces simplifies the code and reduces duplicated logic.
- Wrote missing basic HARegionQueue unit/integration tests, and an integration test to capture setting the ClientUpdateMessage property on HAEventWrapper to null prematurely
- Added new event tracing messages at debug logging level to help track similar issues in the future
Co-authored-by: Ryan McMahon …

GEODE-5420: Protect events in HAContainer from premature modification

---

gradle/test.gradle

Thes extra log messages are just making it harder to find actual
failures.
@mhansonp @balesh2

Removing reports of successful tests from the build output

---

gradle/java.gradle

Invoking 'tasks' within taskGraph.whenReady() does not get all tasks,
but only the tasks for the current project. Move the whenReady() back
within a subprojects closure to get correct behavior back

GEODE-5508 Reverts change from GEODE-5492 that broke UTF-8 and manifests

---

geode-assembly/src/distributedTest/java/org/apache/geode/rest/internal/web/controllers/RestAPIsWithSSLDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/RegionChangesPersistThroughClusterConfigurationDUnitTest.java

We were getting two separate random ports and not validating that the
ports are actually distinct. This change gets both ports at the same time
and thus ensures uniqueness.

GEODE-5479 - Fix usage of AvailablePortHelper

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/TransactionOnBehalfOfClientMemberDistributedTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/PausedTXStateProxyImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXState.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXStateProxy.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXStateProxyImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PartitionMessage.java
geode-core/src/test/java/org/apache/geode/internal/cache/TXStateTest.java

* Only initTXMemberId in PartitionMessage if transaction is originated from client.
* Returns client member id in TXState.getOriginatingMember() if it is a client originated transaction
so it can be correctly set in the PartitionMessage.

GEODE-5515: Only initTXMemberId in PartitionMessage if transaction is originated from client.

---

geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionTest.java

Changes are made to get the register initial image results from primary buckets. This avoids getting  stale data, when there is an inflight operation thats not yet applied on secondary.
Co-authored-by: @pdxrunner 

GEODE-5513: Changes to build register interest initial snapshot from primary bucket

---

geode-core/src/integrationTest/java/org/apache/geode/internal/statistics/StatTypesAreRolledOverRegressionTest.java
geode-core/src/main/java/org/apache/geode/internal/statistics/StatArchiveReader.java

- This commit also fixes a resource leak in
StatTypesAreRolledOverRegressionTest which was causing the test to fail on
Windows.

GEODE-5517: Have StatArchiveReader implement AutoCloseable

---

geode-core/src/main/java/org/apache/geode/internal/cache/execute/PartitionedRegionFunctionResultSender.java
geode-core/src/main/java/org/apache/geode/internal/i18n/LocalizedStrings.java
geode-lucene/src/distributedTest/java/org/apache/geode/cache/lucene/LuceneQueriesDUnitTest.java
geode-lucene/src/distributedTest/java/org/apache/geode/cache/lucene/LuceneQueriesReindexDUnitTest.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/LuceneService.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneQueryImpl.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneServiceImpl.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/distributed/IndexingInProgressFunction.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/distributed/LuceneQueryFunction.java
geode-lucene/src/main/resources/org/apache/geode/internal/sanctioned-geode-lucene-serializables.txt

* If the Lucene query function is executed by an old client (<=1.6.0) on a new server, it will wait for the index to be created.
* Server wont return a LuceneIndexCreationInProgressException back to the old client resulting in a ClassNotFoundException.

GEODE-5055: Handle index in progress for old clients

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ExportLogsDUnitTest.java

Added Awaitility to wait at least 1 millisecond to reduce flakiness on windows.

GEODE-5212: reduce flakiness of ExportLogsOverHttpDistributedTest

---

geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/QueryIndexDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreateDefinedIndexesCommandDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/query/QueryServiceJUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/query/QueryService.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/DefaultQueryService.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheCreation.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheXmlGenerator.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DestroyIndexFunction.java

GEODE-5246: Avoid NULL in QueryService.getIndexes
- Added Unit tests.
- Changed `DefaultQueryService` to return an empty list instead of
`null` when no indexes are defined.

GEODE-5246: QueryService.getIndexes should not return null when there are no indexes

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ha/HARegionQueueDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/ha/HARQAddOperationJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/ha/HARegionQueueIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/ha/HARegionQueueJUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/ha/HARegionQueue.java

- Double decrementing of HAEventWrapper ref count could occur from simultaneously destroying the region while either processing a queue removal message or dispatching a message.  Fix is to remove the available ID before decrementing in the region destroy logic.
- Added tests for fix
- Fixed getAvalaibleIds() method name typo
Co-authored-by: Ryan McMahon <rmcmahon@pivotal.io>
Co-authored-by: Lynn Hughes-Godfrey <lhughesgodfrey@pivotal.io>
email to …

GEODE-5495: Destroy available ID before decrement in updateHAContainer()

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/PutOp.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/PutOpJUnitTest.java

When a new PutOp message is sent to the server with the full value instead
of a delta we now set the isRetry flag on the message so that the server
will know to check if a version has already been assigned to the operation.

GEODE-5520 Inconsistency created by delta interaction with concurrency control

---

geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneServiceImpl.java

* new lock created for updating the region's cache service profile
* synchronized the addition / validation / removal of LuceneIndexCreationProfile in the data region.

GEODE-5197: Synchronized update cache service profile in lucene

---

geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneServiceImpl.java

* new lock created for updating the region's cache service profile
* synchronized the addition / validation / removal of LuceneIndexCreationProfile in the data region.

GEODE-5197: Synchronized update cache service profiles

---

geode-core/src/main/java/org/apache/geode/distributed/LocatorLauncher.java
geode-core/src/main/java/org/apache/geode/distributed/ServerLauncher.java

LocatorLauncher and ServerLauncher should ignore while
validating workingDir path.

GEODE-5212: Ignore case when comparing paths.

---

geode-core/src/main/java/org/apache/geode/internal/cache/execute/ServerToClientFunctionResultSender.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/ServerToClientFunctionResultSender65.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/BaseCommand.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunction61.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunction65.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunction66.java
geode-core/src/test/java/org/apache/geode/internal/cache/execute/ServerToClientFunctionResultSender65JUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/execute/ServerToClientFunctionResultSenderJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/BaseCommandJUnitTest.java

* When an exception is received lastResultReceived flag is set.
* Previously this flag is only set if exception is of type QueryInvocationTargetException or FunctionInvocationTargetException
* Setting this flag will prevent other threads from sending results to the client after the exception is sent.

GEODE-5521: lastResultReceived flag set

---

geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/LocatorSSLJUnitTest.java
geode-junit/src/main/java/org/apache/geode/util/test/TestUtil.java

When a classpath resource is looked up the path
retrieved from the resource URI can be null in which 
case it creates a file from copying the resource. This
temp file path is already a good one to be returned.

GEODE-5212: Fix TestUtil to return path

---

ci/pipelines/geode-build/test-stubs/acceptance.yml
ci/pipelines/geode-build/test-stubs/distributed.yml
ci/pipelines/geode-build/test-stubs/integration.yml
ci/pipelines/geode-build/test-stubs/upgrade.yml

* Reduce acceptancetest from 30GB to 12GB
* Reduce distributedtest from 210GB to 180GB
* Reduce integrationtest from 210GB to 48GB
* Reduce upgradetest from 210GB to 120GB

[GEODE-5548] Reduce RAM usage in various jobs due to unused resources.

---

build.gradle
geode-web/build.gradle
gradle/spotless.gradle
gradle/test.gradle

* devBuild depends on :assembly and :spotlessApply
* Ensure that spotlessApply and spotlessCheck run before compilation
*** This ordering dependency is project wide, not only with respect to
devBuild
* Correct apparent error in precheckin task only running
acceptanceTest task in geode-assembly module
*** Historically, this was the only module that contained
acceptanceTests.  This was changed with the introduction of nebula
facets.
* Minor readability improvements in touched files.
Signed-off-by: Patrick Rhomberg <prhomberg@pivotal.io>
- [n/a] If adding …

GEODE-5555: Add 'devBuild' task

---

geode-core/src/distributedTest/java/org/apache/geode/management/UniversalMembershipListenerAdapterDUnitTest.java

This test has many wait blocks that just used an if. So if the thread
was notified by some other event, it would leave the wait without the
expected event being delivered.

GEODE-5480: Changing wait blocks to use a while loop

---

geode-core/src/main/java/org/apache/geode/internal/cache/versions/RVVException.java
geode-core/src/main/java/org/apache/geode/internal/cache/versions/RVVExceptionB.java
geode-core/src/main/java/org/apache/geode/internal/cache/versions/RVVExceptionT.java
geode-core/src/main/java/org/apache/geode/internal/cache/versions/RegionVersionHolder.java
geode-core/src/test/java/org/apache/geode/internal/cache/versions/RegionVersionHolderJUnitTest.java

This modifies the RVVException to iterate over the received version newest to
oldest, which makes generating the canonical exceptions much more
straightforward.

GEODE-5559: Improve runtime of RegionVersionHolder.canonicalExceptions

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/PersistentPartitionedRegionWithTransactionDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXCommitMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXEntryState.java
geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/RegionCommitTest.java

GEODE-5541: A create followed by a destroy of the same key will not invoke cache listener on remote nodes.

---

ci/pipelines/geode-build/test-stubs/distributed.yml

We are seeing 5% of our builds fail with membership errors due to
heartbeat timeouts. We also see that the DistributedTest job is running
with a 300 load average. Reducing the parallelism to avoid overloading
the machine.

Reducing the parallelism of if distributedTest

---

ci/pipelines/pull-request/base.yml
ci/pipelines/pull-request/deploy_pr_pipeline.sh
ci/pipelines/pull-request/pr-template.yml
ci/pipelines/pull-request/test-stubs/newtests.yml
ci/scripts/archive_results.sh
ci/scripts/repeat-new-tests.sh
gradle/test.gradle

Adding a job to the PR pipeline that finds new or modified test files
and runs them many times. The goal is to fail PRs that create new flaky
tests.

GEODE-5387: Adding job to the pr pipeline to stress new tests

---

geode-core/src/integrationTest/java/org/apache/geode/management/internal/beans/ManagementAdapterTest.java

Use the concurrency rule to run threads instead of providing a custom
implementation that may or may not be correct.

GEODE-5583: Use the ConcurrencyRule to run threads

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartServerCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java

* Additional logs added when cache-xml file is used in start server gfsh command.
* A warning is logged mentioning that cluster config will take precedence over the cache-xml file provided in the command.
* start server command help updated with the above information.

GEODE-3839: Warning when cache xml is used

---

geode-core/src/integrationTest/java/org/apache/geode/management/bean/stats/GatewayReceiverStatsJUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/GatewayReceiverMBeanBridge.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/wancommand/ListGatewaysCommandDUnitTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/wancommand/StatusGatewayReceiverCommandDUnitTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/wancommand/WANCommandUtils.java

The class `GatewayReceiverMBeanBridge` uses the `MBeanStatsMonitor` to
retrieve the amount of senders currently connected. This statistic
tends to be out of date and heavily depends on the `HostStatSampler`
class to run periodically and update the data. Whenever a receiver is
stopped its stats are also closed and, as such, the
`clientConnectionCount` is not updated anymore, resulting in a wrong
gateway-sender connected count reported.
- Added tests to verify the accuracy of the current gateway-senders
connected.
- Renamed `WanCommandListDUnitTest` to `ListGatewaysCommandDUnitTest`.
- Modified the `GatewayReceiverMBeanBridge` to retrieve the current
client connection count from the underlying acceptor instead of
the `MBeanStatsMonitor` class.
Thank you for …

GEODE-5248: Fixes in GatewayReceiverMBeanBridge

---

geode-core/src/integrationTest/java/org/apache/geode/cache30/ShorteningExpirationTimeRegressionTest.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/ServerStarterRule.java

* the timeout is changed to 1ms after the 2nd put. If the assertion call happens 1ms after the 2nd put, the test would fail
* remove boiler code using ServerStarterRule

GEODE-5257: remove unnecessary assertion that introduced the flakiness.

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/shell/Gfsh.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/shell/GfshAbstractUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/shell/GfshConsoleModeUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/shell/GfshHeadlessModeUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/shell/GfshJunitTest.java

GEODE-5531/GEODE-1507: Variable Substitution in GFSH
The problem was introduced when `spring-shell` and `jline` libraries
were upgraded. The method `Gfsh.executeCommand` now substitutes all
variables (overriding `AbstractShell.executeCommand`) before delegating
the execution to the parent class (as `Gfsh.executeScriptLine` does).

GEODE-5531/GEODE-1507: Variable Substitution in GFSH

---

geode-core/src/main/java/org/apache/geode/internal/cache/execute/ServerToClientFunctionResultSender.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/ServerToClientFunctionResultSender65.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction66.java
geode-core/src/test/java/org/apache/geode/internal/cache/execute/ServerToClientFunctionResultSender65JUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/execute/ServerToClientFunctionResultSenderJUnitTest.java

* To prevent situations where exceptions thrown in lastResult in not sent to the client.
* This happens if we set the lastResultReceived and then an exception occurs.
* exception is not sent back because the flag is set.
* solution is now to set the flag only after the msg is sent from lastResult.

GEODE-5589: lastResultReceived set after msg sent

---

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyJndiBindingCommandTest.java

* this was fine in java 8 but would pose a problem after we move to java 10.

GEODE-4384: fix test's argument captor type.

---

ci/scripts/archive_results.sh
ci/scripts/capture-call-stacks.sh

We are seeing a lot of hangs and OOMEs in DistributedTest all of a sudden. Unfortunately, we are not capturing the call stacks and the hprof files we need to diagnose the issue. These changes should help.

GEODE-5615 Capturing more data in the case of hangs or OOMEs

---

geode-rebalancer/src/test/java/org/apache/geode/cache/util/AutoBalancerJUnitTest.java

This test asserted that execute was invoked exactly twice by a
background timer task. But that task could invoke execute more times
than that if the main test thread is slow.

GEODE-5617: FIxing a race in AutoBalancerJUnitTest

---

geode-junit/src/main/java/org/apache/geode/test/junit/rules/ConcurrencyRule.java
geode-junit/src/test/java/org/apache/geode/test/junit/rules/ConcurrencyRuleTest.java

Before this, if ConcurrencyRule was used for a test it failed because
`allthreadsExecuted` was `false`.
Also delegate to the non-default constructor with the default
constructor.
@balesh2

GEODE-5627: ConcurrencyRule passes when not used.

---

geode-core/src/distributedTest/java/org/apache/geode/cache/management/MemoryThresholdsDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache/management/MemoryThresholdsOffHeapDUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/DefaultQueryService.java
geode-core/src/main/java/org/apache/geode/internal/cache/CacheDistributionAdvisor.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/MemoryThresholdInfo.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/control/HeapMemoryMonitor.java
geode-core/src/main/java/org/apache/geode/internal/cache/control/ResourceAdvisor.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/DistributedRegionFunctionExecutor.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/MemberFunctionExecutor.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/MultiRegionFunctionExecutor.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/PartitionedRegionFunctionExecutor.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PartitionedRegionRebalanceOp.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/RegionAdvisor.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction65.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction66.java
geode-core/src/test/java/org/apache/geode/internal/cache/DistributedRegionJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/MemoryThresholdInfoTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/control/HeapMemoryMonitorTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction66Test.java

There is an AtomicBoolean (memoryThresholdReached) in LocalRegion.
In DistributedRegion, a subclass of LocalRegion, there is a CopyOnWriteArraySet (memoryThresholdReachedMembers).
In DistributedRegion, these two fields are set together by synchronizing on memoryThresholdReachedMembers.
If the boolean is true (meaning we crossed the critical threshold), the set must contain the members
that are low on memory.
In LocalRegion, these two fields were being read without synchronization, so the boolean and set could be
inconsistent with each other. The boolean could be read as true, but the set could be read as empty.
This can occur when the reading thread reads the boolean, then another thread calls a method that sets
both fields, then the reading thread reads the set.
This fix adds a new …

GEODE-5562 Reading the values of LocalRegion.memoryThresholdReached and DistributedRegion.memoryThresholdReachedMembers must be atomic

---

geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/JdbcAsyncWriterTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/JdbcWriterTest.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/QueueConnectionImplJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/datasource/GemFireBasicDataSourceJUnitTest.java

I also fixed a couple warnings in the tests I changed.

GEODE-5632: import Assertions instead of AssertionsForClassTypes

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/StopLocatorCommandDUnitTest.java

Apparently members are not immmediately visible to stop after gfsh start
locator. Changing the test to use awaitility to wait until the members
can be stopped.

GEODE-5623: Use Awaitility in StopLcoatorCommandDUnitTest

---

geode-core/src/main/java/org/apache/geode/internal/cache/AbstractBucketRegionQueue.java
geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegionQueue.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelQueueRemovalMessage.java
geode-core/src/test/java/org/apache/geode/internal/cache/wan/parallel/ParallelQueueRemovalMessageJUnitTest.java

* After GII a flag is set to indicate that failedBatchRemovalMessageKeys has been processed
* If this flag is set, no more entries will be put into failedBatchRemovalMessageKeys.

GEODE-5631: failedBatchRemovalMessageKeys not used after GII

---

build.gradle
ci/pipelines/geode-build/deploy_pipeline.sh
ci/pipelines/geode-build/jinja.template.yml
ci/scripts/publish.sh
geode-assembly/build.gradle
geode-assembly/src/integrationTest/resources/expected_jars.txt
geode-core/build.gradle
geode-junit/build.gradle
geode-lucene/build.gradle
geode-pulse/build.gradle
geode-web-api/build.gradle
geode-web/build.gradle
gradle/publish.gradle
gradle/test.gradle
gradle/utilities.gradle

Uses vanilla maven-publish Gradle plugin, instead of nexus (nexus is
still used for release artifact publishing)
GCS credentials are inherited from the concourse worker
Co-authored-by: Jake Barrett <bjarrett@pivotal.io>

GEODE-5597 Publish geode artifacts to maven repo on GCS

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/MultiUserAuthenticationFunctionServiceDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/ServerFunctionExecutor.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/ServerRegionFunctionExecutor.java

GEODE-5618: FunctionService.onServer() and FunctionService.onRegion() fail when multiuser-authentication=true
When a client executes a function using the id instead of the actual
instance, an internal invocation to the `GetFunctionAttributeOp`
function is executed to get the metadata about the original function
itself. This invocation doesn't set the user attributes requried by the
authentication mechanism, so the entire invocation fails.
- Added distributed tests.
- Classes `ServerFunctionExecutor` and
`ServerRegionFunctionExecutor` now set the `userAttributes` in the
local thread before getting the metadata when the function is
executed by id.
to ensure the following …

GEODE-5618: Auth Attributes in FunctionService

---

geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedDiskDirRule.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/DiskDirRule.java

To redirect Geode default disk store to a TemporaryFolder, you can simply
add this to any test:
```java
@Rule
public DiskDirRule diskDirRule = new DiskDirRule();
```
Or in a DistributedTest use:
```java
@Rule
public DistributedDiskDirRule diskDirRule = new DistributedDiskDirRule();
```

GEODE-5641: add no-arg constructor to DiskDirRule

---

geode-core/src/integrationTest/java/org/apache/geode/internal/SSLConfigJUnitTest.java
geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java

renamed ssl-enable-endpoint-identification
to ssl-endpoint-identification-enabled.

GEODE-5594: Rename SSL hostname validation property name

---

gradle/test.gradle

GEODE-5536 force unitTest compilation to be dependency of source classes

---

geode-junit/src/test/java/org/apache/geode/test/junit/rules/ExecutorServiceRuleTest.java

All calls requiring a timeout now use Awaitility. Timeout for all
calls are defined centrally with a value of 2 minutes.
Remove tests that were actually testing Executors/ExecutorService.
Please review @dhemery @balesh2

GEODE-5662: improve timeouts in ExecutorServiceRuleTest

---

geode-dunit/src/main/java/org/apache/geode/test/junit/rules/ServerStarterRule.java

1. add a method to get a default dunit locator port in case servers want to join with that locator instead.
2. ServerStartupRule can start with cache only (no cache server started if needed)
3. create convenience methods to create regions with different region attributes setup.

GEODE-5475: rule improvement

---

geode-docs/managing/security/implementing_ssl.html.md.erb
geode-docs/reference/topics/gemfire_properties.html.md.erb

document new ssl-endpoint-identification-enabled property
@upthewaterspout @bschuchardt @sboorlagadda Please review this new documentation that goes with GEODE-5594 code changes.

GEODE-5594 Enable endpoint validation during using SSL handshake

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionCreationDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/locks/DLockServiceLeakTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/InterruptDiskJUnitTest.java
geode-junit/src/integrationTest/java/org/apache/geode/test/junit/rules/ExecutorServiceRuleIntegrationTest.java
geode-junit/src/main/java/org/apache/geode/test/junit/rules/ExecutorServiceRule.java

This changes the ExecutorServiceRule to use an unlimited ThreadPoolExecutor.
Improve or fixup a couple tests that use the ExecutorServiceRule:
* PartitionedRegionCreationDUnitTest
* DLockServiceLeakTest
* InterruptDiskJUnitTest (major overhaul)
This PR depends on PR #2405 (GEODE-5662: improve timeouts in ExecutorServiceRuleTest) which deleted two flaky tests from ExecutorServiceRuleTest because the tests were primarily testing ExecutorService instead of the rule itself.

GEODE-5652: use unlimited ThreadPoolExecutor in ExecutorServiceRule

---

geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/AgentUtilJUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/AgentUtil.java

within AgentUtil.java. This is to address problem where
http server is started from Java API (Spring Data Geode specifically)
Now, the application can reference the `geode-web-api` war from repo
and not have to specifically set `GEODE-HOME` property

GEODE-5660: Added method to lookup war file from classpath

---

geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
geode-wan/src/integrationTest/java/org/apache/geode/internal/cache/wan/misc/WANConfigurationJUnitTest.java
geode-wan/src/main/java/org/apache/geode/internal/cache/wan/GatewayReceiverImpl.java

This changes the behavior of GatewayReceiverImpl to be consistent with
other classes and throw unconditionally when an exception occurs in
.start()

[GEODE-5591] If there is a BindException we should always throw.

---

geode-dunit/src/main/java/org/apache/geode/test/junit/rules/MemberStarterRule.java
geode-junit/src/main/java/org/apache/geode/internal/UniquePortSupplier.java
geode-junit/src/test/java/org/apache/geode/internal/UniquePortSupplierTest.java

Adding a utility to hand out unique ports that don't conflict with
each other, and using that in the MemberStarterRule. This should fix port
conflicts in AlterRuntimeCommandDUnitTest and others.
Co-authored-by: Dale Emery <dale@dhemery.com>

GEODE-5622: Add unique port supplier that remembers supplied ports

---

geode-dunit/src/main/java/org/apache/geode/security/ClientAuthorizationTestCase.java
geode-dunit/src/main/java/org/apache/geode/security/SecurityTestUtils.java

CLientAUthorizationDUnitTest was only waiting 7 seconds for an event to
occur. Switching to Awaitility and waiting for 5 minutes.

GEODE-5481: Extended wait duration in security tests

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/DiskInitFileJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/OplogRVVJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/statistics/LinuxSystemStatsTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/statistics/ValueMonitorIntegrationTest.java
geode-core/src/test/java/org/apache/geode/cache/query/internal/CompiledAggregateFunctionJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/TxCommitMessageTest.java
geode-core/src/test/java/org/apache/geode/internal/io/CompositeOutputStreamJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/net/SocketUtilsJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/util/IOUtilsJUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/JettyHelperJUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsJUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListIndexCommandJUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/DescribeDiskStoreFunctionJUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/ListDiskStoresFunctionJUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/ListIndexFunctionJUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsJUnitTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/distributed/TopEntriesJUnitTest.java
geode-rebalancer/src/test/java/org/apache/geode/cache/util/AutoBalancerJUnitTest.java
geode-web/src/test/java/org/apache/geode/management/internal/web/controllers/support/LoginHandlerInterceptorJUnitTest.java
geode-web/src/test/java/org/apache/geode/management/internal/web/http/converter/SerializableObjectHttpMessageConverterJUnitTest.java
gradle/dependency-versions.properties
gradle/test.gradle

GEODE-5607: Replace Jmock with Mockito
- Removed dependency to `org.jmock`.
- Migrated several test classes to use `Mockito` instead `Jmock`.
- Changed same classes to use `assertj` instead of `junit.Assert`.
- Changed same classes to use `Awaitility` instead of `WaitCriterion`.

GEODE-5607: Replace Jmock with Mockito

---

geode-core/src/main/java/org/apache/geode/internal/cache/tx/AbstractPeerTXRegionStub.java
geode-core/src/test/java/org/apache/geode/internal/cache/tx/AbstractPeerTXRegionStubTest.java

GEODE-5702: Re_throw a specific TransactionException instead of wrapping it to a new TransactionException.

---

geode-dunit/src/main/java/org/apache/geode/cache30/MultiVMRegionTestCase.java

There was an awaitility that intended to loop until data was consistent
but instead failed on the first pass if any keys weren't consistent.
Signed-off-by: khowe@pivotal.io

GEODE-5704: use untilAsserted to avoid early failure

---

geode-core/src/main/java/org/apache/geode/internal/cache/EntryEventImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/entries/AbstractDiskRegionEntry.java
geode-core/src/main/java/org/apache/geode/internal/cache/entries/DiskEntry.java
geode-core/src/main/java/org/apache/geode/internal/offheap/OffHeapRegionEntryHelper.java
geode-core/src/test/java/org/apache/geode/internal/cache/entries/DiskEntryHelperTest.java

* If RegionDestroyedException is thrown while trying to set a value, but after memory has been allocated, we will now release the memory in a catch block.

GEODE-5565: Release off heap memory if unable to set value 

---

geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PutAllPRMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/RemoveAllPRMessage.java
geode-core/src/test/java/org/apache/geode/internal/cache/BucketRegionJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/PutAllPRMessageTest.java

Co-authored-by: @boglesby 
GEODE-5605: 
- After removeAll/PutAll messages are processed on replicas, check for cache close is done.
This results in retrying the operation from accessor node; which will take care of partial 
distribution due to cache close.
- [Yes] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?
- [No ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?
- [Yes] Is your initial contribution a single, squashed commit?
- [Yes ] Does `gradlew build` run cleanly?
- [Yes] Have you written or updated unit tests to verify your changes?
- [NA ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF …

GEODE-5605: After removeAll/PutAll messages are processed on replicas, check for cache close is done.

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ExportClusterConfigurationCommandDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/configuration/ClusterConfigImportDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/result/model/ResultModelIntegrationTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ExportClusterConfigurationCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ExportConfigCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/result/ModelCommandResult.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/result/model/FileResultModel.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/result/model/ResultModel.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/shell/Gfsh.java
geode-junit/src/main/java/org/apache/geode/test/junit/assertions/ResultModelAssert.java
geode-web/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ExportConfigCommandDUnitTest.java
geode-web/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/CommandOverHttpTest.java

* file saving should be handled by the command's postExecutor to save to appropriate places
* after saving file content to a directory already, the ResultModel turned the FileResultModel into InfoResultModel.
* gfsh should not be the place to save files in ModelCommandResult.

GEODE-5727: rework how ResultModel deal with file contents.

---

geode-core/src/integrationTest/java/org/apache/geode/cache/ProxyJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/RegionExpirationIntegrationTest.java

ProxyJUnitTest.testExpiration used small timeouts and was flaky. It
looks like it was probably a near duplicate of a test that was already
refactored into RegionExpirationIntegrationTest. Removing the test and
parameterizing RegionExpirationIntegrationTest instead.

GEODE-5094: Replace flaky expiration with prexisting better one

---

ci/pipelines/geode-build/jinja.template.yml
ci/pipelines/pull-request/jinja.template.yml
ci/scripts/build.sh
ci/scripts/execute_tests.sh
ci/scripts/windows/test-run.sh
geode-assembly/build.gradle
geode-core/build.gradle
gradle.properties

Found during testing, relating to GEODE-5694, remove the zip artifacts for better signing behavior

GEODE-5600 - Run createVersionPropertiesFile on SHA change

---

geode-core/src/main/java/org/apache/geode/internal/offheap/OffHeapRegionEntryHelper.java
geode-core/src/test/java/org/apache/geode/internal/offheap/OffHeapRegionEntryHelperJUnitTest.java

* turning on assertion in classloader would not play nicely in jdk9 and later.

GEODE-3: do not use Assert in production code. use explicit exception.

---

ci/pipelines/geode-build/deploy_pipeline.sh
ci/pipelines/meta/deploy_meta.sh
ci/pipelines/shared/utilities.sh
ci/scripts/start_instance.sh

Automatically start the meta-mini-image job on deployment
Disable/pause jobs that are unused in release
DRY the sanitization utility across scripts
Expose the main pipeline from a deployment from apache

GEODE-5722 - Improve concourse deployment experience for releases

---

geode-core/src/main/java/org/apache/geode/internal/InternalDataSerializer.java

this code change is covered by analyzeDataSerializable test already.
this should not impact runs on jdk8,  but the test was failing using jdk9 and later without this fix.
Port the fix to develop to make sure this does not interfere with jdk8.

GEODE-3: Use the correct DataSerializer for TimeUnit in java 9 and later

---

gradle/java.gradle

* javadoc task will fail if we include internal packages using java9 and later

GEODE-3: exclude internal packages when generating javadoc

---

build.gradle
geode-core/build.gradle
geode-protobuf-messages/build.gradle

Use `./gradle generate` to create the sources from both protobuf and
ANTLR, then refresh the IDE sources and build as normal.

GEODE-5688 Create task to generate all sources for better IDE behavior

---

ci/scripts/execute_build.sh
ci/scripts/execute_tests.sh
ci/scripts/rsync_code_down.sh
ci/scripts/rsync_code_up.sh

Adding ConnectionAttempts=60 to all concourse scripts that are using
ssh. We are seeing jobs occasionally fail with connection refused. If
this is a transient issue, this change might fix it.

GEODE-5714: Retry ssh connections in concourse

---

geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/HintCommandIntegrationTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/help/Helper.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java

GEODE-5353: gfsh hint should be case independent
- Added integration tests for `gfsh hint` command.
- Removed some minor warnings from the `Helper` class.
- Replaced the internal `HashMap` containing the `topics` for a
`TreeMap` with the `String.CASE_INSENSITIVE_ORDER` comparator.

GEODE-5353: gfsh hint should be case independent

---

geode-core/src/main/java/org/apache/geode/internal/process/MBeanOrFileProcessController.java

…ilable, skip using the FileProcessController
* this would fix the issue that the StatusServerExitCodeAcceptanceTest.statusWithWrongPid taking too long to exit.

GEODE-4052: Fix StatusServerExitCodeAcceptanceTest.statusWithWrongPid failure

---

geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedNoAckRegionCCEDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedNoAckRegionCCEOffHeapDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/cache30/MultiVMRegionTestCase.java
geode-dunit/src/main/java/org/apache/geode/cache30/RegionTestCase.java

Assertion errors within invoked runnables get wrapped in an
RMIException, so untilAsserted does not recognize them as failed
assertions. Since they are treated as unexpected errors, awaitility
does not loop.  Moving the awaitility inside the invocation gives us the
expected behavior.
Signed-off-by: Dale Emery<demery@pivotal.io>

GEODE-5499: move awaitility into invoked runnable

---

geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/DistributedRegionTest.java

* To avoid race with concurrent cache operation, a clearRegion write lock is needed
when clearing entries and disk region entries during cleanUpAfterFailedGII, as cache
operations hold clearRegion read lock.

GEODE-5748: Hold clearRegion write lock during cleanUpAfterFailedGII

---

build.gradle
extensions/geode-modules-assembly/build.gradle
geode-assembly/build.gradle
gradle/publish.gradle
gradle/utilities.gradle

Using maven-publish plugin instead of nexus plugin. This removes our
dependency on the old 'maven' plugin, and cleans up a lot of custom
disable-task code related to distributions.

GEODE-5757: Remove Nexus publication plugin

---

geode-docs/developing/transactions/directed_example.html.md.erb

- use consistent variable name for transaction manager object
- Boolean -> boolean in function example
- move boolean success to be after commit, so that an exception
upon commit does not report success when a subsequent attempt
does not have sufficent quantity
- get the cache from the context

GEODE-5762 Fix transactions docs code snippets

---

geode-junit/build.gradle

org.skyscreamer:jsonassert which brings in a transitive dependency
on com.vaadin.external.google:android-json which is incompatible
with geode-json.

GEODE-5761: Exclude android-json transitive dependency

---

geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/AggregateRegionStatsMonitor.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/GCStatsMonitor.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/GatewaySenderOverflowMonitor.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/MemberLevelDiskMonitor.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/VMStatsMonitor.java
geode-core/src/test/java/org/apache/geode/management/internal/beans/stats/AggregateRegionStatsMonitorTest.java
geode-core/src/test/java/org/apache/geode/management/internal/beans/stats/GCStatsMonitorTest.java
geode-core/src/test/java/org/apache/geode/management/internal/beans/stats/GatewaySenderOverflowMonitorTest.java
geode-core/src/test/java/org/apache/geode/management/internal/beans/stats/MemberLevelDiskMonitorTest.java
geode-core/src/test/java/org/apache/geode/management/internal/beans/stats/VMStatsMonitorTest.java

GEODE-5314: Use Atomics instead of Volatile
- Added JUnit Tests for all modified classes.
- Replaced `volatile` by `AtomicIntenger` / `AtomicLong` in
`GcStatsMonitor`, `AggregateRegionStatsMonitor`, `VMStatsMonitor`,
`GatewaySenderOverflowMonitor` and `MemberLevelDiskMonitor`.

GEODE-5314: MBeanStatsMonitor child classes should use atomics instead of volatiles to avoid data race

---

build.gradle
geode-core/build.gradle

As an extension developer, gradle's `rootProject` may not refer
to the Geode root project, depending on the extension's structure.

GEODE-5600: Fix extension developer issues with buildinfo

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/NetSearchMessagingDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionMultipleDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/versions/TombstoneDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/JUnit4DistributedTestCase.java

* Add logging to the JUnit4DistributedTestCase for test lifecycle. The
GEODE-5501 bug may be due to tests' @After executing after the next
test has started. Extra logging as to when tests are starting and ending
will help with diagnosing this failure when it occurs.
* Touch the failing test, NetSearchMessagingDUnitTest, so it runs in
StressNewTest CI job
* Touch other tests that extend JUnit4DistributedTestCase so that they
run in StressNewTest CI job
Signed-off-by: Dale Emery <demery@pivotal.io> …

GEODE-5501: add logging in test base for debug

---

geode-dunit/src/main/java/org/apache/geode/test/dunit/standalone/ProcessManager.java

We observed that several tests in AlterRuntimeCommandDUnitTest class
were taking minutes when they should be taking a few seconds at most.
After some debugging, we determined that the JVM itself is struggling to
deal with having 100K+ classes loaded. They are loaded because the test
is repeated starting and stopping the http service, which creates a
classloader and causes soft references to all of the loaded classes to
be cached.
By setting this flag to clear the soft references faster, the test times
go back to normal.
submit an update …

GEODE-5765: Clean up soft references faster in dunit tests

---

geode-core/src/main/java/org/apache/geode/internal/InternalDataSerializer.java
geode-core/src/test/java/org/apache/geode/internal/InternalDataSerializerJUnitTest.java

A SocketException has to be caught because we want to continue trying to connect to locators rather than shutdown the gateway sender event processor.  The SocketException appears to arise due to a temporary network connectivity issue when reading off the socket.  We already handle an unexpected EOF here, so we should most likely be handling the SocketException in the same way.
-------------------------------------------

GEODE-5747: Handling SocketException in InternalDataSerializer

---

geode-web/build.gradle
geode-web/src/test/java/org/apache/geode/management/internal/web/controllers/support/LoginHandlerInterceptorJUnitTest.java

The MultithreadedTestCase class is unreliable under heavy contention for
CPUs, causing the LoginHandlerInterceptorJUnitTest's thread safety test
to fail intermittently in CI. We replaced MultithreadedTestCase (in this
one class) with a more reliable Semaphore-based mechanism to coordinate
the threads.
Also:
* Used ConcurrencyRule to run the multiple threads and collect errors.
* Added geode-junit to geode-web test classpath, to pick up
ConcurrencyRule.
* Simplified the thread-safety test to focus on thread-safety, leaving
basic correctness to other tests.
Signed-off-by: Helena Bales <hbales@pivotal.io> …

GEODE-5551: Replace thread interleaving mechanism

---

geode-core/src/main/java/org/apache/geode/internal/DeployedJar.java

This test was failing on windows with a unexpected
suspect string. The underlying problem is that an
input stream kept open and causes the deletion to
fail.
This fix also fixes:
* CreateRegionCommandDUnitTest
* DeployCommandRedeployDUnitTest
- hotDeployShouldNotResultInAnyFailedFunctionExecutions
- redeployJarsWithNewVersionsOfFunctions

GEODE-5212: fix failing ConcurrentDeployDUnitTest

---

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocator.java

The call to equals() assumed that coordinator was non-null, but
coordinator may legitimately be null.
Please review: @balesh2 @galen-pivotal @upthewaterspout @pdxrunner

GEODE-5728: Allow null coordinator in equals()

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandDUnitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/StartServerCommandDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/StartMemberUtilsTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartMemberUtils.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartServerCommand.java

Tests using relative paths had depended on running as a user other than root.
The tests expceted that file or directpory creation would fail because the user
would not have permission to write to filesystem root.
A further problem was the several tests had hardcoded '/' in pathnames,
which is incompatible with running on Windows.
* make tests use relative paths
* remove system dependent path separators
* move tests that expect directory creation to fail to StartMemberUtilsTest.
submit an update to your PR as soon as possible. If you need …

GEODE-5741: Modified tests to be independent of environment

---

geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/AggregateRegionStatsMonitor.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/GCStatsMonitor.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/GatewaySenderOverflowMonitor.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/MBeanStatsMonitor.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/MemberLevelDiskMonitor.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/VMStatsMonitor.java
geode-core/src/test/java/org/apache/geode/management/internal/beans/stats/AggregateRegionStatsMonitorTest.java
geode-core/src/test/java/org/apache/geode/management/internal/beans/stats/GCStatsMonitorTest.java
geode-core/src/test/java/org/apache/geode/management/internal/beans/stats/GatewaySenderOverflowMonitorTest.java
geode-core/src/test/java/org/apache/geode/management/internal/beans/stats/MBeanStatsMonitorTest.java
geode-core/src/test/java/org/apache/geode/management/internal/beans/stats/MemberLevelDiskMonitorTest.java

The internal class `DefaultHashMap` was designed as an internal
workaround to return a default value whenever the value returned by
`Map.get(K)` was `null`. Starting with Java 8 the `Map` interface
added the method `getOrDefault`, which does something similar in a more
efficient way but it returns the default only if the key doesn't exist.
After inspecting the code, we don't insert `null` values into the
`statsMap`, so it is safe to delete the old `DefaultHashMap` class and
replace its usaged by `Map.getOrDefault`. …

GEODE-5523: Remove DefaultHashMap

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommandDUnitTest.java

The assertion is asserting a multi-line string xml content
which includes a new line which is hardcoded to '\n'.

GEODE-5212: fix failing DestroyRegionCommandDUnitTest on windows

---

geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegionMap.java
geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/map/AbstractRegionMapPut.java
geode-core/src/main/java/org/apache/geode/internal/cache/map/RegionMapCommitPut.java
geode-core/src/main/java/org/apache/geode/internal/cache/map/RegionMapDestroy.java
geode-core/src/main/java/org/apache/geode/internal/cache/map/RegionMapPut.java
geode-core/src/test/java/org/apache/geode/internal/cache/AbstractRegionMapTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/DistributedRegionTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/map/RegionMapCommitPutTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/map/RegionMapDestroyTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/map/RegionMapPutTest.java

* Hold write lock when cleanUpAfterFailedGII.
* Hold read lock when cache operation is performed on the farside if region is not yet initialized.
* Also hold read lock when transaction is performed on the farside if region not initialized yet.

GEODE-5748: Hold a write lock during cleanUpAfterFailedGII

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/wan/asyncqueue/AsyncEventListenerDistributedTest.java

testReplicatedSerialAsyncEventQueueWithPersistenceEnabled_Restart()
starts a cache with an AsyncEventListener, pauses the gateway sender,
puts 1000 entries, stops and restarts the cache with a new listener, and
verifies that all 1000 entry events are delivered to the new listener.
When the other tests in this class pause the gateway sender, they wait
for the event dispatcher to pause before proceeding. This flaky test
neglected to wait. As a result, from time to time a number of events
were delivered to the old listener before the dispatcher paused, and so
were not delivered to the new listener after restart.
The test now waits for the dispatcher to pause before putting the 1000
entries, and so all of the events are delivered to the post-restart
listener.
Thank you for submitting a …

GEODE-5726 Wait for dispatcher to pause

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/util/MergeLogsDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/logging/MergeLogFilesJUnitTest.java
geode-core/src/main/java/org/apache/geode/admin/internal/LogCollator.java
geode-core/src/main/java/org/apache/geode/internal/SystemAdmin.java
geode-core/src/main/java/org/apache/geode/internal/logging/MergeLogFiles.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/util/MergeLogs.java

- Other refactoring which converted a pair of linked structures (log filename
and the associated InputStream) into a Map.

GEODE-5212: Ensure that MergeLogs closes its InputStreams

---

extensions/geode-modules-session/src/integrationTest/java/org/apache/geode/modules/session/installer/InstallerJUnitTest.java
geode-core/src/test/java/org/apache/geode/test/process/ProcessWrapper.java
geode-pulse/src/integrationTest/java/org/apache/geode/tools/pulse/controllers/PulseControllerJUnitTest.java

* fix InstallerJUnitTest
* remove -d64 option
* PowerMock needs to ignore more modules in PulseControllerJunitTest in java9

GEODE-3: small java 9 compatibility fixes

---

geode-core/src/main/java/org/apache/geode/internal/logging/log4j/HexThreadIdPatternConverter.java
geode-core/src/main/resources/log4j2-cli.xml
geode-core/src/main/resources/log4j2.xml
geode-core/src/main/resources/org/apache/geode/internal/logging/log4j/log4j2-legacy.xml
geode-core/src/test/java/org/apache/geode/internal/logging/log4j/HexThreadIdPatternConverterTest.java
geode-core/src/test/resources/org/apache/geode/internal/logging/log4j/marker/log4j2-gemfire_verbose-accept.xml
geode-core/src/test/resources/org/apache/geode/internal/logging/log4j/marker/log4j2-gemfire_verbose-deny.xml
geode-core/src/test/resources/org/apache/geode/internal/logging/log4j/marker/log4j2-geode_verbose-accept.xml
geode-core/src/test/resources/org/apache/geode/internal/logging/log4j/marker/log4j2-geode_verbose-deny.xml
geode-core/src/test/resources/org/apache/geode/test/golden/log4j2-test.xml
geode-dunit/src/main/java/org/apache/geode/test/dunit/standalone/DUnitLauncher.java

Renamed Geode ThreadIdPatternConverter to HexThreadIdPatternConverter because the plugin details currently match an nearly identical class in Log4J2 which formats tid to be decimal instead of hex.

GEODE-5776: Use HexThreadIdPatternConverter for tid in logs

---

geode-assembly/build.gradle

src distribution excludes '**/out/**' which triggers on our concourse
resource script entitled 'out'. This gets the script into the archive
anyway

Force inclusion of all ci/** files to work around exclude name collision

---

geode-core/src/main/java/org/apache/geode/distributed/internal/AbstractDistributionConfig.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfigImpl.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfigSnapshot.java
geode-core/src/main/java/org/apache/geode/distributed/internal/RuntimeDistributionConfigImpl.java
geode-core/src/main/java/org/apache/geode/internal/AbstractConfig.java
geode-core/src/main/java/org/apache/geode/internal/Config.java
geode-core/src/main/java/org/apache/geode/internal/logging/LogConfig.java
geode-core/src/main/java/org/apache/geode/internal/logging/LogConfigSupplier.java
geode-core/src/main/java/org/apache/geode/internal/logging/SecurityLogConfig.java

Add LogConfigSupplier and some additional changes to LogConfig for
logging changes.
This is only part of the work for GEODE-2644. Aside from LogConfigSupplier and LogConfig, this PR simply removes warnings, renames variables, and fixes some comments.

GEODE-2644: Cleanup config classes

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DeployWithGroupsDUnitTest.java

bounce on windows is not graceful and causes the
distributed system to start suspect processing.
Ignoring these tests until GEODE-5787 is fixed.

GEODE-5788: On Windows, Ignore tests that bounces VMs

---

geode-core/src/integrationTest/java/org/apache/geode/cache/client/ClientCacheFactoryJUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/client/ClientCacheFactory.java
geode-core/src/main/java/org/apache/geode/pdx/internal/ClientTypeRegistration.java
geode-core/src/main/resources/META-INF/schemas/geode.apache.org/schema/cache/cache-1.0.xsd

GEODE-5771: Deprecate PDX Persistence on Client
Currently, even when set, the PDX metadata is not persisted on the
client side (to avoid dealing with problems that might arise if the
client's PDX data is inconsistent with the server).
- Methods `setPdxPersistent` and `setPdxDiskStore` from
`ClientCacheFactory` have been deprecated.
- Attributes `persistent` and `disk-store-name` from the element `pdx`
have been deprecated (new complex type `client-pdx-type` has been
added to avoid messing with the pdx definition used for non-clients).
- A `warning` message will now be logged when creating the cache if we
detect that PDX persistence has been configured for a client cache.
- Added test methods to `ClientCacheFactoryJUnitTest`, also replaced
the usage of `junit.Assert` by `assertj`, and …

GEODE-5771: Deprecate PDX Persistence on Client

---

geode-core/src/integrationTest/java/org/apache/geode/internal/logging/LogServiceIntegrationJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/logging/log4j/GeodeVerboseLogMarkerIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/logging/log4j/custom/CustomConfigWithCacheIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/logging/log4j/custom/CustomConfigWithLogServiceIntegrationTest.java
geode-core/src/main/java/org/apache/geode/internal/Banner.java
geode-core/src/main/java/org/apache/geode/internal/logging/LogService.java

Two small commits that are part of GEODE-2644:
```
commit 46285f1ca33bcf2abd18382fd9996684e67be920 (HEAD -> GEODE-2644-Appenders-cleanup-LogService, kirklund-fork/GEODE-2644-Appenders-cleanup-LogService)
Date:   Thu Sep 27 16:04:25 2018 -0700
GEODE-2644: Cleanup LogService
Rename variables, remove SuppressWarnings, remove unused code.
commit 6d5701709bd5558dec9f279602dbd1598ec0a770
Date:   Thu Sep 27 15:58:00 2018 -0700
GEODE-2644: Rename LogService getConfigInformation to getConfigurationInfo
```

GEODE-2644: Cleanup LogService

---

geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/GfshParserAutoCompletionTest.java

Improve assertions so that failures in this test can be
diagnosed without using the IDE debugger.
This test is failing on my branch for GEODE-2644 but
the failure messages are very cryptic. This simple change
makes the assertion messages easy to understand. Since
this is valuable on develop, I'd like to merge the test change
to develop.

GEODE-2644: Improve GfshParserAutoCompletionTest assertions

---

geode-core/src/main/java/org/apache/geode/internal/logging/LogFileParser.java
geode-core/src/main/java/org/apache/geode/internal/logging/LogWriterImpl.java
geode-core/src/main/java/org/apache/geode/internal/logging/MergeLogFiles.java
geode-core/src/main/java/org/apache/geode/internal/logging/SortLogFile.java

Use org.apache.commons.lang.SystemUtils.LINE_SEPARATOR instead of \n.
These are all of the hardcoded \n I could find in a the internal.logging package (and sub-packages) except for the chars in LogWriterImpl#formatText.
I left LogWriterImpl#formatText alone. This method is iterating over chars and decrementing a count for every \n and \r found. Since this is dealing with char instead of String and it actually works on Windows as written, I left it alone for now. We can eventually rewrite this method with some new unit tests but that's a little more work than just replacing \n with LINE_SEPARATOR.

GEODE-2644: Use LINE_SEPARATOR in logging classes

---

geode-core/src/integrationTest/resources/org/apache/geode/internal/logging/log4j/ConsoleAppenderWithLoggerContextRuleIntegrationTest_log4j2.xml
geode-core/src/integrationTest/resources/org/apache/geode/internal/logging/log4j/ConsoleAppenderWithSystemOutRuleIntegrationTest_log4j2.xml

Use HexThreadIdPatternConverter in two more tests that were introduced after fixing GEODE-5776.

GEODE-5776: Use HexThreadIdPatternConverter in tests

---

geode-core/src/distributedTest/java/org/apache/geode/management/JMXMBeanReconnectDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/MemberVM.java

Signed-off-by: Jens Deppe <jdeppe@pivotal.io>

GEODE-5794: fix failing JMXMBeanReconnectDUnitTest

---

geode-core/src/integrationTest/resources/org/apache/geode/distributed/LocatorLauncherRemoteWithCustomLoggingIntegrationTest_log4j2.xml
geode-core/src/integrationTest/resources/org/apache/geode/distributed/ServerLauncherRemoteWithCustomLoggingIntegrationTest_log4j2.xml
geode-core/src/integrationTest/resources/org/apache/geode/internal/logging/log4j/ConsoleAppenderWithSystemOutRuleIntegrationTest_log4j2.xml
geode-core/src/integrationTest/resources/org/apache/geode/internal/logging/log4j/custom/CustomConfigWithCacheIntegrationTest_log4j2.xml
geode-core/src/integrationTest/resources/org/apache/geode/internal/logging/log4j/custom/CustomConfigWithLogServiceIntegrationTest_log4j2.xml
geode-core/src/main/resources/log4j2-cli.xml
geode-core/src/main/resources/log4j2.xml
geode-core/src/main/resources/org/apache/geode/internal/logging/log4j/log4j2-legacy.xml
geode-core/src/test/resources/org/apache/geode/internal/logging/log4j/marker/log4j2-gemfire_verbose-accept.xml
geode-core/src/test/resources/org/apache/geode/internal/logging/log4j/marker/log4j2-gemfire_verbose-deny.xml
geode-core/src/test/resources/org/apache/geode/internal/logging/log4j/marker/log4j2-geode_verbose-accept.xml
geode-core/src/test/resources/org/apache/geode/internal/logging/log4j/marker/log4j2-geode_verbose-deny.xml
geode-core/src/test/resources/org/apache/geode/test/golden/log4j2-test.xml

This changes the level from FATAL to WARN. WARN is the default.
StatusLogger is the internal Log4J2 logger used by Appenders,
PatternConverters, etc. WARN level is the default and it will be
silent unless we introduce a bug into one of the custom Appenders
or PatternConverters in Geode.

GEODE-5799: Set StatusLogger level to WARN

---

buildSrc/src/main/groovy/org/apache/geode/gradle/RepeatTest.groovy
ci/scripts/repeat-new-tests.sh
geode-assembly/build.gradle
gradle/docker.gradle
gradle/test.gradle

Because test classpaths can differ between source sets and modules, we should keep them separate, rather than combining them as `repeatTest` was doing before.
This PR removes the original `repeatTest` task and replaces it with one repeat test task per source set.
We tested the PR script by replacing most of `execute_tests.sh` with a single `bash` call and running locally.

GEODE-5781: split repeatTest into separate tasks

---

geode-dunit/src/main/java/org/apache/geode/test/dunit/standalone/DUnitLauncher.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/standalone/ProcessHolder.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/standalone/ProcessManager.java

* Removed getter on ProcessHolder to get underlying  process
* Added waitFor to ProcessHolder
* Added getters to get underlying process error & input stream
Signed-off-by: Sai Boorlagadda <sboorlagadda@pivotal.io>

GEODE-5787: extract ProcessHolder to be an outer class

---

geode-core/src/main/java/org/apache/geode/internal/AbstractConfig.java
geode-core/src/main/java/org/apache/geode/internal/i18n/LocalizedStrings.java
geode-core/src/test/java/org/apache/geode/internal/AbstractConfigTest.java

Add new characterization tests for AbstractConfig.setAttribute

GEODE-5784: Remove unused duplicate condition from AbstractConfig

---

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TcpServerJUnitTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpServer.java
geode-core/src/main/java/org/apache/geode/internal/InternalDataSerializer.java
geode-core/src/test/java/org/apache/geode/internal/InternalDataSerializerJUnitTest.java

Attempting to make handling of EOFException and SocketException consistent.  This exception handling and an Assert were the only differences between readDataSerializable(DataInput) and readDataSerializableFixedID(DataInput), so we refactored that and were able to delete the FixedID version of the method.
It doesn't make sense that we would handle EOFException and SocketException in readDataSerializable(DataInput), but not in readDataSerializableFixedID(DataInput).  Looking back at the history of the original EOFException handling in readDataSerializable(DataInput), it looks like this was a quick patch fix because this exception was seen/unhandled in readDataSerializable(DataInput), but there is no reason the same issue couldn't happen in the readDataSerializableFixedID(DataInput) method …

GEODE-5747: Handling SocketException consistently

---

extensions/geode-modules-session/build.gradle
extensions/geode-modules-test/build.gradle
extensions/geode-modules-tomcat7/build.gradle
extensions/geode-modules-tomcat8/build.gradle
extensions/geode-modules-tomcat8/src/distributedTest/java/org/apache/geode/modules/session/Tomcat8SessionsClientServerDUnitTest.java
extensions/geode-modules-tomcat8/src/distributedTest/java/org/apache/geode/modules/session/Tomcat8SessionsDUnitTest.java
extensions/geode-modules/build.gradle
gradle/dependency-versions.properties

* upgrade dependency version
* exclude test lib to pull in a old version of xerces
* AuthConfigFactory needs to be turned off in the test with newer version of tomcat libs

GEODE-3: upgrade tomcat7/tomcat8 library to be java9 compatible

---

geode-core/src/main/java/org/apache/geode/internal/cache/TXCommitMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXFarSideCMTracker.java
geode-core/src/test/java/org/apache/geode/internal/cache/TXCommitMessageTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/TXFarSideCMTrackerTest.java

* Always send CommitProcessQueryMessage to other replicates to see if anyone received second 
message as transaction originator for client transaction will be different from transaction host.
* Do not wait for transaction originator to depart when processing CommitProcessQueryMessage if 
transaction host is crashed. Originator may not be the same as the crashed transaction host and 
never departs from the distributed system.

GEODE-5828: fixes replicates miss transaction commit.

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreateJndiBindingCommandDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/GfshParseResult.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateJndiBindingCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/UsernamePasswordInterceptor.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/UsernamePasswordInterceptorTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/shell/GfshExecutionStrategyTest.java

Added Intercepter to CreateJndiCommand to prompt for user name and
password.
Modified GfshParseResult to allow update of the user input text.
When the command parsing occurs again on the remote side, the
modified user input will be used to determine function parms.
Added tests to cover new interceptor and modified tests to cover
new funcitonality for GfshExecutionStrategy and
CreateJndiBindingCommand.
Co-authored-by: Rob Day-Reynolds <rdayreynolds@pivotal.io>
Please ensure that once …

GEODE-5711: Gfsh prompt for JNDI username and password

---

geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/wancommand/CreateGatewayReceiverCommandDUnitTest.java

- There is a subtle, low-level networking issue on Windows. See here
https://stackoverflow.com/questions/52653506/udp-socket-binding-and-sending-behavior-on-windows-1709
and here
https://serverfault.com/questions/934207/socket-binding-and-sending-on-different-addresses

GEODE-5829: Do not bind to both localhost and the actual address of the host

---

geode-assembly/build.gradle
geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/ContainerInstall.java
geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/TomcatInstall.java
geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/GenericAppServerInstall.java
geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/TomcatSessionBackwardsCompatibilityTestBase.java
gradle/dependency-versions.properties

We were downloading full installs of tomcat and jetty on every test run.
This occasionally resulted in test failures if the download site was
down. Now we get this installs as gradle dependencies, which will be
cached.

GEODE-5811: Get gradle to cache tomcat and jetty installs

---

geode-core/src/main/resources/log4j2-cli.xml
geode-core/src/main/resources/log4j2.xml
geode-core/src/main/resources/org/apache/geode/internal/logging/log4j/log4j2-legacy.xml
geode-core/src/test/resources/org/apache/geode/test/golden/log4j2-test.xml

When GEODE-2644 is merged to develop, we should be able to change
the StatusLogger level back down to WARN.
This will prevent this noise:
```
2018-10-06 23:19:31,304 DisconnectThread ERROR Attempted to append to non-started appender org.apache.geode.internal.logging.log4j.LogWriterAppender-org.apache.geode
2018-10-06 23:19:31,405 DisconnectThread ERROR Attempted to append to non-started appender org.apache.geode.internal.logging.log4j.LogWriterAppender-org.apache.geode
2018-10-06 23:19:31,405 DisconnectThread ERROR Attempted to append to non-started appender org.apache.geode.internal.logging.log4j.LogWriterAppender-org.apache.geode
2018-10-06 23:27:09,989 vm_15_thr_35_dataStore1_host1_20973 ERROR Attempted to append to non-started appender …
```

GEODE-5799: Restore StatusLogger level to FATAL

---

geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionBulkOperationTest.java

GEODE-5849: Do not wrap CacheClosedException if client cache is closing.

---

geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
geode-core/src/main/java/org/apache/geode/internal/net/SSLConfigurationFactory.java
geode-core/src/main/java/org/apache/geode/internal/security/SecurableCommunicationChannel.java
geode-core/src/test/java/org/apache/geode/internal/net/SSLConfigurationFactoryJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/security/SecurableCommunicationChannelTest.java
geode-docs/managing/security/implementing_ssl.html.md.erb

GEODE-5830: Fix `NONE` enum for SSL configuration
The `SecurableCommunicationChannel.NONE` enum instance now references
the correct constant string, `none`, instead of `NO_COMPONENT`.

GEODE-5830: Fix `NONE` enum for SSL configuration

---

geode-assembly/build.gradle

Previous exclusion would count executable files named 'build' or 'out'
regardless of path, when we only want to exclude the build-tools output
directories.

Better path resolution for srcDist exclusions

---

gradle/publish.gradle

* Add `updateExpectedPom` task to perform copy of actual to expected.
----

GEODE-5804: Improve checkPom task

---

ci/pipelines/geode-build/jinja.template.yml

[GEODE-5864] UpdatePassingRef doesn't need docker-geode-build-image.

---

ci/pipelines/geode-build/jinja.template.yml

[GEODE-5864] Get rid of docker-geode-build-resource.

---

geode-docs/basic_config/data_entries_custom_classes/managing_data_entries.html.md.erb
geode-docs/basic_config/data_entries_custom_classes/using_custom_classes.html.md.erb

GEODE-5845 Document not to use enums for keys

---

buildSrc/src/main/groovy/org/apache/geode/gradle/RepeatTest.groovy

The RepeatTest task was not retaining the workerProcessFactory installed
by the docker plugin, because the new version of the docker plugin used
a different implementation of TestExcecutor.

GEODE-5893: Keep docker configuration in RepeatTest

---

ci/scripts/execute_tests.sh

This fixes previous pull request for Windows platform.

GEODE-5906 no chmod on windows

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/MockAppender.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/PersistentColocatedPartitionedRegionDUnitTest.java

This test had a number of tests making assertions about log messages.
Unfortunately, these tests had assertions inside of a try/finally block,
and the finally had a return. Therefore the assertion failures were
simply ignored, and the test was just a test that the callables returned
in 60 seconds.
Fixing this test by removing the bad verify calls and returns in finally
blocks.
Cleaning up the way the tests hooked into the logging system.
email to …

GEODE-4872: Fixing logging tests in PersistentColocatedPartitionedRegionDUnitTest

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/commands/StartLocatorAcceptanceTest.java
geode-core/src/main/java/org/apache/geode/admin/DistributedSystemConfig.java
geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java
geode-core/src/main/java/org/apache/geode/internal/tcp/TCPConduit.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java
geode-docs/configuring/running/firewalls_ports.html.md.erb
geode-docs/reference/topics/gemfire_properties.html.md.erb

Currently the default range for membership ports is 1024-65535.  This results
in occassional failures where a random membership port selection will conflict
with the default server or locator port when using all default values.
This change modifies the default range to 41000-61000.  In addition to not
conflicting with any of the default ports (highest is 40404), this is also a
proper subset of the default Linux ephemeral port range (32768-61000).
email to …

GEODE-5742: Restrict default membership range to not conflict with default ports

---

gradle/test.gradle

Changing the repeatXXXTest tasks to copy the dependencies from their
source task.

GEODE-5902: Fixing repeatTest task dependencies

---

geode-core/src/main/java/org/apache/geode/internal/cache/persistence/DiskStoreID.java
geode-core/src/test/java/org/apache/geode/internal/cache/persistence/DiskStoreIDJUnitTest.java

@dschneider-pivotal @boglesby @bschuchardt @jhuynh1 

GEODE-5908: DiskStoreID.compare should compare mostSig, then leastSig

---

ci/scripts/repeat-new-tests.sh
gradle/docker.gradle

Not all acceptance tests can be run in parallel in docker containers, so
disabling them in StressNewTest.
Also, enabling docker for acceptance tests if the user has configured
docker. We were getting hard to diagnose failures when running
repeatAcceptanceTest with docker configured, because the build silently
ignored the docker settings. Now the build will not ignore those
settings, so acceptance tests than *can* run in
docker will, and tests that cannot will consistently fail with a docker
related error.
submit an update to your PR as …

GEODE-5910: Disabling acceptance tests in StressNewTest

---

geode-core/src/main/java/org/apache/geode/cache/Operation.java
geode-core/src/main/java/org/apache/geode/internal/cache/BucketAdvisor.java
geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionDataStore.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PutAllPRMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/RemoveAllPRMessage.java
geode-core/src/test/java/org/apache/geode/internal/cache/BucketRegionJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/BucketRegionTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/PutAllPRMessageTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/RemoveAllPRMessageTest.java

* A bulk opertion could remove lockObject due to RegionDestroyedException.
* Do not allow a new operation to proceed without checking region readiness.

GEODE-5888: Check partitioned region is ready in bucket region

---

geode-assembly/src/distributedTest/java/org/apache/geode/rest/internal/web/controllers/RestAPIsWithSSLDUnitTest.java

* refactor RestAPIsWithSSLDUnitTest to use rules
* use supported cipher suites across jdk versions.

GEODE-5819: use cipher suites supported across jdk versions

---

geode-core/src/distributedTest/java/org/apache/geode/management/DistributedSystemDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/ManagementListener.java
geode-core/src/test/java/org/apache/geode/management/internal/beans/ManagementListenerTest.java

```
commit 9fdb6597cd5df3899fb791d1c81dbfe9e27dfaf5 (HEAD -> GEODE-5915-Alert-warning, kirklund-fork/GEODE-5915-Alert-warning)
Date:   Tue Oct 23 14:47:58 2018 -0700
GEODE-5915: Fix IllegalMonitorStateException logged for Alerts
* Prevent IllegalMonitorStateException in ManagementListener.
* Pass in InternalDistributedSystem to prevent singleton fetches.
* Create unit tests for ManagementListener.
```
```
commit 651d2058ef33630f2e83a16a6a4f4bf4a56eb782
Date:   Tue Oct 23 14:46:38 2018 -0700
GEODE-5915: Cleanup DistributedSystemDUnitTest
* Remove unnecessary this qualifiers.
* Minor whitespace changes.
```

GEODE-5915: Fix IllegalMonitorStateException logged for Alerts

---

ci/images/alpine-tools/Dockerfile

Now that all build and test and combine-reports is being done on heavy lifters, there's no longer any need to include java in the concourse worker image.

GEODE-5929 concourse workers no longer need java

---

geode-dunit/src/main/java/org/apache/geode/test/dunit/standalone/DUnitLauncher.java

The suspect appender is added programmatically without a log4j2.xml
so there's no way to specify additional plugin packages.
Change hexTid back to tid to prevent error messages about not
finding the HexThreadIdPatternConverter.

GEODE-5827: Use standard pattern converters in suspect appender

---

geode-core/src/integrationTest/java/org/apache/geode/management/DistributedSystemMXBeanIntegrationTest.java
geode-core/src/main/java/org/apache/geode/internal/admin/remote/AlertLevelChangeMessage.java
geode-core/src/main/java/org/apache/geode/internal/admin/remote/AlertListenerMessage.java
geode-core/src/main/java/org/apache/geode/management/internal/FederatingManager.java
geode-core/src/main/java/org/apache/geode/management/internal/ManagerStartupMessage.java
geode-core/src/main/java/org/apache/geode/management/internal/MemberMessenger.java

* Create DistributedSystemMXBeanIntegrationTest
* Add ignored test for bug GEODE-5923
* Cleanup alert related classes and add lots of javadocs
This does NOT fix GEODE-5923. This PR just adds a disabled test that confirms the bug and then cleans up alert related classes and adds lots of comments to them to explain how things work.

GEODE-5923: Add test for local alerts and cleanup classes

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/wan/asyncqueue/ParallelAsyncEventListenerDistributedTest.java

AbstractMovingAsyncEventListener.processEvents() recorded keys using
unsynchronized modification of a HashSet, though some tests could call
the method concurrently on as many as 3 threads.
AbstractMovingAsyncEventListener now uses a synchronized set to record
keys.
Please review @upthewaterspout @kirklund

GEODE-5764: Use a thread-safe set to record keys

---

geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java

* While this is unlikely to correct the Java11 SSL handshake failures, it should make tests currently hanging properly fail out so that a full failure-set can be analyzed.

GEODE-5819: Reduce 16h40m wait on shutdown to intended 60 seconds.

---

geode-core/src/main/java/org/apache/geode/internal/cache/ColocationHelper.java
geode-core/src/test/java/org/apache/geode/internal/cache/ColocationHelperTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/concurrent/ConcurrentParallelGatewaySenderDUnitTest.java

Move assertion on region size to an async invoke, join the thread doing
puts, then join the thread doing the assertions. There was a bug in this
test where the thread doing puts would not progress far enough by the
time the awaitility timed out for region size being 20 entries greater
than the previous region size. Setting off the awaitility as an async
invocation and joining the put thread allows more puts to reliably occur
before the awaitility times out. …

GEODE-5797: Move assertion to async invoke

---

ci/images/google-geode-builder/scripts/setup.sh
ci/pipelines/images/jinja.template.yml

The Java 11.0.1 release exposed an oversight in the new pipeline: some triggers were not in place to ensure images were rebuilt with the new version.
With this fix, the linux image now grabs the latest released version of OpenJDK11 (instead of a hardcoded version), and both linux and windows images are triggered once a week (for lack of a better way to know when there is a new chocolatey update for windows or a change to download link for linux).

GEODE-5950 ensure images pick up new Java11 versions

---

geode-connectors/src/main/resources/META-INF/services/org.springframework.shell.core.CommandMarker

Remove the references to the JDBC connection commands
[GEODE-5945]

GEODE-5945: Remove ref to JDBC connection commands

---

ci/pipelines/geode-build/jinja.template.yml

GEODE-5864: Add GLOBAL_GRADLE_ARGS to PublishArtifacts.

---

geode-docs/tools_modules/http_session_mgmt/tomcat_installing_the_module.html.md.erb

This is a fix to the Geode docs for tomcat session module.
See: https://geode.apache.org/docs/guide/12/tools_modules/http_session_mgmt/tomcat_installing_the_module.html

GEODE-5961: Add commons-validator jar to tomcat dependencies

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/fixed/FixedPartitioningWithTransactionDistributedTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXManagerImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXStateProxyImpl.java
geode-core/src/test/java/org/apache/geode/internal/cache/TXManagerImplTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/TXStateProxyImplTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/CacheRule.java

* to be able to detect primary bucket has moved due to rebalance.
* add debug level logging for transaction.

GEODE-5953: set target member when transaction hosted locally

---

geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/ResourceManagerWithQueryMonitorDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PRQueryDistributedTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/query/QueryJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/index/CompactRangeIndexJUnitTest.java
geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-core/src/main/java/org/apache/geode/cache/query/internal/DefaultQuery.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/HashIndex.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/MemoryIndexStore.java
geode-core/src/main/java/org/apache/geode/distributed/internal/streaming/StreamingOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/PRQueryProcessor.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionQueryEvaluator.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/QueryMessage.java
geode-cq/src/distributedTest/java/org/apache/geode/cache/query/dunit/QueryMonitorDUnitTest.java

Consolidate three interface methods into one that takes an enum
to identify the "spot" in the query processing logic.
Co-authored-by: Galen O'Sullivan <gosullivan@pivotal.io>
- N/A If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
submit an update to your PR as soon as possible. If you need help, please send …

GEODE-5881: simplify DefaultQuery.TestHook

---

geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/ConnectionsCommandManagerJUnitTest.java

Added a new test to the JDBC connector project to verify that the list
of commands loaded via the scanner and the command marker match the list
of commands found via these two sources. This is to avoid
errors/warnings due to commands which appear in Command Marker files but
don't have available source code.

GEODE-5960: Add test to verify CommandMarker file for the JDBC connector

---

geode-docs/managing/security/implementing_ssl.html.md.erb
geode-docs/reference/topics/gemfire_properties.html.md.erb

The property has already been implemented. This is its documentation.

GEODE-5338: Document 'ssl-use-default-context' property

---

geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/JdbcDistributedTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/AlterMappingCommandDUnitTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommandDUnitTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommandDUnitTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyMappingCommandDunitTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/JdbcClusterConfigDistributedTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/ListMappingCommandDUnitTest.java
geode-connectors/src/integrationTest/java/org/apache/geode/connectors/jdbc/internal/cli/AlterMappingCommandIntegrationTest.java
geode-connectors/src/integrationTest/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommandIntegrationTest.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/SqlToPdxInstanceCreator.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/AlterMappingCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/AlterMappingFunction.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/configuration/RegionMapping.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/xml/ElementType.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/xml/JdbcConnectorServiceXmlParser.java
geode-connectors/src/main/resources/META-INF/schemas/geode.apache.org/schema/jdbc/jdbc-1.0.xsd
geode-connectors/src/main/resources/org/apache/geode/internal/sanctioned-geode-connectors-serializables.txt
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/RegionMappingTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/SqlToPdxInstanceCreatorTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/AlterMappingCommandTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/AlterMappingFunctionTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommandTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/xml/ElementTypeTest.java

Renamed the xsd "pdx-class" to "pdx-name".
Renamed the gfsh "--pdx-class-name" to "--pdx-name".
@BenjaminPerryRoss 
@monkeyherder 

GEODE-5967: change pdx-class-name to pdx-name

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Destroy.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Destroy65.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/Destroy65Test.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/DestroyTest.java

Also fixed new Object[] mistake in log statement in Destroy65
that was introduced by changes for GEODE-5686.

GEODE-5963: Change destroy no entry found log statement to debug

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/JdbcConnectorServiceImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/DumpB2NRegion.java

* no method invocation on de-referenced objects.

GEODE-5981: No operations on null values

---

geode-junit/src/main/java/org/apache/geode/test/awaitility/GeodeAwaitility.java
geode-junit/src/test/java/org/apache/geode/test/awaitility/GeodeAwaitilityTest.java

Add getTimeout to allow the default timeout to be used for more than
just Awaitility (for example, with Mockito.timeout).
Add toTimeDuration to facilitate conversions between java.time.Duration
and org.awaitility.Duration.
Make timeout non-static for testing and write some unit tests.
NOTE: I'm using these changes in PR #2778.

GEODE-5978: Expand GeodeAwaitility and add test coverage

---

ci/images/google-windows-geode-builder/windows-packer.json

added -ErrorAction ignore to ensure we continue the script if the
process does not need to be killed because it has already exited.
email to …

GEODE-6003 don't fail if we can't kill a process because it's already exited

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/ExecuteRegionFunctionOp.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/ExecuteRegionFunctionOpTest.java

* Add to exception list If the cause of the FunctionException 
is FunctionInvocationTargetException

GEODE-5884: Adding to function exception list if matching cause

---

build.gradle
geode-assembly/build.gradle
geode-core/build.gradle
geode-old-versions/build.gradle
geode-pulse/build.gradle
gradle.properties
gradle/dependency-resolution.gradle
gradle/spotless.gradle
gradle/utilities.gradle
settings.gradle

* gradle.startParameter.continueOnFailure moved to settings.gradle
* Project properties group and scriptDir moved to gradle.properties
* Removed unnecessary import and semicolons in *.gradle
* Improved property and task comments
-----
- [Build is Build] Have you written or updated unit tests to verify your changes?
submit an update to your PR as …

GEODE-6019: Move gradle constants in constants files.

---

ci/pipelines/pull-request/jinja.template.yml

GEODE-6009 add Java 11 to PR pipeline

---

ci/pipelines/geode-build/jinja.template.yml

This fix defers running Windows tests until the commit has first passed all Linux tests.  This will reduce resource usage when some test does not pass, and also alleviates the 18-jobs-tall stack we had in the Complete view.
submit an …

GEODE-6020 make non-gating jobs run only after all gating jobs have passed

---

geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/QueryMonitorIntegrationTest.java
geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
geode-core/src/jmh/java/org/apache/geode/cache/query/internal/MonitorQueryUnderContentionBenchmark.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/DefaultQueryService.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/QueryMonitor.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/QueryMessage.java
geode-core/src/test/java/org/apache/geode/cache/query/internal/QueryMonitorTest.java

A race existed between setting low memory in the heap monitor thread,
and checking the low memory state in query monitoring thread.
The cancelation executor was shut down and no longer accepting new
tasks when this race occurred, causing a RejectedExecutionException.
This commit solves that problem by encapsulating the scheduling
behavior using the state design pattern.
Co-authored-by: Ryan McMahon <rmcmahon@pivotal.io>
- N/A If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF …

GEODE-5993: Eliminate race in monitorQueryThread()

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreateJndiBindingCommandDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DestroyJndiBindingCommandDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/VMProvider.java

GEODE-5873: Fix VMProvider.invokeInEveryMember
Method `invokeInEveryMember` from `VMProvider` ends up being a no-op
when the array of members is empty or null.
- Fixed tests `CreateJndiBindingCommandDUnitTest` and
`DestroyJndiBindingCommandDUnitTest`, they weren't fully validating
the result.
- Method `invokeInEveryMember` now validates its parameters, throwing
an exception when the arguments are invalid.

GEODE-5873: Fix VMProvider.invokeInEveryMember

---

geode-dunit/src/main/java/org/apache/geode/test/junit/rules/VMProvider.java

GEODE-6042: Fix commons-lang import
- VMProvider now imports the correct commons-lang version.

GEODE-6042: Fix commons-lang import

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CommandInitializer.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunction66.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunctionGeode18.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunctionGeode18Test.java
geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgradeNonHAFunction.java

* Due to the refactor that caused us to lose wrapping of exceptions,
the fix to GEODE-5884 cannot be applied to GEODE 1.0-1.7 clients
* Adding new command class will allow clients to identify which function class
it is expecting to execute and what behavior to expect

GEODE-5884: Setting function waitOnException flag only for newer clients

---

gradle/publish.gradle

before this fix, ./gradlew build install will fail on release branch
with this fix, now it will succeed (signing will only be attempted if
signing properties are set)

GEODE-6048 build should work on release branches

---

geode-core/src/integrationTest/java/org/apache/geode/management/internal/beans/DistributedSystemBridgeIntegrationTest.java
geode-core/src/test/java/org/apache/geode/management/internal/beans/DistributedSystemBridgeJUnitTest.java

GEODE-3835: Use TemporayFolder instead of /tmp
- Replaced the usage of `junit.Assert` by `assertj`.

GEODE-3835: Use TemporayFolder instead of /tmp

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/eviction/EvictionDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/PartitionedRegionIntegrationTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/VMProvider.java

GEODE-4712 GEODE-5943: shut down the bucketSorter when destroying the partitioned region

---

geode-core/src/integrationTest/java/org/apache/geode/cache/query/functional/IndexUsageInNestedQueryWithParamsJUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledID.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledIndexOperation.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledOperation.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledPath.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledValue.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/QueryUtils.java
geode-core/src/test/java/org/apache/geode/cache/query/internal/AbstractCompiledValueTestJUnitTest.java

* Parameterized queries were throwing UnsupportedOperationExceptions.
* This was because of trying to pre-compute values for join optimization.
* When the query was parameterized it is not possible to compute these values and hence these exceptions are thrown
* The fix was to prevent this computation when it is not needed or not possible.

GEODE-6053: Parameterized Queries fixed

---

ci/scripts/repeat-new-tests.sh

This job was failing because concourse was no longer creating an origin
remote in the git repo.
Also, changing the script to fail if there are issues with some of
commands we are executing in $().

GEODE-6059: Get ahold of origin/develop in StressNewTests

---

geode-assembly/src/distributedTest/java/org/apache/geode/rest/internal/web/controllers/RestAPIsWithSSLDUnitTest.java
geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/JdbcDistributedTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/ClientHealthStatsDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/security/MultiClientDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/security/MultiUserAuthenticationDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/security/ClientAuthDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/security/ClientAuthorizationLegacyConfigurationDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/security/ClientDataAuthorizationUsingLegacySecurityDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/security/ClientDataAuthorizationUsingLegacySecurityWithFailoverDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/security/ClientDestroyInvalidateAuthDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/security/ClientExecuteFunctionAuthDUnitTest.java
geode-cq/src/distributedTest/java/org/apache/geode/cache/query/dunit/QueryMonitorDUnitTest.java
geode-cq/src/distributedTest/java/org/apache/geode/security/ClientCQAuthDUnitTest.java
geode-cq/src/distributedTest/java/org/apache/geode/security/MultiUserAPIDUnitTest.java
geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/ClusterStartupRuleCanSpecifyOlderVersionsDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/security/SecurityTestUtil.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/MemberVM.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/ClientCacheRule.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/MemberStarterRule.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/ServerStarterRule.java

* refactored a couple of MultiUser tests to use the ClientCacheRule
* add more convenience methods in ClientCacheRule
* clean up the ClusterStarterRule.startClient interface
* deprecate the SecurityTestUtils to favor using rules

GEODE-4110: improve junit ClientCacheRule

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartServerCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/lifecycle/StatusLocatorCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/lifecycle/StopLocatorCommand.java

GEODE-5971: Refactor Start/Status/Stop Locator commands to return ResultModel

---

.gitattributes
ci/scripts/windows/test-run.sh
gradle/spotless.gradle

- Spotless no longer uses line endings check as it is not recommened
- https://github.com/diffplug/spotless/tree/master/plugin-gradle#line-endings-and-encodings-invisible-stuff
Conversation [here ](https://markmail.org/message/2jippxjsl6a6r6ae )for those who want to follow along
~~- [ ] Have you written or updated unit tests to verify your changes?~~
~~- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?~~
Please ensure that once the PR is submitted, you check travis-ci for build issues …

GEODE-6073:  All files have lf endings

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/PooledConnection.java
geode-core/src/main/java/org/apache/geode/distributed/internal/membership/InternalDistributedMember.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/GatewaySenderEventRemoteDispatcherIntegrationTest.java

Throw a ServerConnectivityException instead of a GemFireConfigException when hostname lookup fails because:
1) The WAN event processor will sleep and retry on ServerConnectivityException, but will shut down due to the a GemFireConfigException.  In this case, we are dealing with an intermittent failure to lookup an IP address by hostname, so we should sleep and retry.
2) ServerConnectivityException conceptually makes more sense.  GemFireConfigException is intended for issues involving configuration i.e. cache.xml.
Co-authored-by: Ryan McMahon <rmcmahon@pivotal.io>
- N/A If …

GEODE-6065: Continue event processing when hostname lookup fails

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/commands/ConfigureEvictionThroughGfsh.java

This should help reduce the frequency of random CI failures for this
test. It's still a bit worrisome that servers were using the same port
in the first place, but that's not really what we're testing here.
Co-authored-by: Galen O'Sullivan <gosullivan@pivotal.io> …

GEODE-6062: Use random server port for ConfigureEvictionThroughGfsh

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateGatewayReceiverCommand.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateGatewayReceiverCommandTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/wancommand/CreateGatewayReceiverCommandDUnitTest.java

GEODE-5667: Fix manual-start default value
- Fixed minor warnings in test classes.
- The `create gateway-receiver` command now sets the `manual-start`
property as `true` when the parameter is specified without a value.

GEODE-5667: Fix manual-start default value

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/commands/LogsAndDescribeConfigAreFullyRedactedAcceptanceTest.java
geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/commands/PutCommandWithJsonTest.java

GEODE-5590 and GEODE-6074 - Setting the server port to 0 to pick an
unused port. These two tests both failed in CI because port 40404 was in
use.

GEODE-6074: Using a free server port in tests

---

geode-lucene/src/distributedTest/java/org/apache/geode/cache/lucene/LuceneIndexDestroyDUnitTest.java

Java MemoryUsage object has a new exception in Java9+ that is not fixed
until Java 12. Add an ignore to the log checker to ignore the suspect
string.

GEODE-6046 - Java memory allocation issue JDK-8207200

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/security/MultiUserAuthenticationDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/security/ClientAuthDUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/RegionService.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ClientSideHandshakeImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/PoolImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ProxyCache.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalCacheForClientAccess.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheCreation.java
geode-core/src/main/java/org/apache/geode/pdx/JSONFormatter.java
geode-cq/src/distributedTest/java/org/apache/geode/security/MultiUserAPIDUnitTest.java
geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/ClusterStartupRuleCanSpecifyOlderVersionsDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/MemberStarterRule.java

* user does not have to provide credentials when creating the client cache in multi-user mode. Credentials are needed only when creating the view.
* CacheProxy should have a reference to the JSONFormatter that is aware of the user attributes
* clean up some tests and add more tests for coverage and usage demo.

GEODE-6078: Allow client cache to use JSONFormatter in multi-user mode

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PersistentRegionRecoveryDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/InitialImageOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/versions/RegionVersionVector.java
geode-core/src/test/java/org/apache/geode/internal/cache/versions/RegionVersionVectorTest.java

Re-submitting after fixing NPE from previous checkin.
Made changes to use the expected initial image requester's rvv
information instead of the image provider's local rvv while
determining full or delta GII.
There was logical error where it was using provider's local
exception(rvv) instead of using requester's local exception(rvv).
This could result in performing Delta GII instead of Full GII.
- [Yes ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?
- [Yes ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?
- [Yes] Is your initial …

GEODE-6013: Use expected initial image requester's rvv information

---

geode-assembly/build.gradle
geode-core/build.gradle
geode-cq/build.gradle
geode-dunit/build.gradle
geode-junit/build.gradle
geode-junit/src/test/resources/expected-pom.xml
geode-lucene/build.gradle
geode-wan/build.gradle
gradle/publish.gradle

Old versions are only used by tests, not any production runtime. Do not
publish to Maven that we need it for all runtime. Mark the modules that
need old-versions for testing appropriately.

GEODE-6105 convert geode-old-versions to xyzTestRuntime dependency

---

geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/ListDataSourceCommandDUnitTest.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/ListDataSourceCommand.java
geode-connectors/src/main/resources/META-INF/services/org.springframework.shell.core.CommandMarker
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/ListDataSourceCommandTest.java

list data-source uses the cluster config to determine what data sources exist.
It will show the following items for each data-source: name, is it pooled, is it in use, and the url.
Internally, data sources are stored as jndi-bindings. If a jndi-binding exists that could not have been created by create data-source, then list data-source will ignore that jndi-binding.

GEODE-6067: add list data-source gfsh command

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/DiskStoreFactoryIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/AlterDiskStoreCommandIntegrationTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/AlterOfflineDiskStoreCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CompactOfflineDiskStoreCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeOfflineDiskStoreCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/UpgradeOfflineDiskStoreCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ValidateDiskStoreCommand.java

GEODE-5342: Fix disk-store validation in commands
- Replaced the usage of `junit.Assert` by `assertj`.
- Offline gfsh comamnds related to disk-stores avoid creating the
disk-store's folder if it doesn't exist already.

GEODE-5342: Fix disk-store validation in commands

---

gradle.properties

GEODE-6111: Add gradle properties to extend http timeouts.

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/PutOp.java
geode-core/src/main/java/org/apache/geode/internal/cache/EntryEventImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionTest.java

* Check putIfAbsent return value from server if it could caused by retry.
* Make sure client putIfAbsent operation message.isRetry is set if it retries after failed when using singleHop.

GEODE-6108: Handle client putIfAbsent returns value due to retry

---

geode-core/build.gradle

This will fix the issue of IntelliJ builds sometimes not inheriting the
dependency from main at compile time. At worst, this line will be
redundant, at best it will provide the required dependency for the
build.

GEODE-6115: add log4j dependency to jmh compile

---

geode-junit/src/main/java/org/apache/geode/test/concurrent/CPUContentionService.java

Add a CPUContentionService utility to contend for CPUs during tests.
This can be added to a test while debugging, and removed after the
problem has been diagnosed.
Co-Authored-By: Dale Emery <demery@pivotal.io>
Co-Authored-By: Helena Bales <hbales@pivotal.io>

GEODE-5994: Add CPUContentionService

---

geode-core/build.gradle
geode-core/src/distributedTest/java/org/apache/geode/management/JMXMBeanReconnectDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/MemberVM.java

There exists a known race condition in starting locators such that if
two locators are started simultaneously, not all the MBeans get
federated to both members. This was causing intermittent test failures
in the before() of JMXMBeanReconnectDUnitTest. To fix this, a wait has
been added so that the first member has enough time to start before the
second one.

GEODE-6107: in test start locators one at a time

---

geode-core/src/main/java/org/apache/geode/management/internal/configuration/utils/ZipUtils.java

The unsanitized path of a zip archive entry, which may
contain '..', was used directly to resolve the destination
path for the files being unzipped.
Extracting files from a malicious archive without validating
that the destination file path is within the destination
directory can cause files outside the destination directory
to be overwritten.
I've checked where this method is used, and it seems to mostly be isolated to unit tests and some CLI commands / management stuff, so felt it is likely safe to publicly open a PR to fix this, especially given that the problem is already listed [as an alert on LGTM](https://lgtm.com/projects/g/apache/geode/alerts/?mode=tree&ruleFocus=1506728586782).
cc @bschuchardt (who has fixed a number of LGTM alerts before)
*(Full disclosure: I'm part of the team …

Fix ZipSlip bug found by LGTM.com

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxyTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxy.java

GEODE-6164: CacheClientProxy's closeSocket should be called atomically

---

geode-core/src/integrationTest/java/org/apache/geode/internal/AvailablePortHelperIntegrationTest.java
geode-core/src/main/java/org/apache/geode/internal/AvailablePort.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/ChildVM.java
geode-junit/src/main/java/org/apache/geode/internal/AvailablePortHelper.java

Rebased to current develop and no longer try to get keeper objects for UDP ports.  Also added better testing of the new behavior.

GEODE-5674: Stop using random values for test ports

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyMappingCommand.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommandTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyMappingCommandTest.java

Now `create jdbc-mapping` and `destroy jdbc-mapping` only target the members
that have the named region.
Authored-by: Jianxia Chen <jchen@pivotal.io>

GEODE-6197: Fix create and destroy jdbc-mapping

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ClientServerRepeatableReadTransactionDistributedTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/RepeatableReadTransactionDistributedTest.java
geode-core/src/integrationTest/java/org/apache/geode/TXJUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/EntriesSet.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalDataView.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegionDataView.java
geode-core/src/main/java/org/apache/geode/internal/cache/PausedTXStateProxyImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXEntry.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXState.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXStateInterface.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXStateProxyImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXStateStub.java

* Do not create txEntryState for entries with tombstones during set operations - keySet, values, etc.
* Only create txEntryState for tombstones during get operation.
Co-authored-by: lgallinat

GEODE-5786: Create txEntryState based on createIfAbsent condition.

---

geode-core/src/distributedTest/java/org/apache/geode/cache/ConnectionPoolDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache/client/internal/LocatorLoadBalancingDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/PartitionedRegionDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/distributed/LocatorDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/ColocationFailoverDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/QueueManagerJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/logging/MergeLogFilesIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/logging/log4j/LogWriterAppenderWithLimitsIntegrationTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java
geode-core/src/main/java/org/apache/geode/distributed/internal/ProductUseLog.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheCreation.java
geode-core/src/main/java/org/apache/geode/internal/jta/TransactionUtils.java
geode-core/src/main/java/org/apache/geode/internal/logging/LogFileParser.java
geode-core/src/main/java/org/apache/geode/internal/logging/LoggingThreadGroup.java
geode-core/src/main/java/org/apache/geode/internal/logging/log4j/LogWriterLogger.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/OpExecutorImplJUnitTest.java
geode-core/src/test/java/org/apache/geode/distributed/internal/ServerLocatorJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/logging/ManagerLogWriterTest.java

Use LogWriterLevel enum instead of InternalLogWriter constants.

GEODE-6122: Use LogWriterLevel instead of InternalLogWriter

---

geode-core/src/main/java/org/apache/geode/pdx/PdxRegistryMismatchException.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/misc/NewWanAuthenticationDUnitTest.java
geode-wan/src/main/java/org/apache/geode/internal/cache/wan/GatewaySenderEventRemoteDispatcher.java

Due to different handling in the GatewaySenderEventRemoteDispatcher
dispatcher and ack reader threads, it was possible for event processing
to stop when a GemFireSecurityException was encountered by the ack
reader connection retry logic.
This commit attempts to share common recoverable cases between the ack
reader and dispatcher, while maintaining the cases which are specific to
each.  We also added a test which ensures that if a connection is denied
due to invalid credentials upon a restart of the receiver, that the
sender can recover if it again provides valid credentials.  In the process,
we removed a significant amount of duplicated and noisy code in the
NewWanAuthenticationDUnitTests.
Co-authored-by: Ryan McMahon …

GEODE-6177: WAN Event processing continues after authentication fails

---

geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/JdbcAsyncWriterIntegrationTest.java
geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/JdbcDistributedTest.java
geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/JdbcLoaderIntegrationTest.java
geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/JdbcWriterIntegrationTest.java
geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/internal/TableMetaDataManagerIntegrationTest.java
geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/internal/TestConfigService.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/EntryColumnData.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/SqlHandler.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/SqlStatementFactory.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/TableMetaData.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/TableMetaDataManager.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/TableMetaDataView.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommand.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/SqlHandlerTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/SqlStatementFactoryTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/SqlToPdxInstanceCreatorTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/TableMetaDataManagerTest.java

create jdbc-mapping --id now accepts a comma separated list of column names.
The key object when using multiple id columns must be a json string that uses the pdx fields names that match those column names.

GEODE-6194: add composite keys to jdbc

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/NetstatDUnitTest.java

Failure of netstat command on the test instance was not being detected.

GEODE-6219: Add assertion to verify the OS commands really ran

---

ci/pipelines/shared/jinja.variables.yml
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/NetstatDUnitTest.java

Running gfsh command "netstat --with-lsof" to a file takes a very long time (> 30min)
when running on JDK8. However it takes only a few seconds with JDK11.
Test is therefore being @Ignore'd until we can figure out the problem.

GEODE-6219: Disable one more test that uses lsof

---

geode-core/src/integrationTest/java/org/apache/geode/internal/statistics/DiskSpaceLimitIntegrationTest.java

```
commit fa08408a1660e6dffbe15721343ce325e5ae933c
Date:   Fri Dec 21 13:59:53 2018 -0800
GEODE-3205: Cleanup and reenable DiskSpaceLimitIntegrationTest
Remove @Ignore added for duplicate ticket GEODE-5494.
Cleanup tests and improve failure messages.
```
```
commit 51b7e62d6f73cfdb8cf9165360ec5a118d51384e
Date:   Fri Dec 21 12:39:33 2018 -0800
GEODE-3205: Fix timestamp warning
```

GEODE-3205: Cleanup and reenable DiskSpaceLimitIntegrationTest

---

gradle/publish.gradle

When we switched to the Nexus plugin we stopped publishing
sources and javadoc artifacts.  These are useful for IDE integration.
Add tasks to ensure these get generated during publishing.

GEODE-6235 Publish sources and javadoc to maven

---

geode-core/src/main/java/org/apache/geode/internal/cache/execute/InternalFunctionService.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction65.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction66.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction70.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction65Test.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction66Test.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction70Test.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunctionTest.java

Remove PowerMock from:
* ExecuteFunctionTest
* ExecuteFunction65Test
* ExecuteFunction66Test
Add test for ExecuteFunction70Test by subclasses ExecuteFunction66Test.
There are two commits. 1st commit is the main one to review. 2nd and 3rd commits fix some log statements, reduce IDE warnings, etc.

GEODE-6143: Remove PowerMock from ExecuteFunction tests

---

geode-old-versions/build.gradle

From 1.8.0 onward we are only releasing tgz, so we need to consume those
instead of zip archives.

GEODE-6242 Consume tgz release artifact for geode-old-versions

---

geode-core/src/main/java/org/apache/geode/internal/stats50/VMStats50.java

First commit prevents logging of a fatal level stack trace when JDK-8207200 is hit and allows remaining stats to be sampled.

GEODE-6253: Handle JDK-8207200 gracefully in VM stats

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/eviction/RegionEntryEvictionIntegrationTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/map/AbstractRegionMapPut.java
geode-core/src/main/java/org/apache/geode/internal/cache/map/FocusedRegionMap.java
geode-core/src/main/java/org/apache/geode/internal/cache/map/RegionMapCommitPut.java
geode-core/src/main/java/org/apache/geode/internal/cache/map/RegionMapPut.java
geode-core/src/test/java/org/apache/geode/internal/cache/map/AbstractRegionMapPutTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/map/RegionMapPutTest.java

The commit f4b0643829b00d0ba9b0852fdd3a679812395545 introduced deadlock between concurrent updates with custom expiry which invoked getValue() from the region entry.
In this case the basicPut() was taking the regionEntry lock and calling customExpiry() which gets the regionEntry from the LRU list which could have been locked by another thread, calling getValue() on this regionEntry invokes lruUpdateCallback() which tries to acquire a lock, resulting in dead lock. 
The issue was fixed by making sure lruUpdateCallback is deferred/called at the higher/caller level (before synchronizing region entry).
- [Y ] Is there a JIRA …

GEODE-92: Fix deadlock issue from previous commit

---

build.gradle
ci/pipelines/geode-build/deploy_pipeline.sh
ci/pipelines/geode-build/jinja.template.yml
ci/pipelines/meta/meta.properties
ci/scripts/archive_results.sh
ci/scripts/execute_build.sh
ci/scripts/execute_publish.sh
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java
gradle.properties
gradle/publish.gradle

* Do not delay publication logic evaluation to accommodate a plugin we no longer use.
* Streamline version specification -- set version directly rather than through three separate properties.
* Remove scripted references to removed versionNumber property.
* Streamline publication target logic -- specify mavenRepository directly rather than via an interpolated mavenSnapshotBucket
* Concourse environment variable MAVEN_SNAPSNOT_BUCKET is now a complete bucket path.
* Concourse uses a semver object as the source-of-truth for binary
build-id and version.  Zero-pad build-id for lexicographical sorting of artifacts.
* Use semver content to help determine release or snapshot in concourse
* Concourse uses 'SNAPSHOT' as the semver pre-release token for develop (from "build")
-----
Thank you for …

GEODE-6259: Refine version specification and consumption

---

geode-core/src/main/java/org/apache/geode/internal/logging/log4j/Log4jAgent.java
geode-core/src/main/java/org/apache/geode/internal/logging/log4j/LogWriterAppender.java

Mark Log4jAgent.getConfigurationInfoString() with @TestingOnly

GEODE-6264: Remove TODO comments from logging classes

---

geode-core/src/integrationTest/java/org/apache/geode/TXJUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXState.java
geode-core/src/test/java/org/apache/geode/internal/cache/TXStateTest.java

* Do not cleanup existing TXEntries if finding an entry does not have expected value.

GEODE-6261: Do not break repeatable read by cleaning up TXEntries

---

ci/pipelines/meta/jinja.template.yml
gradle.properties
gradle/publish.gradle

* Default values in gradle.properties should not be quote-wrapped
* Short-circuit-when-exists operator is ?: in Groovy, not || like in Python.
* Username/Password credentials are only valid for maven targets of HTTP, HTTPS, and SFTP.
* The meta pipeline should be updated when meta.properties changes.

GEODE-6259: Correct issues with publish targets

---

extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/ClientServerSessionCache.java
geode-assembly/build.gradle
geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/ServerContainer.java
geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/CargoTestBase.java
geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Tomcat8ClientServerCustomCacheXmlTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/TomcatClientServerTest.java

- If a user provides their own client cache xml, we need to ensure that the
SessionExpirationCacheListener, as well as any necessary interest
registration, has been set up.
- Update build.xml so that these tests can be run from IntelliJ

GEODE-6270: Correctly set up user-provided client cache regions for session modules

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java

Signed-off-by: Peter Tran <ptran@pivotal.io>

GEODE-6274: Removes CreateRegionCommand build warning

---

ci/pipelines/geode-build/jinja.template.yml
ci/scripts/archive_results.sh
ci/scripts/execute_build.sh
ci/scripts/execute_publish.sh
ci/scripts/shared_utilities.sh

* Extract common semver version parsing to shared_utilities.sh
* Fix use of pull-request resource to get PR number
* Cleanup pointlessly used buildid version file ; use modified input as obvious output.

GEODE-6279 Correct pull-request-id encoding in URL

---

ci/pipelines/geode-build/jinja.template.yml
ci/pipelines/shared/jinja.variables.yml
ci/scripts/cleanup_benchmarks.sh
ci/scripts/run_benchmarks.sh

The Benchmark scripts now take named cli options instead of positional
ones. Use the named options in CI to call the benchmark, and pass the
branch and version number through to the scripts, even though only one
will be used at a time.
Signed-off-by: Helena A. Bales <hbales@pivotal.io>

GEODE-6276: Use named cli option in benchmark

---

geode-core/src/distributedTest/java/org/apache/geode/cache/management/MemoryThresholdsDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/SimpleDiskRegionJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/statistics/GemFireStatSamplerIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/statistics/SimpleStatSamplerIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/statistics/ValueMonitorIntegrationTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java
geode-core/src/main/java/org/apache/geode/internal/admin/remote/FetchResourceAttributesResponse.java
geode-core/src/main/java/org/apache/geode/internal/admin/remote/FetchStatsResponse.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXFarSideCMTracker.java
geode-core/src/main/java/org/apache/geode/internal/cache/control/HeapMemoryMonitor.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/AcceptorImpl.java
geode-core/src/main/java/org/apache/geode/internal/size/ReflectionObjectSizer.java
geode-core/src/main/java/org/apache/geode/internal/statistics/AbstractStatisticsFactory.java
geode-core/src/main/java/org/apache/geode/internal/statistics/DummyStatisticsRegistry.java
geode-core/src/main/java/org/apache/geode/internal/statistics/GemFireStatSampler.java
geode-core/src/main/java/org/apache/geode/internal/statistics/HostStatSampler.java
geode-core/src/main/java/org/apache/geode/internal/statistics/LocalStatisticsFactory.java
geode-core/src/main/java/org/apache/geode/internal/statistics/LocalStatisticsImpl.java
geode-core/src/main/java/org/apache/geode/internal/statistics/SampleCollector.java
geode-core/src/main/java/org/apache/geode/internal/statistics/SimpleStatSampler.java
geode-core/src/main/java/org/apache/geode/internal/statistics/StatisticsManager.java
geode-core/src/main/java/org/apache/geode/internal/statistics/StatisticsManagerFactory.java
geode-core/src/main/java/org/apache/geode/internal/statistics/StatisticsRegistry.java
geode-core/src/main/java/org/apache/geode/internal/statistics/platform/OsStatisticsFactory.java
geode-core/src/main/java/org/apache/geode/internal/stats50/Atomic50StatisticsImpl.java
geode-core/src/test/java/org/apache/geode/distributed/internal/InternalDistributedSystemTest.java
geode-core/src/test/java/org/apache/geode/internal/statistics/StatisticsImplTest.java
geode-core/src/test/java/org/apache/geode/internal/statistics/StatisticsRegistryTest.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/PutAllCSDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/cache30/MultiVMRegionTestCase.java

Please review @kirklund @galen-pivotal @mhansonp

GEODE-6269: Extract StatisticsRegistry from InternalDistributedSystem

---

geode-core/src/distributedTest/java/org/apache/geode/cache30/ClientMembershipDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/DistributedSystemMXBeanWithNotificationsDistributedTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/RegionManagementDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/UniversalMembershipListenerAdapterDUnitTest.java
geode-core/src/main/java/org/apache/geode/distributed/DistributedMember.java
geode-core/src/main/java/org/apache/geode/distributed/internal/membership/InternalDistributedMember.java
geode-core/src/main/java/org/apache/geode/distributed/internal/membership/NetMember.java
geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMember.java
geode-core/src/main/java/org/apache/geode/management/internal/MBeanJMXAdapter.java
geode-core/src/main/java/org/apache/geode/management/internal/NotificationHub.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/DistributedSystemBridge.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/ManagementAdapter.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/CliUtil.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/RebalanceCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ShowMetricsCommand.java
geode-core/src/test/java/org/apache/geode/management/internal/MBeanJMXAdapterTest.java

Introduce new DistributedMember.getUniqueId which is immutable.
Change MBeanJMXAdapter to use getUniqueId for MBean names
instead of getId when a member name has not been specified.
Notes: 
I went ahead and added getUniqueId to both DistributedMember and NetMember because the returned value should be the same as getId but without the membership port that was being changed in NetMember. If there is a better name for getUniqueId, please make suggestions!
I also renamed MBeanJMXAdapter.getMemberNameOrId to MBeanJMXAdapter.getMemberNameOrUniqueId and added new tests to MBeanJMXAdapterTest for my changes.
PR #3071 has failing tests caused by the MBean names changing in Loners because of getId mutating at runtime. I think that will be enough test coverage for GEODE-6285.

GEODE-6285: Make MBean names immutable in loner

---

geode-core/src/integrationTest/java/org/apache/geode/management/DisableJmxIntegrationTest.java
geode-core/src/main/java/org/apache/geode/admin/DistributedSystemConfig.java
geode-core/src/main/java/org/apache/geode/admin/internal/DistributedSystemConfigImpl.java
geode-core/src/main/java/org/apache/geode/admin/jmx/internal/AdminDistributedSystemJmxImpl.java
geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
geode-core/src/main/java/org/apache/geode/distributed/internal/AbstractDistributionConfig.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfigImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionConfigJUnitTest.java

This is needed in order to disable JMX in PersistentPartitionedRegionRegressionTest which will then prevent that test from deadlocking in the JMX ManagementListener.
I did not add this property to GFSH commands because I didn't think it was useful enough for most Users to worry about having it on the start server or start locator commands.

GEODE-6294: Add disable-jmx config property

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/PersistentPartitionedRegionRegressionTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/DisableJmxIntegrationTest.java
geode-core/src/main/java/org/apache/geode/admin/DistributedSystemConfig.java
geode-core/src/main/java/org/apache/geode/admin/internal/DistributedSystemConfigImpl.java
geode-core/src/main/java/org/apache/geode/admin/jmx/internal/AdminDistributedSystemJmxImpl.java
geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
geode-core/src/main/java/org/apache/geode/distributed/internal/AbstractDistributionConfig.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfigImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionConfigJUnitTest.java

The cause of the hang in GEODE-6232 is lock ordering that involves JMX ManagementListener. Since PersistentPartitionedRegionRegressionTest does not need JMX, this change will disable JMX in the test.
Requires PR #3095 to be merged first. The commit in that PR is included in this PR's branch. Please review just the 2nd commit in this PR which changes PersistentPartitionedRegionRegressionTest to use disable-jmx.

GEODE-6232: Disable JMX in PersistentPartitionedRegionRegressionTest

---

geode-core/src/integrationTest/java/org/apache/geode/internal/AvailablePortHelperIntegrationTest.java

- This test was failing fairly consistently on Windows. An initial assumption
was that the given port range would be completely free. This is typically
true in a Linux/Docker environment but is not the case on Windows.
- The logic of these modified tests is somewhat extreme as in actual use, there
would never be a need for 1000 ranges.
Signed-off-by: Aditya Anchuri <aanchuri@pivotal.io>

GEODE-6268: Reduce the number of iterations for unique port ranges in AvailablePortHelperIntegrationTest

---

ci/pipelines/shared/jinja.variables.yml

- This option is most likely causing bind exceptions in CI.

GEODE-6305: Disable Gradle parallel mode for WindowsGfshDistributedTest jobs

---

geode-core/src/integrationTest/java/org/apache/geode/distributed/LocatorLauncherRemoteIntegrationTestCase.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/ServerLauncherRemoteIntegrationTestCase.java

This will provide some details about if the process is actually
alive or not when FileProcessController.status throws
IllegalStateException.
When the test fails again, if Process is not alive then the
underlying cause is probably something like a BindException
preventing the startup of the Locator process.
This info will also apply to GEODE-6183 which is nearly
identical.
I'm including the change in ServerLauncherRemoteIntegrationTestCase
as well in case there's ever a similar failure starting up a server.

GEODE-6297: Add Process info to Launcher status failure msg

---

geode-junit/src/integrationTest/java/org/apache/geode/test/junit/rules/ExecutorServiceRuleIntegrationTest.java
geode-junit/src/main/java/org/apache/geode/test/junit/rules/ExecutorServiceRule.java
geode-junit/src/test/java/org/apache/geode/test/junit/rules/ExecutorServiceRuleGetThreadsTest.java

This change is required for the RegressionTest that I attached to [GEODE-6255: ManagementListener may deadlock with Cache close](https://issues.apache.org/jira/browse/GEODE-6255).

GEODE-6301: Add call stack support to ExecutorServiceRule

---

geode-core/src/integrationTest/java/org/apache/geode/pdx/PdxInstanceFactoryJUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/RegionService.java
geode-core/src/main/java/org/apache/geode/pdx/PdxInstance.java
geode-core/src/main/java/org/apache/geode/pdx/internal/PdxInstanceFactoryImpl.java
geode-core/src/main/java/org/apache/geode/pdx/internal/PdxInstanceImpl.java

PdxInstance.equals will only act as if an instance has a field
with the default value if the class name is not empty.
If the class name is empty it will now require that both instances
have all the same identity fields.

GEODE-6290: change PdxInstance.equals for empty class name

---

geode-junit/src/main/java/org/apache/geode/codeAnalysis/AnalyzeSerializablesJUnitTestBase.java

- Trying to fix an issue with AnalyzeSerializablesJUnitTest on Windows and
JDK 11.

GEODE-6307: Attempt to normalize file paths for correct comparison

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/ClientServerConnectDisconnectDistributedTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxy.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientUserAuths.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java

The changes to CacheClientProxy  closeTransientFields and closeOtherTransientFields are to address the bug I found while debugging this leak.
The main changes to address the leak are to invoke removeSubject in ClientUserAuths. cleanup and logout in CacheClientProxy.closeOtherTransientFields.

GEODE-6267: Logged out subject

---

geode-core/src/main/java/org/apache/geode/internal/process/ControllableProcess.java
geode-core/src/test/java/org/apache/geode/internal/process/ControllableProcessTest.java

This fixes a potential cause of GEODE-6297 by preventing locator/server status from writing to status file if the status contains only whitespace.

GEODE-6313: Make ControllableProcess fail if status is only whitespace

---

geode-core/src/main/java/org/apache/geode/distributed/AbstractLauncher.java
geode-core/src/main/java/org/apache/geode/internal/process/ControllableProcess.java
geode-core/src/test/java/org/apache/geode/distributed/AbstractLauncherServiceStateTest.java
geode-core/src/test/java/org/apache/geode/internal/process/ControllableProcessTest.java

The launcher status used to contain line separators. Looks like this was lost when LocalizedStrings were removed.
This PR restores line separators to the status output of the launchers and adds new unit tests for it.

GEODE-6308: Use line separators in launcher status

---

geode-protobuf/src/integrationTest/java/org/apache/geode/internal/protocol/protobuf/v1/acceptance/CacheConnectionJUnitTest.java

- This test would fail intermittently on Windows with JDK11. It seems like the
protobuf message is still being processed on the server, when the sending
socket is closed by the test. Just wait to start reading something back on
the socket before continuing.

GEODE-6317: Fix intermittent CacheConnectionJUnitTest failures

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/configuration/ClusterConfigLocatorRestartDUnitTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/ServiceConfig.java
geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocator.java
geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java

This modifies auto-reconnect to lengthen the time a Locator will attempt
to join from 24 seconds to 60 seconds and prevents the Locator from
creating its own cluster (which would form a split-brain).  In an
auto-reconnect attempt the location service will not start up until a
quorum of the old cluster can be contacted, meaning that some process
that's still in the cluster exists and should have taken over the role
of membership coordinator.  The locator needs to join using that
coordinator and not create its own cluster.
This also corrects the handling of the old membership view in
GMSLocator.  The restarted location service was incorrectly using this
old view as an authority on who had the role of coordinator but it
should only be used as a hint.  This is done by putting the view into …

GEODE-6309 ClusterConfigLocatorRestartDUnitTest fails to spin up a new server

---

geode-core/src/distributedTest/java/org/apache/geode/cache/management/MemoryThresholdsDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/ResourceManagerWithQueryMonitorDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionEvictionDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/eviction/EvictionDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/control/MemoryMonitorJUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/control/HeapMemoryMonitor.java
geode-core/src/main/java/org/apache/geode/internal/cache/control/MemoryThresholds.java
geode-core/src/test/java/org/apache/geode/internal/cache/control/HeapMemoryMonitorTest.java
geode-junit/src/main/java/org/apache/geode/test/fake/Fakes.java
geode-lucene/src/distributedTest/java/org/apache/geode/cache/lucene/EvictionDUnitTest.java

The tolerance counter was not properly being reset between
non-consecutive EVICTION and CRITICAL events.  To fix this and make it
more understandable, the threshold logic was combined with the logic to
compute the next state in the MemoryThreshold state machine.  The
counter is now reset between non-consecutive EVICTION and CRITICAL
events.
submit …

GEODE-6304: Refactor memory monitor to properly reset tolerance counter

---

geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PartitionMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/tx/RemoteOperationMessage.java
geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/PartitionMessageTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/tx/RemoteOperationMessageTest.java

When a `FunctionStreamingResultCollector` is processing (reply) messages for a transactional operation, it sometimes encounters a message that is a generic `ReplyMessage`, not a `FunctionStreamingReplyMessage`. This happens when the (remote) message processor (`PartitionMessage.process()`) attempts to perform the operation, but finds that the transaction is already closed. `process()` replies with a generic `ReplyMessage` in that case, resulting in a `ClassCastException` over in the `FunctionStreamingResultCollector`.
The solution, here, is to reply with a `TransactionException` from `process()` in this case.
This PR consists of two commits: one for the bug just described, and another (tiny one) that got the breadcrumbs facility working again. The latter was helpful in debugging the IPC. …

GEODE-6330: Return a TransactionException Instead of a Generic ReplyMessage

---

geode-core/src/main/java/org/apache/geode/internal/cache/CachePerfStats.java
geode-core/src/main/java/org/apache/geode/internal/cache/DummyCachePerfStats.java
geode-core/src/test/java/org/apache/geode/internal/cache/CachePerfStatsTest.java

Cleaned up some minor warnings in CachePerfStats and introduced an inner-interface with constructor changes to facilitate unit testing. Unit tests were written for all CachePerfStats operation count stats that are currently implemented as IntCounters which can wrap from max integer to negative values.
Please review @mhansonp @demery-pivotal

GEODE-6334: Create CachePerfStatsTest and cleanup CachePerfStats

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RegionManagementDunitTest.java
geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/DisabledClusterConfigTest.java
geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/HttpServiceIntegrationTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/api/RegionAPIDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/CliFunctionResult.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/RegionConfigMutator.java
geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/MemberStarterRule.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/ManagementControllerAdvice.java

* fail early if cluster persistence serivce is not enabled
* creating the region twice will result in status code 409
* if region creation is partially failed on members, do not update cluster configuration.

GEODE-6174: more error handling in LocatorClusterConfigurationService

---

geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySenderEventProcessor.java
geode-core/src/main/java/org/apache/geode/internal/monitoring/ThreadsMonitoring.java
geode-core/src/main/java/org/apache/geode/internal/monitoring/ThreadsMonitoringImpl.java
geode-core/src/main/java/org/apache/geode/internal/monitoring/ThreadsMonitoringImplDummy.java
geode-core/src/test/java/org/apache/geode/internal/monitoring/ThreadsMonitoringImplJUnitTest.java

Modified the gateways to update the ThreadsMonitor before sleeping.

GEODE-6342 ThreadsMonitor prints many warnings in gateway sender logs

---

geode-core/src/main/java/org/apache/geode/management/internal/beans/DistributedSystemBridge.java

- There is a small window where the iterator has been created 
but the underlying structure (a ConcurrentHashMap) has changed,
resulting in an ArrayIndexOutOfBoundsException during iteration.

GEODE-6349: Fix potential race in DistributedRegionBridge.listAllRegions

---

geode-core/src/main/java/org/apache/geode/cache/CacheFactory.java
geode-core/src/main/java/org/apache/geode/distributed/DistributedSystem.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java
geode-core/src/main/java/org/apache/geode/distributed/internal/SecurityConfig.java

* Extract `DistributedSystem.connect()` to `InternalDistributedSystem.connectInternal()` so that parameters can be passed in.
* Make `DistributedSystem.existingSystems` a `List<InternalDistributedSystem>.
* Add a comment making it clear that users should never override `DistributedSystem`.
* Remove commented code

GEODE-6353: remove the ThreadLocal from SecurityConfig.

---

geode-junit/src/integrationTest/java/org/apache/geode/test/junit/rules/ExecutorServiceRuleIntegrationTest.java
geode-junit/src/main/java/org/apache/geode/test/junit/rules/ExecutorServiceRule.java
geode-junit/src/test/java/org/apache/geode/test/junit/rules/ExecutorServiceRuleDumpThreadsTest.java
geode-junit/src/test/java/org/apache/geode/test/junit/rules/ExecutorServiceRuleGetThreadsTest.java
geode-junit/src/test/java/org/apache/geode/test/junit/rules/ExecutorServiceRuleTest.java

ThreadInfo.toString contains all of the relevant monitor/synchronizer lock info that ExecutorServiceRule.dumpThreads needs so I removed customization of the dump and just use what ThreadInfo provides.

GEODE-6301: Use ThreadInfo.toString in ExecutorServiceRule.dumpThreads

---

geode-core/src/main/java/org/apache/geode/distributed/internal/InternalConfigurationPersistenceService.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/CommandManager.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/util/ClasspathScanLoadHelper.java
geode-core/src/main/java/org/apache/geode/management/internal/deployment/FunctionScanner.java

* Properly wraps all scanner uses in try-with-resources blocks (to ensure temporary files are cleaned up and file descriptors are closed promptly, rather than waiting for full GC to invoke finalizers).
* Limits thread usage to single thread, regardless of available CPUs or memory (this eliminates the "multiplier effect" where file descriptors used could be as high as 1.25 * number-of-jars * number-of-cpus).
* Removes usage of a non-public classgraph API (to broaden binary compatibility with other versions of classgraph up to 4.4.12, in case anyone wants to experiment with swapping in a newer version).
* Please note, classgraph 4.6.x is NOT a drop-in replacement.  Migrating to the latest version of classgraph would require some non-trivial code changes on our side.  Version up to 4.4.12 …

GEODE-6310 limit classgraph file descriptor consumption

---

geode-dunit/src/main/java/org/apache/geode/cache30/CacheXmlTestCase.java

The default tolerance of 1 was masking an issue with high heap in these cache XML tests.  Setting the default back to 1 for these tests, which is what it was prior to the changes from https://github.com/apache/geode/commit/546abdd173afe13c01e148900c2b9114dc5bc4cc.  Going to continue investigating the source of the high heap after this is merged. …

GEODE-6347: Setting tolerance to 1 for Cache XML tests

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/configuration/ClusterConfigDeployJarDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DeployCommand.java

GEODE-6364: Deploy of invalid jar file does not write file contents to config on locator

---

geode-dunit/build.gradle
geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/VmEventListenerDistributedTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/Host.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/VM.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/VMEventListener.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/VMEventListenerRegistry.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/DUnitHost.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/DUnitLauncher.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/VMEventNotifier.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/AbstractDistributedRule.java
geode-dunit/src/test/java/org/apache/geode/test/dunit/internal/VMEventNotifierTest.java
geode-dunit/src/test/resources/expected-pom.xml

A DUnit Rule (or even a test) can now register a VMEventListener:
`VM.getVMEventListenerRegistry().addVMEventListener(vmEventListener);`
VMEventListeners will receive the following notifications:
```
public void afterCreateVM(VM vm);
public void beforeBounceVM(VM vm);
public void afterBounceVM(VM vm);
```
DUnit Rules can use these callbacks in order to support
dynamic creation or bouncing of VMs.
Note: this PR does not complete the ticket GEODE-6033. Next step is to change the DUnit Rules to register a VMEventListener. Then the ticket will be resolved.
Please review @demery-pivotal

GEODE-6033: Add VMEventListener for DUnit Rules

---

geode-core/src/test/java/org/apache/geode/management/internal/cli/shell/GfshAbstractUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/shell/GfshConsoleModeUnitTest.java

- This avoids subsequent tests failing because they are checking for the
presence of LogWrapper.

GEODE-6370: Clean up LogWrapper between tests

---

geode-assembly/build.gradle

`doFirst` is a bad idea with respect to configuration caching in Gradle.
Replace with a separate task to generate the requested classpath. See
https://guides.gradle.org/using-build-cache/#suggestions_for_authoring_your_build
Gradle task-inputs create dependencies, but dependency declaration does
not generate input coupling.
email to …

GEODE-6323 Fix dependency tracking for manifest jars

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt
geode-assembly/src/test/resources/expected-pom.xml
geode-common/src/test/resources/expected-pom.xml
geode-concurrency-test/src/test/resources/expected-pom.xml
geode-connectors/src/test/resources/expected-pom.xml
geode-core/src/test/resources/expected-pom.xml
geode-cq/src/test/resources/expected-pom.xml
geode-dunit/src/test/resources/expected-pom.xml
geode-experimental-driver/src/test/resources/expected-pom.xml
geode-json/src/test/resources/expected-pom.xml
geode-junit/src/test/resources/expected-pom.xml
geode-lucene/src/test/resources/expected-pom.xml
geode-management/src/test/resources/expected-pom.xml
geode-old-client-support/src/test/resources/expected-pom.xml
geode-protobuf-messages/src/test/resources/expected-pom.xml
geode-protobuf/src/test/resources/expected-pom.xml
geode-pulse/src/test/resources/expected-pom.xml
geode-rebalancer/src/test/resources/expected-pom.xml
geode-wan/src/test/resources/expected-pom.xml
geode-web-api/src/test/resources/expected-pom.xml
geode-web-management/src/test/resources/expected-pom.xml
geode-web/src/test/resources/expected-pom.xml
gradle/geode-dependency-management.gradle

The following flaws have been published by NIST since Dec 2018
* CVE-2018-1000873
* CVE-2018-19362
* CVE-2018-19361
* CVE-2018-19360
submit an update to your PR as soon

GEODE-6381: Update Jackson version to fix dependency CVEs

---

gradle/spotless.gradle

* This acts as a safeguard against developers forgetting to bump the input to 'bumpThisNumberIfACustomStepChanges'
-----

GEODE-6395: Use md5 as Spotless cache value.

---

geode-core/src/test/java/org/apache/geode/internal/cache/CachePerfStatsTest.java

GEODE-6405: Restore enableClockStats to false in CachePerfStatsTest

---

geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedDiskDirRuleDistributedTest.java
geode-dunit/src/integrationTest/java/org/apache/geode/test/junit/rules/DiskDirRuleIntegrationTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedDiskDirRule.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/DiskDirRule.java
geode-junit/src/main/java/org/apache/geode/test/junit/runners/TestRunner.java

* Create tests for DiskDirRule and DistributedDiskDirRule.
* Fix a couple minor issues found by testing DiskDirRule.
* Make DistributedDiskDirRule support create and bounce VMs.

GEODE-6033: Support dynamic VMs in DistributedDiskDirRule

---

geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/ServerContainer.java
geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/TomcatContainer.java
geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/GenericAppServerContainer.java

Changed `ServerContainer` to catch and IOExceptions while dumping container logs.

GEODE-6396: Make ServerContainer tolerate IOExceptions while dumping logs

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/PersistentPartitionHangsDuringRestartRegressionTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/PersistentPartitionedRegionRegressionTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/VMEventListener.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedDiskDirRule.java

Extract doesNotWaitForPreviousInstanceOfOnlineServer to
PersistentPartitionHangsDuringRestartRegressionTest.
Disable ENABLE_NETWORK_PARTITION_DETECTION and use bounceForcibly
instead of disconnecting vm0.
Also fixes GEODE-6356 with addIgnoredException for CancelException.

GEODE-6409: Bounce VM in doesNotWaitForPreviousInstanceOfOnlineServer

---

geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-core/src/main/java/org/apache/geode/internal/cache/DestroyPartitionedRegionMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/InvalidatePartitionedRegionMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/RegionEventImpl.java
geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/DestroyPartitionedRegionMessageDUnitTest.java
geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/InvalidatePartitionedRegionMessageDUnitTest.java

* Event id is included in the DestroyPartitionedRegionMessage and InvalidatePartitionedRegionMessage
* This is to prevent the NPE
* The NPE occurs when server tries to notify the clients after receiving the message
* While getting the thread id and sequence id it ends up with an NPE and event id is null.

GEODE-6391: Adding the event ID to the messages

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommand.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommandTest.java

- Added server group support for the logic in destroy region which
checks for an existing jdbc-mapping

GEODE-6365: Group support for mapping logic in DestroyRegionCommand

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RegionManagementDunitTest.java
geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/DisabledClusterConfigTest.java
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt
geode-core/src/test/java/org/apache/geode/management/internal/api/ClusterManagementResultTest.java
geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java
geode-management/src/main/java/org/apache/geode/management/internal/api/ClusterManagementResult.java
geode-management/src/main/java/org/apache/geode/management/internal/api/Status.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementIntegrationTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementSecurityIntegrationTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/ManagementControllerAdvice.java

I just want to see if this change set will work.
* change the ControllerAdvisor to return 200 with EntityExistsException.
* Use simple boolean flag for ClusterManagementResult status
* isSuccessfullyAppliedOnMembers will be true is memberList is empty.

GEODE-6174: rest call "create" should be idempotent

---

geode-core/src/main/java/org/apache/geode/internal/cache/RegionNameValidation.java
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/ConfigurationMutator.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/RegionConfigMutator.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/ConfigurationValidator.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidator.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidatorTest.java

Co-authored-by: Kenneth Howe <khowe@pivotal.io>

GEODE-6174: move exists method into the validator

---

geode-core/src/main/java/org/apache/geode/internal/statistics/StripedStatisticsImpl.java

Synchronize on getting and setting stats to avoid a race condition that
could occur when multiple threads were trying to set gauge stats.

GEODE-6440: synchronize when getting and setting

---

geode-junit/src/test/java/org/apache/geode/test/junit/rules/ConcurrencyRuleTest.java

This test was timing out when run in CI. Since it never fails locally,
the issue appears to be with resource contention. Increasing the timeout
should reduce the frequency of failures as it gives the test more time
to spin up the required threads. This test will still fail if it fails
to start two threads within a minute.

GEODE-6422: Fix test timeout issue

---

geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedNoAckRegionCCEDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/ConflationDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/TXJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/ClientAccessToInternalStatsTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/ProxyJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/asyncqueue/AsyncEventQueueEvictionAndExpirationJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/PartitionedRegionSingleNodeOperationsJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/statistics/DistributedSystemStatisticsIntegrationTest.java
geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-core/src/main/java/org/apache/geode/cache/client/internal/ConnectionStats.java
geode-core/src/main/java/org/apache/geode/internal/admin/ClientStatsManager.java
geode-core/src/main/java/org/apache/geode/internal/admin/remote/ClientHealthStats.java
geode-core/src/main/java/org/apache/geode/internal/cache/CachePerfStats.java
geode-core/src/main/java/org/apache/geode/internal/cache/DummyCachePerfStats.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/statistics/StatisticsImpl.java
geode-core/src/main/java/org/apache/geode/management/ClientHealthStatus.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/CacheServerBridge.java
geode-core/src/test/java/org/apache/geode/internal/cache/CachePerfStatsTest.java
geode-dunit/src/main/java/org/apache/geode/cache30/RegionTestCase.java
geode-dunit/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscDUnitTestBase.java

Changes gets, misses, getFailures, and getTimeouts stats from int to
long so that they don't rollover as quickly.

GEODE-6425: fix rollover of get stats

---

geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/ManagementControllerAdvice.java

Added a handler for `IllegalArgumentException` in the `ManagementControllerAdvice` to return
HttpStatus 400 as required by the CMS spec on the wiki

GEODE-6174: Don't catch IllegalArgumentException from the validator

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/TableMetaDataManager.java
geode-core/src/jmh/java/org/apache/geode/internal/util/ComputeIfAbsentBenchmark.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/AttributeDescriptor.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java
geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/GMSEncrypt.java
geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupDefinition.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientHealthMonitor.java
geode-core/src/main/java/org/apache/geode/internal/util/JavaWorkarounds.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/CqServiceImpl.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/FlatFormatSerializer.java

…Absent
*  Tries to do the get() outside of a lock before computing
Please suggest a better name than JavaWorkarounds... I just haven't thought of anything good...

GEODE-6404: work around possible sync issue with computeIfAbsent

---

geode-core/src/main/java/org/apache/geode/internal/process/ProcessUtils.java
geode-core/src/main/java/org/apache/geode/internal/process/UncheckedPidUnavailableException.java
geode-core/src/main/java/org/apache/geode/internal/statistics/HostStatSampler.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt
geode-core/src/test/java/org/apache/geode/internal/statistics/HostStatSamplerTest.java

If the PID is unavailable for any reason, fall back to using
DistributedSystem ID.
@demery-pivotal please review

GEODE-6442: Use PID for OS and Process stats if available

---

ci/images/google-windows-geode-builder/windows-packer.json

- The current version being installed is 7.9.0.1 but my theory is that
that is causing build issues.

GEODE-6464: Pin OpenSSH in Windows images to version 7.7.2.1

---

geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyMappingCommandDunitTest.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyMappingCommand.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyMappingCommandTest.java

- Refactored DestroyMappingCommand to fix issue causing commands run
without group parameter specified to run on all members, which resulted
in mappings being removed from servers in all groups, without updating
cluster config
Authored-by: Benjamin Ross <bross@pivotal.io>

GEODE-6365: Fixed DestroyMappingCommand bug for default 'cluster' group

---

geode-core/src/main/java/org/apache/geode/internal/cache/wan/GatewaySenderEventImpl.java
geode-core/src/main/java/org/apache/geode/internal/datasource/GemFireBasicDataSource.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/shell/Gfsh.java

* A repeated check on a non-volatile field is not thread-safe, and could result in unexpected behavior.
* Fixed using volatile and local variables

GEODE-6470: Making double-checked locking thread-safe

---

geode-assembly/build.gradle
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ManagementRequestLoggingDUnitTest.java
geode-web-management/build.gradle
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/ManagementLoggingFilter.java
geode-web-management/src/main/webapp/WEB-INF/web.xml

- Requests are logged simply with a prefix of 'Management request'. This
could easily be customized in the future.
- Request logging can be disabled by setting the system property
`geode.management.request.logging=false`

GEODE-6443: Log all requests to REST ManagementService

---

geode-core/src/main/java/org/apache/geode/cache/CacheFactory.java
geode-core/src/main/java/org/apache/geode/cache/client/ClientCacheFactory.java
geode-core/src/main/java/org/apache/geode/distributed/internal/ConnectionConfig.java
geode-core/src/main/java/org/apache/geode/distributed/internal/ConnectionConfigImpl.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java
geode-core/src/main/java/org/apache/geode/internal/cache/CacheConfig.java
geode-core/src/main/java/org/apache/geode/internal/cache/CacheFactoryStatics.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalCache.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalCacheBuilder.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalCacheForClientAccess.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheCreation.java
geode-core/src/test/java/org/apache/geode/distributed/internal/ConnectionConfigImplTest.java
geode-core/src/test/java/org/apache/geode/distributed/internal/InternalDistributedSystemTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/GemFireCacheImplTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/InternalCacheBuilderAllowsMultipleSystemsTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/InternalCacheBuilderTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java

All code (product and tests) now use InternalCacheBuilder to construct
instances of GemFireCacheImpl.
CacheFactory now delegates to InternalCacheBuilder which adds a few
more internal options that are not exposed on CacheFactory.
InternalCacheBuilder is necessary so we can create Micrometer MeterRegistry
in one place for all instances of GemFireCacheImpl.
@demery-pivotal

GEODE-6295: Use InternalCacheBuilder for constructing GemFireCacheImpl

---

geode-core/src/main/java/org/apache/geode/internal/statistics/AbstractStatisticsFactory.java
geode-core/src/main/java/org/apache/geode/internal/statistics/HostStatSampler.java
geode-core/src/main/java/org/apache/geode/internal/statistics/StatisticsImpl.java
geode-core/src/main/java/org/apache/geode/internal/statistics/StatisticsManager.java
geode-core/src/main/java/org/apache/geode/internal/statistics/StatisticsRegistry.java
geode-core/src/test/java/org/apache/geode/internal/statistics/HostStatSamplerTest.java
geode-core/src/test/java/org/apache/geode/internal/statistics/StatisticsImplTest.java
geode-core/src/test/java/org/apache/geode/internal/statistics/StatisticsRegistryTest.java

The previous commit for GEODE-6442 was correct but incomplete. There are still instances of statistics shown in VSD that should display the pid in the pid column but instead show either nothing (zero) or a membership port.
The commit for GEODE-6269: Extract StatisticsRegistry from IDS (#3068) removed the correct defaults of textId and numericId. When textId is empty, the textId should default to the member name (StatisticsManager.getName). When numericId is zero, the numericId should default to the pid (StatisticsManager.getPid).
Note that I've restored the correct defaults in the base class StatisticsImpl instead of duplicating it in both LocalStatisticsImpl and StripedStatisticsImpl. New tests confirm the defaults and will prevent accidental changes in the future.
I fixed up …

GEODE-6442: Fix Statistics textId and numericId

---

geode-core/src/main/java/org/apache/geode/internal/statistics/GemFireStatSampler.java
geode-core/src/main/java/org/apache/geode/internal/statistics/HostStatHelper.java

```
commit b9114c903aad5f8a4fc56a6179d81a5dc32be3c2
Date:   Tue Mar 5 12:21:06 2019 -0800
GEODE-6487: Use PID for OsStatistics numericId
Cleanup HostStatHelper.
```
```
commit 001ce09b33ed1512321c1f571be65f8ba3c15642
Date:   Tue Mar 5 12:12:00 2019 -0800
GEODE-6486: Use PID for StatSamplerStats numericId
```
```
commit a44fec264f9067d262cd3b323de670a2588f3392
Date:   Tue Mar 5 12:09:34 2019 -0800
GEDOE-6486: Cleanup GemFireStatSampler
```

GEODE-6486/GEODE-6487: Use PID for StatSamplerStats and OsStatistics numericIds

---

geode-junit/src/test/java/org/apache/geode/test/junit/rules/ConcurrencyRuleTest.java

Removing non-deterministic unit tests because unit tests should be
deterministic, and the tests were testing test code, not product code.

GEODE-6479 and GEODE-6422: remove tests

---

geode-assembly/build.gradle
geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/rest/GradleBuildWithGeodeCoreAcceptanceTest.java
geode-assembly/src/acceptanceTest/resources/gradle-test-projects/management/build.gradle
geode-assembly/src/acceptanceTest/resources/gradle-test-projects/management/src/main/java/ServerTestApp.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/HttpService.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalCache.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalCacheForClientAccess.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheCreation.java
geode-core/src/main/java/org/apache/geode/management/internal/ManagementAgent.java
geode-core/src/main/java/org/apache/geode/management/internal/RestAgent.java
geode-junit/src/main/java/org/apache/geode/test/junit/rules/RequiresGeodeHome.java
geode-junit/src/main/java/org/apache/geode/test/util/ResourceUtils.java

- If the HttpService (or war deployment) fails, simply log a warning
message and continue starting.
- Add a simple gradle building test which ensures that 'geode-core' is
the only module required to start a basic Cache.

GEODE-6492: Ensure that starting HttpService can fail gracefully in the face of errors

---

geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedUseJacksonForJsonPathRuleDistributedTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedDiskDirRule.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedUseJacksonForJsonPathRule.java
geode-junit/build.gradle
geode-junit/src/main/java/org/apache/geode/test/junit/rules/UseJacksonForJsonPathRule.java
geode-junit/src/test/java/org/apache/geode/test/junit/rules/UseJacksonForJsonPathRuleTest.java
geode-junit/src/test/resources/expected-pom.xml

* Add vmCount constructor to DistributedDiskDirRule
* Order geode-junit compile dependencies alphabetically
* Add jackson compile dependencies to geode-junit
* Cleanup IDE warnings in UseJacksonForJsonPathRule
* Cleanup and javadoc DistributedUseJacksonForJsonPathRule
* Add new test DistributedUseJacksonForJsonPathRuleDistributedTest
* Make DistributedUseJacksonForJsonPathRule support create and bounce VMs
@demery-pivotal please review
Background: By default json-path uses json-smart. UseJacksonForJsonPathRule and DistributedUseJacksonForJsonPathRule configure json-path to use Jackson instead of json-smart. This helps us narrow our json library usage to Jackson while using json-path in tests that involve json.

GEODE-6033: Support dynamic VMs in DistributedUseJacksonForJsonPathRule

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/DeprecatedCacheServerLauncherIntegrationTest.java

This test is failing occasionally in CI. Printing out the log of the
server in the test so that we will have some clue if the server fails to
start in future test runs.

GEODE-4240: Printing out cache server log

---

ci/scripts/execute_tests.sh

The concourse jobs where we tried to turn of parallel gradle were still
running gradle in parallel, because it's the default. Pass --no-parallel
if the job is configured not to run in parallel.
This was causing port/file related conflicts in the windows tests, which
are set to not run in parallel.

GEODE-6447: Honor the PARALLEL_GRADLE flag in builds

---

geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeDataSourceCommandDUnitTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyDataSourceCommandDUnitTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/ListDataSourceCommandDUnitTest.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateDataSourceCommand.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/functions/DestroyJndiBindingFunctionTest.java
geode-core/src/main/java/org/apache/geode/internal/jndi/JNDIInvoker.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DestroyJndiBindingFunction.java

GEODE-6511 Change data source to use connection pool by default

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateGatewaySenderCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateGatewaySenderCommandTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/wancommand/CreateDestroyGatewaySenderCommandDUnitTest.java

GEODE-6519: Fix `CreateGatewaySenderCommand` Flags
- Parameter `manual-start` from `create gateway-sender` command is set
as `false` by default when specified without a value.
- Parameters `parallel`, `disk-synchronous`, `enable-persistence` and
`enable-batch-conflation` from `create gateway-sender` command are set
as `true` by default when specified without a value.

GEODE-6519: Fix CreateGatewaySenderCommand Flags

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommand.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommandTest.java

 GEODE-5971: refactor DestroyRegionCommand and CreateRegionCommand.interceptor

---

geode-core/src/main/java/org/apache/geode/internal/cache/InternalCacheBuilder.java
geode-core/src/main/java/org/apache/geode/internal/metrics/CacheMeterRegistryFactory.java
geode-core/src/main/java/org/apache/geode/internal/metrics/CompositeMeterRegistryFactory.java
geode-core/src/test/java/org/apache/geode/internal/metrics/CacheMeterRegistryFactoryTest.java

Extract default from CompositeMeterRegistryFactory to concrete class
CompositeMeterRegistryFactory.
Please review: @demery-pivotal @upthewaterspout @moleske

GEODE-6295: Extract default from CompositeMeterRegistryFactory

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/rest/StandaloneClientManagementAPIAcceptanceTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/GeodeManagementFeatureFlagDUnitTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/MemberStarterRule.java
geode-junit/src/main/java/org/apache/geode/test/junit/rules/accessible/AccessibleRestoreSystemProperties.java
geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/DebuggableCommand.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementService.java

* The Geode Management API is disabled
* A feature flag has been added to allow people to use this experimental
feature using System Property `enable-experimental-cluster-management-service`

GEODE-6523 Disables Geode Management API with feature flag

---

geode-core/src/main/java/org/apache/geode/internal/cache/EntrySnapshot.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXEntry.java

[Part of GEODE-6534: Refactor LocalRegion]
Make entryUserAttributes final and thread safe.
Lots of threads were checking for null and constructing it as either
ConcurrentHashMap or HashTable. Now it is a final ConcurrentHashMap.
Reduced visibility to private and added accessor.
Please review: @demery-pivotal

GEODE-6534: Encapsulate LocalRegion entryUserAttributes

---

geode-core/src/main/java/org/apache/geode/internal/metrics/CacheMeterRegistryFactory.java
geode-core/src/test/java/org/apache/geode/internal/metrics/CacheMeterRegistryFactoryTest.java

Co-Authored-By: Dale Emery demery@pivotal.io
Co-Authored-By: Michael Oleske moleske@pivotal.io
Please review: @demery-pivotal @moleske

GEODE-6528: Add host.jvm.memory.used meter for heap and nonheap

---

geode-core/src/distributedTest/java/org/apache/geode/pdx/PdxMultiClusterClientServerDUnitTest.java
geode-core/src/main/java/org/apache/geode/pdx/internal/ClientTypeRegistration.java

Some users were relying on having PDX types copied from one cluster to
another in the client. This logic was removed (accidentally?) in
cf0b378429. Restoring the original behavior to copy a type from one
cluster to another when it is created.
Note that receiving a type through a read still does not result in
copying a type from one cluster to another, so this topology is not
completely supported even with this fix.

GEODE-6271: Restoring pdx type copying behavior in client

---

geode-core/src/main/java/org/apache/geode/internal/cache/RegionPerfStats.java
geode-core/src/test/java/org/apache/geode/internal/cache/RegionPerfStatsTest.java

Please review: @demery-pivotal @mhansonp 
GEODE-6539 was caused by this commit:
```
commit 02eda0a6af6d84a1e26e44248280c0de7feb4a88
Date:   Tue Mar 19 16:25:52 2019 -0700
GEODE-6534: Extract RegionPerfStats from LocalRegion (#3315)
Set enableClockStats before constructing CachePerfStats.
```

GEODE-6539: Use RegionStats-regionName for RegionPerfStats TextId

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ClearTXLockingDUnitTest.java

Making the latches static final should fix the intermittent NPE.

GEODE-2275: Update and cleanup ClearTXLockingDUnitTest

---

geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/GeodeEntityResolver.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/PivotalEntityResolver.java
geode-core/src/test/java/org/apache/geode/internal/cache/xmlcache/GeodeEntityResolverTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/xmlcache/PivotalEntityResolverTest.java

Matches both http and https well known system ids to schemas.

GEODE-6540: Resolves entities with https urls.

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DeployWithGroupsDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DescribeRegionDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DestroyAsyncEventQueueCommandDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeRegionCommand.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeRegionJUnitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/result/model/TabularResultModelTest.java
geode-dunit/src/main/java/org/apache/geode/management/internal/cli/commands/FunctionCommandsDUnitTestBase.java
geode-junit/src/main/java/org/apache/geode/test/junit/assertions/TabularResultModelAnyRowAssert.java
geode-junit/src/main/java/org/apache/geode/test/junit/assertions/TabularResultModelAssert.java
geode-junit/src/main/java/org/apache/geode/test/junit/assertions/TabularResultModelColumnAssert.java
geode-junit/src/main/java/org/apache/geode/test/junit/assertions/TabularResultModelRowAssert.java
geode-junit/src/main/java/org/apache/geode/test/junit/assertions/TabularResultModelSliceAssert.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/wancommand/ListGatewaysCommandDUnitTest.java

also improves Tabular asserts so individual rows or columns can be selected and asserted on much like a ListAssert, but chain-able at the table level so all rows or columns of a table can be checked in a single assert chain.

GEODE-5971: refactor DescribeRegionCommand to use ResultModel
