geode-core/src/main/java/org/apache/geode/CopyHelper.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/OpExecutorImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/PRHARedundancyProvider.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionHelper.java
geode-wan/src/main/java/org/apache/geode/internal/cache/wan/GatewaySenderEventRemoteDispatcher.java

* Due to contradictory dynamic type checks, dead codes were create.
* This commit deletes those dead code.

GEODE-5974: Removal of dead code.

---

geode-core/src/main/java/org/apache/geode/management/internal/ManagementResourceRepo.java
geode-core/src/main/java/org/apache/geode/redis/internal/RegionProvider.java

* Ensured that container access is done with the proper object type as a parameter.

GEODE-5975: Fixed container access.

---

geode-protobuf/build.gradle
geode-protobuf/geode-protobuf-test/build.gradle
geode-protobuf/src/test/resources/expected-pom.xml

GEODE-5937: Made dependencies explicit in geode-protobuf modules.

---

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/mgr/GMSMembershipManager.java
geode-core/src/main/java/org/apache/geode/internal/cache/CacheServerLauncher.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionQueryEvaluator.java
geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/ProtobufQueryService.java
geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/data/Cluster.java

* Removed collections that are populated but are never used.

GEODE-5980: Removed unused collections

---

geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/JdbcDistributedTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommandDUnitTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommandDUnitTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyMappingCommandDunitTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/JdbcClusterConfigDistributedTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/ListMappingCommandDUnitTest.java
geode-connectors/src/integrationTest/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommandIntegrationTest.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/SqlHandler.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/configuration/RegionMapping.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/xml/ElementType.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/xml/JdbcConnectorServiceXmlParser.java
geode-connectors/src/main/resources/META-INF/schemas/geode.apache.org/schema/jdbc/jdbc-1.0.xsd
geode-connectors/src/main/resources/org/apache/geode/internal/sanctioned-geode-connectors-serializables.txt
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/RegionMappingTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/SqlHandlerTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommandTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/xml/ElementTypeTest.java

GEODE-5977: rename --connection to --data-source

---

geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java

GEODE-5338: Rephrased warning when SSL hostname validation is disabled

---

geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/test/junit/rules/HttpResponseAssert.java
geode-core/src/main/java/org/apache/geode/internal/cache/package.html
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java

Fix vararg warnings

---

ci/pipelines/geode-build/jinja.template.yml
ci/pipelines/metrics/jinja.template.yml

GEODE-5999 split pipeline back into separate jobs

---

geode-core/src/main/java/org/apache/geode/redis/internal/executor/list/ListExecutor.java

GEODE-5983: Added missing null check

---

geode-core/src/distributedTest/java/org/apache/geode/cache/client/internal/ClientServerHostNameVerificationDistributedTest.java

GEODE-6008: ignore root exception as well.

---

geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegion.java

* Using read-write locks to synchronize the getters and setters for CacheLoader and CacheWriter.

GEODE-5982: Synchronized access to CacheLoader and CacheWriter

---

geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/JdbcDistributedTest.java
geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/JdbcLoaderIntegrationTest.java
geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/MySqlJdbcDistributedTest.java
geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/TestDate.java
geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/internal/TestConfigService.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommandDUnitTest.java
geode-connectors/src/integrationTest/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommandIntegrationTest.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/SqlToPdxInstanceCreator.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/configuration/RegionMapping.java
geode-connectors/src/main/resources/META-INF/schemas/geode.apache.org/schema/jdbc/jdbc-1.0.xsd
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/RegionMappingTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/SqlToPdxInstanceCreatorTest.java

GEODE-6000: make pdx-name required

---

ci/pipelines/pull-request/jinja.template.yml

GEODE-6009 add Java 11 PR checks to github

---

ci/pipelines/meta/deploy_meta.sh

also handles release branches a little better

GEODE-6040 fix deploy_meta.sh to pause pipelines correctly

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ExportClusterConfigurationCommandDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ExportClusterConfigurationCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ExportConfigCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ImportClusterConfigurationCommand.java

GEODE-5971: Refactor export/import commands to extend GfshCommand

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/GetCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/LocateEntryCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/PutCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/QueryCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/RemoveCommand.java

GEODE-5971: Refactor Data commands to extend GfshCommand

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/BackupDiskStoreCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CompactDiskStoreCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeDiskStoreCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListDiskStoresCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/RevokeMissingDiskStoreCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ShowMissingDiskStoreCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ValidateDiskStoreCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DescribeDiskStoreFunction.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/DescribeDiskStoreFunctionJUnitTest.java

GEODE-5971: Refactor diskstore commands to extend GfshCommand

---

geode-cq/src/upgradeTest/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscBCDUnitTest.java

GEODE-6051: Fix suspect string by using addIgnoredException.

---

geode-core/src/main/java/org/apache/geode/cache/query/internal/DefaultQuery.java
geode-core/src/test/java/org/apache/geode/cache/query/internal/QueryMonitorTest.java

- N/A If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

GEODE-6072: Clean up thread local between tests

---

ci/scripts/repeat-new-tests.sh

Keeps the PR from needing the entire repo for faster testing

GEODE-6059 - PR pipeline gets merge-base from resource

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeConfigCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/GetMemberConfigInformationFunction.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeConfigCommandTest.java

GEODE-6064: redact the password in describeConfig command

---

geode-core/src/main/java/org/apache/geode/redis/internal/executor/hash/HIncrByFloatExecutor.java
geode-core/src/main/java/org/apache/geode/redis/internal/executor/sortedset/GeoDistExecutor.java

GEODE-5998: Using primitive type (LGTM fix)

---

geode-assembly/src/distributedTest/java/org/apache/geode/rest/internal/web/controllers/RestAPITestBase.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/DistributedCacheTestCase.java
geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgrade2DUnitTestBase.java
geode-dunit/src/main/java/org/apache/geode/cache/client/internal/LocatorTestBase.java
geode-dunit/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheServerTestUtil.java
geode-dunit/src/main/java/org/apache/geode/internal/cache/wan/AsyncEventQueueTestBase.java
geode-dunit/src/main/java/org/apache/geode/security/ClientAuthorizationTestCase.java
geode-dunit/src/main/java/org/apache/geode/security/query/QuerySecurityBase.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/DistributedTestCase.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/cache/internal/JUnit4CacheTestCase.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/DistributedTestFixture.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/JUnit4DistributedTestCase.java

GEODE-6039: deprecate DistributedTestCase and associated.

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/JdbcPooledDataSourceFactory.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateDataSourceCommand.java
geode-core/src/main/java/org/apache/geode/datasource/PooledDataSourceFactory.java

Also fix parameter name in CreateDataSourceCommand

Update javadocs for data-source pool classes

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/eviction/EvictionDUnitTest.java

GEODE-5943: cleanup vm before each test

---

geode-core/src/integrationTest/java/org/apache/geode/management/internal/security/MBeanSecurityJUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/MBeanJMXAdapter.java
geode-core/src/main/java/org/apache/geode/management/internal/SystemManagementService.java
geode-core/src/test/java/org/apache/geode/management/internal/MBeanJMXAdapterTest.java

- N/A If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

GEODE-6052: Use constructor DI to avoid PowerMock in JMX tests

---

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/InternalDistributedMember.java
geode-core/src/main/java/org/apache/geode/internal/SystemAdmin.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXEntryState.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/FetchBulkEntriesMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/versions/RegionVersionHolder.java
geode-core/src/main/java/org/apache/geode/internal/concurrent/CompactConcurrentHashSet2.java
geode-core/src/main/java/org/apache/geode/internal/statistics/StatArchiveWriter.java
geode-core/src/test/java/org/apache/geode/internal/cache/TXEntryStateUnitTest.java
geode-dunit/src/main/java/batterytest/greplogs/LogConsumer.java
geode-dunit/src/main/java/org/apache/geode/internal/cache/PartitionedRegionGetSomeKeys.java

GEODE-6028: Remove checks that are not necessary.

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateDataSourceCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeDataSourceCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyMappingCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/ListMappingCommand.java

* Added commandAvailable method to all JDBC commands
* All commands set to only be available when connected

GEODE-6088: Enable GFSH command availability for JDBC commands

---

geode-core/src/distributedTest/java/org/apache/geode/distributed/ServerLauncherDUnitTestHelper.java

GEODE-4883: Set server port correctly for an ephemeral port

---

geode-connectors/build.gradle
geode-core/build.gradle
geode-dunit/build.gradle

GEODE-6113: Unable to run geode-web http-based dunit tests in IntelliJ

---

.gitignore
gradle/rat.gradle

GEODE-6110: Add .java-version to .gitignore and rat ignore list.

---

geode-connectors/build.gradle
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommandDUnitTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommandDUnitTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyMappingCommandDunitTest.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyMappingCommand.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommandTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommandTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyMappingCommandTest.java

Co-authored-by: Jianxia Chen <jchen21@apache.org>

GEODE-6118: Support slash on region name for jdbc-mapping commands

---

build.gradle
gradle/rat.gradle

GEODE-6130: Fix RAT to search from project root directory.

---

ci/pipelines/meta/jinja.template.yml

GEODE-6144 use concourse-pipeline-resource fix for large # of pipelines

---

geode-core/src/integrationTest/java/org/apache/geode/internal/logging/log4j/FastLoggerWithDefaultConfigIntegrationTest.java

This was accidental and it should have been importing from Mockito.

GEODE-6143: Change PowerMockito import to Mockito

---

geode-core/src/main/java/org/apache/geode/cache/configuration/CacheConfig.java
geode-core/src/main/java/org/apache/geode/internal/config/JAXBService.java
geode-core/src/main/java/org/apache/geode/internal/config/NameSpaceFilter.java
geode-core/src/main/java/org/apache/geode/internal/config/VersionAdapter.java
geode-core/src/test/java/org/apache/geode/internal/config/JAXBServiceTest.java

GEODE-5971: JaxbService should be able to unmarshall older namespace xml

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/lifecycle/StartJConsoleCommand.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/lifecycle/StartJConsoleCommandTest.java

GEODE-5971: refactor StartJConsoleCommand to use ResultModel

---

geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyMappingCommandDunitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommand.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommandTest.java

Co-authored-by: Jianxia Chen <jchen21@apache.org>

GEODE-6142: Check JDBC mapping before destroy region

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/StatusClusterConfigServiceCommandDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StatusClusterConfigServiceCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/FetchSharedConfigurationStatusFunction.java

- Added missing DUnit test for the command.
Signed-off-by: Ken Howe <khowe@pivotal.io>
Signed-off-by: Aditya Anchuri <aanchuri@pivotal.io>

GEODE-5971: Refactor StatusClusterConfigServiceCommand to extend GfshCommand base type

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/lifecycle/StartJVisualVMCommand.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/lifecycle/StartJVisualVMCommandTest.java

GEODE-5971: refactor StartJvisualvm command to use new ResultModel

---

gradle/java.gradle

@Bill @jhuynh1 @mcmellawatt @jinmeiliao 

GEODE-6168: verify java version should consider the possible "-"

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/shell/unsafe/GfshSignalHandler.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/shell/unsafe/GfshSignalHandlerTest.java

GEODE-6112: Gfsh should respond to SIGINT

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateDataSourceCommand.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/CreateDataSourceCommandTest.java

Co-autored-by: Jianxia Chen <jchen21@apache.org>

GEODE-6066: Fixed cluster config update for error case

---

geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/PartitionedRepositoryManagerJUnitTest.java

GEODE-6143: remove PowerMock from PartitionedRepositoryManagerJUnitTest

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateDataSourceCommand.java

GEODE-6179: update create data-source help

---

geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/UnregisterInterestTest.java

GEODE-6143: remove PowerMock from UnregisterInterestTest

---

geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/VMStatsMonitor.java
geode-core/src/test/java/org/apache/geode/management/internal/beans/stats/VMStatsMonitorTest.java

GEODE-6143: remove PowerMock from VMStatsMonitorTest

---

geode-core/src/test/java/org/apache/geode/internal/cache/tx/RemotePutMessageTest.java

GEODE-6143: remove PowerMock from RemotePutMessageTest

---

geode-core/src/distributedTest/java/org/apache/geode/cache/client/internal/ClientServerHostNameVerificationDistributedTest.java
geode-core/src/distributedTest/java/org/apache/geode/distributed/LocatorDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/distributed/LocatorUDPSecurityDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/tcpserver/TcpServerBackwardCompatDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/GridAdvisorDUnitTest.java
geode-core/src/main/java/org/apache/geode/distributed/DistributedSystem.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java
geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpClient.java
geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpServer.java

Geode 5793: LocatorDUnitTest. testNonSSLLocatorDiesWhenConnectingToSSLLocator

---

geode-core/src/main/java/org/apache/geode/internal/cache/control/MemoryThresholds.java
geode-core/src/test/java/org/apache/geode/internal/cache/control/HeapMemoryMonitorTest.java

GEODE-6143: remove PowerMock from HeapMemoryMonitorTest

---

geode-junit/src/main/java/org/apache/geode/internal/AvailablePortHelper.java

Removing an accidental ++ that was breaking the previous commit.

GEODE-5674: Stop picking ports randomly for tests

---

geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/ValueComparisonHelper.java
geode-core/src/main/java/org/apache/geode/internal/cache/entries/AbstractRegionEntry.java
geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionTest.java

* Treats a retried putIfAbsent operation a successful one if returned value is the value to be put
* Move the check value methods to ValueComparisonHelper class.

GEODE-6195: Check if returned value is caused by a retried putIfAbsent operation

---

geode-core/src/test/java/org/apache/geode/internal/offheap/DataTypeJUnitTest.java

GEODE-6143: remove PowerMock from DataTypeJUnitTest

---

ci/docker/Dockerfile
ci/images/google-geode-builder/scripts/setup.sh
ci/images/test-container/Dockerfile

GEODE-6216 add netstat to test images for NetstatDUnitTest

---

ci/scripts/execute_build.sh

GEODE-6223: Add resolveDependencies to Build test job.

---

ci/docker/Dockerfile
ci/images/google-geode-builder/scripts/setup.sh
ci/images/test-container/Dockerfile

GEODE-6227 add lsof to test images for NetstatDUnitTest

---

geode-core/build.gradle
geode-core/src/test/resources/expected-pom.xml

Please read the full description of GEODE-6154 before deciding if you support or object to these changes.

GEODE-6154: Remove optional from geode-core spring-shell dependency

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/ha/HARegionQueueIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/ha/HARegionQueueJUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java

GEODE-6143: remove PowerMock from HARegionQueueIntegrationTest

---

ci/pipelines/shared/jinja.variables.yml

GEODE-6231: Increase timeout for DistributedTest jobs.

---

geode-core/src/main/java/org/apache/geode/cache/configuration/RegionAttributesType.java

GEODE-5971: Remove Javadoc references to deleted expiration classes in RegionAttributesType

---

geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImplJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/beans/ManagementAdapterTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/persistence/PersistenceInitialImageAdvisorTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListGatewayCommandTest.java
geode-core/src/test/java/org/apache/geode/pdx/internal/PdxInstanceImplTest.java

Also, minor cleanup to remove warnings and/or follow best practices.

GEODE-6143: Import methods from Mockito instead of PowerMockito

---

geode-core/src/test/java/org/apache/geode/cache/query/internal/types/TypeUtilsJUnitTest.java

GEODE-6143: remove PowerMock from TypeUtilsJUnitTest

---

ci/scripts/run_benchmarks.sh
gradle.properties

Signed-off-by: Helena A. Bales <hbales@pivotal.io>

GEODE-6275: Fail when benchmark pipes fails.

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingFunction.java
geode-connectors/src/main/java/org/apache/geode/connectors/util/internal/DescribeMappingResult.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingFunctionTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/org/apache/geode/connectors/util/DescribeMappingCommandTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/util/internal/DescribeMappingResultTest.java
geode-junit/src/main/java/org/apache/geode/test/junit/assertions/CommandResultAssert.java

Co-authored-by: Rob Day-Reynolds <rdayreynolds@pivotal.io>

GEODE-6187: Added sorting and hid empty attributes for DescribeMappingCommand

---

geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/JdbcLoaderIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/pdx/PdxInstanceFactoryJUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/RegionService.java
geode-core/src/main/java/org/apache/geode/pdx/internal/PdxInstanceFactoryImpl.java

GEODE-6289: check for null className on createPdxInstanceFactory

---

geode-core/src/main/java/org/apache/geode/internal/cache/ValueComparisonHelper.java
geode-core/src/test/java/org/apache/geode/internal/cache/ValueComparisonHelperTest.java

* fixed an error in the helper class  when adding test coverage.

GEODE-6212: Add unit test coverage for ValueComparisonHelper

---

geode-core/src/main/java/org/apache/geode/management/internal/beans/ManagementListener.java
geode-core/src/test/java/org/apache/geode/management/internal/beans/ManagementListenerTest.java

This change is required for the RegressionTest that I attached to [GEODE-6255: ManagementListener may deadlock with Cache close](https://issues.apache.org/jira/browse/GEODE-6255).

GEODE-6255: Make ManagementListener testable and interruptible

---

ci/pipelines/geode-build/jinja.template.yml

Increase benchmark job timeout.

---

geode-docs/reference/topics/gemfire_properties.html.md.erb

PR created with klund@apache.org

GEODE-6294 Document new disable-jmx property

---

geode-core/src/integrationTest/java/org/apache/geode/internal/statistics/GemFireStatSamplerIntegrationTest.java

- Convert all assertions to AssertJ and make them more informative.
- Convert all polling loops to Awaitility.
The goal of this commit is to improve the test to give better information in future runs.
Please review @mhansonp

GEODE-6325: Clarify start time assertion

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ExecuteFunctionCommandDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ExecuteFunctionCommandSecurityTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/execute/CoreFunctionSecurityTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ExecuteFunctionCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/UserFunctionExecution.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/UserFunctionExecutionTest.java
geode-web/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ExecuteFunctionCommandWithSecurityDUnitTest.java

GEODE-6293: Fix fire & forget functions in gfsh

---

geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionMessage.java
geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
geode-core/src/main/java/org/apache/geode/internal/util/PluckStacks.java

GEODE-6339: centralize thread name string

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/CacheClientNotifierDUnitTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/Simple2CacheServerDUnitTest.java

@boglesby @bschuchardt @jhuynh1 

GEODE-6344: should revert GEODE-1183 before a better fix

---

geode-core/src/main/java/org/apache/geode/internal/cache/control/HeapMemoryMonitor.java

GEODE-6347: Adding better logging around critical threshold state change

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/RemoteTransactionDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/TXJUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/TransactionEvent.java
geode-core/src/main/java/org/apache/geode/cache/TransactionListener.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/RemoteCQTransactionDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/cache30/MultiVMRegionTestCase.java
geode-junit/src/main/java/org/apache/geode/cache/util/TxEventTestUtil.java

Please review @kirklund @mhansonp

GEODE-6339: Revert TransactionEvent Generification

---

geode-core/src/integrationTest/java/org/apache/geode/distributed/LauncherMemberMXBeanIntegrationTest.java

- Because metrics can change between retrievals, we're never guaranteed to be
able to match exactly. If the upstream code is really broken then this retry
approach should not hide that.

GEODE-5782: Add some retry logic to retrieving metrics

---

geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommandDUnitTest.java

Authored-by: Jianxia Chen <jchen@pivotal.io>

GEODE-6354: Add missing server group assertion

---

geode-dunit/src/main/java/org/apache/geode/cache30/MultiVMRegionTestCase.java

GEODE-6277: use await() instead of hard-coded sleep(3000) in the test

---

ci/pipelines/geode-build/jinja.template.yml

GEODE-6373: Increased the timeout on benchmark tests to 4h

---

geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/shell/GfshConsoleModeIntegrationTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/shell/GfshAbstractUnitTest.java

- This avoids subsequent tests failing because they are checking for the
presence of LogWrapper.

GEODE-6370: Clean up LogWrapper between tests

---

geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/FunctionStats.java

This is mostly cleanup, but also fix `getFunctionStats()` and `getFunctionServiceStats()`.

GEODE-6355: Fix broken stats in InternalDistributedSystem.

---

ci/scripts/run_benchmarks.sh

* change geode benchmark branch from -m to -e
* use the new -m option to specify metadata for ci runs of benchmarks

GEODE-6340: use new cli options for benchmarks

---

geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/SharedErrorCollectorDistributedTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/SharedErrorCollector.java
geode-junit/src/main/java/org/apache/geode/test/junit/runners/TestRunner.java

Make SharedErrorCollector support create and bounce VM.

GEODE-6033: Support dynamic VMs in SharedErrorCollector

---

gradle/pmd.gradle

GEODE-6380: Making pmd.gradle more portable

---

geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/SharedCountersRuleDistributedTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/VM.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/SharedCountersRule.java
geode-junit/src/main/java/org/apache/geode/test/junit/runners/TestRunner.java

Make SharedCountersRule support create and bounce VM.

GEODE-6033: Support dynamic VMs in SharedCountersRule

---

geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedRestoreSystemPropertiesDistributedTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/AbstractDistributedRule.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedRestoreSystemProperties.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedRule.java

Make DistributedRestoreSystemProperties support create and bounce VM.

GEODE-6033: Support dynamic VMs in DistributedRestoreSystemProperties

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionSingleHopDUnitTest.java

GEODE-6441: refactor the test to use await instead of sleep

---

geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/ListMappingCommandDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommand.java

GEODE-6365: Fixed logic error in DestroyRegionCommand

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ClusterManagementLocatorReconnectDunitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RegionManagementDunitTest.java
geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/DisabledClusterConfigTest.java
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/test/java/org/apache/geode/management/internal/api/ClusterManagementResultTest.java
geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementResult.java

GEODE-6174: rename ClusterManagementResult methods to avoid confusion.

---

ci/pipelines/shared/jinja.variables.yml

GEODE-6447: Windows Acceptance and Integration tests should not run in parallel

---

geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderQueueDUnitTest.java

GEODE-6435: Reduced gateway sender socket buffer size

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
geode-assembly/src/integrationTest/resources/expected_jars.txt
geode-assembly/src/test/resources/expected-pom.xml
geode-common/src/test/resources/expected-pom.xml
geode-concurrency-test/src/test/resources/expected-pom.xml
geode-connectors/src/test/resources/expected-pom.xml
geode-core/src/test/resources/expected-pom.xml
geode-cq/src/test/resources/expected-pom.xml
geode-dunit/src/test/resources/expected-pom.xml
geode-experimental-driver/src/test/resources/expected-pom.xml
geode-json/src/test/resources/expected-pom.xml
geode-junit/src/test/resources/expected-pom.xml
geode-lucene/src/test/resources/expected-pom.xml
geode-management/src/test/resources/expected-pom.xml
geode-old-client-support/src/test/resources/expected-pom.xml
geode-protobuf-messages/src/test/resources/expected-pom.xml
geode-protobuf/src/test/resources/expected-pom.xml
geode-pulse/src/test/resources/expected-pom.xml
geode-rebalancer/src/test/resources/expected-pom.xml
geode-wan/src/test/resources/expected-pom.xml
geode-web-api/src/test/resources/expected-pom.xml
geode-web-management/src/test/resources/expected-pom.xml
geode-web/src/test/resources/expected-pom.xml
gradle/geode-dependency-management.gradle

GEODE-6439: Bump version of jackson-module-scala_2.10

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/commands/DeployWithLargeJarTest.java
geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/commands/DestroyIndexIfExistsTest.java
geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/commands/ImportClusterConfigTest.java
geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/commands/StopServerAcceptanceTest.java
geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/commands/StopServerWithSecurityAcceptanceTest.java
geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/shell/StatusServerExitCodeAcceptanceTest.java

GEODE-6372: use random port when starting server to avoid port conflict

---

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/InternalDistributedMember.java
geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMember.java
geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitor.java
geode-core/src/main/java/org/apache/geode/internal/InternalDataSerializer.java
geode-core/src/main/java/org/apache/geode/internal/Version.java
geode-core/src/main/java/org/apache/geode/internal/cache/DestroyPartitionedRegionMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/EventID.java
geode-core/src/main/java/org/apache/geode/internal/cache/ExpireDisconnectedClientTransactionsMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/InvalidatePartitionedRegionMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/LatestLastAccessTimeOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXCommitMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CommandInitializer.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/GatewaySenderEventImpl.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/domain/XmlEntity.java
geode-core/src/test/java/org/apache/geode/internal/VersionJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/ExpireDisconnectedClientTransactionsMessageTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateGatewaySenderCommandTest.java
geode-cq/src/upgradeTest/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscBCDUnitTest.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneIndexCreationProfile.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneServiceImpl.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommands.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/distributed/LuceneQueryFunction.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsJUnitTest.java

GEODE-6434: Changing ordinal variables to GEODE_X_Y_Z format

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/configuration/ClusterConfigLocatorRestartDUnitTest.java

GEODE-6437: add more ignored exceptions

---

geode-core/src/main/java/org/apache/geode/distributed/internal/locks/DLockGrantor.java
geode-core/src/test/java/org/apache/geode/distributed/internal/locks/DLockGrantorTest.java

GEODE-6379: track departed members to avoid processing in-flight lock request

---

geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommandDUnitTest.java
geode-connectors/src/distributedTest/resources/org/apache/geode/internal/ResourcePDX.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingPreconditionCheckFunction.java

GEODE-6457: Use ClassPathLoader for create jdbc-mapping

---

geode-docs/tools_modules/gfsh/command-pages/configure.html.md.erb

GEODE-4794 User Guide - update description of `gfsh configure pdx` command.

---

ci/pipelines/geode-build/jinja.template.yml

* These are only visible under the 'Semver Management' group.

GEODE-6460: Add semver controls to pipeline.

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/rest/StandaloneClientManagementAPIAcceptanceTest.java
geode-assembly/src/acceptanceTest/resources/ManagementClientCreateRegion.java
geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/internal/ProcessLogger.java

- Also restore more detailed logging in ProcessLogger.

GEODE-6473: Create a test which utilizes the geode-management.jar

---

geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java

- [] Have you written or updated unit tests to verify your changes?

GEODE-6475: Adding isDisconnected() method to InternalDistributedSystem

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DescribeMembersCommandDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/DescribeConnectionCommandIntegrationTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/CliUtil.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeClientCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeConfigCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeConnectionCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeMemberCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java
geode-junit/src/main/java/org/apache/geode/test/junit/assertions/CommandResultAssert.java

GEODE-5971: refactor DescribeXXCommand to use ResultModel

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/rest/StandaloneClientManagementAPIAcceptanceTest.java
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ShowMissingDiskStoreCommand.java
geode-management/build.gradle
geode-management/src/main/java/org/apache/geode/management/internal/ClientClusterManagementService.java
geode-management/src/test/resources/expected-pom.xml

GEODE-7: compile using jdk11

---

geode-cq/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DescribeClientCommandDUnitTest.java

GEODE-5971: fix a flaky test on windows

---

geode-web-api/src/integrationTest/java/org/apache/geode/rest/internal/web/controllers/RestAccessControllerTest.java
geode-web-api/src/integrationTest/resources/org/apache/geode/rest/internal/web/controllers/order1-array.json
geode-web-api/src/main/java/org/apache/geode/rest/internal/web/controllers/AbstractBaseController.java
geode-web-api/src/main/java/org/apache/geode/rest/internal/web/controllers/CommonCrudController.java
geode-web-api/src/main/java/org/apache/geode/rest/internal/web/controllers/FunctionAccessController.java
geode-web-api/src/main/java/org/apache/geode/rest/internal/web/util/JSONUtils.java

GEODE-5016: Replace org.json with Jackson in geode-web-api

---

ci/pipelines/examples/deploy_pipeline.sh
ci/pipelines/examples/jinja.template.yml
ci/pipelines/geode-build/deploy_pipeline.sh
ci/pipelines/geode-build/jinja.template.yml
ci/pipelines/images/deploy_images_pipeline.sh
ci/pipelines/images/jinja.template.yml
ci/pipelines/meta/deploy_meta.sh
ci/pipelines/meta/jinja.template.yml
ci/pipelines/metrics/deploy_metrics_pipeline.sh
ci/pipelines/metrics/jinja.template.yml
ci/pipelines/pull-request/deploy_pr_pipeline.sh
ci/pipelines/pull-request/jinja.template.yml
ci/pipelines/render.py
ci/pipelines/shared/jinja.variables.yml

GEODE-6483: Separate concerns of render.py.

---

geode-core/src/main/java/org/apache/geode/internal/cache/InitialImageOperation.java
geode-core/src/test/java/org/apache/geode/internal/cache/InitialImageOperationTest.java

GEODE-6497: Send failed message to image requester when provider is shutting down.

---

ci/scripts/cleanup_benchmarks.sh
ci/scripts/run_benchmarks.sh

Use the new CLI options and add --ci option to reflect changes to
benchmark scripts.

GEODE-6479: change calls to benchmark

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/PersistentPartitionedRegionDistributedTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/lang/ThrowableUtils.java
geode-core/src/test/java/org/apache/geode/internal/lang/ThrowableUtilsTest.java

GEODE-6348: Wait for cache to close in test of ConflictingPersistentData

---

geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/JdbcAsyncWriterIntegrationTest.java
geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/JdbcDistributedTest.java
geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/JdbcLoaderIntegrationTest.java
geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/JdbcWriterIntegrationTest.java
geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/MySqlJdbcLoaderIntegrationTest.java
geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/PostgresJdbcLoaderIntegrationTest.java
geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/PostgresJdbcWriterIntegrationTest.java
geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/TestDataSourceFactory.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/JdbcConnectorService.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/JdbcConnectorServiceImpl.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/SqlHandler.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/SqlToPdxInstance.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/configuration/RegionMapping.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/xml/RegionMappingConfiguration.java
geode-connectors/src/main/java/org/apache/geode/connectors/util/internal/MappingConstants.java
geode-connectors/src/main/resources/META-INF/schemas/geode.apache.org/schema/jdbc/jdbc-1.0.xsd
geode-connectors/src/main/resources/org/apache/geode/internal/sanctioned-geode-connectors-serializables.txt
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/JdbcConnectorServiceTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/RegionMappingTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/SqlHandlerTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/SqlToPdxInstanceTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommandTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java

GEODE-6461: at startup fail if jdbc info from create jdbc-mapping has changed

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DeployWithGroupsDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DeployCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyFunctionCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ExecuteFunctionCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListDeployedCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListFunctionCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/UndeployCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/ListDeployedFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/ListFunctionFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/UndeployFunction.java
geode-dunit/src/main/java/org/apache/geode/management/internal/cli/commands/FunctionCommandsDUnitTestBase.java

- DeployCommand
- DestroyFunctionCommand
- ExecuteFunctionCommand
- ListDeployedCommand
- ListFunctionCommand
- UndeployCommand

GEODE-5971: Refactoring various commands

---

geode-assembly/src/acceptanceTest/resources/ManagementClientCreateRegion.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ClusterManagementLocatorReconnectDunitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ManagementRequestLoggingDUnitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RegionManagementDunitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RegionManagementRestSecurityDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/CacheConfigDAODUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/api/RegionAPIDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/configuration/mutators/RegionConfigMutatorIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/configuration/realizers/RegionConfigRealizerIntegrationTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidator.java
geode-core/src/test/java/org/apache/geode/cache/configuration/CacheConfigTest.java
geode-core/src/test/java/org/apache/geode/cache/configuration/RegionConfigTest.java
geode-core/src/test/java/org/apache/geode/distributed/internal/InternalConfigurationPersistenceServiceTest.java
geode-core/src/test/java/org/apache/geode/internal/config/JAXBServiceTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/AlterRegionCommandTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/realizers/RegionConfigRealizerTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidatorTest.java
geode-management/src/main/java/org/apache/geode/cache/RegionShortcut.java
geode-management/src/main/java/org/apache/geode/cache/configuration/RegionConfig.java
geode-web-management/src/distributedTest/java/org/apache/geode/management/client/ClientClusterManagementServiceDUnitTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementIntegrationTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementSecurityIntegrationTest.java

GEODE-6505: Use Enum instead of String for RegionConfig type

---

geode-web-api/src/integrationTest/java/org/apache/geode/rest/internal/web/controllers/EchoArgumentFunction.java
geode-web-api/src/integrationTest/java/org/apache/geode/rest/internal/web/controllers/RestAccessControllerTest.java
geode-web-api/src/main/java/org/apache/geode/rest/internal/web/controllers/AbstractBaseController.java

GEODE-6506: Don't return JSONy objects when converting from json to Object arrays

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListDeployedCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListFunctionCommand.java

GEODE-5971: fix NPE in the gfsh command

---

geode-core/src/jmh/java/org/apache/geode/cache/query/internal/MonitorQueryUnderContentionBenchmark.java

GEODE-6488: Fixing QueryMonitor JMH test

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/GIIDeltaDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentRVVRecoveryDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/TXJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/query/PdxStringQueryJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/query/RegionJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/query/functional/QueryREUpdateInProgressJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/RegionEntryFlagsJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/UpdateVersionJUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/AbstractIndex.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/CompactRangeIndex.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/DummyQRegion.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/HashIndex.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/MapIndexStore.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/MemoryIndexStore.java
geode-core/src/main/java/org/apache/geode/internal/cache/EntriesSet.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalDataSet.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegionDataView.java
geode-core/src/main/java/org/apache/geode/internal/cache/NonTXEntry.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/FetchEntriesMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/snapshot/SnapshotPacket.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/BaseCommand.java
geode-core/src/test/java/org/apache/geode/cache/query/internal/RestrictedMethodInvocationAuthorizerTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/TXStateProxyImplTest.java
geode-junit/src/main/java/org/apache/geode/internal/cache/DiskRegionTestingBase.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/UpdateVersionDUnitTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/misc/NewWANConcurrencyCheckForDestroyDUnitTest.java

[Part of GEODE-6534: Refactor LocalRegion]

GEODE-6534: Extract NonTXEntry from LocalRegion

---

boms/geode-all-bom/src/test/resources/expected-pom.xml

Update Expected POM

---

geode-core/src/distributedTest/java/org/apache/geode/pdx/PdxMultiClusterClientServerDUnitTest.java
geode-core/src/main/java/org/apache/geode/pdx/internal/ClientTypeRegistration.java

Copying a type to additional pools on the client may fail if not servers
are running in those additional pools. Ignoring failures due to copying
a type from one pool to another.
Also, simplifying the logic in addImportedType/Enum to make it clear that those methods
stop at the first failure.

GEODE-6271: Ignore failures from other pools

---

geode-core/src/main/java/org/apache/geode/internal/cache/ExpiryRegionEntry.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java

Please review: @demery-pivotal @mhansonp @moleske

GEODE-6534: Extract ExpiryRegionEntry from LocalRegion

---

geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/DebuggableCommand.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementService.java

GEODE-6523 - Prepends gemfire to the feature flag

---

geode-core/src/main/java/org/apache/geode/internal/cache/NonTXEntry.java

[Part of GEODE-6534: Refactor LocalRegion]
Make the boolean entryIsDestroyed thread safe.
Note: I'm preparing to move NonTXEntry to top-level class. I want to isolate the only thread-safety change to this single commit.

GEODE-6534: Make NonTXEntry entryIsDestroyed volatile

---

geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java

GEODE-6553: Make resourceListeners in InternalDistributedSystem a final field

---

geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java

* Reduce visibility of classes and fields
* Add @VisibleForTesting annotations
* Add final to several fields

GEODE-6534: Move LocalRegion nested classes to bottom of class

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DeployCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyFunctionCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ShowMetricsInterceptor.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/result/model/FileResultModel.java

DestroyFunctionCommand to use ResultModel

GEODE-5971 Refactors ShowMetricsInterceptor, DeployFunctionCommand and

---

geode-pulse/geode-pulse-test/src/main/java/org/apache/geode/tools/pulse/tests/PulseTestLocators.java
geode-pulse/geode-pulse-test/src/main/java/org/apache/geode/tools/pulse/tests/rules/WebDriverRule.java
geode-pulse/geode-pulse-test/src/main/resources/pulse-auth.json
geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/data/Repository.java
geode-pulse/src/main/webapp/WEB-INF/spring-security.xml
geode-pulse/src/main/webapp/accessDenied.html
geode-pulse/src/uiTest/java/org/apache/geode/tools/pulse/tests/ui/PulseAuthorizationTest.java

GEODE-6544: Handle unauthorised accesses to Pulse
- Added a new 'access Denied' page to be used whenever an already
authenticated operator tries to access a resource for which not enough
permissions are granted.

GEODE-6544: Handle unauthorised accesses to Pulse

---

boms/geode-all-bom/build.gradle
geode-assembly/build.gradle
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt
geode-protobuf-messages/build.gradle

geode-all-bom shouldn't make a jar

---

geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/HistoryCommandIntegrationTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/HistoryCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListIndexCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/PDXRenameCommand.java

GEODE-5971: refactor misc commands to use ResultModel

---

geode-concurrency-test/build.gradle
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/ConcurrentTestRunner.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/ParallelExecutor.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/Utilities.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/loop/LoopRunner.java
geode-concurrency-test/src/test/java/org/apache/geode/test/concurrency/ConcurrentTestRunnerTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/pooling/AvailableConnectionManagerConcurrentTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/pooling/ConnectionAccountingConcurrentTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerImplTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerJUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/OpExecutorImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/AvailableConnectionManager.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/ConnectionAccounting.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/ConnectionManager.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/PooledConnection.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/OpExecutorImplJUnitTest.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/pooling/AvailableConnectionManagerTest.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/pooling/ConnectionAccountingTest.java

Refactor ConnectionManagerImpl to a non-blocking implementation.
Signed-off-by: Darrel Schneider <dschneider@pivotal.io>

GEODE-6515: refactor ConnectionManagerImpl

---

build.gradle
gradle/rat.gradle

Update Gradle plugins to latest versions.

---

geode-docs/developing/events/limit_server_subscription_queue_size.html.md.erb

I tried to make this passage in the doc self-consistent. I also tried to clarify the message by eliminating some redundancy.

GEODE-6585: clarify subscription-ack-interval

---

geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImplJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/QueueManagerJUnitTest.java
geode-core/src/main/java/org/apache/geode/DataSerializer.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ConnectionSource.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/EndpointManagerImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ExplicitConnectionSourceImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/LiveServerPinger.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/PoolImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/QueueConnectionImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/QueueManager.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/QueueManagerImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/RegisterInterestTracker.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ServerDenyList.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/locator/ClientConnectionRequest.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/locator/ClientReplacementRequest.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/locator/GetAllServersResponse.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/locator/QueueConnectionResponse.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/locator/SerializationHelper.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/ExecutionContext.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/QScope.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/RuntimeIterator.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionAdvisor.java
geode-core/src/main/java/org/apache/geode/distributed/internal/LocatorLoadSnapshot.java
geode-core/src/main/java/org/apache/geode/internal/InternalDataSerializer.java
geode-core/src/main/java/org/apache/geode/internal/cache/ProxyBucketRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/RegionAdvisor.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/ops/ServerCQProxyImpl.java

GEODE-6588: Cleanup generics and other static analyzer issues.

---

geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java
geode-web-management/build.gradle
geode-web-management/src/commonTest/java/org/apache/geode/management/internal/rest/BaseLocatorContextLoader.java
geode-web-management/src/commonTest/java/org/apache/geode/management/internal/rest/LocatorWebContext.java
geode-web-management/src/distributedTest/java/org/apache/geode/management/client/ClientClusterManagementServiceDUnitTest.java
geode-web-management/src/distributedTest/java/org/apache/geode/management/client/MemberManagementServiceDUnitTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementIntegrationTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementSecurityIntegrationTest.java

* adding request/response logging in the controller tests

GEODE-6574: create a LocatorWebContext to ease controller testing using Spring mock context

---

geode-assembly/build.gradle
geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/rest/GradleBuildWithGeodeCoreAcceptanceTest.java
geode-assembly/src/acceptanceTest/resources/gradle-test-projects/management/build.gradle

GEODE-6589: Parameterize gradle project group for use in GradleBuildWithGeodeCoreAcceptanceTest

---

geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionMetricsTest.java

GEODE-6600: Remove meters on region close

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentRecoveryOrderDUnitTest.java

It's actually pretty likely that a thread is going to catch and then
log a DistributedSystemDisconnectedException or CacheClosedException.
Use addIgnoredException for both types.

GEODE-4267: Fix suspect string in testCrashDuringPreparePersistentId

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ClientClusterManagementServiceDunitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java
geode-management/src/main/java/org/apache/geode/management/internal/ClientClusterManagementService.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementIntegrationTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementSecurityIntegrationTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RegionManagementController.java

GEODE-6560 - Geode Management REST supports creating regions by group

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/SetVariableCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ShCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ShutdownCommand.java

GEODE-5971: refactor various commands to use ResultModel

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DescribeMembersCommandDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeMemberCommand.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/ServerStarterRule.java

* add support for multiple cache servers in ServerStartupRule

GEODE-5971: describe member failed to display multiple cache servers

---

geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommandDUnitTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommandForProxyRegionDUnitTest.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommand.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommandTest.java

GEODE-6592: Added --if-not-exists flag to CreateMappingCommand

---

geode-core/src/distributedTest/java/org/apache/geode/internal/metrics/MeterSubregistryReconnectDistributedTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/CacheFactoryIntegrationTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalCache.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalCacheBuilder.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalCacheForClientAccess.java
geode-core/src/main/java/org/apache/geode/internal/cache/ReconnectableCache.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheCreation.java
geode-core/src/test/java/org/apache/geode/internal/cache/InternalCacheBuilderAllowsMultipleSystemsTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/InternalCacheBuilderTest.java

Please review: @demery-pivotal

GEODE-6606: Support added MeterSubregistries in reconnect

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionCollection.java
geode-protobuf/src/test/java/org/apache/geode/internal/cache/tier/sockets/ProtobufServerConnectionTest.java

Remove synchronization around changing values that could be volatile and
that are atomic. Results in a performance gain.

GEODE-6584: remove unecessary synchronization

---

geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/GfshCommandIntegrationTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/remote/CommandExecutor.java

GEODE-6602: gfsh commands should be logged in locator log

---

geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidator.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidatorTest.java
geode-management/src/main/java/org/apache/geode/cache/configuration/RegionType.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementIntegrationTest.java

GEODE-6505: add more RegionType and type validation

---

geode-assembly/src/acceptanceTest/resources/ManagementClientTestCreateRegion.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ClientClusterManagementSSLTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ClientClusterManagementServiceDunitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ClusterManagementLocatorReconnectDunitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ClusterManagementServiceOnServerTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ManagementRequestLoggingDUnitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RegionManagementDunitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RegionManagementRestSecurityDUnitTest.java
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/CacheConfigDAODUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/api/RegionAPIDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/configuration/mutators/RegionConfigMutatorIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/configuration/realizers/RegionConfigRealizerIntegrationTest.java
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/UpdateCacheFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/RegionConfigManager.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/realizers/RegionConfigRealizer.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidator.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt
geode-core/src/test/java/org/apache/geode/cache/configuration/RegionConfigTest.java
geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java
geode-management/src/main/java/org/apache/geode/cache/configuration/BasicRegionConfig.java
geode-management/src/main/java/org/apache/geode/cache/configuration/CacheConfig.java
geode-management/src/main/java/org/apache/geode/cache/configuration/RegionConfig.java
geode-management/src/test/java/org/apache/geode/cache/configuration/CacheElementJsonMappingTest.java
geode-web-management/src/distributedTest/java/org/apache/geode/management/client/ClientClusterManagementServiceDUnitTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementIntegrationTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementSecurityIntegrationTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RegionManagementController.java

GEODE-6612: move attributes that can not be configured in v2 api out of RegionConfig

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/build.gradle
geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/rest/StandaloneClientManagementAPIAcceptanceTest.java
geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/rest/SwaggerManagementVerificationIntegrationTest.java
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt
geode-core/build.gradle
geode-core/src/test/resources/expected-pom.xml
geode-management/build.gradle
geode-management/src/main/java/org/apache/geode/cache/configuration/BasicRegionConfig.java
geode-management/src/main/java/org/apache/geode/management/api/RestfulEndpoint.java
geode-web-management/build.gradle
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/ManagementLoggingFilter.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RegionManagementController.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/swagger/SwaggerConfig.java
geode-web-management/src/main/resources/swagger-management.properties
geode-web-management/src/main/webapp/docs/index.html
geode-web-management/src/test/resources/expected-pom.xml

GEODE-6608: Add Swagger UI to Management REST API

---

geode-assembly/src/acceptanceTest/resources/ManagementClientTestCreateRegion.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ClientClusterManagementServiceDunitTest.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/configuration/RegionMapping.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/api/RegionAPIDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt
geode-core/src/test/java/org/apache/geode/internal/config/JAXBServiceTest.java
geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/management/configuration/Index.java
geode-management/src/main/java/org/apache/geode/cache/configuration/BasicRegionConfig.java
geode-management/src/main/java/org/apache/geode/cache/configuration/CacheConfig.java
geode-management/src/main/java/org/apache/geode/cache/configuration/CacheElement.java
geode-management/src/main/java/org/apache/geode/cache/configuration/DiskStoreType.java
geode-management/src/main/java/org/apache/geode/cache/configuration/JndiBindingsType.java
geode-management/src/main/java/org/apache/geode/cache/configuration/RegionConfig.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementService.java
geode-management/src/main/java/org/apache/geode/management/configuration/MemberConfig.java
geode-management/src/main/java/org/apache/geode/management/internal/ClientClusterManagementService.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RegionManagementController.java

GEODE-6612: make group an attribute in CacheElement

---

geode-core/src/main/java/org/apache/geode/internal/cache/ProxyBucketRegion.java

GEODE-6621: ensure that getBucketOwners result is modifiable

---

boms/geode-all-bom/build.gradle

Only include plugins used in the project. In this case, our `java`
plugin, not the rest

GEODE-6611: Audit geode-all-bom plugin inclusions

---

geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/rebalance/PartitionedRegionLoadModelJUnitTest.java

GEODE-6618: Remove PartitionedRegionLoadModelJUnitTest etc hosts dependency

---

geode-core/src/main/java/org/apache/geode/pdx/internal/json/PdxToJSON.java
geode-experimental-driver/src/integrationTest/java/org/apache/geode/experimental/driver/RegionIntegrationTest.java
geode-protobuf/src/distributedTest/java/org/apache/geode/internal/protocol/protobuf/v1/operations/GetAndPutJsonDocumentsDUnitTest.java
geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/serialization/codec/JsonPdxConverterJUnitTest.java

GEODE-6633: Remove JSON pretty printing from PdxToJSON

---

geode-junit/src/main/java/org/apache/geode/test/junit/assertions/ClusterManagementResultAssert.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementIntegrationTest.java

GEODE-6612: create ClusterManagementResultAssert for assert chaining

---

geode-core/src/main/java/org/apache/geode/cache/util/ObjectSizer.java

GEODE-5724: Fixed typo with link in javadoc

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ListRegionManagementDunitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/ConfigurationManager.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/RegionConfigManager.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidator.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidatorTest.java
geode-management/src/main/java/org/apache/geode/cache/configuration/CacheElement.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementResult.java
geode-management/src/main/java/org/apache/geode/management/internal/ClientClusterManagementService.java
geode-management/src/test/java/org/apache/geode/cache/configuration/CacheElementJsonMappingTest.java
geode-web-management/src/distributedTest/java/org/apache/geode/management/client/ClientClusterManagementServiceDUnitTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementIntegrationTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/MemberManagementController.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RegionManagementController.java

* implement list api in RegionConfigManager
* add more validation if user passes in invalid group/config information.

GEODE-6612: list regions in Management v2 api

---

geode-core/src/main/java/org/apache/geode/management/internal/security/MBeanServerWrapper.java

GEODE-6627: Authorization is now called only on unique context values

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreatePooledJndiBindingDUnitTest.java

Authored-by: Jianxia Chen <jchen21@apache.org>

GEODE-6647: Move CreatePooledJndiBindingDUnitTest

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/TXDetectReadConflictJUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java

GEODE-6651: Fixed NPE

---

ci/pipelines/shared/jinja.variables.yml
ci/scripts/repeat-new-tests.sh
gradle/test.gradle

GEODE-6634: Fix parallel option for repeatTest

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientHealthMonitor.java
geode-core/src/main/java/org/apache/geode/internal/util/JavaWorkarounds.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientHealthMonitorTest.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientTestBase.java

 GEODE-6649: Remove lock contention in ClientHealthMonitor heartbeats.

---

geode-connectors/src/acceptanceTest/java/org/apache/geode/connectors/jdbc/JdbcDistributedTest.java

GEODE-6640: add integration tests to do put, invalidate, then get from async JDBC mapping

---

geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpServer.java

To avoid filling up logs, only log the exception message, not the full stack trace

GEODE-6666: Catch SocketTimeoutException

---

extensions/geode-modules/src/integrationTest/java/org/apache/geode/modules/util/BootstrappingFunctionTest.java
extensions/geode-modules/src/main/java/org/apache/geode/modules/util/BootstrappingFunction.java

- [N] Has your PR been rebased against the latest commit within the target branch (typically `develop`)? …

GEODE-6665: Avoid creating regions on Locator

---

geode-core/src/distributedTest/java/org/apache/geode/cache30/CacheXMLPartitionResolver.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/fixed/QuarterPartitionResolver.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/fixed/SingleHopQuarterPartitionResolver.java
geode-dunit/src/main/java/org/apache/geode/internal/cache/execute/CustomerIDPartitionResolver.java

* Added hashCode methods to classes that were missing one.

GEODE-5986 Inconsistent equals/hashCode

---

boms/geode-all-bom/build.gradle
boms/geode-all-bom/src/test/resources/expected-pom.xml

* Add repository specification from publish.gradle to bom publishing
block.  This configuration should be extracted in a future commit to
avoid duplication of code.  Without this block, the bom publish task
appears always UP-TO-DATE.
* Add signing, also previously in publish.gradle.
* Extra work with scope removed.  As a bom without scope will default to
'compile' scope, and as explicit is better than implicit, the extra work
was superfluous.
-----
Side note: Who made the design decision that a publication task with no publication targets another other than a task failure..?
-----
- [n/a] If adding new dependencies to the …

GEODE-6611: Correct publication issues in all-bom.

---

ci/scripts/run_benchmarks.sh

reduce verbosity of benchmark CI output and update version numbers due to new release

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/rest/StandaloneClientManagementAPIAcceptanceTest.java
geode-assembly/src/acceptanceTest/resources/ManagementClientTestCreateRegion.java

GEODE-6679: Use ephemeral ports in StandaloneClientManagementAPIAcceptanceTest

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommand.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommandInterceptorTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/extension/mock/MockExtensionCommands.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ChangeLogLevelCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateGatewaySenderCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DeployCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListClientCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/lifecycle/StartPulseCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/lifecycle/StartVsdCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/result/ResultBuilder.java
geode-junit/src/main/java/org/apache/geode/test/junit/assertions/ResultModelAssert.java

GEODE-5971: refactor remaining command's usage of Result

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/PersistentPartitionHangsDuringRestartRegressionTest.java

Cleanup comments, WAIT_TO_BOUNCE latch, await timeout and tearDown.
Use static imports to improve readability.

GEODE-6656: Fix up PersistentPartitionHangsDuringRestartRegressionTest

---

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/InternalDistributedMember.java

GEODE-6697: Make system property controlled variable static.

---

geode-assembly/src/acceptanceTest/resources/ManagementClientTestCreateRegion.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/RegionConfigManager.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/mutators/RegionConfigManagerTest.java
geode-management/src/main/java/org/apache/geode/cache/configuration/RegionConfig.java

GEODE-6612: use java Objects for comparison instead of guava

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/extension/mock/MockExtensionCommands.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/MemberMBeanBridge.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/CliAroundInterceptor.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/remote/CommandExecutor.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/remote/OnlineCommandProcessor.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/result/model/ResultModel.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/shell/GfshExecutionStrategy.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/shell/JmxOperationInvoker.java
geode-core/src/main/java/org/apache/geode/management/internal/web/http/support/HttpRequester.java
geode-core/src/main/java/org/apache/geode/management/internal/web/shell/HttpOperationInvoker.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/remote/OnlineCommandProcessorTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/result/model/ResultModelTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/shell/GfshExecutionStrategyTest.java
geode-lucene/src/distributedTest/java/org/apache/geode/cache/lucene/LuceneCommandsSecurityDUnitTest.java
geode-web/src/integrationTest/java/org/apache/geode/management/internal/web/controllers/ShellCommandsControllerProcessCommandTest.java
geode-web/src/main/java/org/apache/geode/management/internal/web/controllers/ShellCommandsController.java

GEODE-5971: have command pipeline send ResultModel json across the wire

---

dev-tools/release/README.md
dev-tools/release/prepare_rc.sh
dev-tools/release/print_rc_email.sh

Adding a script to build a release candidate.
Adding another script to create an email template.
Publishing the release candidate and sending the email are still manual
steps.

Adding a couple of scripts to automate release candidates

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/BucketCreationCrashCompletesRegressionTest.java

Inline methods in test to improve readability.
Please review: @demery-pivotal @aaronlindsey @mhansonp

GEODE-6667: Await 2 owners of bucket in testCrashWhileCreatingABucket

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreateDefinedIndexesCommandDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DescribeMembersCommandDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ListJndiBindingCommandDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ListMembersCommandDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/LocateEntryDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/GetCommandIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/PutCommandIntegrationTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/remote/CommandExecutor.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/result/CommandResult.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateDefinedIndexesCommandTest.java

GEODE-5971: remove unnecessary @VisibleToTest methods

---

geode-core/src/main/java/org/apache/geode/cache/client/ClientCacheFactory.java
geode-core/src/main/java/org/apache/geode/cache/client/Pool.java
geode-core/src/main/java/org/apache/geode/cache/client/PoolFactory.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/AbstractOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/AuthenticateUserOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/DataSerializerRecoveryListener.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ExecutablePool.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ExplicitConnectionSourceImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/InstantiatorRecoveryListener.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/Op.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/OpExecutorImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/PoolImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/PutOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/PoolFactoryImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/PoolManagerImpl.java
geode-management/src/main/java/org/apache/geode/cache/configuration/PoolType.java

 GEODE-6580: Cleanup static analyzer warnings.

---

geode-core/src/main/java/org/apache/geode/internal/InternalDataSerializer.java
geode-core/src/test/java/org/apache/geode/DataSerializerTest.java

GEODE-6692: canonicalize deserialization of empty string

---

geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/AbstractRegionJUnitTest.java

GEODE-6704: optimize getAllGatewaySenderIds

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientRegistrationEventQueueManager.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientRegistrationEventQueueManagerTest.java

GEODE-6708: Ensuring single drainer and preventing NPE

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/AbstractOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/AuthenticateUserOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ClientSideHandshakeImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/PutOp.java
geode-core/src/main/java/org/apache/geode/cache/wan/EventSequenceID.java
geode-core/src/main/java/org/apache/geode/internal/ByteArrayDataInput.java
geode-core/src/main/java/org/apache/geode/internal/cache/EntryEventImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/EventID.java
geode-core/src/main/java/org/apache/geode/internal/cache/FilterRoutingInfo.java
geode-core/src/main/java/org/apache/geode/internal/cache/ha/ThreadIdentifier.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/AuthIds.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxy.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientUpdater.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientProxyMembershipID.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientUpdateMessageImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/EncryptorImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java
geode-core/src/main/java/org/apache/geode/internal/offheap/DataType.java

ByteArrayInputStream+DataInputStream with ByteArrayDataInput

---

geode-core/src/integrationTest/java/org/apache/geode/management/bean/stats/DistributedSystemStatsJUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java

GEODE-6472 Double increment gets for partitioned region

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/ClearOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ContainsKeyOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/DestroyOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/DestroyRegionOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ExecuteRegionFunctionNoAckOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ExecuteRegionFunctionOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ExecuteRegionFunctionSingleHopOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/GetAllOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/GetClientPRMetaDataOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/GetClientPartitionAttributesOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/GetEntryOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/GetOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/InvalidateOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/KeySetOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/PutAllOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/PutOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/RegisterInterestListOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/RegisterInterestOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/RemoveAllOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/SizeOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/UnregisterInterestListOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/UnregisterInterestOp.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientInterestMessageImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientTombstoneMessage.java
geode-wan/src/main/java/org/apache/geode/cache/client/internal/GatewaySenderBatchOp.java

GEODE-6690: now uses the caching addStringPart for region name parts

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/MemberManagementServiceDunitTest.java
geode-core/src/test/java/org/apache/geode/management/internal/api/ClusterManagementResultTest.java
geode-junit/src/main/java/org/apache/geode/test/junit/assertions/ClusterManagementResultAssert.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementResult.java
geode-management/src/test/java/org/apache/geode/cache/configuration/CacheElementJsonMappingTest.java
geode-web-management/src/distributedTest/java/org/apache/geode/management/client/MemberManagementServiceDUnitTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/MemberManagementController.java

GEODE-6728: remove extra getResult() method

---

ci/pipelines/examples/jinja.template.yml
ci/pipelines/geode-build/jinja.template.yml
ci/pipelines/pull-request/jinja.template.yml

GEODE-6739: add macros for test and PR jobs

---

geode-core/src/integrationTest/java/org/apache/geode/pdx/JSONFormatterBasicJUnitTest.java
geode-core/src/main/java/org/apache/geode/pdx/JSONFormatter.java
geode-core/src/main/java/org/apache/geode/pdx/internal/json/PdxInstanceHelper.java
geode-core/src/main/java/org/apache/geode/pdx/internal/json/PdxInstanceSortedHelper.java

GEODE-6327: Ability to specify identity fields on JSON documents

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/json/QueryResultFormatter.java

GEODE-6743: Use UncheckedIOException instead of RuntimeIOException

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientRegistrationEventQueueManager.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifierTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientRegistrationEventQueueManagerTest.java

GEODE-6741: Copy off-heap to heap for client registration queue

---

geode-core/src/main/java/org/apache/geode/internal/ByteArrayDataInput.java
geode-core/src/test/java/org/apache/geode/internal/ByteArrayDataInputTest.java

ByteArrayDataInput.readUTF is now optimized for ASCII strings.
added unit tests for readUTF.

GEODE-6676: optimize readUTF for ASCII

---

geode-junit/src/main/java/org/apache/geode/util/test/TestUtil.java

Restore deprecation and delegation of TestUtil to ResourceUtils after reverting the deletion of TestUtil.

GEODE-6731: Deprecate TestUtil and delegate to ResourceUtils

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ListIndexManagementDUnitTest.java
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/test/java/org/apache/geode/cache/configuration/CacheConfigTest.java
geode-core/src/test/java/org/apache/geode/cache/configuration/RegionConfigTest.java
geode-management/src/main/java/org/apache/geode/cache/configuration/RegionConfig.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementResult.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementService.java
geode-management/src/main/java/org/apache/geode/management/configuration/RuntimeIndex.java
geode-management/src/main/java/org/apache/geode/management/configuration/RuntimeRegionConfig.java
geode-management/src/main/java/org/apache/geode/management/internal/ClientClusterManagementService.java
geode-management/src/test/java/org/apache/geode/cache/configuration/CacheElementJsonMappingTest.java
geode-web-management/src/distributedTest/java/org/apache/geode/management/client/MemberManagementServiceDUnitTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/MemberManagementController.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RegionManagementController.java

GEODE-6744: list index rest api

---

ci/pipelines/geode-build/jinja.template.yml
ci/pipelines/meta/deploy_meta.sh

* PublishArtifacts is conditional
* sort input parameters to meta fly

GEODE-6752: Move updateXYZ jobs after publication of SNAPSHOT artifacts

---

geode-docs/tools_modules/gfsh/configuring_gfsh.html.md.erb

GEODE-6653 Fix formatting of results

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/RegionListenerJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/ServerBuilderIntegrationTest.java

GEODE-6764: Fix tests for Windows

---

ci/pipelines/meta/jinja.template.yml
ci/pipelines/reaper/deploy_reaper_pipeline.sh
ci/pipelines/reaper/jinja.template.yml

* Refactor reaper pipeline to work like other pipelines.
* Add job that checks benchmarks clusters and destroys ones
older than a week.

[GEODE-6766] Add benchmark job to reaper pipeline.

---

extensions/geode-modules/src/main/java/org/apache/geode/modules/util/RegionHelper.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/CacheXml66DUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/ReconnectDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/client/ClientCacheFactoryJUnitTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/mgr/GMSMembershipManager.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheXmlGenerator.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/XmlGenerator.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/ExportConfigFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/domain/XmlEntity.java
geode-lucene/src/integrationTest/java/org/apache/geode/cache/lucene/internal/xml/LuceneIndexXmlGeneratorIntegrationJUnitTest.java
geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeMultipleReceiversDefinedInClusterConfiguration.java

GEODE-6588: Cleanup static analyzer warnings.

---

geode-core/src/integrationTest/java/org/apache/geode/pdx/JSONFormatterBasicJUnitTest.java
geode-core/src/main/java/org/apache/geode/pdx/JSONFormatter.java

GEODE-6327: Add method overload to avoid breaking API in JSONFormatter

---

geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/MemberConfigManager.java
geode-management/src/main/java/org/apache/geode/management/configuration/MemberConfig.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/MemberManagementServiceRestIntegrationTest.java

Adds groups to REST API v2 list members

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/result/CommandResult.java
geode-dunit/src/main/java/org/apache/geode/management/internal/cli/commands/QueryCommandIntegrationTestBase.java

GEODE-6775: Remove unnecessary blank lines from gfsh output

---

geode-core/src/main/java/org/apache/geode/cache/execute/Function.java

[n/a] Have you written or updated unit tests to verify your changes?
[n/a] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

GEODE-6701: Remove reference to deprecated class

---

geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/MemberConfigManager.java

Geode 6745 add groups to list members with rename

---

ci/images/google-windows-geode-builder/windows-packer.json

Update windows source image family.

---

ci/images/alpine-tools/Dockerfile

Pin packer version to 1.3.5.

---

geode-junit/src/main/java/org/apache/geode/codeAnalysis/AnalyzeSerializablesJUnitTestBase.java

trial: see if the test will pass while running on jdk11

---

ci/images/alpine-tools/Dockerfile
ci/images/google-windows-geode-builder/build_image.sh

Keep newest packer but install specific version as well.

---

ci/images/google-windows-geode-builder/windows-packer.json

Remove hopefully now spurious line.

---

ci/images/google-windows-geode-builder/windows-packer.json

Removing lines we hopefully don't need anymore.

---

geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/MemberConfigManager.java
geode-management/src/main/java/org/apache/geode/management/configuration/MemberConfig.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/MemberManagementServiceRestIntegrationTest.java

GEODE-6745 Adds properties to REST api v2 list members

---

geode-core/src/main/java/org/apache/geode/internal/datasource/DataSourceCreateException.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt

GEODE-6790: Refactor DataSourceCreateException to correctly capture cause

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/domain/MemberInformation.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/MemberConfigManager.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/mutators/MemberConfigManagerTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/MemberManagementServiceRestIntegrationTest.java

Geode 6745 adds test cover to member config manager

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/OplogRVVJUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/AbstractDiskRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/Oplog.java
geode-core/src/main/java/org/apache/geode/internal/cache/persistence/DiskRecoveryStore.java

GEODE-6754: Cleanup LocalRegion warnings, typos, and bug refs

---

geode-core/src/test/java/org/apache/geode/internal/net/NioPlainEngineTest.java

Bruce did the heavy lifting. I'm turning the test back on.

GEODE-6733 un-ignore test now that static has been removed

---

geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/CreateDataSourceCommandDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheXmlParser.java
geode-core/src/main/java/org/apache/geode/internal/datasource/DataSourceFactory.java
geode-core/src/main/java/org/apache/geode/internal/jndi/JNDIInvoker.java

-Modified Hikari configuration to omit jdbc-driver-class.

GEODE-6669 Changed CreateDataSourceCommand to register driver earlier

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ListMembersCommandDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListMembersCommand.java

reference: https://issues.apache.org/jira/browse/GEODE-6815

GEODE-6815 Adds member count to gfsh list members

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/PooledConnection.java

GEODE-6794 Fix calling notifyAll always while returning connection

---

geode-core/src/distributedTest/java/org/apache/geode/internal/logging/LoggingWithReconnectDistributedTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/logging/StartupConfigurationLoggingIntegrationTest.java
geode-core/src/main/java/org/apache/geode/internal/logging/LoggingSession.java

GEODE-2600 Inconsistent spacing of headers in Startup Configuration log

---

geode-core/src/main/java/org/apache/geode/SystemFailure.java
geode-core/src/main/java/org/apache/geode/distributed/DistributedSystem.java
geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java
geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/offheap/DisconnectingOutOfOffHeapMemoryListener.java
geode-core/src/main/java/org/apache/geode/internal/util/concurrent/FutureResult.java
geode-core/src/test/java/org/apache/geode/internal/offheap/DisconnectingOutOfOffHeapMemoryListenerJUnitTest.java

GEODE-6588: Cleanup static analyzer warnings and generics

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ClearTXLockingDUnitTest.java

GEODE-6820: Initialize count down latches in setup method.

---

geode-core/src/distributedTest/java/org/apache/geode/management/PartitionedRegionStatsTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java

GEODE-6472 Fix double increment getsRate for partitioned region

---

ci/pipelines/shared/jinja.variables.yml
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientReconnectDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/query/functional/IndexUsageInNestedQueryJUnitTest.java
geode-core/src/main/java/org/apache/geode/admin/internal/DistributedSystemHealthMonitor.java
geode-core/src/main/java/org/apache/geode/admin/internal/GemFireHealthEvaluator.java
geode-core/src/main/java/org/apache/geode/admin/internal/LogCollator.java
geode-core/src/main/java/org/apache/geode/admin/internal/SystemMemberImpl.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/MethodDispatch.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/IndexManager.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/PartitionedIndex.java
geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/CqPerfUsingPoolDUnitTest.java
geode-cq/src/distributedTest/java/org/apache/geode/security/ClientPostAuthorizationDUnitTest.java
geode-cq/src/distributedTest/java/org/apache/geode/security/FilterPostAuthorization.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/AckReaderThreadJUnitTest.java

Removed most raw arraylists in the repo

GEODE-6588 removed raw arraylists, assigning them each a type

---

geode-core/src/distributedTest/java/org/apache/geode/cache30/CacheStatisticsPartitionedRegionDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/ShowMetricsCommandIntegrationTest.java
geode-core/src/main/java/org/apache/geode/cache/Region.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/cache/internal/JUnit4CacheTestCase.java

- [ Yes ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?
- [ Yes ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?
- [ Yes ] Is your initial contribution a single, squashed commit?
- [ Yes ] Does `gradlew build` run cleanly?
- [ Yes ] Have you written or updated unit tests to verify your changes?
- [ NA ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? …

GEODE-2685: getStatistics supported operation for PartitionedRegion

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsDUnitTest.java

no behavior change, only additional tests

GEODE-6749 additional tests for duplicate disk store detection logic

---

geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/DeregisterDriverCommandDUnitTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/ListDriversCommandDUnitTest.java
geode-connectors/src/distributedTest/java/org/apache/geode/connectors/jdbc/internal/cli/RegisterDriverCommandDUnitTest.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DeregisterDriverCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DeregisterDriverFunction.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/ListDriversCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/ListDriversFunction.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/RegisterDriverCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/RegisterDriverFunction.java
geode-connectors/src/main/resources/META-INF/services/org.springframework.shell.core.CommandMarker
geode-connectors/src/main/resources/org/apache/geode/internal/sanctioned-geode-connectors-serializables.txt
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/DeregisterDriverCommandTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/DeregisterDriverFunctionTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/ListDriversCommandTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/ListDriversFunctionTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/RegisterDriverCommandTest.java
geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/RegisterDriverFunctionTest.java
geode-core/src/main/java/org/apache/geode/internal/util/DriverJarUtil.java
geode-core/src/test/java/org/apache/geode/internal/util/DriverJarUtilTest.java

GEODE-6773 Adding register driver, deregister driver and list drivers gfsh commands

---

geode-core/src/main/java/org/apache/geode/internal/util/concurrent/StoppableCountDownLatch.java
geode-core/src/test/java/org/apache/geode/internal/util/concurrent/StoppableCountDownLatchTest.java

GEODE-6785: Retry time - system property read optimized

---

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DeregisterDriverCommand.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/RegisterDriverCommand.java

Removed references to jar files
[skip ci]

GEODE-6773

---

extensions/geode-modules-assembly/build.gradle

GEODE-6797: Use better packaging techniques to avoid missing dependency

---

geode-core/src/main/java/org/apache/geode/internal/cache/DistributedCacheOperation.java

GEODE-6828: check synchronize only for debug/trace

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/ha/HARegionQueueIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/ha/HARegionQueueJUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/ha/HARegionQueue.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientRegistrationEventQueueManager.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/HAEventWrapper.java

GEODE-6845: Consistent logging when incrementing putInProgress

---

geode-core/src/main/java/org/apache/geode/cache/AttributesFactory.java
geode-core/src/test/java/org/apache/geode/cache/AttributesFactoryJUnitTest.java

Co-authored-by: Peter Tran <ptran@gmail.com>

GEODE-6829: Fixes synchronization in AttributesFactory

---

geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/FunctionStats.java

GEODE-6837: optimize read system property "statsDisabled"

---

ci/bin/concourse_job_performance.py

Revert "GEODE-6852: updated script due to SSEClient change"

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/GatewayReceiverManagementDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java

GEODE-6811: fix bug in list cache element method

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RegionManagementDunitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RegionManagementRestSecurityDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/ConfigurationManager.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/RegionConfigManager.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/MemberValidator.java
geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/mutators/RegionConfigManagerTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/MemberValidatorTest.java

 GEODE-6306: add capability to check cache element compatibility

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/DiskStoreImplIntegrationTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/DiskDirectoryStats.java
geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java
geode-core/src/main/java/org/apache/geode/management/DiskStoreMXBean.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/DiskStoreMBean.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/DiskStoreMBeanBridge.java

GEODE-5222: DiskStore usage percentage in JMX

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ContainsKey.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ContainsKey66.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Destroy.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Destroy65.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Get70.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/GetAll.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/GetAll651.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/GetAll70.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/GetAllWithCallback.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Invalidate.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Put.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Put61.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Put65.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/RegisterInterest.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/RegisterInterest61.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Request.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/UnregisterInterest.java
geode-core/src/main/java/org/apache/geode/internal/security/IntegratedSecurityService.java
geode-core/src/main/java/org/apache/geode/internal/security/LegacySecurityService.java
geode-core/src/main/java/org/apache/geode/internal/security/SecurityService.java

GEODE-6691: SecurityService.authorize optimized

---

geode-docs/reference/statistics_list.html.md.erb

[n/a] Have you written or updated unit tests to verify your changes?
[n/a] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

GEODE-6654: Fix statistics documentation issues

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImpl.java

The log message is the same as the log message a few lines down which results in extra spam in the logs.

GEODE-6810: Removed Superfluous Log Message

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/FunctionRetryTestBase.java
geode-core/src/main/java/org/apache/geode/cache/execute/Execution.java

Remove duplicate switch section

GEODE-6677: Fix compile errors

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/AbstractOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/AbstractOpWithTimeout.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ConnectionConnector.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ConnectionFactory.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ConnectionFactoryImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ConnectionImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ExecuteFunctionOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ExecuteRegionFunctionOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ExecuteRegionFunctionSingleHopOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ServerRegionProxy.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/AbstractExecution.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/ServerFunctionExecutor.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/ServerRegionFunctionExecutor.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction66.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunction66.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunctionSingleHop.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/AbstractOpWithTimeoutTest.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/ConnectionConnectorTest.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/ExecuteFunctionOpRetryTest.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/ExecuteRegionFunctionOpRetryTest.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/ExecuteRegionFunctionSingleHopOpRetryTest.java

Commit f758494 is a cleanup commit. The changes are in 
1d275b4. I suggest you review them separately.

 GEODE-6857: Moves function timeout to function operations.

---

geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/RegionConfigManager.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/mutators/RegionConfigManagerTest.java
geode-web-management/src/distributedTest/java/org/apache/geode/management/internal/rest/RegionManagementSecurityRestDUnitTest.java

GEODE-6892: Default entryCount for newly created region to 0

---

geode-core/src/test/java/org/apache/geode/cache/configuration/RegionConfigTest.java
geode-management/src/main/java/org/apache/geode/cache/configuration/PdxType.java
geode-management/src/main/java/org/apache/geode/management/api/RestfulEndpoint.java
geode-management/src/main/java/org/apache/geode/management/internal/ClientClusterManagementService.java
geode-management/src/test/java/org/apache/geode/cache/configuration/GatewayReceiverConfigTest.java
geode-management/src/test/java/org/apache/geode/cache/configuration/PdxTypeTest.java
geode-management/src/test/java/org/apache/geode/management/configuration/MemberConfigTest.java
geode-web-management/src/distributedTest/java/org/apache/geode/management/client/ConfigurePDXDUnitTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/PdxManagementTest.java

GEODE-6811: fix the rest endpoint URI

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ha/HAGIIDUnitTest.java

* Immitating the fix for GEODE-6051
* Compared successfull runs of the test on IntelliJ and comapared the logs to the failed tests and all the stacktraces match.

GEODE-6888: Adding ignored exception for ConnectException

---

geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandIntegrationTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java

GEODE-6870: Solution for creation of non-persistent overflow region

---

geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/InitialImageOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/DistributedRegionJUnitTest.java

Co-authored-by: Eric Shu <eshu@pivotal.io>

GEODE-6899: retried client should set last try's version tag if found

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/DiskRegionJUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java

GEODE-2863: Discard all new tasks, after close request received

---

geode-assembly/src/acceptanceTest/resources/ManagementClientCreateRegion.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/client/CreateRegionWithDiskstoreAndSecurityDUnitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ClientClusterManagementSSLTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ClientClusterManagementServiceDunitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ClusterManagementServiceOnServerTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/GatewayReceiverManagementDUnitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ManagementRequestLoggingDUnitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RegionManagementDunitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ServerRestartTest.java
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-core/src/distributedTest/java/org/apache/geode/management/internal/api/RegionAPIDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-management-serializables.txt
geode-core/src/test/java/org/apache/geode/management/internal/api/ClusterManagementResultTest.java
geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java
geode-junit/src/main/java/org/apache/geode/test/junit/assertions/SimpleClusterManagementResultAssert.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementResult.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementService.java
geode-management/src/main/java/org/apache/geode/management/api/RestfulEndpoint.java
geode-management/src/main/java/org/apache/geode/management/api/SimpleClusterManagementResult.java
geode-management/src/main/java/org/apache/geode/management/internal/ClientClusterManagementService.java
geode-web-management/src/distributedTest/java/org/apache/geode/management/client/ClientClusterManagementServiceDUnitTest.java
geode-web-management/src/distributedTest/java/org/apache/geode/management/client/ConfigurePDXDUnitTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/GatewayManagementIntegrationTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/PdxManagementTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementIntegrationTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/GatewayManagementController.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/PdxManagementController.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RegionManagementController.java

Simple result

---

geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedAckRegionCCEDUnitTest.java
geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/AddCacheServerProfileMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/CacheDistributionAdvisor.java
geode-core/src/main/java/org/apache/geode/internal/cache/CacheFactoryStatics.java
geode-core/src/main/java/org/apache/geode/internal/cache/ColocationHelper.java
geode-core/src/main/java/org/apache/geode/internal/cache/CreateRegionProcessor.java
geode-core/src/main/java/org/apache/geode/internal/cache/DestroyRegionOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistributedCacheOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/FilterProfile.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/InitialImageOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionHelper.java
geode-core/src/main/java/org/apache/geode/internal/cache/RemoveCacheServerProfileMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/SearchLoadAndWriteProcessor.java
geode-core/src/main/java/org/apache/geode/internal/cache/StateFlushOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXCommitMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/ha/QueueRemovalMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/persistence/MembershipFlushRequest.java
geode-core/src/main/java/org/apache/geode/internal/cache/persistence/MembershipViewRequest.java
geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PersistentStateQueryMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PrepareNewPersistentMemberMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/persistence/RemovePersistentMemberMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueue.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelQueueRemovalMessage.java
geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionTest.java

* Refactor static ints to enum type.
* Cleanup method names.
* Replace null case with default value.

GEODE-6761: Reduce garbage in LocalRegion.initializationThread

---

geode-core/src/distributedTest/java/org/apache/geode/pdx/ClientsWithVersioningRetryDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java

added retry dunit tests for all the c/s operations.

GEODE-6908: retried REMOVE should not create new version tag.

---

geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateIndexCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/realizers/ConfigurationRealizer.java
geode-core/src/test/java/org/apache/geode/management/internal/api/ClusterManagementResultTest.java
geode-junit/src/main/java/org/apache/geode/test/junit/assertions/ClusterManagementResultAssert.java
geode-management/src/main/java/org/apache/geode/cache/configuration/GatewayReceiverConfig.java
geode-management/src/main/java/org/apache/geode/cache/configuration/PdxType.java
geode-management/src/main/java/org/apache/geode/cache/configuration/RegionConfig.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementResult.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementService.java
geode-management/src/main/java/org/apache/geode/management/api/ConfigurationResult.java
geode-management/src/main/java/org/apache/geode/management/api/CorrespondWith.java
geode-management/src/main/java/org/apache/geode/management/configuration/MemberConfig.java
geode-management/src/main/java/org/apache/geode/management/internal/ClientClusterManagementService.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/GatewayManagementIntegrationTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RegionManagementController.java

* rename RespondsWith to CorrespondsWith
* rename Response to ConfgiurationResult (as opposed to RealizationResult)
* further type ConfigurationRealizer

GEODE-6861: class renaming

---

geode-core/src/main/java/org/apache/geode/internal/cache/tx/RemotePutMessage.java
geode-core/src/test/java/org/apache/geode/internal/cache/tx/RemotePutMessageTest.java

GEODE-6929: Modified RemotePutMessage operateOnRegion to return after sending the exception reply

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt

Update Micrometer to 1.2.0

---

geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheCreation.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/ClientCacheCreation.java
geode-core/src/test/java/org/apache/geode/internal/cache/xmlcache/CacheCreationJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/xmlcache/CacheCreationTest.java

```
commit 49718f7e1eeb5de299fbde2d860f22d9ec903a1d (HEAD -> GEODE-6918-cleanup-classes-03, kirklund-fork/GEODE-6918-cleanup-classes-03)
Date:   Wed Jul 3 12:19:00 2019 -0700
GEODE-6918: Rename CacheCreationTest
Rename CacheCreationJUnitTest as CacheCreationTest
```
```
commit e96b27ccbb52cda0c708159dea707948a0361812
Date:   Wed Jul 3 12:17:50 2019 -0700
GEODE-6918: Cleanup CacheCreation and CacheCreationJUnitTest
```

GEODE-6918: Cleanup CacheCreation and unit test

---

geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/PersistentOplogSet.java
geode-core/src/test/java/org/apache/geode/internal/cache/PersistentOplogSetTest.java

GEODE-6918: Restore use of System.out and max in PersistentOplogSet

---

geode-docs/developing/query_select/aggregates.html.md.erb

GEODE-6911: Fix SUM short description in docs

---

geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/TestHistoryLogger.java

GEODE-6938: Correctly log dunit test history

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/GatewayReceiverManagementDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/GatewayReceiverMBeanBridge.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/realizers/GatewayReceiverRealizer.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-management-serializables.txt
geode-core/src/test/java/org/apache/geode/management/internal/beans/GatewayReceiverMBeanBridgeTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/realizers/GatewayReceiverRealizerTest.java
geode-management/src/main/java/org/apache/geode/management/runtime/GatewayReceiverInfo.java

* add sender count and sender list

GEODE-6811: view the runtime info of gateway receivers

---

geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PRTombstoneMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java
geode-core/src/test/java/org/apache/geode/internal/cache/BucketRegionTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifierTest.java

GEODE-6762: First part - check is there proxy to notify

---

geode-management/src/test/script/list-management-url.sh

add script to list the management rest endpoints.

---

geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySenderEventProcessor.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/GatewaySenderMBean.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderAlertThresholdDUnitTest.java

GEODE-6933: Fix Gateway Sender alert-threshold

---

ci/images/meta-mini/Dockerfile
ci/pipelines/geode-build/jinja.template.yml
ci/pipelines/shared/jinja.variables.yml

Co-authored-by: Bala Kaza Venkata <bkazavenkata@pivotal.io>

Parameterize initial version to reduce possible errors.

---

geode-core/src/main/java/org/apache/geode/management/cli/GfshCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CompactDiskStoreCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateDiskStoreCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsUtils.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsUtilsTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/GfshCommandJUnitTest.java

- due to different ways of determining existence of disk stores
- added more protection against NPEs

GEODE-6779: fix issues with DUnit failures

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/ServerRegionProxy.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/ServerRegionFunctionExecutor.java

This PR is in addition to the previous checkin made with GEODE-6798:
Commit 0b2f2c248c38b54c59df638315b37ad9ffc604af in geode's branch refs/heads/develop from agingade
The previous checkin introduced performance degradation, observed due to garbage collection. Before the refactoring changes the ExecuteRegionFunctionOpImpl instance was created as needed; in the refactoring code it was created all the time, resulting in excess garbage. This PR addresses the issue by using Supplier instance, that creates the ExecuteRegionFunctionOpImpl as and when needed.
- [Y] Is your initial contribution a …

GEODE-6798 Refactor client function execution logic

---

ci/images/google-windows-geode-builder/build_image.sh

Add flags to allow for local building.

---

ci/pipelines/images/jinja.template.yml

Bump timeout on windows builder job to 3h to get it to green.

---

geode-docs/tools_modules/gfsh/command-pages/set.html.md.erb
geode-docs/tools_modules/gfsh/getting_started_gfsh.html.md.erb

GEODE-7011: Remove docs mention of APP_COLLECTION_LIMIT

---

geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/GfshParserAutoCompletionTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/help/HelperIntegrationTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/CommandManager.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/GfshParser.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/GfshHelpCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/GfshHintCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/help/Helper.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/help/HelperUnitTest.java

Geode 7013 command line help broken

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/fixed/FixedPartitioningWithTransactionDistributedTest.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ServerRegionProxy.java

* Fixes test to force and wait for PR metadata to update.
* Run each test via function execution by id and object.

GEODE-7006: Fixes function execution by id with transactions.

---

geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ConcurrentParallelGatewaySenderEventProcessor.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/ConcurrentSerialGatewaySenderEventProcessor.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/GatewaySenderMBeanBridge.java
geode-wan/src/distributedTest/java/org/apache/geode/management/WANManagementDUnitTest.java

GEODE-6954 Update dispatcher in JMX after receiver restart

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/PersistentPartitionedRegionDistributedTest.java

GEODE-7029: More robust INetAddress retrieval for revokation

---

geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/PartitionedRegionCompactRangeIndexDUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/CompactRangeIndex.java
geode-core/src/test/java/org/apache/geode/cache/query/internal/index/CompactRangeIndexTest.java

GEODE-6998: Fix for NPE at index update due to GII

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
build.gradle
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-core/README.md
geode-core/build.gradle

* Generate correct JMH shadow jar for standalone execution.
* Fix plugin dependencies.
* Add profiler command line property.
* Adds README

GEODE-6958: Improve JMH integration

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/PersistentPartitionedRegionDistributedTest.java

GEODE-7030: Handling expected exception when scheduling async write

---

geode-book/master_middleman/source/subnavs/geode-subnav.erb

GEODE-7033: User Guide - Balance lists in left-hand nav panel

---

ci/images/google-geode-builder/scripts/setup.sh

Remove unattended-upgrades and autoremove unnecessary stuff.

---

geode-core/src/main/java/org/apache/geode/internal/Version.java

- [] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

Fixing new version and ordinal

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PersistentRegionRecoveryDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/control/RebalanceOperationDistributedTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/PersistentPartitionedRegionDistributedTest.java

GEODE-7015: Resetting static state after tests

---

ci/pipelines/geode-build/jinja.template.yml

GEODE-7014: add Benchmark task to main CI tab

---

geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java

GEODE-7012: Failure in upgrade testing - upgrading 1.9 to 1.10

---

geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/PersistentRegionCompactRangeIndexDUnitTest.java
geode-core/src/distributedTest/resources/org/apache/geode/cache/query/dunit/PartitionedPersistentRegionWithIndex.xml
geode-core/src/distributedTest/resources/org/apache/geode/cache/query/dunit/ReplicatePersistentRegionWithIndex.xml

GEODE-6998: Add index test for gii tombstone/values update to tombstone 

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/control/RebalanceOperationDistributedTest.java

GEODE-7015: Fixing redundant copies in test

---

ci/pipelines/geode-build/jinja.template.yml

* Move benchmark to main group
* Make it gating
* Pass geode-ci resource between jobs
Signed-off-by: Robert Houghton <rhoughton@pivotal.io>

GEODE-7014: Move Benchmark to CI Main

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/InvalidateOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ServerRegionProxy.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/InvalidateOpJUnitTest.java
geode-docs/developing/partitioned_regions/how_pr_single_hop_works.html.md.erb

GEODE-6748: First part of solution

---

geode-wan/src/main/java/org/apache/geode/cache/client/internal/GatewaySenderBatchOp.java

GEODE-7048: Remove dead code in GatewaySenderBatchOp

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/security/JmxMultipleConnectionsTest.java
geode-core/src/main/java/org/apache/geode/internal/security/shiro/JMXShiroAuthenticator.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/MBeanServerConnectionRule.java

GEODE-6717: Logging out when all JMX connections are closed

---

geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/RestartOfMemberDistributedTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java

GEODE-7036: Fix for NPE caused by ex-coordinator joining quorum

---

ci/pipelines/shared/jinja.variables.yml

Update the branch used in the benchmark to be the release branch.
Continue to compare this to the develop/highwater tag since this is a
mark of the previous best stable performance.

GEODE-7067: Update Benchmarked branch

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/OfflineSnapshotJUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java

Co-authored-by: Donal Evans doevans@pivotal.io

GEODE-7080: Do not add removed entry into offline export file.

---

geode-core/src/distributedTest/java/org/apache/geode/distributed/DistributedLockServiceDUnitTest.java

- Use Awaitility instead of Thread.sleep to make sure the asynchronous
task is alive before continuing with the test.

GEODE-7062: Fix Race Condition in DUnit Test

---

geode-core/src/distributedTest/java/org/apache/geode/cache30/ReconnectDUnitTest.java

GEODE-7092: increase flaky test MEMBER_TIMEOUT

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/ha/HARegionQueueIntegrationTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/AcceptorImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientRegistrationEventQueueManager.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientUpdateMessageImpl.java
geode-core/src/test/java/org/apache/geode/internal/cache/BucketRegionTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/CacheServerImplTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionPartialMockTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/AcceptorImplTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifierTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientRegistrationEventQueueManagerTest.java

GEODE-7089: Each client registration thread uses its own queue

---

geode-pulse/src/main/webapp/WEB-INF/spring-security.xml

GEODE-7104: Ensure compatibility with Spring 5.x

---

geode-core/src/distributedTest/java/org/apache/geode/pdx/internal/TypeRegistrationDistributedTest.java
geode-core/src/integrationTest/java/org/apache/geode/pdx/PdxInstanceJUnitTest.java
geode-core/src/main/java/org/apache/geode/pdx/internal/PeerTypeRegistration.java
geode-core/src/main/java/org/apache/geode/pdx/internal/TypeRegistrationStatistics.java
geode-core/src/test/java/org/apache/geode/internal/cache/GemFireCacheImplTest.java

 GEODE-7083: Adds statistics to PeerTypeRegistration

---

geode-docs/getting_started/querying_quick_reference.html.md.erb

- Fixed count examples.
- Added examples for the different aggregate functions.

GEODE-6907: Add Aggregate Function Examples

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/RegionEntriesGaugeTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/RegionPerfStats.java
geode-core/src/test/java/org/apache/geode/internal/cache/RegionPerfStatsTest.java

Draft pull request to see test results.

GEODE-7140: Rename the meters for entries

---

geode-core/src/main/java/org/apache/geode/internal/metrics/CacheMeterRegistryFactory.java
geode-core/src/test/java/org/apache/geode/internal/metrics/CacheMeterRegistryFactoryBindersTest.java
geode-core/src/test/java/org/apache/geode/internal/metrics/CacheMeterRegistryFactoryTest.java

Creating a draft PR to test the code.

GEODE-7139: Cleanup the common tags on the meters

---

geode-management/build.gradle
geode-management/src/main/java/org/apache/geode/management/api/RestfulEndpoint.java
geode-management/src/main/java/org/apache/geode/management/configuration/AbstractConfiguration.java
geode-management/src/test/resources/expected-pom.xml

GEODE-6941: clean out xml traces in geode-management

---

geode-core/src/main/java/org/apache/geode/internal/Version.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CommandInitializer.java

This is a PR against release/1.9.1 to remove 1.9.1 from Version.

Remove 1.9.1 from Version

---

geode-core/src/distributedTest/java/org/apache/geode/internal/jta/dunit/TransactionTimeOutDUnitTest.java

GEODE-7114: fix flaky tests by using GeodeAwaitility.

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentPartitionedRegionWithRedundancyDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/BucketAdvisor.java

GEODE-7039: Improve read performance during server recovery

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ListRegionManagementDunitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreateIndexCommandDUnitTest.java
geode-core/src/main/java/org/apache/geode/distributed/ConfigurationPersistenceService.java
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateIndexCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/CommonConfigurationValidator.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/MemberValidator.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-management-serializables.txt
geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateIndexCommandTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/CommonConfigurationValidatorTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/MemberValidatorTest.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementService.java
geode-management/src/main/java/org/apache/geode/management/configuration/AbstractConfiguration.java
geode-management/src/main/java/org/apache/geode/management/configuration/GatewayReceiver.java
geode-management/src/main/java/org/apache/geode/management/configuration/Pdx.java
geode-management/src/test/java/org/apache/geode/cache/configuration/AbstractConfigurationTest.java
geode-management/src/test/java/org/apache/geode/cache/configuration/ConfigurationJsonMappingTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/MemberManagementController.java

GEODE-7136: remove "groups" in management configuration

---

geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifierTest.java

GEODE-7158: Adding singleton cleanup before tests

---

geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb

GEODE-6556: gfsh 'create region' expiration params explanation

---

geode-docs/managing/heap_use/heap_management.html.md.erb

GEODE-7191: Duplicated info about JVM GC parameters

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/AlterAsyncEventQueueCommandDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/AlterAsyncEventQueueCommand.java

Revert "GEODE-7179: Add option to AlterAsyncEventQueue gfsh command for pause-event processing"

---

geode-lucene/geode-lucene-test/src/main/java/org/apache/geode/cache/lucene/test/GrandSubCustomer.java
geode-lucene/geode-lucene-test/src/main/java/org/apache/geode/cache/lucene/test/SubCustomer.java
geode-lucene/src/integrationTest/java/org/apache/geode/cache/lucene/NestedObjectSeralizerIntegrationTest.java
geode-lucene/src/integrationTest/java/org/apache/geode/cache/lucene/NestedObjectSerializerOnGrandSubclassIntegrationTest.java
geode-lucene/src/integrationTest/java/org/apache/geode/cache/lucene/NestedObjectSerializerOnSubclassIntegrationTest.java
geode-lucene/src/integrationTest/java/org/apache/geode/cache/lucene/ToplevelObjectSerializerOnGrandSubclassIntegrationTest.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/FlatFormatSerializer.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/FlatFormatSerializerJUnitTest.java

GEODE-7208: FlatFormatSerializer should index on inherited fields

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunction66.java
geode-core/src/main/java/org/apache/geode/management/internal/api/GeodeClusterManagementServiceBuilder.java

GEODE-6094: Removing unnecessary String.format.

---

geode-book/master_middleman/source/subnavs/geode-subnav.erb
geode-docs/managing/heap_use/heap_and_off_heap_management.html.md.erb
geode-docs/managing/heap_use/heap_management.html.md.erb

GEODE-7215: Include status of G1 GC compatibility in documentation

---

geode-web-management/src/main/java/org/apache/geode/management/internal/rest/ManagementLoggingFilter.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/ManagementControllerAdvice.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/MemberManagementController.java

* add the filter for list members
* remove classnames from the json response in the logs
this is only added for list members for demo purposes. Later on, we should have a story to add the default filter to all the controller and have test to make sure the output of the filter is as expected

GEODE-6966: add default jqFilter for the json result

---

geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/Tomcat8ClientServerRollingUpgradeTest.java
geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/TomcatSessionBackwardsCompatibilityTestBase.java
geode-core/src/distributedTest/java/org/apache/geode/ClusterCommunicationsDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/security/ClientDataAuthorizationUsingLegacySecurityDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/security/ClientDataAuthorizationUsingLegacySecurityWithFailoverDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/ProcessManager.java
geode-junit/src/main/java/org/apache/geode/test/version/TestVersion.java
geode-junit/src/main/java/org/apache/geode/test/version/VersionManager.java
geode-lucene/src/upgradeTest/java/org/apache/geode/cache/lucene/LuceneSearchWithRollingUpgradeDUnit.java
geode-old-versions/build.gradle
geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeMultipleReceiversDefinedInClusterConfiguration.java
settings.gradle

GEODE-7250 accommodate new versions greater than 1.9

---

geode-docs/managing/heap_use/off_heap_management.html.md.erb

GEODE-7215: Fix broken link in doc

---

geode-core/src/main/java/org/apache/geode/management/internal/configuration/converters/RegionConverter.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidator.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/converters/RegionConverterTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidatorTest.java
geode-management/src/main/java/org/apache/geode/management/configuration/Region.java
geode-management/src/main/java/org/apache/geode/management/configuration/RegionType.java

GEODE-6945: use LEGACY instead of UNSUPPORTED

---

geode-book/README.md

GEODE-7260: Fix wrong statement in geode-book/README

---

geode-core/src/main/java/org/apache/geode/management/internal/configuration/converters/RegionConverter.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidator.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/converters/RegionConverterTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidatorTest.java
geode-management/src/main/java/org/apache/geode/management/configuration/Region.java
geode-management/src/main/java/org/apache/geode/management/configuration/RegionType.java
geode-management/src/test/java/org/apache/geode/management/configuration/RegionTest.java

* experimental api should not have deprecated apis.

GEODE-6945: remove deprecated types in v2 RegionType

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/PRColocationDUnitTest.java
geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-core/src/main/java/org/apache/geode/internal/cache/BucketSetHelper.java
geode-core/src/main/java/org/apache/geode/internal/cache/ColocationHelper.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalDataSet.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionDataStore.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/FunctionExecutionNodePruner.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/FunctionRemoteContext.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/InternalRegionFunctionContext.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/PartitionedRegionFunctionResultSender.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/RegionFunctionContextImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PartitionedRegionFunctionStreamingMessage.java
geode-core/src/test/java/org/apache/geode/internal/cache/BucketSetHelperTest.java
geode-dunit/src/main/java/org/apache/geode/internal/cache/functions/TestFunction.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/PartitionedRepositoryManager.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/PartitionedRepositoryManagerJUnitTest.java

GEODE-7134: Replace bucket Set with bucket int[]

---

geode-assembly/src/distributedTest/java/org/apache/geode/rest/internal/web/controllers/RestAPIsWithSSLDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/eviction/EvictionDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/util/MergeLogsDistributedTest.java
geode-cq/src/distributedTest/java/org/apache/geode/security/MultiUserAPIDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/Invoke.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/DUnitHost.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/DUnitLauncher.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/InternalBlackboardImpl.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/JUnit4DistributedTestCase.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java

GEODE-7265: Avoid creating default locator VM when ClusterStartupRule is used

---

geode-web/build.gradle
geode-web/src/test/resources/expected-pom.xml

GEODE-7261: Include spring-core in the geode-web war artifact

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ClientServerNotColocatedTransactionDistributedTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXState.java

* make sure TXStateProxyImpl tracks the transactional reads
so that it could throw correct TransactionException accordingly.

 GEODE-7243: Throw correct TransactionException accordingly

---

geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/rest/SwaggerManagementVerificationIntegrationTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/swagger/SwaggerConfig.java

GEODE-7156: add authTokenEnabled in swagger api info

---

geode-core/src/integrationTest/java/org/apache/geode/internal/AvailablePortHelperIntegrationTest.java

* Reduce excessive runtime loops
* Rewrite tests using newer JDK utilities and AssertJ
* Remove parameters from tests that don't need them
Please review: @aaronlindsey

GEODE-6860: Cleanup AvailablePortHelperIntegrationTest

---

dev-tools/docker/base/Dockerfile
dev-tools/docker/docs/Dockerfile
dev-tools/docker/docs/README.md
dev-tools/docker/docs/build-docs.sh
dev-tools/docker/docs/build-image-common.sh
dev-tools/docker/docs/view-docs.sh
geode-book/README.md

GEODE-7272: Generate user guide using Docker

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt

Need to pick up a fix for a CVE in Jackson. Hence rolling the version...

GEODE-7255: Pickup Jackson CVE fix

---

geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/misc/WanAutoDiscoveryDUnitTest.java

GEODE-7270: wait until expected sites are ready to make test stable

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentPartitionedRegionWithRedundancyDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionStats.java

GEODE-7248: update flaky test

---

geode-core/src/integrationTest/java/org/apache/geode/internal/logging/MergeLogFilesIntegrationTest.java
geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
geode-core/src/main/java/org/apache/geode/internal/logging/LogFileParser.java
geode-core/src/main/java/org/apache/geode/internal/logging/LogWriterImpl.java
geode-core/src/main/java/org/apache/geode/internal/logging/MergeLogFiles.java
geode-core/src/main/java/org/apache/geode/internal/logging/SortLogFile.java
geode-core/src/main/java/org/apache/geode/internal/process/BlockingProcessStreamReader.java
geode-core/src/main/java/org/apache/geode/internal/process/NonBlockingProcessStreamReader.java
geode-core/src/main/java/org/apache/geode/internal/process/ProcessStreamReader.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/result/CommandResult.java
geode-core/src/test/java/org/apache/geode/internal/logging/InternalLogWriterTest.java
geode-core/src/test/java/org/apache/geode/internal/logging/LogWriterImplTest.java
geode-core/src/test/java/org/apache/geode/internal/logging/SortLogFileTest.java
geode-junit/src/integrationTest/java/org/apache/geode/test/compiler/JavaCompilerTest.java
geode-junit/src/main/java/org/apache/geode/internal/process/AbstractProcessStreamReaderIntegrationTest.java
geode-junit/src/main/java/org/apache/geode/test/compiler/JavaCompiler.java
geode-junit/src/main/java/org/apache/geode/test/compiler/UncompiledSourceCode.java
geode-junit/src/main/java/org/apache/geode/test/junit/rules/RequiresGeodeHome.java
geode-junit/src/test/java/org/apache/geode/test/compiler/UncompiledSourceCodeTest.java

Cleanup any classes and tests touched for line feeds.

GEODE-6133: Use System.lineSeparator() for line feeds

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/ClientServerRemoteHostAddressDistributedTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxy.java
geode-core/src/main/java/org/apache/geode/internal/net/SocketCloser.java

GEODE-7284: Modified CacheClientProxy remoteHostAddress to be unique

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java
geode-management/src/main/java/org/apache/geode/management/configuration/ClassName.java
geode-management/src/main/java/org/apache/geode/management/internal/ManagementHelper.java
geode-management/src/test/java/org/apache/geode/management/internal/ClusterManagementOperationStatusResultTest.java
geode-management/src/test/java/org/apache/geode/management/internal/ManagementHelperTest.java

cleaned up javadocs on ClassName
made isClassNameValid private

GEODE:7266: improve ClassName javadocs

---

geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/rest/controllers/ClusterManagementRestLoggingTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/AbstractManagementController.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/GatewayManagementController.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/MemberManagementController.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/PdxManagementController.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/PingManagementController.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RebalanceOperationController.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RegionManagementController.java

Co-authored-by: Joris Melchior <jmelchior@pivotal.io>

GEODE-7131: update spring annotation

---

geode-core/src/test/java/org/apache/geode/internal/cache/BucketRegionTest.java

GEODE-7319:Replace mock EntryEventImpl.class in problematic TCs

---

geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/DefaultQueryServiceDeprecationTest.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/DefaultQueryService.java

GEODE-7279: Warning log for deprecated system value should be shown once

---

geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementResult.java
geode-management/src/main/java/org/apache/geode/management/configuration/AbstractConfiguration.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/GatewayManagementController.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/PdxManagementController.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RegionManagementController.java

GEODE-7074:improve Cluster Management Rest api Swagger documentation

---

ci/pipelines/geode-build/jinja.template.yml
ci/scripts/cleanup_benchmarks.sh
ci/scripts/run_benchmarks.sh

ci: run benchmarks with security manager enabled

---

geode-core/src/test/java/org/apache/geode/internal/cache/BucketRegionTest.java

Revert "GEODE-7319:Replace mock EntryEventImpl.class in problematic TCs"

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/CacheDistributionAdvisorConcurrentTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionAdvisor.java
geode-core/src/main/java/org/apache/geode/internal/cache/CacheDistributionAdvisor.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistributedCacheOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/CacheDistributionAdvisorTest.java

- [] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
Please ensure that once the PR is submitted, check Concourse for build …

GEODE-6807: cache adviseUpdate and adviseAllEventsOrCached

---

geode-core/src/main/java/org/apache/geode/cache/query/security/JavaBeanAccessorMethodAuthorizer.java
geode-core/src/main/java/org/apache/geode/cache/query/security/RegExMethodAuthorizer.java
geode-core/src/main/java/org/apache/geode/cache/query/security/RestrictedMethodAuthorizer.java
geode-core/src/main/java/org/apache/geode/cache/query/security/UnrestrictedMethodAuthorizer.java
geode-core/src/test/java/org/apache/geode/cache/query/security/RestrictedMethodAuthorizerTest.java

- Method renamed to better reflect its intent.

GEODE-7320: Rename isKnownDangerousMethod

---

geode-docs/developing/querying_basics/what_is_a_query_string.html.md.erb

GEODE-7332 Add link in docs to OQL aggregates subsection

---

geode-docs/managing/logging/configuring_log4j2.html.md.erb

This PR updates locations of Log4j XML file within the docs.

GEODE-7331 Improve docs on logging (Log4j is optional)

---

geode-core/src/main/java/org/apache/geode/management/internal/MBeanProxyFactory.java
geode-core/src/main/java/org/apache/geode/management/internal/MBeanProxyInvocationHandler.java
geode-core/src/main/java/org/apache/geode/management/internal/MXBeanProxyInvocationHandler.java
geode-core/src/main/java/org/apache/geode/management/internal/OpenTypeConverter.java
geode-core/src/main/java/org/apache/geode/management/internal/OpenTypeUtil.java
geode-core/src/test/java/org/apache/geode/management/internal/MBeanProxyFactoryTest.java
geode-core/src/test/java/org/apache/geode/management/internal/MBeanProxyInvocationHandlerTest.java

Create MBeanProxyInvocationHandlerTest
Cleanup related management classes:
* MBeanProxyInvocationHandler
* MXBeanProxyInvocationHandler
* OpenTypeUtil
* OpenTypeConverter
NOTE: this PR does NOT fix GEODE-6682. This PR just cleans up the classes involved in the ticket and adds a new unit test. I'm hoping that we can reproduce the ticket in the new unit test and then fix the cause, but I'm not sure how long it'll take to finish this up so I'd like to merge this in.

GEODE-6682: Create unit tests for MBeanProxyInvocationHandler

---

geode-core/src/main/java/org/apache/geode/management/internal/FederatingManager.java
geode-core/src/test/java/org/apache/geode/management/internal/FederatingManagerTest.java

GEODE-7297: Prevent NullPointerException in FederatingManager

---

settings.gradle

Add 1.9.2 to old versions

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientConnectDisconnectSocketDistributedTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxy.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientTestCase.java

GEODE-7286: Reset _socketClosed AtomicBoolean when client reconnects

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/MemberTypeCommonTagsTest.java
geode-core/src/main/java/org/apache/geode/metrics/internal/InternalDistributedSystemMetricsService.java
geode-core/src/test/java/org/apache/geode/metrics/internal/InternalDistributedSystemMetricsServiceBuilderTest.java
geode-core/src/test/java/org/apache/geode/metrics/internal/InternalDistributedSystemMetricsServiceTest.java

GEODE-7363: Add member type common tag

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/build.gradle
geode-assembly/src/integrationTest/java/org/apache/geode/rest/internal/web/RestSecurityPostProcessorTest.java
geode-assembly/src/integrationTest/resources/expected_jars.txt
geode-http-service/src/main/java/org/apache/geode/internal/cache/InternalHttpService.java
geode-web-api/build.gradle

* also fix dev rest api to honor json annotation loaded by the system classloader

GEODE-7334: do not load jackson classes from system class loader

---

geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/TomcatSessionBackwardsCompatibilityTomcat8WithOldModuleCanDoPutsTest.java

GEODE-7367: Unignored Tomcat8WithOldModuleCanDoPutsTest

---

geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/TomcatSessionBackwardsCompatibilityTomcat7079WithOldModuleCanDoPutsTest.java

GEODE-7367: Unignored TomcatSessionBackwardsCompatibilityTomcat7079WithOldModuleCanDoPutsTest

---

geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpServer.java
geode-core/src/test/java/org/apache/geode/distributed/internal/tcpserver/TcpServerDependenciesTest.java

[GEODE-7354](https://issues.apache.org/jira/browse/GEODE-7354)

GEODE-7354: break dependencies on SystemFailure

---

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ShutdownCommand.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/ShutdownCommandInterceptorTest.java

GEODE-7372: abort when user respond with no to shutdown command

---

ci/pipelines/geode-build/jinja.template.yml
ci/scripts/create_instance.sh

Co-authored-by: Bala Kaza Venkata <bkazavenkata@pivotal.io>

GEODE-7392: Add sha tag to heavy lifter.

---

geode-core/src/integrationTest/java/org/apache/geode/management/internal/security/JmxCredentialTypeTest.java
geode-core/src/main/java/org/apache/geode/internal/security/shiro/JMXShiroAuthenticator.java
geode-core/src/main/java/org/apache/geode/management/internal/ManagementAgent.java

GEODE-7373: add jmx credential type constraint

---

geode-core/src/main/java/org/apache/geode/internal/net/BufferPool.java
geode-core/src/main/java/org/apache/geode/internal/net/NioPlainEngine.java
geode-core/src/main/java/org/apache/geode/internal/net/NioSslEngine.java
geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
geode-core/src/main/java/org/apache/geode/internal/tcp/MsgStreamer.java
geode-core/src/test/java/org/apache/geode/internal/net/NioPlainEngineTest.java
geode-core/src/test/java/org/apache/geode/internal/net/NioSslEngineTest.java

GEODE-6661: Fixed use of Direct and Non-Direct buffers

---

geode-book/master_middleman/source/subnavs/geode-subnav.erb
geode-docs/managing/statistics/setting_up_statistics.html.md.erb
geode-docs/tools_modules/book_intro.html.md.erb
geode-docs/tools_modules/micrometer/micrometer-configuration.html.md.erb
geode-docs/tools_modules/micrometer/micrometer-meters.html.md.erb
geode-docs/tools_modules/micrometer/micrometer-overview.html.md.erb

Created a new section in 'tools' menu where we document what micrometer is, meters we have added, and how to use it.
- ~[ ] Have you written or updated unit tests to verify your changes?~
- ~[ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?~

GEODE-7395: Add Micrometer docs

---

geode-core/src/integrationTest/java/org/apache/geode/distributed/LocatorLauncherStatusTest.java
geode-core/src/main/java/org/apache/geode/distributed/LocatorLauncher.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/LocatorLauncherStartupRule.java

GEODE-7401: add LocatorLauncherStartupRule

---

geode-management/src/test/script/update-management-wiki.sh

You can see the improvements now at:
master (currently 1.10):
https://cwiki.apache.org/confluence/display/pages/viewpage.action?pageId=115511910
(for comparison, look at v56 in the history to see what it looked like before this PR)
develop:
https://cwiki.apache.org/confluence/display/pages/viewpage.action?pageId=132322415
(for comparison, look at v25 in the history to see what it looked like before this PR)
Summary of improvements:
* removed sections that did not add value
* removed duplicate model classnames
* qualified endpoints with `/management`
* table of contents is now generated by the wiki
* css is preserved
* all links work now

GEODE-7322: improvements to script to generate management REST wiki

---

geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/ServerContainer.java

GEODE-7367: Limit max and init memory for ServerContainer

---

geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/LocatorSSLJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TCPClientSSLIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TCPServerSSLJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/SSLConfigIntegrationJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/SSLConfigJUnitTest.java
geode-core/src/main/java/org/apache/geode/admin/internal/AdminDistributedSystemImpl.java
geode-core/src/main/java/org/apache/geode/internal/admin/SSLConfig.java
geode-core/src/main/java/org/apache/geode/internal/admin/remote/DistributionLocatorId.java
geode-core/src/main/java/org/apache/geode/internal/admin/remote/RemoteTransportConfig.java
geode-core/src/main/java/org/apache/geode/internal/net/SSLConfigurationFactory.java
geode-core/src/main/java/org/apache/geode/internal/net/SocketCreatorFactory.java
geode-core/src/main/java/org/apache/geode/management/internal/JmxManagerAdvisee.java
geode-core/src/test/java/org/apache/geode/internal/net/SSLConfigurationFactoryJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/net/SocketCreatorJUnitTest.java
geode-http-service/src/test/java/org/apache/geode/management/internal/InternalHttpServiceJunitTest.java
geode-protobuf/src/integrationTest/java/org/apache/geode/internal/protocol/protobuf/v1/acceptance/CacheConnectionIntegrationTest.java
geode-protobuf/src/integrationTest/java/org/apache/geode/internal/protocol/protobuf/v1/acceptance/CacheOperationsJUnitTest.java
geode-pulse/geode-pulse-test/src/main/java/org/apache/geode/tools/pulse/tests/rules/ServerRule.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/GatewaySenderEventRemoteDispatcherIntegrationTest.java

Reverts apache/geode#4204
Breaking the build

Revert "GEODE-7157: SSLConfig&SSLConf..Factory thread-safe"

---

ci/pipelines/metrics/jinja.template.yml

- [x ] Is your initial contribution a single, squashed commit?

GEODE-7408: Metrics pipeline is referencing incorrect image

---

geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/LocatorSSLJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TCPClientSSLIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TCPServerSSLJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/SSLConfigIntegrationJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/SSLConfigJUnitTest.java
geode-core/src/main/java/org/apache/geode/admin/internal/AdminDistributedSystemImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ConnectionFactoryImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/PoolImpl.java
geode-core/src/main/java/org/apache/geode/distributed/LocatorLauncher.java
geode-core/src/main/java/org/apache/geode/internal/admin/SSLConfig.java
geode-core/src/main/java/org/apache/geode/internal/admin/remote/DistributionLocatorId.java
geode-core/src/main/java/org/apache/geode/internal/admin/remote/RemoteTransportConfig.java
geode-core/src/main/java/org/apache/geode/internal/net/SSLConfigurationFactory.java
geode-core/src/main/java/org/apache/geode/internal/net/SocketCreatorFactory.java
geode-core/src/main/java/org/apache/geode/management/internal/JmxManagerAdvisee.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/PoolImplTest.java
geode-core/src/test/java/org/apache/geode/internal/net/SSLConfigurationFactoryJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/net/SocketCreatorJUnitTest.java
geode-http-service/src/test/java/org/apache/geode/management/internal/InternalHttpServiceJunitTest.java
geode-protobuf/src/integrationTest/java/org/apache/geode/internal/protocol/protobuf/v1/acceptance/CacheConnectionIntegrationTest.java
geode-protobuf/src/integrationTest/java/org/apache/geode/internal/protocol/protobuf/v1/acceptance/CacheOperationsJUnitTest.java
geode-pulse/geode-pulse-test/src/main/java/org/apache/geode/tools/pulse/tests/rules/ServerRule.java
geode-wan/src/test/java/org/apache/geode/internal/cache/wan/GatewaySenderEventRemoteDispatcherIntegrationTest.java

`PoolImplTest` failed to compile. It compiles and the test passes now.
Original (reverted) PR: https://github.com/apache/geode/pull/4204
Revert PR: https://github.com/apache/geode/pull/4283

GEODE-7157: fix compile error causing reverted merge of GEODE-7157

---

geode-book/config.yml
geode-book/redirects.rb

GEODE-7415: Fix version variable for docs

---

geode-assembly/src/distributedTest/java/org/apache/geode/rest/internal/web/controllers/RestAPIsAndInterOpsDUnitTest.java

This is one the commits to remove the deprecated `AttributesFactory`
class from the geode-assembly module. The work is splitted to avoid
hitting issues in CI.
- Removed references to the deprecated AttributesFactory class from
the RestAPIsAndInterOpsDUnitTest class.

GEODE-7407: Remove AttributesFactory (2/4)

---

geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/aggregate/AvgIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/aggregate/CountIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/aggregate/MaxIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/aggregate/MinIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/aggregate/SumIntegrationTest.java

GEODE-7432: Fix spelling error in test methods

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ManagementRequestLoggingDistributedTest.java
geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/rest/controllers/ClusterManagementRestLoggingTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/ManagementLoggingFilter.java

Simple change to log level in management API to avoid logs being too chatty

GEODE-7428: change log level in management API

---

geode-core/src/main/java/org/apache/geode/distributed/ServerLauncher.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/ServerLauncherStartupRule.java

GEODE-7401: add ServerLauncherStartupRule

---

extensions/geode-modules/src/integrationTest/java/org/apache/geode/modules/session/catalina/internal/DeltaSessionStatisticsIntegrationTest.java

- Fixed flakiness in DeltaSessionStatisticsIntegrationTest.

GEODE-7439: Fix DeltaSessionStatisticsIntegrationTest

---

geode-management/src/test/script/update-management-wiki.sh

Problems with having only two wiki pages (one generated from master and one from develop) had two drawbacks:
1) could not generate docs until after release shipped
2) could not link to previous doc version when they get overwritten, because confluence doesn't seem to support a url syntax to refer to page version in history, and even if it did, it would be clunky
3) it was confusing that develop was a sub-page of 1.10.0
Now, one wiki page per release version must be (manually) allocated and added to the script, but now it generate the wiki page from develop, master, or an active release branch, so that docs can be made available earlier in the release process.
See new page tree at https://cwiki.apache.org/confluence/display/GEODE/develop+Management+REST+API+-+v1

GEODE-7457: publish one wiki page per release instead of overwriting

---

geode-core/src/main/java/org/apache/geode/cache/TransactionId.java

do not use internal class

---

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TcpServerJUnitTest.java
geode-core/src/test/java/org/apache/geode/distributed/internal/membership/MembershipDependenciesJUnitTest.java
geode-core/src/test/java/org/apache/geode/distributed/internal/tcpserver/TcpServerDependenciesTest.java

[GEODE-7380](https://issues.apache.org/jira/browse/GEODE-7380)
Apparently all the substantive work for this PR was already done on `develop` so all I had to do in the end was eliminate the offending clauses in the ArchUnit test.

GEODE-7380: remove dependencies on DistributionConfig

---

extensions/geode-modules/src/integrationTest/java/org/apache/geode/modules/session/catalina/internal/DeltaSessionStatisticsIntegrationTest.java

- Fixed flakiness in DeltaSessionStatisticsIntegrationTest.

GEODE-7461: Fix Flaky Test

---

geode-core/src/test/java/org/apache/geode/internal/cache/ha/HARegionQueueTest.java

GEODE-7466: Closed the existing CacheClientNotifier instance

---

geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/PdxValidatorTest.java

GEODE-7468: fix compiler warnings

---

geode-core/src/main/java/org/apache/geode/distributed/internal/Distribution.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionImpl.java

Restoring the beHealthy test hook that was removed from Distribution.

GEODE-7456: Restoring removed test hook

---

geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/tests/ChangeProductVersionDistributedTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/Host.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/VM.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/DUnitHost.java
geode-junit/src/main/java/org/apache/geode/test/version/TestVersion.java
geode-junit/src/test/java/org/apache/geode/test/version/TestVersionTest.java

[GEODE-7482](https://issues.apache.org/jira/browse/GEODE-7482)

GEODE-7482: make DUnit launch correct product version

---

extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/DeltaSessionManager.java

GEODE-7368: Caught and ignored EntryNotFoundException during doUnload

---

geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionArchUnitTest.java

Disabling this test until we can make it consistently not run out of memory.

GEODE-7489: Disable DistributionArchUnitTest

---

geode-book/master_middleman/source/subnavs/geode-subnav.erb
geode-docs/configuring/cluster_config/gfsh_persist.html.md.erb
geode-docs/managing/security/implementing_authorization.html.md.erb
geode-docs/tools_modules/gfsh/cache_xml_2_gfsh.html.md.erb
geode-docs/tools_modules/gfsh/command-pages/alter.html.md.erb
geode-docs/tools_modules/gfsh/gfsh_quick_reference.html.md.erb
geode-docs/tools_modules/gfsh/quick_ref_commands_by_area.html.md.erb

GEODE-6993: Add documentation for alter query-service gfsh command

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/wan/asyncqueue/AsyncEventListenerDistributedTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/wan/asyncqueue/ParallelSerialAsyncEventListenerStopStartDistributedTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/asyncqueue/internal/SerialAsyncEventQueueImplJUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/asyncqueue/internal/SerialAsyncEventQueueImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySender.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySenderEventProcessor.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ConcurrentParallelGatewaySenderEventProcessor.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/ConcurrentSerialGatewaySenderEventProcessor.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderQueue.java
geode-core/src/test/java/org/apache/geode/cache/asyncqueue/internal/SerialAsyncEventQueueImplTest.java

GEODE-7465: Set eventProcessor to null in serial AEQ when it is stopped

---

geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionImpl.java

GEODE-7456: Fixing omitted catch statement that adds shutdown cause.

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy

GEODE-7494: Upgrade ArchUnit to 0.12.0

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DeployCommandRedeployDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DeploySemanticVersionJarDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DeployWithGroupsDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/ClassPathLoaderDeployTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/ClassPathLoaderIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/ClassPathLoaderJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/DeployedJarTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/JarDeployerDeadlockTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/JarDeployerFileTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/JarDeployerIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/backup/IncrementalBackupIntegrationTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalConfigurationPersistenceService.java
geode-core/src/main/java/org/apache/geode/internal/ClassPathLoader.java
geode-core/src/main/java/org/apache/geode/internal/DeployJarChildFirstClassLoader.java
geode-core/src/main/java/org/apache/geode/internal/DeployedJar.java
geode-core/src/main/java/org/apache/geode/internal/JarDeployer.java
geode-core/src/main/java/org/apache/geode/internal/cache/ClusterConfigurationLoader.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DeployCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DeployFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/ListDeployedFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/UndeployFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/domain/Configuration.java
geode-core/src/test/java/org/apache/geode/distributed/internal/InternalConfigurationPersistenceServiceJunitTest.java
geode-core/src/test/java/org/apache/geode/distributed/internal/InternalConfigurationPersistenceServiceTest.java
geode-core/src/test/java/org/apache/geode/internal/ClassPathLoaderTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/ClusterConfigurationLoaderTest.java
geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ExportClusterConfigurationCommandTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/domain/ConfigurationTest.java

GEODE-7436: Deploy jar using semantic versioning scheme

---

geode-dunit/src/distributedTest/java/org/apache/geode/test/greplogs/LogConsumerDistributedTest.java

Some of the nested test classes were not awaiting the completion of the
AsyncInvocation.
Use AtomicReference instead of volatile for test fields.
The actual fix is adding this line to each of the nested tests:
```
asyncInvocation.get().await();
```
On this branch, LogConsumerDistributedTest passes 1000 dunitrunner runs as well as cross-section 16 1000.
This PR also fixes [GEODE-7467](https://issues.apache.org/jira/browse/GEODE-7467) which was occurring when the AsyncInvocations logged the error message after LogConsumerDistributedTest completed. Awaiting for completion of all AsyncInvocations prevents this late logging.

GEODE-7470: Fix LogConsumerDistributedTest

---

geode-book/config.yml
geode-docs/configuring/cluster_config/persisting_configurations.html.md.erb
geode-docs/configuring/running/running_the_cacheserver.html.md.erb
geode-docs/configuring/running/running_the_locator.html.md.erb
geode-docs/getting_started/15_minute_quickstart_gfsh.html.md.erb
geode-docs/getting_started/installation/install_standalone.html.md.erb
geode-docs/getting_started/system_requirements/host_machine.html.md.erb
geode-docs/managing/management/jmx_manager_operations.html.md.erb
geode-docs/tools_modules/gfsh/tour_of_gfsh.html.md.erb
geode-docs/tools_modules/http_session_mgmt/tc_additional_info.html.md.erb
geode-docs/tools_modules/http_session_mgmt/tc_setting_up_the_module.html.md.erb
geode-docs/tools_modules/http_session_mgmt/weblogic_setting_up_the_module.html.md.erb

GEODE-2184: Genericize Java version numbers in docs

---

geode-book/master_middleman/source/subnavs/geode-subnav.erb
geode-docs/managing/security/implementing_authorization.html.md.erb
geode-docs/tools_modules/gfsh/command-pages/describe.html.md.erb
geode-docs/tools_modules/gfsh/quick_ref_commands_by_area.html.md.erb

GEODE-7405: Documentation for describe query-service command

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RebalanceManagementDunitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/extension/mock/MockExtensionCommands.java
geode-core/src/distributedTest/java/org/apache/geode/internal/util/PluckStacksDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/CliUtilDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/RepeatedRebalanceDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/ClusterConfigurationLoader.java
geode-core/src/main/java/org/apache/geode/internal/cache/control/RebalanceResultsImpl.java
geode-core/src/main/java/org/apache/geode/management/cli/GfshCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/CliUtil.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/AlterRuntimeConfigCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeClientCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsUtils.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ExportConfigCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/GCCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListRegionCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/NetstatCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/RebalanceCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/RegionCommandsUtils.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StatusClusterConfigServiceCommand.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/RebalanceFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/operation/RebalanceOperationPerformer.java
geode-core/src/main/java/org/apache/geode/management/internal/util/ManagementUtils.java
geode-management/src/main/java/org/apache/geode/management/internal/operation/RebalanceResultImpl.java
geode-management/src/main/java/org/apache/geode/management/runtime/RebalanceResult.java

GEODE-7496 - Decouple management API from Gfsh RebalanceCommand

---

geode-assembly/src/integrationTest/java/org/apache/geode/BundledJarsJUnitTest.java
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/expected_jars.txt
geode-core/build.gradle
geode-core/src/test/resources/expected-pom.xml
geode-memcached/build.gradle
geode-memcached/src/test/resources/expected-pom.xml

GEODE-7502: Remove findbugs dependency from runtime

---

geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/DocLinksControllerRestIntegrationTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/DocLinksController.java

GEODE-7463: show management rest api docs

---

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/RebalanceCommandDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/RebalanceCommand.java

GEODE-7521: Add slash to start of region name.

---

ci/scripts/rsync_code_down.sh
ci/scripts/rsync_code_up.sh

Create a complete state of the worker on the heavy-lifter for running
Gradle tasks.

rsync all inputs and outputs between the heavy-lifter and concourse

---

geode-book/README.md

Changed underscore to hyphen in a pathname.

Fix typo in a README file

---

geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/DocLinksController.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/security/RestSecurityConfiguration.java

- Provide structure for doclinks for better Swagger experience

GEODE-7463: make docLinks public

---

README.md

the PNG has capital letters now

Fix Geode Logo

---

geode-book/config.yml
geode-docs/configuring/running/cluster-management-service.html.md.erb

Tweak to the version variable that links to the Wiki feature description - needs to be geode-specific

GEODE-7454 Document Cluster Mgmt Svc: introduce a doc template variable

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RegionManagementDunitTest.java
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-core/src/main/java/org/apache/geode/cache/configuration/DeclarableType.java
geode-core/src/main/java/org/apache/geode/cache/configuration/RegionAttributesType.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/converters/RegionConverter.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidator.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-management-serializables.txt
geode-core/src/test/java/org/apache/geode/cache/configuration/RegionAttributesTypeTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/converters/RegionConverterTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidatorTest.java
geode-management/src/main/java/org/apache/geode/management/configuration/Region.java
geode-management/src/main/java/org/apache/geode/management/internal/PlainClusterManagementServiceBuilder.java
geode-management/src/test/java/org/apache/geode/management/configuration/RegionTest.java

Revert "GEODE-7504: region eviction support"

---

geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySenderEventProcessor.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ConcurrentParallelGatewaySenderEventProcessor.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderEventProcessor.java
geode-core/src/test/java/org/apache/geode/internal/cache/wan/AbstractGatewaySenderEventProcessorTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/wan/parallel/ConcurrentParallelGatewaySenderEventProcessorTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderEventProcessorTest.java

* returns localSize on ParallelGatewaySenderQueue for eventQueueSize.

GEODE-7530: returns localSize on ParallelGatewaySenderQueue

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RegionManagementDunitTest.java
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-common/src/main/java/org/apache/geode/util/internal/GeodeJsonMapper.java
geode-common/src/test/java/org/apache/geode/util/internal/GeodeJsonMapperTest.java
geode-core/src/main/java/org/apache/geode/cache/configuration/DeclarableType.java
geode-core/src/main/java/org/apache/geode/cache/configuration/RegionAttributesType.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/converters/RegionConverter.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidator.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-management-serializables.txt
geode-core/src/test/java/org/apache/geode/cache/configuration/RegionAttributesTypeTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/converters/RegionConverterTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidatorTest.java
geode-management/src/main/java/org/apache/geode/management/configuration/Region.java
geode-management/src/main/java/org/apache/geode/management/internal/PlainClusterManagementServiceBuilder.java
geode-management/src/test/java/org/apache/geode/management/configuration/RegionTest.java

* added eviction support to RegionConverter and RegionConfigValidator

GEODE-7504: region eviction support

---

geode-core/src/main/java/org/apache/geode/cache/configuration/RegionConfig.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/converters/IndexConverter.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/converters/IndexConverterTest.java
geode-management/src/main/java/org/apache/geode/management/configuration/Index.java
geode-management/src/main/java/org/apache/geode/management/configuration/IndexType.java
geode-management/src/main/java/org/apache/geode/management/configuration/RegionType.java

co-authored-by: Dale Emery <demery@pivotal.io>
co-authored-by: Jinmei Liao <jliao@pivotal.io>

Geode-7498: show index type

---

ci/scripts/create_instance.sh
ci/scripts/delete_instance.sh

- [ n/a] Does `gradlew build` run cleanly?
- [ n/a] Have you written or updated unit tests to verify your changes?
- [ n/a] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

GEODE-7527: Correct create_instance and delete_instance zone usage

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/partitioned/colocation/ModifyColocationIntegrationTest.java

Use CacheLifecycleListener to await asynchronous cache close. Remove
await from after synchronous cache close calls.
This fixes the failures of ModifyColocationIntegrationTest in one of my PR StressNewTest jobs: https://concourse.apachegeode-ci.info/builds/113106

GEODE-7513: Fix ModifyColocationIntegrationTest

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/NetSearchMessagingDUnitTest.java

Refactor out warnings and deprecations. Changes made to address flakiness:
- Implement Serializable
- Use Dunit rules DistributedRule and CacheRule
- Use AssertJ
- Use setup and teardown methods
email …

GEODE-7474: Fix NetSearchMessagingDUnitTest

---

geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-management-serializables.txt

GEODE-7498: fix assembly content test

---

geode-core/src/test/java/org/apache/geode/management/internal/configuration/realizers/DeploymentRealizerTest.java

GEODE-7398: Fix windows path separator comparison

---

geode-core/src/main/java/org/apache/geode/management/internal/configuration/converters/IndexConverter.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/converters/IndexConverterTest.java
geode-management/src/main/java/org/apache/geode/management/configuration/IndexType.java

GEODE-7498: update index type name from FUNCTIONAL to RANGE

---

geode-core/src/test/java/org/apache/geode/management/internal/configuration/realizers/DeploymentRealizerTest.java

GEODE-7564: fix windows test failure

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/RedundancyLevelPart3DUnitTest.java

Changes made to address flakiness:
- Inline super
- Implement Serializable
- Use Dunit rules DistributedRule and CacheRule
- Use setup and teardown methods
- Use AssertJ

GEODE-7469: Fix RedundancyLevelPart3DUnitTest

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/DeployToMultiGroupDUnitTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/DeploymentManagementController.java

GEODE-7398: implement get single deployment end point

---

geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java

GEODE-6927 make getThreadOwnedConnection code thread safe

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/DeploymentManagementDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/realizers/DeploymentRealizer.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-management-serializables.txt
geode-core/src/test/java/org/apache/geode/management/internal/configuration/realizers/DeploymentRealizerTest.java
geode-management/src/main/java/org/apache/geode/management/runtime/DeploymentInfo.java

GEODE-7398: add timeDeployed to the runtime info of deployed jar

---

ci/bin/concourse_job_performance.py

Updated the mass test script to use a local look at the concourse config.

Mass test script change

---

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/GMSMembershipJUnitTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionMessage.java
geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMembership.java
geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/api/Message.java
geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messages/AbstractGMSMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PartitionMessageWithDirectReply.java

[GEODE-7569](https://issues.apache.org/jira/browse/GEODE-7569)

GEODE-7569: repair play dead in membership tests

---

ci/pipelines/metrics/jinja.template.yml

- Because the upstream concept doesn't seem necessary

Yet another tweak to the jinja template

---

ci/bin/concourse_job_performance.py

Removing a dependency on my home directory.

Removing a dependency on my home directory

---

geode-management/src/main/java/org/apache/geode/management/configuration/AutoSerializer.java
geode-management/src/main/java/org/apache/geode/management/configuration/ClassName.java
geode-management/src/main/java/org/apache/geode/management/configuration/Pdx.java

GEODE-7574: fix javadoc warnings

---

geode-web-management/src/main/java/org/apache/geode/management/internal/rest/ManagementLoggingFilter.java

* revert accidental change to the logging

GEODE-7424: revert accidental change to the logging

---

geode-http-service/src/main/java/org/apache/geode/internal/cache/InternalHttpService.java

GEODE-7533: System Properties catalina.home and catalina.base are cleared during webapp reloads when using HTTP Session Management Module

---

geode-docs/developing/query_additional/using_query_bind_parameters.html.md.erb

GEODE-7534: Add example for query with bind params

---

geode-core/src/main/java/org/apache/geode/internal/cache/PoolManagerImpl.java

Added type checking before casting generic `Pool.java` to`PoolImpl.java`

GEODE-7531: Added type checking in PoolManagerImpl

---

geode-core/src/main/java/org/apache/geode/internal/cache/PoolManagerImpl.java

Amending emergencyClose to type check before casting. 
Also included Optional instead of null checks
- [] Have you written or updated unit tests to verify your changes?

GEODE-7159: Amending emergencyClose to type check before casting. 

---

geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/IndexConfigManager.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/IndexValidator.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/IndexValidatorTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementIntegrationTest.java

Now makes sure that create index on a group works correctly.

GEODE-7424: create index on group

---

geode-gfsh/build.gradle
geode-gfsh/src/test/resources/expected-pom.xml

GEODE-7588: Add geode-all-bom to geode-gfsh.

---

ci/scripts/run_benchmarks.sh

Fixes bash error in run_benchmarks.sh script.

---

geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/index/AbstractIndexMaintenanceIntegrationTest.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/AbstractIndex.java

GEODE-7593: Force index to use Strings instead of PdxString when Eviction enabled

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionAsSubregionDUnitTest.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneServiceImpl.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/distributed/LuceneQueryFunction.java
geode-lucene/src/upgradeTest/java/org/apache/geode/cache/lucene/LuceneSearchWithRollingUpgradeTestBase.java

* Modified test to assert that wait for flush successfully completes

GEODE-7571: Fix logic determining when query will wait for a repo

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/StatusLocatorCommandDunitTest.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/LocatorLauncherStatusTest.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/GfshCommandRule.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/LocatorLauncherStartupRule.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/MemberStarterRule.java

GEODE-7583: rule improvement for ssl support

---

geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/functions/GatewaySenderCreateFunction.java
geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/commands/CreateGatewaySenderCommandTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/wancommand/CreateDestroyGatewaySenderCommandDUnitTest.java

GEODE-7561: GW sender allow single dispatcher thread

---

geode-core/src/distributedTest/java/org/apache/geode/distributed/LocatorDUnitTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionImpl.java
geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/Services.java

ensure that exceptions are translated to those acceptable by geode-core

---

geode-core/src/distributedTest/java/org/apache/geode/management/ClientHealthStatsDUnitTest.java

[GEODE-7614](https://issues.apache.org/jira/browse/GEODE-7614)

GEODE-7614: wait for subscriptions

---

geode-core/src/main/java/org/apache/geode/distributed/internal/AbstractDistributionConfig.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java

[GEODE-7613](https://issues.apache.org/jira/browse/GEODE-7613)

GEODE-7613: move multicast address init to where it's needed

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ListIndexManagementDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/IndexConfigManager.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/realizers/IndexRealizer.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/IndexValidator.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/mutators/IndexConfigManagerTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/realizers/IndexRealizerTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/IndexValidatorTest.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementRealizationResult.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/ClusterManagementSecurityRestIntegrationTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementControllerSpringTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementIntegrationTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RegionManagementController.java

GEODE-7425 delete index

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/SingleHopGetAllPutAllDUnitTest.java

Added some recommended changes to try to address the issue.

GEODE-7387: SingleHopGetAllPutAllDUnitTest.testRemoveAllInClient is failing

---

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitorJUnitTest.java

GEODE-7541: Clean up of auto-generated catch blocks.

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/StatusLocatorCommandSSLTest.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/utils/ClusterConfigurationStatusRetriever.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/ConnectCommand.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/OfflineGfshCommand.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/lifecycle/StatusLocatorCommand.java

* add "security-property-file" option to the command
* use the ssl properties when connect for status

GEODE-7583: allow "status locator" to work with ssl enabled locators

---

ci/pipelines/shared/jinja.variables.yml

Benchmark against previous release.

---

ci/pipelines/geode-build/jinja.template.yml
ci/pipelines/shared/jinja.variables.yml
ci/scripts/run_benchmarks.sh

Bring benchmark job changes to release 1.11.0

---

geode-core/src/integrationTest/java/org/apache/geode/management/internal/security/NoSecurityManagerTest.java
geode-core/src/main/java/org/apache/geode/management/internal/BlockMBeanCreationController.java
geode-core/src/main/java/org/apache/geode/management/internal/ManagementAgent.java

GEODE-7628: Block mbean creation when no security

---

geode-junit/src/main/java/org/apache/geode/internal/jta/JTAUtils.java

GEODE-7560: Fix LGTM JTAUtils Issues

---

geode-core/src/test/java/org/apache/geode/distributed/internal/membership/MembershipDependenciesJUnitTest.java
geode-core/src/test/java/org/apache/geode/distributed/internal/membership/gms/api/MembershipAPIArchUnitTest.java

GEODE-7345: Clean up resolved dependency exceptions in API test.

---

geode-core/src/distributedTest/java/org/apache/geode/cache/ConnectionPoolDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/DiskDistributedNoAckAsyncOverflowRegionDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/DiskDistributedNoAckSyncOverflowRegionDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedAckOverflowRegionCCEDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedAckOverflowRegionCCEOffHeapDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedAckPersistentRegionCCEDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedAckPersistentRegionCCEOffHeapDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedAckRegionCCEDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedAckRegionCCEOffHeapDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedAckRegionCompressionDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedAckRegionDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedAckRegionOffHeapDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedMulticastRegionDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedNoAckRegionOffHeapDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/LocalRegionDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/SearchAndLoadDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/TXDistributedDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache30/TXRestrictionsDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ClientDeserializationCopyOnReadRegressionTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/GIIDeltaDUnitTest.java
geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/CqQueryDUnitTest.java
geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/CqQueryUsingPoolDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/cache30/ClientServerTestCase.java
geode-dunit/src/main/java/org/apache/geode/cache30/MultiVMRegionTestCase.java

fixing other calls to getRegionAttributes.

GEODE-7600: fixing other calls to getRegionAttributes.

---

geode-dunit/src/main/java/org/apache/geode/test/junit/rules/LocatorStarterRule.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/ManagementLoggingFilter.java

GEODE-7640: allow tests to turn on management request/response logging

---

geode-management/src/test/java/org/apache/geode/management/configuration/AutoSerializerTest.java
geode-unsafe/src/main/java/org/apache/geode/unsafe/internal/com/sun/jmx/remote/security/MBeanServerAccessController.java

GEODE-7641: clean up compiler warnings

---

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSUtil.java
geode-core/src/test/java/org/apache/geode/distributed/internal/membership/gms/GMSUtilTest.java

[GEODE-7648](https://issues.apache.org/jira/browse/GEODE-7648)

GEODE-7648: elide hostname resolution if no bindAddress given

---

ci/pipelines/meta/destroy_pipelines.sh
dev-tools/release/deploy_rc_pipeline.sh
dev-tools/release/finalize_release.sh

and adapt release scripts to use new team name convention for fly target name

GEODE-7575: add missing $ for shell variable

---

geode-common/src/main/java/org/apache/geode/internal/lang/JavaWorkarounds.java
geode-common/src/main/java/org/apache/geode/util/internal/JavaWorkarounds.java
geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/TableMetaDataManager.java
geode-core/src/jmh/java/org/apache/geode/internal/util/ComputeIfAbsentBenchmark.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/AttributeDescriptor.java
geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitor.java
geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/GMSEncrypt.java
geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupDefinition.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/metrics/FunctionStatsManager.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientHealthMonitor.java
geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java
geode-core/src/test/java/org/apache/geode/distributed/internal/membership/MembershipDependenciesJUnitTest.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/CqServiceImpl.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/FlatFormatSerializer.java

- moved class to geode-common module

GEODE-7542: Remove dependency upon JavaWorkarounds.

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/RedundancyLevelPart1DUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/RedundancyLevelPart3DUnitTest.java

Changes made to address flakiness:
- Inline super
- Implement Serializable
- Use Dunit rules DistributedRule and CacheRule
- Use AssertJ
- Use setup and teardown methods
- CountdownLatch rather than Thread.sleep
- No static methods
- Delete ignored tests
submit an update to your PR …

GEODE-7210: Fix RedundancyLevelPart1DUnitTest

---

ci/pipelines/meta/deploy_meta.sh
ci/pipelines/meta/destroy_pipelines.sh

hopefully this is the last of them...

GEODE-7575: fix a few more places where team name was hardcoded

---

settings.gradle

add 1.11.0 to old versions

---

build.gradle
geode-assembly/Dockerfile
geode-assembly/build.gradle
gradle.properties

GEODE-7651:  Provide docker target for geode-assembly

---

geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/ClientCQImpl.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/CqListenerImpl.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/CqServiceImpl.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/CqServiceVsdStats.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/ServerCQImpl.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/command/CloseCQ.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/command/ExecuteCQ.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/command/ExecuteCQ61.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/command/StopCQ.java

GEODE-7660: clean up unneeded initializers

---

geode-core/src/main/java/org/apache/geode/internal/cache/locks/TXOriginatorRecoveryProcessor.java

GEODE-7689: Use the recipient list without the current member

---

geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-core/src/integrationTest/java/org/apache/geode/net/SSLSocketParameterExtensionIntegrationTest.java
geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
geode-core/src/main/java/org/apache/geode/distributed/internal/AbstractDistributionConfig.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfigImpl.java
geode-core/src/main/java/org/apache/geode/internal/admin/SSLConfig.java
geode-core/src/main/java/org/apache/geode/internal/net/SSLConfigurationFactory.java
geode-core/src/main/java/org/apache/geode/internal/net/SSLParameterExtension.java
geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
geode-core/src/main/java/org/apache/geode/net/SSLParameterExtension.java
geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionConfigJUnitTest.java
geode-docs/reference/topics/gemfire_properties.html.md.erb

GEODE-7414_1: Define interface

---

geode-core/src/main/java/org/apache/geode/distributed/internal/InternalConfigurationPersistenceService.java

GEODE-7693: Equals compares objects of same type.

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/AvailableConnectionManager.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/CqEntry.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/QRegion.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/IndexManager.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/Part.java

GEODE-7691: Instance of parameter checked in equals method.

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/DeployToMultiGroupDUnitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ListIndexManagementDUnitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ListRegionManagementDunitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/MemberManagementServiceDunitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RegionManagementDunitTest.java
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/RegionConfigManager.java
geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java
geode-junit/src/main/java/org/apache/geode/test/junit/assertions/ClusterManagementGetResultAssert.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementGetResult.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementRealizationResult.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementResult.java
geode-management/src/main/java/org/apache/geode/management/api/ConfigurationInfo.java
geode-management/src/main/java/org/apache/geode/management/api/ConfigurationResult.java
geode-management/src/main/java/org/apache/geode/management/configuration/GroupableConfiguration.java
geode-management/src/main/java/org/apache/geode/management/configuration/Region.java
geode-management/src/main/java/org/apache/geode/management/runtime/RuntimeInfo.java
geode-management/src/main/java/org/apache/geode/management/runtime/RuntimeRegionInfo.java
geode-management/src/test/java/org/apache/geode/cache/configuration/GroupableConfigurationTest.java
geode-management/src/test/java/org/apache/geode/management/api/ClusterManagementGetResultTest.java
geode-management/src/test/java/org/apache/geode/management/api/ConfigurationInfoTest.java
geode-management/src/test/java/org/apache/geode/management/configuration/RegionTest.java
geode-web-management/src/distributedTest/java/org/apache/geode/management/client/ConfigurePDXDUnitTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/HateoasIntegrationTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/MemberManagementServiceRestIntegrationTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/MemberManagementController.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RegionManagementController.java

GEODE-7699: use ConfigurationInfo to wrap the get result

---

geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionTest.java

* Throw TransactionDataRebalancedException during get operation
if bucket moved to other member.

GEODE-7713: Throw TransactionDataRebalancedException during get operation

---

geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySender.java
geode-core/src/test/java/org/apache/geode/internal/cache/wan/AbstractGatewaySenderTest.java

* Handle region is null in AbstractGatewaySender.getSynchronizationEvent

GEODE-7725: Handle region is null case

---

geode-core/src/test/java/org/apache/geode/internal/monitoring/executor/AbstractExecutorGroupJUnitTest.java

added awaits & better assertions

GEODE-7700: AbstractExecutorGroupJUnitTest lockOwnerThreadStackIsReported

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt

GEODE-7729: Upgrades JNA to 5.5.0

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt

Revert "GEODE-7729: Upgrades JNA to 5.5.0"

---

geode-core/src/distributedTest/java/org/apache/geode/distributed/LocatorDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/distributed/internal/membership/api/MembershipManagerHelper.java

GEODE-7731: fix the checking of the end state of test.

---

geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/ClientCQImpl.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/CqServiceImpl.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/ServerCQImpl.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/command/GetDurableCQs.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/ops/CreateCQOp.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/ops/GetDurableCQsOp.java

GEODE-7660: Code cleanup for cqs

---

geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/concurrent/ConcurrentWANPropagation_1_DUnitTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/concurrent/ConcurrentWANPropagation_2_DUnitTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderAlertThresholdDUnitTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderOperationsDUnitTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueueOverflowDUnitTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialWANPropagationDUnitTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialWANPropagationsFeatureDUnitTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialWANStatsDUnitTest.java

GEODE-7659: Removed unused wait parameter, fixed test listener pollution

---

geode-core/src/distributedTest/java/org/apache/geode/management/JMXMBeanReconnectDUnitTest.java

* Fix locators string delimiter
* Disable locator-to-locator MXBean validations that intermittently
demonstrate GEODE-7739

GEODE-7710: Fix JMXMBeanReconnectDUnitTest flakiness

---

geode-cq/src/distributedTest/java/org/apache/geode/cache/query/internal/QueryConfigurationServiceConstraintsDistributedTest.java

GEODE-7604: Fix QueryConfigurationServiceConstraintsDistributedTest
* Rewrite test with standard Geode and JMX APIs
* Rewrite CountingCqListener with AtomicIntegers
* Replace if-else with enum

GEODE-7604: Fix QueryConfigurationServiceConstraintsDistributedTest

---

geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/PutAllClientServerDistributedTest.java

The flakiness was already fixed in the previous commit. This PR just cleans up the test a bit more.

GEODE-7650: Cleanup PutAllClientServerDistributedTest

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionSingleHopDUnitTest.java

* No longer extending JUnit4CacheTestCase
* Remove all calls to sleep
* Use UniversalMembershipListenerAdapter with CountDownLatch to gate client
Also fixes GEODE-7116.

GEODE-6819: Fix PartitionedRegionSingleHopDUnitTest

---

geode-core/src/distributedTest/java/org/apache/geode/cache/ConnectionPoolDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DestroyEntryPropagationDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxy.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientUpdater.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientUpdateMessageImpl.java
geode-dunit/src/main/java/org/apache/geode/cache30/CertifiableTestCacheListener.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/cache/internal/JUnit4CacheTestCase.java

Cleaning the teardown approach
change to wait for event history to be correct.
getting rid of a timing issue

GEODE-7600-4: Further cleanup

---

dev-tools/release/README.md
dev-tools/release/commit_rc.sh
dev-tools/release/deploy_rc_pipeline.sh
dev-tools/release/finalize_release.sh
dev-tools/release/prepare_rc.sh
dev-tools/release/print_rc_email.sh
dev-tools/release/promote_rc.sh

mailing list thread: https://lists.apache.org/thread.html/r67fb7bf3a9d249a0f9566a46bbd5667105e0ba564db3674a878d66d9%40%3Cdev.geode.apache.org%3E
DO NOT MERGE unless consensus has been reached and/or a vote has passed on the dev list.  Until then, this PR is provided only as an exhibit of the changes being proposed.

GEODE-7716: geode-benchmarks src should be included in release artifacts

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/GatewayReceiverManagementDUnitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ListIndexManagementDUnitTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ListRegionManagementDunitTest.java
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-core/src/integrationTest/java/org/apache/geode/logging/internal/EntityInfoIntegrationTest.java
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/test/java/org/apache/geode/management/internal/api/ClusterManagementResultTest.java
geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java
geode-junit/src/main/java/org/apache/geode/test/junit/assertions/ClusterManagementGetResultAssert.java
geode-junit/src/main/java/org/apache/geode/test/junit/assertions/ClusterManagementListResultAssert.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementGetResult.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementListResult.java
geode-management/src/main/java/org/apache/geode/management/api/EntityGroupInfo.java
geode-management/src/main/java/org/apache/geode/management/api/EntityInfo.java
geode-management/src/test/java/org/apache/geode/management/api/ClusterManagementGetResultTest.java
geode-management/src/test/java/org/apache/geode/management/api/EntityGroupInfoTest.java
geode-management/src/test/java/org/apache/geode/management/api/EntityInfoTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/GatewayManagementIntegrationTest.java

* rename ConfigurationInfo to EntityInfo
* rename ConfigurationResult to EntityGroupInfo

GEODE-7724: class rename

---

ci/pipelines/images/jinja.template.yml
ci/pipelines/pull-request/jinja.template.yml

GEODE-7745:

---

ci/scripts/create_instance.sh

WIP to consolidate instance creation scripts for common CI between Geode main and native client.

GEODE-7740: Native Client enhancements to instance creation.

---

geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/ListGatewayCommand.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/StatusGatewaySenderCommand.java
geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/commands/ListGatewayCommandTest.java

GEODE-7757: show more detailed status for Gateway senders

---

geode-redis/src/main/java/org/apache/geode/redis/internal/executor/AbstractExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/SetExecutor.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/string/SetExecutorTest.java

GEODE-7758: Add unit test for SetExecutor

---

geode-docs/managing/statistics/setting_up_statistics.html.md.erb
geode-docs/reference/topics/gemfire_properties.html.md.erb

GEODE-7714: change docs about disabling statistics archiving

---

geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImplJUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImpl.java
geode-tcp-server/build.gradle
geode-tcp-server/src/main/java/org/apache/geode/distributed/internal/tcpserver/LocatorAddress.java
geode-tcp-server/src/test/java/org/apache/geode/distributed/internal/tcpserver/LocatorAddressTest.java

GEODE-7582: Update initlocator list

---

geode-core/src/distributedTest/java/org/apache/geode/management/JMXMBeanReconnectDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/JMXNotificationType.java
geode-core/src/main/java/org/apache/geode/management/internal/ManagementConstants.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/ManagementAdapter.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/ManagerMBean.java

* Reenable locator mbean federation validation in
JMXMBeanReconnectDUnitTest
* Fix federation of ManagerMXBean

GEODE-7739: Federate ManagerMXBean

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/GeodeClientClusterManagementSecurityTest.java
geode-management/src/main/java/org/apache/geode/management/internal/api/BaseManagementServiceBuilder.java

GEODE-7752: Fixed failing distributed tests for ClusterManagementService

---

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/PageableLuceneQueryResultsImpl.java

GEODE-7772: Simplify hasNext in PageableLuceneQueryResultsImpl

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ListIndexManagementDUnitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/test/java/org/apache/geode/management/internal/api/ClusterManagementResultTest.java
geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java
geode-junit/src/main/java/org/apache/geode/test/junit/assertions/ClusterManagementGetResultAssert.java
geode-junit/src/main/java/org/apache/geode/test/junit/assertions/ClusterManagementListResultAssert.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementListResult.java
geode-management/src/main/java/org/apache/geode/management/api/EntityGroupInfo.java
geode-management/src/main/java/org/apache/geode/management/api/EntityInfo.java
geode-management/src/test/java/org/apache/geode/management/api/ClusterManagementListResultTest.java
geode-management/src/test/java/org/apache/geode/management/api/EntityGroupInfoTest.java
geode-management/src/test/java/org/apache/geode/management/api/EntityInfoTest.java
geode-web-management/src/distributedTest/java/org/apache/geode/management/client/MemberManagementServiceDUnitTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/GatewayManagementIntegrationTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/HateoasIntegrationTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/MemberManagementServiceRestIntegrationTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/MemberManagementController.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RegionManagementController.java

GEODE-7717: ClusterManagementListResult should show a list of EntityInfo

---

geode-core/src/distributedTest/java/org/apache/geode/distributed/LocatorDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/InternalLocatorIntegrationTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheXmlGenerator.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/GMSQuorumChecker.java

GEODE-7760: NPE in Locator during auto-reconnect

---

geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/BucketRegionJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/DistributedRegionJUnitTest.java

GEODE-7683: introduce BR.cmnClearRegion

---

geode-membership/src/integrationTest/resources/log4j2.xml

GEODE-7792: configure logging for geode-membership integration tests

---

geode-redis/src/distributedTest/java/org/apache/geode/redis/MockSubscriber.java
geode-redis/src/distributedTest/java/org/apache/geode/redis/PubSubDUnitTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/PubSubTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/mocks/MockSubscriber.java
geode-redis/src/main/java/org/apache/geode/redis/GeodeRedisServer.java
geode-redis/src/main/java/org/apache/geode/redis/internal/Client.java
geode-redis/src/main/java/org/apache/geode/redis/internal/Coder.java
geode-redis/src/main/java/org/apache/geode/redis/internal/ExecutionHandlerContext.java
geode-redis/src/main/java/org/apache/geode/redis/internal/GeoCoder.java
geode-redis/src/main/java/org/apache/geode/redis/internal/PubSub.java
geode-redis/src/main/java/org/apache/geode/redis/internal/PubSubImpl.java
geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
geode-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
geode-redis/src/main/java/org/apache/geode/redis/internal/RedisDataType.java
geode-redis/src/main/java/org/apache/geode/redis/internal/Subscriber.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/AbstractExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PublishExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/SubscribeExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/UnsubscribeExecutor.java
geode-redis/src/main/resources/org/apache/geode/redis/internal/sanctioned-geode-redis-serializables.txt

Redis PUBLISH/SUBSCRIBE is described here: https://redis.io/topics/pubsub
This implementation introduces 3 new command classes to support this:
`SubscribeExecutor`, `PublishExecutor` and `UnsubscribeExecutor`. At a high
level, the flow is as follows:
- A Redis client issues a SUBSCRIBE command. The server maintains a list of
subscribed clients and associate channel(s) in the `Subscribers` class. A
subscribed `Client` uses Netty's notion of a `uniqueID` to identify itself
uniquely.
- When a client PUBLISHes a message on a channel, the publish 'event' uses an
`onMembers` function call to distribute the channel/message to all members.
Each member then publishes the message to any `Client`s registered on the
channel.
Points to note:
Redis pub/sub is not HA. i.e. A subscriber only receives …

GEODE-7778: Add PUBLISH, SUBSCRIBE and UNSUBSCRIBE Redis commands

---

geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/util/MergeLogsDistributedTest.java

GEODE-7791: fix MergeLogsDistributedTest

---

geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/ResourceManagerWithQueryMonitorDUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/QueryOp.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/DefaultQuery.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/ExecutionContext.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/QueryMonitor.java

Fixing a timing issue where we were not waiting long enough for a latch among other issues.

Geode 4263

---

geode-core/src/distributedTest/java/org/apache/geode/internal/tcp/TCPConduitDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/DistributedSystemMXBeanWithAlertsDistributedTest.java
geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java

GEODE-7727: modify sender thread to detect release of connection

---

geode-connectors/src/acceptanceTest/resources/org/apache/geode/connectors/jdbc/internal/postgres.yml
geode-connectors/src/acceptanceTest/resources/org/apache/geode/connectors/jdbc/postgres.yml

Fix for failing Postgres connector acceptance test

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/PubSubTest.java

GEODE-7798: Fix flaky PubSub test

---

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/LuceneListIndexCommand.java

GEODE-7773: remove redundant addAll command

---

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneRegionListener.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneServiceImpl.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/LuceneRegionListenerJUnitTest.java

GEODE-7770: remove unused cache reference

---

extensions/geode-modules/src/main/java/org/apache/geode/modules/session/bootstrap/AbstractCache.java

GEODE-7769: use parseFloat instead of valueOf

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/PubSubTest.java

GEODE-7798: Ignore PubSubTest until the flakiness can be removed

---

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/repository/serializer/ReflectionLuceneSerializer.java

GEODE-7774: Remove addAll in ReflectionLuceneSerializer

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt
geode-redis/build.gradle
geode-redis/src/integrationTest/java/org/apache/geode/redis/PubSubTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/mocks/MockSubscriber.java
geode-redis/src/main/java/org/apache/geode/redis/internal/AbstractSubscription.java
geode-redis/src/main/java/org/apache/geode/redis/internal/ChannelSubscription.java
geode-redis/src/main/java/org/apache/geode/redis/internal/ExecutionHandlerContext.java
geode-redis/src/main/java/org/apache/geode/redis/internal/PatternSubscription.java
geode-redis/src/main/java/org/apache/geode/redis/internal/Subscription.java
geode-redis/src/main/java/org/apache/geode/redis/internal/org/apache/hadoop/fs/GlobPattern.java

- Remove flusher execution in favor of just calling writeAndFlush
- Bump Netty to 4.1.45
- Correct response message depending on the type of subscription processing a PUBLISH

GEODE-7798: Fix flakiness in PubSubTest

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-redis/build.gradle
geode-redis/src/integrationTest/java/org/apache/geode/redis/GeoJUnitTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/SSLTest.java
geode-redis/src/main/java/org/apache/geode/redis/GeodeRedisServer.java

Enabling SSL for Redis-API

---

geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerImplTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerJUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/OpExecutorImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/PoolImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/ConnectionManager.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerImpl.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/OpExecutorImplJUnitTest.java

GEODE-6536: Added retry in borrowConnection/single hop

---

geode-docs/getting_started/setup_classpath.html.md.erb
geode-docs/rest_apps/setup_config.html.md.erb

GEODE-7815: Document setting a GEODE_HOME env variable

---

geode-core/build.gradle

[GEODE-7823](https://issues.apache.org/jira/browse/GEODE-7823)

GEODE-7823: eliminate org.junit unavailable compile error in IntelliJ

---

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/distributed/LuceneQueryFunction.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/distributed/LuceneQueryFunctionJUnitTest.java

GEODE-7771: change getting cache in getLuceneIndex

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/DeltaPropagationDUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/client/ClientRegionFactory.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ClientRegionFactoryImpl.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/PutAllClientServerDistributedTest.java

Revert fluent style usage of ClientRegionFactory in DeltaPropagationDUnitTest.
Revert fluent style API fix in ClientRegionFactory.
Revert fluent style usage of ClientRegionFactory in PutAllClientServerDistributedTest.

Revert fluent style API fix in ClientRegionFactory

---

geode-management/src/main/java/org/apache/geode/management/api/CommandType.java
geode-management/src/main/java/org/apache/geode/management/api/RestTemplateClusterManagementServiceTransport.java
geode-management/src/main/java/org/apache/geode/management/configuration/AbstractConfiguration.java
geode-management/src/main/java/org/apache/geode/management/configuration/Deployment.java
geode-management/src/main/java/org/apache/geode/management/internal/ClientClusterManagementService.java
geode-management/src/test/java/org/apache/geode/management/internal/ClientClusterManagementServiceTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/DeploymentManagementController.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/security/RestSecurityConfiguration.java
geode-web-management/src/main/webapp/WEB-INF/management-servlet.xml

Co-authored-by: Jinmei Liao <jliao@pivotal.io>

GEODE-7421: REST deployment of jar files to cluster

---

geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/functions/RegionCreateFunction.java
geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/functions/RegionCreateFunctionJUnitTest.java

GEODE-7842: Improve concurrent region creation

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/PubSubIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/mocks/MockBinarySubscriber.java
geode-redis/src/main/java/org/apache/geode/redis/internal/AbstractSubscription.java
geode-redis/src/main/java/org/apache/geode/redis/internal/ChannelSubscription.java
geode-redis/src/main/java/org/apache/geode/redis/internal/PatternSubscription.java
geode-redis/src/main/java/org/apache/geode/redis/internal/PubSub.java
geode-redis/src/main/java/org/apache/geode/redis/internal/PubSubImpl.java
geode-redis/src/main/java/org/apache/geode/redis/internal/Subscription.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PublishExecutor.java
geode-redis/src/test/java/org/apache/geode/redis/internal/PubSubImplJUnitTest.java

GEODE-7840: Redis pub/sub does not handle binary messages correctly

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/build.gradle
geode-core/build.gradle
geode-core/src/test/resources/expected-pom.xml
geode-gfsh/build.gradle
geode-lucene/build.gradle
geode-management/build.gradle

Adds compileOnly dependencies on annotation artifacts.

GEODE-7642: Removes warnings about missing annotations.

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifierTest.java

GEODE-7763: Do not exportValue if no clients are waiting for result

---

geode-pulse/build.gradle
geode-pulse/src/integrationTest/java/org/apache/geode/tools/pulse/controllers/PulseControllerJUnitTest.java
geode-pulse/src/integrationTest/java/org/apache/geode/tools/pulse/security/CustomSecurityConfigTest.java
geode-pulse/src/integrationTest/java/org/apache/geode/tools/pulse/security/DefaultSecurityConfigTest.java
geode-pulse/src/integrationTest/resources/pulse-authentication-custom.xml
geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/security/DefaultSecurityConfig.java
geode-pulse/src/main/webapp/WEB-INF/pulse-servlet.xml

GEODE-7815: add Pulse custom security profile test

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/RenameTest.java
geode-redis/src/main/java/org/apache/geode/redis/GeodeRedisServer.java
geode-redis/src/main/java/org/apache/geode/redis/internal/ExecutionHandlerContext.java
geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
geode-redis/src/main/java/org/apache/geode/redis/internal/RegionProvider.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/AuthExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RenameExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HashExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SetExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/GetExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/StringExecutor.java
geode-redis/src/main/resources/org/apache/geode/redis/internal/sanctioned-geode-redis-serializables.txt
geode-redis/src/test/java/org/apache/geode/redis/internal/ExecutionHandlerContextJUnitTest.java

Geode 7850: Implement Redis Rename Command

---

geode-management/src/main/java/org/apache/geode/management/runtime/OperationResult.java
geode-management/src/main/java/org/apache/geode/management/runtime/RebalanceResult.java

GEODE-7804: moved two methods up from RebalanceResult to OperationResult

---

geode-core/src/main/java/org/apache/geode/distributed/LocatorLauncher.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/api/MembershipLocator.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/locator/MembershipLocatorImpl.java
geode-tcp-server/src/distributedTest/java/org/apache/geode/distributed/internal/tcpserver/TcpServerProductVersionDUnitTest.java
geode-tcp-server/src/main/java/org/apache/geode/distributed/internal/tcpserver/HostAndPort.java
geode-tcp-server/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpServer.java
geode-tcp-server/src/test/java/org/apache/geode/distributed/internal/tcpserver/HostAndPortTest.java
geode-tcp-server/src/test/java/org/apache/geode/distributed/internal/tcpserver/TcpServerDependenciesTest.java
geode-tcp-server/src/test/java/org/apache/geode/distributed/internal/tcpserver/TcpServerJUnitTest.java

Cleaned up a distributedTest that no longer needs to reference
geode-core 7 moved it to the unit test source set.
Added additional tests.

GEODE-7867 Add more unit tests to geode-tcp-server

---

geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionManager.java
geode-core/src/main/java/org/apache/geode/distributed/internal/LonerDistributionManager.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/MemberMBeanBridge.java

Avoids having to check instanceof and cast to
ClusterDistributionManager in MemberMBeanBridge.

GEODE-7710: Add getRedundancyZone to DistributionManager

---

geode-cq/src/distributedTest/java/org/apache/geode/cache/query/internal/QueryConfigurationServiceConstraintsDistributedTest.java

Make sure the CQ is effectively running on the server before
continuing with the test execution to avoid races.

GEODE-7604: Fix Test Flakiness

---

geode-lucene/build.gradle
geode-lucene/src/test/resources/expected-pom.xml

lucene-core and geode-core are `api` not `implementation` dependencies.
- [X Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

GEODE-7893: Fix Analyzer dependency in geode-lucene

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/ListsIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/SortedSetsIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/StringsIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ExpireIntegrationTest.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/ExpirationExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/ExpireExecutor.java

GEODE-7895:Create integration tests for EXPIRE command in Redis Adapter

---

geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/PutAllClientServerDistributedTest.java

Subscription enabled must be true for the other subscription config
options on PoolFactory to do anything.
This does NOT fix GEODE-7812. I've submitted this as its own PR because I want it to merge to develop as a separate commit.

GEODE-7812: Fix PoolFactory usage in PutAllClientServerDistributedTest

---

geode-core/src/test/java/org/apache/geode/distributed/internal/InternalLocatorTest.java
geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/GfshCommandIntegrationTest.java

GEODE-7907: change test to use non-default jmx-manager-port

---

geode-assembly/src/integrationTest/java/org/apache/geode/tools/pulse/PulseSecurityConfigCustomProfileTest.java
geode-assembly/src/integrationTest/resources/pulse-authentication-custom.xml
geode-core/src/distributedTest/java/org/apache/geode/internal/tcp/CloseConnectionTest.java
geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
geode-core/src/main/java/org/apache/geode/management/internal/ManagementAgent.java
geode-docs/tools_modules/pulse/pulse-auth.html.md.erb

GEODE-7851: update docs on Pulse Authentication

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionSingleHopDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionSingleHopWithServerGroupDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/SingleHopStatsDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImplJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/QueueManagerJUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ClientMetadataService.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ClientPartitionAdvisor.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ExecuteRegionFunctionSingleHopOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/GetAllOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/InternalPool.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/PoolImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/PutAllOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/RemoveAllOp.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ServerRegionDataAccess.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ServerRegionProxy.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/SingleHopClientExecutor.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/SingleHopOperationCallable.java
geode-core/src/main/java/org/apache/geode/internal/cache/BucketAdvisor.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionHelper.java
geode-core/src/main/java/org/apache/geode/internal/cache/RegionMapOwner.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/FunctionExecutionNodePruner.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/RegionAdvisor.java

Cleanup some collection types and interfaces for PutAllOp and
PutAllClientServerDistributedTest.
This does NOT fix GEODE-7812. I'm submitting this as its own PR because I want it to be a separate commit.

GEODE-7812: Cleanup for PutAllOp

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/DeploymentManagementRedployDUnitTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalConfigurationPersistenceService.java
geode-core/src/main/java/org/apache/geode/internal/JarDeployer.java

GEODE-7902: fix flaky test

---

build.gradle
geode-assembly/build.gradle
gradle/standard-subproject-configuration.gradle

Also rev the versions of those plugins.

GEODE-7916: use updated gradle plugin declarations

---

geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java

GEODE-7864: Removed unused logConfigListeners in InternalLocator

---

geode-dunit/src/main/java/org/apache/geode/internal/cache/functions/TestFunction.java

GEODE-7864: Removed unused Arraylist vals in TestFunction

---

geode-dunit/src/main/java/org/apache/geode/cache/query/dunit/TestObject.java
geode-junit/src/main/java/org/apache/geode/internal/cache/PartitionedRegionTestHelper.java
geode-junit/src/main/java/org/apache/geode/security/query/data/QueryTestObject.java

GEODE-7864: Instance checks in equals methods

---

extensions/session-testing-war/src/main/java/org/apache/geode/modules/session/CommandServlet.java

GEODE-7864: Removed printStackTrace command.

---

geode-core/src/main/java/org/apache/geode/cache/EvictionAttributes.java

GEODE-7864: Remove boxed variable as it can never be null.

---

geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/result/model/ResultModel.java

GEODE-7864: Fixed javadocs params

---

geode-core/src/main/java/org/apache/geode/internal/cache/execute/ServerRegionFunctionExecutor.java
geode-dunit/src/main/java/org/apache/geode/cache/query/QueryTestUtils.java

GEODE-7864: Fixed queries with missing space.

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy

GEODE-7851: use the latest version of nimbus-jose-jwt.jar

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ExpireIntegrationTest.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/ExpireExecutor.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/general/ExpireExecutorJUnitTest.java

GEODE-7914: create missing unit test for Redis Module Expire Command

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientDataSerializerMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientInstantiatorMessage.java
geode-dunit/src/main/java/org/apache/geode/internal/cache/functions/TestFunction.java

GEODE-7864: Print contents of arrays correctly.

---

geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/ha/HARegionQueue.java

GEODE-7864: Prevent overflow during multiplication.

---

geode-redis/src/distributedTest/java/org/apache/geode/redis/RedisDistDUnitTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/PubSubIntegrationTest.java

GEODE-7904, GEODE-7870: Ignore flaky tests while they are being worked on

---

settings.gradle

add 1.12.0 to old versions

---

geode-redis/src/distributedTest/java/org/apache/geode/redis/PubSubDUnitTest.java

GEODE-7925: Add concurrency test to PubSubDUnitTest

---

geode-docs/reference/topics/gemfire_properties.html.md.erb

GEODE-7942: document enable-management-rest-service

---

geode-docs/configuring/running/cluster-management-service.html.md.erb
geode-docs/reference/topics/gemfire_properties.html.md.erb

GEODE-7156: add docs for security-auth-token-enabled-components

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/tier/sockets/ConnectionProxyJUnitTest.java

I was taking a look to `ConnectionProxyJUnitTest` and I realized that `verifyAckSend`and `verifyExpiry`methods were not using their `timeToWait` parameter, so in fact they were using the default `GeodeAwaitability` timeout value (5 minutes).
I changed that and then I realized different calls to both methods were using different timeouts. And the one used for `verifyExpiry` in `testPeriodicAckSendByClient` was causing the test to fail, so I decided to homogenize calls to the same method, using a common timeout (the two new Duration objects in the class).
And finally I removed the usage of deprecated `WaitCriterion` class.

GEODE-7892: Code improvements in ConnectionProxyJUnitTest

---

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TCPClientSSLIntegrationTest.java
geode-tcp-server/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpClient.java

GEODE-7917: change thrown exception type for SSL to IOException

---

geode-core/src/main/java/org/apache/geode/admin/internal/ManagedSystemMemberImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/FilterProfile.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/BatchDestroyOperation.java
geode-core/src/main/java/org/apache/geode/pdx/internal/AutoSerializableManager.java
geode-junit/src/main/java/org/apache/geode/management/internal/cli/commands/CommandAvailabilityIndicatorTestHelper.java

GEODE-7864: Remove null checks that are not required.(Part 2)

---

geode-junit/src/main/java/org/apache/geode/internal/jta/CacheUtils.java

GEODE-7864: Closing the query statements after execution.

---

geode-core/src/main/java/org/apache/geode/internal/AbstractConfig.java
geode-core/src/main/java/org/apache/geode/internal/cache/BucketAdvisor.java
geode-core/src/main/java/org/apache/geode/internal/cache/DestroyPartitionedRegionMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistTXCommitMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistTXPrecommitMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistTXRollbackMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXCommitMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/BecomePrimaryBucketMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/DeposePrimaryBucketMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/FetchPartitionDetailsMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/MoveBucketMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/RemoveBucketMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/SizeMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/tx/RemoteSizeMessage.java
geode-core/src/main/java/org/apache/geode/internal/statistics/ArchiveSplitter.java
geode-core/src/main/java/org/apache/geode/internal/tcp/ImmutableByteBufferInputStream.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/filesystem/FileInputStream.java

GEODE-7864: Prevented non synchronized override of synchronized methods.

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt
geode-assembly/src/integrationTest/resources/expected_jars.txt

it's been a little while since Spring was last updated.  pull in latest on develop now before next support branch cut looms.

GEODE-7970: bump spring to latest

---

geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PersistentBucketRecoverer.java

Authored-by: Jianxia Chen <jchen21@apache.org>

GEODE-7945: Replace Map with ConcurrentMap for GemFireCacheImpl.rootRegions

---

geode-management/src/main/java/org/apache/geode/management/configuration/HasFile.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/DeploymentIntegrationTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/DeploymentManagementController.java
geode-web-management/src/test/java/org/apache/geode/management/internal/rest/controllers/DeploymentManagementControllerTest.java

* update the swagger do to be specific about the param description.

GEODE-7976: make "config" param optional when deploy using CMS.

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ExpireAtIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/DummySubscription.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/SubscriptionsIntegrationTest.java
geode-redis/src/main/java/org/apache/geode/redis/internal/Subscriptions.java
geode-redis/src/test/java/org/apache/geode/redis/internal/SubscriptionsTest.java

GEODE-7943 add synchronization to Subscriptions class

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/GeoIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/SetsIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/StringsIntegrationTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/set/SetExecutorJUnitTest.java

GEODE-7978: Improve tests for Redis Module SREM Command

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/GeoIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/SetsIntegrationTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/set/SetExecutorJUnitTest.java

Revert "GEODE-7978: Improve tests for Redis Module SREM Command"

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/client/sni/ClientSNIAcceptanceTest.java
geode-assembly/src/acceptanceTest/java/org/apache/geode/client/sni/ClientSNICQAcceptanceTest.java
geode-assembly/src/acceptanceTest/resources/org/apache/geode/client/sni/scripts/geode-starter.gfsh

GEODE-7852: Create simple CQ over SNI test.

---

geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedAckRegionCCEDUnitTest.java

GEODE-7761: change Ignore description

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/NetSearchMessagingDUnitTest.java

Adding debug logging to try and track this down via the mass test run.

Geode 7474: NetSearchMessagingDUnitTest.testNetSearchFailoverFromReplicate fails

---

geode-docs/tools_modules/pulse/pulse-auth.html.md.erb
geode-pulse/src/main/resources/pulse.properties

GEODE-7851: Document Pulse OAuth properties

---

geode-core/src/main/java/org/apache/geode/internal/cache/control/RebalanceResultsImpl.java
geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/RebalanceMembersColocationTest.java

GEODE-7980: update rebalance output on colocated region

---

boms/geode-all-bom/build.gradle
gradle/publish-artifacts.gradle
gradle/publish-common.gradle
gradle/publish-java.gradle
gradle/publish-war.gradle

Don't Repeat Yourself refactor.

GEODE-7984: Refactor Gradle scripts for publishing well-formed POM files

---

geode-core/src/main/java/org/apache/geode/distributed/internal/ServerLocator.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/rebalance/model/PartitionedRegionLoadModel.java
geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/rebalance/PartitionedRegionLoadModelJUnitTest.java

GEODE-7864: Prevent implicit narrowing.

---

geode-redis/src/acceptanceTest/java/org/apache/geode/redis/ExistsDockerAcceptanceTest.java
geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/ExistsDUnitTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ExistsIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ExpireIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/general/PersistIntegrationTest.java
geode-redis/src/main/java/org/apache/geode/redis/internal/RegionProvider.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/ExistsExecutor.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/general/ExistsExecutorJUnitTest.java

The Redis EXISTS command verifies that a key exists (https://redis.io/commands/exists).  The EXISTS command was previously implemented, but not tested. This PR adds tests and fixes implementation for this command.

GEODE-7992: Implement a test class for the EXISTS Redis API command

---

geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/MSetExecutor.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/general/ExpireAtExecutorJUnitTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/general/ExpireExecutorJUnitTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/general/PExpireAtExecutorJUnitTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/set/SetExecutorJUnitTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/string/DelExecutorJUnitTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/string/GetRangeExecutorJUnitTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/string/GetSetExecutorJUnitTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/string/IncrExecutorJUnitTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/string/StringGetExecutorJUnitTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/string/StringMGetExecutorJUnitTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/string/StringMSetExecutorJUnitTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/string/StringSetExecutorJUnitTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/executor/string/StrlenExecutorJUnitTest.java

GEODE-8000: Test refactor command mocks

---

geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientTestCase.java

- Added to awaits where they seemed needed
- Cleaned out runnables

GEODE-5428

---

geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupService.java

Log as warning exception that causes backup execution to fail

GEODE-7989: Improve backup exceptions logging

---

geode-redis/src/acceptanceTest/java/org/apache/geode/redis/ExpireAtNativeRedisAcceptanceTest.java
geode-redis/src/acceptanceTest/java/org/apache/geode/redis/ExpireNativeRedisAcceptanceTest.java
geode-redis/src/acceptanceTest/java/org/apache/geode/redis/GeoNativeRedisAcceptanceTest.java
geode-redis/src/acceptanceTest/java/org/apache/geode/redis/HashesNativeRedisAcceptanceTest.java
geode-redis/src/acceptanceTest/java/org/apache/geode/redis/ListsNativeRedisAcceptanceTest.java
geode-redis/src/acceptanceTest/java/org/apache/geode/redis/PersistNativeRedisAcceptanceTest.java
geode-redis/src/acceptanceTest/java/org/apache/geode/redis/PexpireNativeRedisAcceptanceTest.java
geode-redis/src/acceptanceTest/java/org/apache/geode/redis/PubSubNativeRedisAcceptanceTest.java
geode-redis/src/acceptanceTest/java/org/apache/geode/redis/RenameNativeRedisAcceptanceTest.java
geode-redis/src/acceptanceTest/java/org/apache/geode/redis/SetsNativeRedisAcceptanceTest.java
geode-redis/src/acceptanceTest/java/org/apache/geode/redis/SortedSetNativeRedisAcceptanceTest.java
geode-redis/src/acceptanceTest/java/org/apache/geode/redis/StringsNativeRedisAcceptanceTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/HashesIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/StringsIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/general/PersistIntegrationTest.java

GEODE-7994: Refactor Native Redis Acceptance Tests

---

geode-redis/src/main/java/org/apache/geode/redis/internal/ExecutionHandlerContext.java

GEODE-8010: message is now debug instead of info

---

.asf.yaml

(cherry picked from commit 87e17289860a4add30c81d226158020bd2d4900a)
I just need approvals and checks to pass so I can merge this change.

GEODE-8006 Add .asf.yaml to control notifications

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/GridAdvisorDUnitTest.java

This test just needed some awaits added to allow the test to retry.

GEODE-7935: Awaiting for verification steps.

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/ClientMetadataService.java
geode-core/src/main/java/org/apache/geode/distributed/internal/AbstractDistributionConfig.java
geode-core/src/main/java/org/apache/geode/internal/SystemAdmin.java
geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/InitialImageOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/PoolManagerImpl.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMembershipView.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocator.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java

GEODE-7864: Removing null checks that are not required.(Part 1)

---

geode-docs/managing/logging/configuring_log4j2.html.md.erb
geode-docs/tools_modules/gfsh/command-pages/change.html.md.erb
geode-logging/src/main/java/org/apache/geode/logging/internal/log4j/api/FastLogger.java

For reference, link to the conversation on dev list: https://markmail.org/thread/a6gobaphywmkm7gq

Logging documentation fixes

---

geode-pulse/src/integrationTest/java/org/apache/geode/tools/pulse/security/OAuthSecurityTokenHandoffTest.java
geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/controllers/PulseController.java
geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/data/Cluster.java
geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/data/Repository.java
geode-pulse/src/main/webapp/scripts/pulsescript/common.js

If a user's access token expires, Pulse attempts to refresh it. If the
refresh fails, Pulse logs the user out and redirects the browser to
/pulse/clusterLogout.
Changes in Repository:
- When OAuth is configured, before returning the user's cluster,
getCluster() checks whether the user's access token has expired.
- If the access token has expired, the repository attempts to refresh
it.  If the refresh succeeds, the repository reconnects the user's
cluster to JMX and returns it.
- If the refresh fails, the repository disconnects the user's cluster
from JMX, removes the cluster from the repository, and throws an
authentication or authorization exception.
Changes in PulseController:
- If the service call throws an authentication or authorization
exception, PulseController.  getPulseUpdate() …

GEODE-7851: Pulse refreshes expired access tokens

---

geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeCreateGatewaySenderMixedSiteOneCurrentSiteTwo.java

test assumed old version and current version will always be incompatible, but on a support branch, old version can be 1.12.0 and current can be 1.12.1 which both have the same serialization version, so changed the test to expect success rather than failure when major and minor are same

GEODE-8024: fix wan test to also work on support branches

---

geode-management/src/test/script/update-management-wiki.sh

- Documentation page will now include the raw swagger json
- This json file can be used to generate clients for the management API

GEODE-8027: documentation script to attach swagger json

---

geode-docs/tools_modules/redis_adapter.html.md.erb

GEODE-7981: fixed docs for redis PARTITION_REDUNDANT

---

geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/QueueManagerJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/pooling/AvailableConnectionManagerConcurrentTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/CacheDistributionAdvisorConcurrentTest.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/ConnectionManager.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/OpExecutorImplJUnitTest.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/pooling/AvailableConnectionManagerTest.java

This PR depends on #4924 being merged to develop first. (This commit used to be in #4924).

GEODE-7964: Fixup all tests touched for Mockito upgrade

---

geode-core/src/main/java/org/apache/geode/internal/net/BufferPool.java
geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
geode-core/src/test/java/org/apache/geode/internal/net/BufferPoolTest.java
geode-core/src/test/java/org/apache/geode/internal/net/NioPlainEngineTest.java
geode-core/src/test/java/org/apache/geode/internal/net/NioSslEngineTest.java

WIP
Created two buffer pools with fixed buffer capacity (according to test results), small (4096), and middle (32768).
submit an update to your PR as soon as possible. If you …

GEODE-6636: Create multiple buffer pools
