.github/PULL_REQUEST_TEMPLATE.md, BUILDING.md, README.md, build.gradle
* Better IntelliJ integration via 'Before Executing' triggers with
Gradle.
* Added screenshot of IntelliJ configuration.
* Replaced old Travis badge with Concourse
* Remove stale reference to Travis in PR template, replace with
concourse
* Grammar fixes in README
=> GEODE-6513: Revised README and BUILDING

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/RebalanceCommandDUnitTest.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/RebalanceCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/result/model/ResultModel.java
=> GEODE-5971: refactor RebalanceCommand to use ResultModel

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/AlterRegionCommand.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/AlterRegionCommandTest.java
GEODE-6550: Use cache-writer in AlterRegionCommand
- Parameter `cache-writer`, instead of `cache-loader`, is now used to
configure the internal `CacheWriter` for the region.
=> GEODE-6550: Use cache-writer in AlterRegionCommand

extensions/geode-modules-session/build.gradle, geode-connectors/build.gradle, geode-connectors/src/test/resources/expected-pom.xml, geode-core/build.gradle, geode-core/src/test/resources/expected-pom.xml, geode-junit/src/test/resources/expected-pom.xml, geode-redis/build.gradle, geode-redis/src/test/resources/expected-pom.xml, geode-web-api/build.gradle, geode-web-management/build.gradle, geode-web/build.gradle, gradle/publish.gradle
* Using implementation or api where appropriate in geode-core
dependencies. This allows downstream consumers of geode-core to get this
dependencies as runtime dependencies instead of compile.
* Adding first order dependencies to other subprojects that needed them.
* Removing a couple of dependencies from geode-core that we were only
using transitively.
*  Adding comments to geode-core dependencies
=> GEODE-6532: Using implementation/api in geode-core instead of compile

geode-core/src/distributedTest/java/org/apache/geode/management/internal/configuration/ClusterConfigServerRestartWithJarDeployDUnitTest.java, geode-core/src/distributedTest/resources/ClusterConfigServerRestartWithJarDeployFunction.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java, geode-core/src/main/java/org/apache/geode/internal/JarDeployer.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/messages/ConfigurationResponse.java, geode-core/src/main/java/org/apache/geode/pdx/internal/PeerTypeRegistration.java, geode-dunit/src/main/java/org/apache/geode/management/internal/configuration/ClusterConfigTestBase.java, geode-dunit/src/main/java/org/apache/geode/test/junit/rules/MemberStarterRule.java, geode-dunit/src/main/java/org/apache/geode/test/junit/rules/ServerStarterRule.java, geode-junit/src/integrationTest/java/org/apache/geode/test/compiler/JarBuilderTest.java, geode-junit/src/main/java/org/apache/geode/test/compiler/JarBuilder.java
- Currently configuring PDX, via gfsh, does not work correctly in
conjunction with this rule.
=> GEODE-6559: PdxInstance.getObject() is using class from older jar in case of Reconnect

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/versions/TombstoneDUnitTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/entries/AbstractRegionEntry.java
During destroy entry (tombstone) under region entry lock, if the
entry had a lower region version than the recorded gc version for
that member, the entry was removed immediately which could result
in dead-lock with tombstone gc thread.
Instead of removing the entry during destroy, it was scheduled to
remove during tombstone gc.
Please …
=> GEODE-6526: Removing call to removeTombstone during entry destroy

geode-core/src/integrationTest/java/org/apache/geode/cache/CacheFactoryIntegrationTest.java, geode-core/src/main/java/org/apache/geode/cache/CacheFactory.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalCacheBuilder.java, geode-core/src/main/java/org/apache/geode/metrics/MetricsPublishingService.java, geode-core/src/main/java/org/apache/geode/metrics/MetricsSession.java, geode-core/src/test/java/org/apache/geode/internal/cache/InternalCacheBuilderTest.java
Provides an API to add meter registries to the cache's composite
registry for publishing cache metrics to external monitoring systems.
Update the Javadocs of all metrics APIs.
Please review: @demery-pivotal @mhansonp
=> GEODE-6558: Add addMeterSubregistry to CacheFactory

gradle/java.gradle
Removal of a bad `doLast` around the insertion of the default NOTICE,
only if the module did not have its own file
=> GEODE-5604: Fix over-zealous fix for adding NOTICE to jar manifest

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifierIntegrationTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionMetricsTest.java, geode-junit/src/main/java/org/apache/geode/test/fake/Fakes.java
* Add cache.region.operations.puts create timer.
* Add cache.region.operations.puts put timer.
* Add cache.region.operations.puts put-if-absent timer.
* Add cache.region.operations.puts replace timer.
* Add cache.region.operations.gets get timer.
* Add cache.region.operations.gets get-entry timer.
* Add cache.region.operations.contains containsKey timer.
* Add cache.region.operations.contains containsValue timer.
* Add cache.region.operations.contains containsKeyOnServer timer.
* Add cache.region.operations.contains containsValueForKey timer.
Please review: @demery-pivotal @mhansonp 
Includes:
```
commit 30c1c4af10fb962f19b6f0ddd23ded2de4c808cc …
```
=> GEODE-6529: Add timers for LocalRegion operations

geode-core/src/integrationTest/java/org/apache/geode/pdx/internal/MultipleCacheJUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java
This change prevents startLocator from creating two DistributedSystem connections when ALLOWS_MULTIPLE_SYSTEMS is true.
=> GEODE-6562: Inject new DistributedSystem into Locator Cache

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/InternalDistributedSystemSecurityIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/security/SecurityManagerLifecycleIntegrationTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java, geode-core/src/main/java/org/apache/geode/internal/security/IntegratedSecurityService.java, geode-lucene/src/distributedTest/java/org/apache/geode/cache/lucene/LuceneClientSecurityDUnitTest.java
IntegratedSecurityService needs to be closed when InternalDistributedSystem is disconnected and no cache was ever created.
Invoke IntegratedSecurityService.close() during InternalDistributedSystem.disconnect().
Make IntegratedSecurityService.close() idempotent so that subsequent invocations are ignored. (Without this other tests that verify number of invocations of close() will fail).
Fix LuceneClientSecurityDUnitTest: The base class overrides getDistributedSystemProperties() so startCacheServer needs to use compatible properties when it invokes getCache(Properties).
=> GEODE-6565: Close IntegratedSecurityService during disconnect

geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/HistoryCommandIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/shell/GfshHistoryJUnitTest.java, geode-core/src/main/java/org/apache/geode/internal/util/ArgumentRedactor.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/Launcher.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/shell/Gfsh.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/shell/jline/GfshHistory.java
- Remove redact method in GfshHistory in favor of
ArgumentRedactor.redact
Co-authored-by: Donal Evans <donalevans86@gmail.com>
=> GEODE-4318: Ensure that passwords are correctly redacted in the gfsh history file

build.gradle, gradle/rat.gradle
Prevents rat from running for every 'subproject:check'. Will only run
for 'check' or ':check'.
=> Don't rat on every subproject.

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/InternalDistributedSystemBuilderForTestingIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/InternalDistributedSystemBuilderIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/InternalDistributedSystemJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitorJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessengerJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/mgr/GMSMembershipManagerJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/pdx/internal/MultipleCacheJUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalCacheBuilder.java, geode-core/src/test/java/org/apache/geode/distributed/internal/InternalDistributedSystemIntegrationTest.java, geode-core/src/test/java/org/apache/geode/distributed/internal/InternalDistributedSystemStatisticsManagerTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/GemFireCacheImplTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/InternalCacheBuilderAllowsMultipleSystemsTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/InternalCacheBuilderTest.java
* Remove all but one constructor.
* Replace newInstance methods with InternalDistributedSystem.Builder.
* Replace newInstanceForTesting methods with
InternalDistributedSystem.BuilderForTesting.
* Replace public static boolean var ALLOW_MULTIPLE_SYSTEMS with usage
of Boolean.getBoolean(ALLOW_MULTIPLE_SYSTEMS_PROPERTY) in
connectInternal.
Most code paths are using DistributedSystem.connect or
InternalDistributedSystem.connectInternal to construct a system.
connectInternal now uses InternalDistributedSystem.Builder.
Several tests are using  InternalDistributedSystem.BuilderForTesting.
NOTES FOR REVIEWERS (PLEASE READ):
NOTE: this is NOT the final refactoring/change to InternalDistributedSystem involving the Builder. We need to make some changes to reconnect for Micrometer. We will also be …
=> GEODE-6558: Add InternalDistributedSystem.Builder

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ManagementRequestLoggingDUnitTest.java, geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/rest/controllers/ClusterManagementRestLoggingTest.java, geode-core/src/test/java/org/apache/geode/cache/configuration/RegionConfigTest.java, geode-management/src/main/java/org/apache/geode/cache/configuration/RegionConfig.java, geode-management/src/main/java/org/apache/geode/management/internal/ClientClusterManagementService.java, geode-web-management/src/main/java/org/apache/geode/management/internal/rest/ManagementLoggingFilter.java
=> GEODE-6443: log all request and response in geode management service

geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/locks/GrantorRequestProcessor.java
Changes a couple of comments to call objects 'it' instead of 'he'.
=> GEODE-5683: remove unnecessarily gendered language

geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
There was lock contention for checking if the clientMetadataService
needed to be initialized. The object is not expensive to construct, so
the initialization has been moved the GemFireCacheImpl's constructor,
allowing the lock object to be removed completely.
=> GEODE-6577: performance gain by removing lazy init

geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
Use a ConcurrentHashMap instead of a HashMap accessed in synchronized
blocks to store host names in SocketCreator. This reduces lock
contention for getting host names by reducing the amount of time spent
holding the lock.
=> GEODE-6580: use ConcurrentHashMap for host names

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/DiskRandomOperationsAndRecoveryJUnitTest.java, geode-core/src/main/java/org/apache/geode/cache/DynamicRegionFactory.java, geode-core/src/main/java/org/apache/geode/internal/cache/AbstractBucketRegionQueue.java, geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/HARegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueue.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderQueue.java, geode-core/src/test/java/org/apache/geode/internal/cache/event/DistributedEventTrackerTest.java
Cleanup LocalRegion:
* Reduce scope of methods and fields
* Remove unused methods and fields
* Replace deprecated call with undeprecated call
* Remove redundant interface
* Apply FunctionalInterface annotation to nested interfaces
=> GEODE-6534: Reduce scope of LocalRegion methods

geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerJUnitTest.java
The test was using System.currentTimeMillis to verify that
the product has blocked for as long as expected.
But the product is using System.nanoTime.
This can cause race conditions because these two different
clocks can be updated at different times.
The test now also uses System.nanoTime.
Also removed some dead test code.
=> GEODE-6593: fix test elapsed time computation

boms/geode-all-bom/src/test/resources/expected-pom.xml, buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy, geode-core/build.gradle, geode-core/src/distributedTest/java/org/apache/geode/management/QueryPdxDataDUnitTest.java, geode-core/src/distributedTest/resources/org/apache/geode/management/Address.java, geode-core/src/distributedTest/resources/org/apache/geode/management/Customer.java
- This test ensures that the classes, backing PDX instance objects are
created dynamically.
=> GEODE-6430: Add test to query PDX-based entries from gfsh

geode-core/src/distributedTest/java/org/apache/geode/internal/alerting/AlertingServiceWithoutListenerDistributedTest.java, geode-core/src/main/java/org/apache/geode/internal/admin/remote/AlertListenerMessage.java
Implement the test alertMessageIsReceivedByManager correctly. The
Manager VM should receive the AlertListenerMessage and its message
should match the alert message.
=> GEODE-6598: Fix alertMessageIsReceivedByManager test

geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/RegionAlterFunction.java, geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/RegionAlterFunctionTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/misc/WanValidationsDUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/AlterRegionCommandDUnitTest.java
GEODE-6551: Fix Constraints Check in Alter Region
Some persistence constraints were not correctly validated for a
partitioned region before associating an async-event-queue and/or
gateway-sender, leaving the region and the cluster configuration
service inconsistent.
- Fixed the internal validation implemented by PartitionedRegion.
- Some method's signatures were changed from "parallelGatewaySender" to
"parallelAsynchronousEventDispatcher" as they are used alike for
both a gateway-sender and async-event-queue.
submit an …
=> GEODE-6551: Fix Constraints Check in Alter Region

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/Message.java
The max message size did not change over the course of execution but was
being re-fetched every time a new message was constructed. To improve
message performance, this value is now static and fetched only once.
=> GEODE-6582: get max message size only once

geode-pulse/build.gradle, gradle/spotless.gradle, gradle/standard-subproject-configuration.gradle
* geode-pulse missing evaluation dependency on geode-core
* remove implicit evaluation dependency in spotless.gradle on geode-core.
* move hook of spotlessApply into spotless.gradle
- [nope] Have you written or updated unit tests to verify your changes?
email to …
=> GEODE-6383: Correct minor lingering issues from previous PR.

geode-core/src/main/java/org/apache/geode/internal/metrics/CacheLifecycleMetricsSession.java, geode-core/src/main/java/org/apache/geode/internal/util/CollectingServiceLoader.java, geode-core/src/main/java/org/apache/geode/internal/util/ListCollectingServiceLoader.java, geode-core/src/test/java/org/apache/geode/internal/metrics/CacheLifecycleMetricsSessionTest.java, geode-core/src/test/java/org/apache/geode/internal/util/ListCollectingServiceLoaderTest.java
Catch and log Errors and RuntimeExceptions thrown from instantiation
of or calls to MetricsPublishingService implementations.
Please review: @demery-pivotal @mhansonp
=> GEODE-6609: Protect from MetricsPublishingService exceptions

geode-assembly/build.gradle
* A previous commit under this ticket was too aggressive in project evaluation dependencies.  Explicit > Implicit.
-----
`evaluationDependsOn` is a bit of a code smell in any case, and we should work towards better modularity / less cross-project reliance in any case.  But that is Future Work (tm) (r) (c).
-----
- [nope] Have you written or updated unit tests to verify your changes?
Please ensure that once the PR is submitted, check …
=> GEODE-6383: Be explicit in evaluation dependencies.

geode-docs/reference/topics/gemfire_properties.html.md.erb
Add documentation for three parameters already added in code: 
- `thread-monitor-enabled`
-  `thread-monitor-interval-ms`
- `thread-monitor-time-limit-ms`
Also tweaked a format for another entry in the same table (geode.disallow-internal-messages-without-credentials)
=> GEODE-5142: User Guide - document thread monitoring options

geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/GfshCommandIntegrationTest.java
- Honestly this is just a workaround as it's more likely that some
lingering, existing process is causing this to fail.
=> GEODE-6643: Fix intermittent failure of GfshCommandIntegrationTest on Windows

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentRVVRecoveryDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentRecoveryOrderDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentRecoveryOrderOldConfigDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentReplicatedTestBase.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/TombstoneService.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/AsyncInvocation.java
* Fix all future await times to use GeodeAwaitility timeout
* Fix testRevokeAHostBeforeInitialization dependency on etc hosts
* Fix testCrashDuringPreparePersistentId flakiness caused by using
wrong await timeouts
=> GEODE-1703: Fix PersistentRecoveryOrderDUnitTest time based flakiness

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionTest.java
* AuthenticationRequiredException is now caught and logged instead of an uncaught exception
* Lowering the log level to warn from error when this exception occurs.
=> GEODE-4958: Lowering the log level to warn

geode-web/src/main/java/org/apache/geode/management/internal/web/http/converter/ServerSerializableObjectHttpMessageConverter.java
* There is a possibility that type can be null, which is handled in the return statement.
* Similar checks were placed in the logger trace statement.
=> GEODE-6557:Handling a possible null situation.

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentRVVRecoveryDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentRecoveryOrderDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentRecoveryOrderOldConfigDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentReplicatedTestBase.java, geode-core/src/main/java/org/apache/geode/internal/cache/TombstoneService.java
Fix additional minor timing issues related to these tickets:
GEODE-1703 GEODE-4267 GEODE-4378 GEODE-5231 GEODE-6375 GEODE-6615
I found a few more places where awaiting the disconnect that was invoked within a DistributionObserver would be a good idea. I also changed the deleteDirectory in setUp and tearDown to deleteQuietly. And I made sure getCache() is invoked before creating disk dirs to be used to create a diskStore for that cache. I think the await is the primary fix that'll prevent problems but the other two may help.
=> GEODE-5231: Fix PersistentReplicatedTestBase subclass flakiness

geode-core/src/main/java/org/apache/geode/internal/cache/BucketAdvisor.java
Since that value can change immediately after we exit these methods,
unless we already have the monitor, we can safely read the current value
with the same staleness guarantee when exiting the method. Lock still
acquired for composite checks and updating the value.
This change measures a 17% increase in throughput in PartitionedFunctionExecutionBenchmark.
=> GEODE-6694: Use volatile access to read current state of BucketAdvisor

geode-concurrency-test/build.gradle, geode-concurrency-test/src/integrationTest/java/org/apache/geode/test/concurrency/ConcurrentTestRunnerTest.java, geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/loop/LoopRunner.java
Run the concurrency test runner for longer by default to increase the
chance of catching issues, and move runner's tests to the integration
level since they are non-deterministic.
=> GEODE-6693: run concurrency tests for longer

geode-core/src/main/java/org/apache/geode/internal/Version.java
Due to a typo, the minor version was left at 9 in the version class.
=> Fixing the minor version byte for Version.GEODE_1_10_0

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Put65.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/Put65Test.java
The StringBuilder creation is now only done when key or region is null.
=> GEODE-6674: only create StringBuilder if needed

geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/InternalDistributedMember.java
InternalDistributedMember now uses readInt instead of readInteger
to prevent an object creation.
Note that readInteger is implemented by calling readInt so this change is safe.
I will probably need to update this pull request to update the tests with the new fromData checksum.
=> GEODE-6688: prevent Integer allocation in InternalDistributedMember deserialization

geode-core/src/main/java/org/apache/geode/internal/cache/DistributedCacheOperation.java
DistributedCacheOperation._distribute is now careful to only create a HashSet
if it will not be empty.
=> GEODE-6673: remove unneeded HashSet creations

ci/images/test-container/Dockerfile, ci/pipelines/geode-build/deploy_pipeline.sh, ci/pipelines/images/jinja.template.yml
Previously used Debian `sid`, which has had openjdk-8 removed by the
maintainers.
=> Use Ubuntu Bionic as the test-container base

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ServerRestartTest.java, geode-core/src/distributedTest/java/org/apache/geode/management/JMXMBeanReconnectDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/RegionChangesPersistThroughClusterConfigurationDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/management/internal/configuration/ClusterConfigServerRestartWithJarDeployDUnitTest.java, geode-dunit/src/main/java/org/apache/geode/distributed/internal/membership/gms/MembershipManagerHelper.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/MemberVM.java, geode-dunit/src/main/java/org/apache/geode/test/junit/rules/LocatorStarterRule.java, geode-dunit/src/main/java/org/apache/geode/test/junit/rules/MBeanServerConnectionRule.java, geode-dunit/src/main/java/org/apache/geode/test/junit/rules/MemberStarterRule.java, geode-dunit/src/main/java/org/apache/geode/test/junit/rules/ServerStarterRule.java
=> GEODE-6561: When a test server is forced to shutdown, do not save cache xml if use cluster config

geode-core/src/jmh/java/org/apache/geode/internal/logging/log4j/FastLoggerDisabledLevelBenchmark.java, geode-core/src/jmh/java/org/apache/geode/internal/logging/log4j/FastLoggerEnabledLevelBenchmark.java, geode-core/src/jmh/java/org/apache/geode/internal/logging/log4j/FastLoggerParameterTypeBenchmark.java
I'd like to merge these FastLogger benchmarks to develop:
* **FastLoggerDisabledLevelBenchmark** compares FastLogger vs Logger for log statements at a disabled level (ie, debug level when current log level is info).
* **FastLoggerEnabledLevelBenchmark** compares FastLogger vs Logger for log statements at an enabled level (ie, info level when current log level is info).
* **FastLoggerParameterTypeBenchmark** compares FastLogger vs Logger for various types of parameters at an enabled level (ie, info level when current log level is info).
Please review: @demery-pivotal @mhansonp @aaronlindsey @moleske @pivotal-jbarrett 
You can run a single JMH Benchmark class using:
```
$ ./gradlew geode-core:jmh -Pinclude=".*FastLoggerDisabledLevelBenchmark.*"
```
The numbers fluctuate from run-to-run, but …
=> GEODE-6720: Add FastLogger benchmarks

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/InternalDistributedMember.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/InternalDistributedMemberTest.java
The compareTo implementation needs to get the InetAddress as a byte array
which causes to byte array allocations.
By changing InternalDistributedMember.equals to not call compareTo InetAddress.equals
can be used instead which prevents the byte array allocations.
=> GEODE-6702: optimize equals by not calling compareTo

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RegionManagementOnMultipleGroup.java, geode-core/src/integrationTest/java/org/apache/geode/management/internal/configuration/realizers/RegionConfigRealizerIntegrationTest.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/realizers/RegionConfigRealizer.java, geode-junit/src/main/java/org/apache/geode/test/junit/assertions/ClusterManagementResultAssert.java
=> GEODE-6174: RegionConfigRealizer should be idempotent for create

geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/PulseAppListener.java, geode-pulse/src/test/java/org/apache/geode/tools/pulse/internal/PulseAppListenerTest.java, geode-pulse/src/test/java/org/apache/geode/tools/pulse/internal/PulseAppListenerUnitTest.java
The change that fixes the NPE from GEODE-6683 is adding the line `repository.setJavaSslProperties(pulseSecurityProperties);` in PulseAppListener.java. The other changes are refactoring to do TDD for this change.
Please review: @kirklund @demery-pivotal @mhansonp @moleske
---
=> GEODE-6683: Set java SSL properties when Pulse runs in non-embedded mode

geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderOperationsDUnitTest.java
testStopSerialGatewaySender had two AsyncInvocations which it was waiting only 30 seconds for completion of. I changed these awaits and several others to use GeodeAwaitility timeout. Note that AsyncInvocation.await() uses that timeout (5 minutes).
Please review: @demery-pivotal @moleske @mhansonp @aaronlindsey @bschuchardt
=> GEODE-6731: Use GeodeAwaitility timeout for timeouts

ci/images/google-geode-builder/packer.json, ci/images/google-geode-builder/scripts/setup.sh, ci/pipelines/meta/deploy_meta.sh, geode-core/src/test/java/org/apache/geode/internal/net/NioPlainEngineTest.java
* Ignore test until static Buffers object is working
* Something about the container change is causing a test-order issue for
unit tests, which is making NioPlainEngineTest:ensureWrappedCapacity
fail due to a non-empty buffer cache.
submit an update to your PR as soon as possible. If you need help, …
=> GEODE-6734: Change packer image resources and scripts to Bionic

geode-core/src/main/java/org/apache/geode/cache/client/internal/AbstractOp.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/AuthenticateUserOp.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/ClientSideHandshakeImpl.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/PutOp.java, geode-core/src/main/java/org/apache/geode/cache/wan/EventSequenceID.java, geode-core/src/main/java/org/apache/geode/internal/ByteArrayDataInput.java, geode-core/src/main/java/org/apache/geode/internal/cache/EntryEventImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/EventID.java, geode-core/src/main/java/org/apache/geode/internal/cache/FilterRoutingInfo.java, geode-core/src/main/java/org/apache/geode/internal/cache/ha/ThreadIdentifier.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/AuthIds.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxy.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientUpdater.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientProxyMembershipID.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientUpdateMessageImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/EncryptorImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java, geode-core/src/main/java/org/apache/geode/internal/offheap/DataType.java, geode-core/src/test/java/org/apache/geode/internal/ByteArrayDataInputTest.java
In addition to the previous changes for GEODE-6687, this pr also has a unit
test for ByteArrayDataInput that demonstrates that readFully(byte[]) now correctly
throws EOFException if it attempts to read past the end of the data.
Previously it threw ArrayIndexOutOfBoundsException.
ByteArrayDataInput had the correct implementation for readFully(byte[],int,int)
which readFully(byte[]) now uses.
=> GEODE-6687: replace ByteArrayInputStream+DataInputStream with ByteArrayDataInput

ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/pull-request/jinja.template.yml, ci/pipelines/shared/shared_jinja.yml, ci/scripts/create_instance.sh
GCP costs are incurred on data egress between zones, even the same
region. Track our `create-instance` attempts, to put the heavy lifter in
the same zone on the first attempt, and roulette only on failure
Co-authored-by: Helena Bales <hbales@pivotal.io> …
=> GEODE-6739: Create Concourse heavy-lift workers in the current zone

geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java, geode-core/src/test/java/org/apache/geode/internal/cache/GemFireCacheImplTest.java
getCacheServers now returns a canonical instance
instead of creating a new instance for each call.
=> GEODE-6670: remove getCacheServers allocation

extensions/geode-modules/build.gradle, extensions/geode-modules/src/main/java/org/apache/geode/modules/util/CreateRegionFunction.java, extensions/geode-modules/src/main/java/org/apache/geode/modules/util/RegionHelper.java, extensions/geode-modules/src/test/java/org/apache/geode/modules/util/CreateRegionFunctionJUnitTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/RegionAttributesCreation.java
* If the existing region was using the DEFAULT diskstore but it was not explicitly linked to the
* region using setDiskStore or disk-store-name tags. diskStoreName is set as null. This is
* interpreted by Geode as use the DEFAULT diskstore.
* This link between the existing region and a diskstore may happen because the diskstore is
* named as DEFAULT.
* The user may change the default location of the DEFAULT diskstore but the AppServer always
* requests it be at the default location.
* This comparison with always used to fail and the AppServer could not start up.
* The goal of this method is that if both existing region and requested region are using the
* DEFAULT diskstore, the existing regions take precedence and the requested ones are ignored.
* This is current behavior which can be …
=> GEODE-6719 : Handling default disktore request from AppServers.

ci/scripts/execute_build.sh, gradle/pmd.gradle
Removing PMD as a dependency of check. Instead, we'll just directly run it in the build job in concourse. This prevents users from having to wait for this job to finish during their build runs.
Also, making sure that PMD output goes to the console, so it shows up in concourse.
=> Stop running pmd as part of build, except in concourse

geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
* Using the same logic used by configShown boolean flag
* The flag is set the first time the log is printed.
* Log level set to info rather than warn.
=> GEODE-6746: Log "hostname validation disabled" log once.

geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt, geode-core/src/main/java/org/apache/geode/internal/HeapDataOutputStream.java, geode-core/src/main/java/org/apache/geode/internal/InternalDataSerializer.java, geode-core/src/main/java/org/apache/geode/internal/cache/FilterRoutingInfo.java, geode-core/src/test/java/org/apache/geode/internal/cache/FilterInfoTest.java
The serialization of a FilterInfo now uses a thread local cached byte array
instead of allocating one each time.
=> GEODE-6686: prevent array allocation in FilterInfo toData

ci/pipelines/geode-build/jinja.template.yml
Tested on a privately deployed Concourse, since CI changes aren't triggered in the precheckin.  Seems to work nicely.
=> GEODE-6752: Add UpdatePassingBuild job to CI.

geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/util/LogExporterFileIntegrationTest.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/util/LogExporter.java
- Currently only files ending in .log are exported.
- GC logs are of the format gc.log.current, gc.log.1 which will now
be exported if they reside in the same dir as server logs.
=> GEODE-6707 gfsh export logs will now export rolled over gc logs

ci/pipelines/meta/deploy_meta.sh, ci/pipelines/meta/jinja.template.yml
Jobs use the image created in the same pipeline directly and trigger
as-needed without manual intervention
=> GEODE-6757: fix input gating for meta

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsDUnitTest.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateDiskStoreCommand.java, geode-core/src/test/java/org/apache/geode/cache/configuration/RegionConfigTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateDiskStoreCommandTest.java, geode-management/src/main/java/org/apache/geode/cache/configuration/DiskStoreType.java
* also make the diskstore config api easier to navigate without affecting xml and json serialization
=> GEODE-6672: persist the diskstore dir correctly in cluster configuration

geode-core/src/integrationTest/java/org/apache/geode/internal/AvailablePortHelperIntegrationTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ExportConfigCommandTest.java
- ExportConfigCommandTest was broken by refactorings around removing
LegacyCommandResult.
- AvailablePortHelperIntegrationTest has always been flaky on Windows.
By default, Windows uses a bunch more ports than Linux, so some of
these tests just don't work reliably as larger port ranges are not
open and available on Windows.
=> GEODE-6764: Fix tests broken and flaky on Windows

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsDUnitTest.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateDiskStoreCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListDiskStoresCommand.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateDiskStoreCommandTest.java
=> GEODE-6749: Prevent gfsh from creating duplicate named disk stores

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/PartitionedRegionAttributesMutatorDUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/internal/cache/PartitionedRegionAttributesMutatorTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionRegionConfig.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
The methods on a PR to alter the time-to-live and idle-time were losing
some of the metadata in the PartitionRegionConfig, including the
isColocationComplete flag. This causes issues with rebalancing and
bucket creation.
=> GEODE-6767: Make sure that we don't lose metadata when altering a PR

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/DeprecatedCacheServerLauncherIntegrationTest.java, geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/internal/ProcessLogger.java, geode-junit/src/main/java/org/apache/geode/test/process/ProcessStreamReader.java, geode-junit/src/main/java/org/apache/geode/test/process/ProcessWrapper.java
- Log all stdout/stderr from DeprecatedCacheServerLauncherIntegrationTest
java invocations.
- Ensure LogManager is initialized correctly in ProcessLogger
- Clean up manifest jars created by ProcessWrapper
=> GEODE-6771: Have ProcessWrapper implement Consumer

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/ClientServerFunctionExecutionDUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/cache/PoolManagerIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/cache/client/ClientRegionFactoryJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/internal/cache/xmlcache/CacheXmlParserJUnitTest.java, geode-core/src/integrationTest/resources/org/apache/geode/internal/cache/xmlcache/CacheXmlParserJUnitTest.testMultiplePools.cache.xml, geode-core/src/integrationTest/resources/org/apache/geode/internal/cache/xmlcache/CacheXmlParserJUnitTest.testRegionWithNonExistingPool.cache.xml, geode-core/src/main/java/org/apache/geode/internal/cache/PoolManagerImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/execute/InternalFunctionExecutionServiceImpl.java, geode-core/src/test/java/org/apache/geode/internal/cache/PoolManagerTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/execute/InternalFunctionExecutionServiceTest.java
GEODE-6759: Avoid Deleting Pools Still in Use
- Added unit and integration tests.
- Replaced the usage of `junit.Assert` by `assertj`.
- PoolManagerImpl now checks whether the pool is being used or not
before unregistering it.
- InternalFunctionExecutionServiceImpl now throws a meaningul
exception if the pool can not be found instead of NPE.
=> GEODE-6759: Prevent Deleting Pool Still in Use and Fix NPE in Function Execution

ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/pull-request/jinja.template.yml
We have recognized that there are very few cases where a commit works fine on JDK11 but fails on JDK8 (since generally most development work is done on 8 and compiled on 8 to begin with).  Therefore, it is not necessary to run PR checks for both 8 and 11.  11 only will catch the most issues, and the main pipeline will still run both just to be absolutely sure.
=> reduce PR checks to Java 11 only

ci/pipelines/geode-build/jinja.template.yml
per discussion on the dev list, this change promotes Windows tests to the same level as Linux tests (all now fire at the same time, all are now visible on the main pipeline view, and all must now pass for a commit to move to the next stage of the pipeline).
dev list consensus was that even though Windows tests currently take a little longer and are still a little flakier than we would like, Windows _is_ a supported platform and these changes will encourage better upkeep.
=> Make windows tests gating

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ListMembersCommandDUnitTest.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListMembersCommand.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListMembersCommandTest.java
The command was searching for the coordinator member and using the
actual object memory reference to execute the comparison, which could
return wrong results..
- When searching for the coordinator, execute the comparison using the
memberUniqueId instead of the memory reference.
=> GEODE-6769: Fix Coordinator tag in list members

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandDUnitTest.java, geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/StartServerCommandDUnitTest.java, geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandIntegrationTest.java, geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/StartServerCommandIntegrationTest.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartServerCommand.java
- Added some tests to check that the `hostname-for-clients` flag is
propagated across the stack while starting locators and servers.
- Replaced usage of class `org.apache.geode.internal.lang.StringUtils`
(deprecated) by `org.apache.commons.lang3.StringUtils`.
=> GEODE-5731: Add tests for hostname-for-clients

geode-management/src/main/java/org/apache/geode/cache/configuration/RegionAttributesType.java, geode-management/src/main/java/org/apache/geode/cache/configuration/RegionConfig.java, geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementResult.java, geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/GeneralManagementServiceRestIntegrationTest.java
- Add a bunch of @ApiModelProperty annotations to hide most of
RegionConfig and RegionAttributesType fields.
=> GEODE-6750: Clean up Swagger UI model for Manageability REST API

ci/pipelines/geode-build/jinja.template.yml
Make concourse more useful to developers.
* For all Apache branches, or all branches named 'develop', update the
passing SHA at the end of the pipeline
* Store the updated-ref at a `<ARTIFACT_BUCKET>/<BRANCH>` encoded location in GCS …
=> GEODE-6813: Build pipeline emits passing ref and build artifact

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ListAsyncEventQueuesCommandDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ListRegionDUnitTest.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/CliUtil.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListAsyncEventQueuesCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListClientCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListDeployedCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListDurableClientCQsCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListFunctionCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListGatewayCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListRegionCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/ListDurableCqNamesFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/shell/Gfsh.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListAsyncEventQueuesTest.java, geode-cq/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DurableClientCommandsDUnitTest.java, geode-cq/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ListClientCommandDUnitTest.java, geode-junit/src/main/java/org/apache/geode/test/junit/assertions/CommandResultAssert.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/wancommand/DestroyGatewaySenderCommandDUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/wancommand/ListGatewaysCommandDUnitTest.java, geode-web/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/CommandOverHttpTest.java
- This also includes not returning an error when no members are found to
execute against.
=> GEODE-6765: Gfsh list* commands do not return error when no results found

ci/images/google-windows-geode-builder/windows-packer.json, ci/scripts/execute_tests.sh
* Something changed in awt.dll in Java 11 and integration
tests no longer complete under Windows Server Core.
* Use Windows Server 2016, install docker and container support.
* Fix execute_tests.sh so that DUnit options are not included when
running tests that are not using DUnit.
=> Update windows image and tweaks to support it.

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/tier/sockets/ConnectionProxyJUnitTest.java, geode-core/src/main/java/org/apache/geode/internal/admin/ClientStatsManager.java, geode-core/src/main/java/org/apache/geode/internal/cache/EntryEventImpl.java, geode-core/src/test/java/org/apache/geode/internal/cache/AbstractRegionMapTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/AbstractRegionMapTxApplyDestroyTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/EntryEventImplTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/SearchLoadAndWriteProcessorTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/event/DistributedEventTrackerTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/PutAllPRMessageTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/RemoveAllPRMessageTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderEventProcessorJUnitTest.java
=> GEODE-6696: EntryEvenImpl.offHeapLock created only if off-heap in use

ci/pipelines/shared/jinja.variables.yml
this divides the longest (5 hour) Windows tests into two jobs to shorten the feedback cycle on a commit.  if favorably received, we could go further in this direction by splitting into even more jobs, and/or we could exclude tests that don't exercise platform-sensitive functionality.
=> split Windows tests into Core and non-Core

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/DeprecatedCacheServerLauncherIntegrationTest.java, geode-junit/src/main/java/org/apache/geode/test/process/ProcessWrapper.java
* Move gemfire config to properties file
* Add process output to allLines before offering line to lineBuffer
* Reformat code to improve readability
* Add directory option to ProcessWrapper to inject TemporaryFolder
The -J-Dgemfire.locator="" with quotes was breaking the next argument
on windows. Moving the config to properties file works around this.
Injecting TemporaryFolder into ProcessWrapper prevents files in the
working directory when running test in IDE.
=>  GEODE-4240: Fix testCreateBuckets on windows

geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupFileCopier.java
- Typically hard links would be attempted to be used, however on
Windows, this results in the backed up file not being deleteable.
=> GEODE-6824: Copy backup files using file copy on Windows

geode-core/src/main/java/org/apache/geode/management/cli/GfshCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateGatewaySenderCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyGatewaySenderCommand.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateGatewaySenderCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyGatewaySenderCommandTest.java, geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/MemberStarterRuleAwaitDUnitTest.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/MemberVM.java, geode-dunit/src/main/java/org/apache/geode/test/junit/rules/MemberStarterRule.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/wancommand/CreateDestroyGatewaySenderCommandDUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/wancommand/DestroyGatewaySenderCommandDUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/AlterRegionCommandDUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandDUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DescribeRegionDUnitTest.java
=> GEODE-6777: Create gateway senders command should only return when DistributedSystemMXBean reflects creation status

geode-core/src/integrationTest/java/org/apache/geode/cache/query/JoinQueriesIntegrationTest.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/QueryUtils.java
When joining multiple regions with indexes, only apply the LIMIT
clause in intermediate execution steps if the proper flag has been set
in the query context.
- Replaced `junit.Assert` by `assertj`.
- Added tests to validate query results of multiple joins.
=> GEODE-6806: Ignore LIMIT in intermediate steps

geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/CacheElementValidator.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidator.java, geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java, geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/CacheElementValidatorTest.java, geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidatorTest.java, geode-management/src/main/java/org/apache/geode/management/internal/ClientClusterManagementService.java, geode-web-management/src/distributedTest/java/org/apache/geode/management/client/ClientClusterManagementServiceDUnitTest.java
* validate group when there deleting a cache element
* group name should not have comma when creating the cache element.
=> GEODE-6786: be able to delete cache element when no members are found.

ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/pull-request/jinja.template.yml, ci/pipelines/shared/jinja.variables.yml
Make the Windows tests not gating for Benchmark job, since benchmark is
run on Linux.
=> GEODE-6827: Make windows not gate for Benchmark

geode-core/src/integrationTest/java/org/apache/geode/cache/query/JoinQueriesIntegrationTest.java
Index creation within the test is now done after region population
finishes, basically avoiding any race conditions that might arise
between adding entries to an index and query execution.
=> GEODE-6839: Fix Flaky JoinQueriesIntegrationTest

geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionAdvisor.java, geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/InitialImageOperation.java, geode-core/src/main/java/org/apache/geode/internal/cache/persistence/DiskStoreID.java, geode-core/src/main/java/org/apache/geode/internal/cache/versions/RegionVersionHolder.java, geode-core/src/main/java/org/apache/geode/internal/cache/versions/RegionVersionVector.java, geode-core/src/main/java/org/apache/geode/internal/cache/versions/VersionSource.java, geode-core/src/test/java/org/apache/geode/internal/cache/DistributedRegionTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/InitialImageOperationTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/versions/RegionVersionHolderTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/versions/RegionVersionVectorTest.java
* Region sync will be invoked to avoid data inconsistency on a newly joined/restarted member
if it received a region synchronization request from other members due to timed task.
* Use a flag in RegionVersionHolder to ensure only one such call is executed.
* Make sure RVV exception is filled for persistent member requesting region sync. (This may
leads to CommitConflictException on some transactions on persistent regions due to this
region sync operation. But it should be rare and is acceptable compared to data inconsistency
issue.)
=> GEODE-6802: Execute region synchronization on newly joined member.

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/tier/sockets/CqNameToOpHashMapIntegrationTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientUpdateMessageImpl.java
By making the CqNameToOpHashMap derive from ConcurrentHashMap and
taking a snapshot prior to serialization, we avoid a race where
this map could be mutated by a client registration thread while a
queue GII which includes this map is occuring in another thread.
email to …
=> GEODE-6842: Making serialization of CqNameToOpHashMap thread safe

geode-assembly/src/distributedTest/java/org/apache/geode/management/client/CreateRegionWithDiskstoreAndSecurityDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/AlterCompressorDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreateAsyncEventQueueCommandDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/management/internal/configuration/ClusterConfigImportDUnitTest.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateDiskStoreCommand.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateDiskStoreCommandTest.java, geode-wan/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/AlterRegionCommandDUnitTest.java
Co-authored-by: Sarah Abbey <sabbey@pivotal.io>
=> GEODE-6779: Create disk store command should only return when the MBeans are available

geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/GatewayReceiverMetricsTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/SimpleMetricsPublishingService.java, geode-core/src/integrationTest/java/org/apache/geode/management/bean/stats/GatewayReceiverStatsIntegrationTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/AcceptorImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/GatewayReceiverStats.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/AcceptorImplTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/wan/GatewayReceiverStatsTest.java, geode-junit/src/main/java/org/apache/geode/test/junit/categories/MetricsTest.java
Updated GatewayReceiverStats to add a
cache.gatewayreceiver.events.received meter to the registry.
The meter is a FunctionCounter that retrieves its value from the
"eventsReceived" stat.
Co-Authored-By: Aaron Lindsey <alindsey@pivotal.io>
Co-Authored-By: Michael Oleske <moleske@pivotal.io>
=> GEODE-6763: Send GatewayReceiver events received to Micrometer

ci/bin/concourse_job_performance.py
- The SSEClient API appears to have changes so the script has
been updated to work now.
- There is an error seen that is bug 613 on TQDM. Not an issue with this code as far as I can see.
=> GEODE-6852: updated script due to SSEClient change

geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/data/Cluster.java, geode-pulse/src/test/java/org/apache/geode/tools/pulse/internal/data/MemberTest.java
- Added Unit tests.
- Prevent div by zero when updating client details per member in pulse.
=> GEODE-6851: Prevent Div by Zero in Pulse

geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/commands/ConnectCommandAcceptanceTest.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ConnectCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommand.java
=> GEODE-6796: Specially-handle UnknownHostException in jmxConnect()

geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionAdvisor.java, geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/InitialImageOperation.java, geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionAdvisorTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/DistributedRegionTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/InitialImageOperationTest.java
* Move schedule region synchronize task to DistributedRegion.
* Use the time task to request region sync with no delay when processing region sync message.
=> GEODE-6853: Do not request region sync during message processing.

geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterElderManager.java, geode-core/src/test/java/org/apache/geode/distributed/internal/ClusterElderManagerTest.java
* waitToBecomeElder could return false earlier without waiting if the node is being shutdown.
* always return an elderState when waitToBecomeElder is true.
=> GEODE-6812: Do not return null if waitToBecomeElder

ci/pipelines/geode-build/jinja.template.yml
* UpdatePassingRef and UpdatePassingBuild become UpdatePassingTokens.
* Create additional coupled file stored in
```<bucket>/<fork>/<branch>/passing-build-tokens*.json```
submit an update to your PR as soon as possible. If you need …
=> GEODE-6855: Publish JSON that contains corresponding SHA and build id

geode-assembly/src/integrationTest/java/org/apache/geode/tools/pulse/PulseDataExportTest.java, geode-assembly/src/uiTest/java/org/apache/geode/tools/pulse/ui/PulseAcceptanceTestBase.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/fixed/SingleHopQuarterPartitionResolver.java, geode-core/src/distributedTest/java/org/apache/geode/management/QueryDataDUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/management/DataQueryEngineIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/json/QueryResultFormatterPdxIntegrationTest.java, geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt, geode-core/src/main/java/org/apache/geode/management/internal/cli/json/AbstractJSONFormatter.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/json/QueryResultFormatter.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/util/JsonUtil.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/json/QueryResultFormatterTest.java
Reverted some of the changes made when deleting the in-house JSON
implementation (`TypedJson`) to the jackson library
(`QueryResultFormatter`) to restore the backward compatibility.
- Added new unit tests.
- Added tests to verify the actual JSON document generated.
- Everything is serialized as JSON array with 2 elements: type & value.
- Internal class names are hidden in the JSON document, public
interfaces are included instead.
- Beans and primitive types only use the standard format when they are
not being serialized as part of an array, in which case the type is
ignored as it's already been serialized as 'ArrayElementType[]'.
to ensure the following steps have been …
=> GEODE-6808: Restore JSON backward compatibility

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/ClientFunctionTimeoutRegressionTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/PRFunctionExecutionDUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/internal/cache/execute/FunctionExecutionOnLonerRegressionTest.java, geode-core/src/main/java/org/apache/geode/cache/execute/Execution.java, geode-core/src/main/java/org/apache/geode/cache/execute/FunctionService.java, geode-core/src/main/java/org/apache/geode/distributed/internal/deadlock/GemFireDeadlockDetector.java, geode-core/src/main/java/org/apache/geode/internal/cache/execute/AbstractExecution.java, geode-core/src/main/java/org/apache/geode/internal/cache/execute/DefaultResultCollector.java, geode-core/src/main/java/org/apache/geode/internal/cache/execute/DistributedRegionFunctionExecutor.java, geode-core/src/main/java/org/apache/geode/internal/cache/execute/FunctionExecutionService.java, geode-core/src/main/java/org/apache/geode/internal/cache/execute/InternalExecution.java, geode-core/src/main/java/org/apache/geode/internal/cache/execute/InternalFunctionExecutionService.java, geode-core/src/main/java/org/apache/geode/internal/cache/execute/InternalFunctionExecutionServiceImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/execute/LocalResultCollectorImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/execute/MemberFunctionExecutor.java, geode-core/src/main/java/org/apache/geode/internal/cache/execute/MultiRegionFunctionExecutor.java, geode-core/src/main/java/org/apache/geode/internal/cache/execute/PartitionedRegionFunctionExecutor.java, geode-core/src/main/java/org/apache/geode/internal/cache/execute/ServerFunctionExecutor.java, geode-core/src/main/java/org/apache/geode/internal/cache/execute/ServerRegionFunctionExecutor.java, geode-core/src/main/java/org/apache/geode/internal/cache/snapshot/WindowedExporter.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/MemberConfigManager.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/realizers/RegionConfigRealizer.java
Extensions and implementations of Execution and ResultCollector and the
classes and interfaces involved in the execution chain were lacking the
ability to apply Generic types.
Typing issues starting from MemberConfigManager.java class were fixed.
Trivial IDE warnings were fixed.
Co-authored-by: Peter Tran <ptran@gmail.com>
=> GEODE-6588: Properly type Function execution related interfaces.

geode-core/src/integrationTest/java/org/apache/geode/internal/ClassPathLoaderDeployTest.java, geode-core/src/integrationTest/java/org/apache/geode/internal/ClassPathLoaderJUnitTest.java, geode-core/src/main/java/org/apache/geode/internal/ChildFirstClassLoader.java, geode-core/src/main/java/org/apache/geode/internal/ClassPathLoader.java, geode-core/src/main/java/org/apache/geode/internal/DeployJarChildFirstClassLoader.java, geode-core/src/main/java/org/apache/geode/internal/DeployedJar.java, geode-core/src/main/java/org/apache/geode/internal/JarDeployer.java
This solution causes each deployed jar to create it's own class loader and chains them together.
The class loaders are now child first class loaders and If a class cannot be found, it will search all 'sibling'/other deployed jars
When a jar is redeployed (new version), we keep some meta data in a map so we no longer crawl the 'old' jar when possible and only search through the latest version of a specific jar.
Java does some caching of classes and in the undeploy scenario, we may still be able to load classes that have been "removed" from the new jar (only if it was already cached by some other class loader).  This can happen when we have inter jar dependencies.
Geode also caches classes, so whenever a redeploy occurs, the geode class cache gets wiped, and first lookups take a minor …
=> GEODE-6822: Deploying jars only creates new classloader for the newly deployed jar

geode-core/src/main/java/org/apache/geode/internal/cache/PRHARedundancyProvider.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionRedundancyTracker.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionStats.java, geode-core/src/test/java/org/apache/geode/internal/cache/PRHARedundancyProviderTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionRedundancyTrackerTest.java
stats is not a reliable source of information. Operators can disable
stats entirely and the data is not guaranteed (ala logging). Instead
pull from the 'original' sources of this data.
=> GEODE-6849: Stop using 'stats' to pull redundancy info

geode-core/src/main/java/org/apache/geode/internal/cache/BucketAdvisor.java, geode-core/src/main/java/org/apache/geode/internal/cache/CacheServerImpl.java, geode-core/src/test/java/org/apache/geode/internal/cache/BucketAdvisorTest.java
* Ignoring IllegalStateException if the server is no more running.
* If the server is not running then getting external address will result in IllegalStateException.
* The server may shut down in between isRunning and getExternalAddress calls.
* If this happens then the server is not added to the location list of the servers hosting bucket.
=> GEODE-6863: Ignoring IllegalStateException

geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionAdvisor.java, geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java, geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionAdvisorTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/DistributedRegionTest.java
* Avoid region sync for empty accessor of persistent replicate region in correct place.
=> GEODE-6886: Do not region sync if lost member is an empty accessor

geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/GatewayReceiverMetricsTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/GatewayReceiverStats.java, geode-core/src/main/java/org/apache/geode/internal/statistics/meters/DoubleStatisticBinding.java, geode-core/src/main/java/org/apache/geode/internal/statistics/meters/IntStatisticBinding.java, geode-core/src/main/java/org/apache/geode/internal/statistics/meters/LegacyStatCounter.java, geode-core/src/main/java/org/apache/geode/internal/statistics/meters/LegacyStatTimer.java, geode-core/src/main/java/org/apache/geode/internal/statistics/meters/LongStatisticBinding.java, geode-core/src/main/java/org/apache/geode/internal/statistics/meters/StatisticBinding.java, geode-core/src/main/java/org/apache/geode/internal/statistics/meters/package-info.java, geode-core/src/test/java/org/apache/geode/internal/cache/wan/GatewayReceiverStatsTest.java, geode-core/src/test/java/org/apache/geode/internal/statistics/meters/DoubleStatisticBindingTest.java, geode-core/src/test/java/org/apache/geode/internal/statistics/meters/IntStatisticBindingTest.java, geode-core/src/test/java/org/apache/geode/internal/statistics/meters/LegacyStatCounterTest.java, geode-core/src/test/java/org/apache/geode/internal/statistics/meters/LegacyStatTimerTest.java, geode-core/src/test/java/org/apache/geode/internal/statistics/meters/LongStatisticBindingTest.java
Added `LegacyStatCounter` and `LegacyStatTimer`. Updated `CacheServerStats` to use a `LegacyStatCounter` to report "events received."
For now, `LegacyStatCounter` allows binding to int stats, so that we can use it for our existing gateway receiver events received meter. After all int stats are converted to long stats (in a separate PR), we will remove the ability to bind to int stats.
Please review @kirklund @pivotal-jbarrett @upthewaterspout @moleske @aaronlindsey @mhansonp
=> GEODE-6887: Add LegacyStatCounter and LegacyStatTimer

geode-dunit/src/main/java/org/apache/geode/test/greplogs/LogConsumer.java, geode-dunit/src/main/java/org/apache/geode/test/greplogs/Patterns.java, geode-dunit/src/test/java/org/apache/geode/test/greplogs/LogConsumerTest.java
Second commit includes some cleanup of LogConsumer and extracts
new Patterns enum.
Note: this does not complete GEODE-6862, but it does create the unit
test and Naba is investigating a possible LogConsumer bug so I want to
share this and hopefully merge what I have so far as a starting point
for testing. Hopefully we can add a regression test that reproduces the
problem that Naba is looking into.
=> GEODE-6862: Create LogConsumerTest

geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionStats.java, geode-core/src/main/java/org/apache/geode/distributed/internal/MaxLongGauge.java, geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionStatsTest.java, geode-core/src/test/java/org/apache/geode/distributed/internal/MaxLongGaugeConcurrentTest.java, geode-core/src/test/java/org/apache/geode/distributed/internal/MaxLongGaugeTest.java
We pull the current max from an atomic long instead of reading the
statistic. The profiler showed that reading the statistic was a contention
hotspot.
A couple things I am thinking about in this PR:
- line 1632 - after talking to @dschneider-pivotal we came up with a solution that uses `incLong` instead of `setLong`.  My only concern here is that if `incLong` fails, the metric will forever be out of sync with the `AtomicLong` field.
- still trying to figure out what multi-threaded tests look like. @dschneider-pivotal referenced some files to look at, but I don't know if those need to be written just yet. 
Please ensure …
=> GEODE-6889: Ensure the highest value is recorded to maxReplyWaitTime

ci/scripts/run_benchmarks.sh
Call the benchmark script with the --ci option to indicate to the
benchmark that it is being called from CI, so that it will check if the
commit should be the new high watermark.
=> GEODE-6898: Call benchmark script with --ci option

geode-dunit/src/main/java/org/apache/geode/test/greplogs/LogConsumer.java, geode-dunit/src/main/java/org/apache/geode/test/greplogs/Patterns.java, geode-dunit/src/test/java/org/apache/geode/test/greplogs/LogConsumerTest.java
* Rename MALFORMED_I18N_MESSAGE in Patterns
* Add MALFORMED_LOG4J_MESSAGE in Patterns
* Use MALFORMED_LOG4J_MESSAGE in isExceptionErrorOrSomeSpecialCase
* Move call to isExceptionErrorOrSomeSpecialCase because all matches
in this method seem to be ignored by LogConsumer (this class is
kind of a mess)
=> GEODE-6862: Add MALFORMED_LOG4J_MESSAGE to LogConsumer

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/MembershipJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocatorIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocatorRecoveryIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/internal/logging/LoggingWithLocatorIntegrationTest.java, geode-core/src/main/java/org/apache/geode/distributed/LocatorLauncher.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java, geode-core/src/main/java/org/apache/geode/distributed/internal/PrimaryHandler.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/MemberFactory.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/MemberServices.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMemberFactory.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocator.java, geode-junit/src/main/java/org/apache/geode/internal/cache/wan/MyDistributedSystemListener.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
Add workingDirectory parameter to the following:
* InternalLocator.startLocator
* MemberFactory.newLocatorHandler
* GMSMemberFactory.newLocatorHandler
Update some tests to use TemporaryFolder for Locator workingDirectory. Note: All of the LocatorLauncher tests are already setting workingDirectory on the launcher -- this PR updates the LocatorLauncher code to set the workingDirectory on the locator, so those tests automatically benefit from having the locator view file moved to a TemporaryFolder.
The purpose of GEODE-6825 is to better facilitate specifying where a Locator will create files, including the locator state file, so that tests can move those files to a JUnit TemporaryFolder.
This PR is divided into multiple commits to facilitate review (5. is the actual fix for GEODE-6825):
1) …
=> GEODE-6825: Add workingDirectory field to GMSLocator

geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionAdvisor.java, geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionAdvisorTest.java
* No need to wait for region initialization when scheduling region sync.
It should be done only before actual executing region sync task.
=> GEODE-6905: Do not wait for region initialization.

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/MembershipJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocatorRecoveryIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeaveJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessengerJUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ReplyProcessor21.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/MemberFactory.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/MemberServices.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/MembershipManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/adapter/auth/GMSAuthenticator.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/adapter/package-info.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMemberFactory.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/Services.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitor.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/interfaces/Authenticator.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/interfaces/HealthMonitor.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/interfaces/Manager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/interfaces/Messenger.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessenger.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/mgr/GMSMembershipManager.java, geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/Handshake.java, geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java, geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/adapter/auth/AbstractGMSAuthenticatorTestCase.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/adapter/auth/GMSAuthenticatorWithAuthenticatorTest.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/adapter/auth/GMSAuthenticatorWithSecurityManagerTest.java, geode-dunit/src/main/java/org/apache/geode/distributed/internal/membership/gms/MembershipManagerHelper.java
* Removing some direct dependencies on classes outside of membership.
* Replaced the pattern having each Service implement MessageHandler and
have a single processMessage method with a switch statement. Instead
we install individual MessageHandlers for each message.
* Removed GMSAuthenticator from Services. Instead we inject the
Authenticator when we create a MembershipManager.
Key-Gripped-By: Bill Burcham <bburcham@pivotal.io>
Co-Authored-By: Bill Burcham <bburcham@pivotal.io>
Co-Authored-By: Ernest Burghardt <eburghardt@pivotal.io>
submit …
=> GEODE-6883: Removing some dependencies on core from membership

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/DiskStoreImplIntegrationTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/PersistentOplogSet.java
- [n/a ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
After implementing the test, I added some logs to PersistenOplogSet which are not included in the commit:
```
diff --git a/geode-core/src/main/java/org/apache/geode/internal/cache/PersistentOplogSet.java …
```
=> GEODE-6652 : Change in checks for next dir in disk store

extensions/geode-modules/src/distributedTest/java/org/apache/geode/modules/util/ClientServerSessionCacheDUnitTest.java, extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/ClientServerSessionCache.java
- Added Unit tests.
- Use the `sizeOnServer` method from the `Region` class instead of
executing the `RegionSizeFunction` on a single server every time
when getting the actual size of the sessions regions.
=> GEODE-6922: Use sizeOnServer instead of function

boms/geode-all-bom/src/test/resources/expected-pom.xml, buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy, geode-core/build.gradle, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/MembershipJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocatorRecoveryIntegrationTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/MemberFactory.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/MemberServices.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMemberFactory.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/MembershipDependenciesJUnitTest.java, gradle/check-pom.gradle
Using ArchUnit to write a test that membership classes must only
depend on other membership classes.
Co-Authored-By: Bill Burcham <bburcham@pivotal.io>
Co-Authored-By: Ernest Burghardt <eburghardt@pivotal.io>
Co-Authored-By: Dan Smith <dsmith@pivotal.io>
=> GEODE-6883: Introduce ArchUnit test for membership

geode-docs/configuring/cluster_config/deploying_application_jars.html.md.erb
Bug submitted by community member YuJue Li. Thank you!
Behavior of gfsh command changed in v1.2 (https://github.com/apache/geode/pull/429), but docs were not updated at the time.
- [na (docs only - not a code change)] Does `gradlew build` run cleanly?
- [na (docs only - not a code change)] Have you written or updated unit tests to verify your changes?
- [na] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
=> GEODE-6831: User Guide - update "Versioning of JAR Files" to match code

geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeNewSenderProcessOldEvent.java
Ignoring an log message about the locator being restarted in
WANRollingUpgradeNewSenderProcessOldEvent. These tests are upgrading the
locator.
=> GEODE-6932: Ignoring log message about locator bouncing

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/control/RebalanceOperationDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/control/RebalanceOperationDistributedTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/MembershipListener.java, geode-core/src/main/java/org/apache/geode/internal/cache/PRHARedundancyProvider.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionDataStore.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/CreateBucketMessage.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/CreateMissingBucketsTask.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/DataStoreBuckets.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PersistentBucketRecoverer.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/RecoveryRunnable.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/RegionAdvisor.java, geode-core/src/test/java/org/apache/geode/internal/cache/PRHARedundancyProviderTest.java
These commits do not fix GEODE-6918, but they do cleanup some code and tests in preparation for the fix.
Please review: @aaronlindsey 
1. [Cleanup PRHARedundancyProvider](https://github.com/apache/geode/pull/3773/commits/3adf3f55c48b7a7d078f3e5801aebc652336a7af)
```
commit 3adf3f55c48b7a7d078f3e5801aebc652336a7af
Date:   Fri Jun 28 11:07:43 2019 -0700
GEODE-6918: Cleanup PRHARedundancyProvider
* Reorder constants and fields
* Move inner-classes to bottom of outer-class
* Extract DataStoreBuckets
* Encapuslate fields behind accessors
* Remove unused fields, contants and methods
* Reduce scope where possible
* Fix misc IDE warnings
* Remove bug system numbers
* Remove todos, useless comments/javadocs
* Fix typos
* Improve comments
* Delete commented out …
```
=> GEODE-6918: Cleanup PRHARedundancyProvider and tests

geode-core/src/main/java/org/apache/geode/internal/cache/DiskRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/OplogSet.java, geode-core/src/main/java/org/apache/geode/internal/cache/PersistentOplogSet.java, geode-core/src/test/java/org/apache/geode/internal/cache/PersistentOplogSetTest.java
* Create PersistentOplogSetTest
* Encapsulate fields
* Reorganize fields
* Fix misc IDE warnings
* Remove unused code
* Remove commented out code
* Remove unnecessary uses of this
* Improve whitespace and comments
* Improve variable names
These commits do not fix GEODE-6918, but they do cleanup some code and tests in preparation for the fix.
=> GEODE-6918: Cleanup and unit test PersistentOplogSet

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/control/RebalanceOperationDistributedTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/PRHARedundancyProvider.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java, geode-core/src/test/java/org/apache/geode/internal/cache/PRHARedundancyProviderTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/PersistentBucketRecovererTest.java
* Cleanup recommendations found in review
* Use constructor injection
* Use MockitoRule and STRICT_STUBS
* Improve field and variable names
* Improve overall consistency, formatting, and comments
=> GEODE-6918: Cleanup PRHARedundancyProvider and PRHARedundancyProviderTest

geode-core/src/main/java/org/apache/geode/distributed/ServerLauncher.java
* Remove unnecessary uses of this
* Replace \n with System.lineSeperator()
* Remove unnecessary qualifications
* Fix misc IDE warnings
* Remove commented out code
* Minor formatting changes
=> GEODE-6918: Cleanup ServerLauncher

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/InternalLocatorIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/MembershipJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocatorIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocatorRecoveryIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/internal/logging/LoggingWithLocatorIntegrationTest.java, geode-core/src/main/java/org/apache/geode/distributed/LocatorLauncher.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalConfigurationPersistenceService.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/MemberFactory.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/MemberServices.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMemberFactory.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocator.java, geode-core/src/main/java/org/apache/geode/internal/config/JAXBService.java, geode-core/src/test/java/org/apache/geode/distributed/internal/InternalConfigurationPersistenceServiceTest.java, geode-core/src/test/java/org/apache/geode/internal/config/JAXBServiceTest.java, geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/AlterAsyncEventQueueCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/remote/CommandExecutorTest.java
* Pass workingDirectory to InternalConfigurationPersistenceService
* Fixup InternalConfigurationPersistenceService constructors
* Create InternalLocatorIntegrationTest
* Use Path instead of String or File
=> GEODE-6918: Cleanup InternalLocator use of workingDirectory

geode-docs/reference/topics/client-cache.html.md.erb
The <cache> reference section has been prettied-up to remove table numbers and standardize subtopic headings for attributes. The <client-cache> section would benefit from receiving the same treatment.
=> GEODE-6949: User Guide - Improve format of <client-cache> reference

geode-core/src/main/java/org/apache/geode/distributed/AbstractLauncher.java, geode-core/src/main/java/org/apache/geode/distributed/LocatorLauncher.java, geode-core/src/main/java/org/apache/geode/distributed/ServerLauncher.java
I added a debug level statement in each launcher stating that either the Server or the Locator is online. This is a place-holder for the new info level statement to be added for GEODE-6918. I think it's ok to add trace or debug level statements like this.
=> GEODE-6948: Use Log4J loggers in Launchers

geode-core/src/distributedTest/java/org/apache/geode/distributed/DistributedSystemDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/management/internal/configuration/ClusterConfigLocatorRestartDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/pdx/DistributedSystemIdDUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java, geode-core/src/main/java/org/apache/geode/distributed/internal/StartupMessage.java, geode-core/src/main/java/org/apache/geode/distributed/internal/StartupOperation.java, geode-core/src/main/java/org/apache/geode/distributed/internal/StartupResponseMessage.java, geode-core/src/test/java/org/apache/geode/distributed/internal/StartupMessageJUnitTest.java
Only hold the locatorLock while reading the locator variable in
restartWithDS. Holding this lock while recovering cluster configuration
was causing other messages to the locator, including the StartupMessage,
to block waiting for this lock.
In addition, wait forever for StartupMessage responses.
StartupOperation had a 15 second timeout, after which it would stop
waiting. That resulted in not having correct metadata about other
members in the system. We were also not waking up the thread in
waitForReplies when a StartupResponseMessage came in with a
rejectionMessage.
Co-Authored-By: Ernest Burghardt <eburghardt@pivotal.io>
=> 6904: Fix hang on locator when restarting due to lock

geode-core/src/distributedTest/java/org/apache/geode/cache30/ReconnectedCacheServerDUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/DistributedMembershipListener.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/mgr/GMSMembershipManager.java, geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalCache.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalCacheForClientAccess.java, geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheCreation.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/MembershipDependenciesJUnitTest.java
Membership shouldn't be concerned with saving a cache.xml file, Do that
outside of the membership layer.
=> GEODE-6883: Save the cache xml for reconnect outside membership

geode-core/src/main/java/org/apache/geode/management/cli/GfshCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CompactDiskStoreCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateDiskStoreCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/GfshCommandJUnitTest.java
- When dealing with diskStore several ways of checking their presence 
were employed which ended up causing intermittent failure on DUnit 
testing. This patch rolls up the check which is used by all interested 
commands.
=> GEODE-6779: fix issue with Bean check variations

geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionStats.java, geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionStatsTest.java
DistributionStats.getSerialQueueBytes(). If stats are disabled then the
throttling would be disabled. Someone needs to maintain this value in a
local atomic.
Co-authored-by: Murtuza Boxwala <mboxwala@pivotal.io>
Co-authored-by: Kamilla Aslami <kaslami@pivotal.io>
=> GEODE-6891: Maintain local copy of SerialQueueBytes

geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/QueryUsingPoolDUnitTest.java
* Test now wait for 60 sec for the compiled query counters to come down to zero.
* Async query invocations may take some time to complete execution when there is a resource constraint.
=> GEODE-6967: Added awaitility clause.

ci/pipelines/images/jinja.template.yml
To run our unit tests, we create Google Compute images. We have observed
infrastructure issues on GCP that has made this process fail or hang, so
we need timeout and retry logic around these tasks
submit an update to your PR as soon …
=> GEODE-3942 - Add timeout and retry to Packer image jobs

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ClientServerReadConflictTransactionDistributedTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/FilterProfile.java
* In transaction with detectReadConflicts enabled, filter information on read locked
keys are not needed.
* Add dunit test cases with detectReadConflicts enabled.
=> GEODE-6955: Fix a NullPointerException.

geode-dunit/src/main/java/org/apache/geode/management/internal/cli/commands/ExportLogsStatsDistributedTestBase.java
=> GEODE-6979: Clean files in ExportLogsStatsDistributedTestBase

geode-docs/managing/troubleshooting/system_failure_and_recovery.html.md.erb
...and gemfire.disk.recoverLruValues
Emphasize that LoadValues must be true in order for LoadLruValues and LoadValuesSync to take effect.
Clarify that LRU is a region-level configuration setting, not a characteristic of individual data values.
=> GEODE-6972: User Guide - Clarify behavior of gemfire.disk.recoverValues

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsUtils.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsUtilsTest.java
- DUnit tests show that beans can contain null values in any imaginable
place so we have to enhance the null value filtering
- Unit test enhanced to verify the checks
=> GEODE-6779: added NPE checks

geode-core/src/main/java/org/apache/geode/internal/cache/control/InternalResourceManager.java, geode-core/src/test/java/org/apache/geode/internal/cache/control/InternalResourceManagerTest.java
This is a follow up commit for GEODE-3718.  shutdownNow was causing some threads waiting for future.get() to get hung.
=> GEODE-3718: shutdownNow should also interrupt non executing runnables

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/xmlcache/CacheXmlParserJUnitTest.java, geode-core/src/integrationTest/resources/org/apache/geode/internal/cache/xmlcache/CacheXmlParserJUnitTest.testDiskUsageWarningPercentage.cache.xml, geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheXmlParser.java
- Fixed parsing of the 'disk-usage-warning-percentage' attribute.
=> GEODE-6999: Fix XML attribute parsing

geode-docs/tools_modules/gfsh/command-pages/put.html.md.erb
- removed a duplicate sentence
- improved the formatting of table items to not split hyphens from the start of option names
=> GEODE-7007: Alter gfsh put docs to prohibit PDX type

geode-assembly/src/acceptanceTest/java/org/apache/geode/launchers/CacheProviderWithFailingStartupTask.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/launchers/ServerStartupNotificationTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/launchers/ServerStartupRedundancyRecoveryNotificationTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/launchers/ServerStartupValueRecoveryNotificationTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/launchers/startuptasks/CompletingAndFailing.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/launchers/startuptasks/Failing.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/launchers/startuptasks/MultipleFailing.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/GatewayReceiverMetricsTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/rules/ServiceJarRule.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/ServerLauncherWithProviderRegressionTest.java, geode-core/src/main/java/org/apache/geode/distributed/ServerLauncher.java, geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/PRHARedundancyProvider.java, geode-core/src/main/java/org/apache/geode/internal/cache/control/InternalResourceManager.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PartitionedRegionRebalanceOpFactory.java, geode-core/src/test/java/org/apache/geode/distributed/ServerLauncherBuilderTest.java, geode-core/src/test/java/org/apache/geode/distributed/ServerLauncherTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/DiskStoreImplValueRecoveryTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/PRHARedundancyProviderTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/control/InternalResourceManagerTest.java, geode-junit/src/main/java/org/apache/geode/internal/AvailablePortHelper.java
Added the requested log message and a test for it.
=> GEODE-6918: Adding log message to denote end of startup

ci/images/google-windows-geode-builder/build_image.sh, ci/images/google-windows-geode-builder/windows-packer.json
* Docker needs to be started up, and needs to be elevated.
* Made openjdk image pulled to be generic because they change
* Added option to build script to add build arguments to packer call.
=> Fix packer configuration for windows image.

geode-wan/src/main/java/org/apache/geode/cache/client/internal/locator/wan/LocatorMembershipListenerImpl.java, geode-wan/src/test/java/org/apache/geode/cache/client/internal/locator/wan/LocatorMembershipListenerTest.java
- Added a warn logging message so users know that the distributor
thread has been interrupted.
- Use awaitility instead of trying to find the daemon thread right
away, it might have not finished and, as such, the assertions
would fail.
=> GEODE-7005: Fix Race Condition in Unit Test

geode-core/src/main/java/org/apache/geode/management/internal/cli/GfshParser.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/help/Helper.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/help/HelperUnitTest.java
This improves gfsh error in cases where required options are not given.
Before:
```describe offline-disk-store --name=foo```
```You should specify option (--disk-dirs, --pdx, --region) for this command```
After: 
```describe offline-disk-store --name=foo```
```You should specify option (--disk-dirs, --pdx, --region) for this command```
```  --disk-dirs=  is required```
```Use "help describe offline-disk-store" (without the quotes) to display detailed usage information.```
Note that the unhelpful first part that lists all possible options, including non-required, comes from a private method in spring shell, so there is no way to suppress it.  But hopefully the added helpful information will be enough to make the user less confused.
=> GEODE-6799: better gfsh error message when missing required parameters

geode-core/src/integrationTest/java/org/apache/geode/internal/net/SSLSocketHostNameVerificationIntegrationTest.java, geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java, geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
=> GEODE-7018: Enable hostname validation for SSL over NIO

geode-core/src/main/java/org/apache/geode/security/ResourcePermission.java
When Security Manager is enabled, every put operation calls IntegratedSecurityService.authorize method, which creates new ResourcePermission object.
Every execution of ResourcePermission constructor takes 5 ms. With the optimization, ResourcePermission constructor execution takes less than 0.1 ms.
Co-authored-by: Kamilla Aslami <kaslami@pivotal.io>
=> GEODE-7004: Optimized ResourcePermission constructor

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/ClientServerFunctionExecutionDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/FunctionServiceStatsDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/PRClientServerFunctionExecutionNoAckDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/PRClientServerRegionFunctionExecutionDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/PRClientServerRegionFunctionExecutionFailoverDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/PRClientServerRegionFunctionExecutionNoSingleHopDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/PRClientServerRegionFunctionExecutionSelectorNoSingleHopDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/PRClientServerRegionFunctionExecutionSingleHopDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/PRClientServerTestBase.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/SingleHopGetAllPutAllDUnitTest.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/ServerRegionProxy.java
* Modifies tests to execute by both object and id.
=> GEODE-7008: Function execution by id uses correct bucket filter.

ci/pipelines/pull-request/jinja.template.yml
The new LGTM PR checks use "in progress" while our existing checks use "pending". Both mean the same thing, but make it tricky to make sense of GitHub's summary e.g. 
`1 in progress, 1 pending, 2 neutral, and 7 successful checks`
This PR changes ours to also use "in progress", so the above example is a little easier to grok:
`2 in progress, 2 neutral, and 7 successful checks`
=> GEODE-7028: rename PR check status 'pending' to 'in progress'

geode-core/src/main/java/org/apache/geode/distributed/internal/StartupMessage.java, geode-core/src/main/java/org/apache/geode/distributed/internal/StartupResponseMessage.java, geode-core/src/test/java/org/apache/geode/distributed/internal/StartupMessageJUnitTest.java
Until we get a response to a StartupMessage, we end up blocking up high
priority thread pool threads. So the StartupMessage should be processed
in a different, unbounded threadpool to avoid a distributed deadlock.
=> GEODE-7012: Execute the StartupMessage in the waiting pool

geode-docs/developing/query_select/aggregates.html.md.erb
- Add details about the usage of the GROUP BY within the documentation,
specifically when the clause is optional and when is mandatory.
=> GEODE-6912: Improve GROUP BY documentation

geode-assembly/src/acceptanceTest/java/org/apache/geode/launchers/ServerStartupNotificationTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/GatewayReceiverMetricsTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/RegionEntriesGaugeTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/rules/ServiceJarRule.java, geode-core/src/distributedTest/java/org/apache/geode/cache/query/internal/index/CopyOnReadIndexDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/disttx/DistTXDebugDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionStatsDUnitTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/CachePerfStats.java, geode-core/src/main/java/org/apache/geode/internal/cache/DummyCachePerfStats.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionDataStore.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionHelper.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionStatus.java, geode-core/src/main/java/org/apache/geode/internal/cache/RegionPerfStats.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySender.java, geode-core/src/main/java/org/apache/geode/internal/statistics/CallbackSampler.java, geode-core/src/main/java/org/apache/geode/internal/statistics/StatisticsImpl.java, geode-core/src/main/java/org/apache/geode/internal/statistics/StatisticsTypeImpl.java, geode-core/src/main/java/org/apache/geode/internal/statistics/SuppliableStatistics.java, geode-core/src/main/java/org/apache/geode/internal/statistics/ValidatingStatisticsType.java, geode-core/src/main/java/org/apache/geode/management/internal/FederatingManager.java, geode-core/src/main/java/org/apache/geode/management/internal/LocalManager.java, geode-core/src/test/java/org/apache/geode/internal/cache/CachePerfStatsTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/RegionPerfStatsTest.java, geode-core/src/test/java/org/apache/geode/internal/statistics/CallbackSamplerTest.java, geode-core/src/test/java/org/apache/geode/internal/statistics/StatisticsImplTest.java, geode-core/src/test/java/org/apache/geode/management/bean/stats/MemberLevelStatsTest.java
Add 'member.region.entries' gauge in `RegionPerfStats`:
- Add region.name and data.policy tags
- Configure the member.region.entries gauge to fetch from new `getLocalSize()` method (see below).
- Configure the 'entryCount' stat to be supplied by new `getLocalSize()` method.
Add `getLocalSize()` method to `InternalRegion`, and implement it in `LocalRegion` and `PartitionedRegion`
- In `LocalRegion`, the method returns the region map size minus the number of tombstones.
- In `PartitionedRegion`, the method sums the local sizes of all local bucket regions.
Also refactored the following:
- Reorganize `CachePerfStats`/`RegionPerfStats` constructors
- Remove `CachePerfStats.getEntries()`
- Remove use of `CachePerfStats.getEntries()` from `PartitionedRegionStatus`.
- Add `@Override` to …
=> GEODE-7001: Add region entry count gauge

geode-core/src/test/java/org/apache/geode/internal/cache/eviction/LRUListWithAsyncSortingTest.java
This test failed in 4 out of the last 22 Windows JDK 11 unit test runs.
There is a race condition within the test. A background thread calls unsetRecentlyUsed() on recentlyUsedNode before setting list.tail.previous() to recentlyUsedNode. Therefore, it's possible for the assertion on list.tail.previous() to fail if the background thread gets interrupted after calling unsetRecentlyUsed() but before setting list.tail.previous().
=> GEODE-6298: Fix flaky test scanMovesRecentlyUsedNodeToTail

geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/GfshParserConverterTest.java, geode-core/src/main/java/org/apache/geode/management/cli/ConverterHint.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DeployCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/converters/FilePathStringConverter.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/converters/JarDirPathConverter.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/converters/JarFilesPathConverter.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/converters/JarDirPathConverterTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/converters/JarFilesPathConverterTest.java
Before, no tab completion was available, in contrast to other commands like `start server --properties-file=`
After, filesystem-based completion is available, with the following rules:
- `--jars` supports a comma-separated list of .jar files, although you must type the comma to start the next completion cycle
- `--dir` will avoid suggesting directories that don't contain any .jar files
During tab completion of either jars or dirs, it will look ahead one directory level to see if it can filter out directories that contain neither jars nor further subdirectories.
=> GEODE-6804: add tab completion for deploy --jar= and --dir=

geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/GfshParserConverterTest.java, geode-core/src/main/java/org/apache/geode/management/cli/ConverterHint.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DeployCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/converters/FilePathStringConverter.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/converters/JarDirPathConverter.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/converters/JarFilesPathConverter.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/converters/JarDirPathConverterTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/converters/JarFilesPathConverterTest.java
Previous fix had issues on Windows with tests using '/'.
@jmelchio 
=> GEODE-6804: Tab completion does not work when specifying path for --jar argument in gfsh

geode-assembly/src/distributedTest/java/org/apache/geode/management/client/CreateRegionWithDiskstoreAndSecurityDUnitTest.java, geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ClientClusterManagementSSLTest.java, geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ClientClusterManagementServiceDunitTest.java, geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/GatewayReceiverManagementDUnitTest.java, geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ListIndexManagementDUnitTest.java, geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RegionManagementDunitTest.java, geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/DisabledClusterConfigTest.java, geode-assembly/src/integrationTest/resources/assembly_content.txt, geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt, geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java, geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java, geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementException.java, geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementRealizationException.java, geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementResult.java, geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementService.java, geode-management/src/main/java/org/apache/geode/management/internal/ClientClusterManagementService.java, geode-web-management/src/distributedTest/java/org/apache/geode/management/client/ClientClusterManagementServiceDUnitTest.java, geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/GatewayManagementIntegrationTest.java, geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementIntegrationTest.java, geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/ManagementControllerAdvice.java, geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/MemberManagementController.java, geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RegionManagementController.java
Before:
the server-side and client-side implementations of `ClusterManagementService` reported errors differently (by throwing various exceptions on the server side, but returning a status code on the client side).
After:
The goal is to be able to code to the `ClusterManagementService` interface without regard to server vs client environment. To make that possible, `ClientClusterManagementService` now raises `ClusterManagemementException` for any non-successful status, and `LocatorClusterManagementService` now wraps throw exceptions in `ClusterManagemementException` where necessary to be consistent with the client side.  REST clients should continue to receive the same status codes as they always did.
=> GEODE-7024: raise a Java exception on non-success response from REST API

geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/test/java/org/apache/geode/internal/cache/AbstractRegionJUnitTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionPartialMockTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionTest.java
Prevent potential NPE during LocalRegion construction when stat sampling is enabled. Specifically, if getLocalSize() is invoked by the callback sampler before the RegionMap inside LocalRegion is created then it will throw an NPE.
=>  GEODE-7001: Prevent potential NPE in LocalRegion

boms/geode-all-bom/src/test/resources/expected-pom.xml, buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy, geode-assembly/src/acceptanceTest/resources/gradle-test-projects/management/build.gradle, geode-assembly/src/integrationTest/resources/assembly_content.txt, geode-assembly/src/integrationTest/resources/dependency_classpath.txt, geode-core/build.gradle, geode-core/src/test/resources/expected-pom.xml, geode-wan/build.gradle
Upgrade to log4j 2.12.0 and mark log4j-core dependency as optional in geode-core.
=> GEODE-7051: Upgrade to log4j 2.12.0

geode-core/src/distributedTest/java/org/apache/geode/distributed/DistributedSystemDUnitTest.java, geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
We were hitting a deadlock during startup if a P2P reader thread tried
to send a failure reply - it would block waiting for startup to finish,
but startup would not finish until the P2P reader thread could read a
startup response.
Send the failure reply in a separate thread, to make sure we always
unblock the P2P reader thread to read new messages.
=> GEODE-7055: Don't send failure replies from a P2P reader thread

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/adapter/GMSMembershipManager.java, geode-core/src/main/java/org/apache/geode/internal/logging/log4j/AlertAppender.java, geode-core/src/test/java/org/apache/geode/internal/logging/log4j/AlertAppenderTest.java
If a custom log4j2.xml is used without specifying the Geode AlertAppender,
GMSMembershipManager may throw a NullPointerException when invoking
AlertAppender.getInstance().stopSession() during a forceDisconnect. This 
change prevents the NullPointerException allowing forceDisconnect to finish.
Users using Spring Boot with Logback are more likely to hit this bug.
=> GEODE-6959: Prevent NPE in GMSMembershipManager for null AlertAppender

geode-core/src/main/java/org/apache/geode/internal/logging/DefaultProviderChecker.java, geode-core/src/main/java/org/apache/geode/internal/logging/ProviderAgentLoader.java, geode-core/src/test/java/org/apache/geode/internal/logging/DefaultProviderCheckerTest.java
This change prevents Geode from using Log4jAgent if Log4j Core is
present but not using Log4jProvider.
For example, Log4j uses SLF4JProvider instead of Log4jProvider when 
log4j-to-slf4j is in the classpath.
By disabling Log4jAgent when other Log4j Providers are in use, this
prevents problems such as ClassCastExceptions when attempting to cast
loggers from org.apache.logging.slf4j.SLF4JLogger to
org.apache.logging.log4j.core.Logger to get the LoggerConfig or
LoggerContext.
=> GEODE-7050: Use Log4jAgent only if Log4j is using Log4jProvider

geode-junit/build.gradle, geode-junit/src/main/java/org/apache/geode/test/micrometer/AbstractMeterAssert.java, geode-junit/src/main/java/org/apache/geode/test/micrometer/CounterAssert.java, geode-junit/src/main/java/org/apache/geode/test/micrometer/GaugeAssert.java, geode-junit/src/main/java/org/apache/geode/test/micrometer/MeterAssert.java, geode-junit/src/main/java/org/apache/geode/test/micrometer/MicrometerAssertions.java, geode-junit/src/main/java/org/apache/geode/test/micrometer/TimerAssert.java, geode-junit/src/test/java/org/apache/geode/test/micrometer/CounterAssertTest.java, geode-junit/src/test/java/org/apache/geode/test/micrometer/GaugeAssertTest.java, geode-junit/src/test/java/org/apache/geode/test/micrometer/MeterAssertTest.java, geode-junit/src/test/java/org/apache/geode/test/micrometer/TimerAssertTest.java, geode-junit/src/test/resources/expected-pom.xml
- `MeterAssert` for assertions common to all meters (assertions about name, tags, and base unit)
- `CounterAssert` for assertions a counter's count
- `GaugeAssert` for assertions a gauge's value
- `TimerAssert` for assertions about a timer's count and total time
The assertions for counters, gauges, and timers each take a `Condition<T>`
that evaluates the relevant value.
@aaronlindsey please review
=> GEODE-7063: Add basic assertions for meters

geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java, geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionTest.java
Prevent PartitionedRegion's getLocalSize() from throwing a
NullPointerException if called before its internal data store is
initialized. The stats sampler uses this method to get the region's
entry count, and stats sampling may start before the internal data store
is initialized.
=> GEODE-7081: Prevent NPE in getLocalSize()

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/wan/asyncqueue/AsyncEventListenerDistributedTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySenderEventProcessor.java, geode-core/src/test/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderEventProcessorJUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialWANConflationDUnitTest.java
- Added tests.
- Use the cached region name when doing conflation instead of the actual region so the processor doesn't need to wait for the actual region to be fully initialized.
=> GEODE-7079: Prevent NPE During Queue Conflation

geode-core/src/main/java/org/apache/geode/internal/cache/versions/BitSetExceptionIterator.java, geode-core/src/main/java/org/apache/geode/internal/cache/versions/RVVException.java, geode-core/src/main/java/org/apache/geode/internal/cache/versions/RegionVersionHolder.java, geode-core/src/test/java/org/apache/geode/internal/cache/versions/BitSetExceptionIteratorTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/versions/RegionVersionHolder2JUnitTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/versions/RegionVersionHolderBitSetJUnitTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/versions/RegionVersionHolderUtilities.java, geode-core/src/test/java/org/apache/geode/internal/cache/versions/RegionVersionVectorTest.java
Ensuring that when we call recordVersion on a RegionVersionHolder,
we appropriately move the bitSet to match the new version we are
recording, rather than trying to expand it. In particular, if new
version is greater than Integer.MAX_VALUE, we can't record than in out
integer indexed bit set.
This change rewrites addBitSetExceptions. The logic is now broken into a
BitSetExceptionIterator, which converts some or all of the bit set into
RVVException objects, and the logic to slide the bit set forward to a
new bitSetVersion.
Adding unit tests that show that large versions cause an
IndexOutOfBounds exception from recordGCVersion. Adding more unit tests
for the internal state of the bitset.
=>  GEODE-7085: Ensuring the bitset stays within BIT_SET_WIDTH

geode-core/src/distributedTest/java/org/apache/geode/cache30/ReconnectDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/distributed/LocatorDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/snapshot/GFSnapshotDUnitTest.java, geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgrade2DUnitTestBase.java, geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgradeClients.java, geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgradeConcurrentPutsReplicated.java, geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgradeHARegionNameOnDifferentServerVersions.java, geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgradeOplogMagicSeqBackwardCompactibility.java, geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgradeRollLocatorWithTwoServers.java, geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgradeRollLocatorsWithOldServer.java, geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgradeRollSingleLocatorWithMultipleServersReplicatedRegion.java, geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgradeVerifyXmlEntity.java, geode-lucene/src/upgradeTest/java/org/apache/geode/cache/lucene/RollingUpgradeQueryReturnsCorrectResultAfterTwoLocatorsWithTwoServersAreRolled.java, geode-lucene/src/upgradeTest/java/org/apache/geode/cache/lucene/RollingUpgradeQueryReturnsCorrectResultsAfterClientAndServersAreRolledOver.java, geode-lucene/src/upgradeTest/java/org/apache/geode/cache/lucene/RollingUpgradeQueryReturnsCorrectResultsAfterClientAndServersAreRolledOverAllBucketsCreated.java, geode-lucene/src/upgradeTest/java/org/apache/geode/cache/lucene/RollingUpgradeReindexShouldBeSuccessfulWhenAllServersRollToCurrentVersion.java, geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeCreateGatewaySenderMixedSiteOneCurrentSiteTwo.java, geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeEventProcessingMixedSiteOneCurrentSiteTwo.java, geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeEventProcessingMixedSiteOneOldSiteTwo.java, geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeEventProcessingOldSiteOneCurrentSiteTwo.java, geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeNewSenderProcessOldEvent.java, geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeSecondaryEventsNotReprocessedAfterCurrentSiteMemberFailover.java, geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeSecondaryEventsNotReprocessedAfterCurrentSiteMemberFailoverWithOldClient.java, geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeSecondaryEventsNotReprocessedAfterOldSiteMemberFailover.java, geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeVerifyGatewayReceiverDoesNotSendRemoveCacheServerProfileToMembersOlderThan1dot5.java, geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeVerifyGatewaySenderProfile.java
A number of tests were attempting to delete old locator state files
containing membership views in order to ensure that artifacts from
previously run tests were not around to infect the current test.
Unfortunately the calls to DistributedTestUtils.deleteLocatorStateFile()
were being made from the wrong working directory.  Instead of looking
for the file(s) in the directory that the test's locator would use they
were looking in the unit test VMs working directory.
submit an update to your PR as soon as possible. If you need help, please send …
=> GEODE-7072 CI Failure: WANRollingUpgradeEventProcessingMixedSiteOneCurrentSiteTwo

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitorJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeaveJUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitor.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/interfaces/HealthMonitor.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java
After passing a "final check" a member will be subject to suspect
processing again but we weren't processing the suspect message locally.
This caused JoinLeave to never be notified of the suspect so that
removal could be initiated.
I also noticed that a method in HealthMonitor was misnamed.  It claimed
to return the set of members that had failed availability checks but
instead it was returning a set of members currently under suspicion.  Looking
at the uses of this method I think it could cause members to be kicked out
that were only late in sending heartbeats.  They should go through full availability
checks before being kicked out.  The new code ensures that this happens
and that RemoveMemberMessages will be processed locally after performing those
checks.
@Bill 
Thank you for …
=> GEODE-3780 suspected member is never watched again after passing final check

geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/MicrometerBinderTest.java, geode-core/src/main/java/org/apache/geode/internal/metrics/CacheMeterRegistryFactory.java, geode-core/src/test/java/org/apache/geode/internal/metrics/CacheMeterRegistryFactoryTest.java
Add the following Micrometer binders:
- JvmGcMetrics
- ProcessorMetrics
- JvmThreadMetrics
- UptimeMetrics
- FileDescriptorMetrics
=> GEODE-7091: Add Micrometer binders to meter registry

geode-docs/developing/function_exec/how_function_execution_works.html.md.erb
* Before : the default for retries was -1 and function execution was retried infinitely.
* After : the default behavior is now that the function will be retried on every server only once and if it fails on every one of them, then an exception will be returned to the user.
=> GEODE-7105: Changed Function execution HA docs

geode-core/src/main/java/org/apache/geode/internal/cache/versions/RegionVersionHolder.java, geode-core/src/test/java/org/apache/geode/internal/cache/versions/RegionVersionHolderBitSetJUnitTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/versions/RegionVersionHolderJUnitTest.java
In recordVersion, there was a code path where we would not call
flushBitSetDuringRecording before calling setVersionInBitSet. Moving the
flush to the top of the method to ensure that the bit set is always
flushed, and we never end up with a case where we try to set too large
of a bit.
By code inspection, we determined that initializeFrom was what got us
into the state that triggered this code path - it could leave
bitSetVersion at a small number while setting version to a large number.
Fixing initializeFrom so that it correctly sets bitSetVersion.
Co-Authored-By: Ernest Burghardt <eburghardt@pivotal.io> …
=> GEODE-7085: Ensure bitset is flushed in all code paths

geode-core/src/distributedTest/java/org/apache/geode/internal/metrics/MeterSubregistryReconnectDistributedTest.java
=> GEODE-7099: Clean up MeterSubregistryReconnectDistributedTest

geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientUpdateMessageImpl.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientUpdateMessageImplTest.java
This fix is to handle a very specific race condition scenario as described here:
Subscription HA is enabled and a server is providing a client queue image to a peer (serializing the queue). Meanwhile, a client is also just finished client subscription registration with that same server and is recalculating its filter info to determine if the client needs the event. Recalculating the filter info results in the client message in the HAContainer to be mutated, which causes a ConcurrentModificationException to occur in the GII provider thread. …
=> GEODE-7088: Using ConcurrentSets for interested clients

geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/GatewayReceiverMetricsTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/GatewayReceiverStats.java, geode-core/src/test/java/org/apache/geode/internal/cache/wan/GatewayReceiverStatsTest.java
- Rename meter 'cache.gatewayreceiver.events.received' to 'geode.gateway.receiver.events'
Draft Pr to verify tests pass.
=> GEODE:7141 Rename meter 'cache.gatewayreceiver.events.received'

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/PartitionedRegionIntegrationTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java, geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionTest.java
- Added tests.
- While releasing the distributed lock acquired to generate a new
global partitioned region ID, don't parse the String
MAX_PARTITIONED_REGION_ID as an Integer.
=> GEODE-7106: Prevent NFE During PRid Generation

geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/TomcatInstall.java, geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/Tomcat8ClientServerRollingUpgradeTest.java, geode-docs/tools_modules/http_session_mgmt/tomcat_installing_the_module.html.md.erb, geode-docs/tools_modules/http_session_mgmt/tomcat_setting_up_the_module.html.md.erb, geode-docs/tools_modules/http_session_mgmt/weblogic_setting_up_the_module.html.md.erb
=> GEODE-6867: Updating Tomcat Session State Module docs

geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/RestartOfMemberDistributedTest.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java
GEODE-7118: Cleanup RestartOfMemberDistributedTest
Add IgnoredException.removeAllExpectedExceptions to ClusterStartupRule
Reduce run-time of RestartOfMemberDistributedTest
* Set MAX_WAIT_TIME_RECONNECT to 1000
* Set MEMBER_TIMEOUT to 2000
=> GEODE-7118: Cleanup RestartOfMemberDistributedTest

geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/ClusterDistributionManagerForAdminDUnitTest.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/LogWriterUtils.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/log4j/LogWriterLogger.java
Rolling upgrade and similar tests that run test code in JVMs using older versions of Geode fail when changing logging classes because these tests are using org.apache.geode.test.dunit.LogWriterUtils.getLogWriter(). This PR creates a fully inlined version of LogWriterLogger in geode-dunit for use by LogWriterUtils. This is all deprecated and should be removed eventually. The removal of LogWriterUtils will keep a developer busy for a while removing the calls from many tests. This geode-dunit LogWriterLogger is temporary and unfortunate but ultimately necessary if we want to move log4j-core code to geode-log4j.
@aaronlindsey please review.
=> GEODE-6964: Add standalone LogWriterLogger to geode-dunit

ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/shared/jinja.variables.yml, ci/scripts/cleanup_benchmarks.sh, ci/scripts/run_benchmarks.sh
* add tasks that run benchmark with SSL
* pass option to run benchmark script
Signed-off-by: Murtuza Boxwala <mboxwala@pivotal.io>
* create cluster for SSL with a different cluster tag
* filter the tests run with SSL
* run the SSL and non-SSL tasks in parallel
=> GEODE-7054: add tests running with SSL

gradle/ide.gradle
When delegating build/run actions to IntelliJ instead of Gradle, IntelliJ 2019 fails to build geode with an error like "output path not specified for modules...". I was able to reproduce this issue on IntelliJ IDEA CE versions 2019.1.4 and 2019.2.1 (see JIRA ticket for details). The issue seems to occur when IntelliJ imports Gradle sub-projects as modules that have "Use module compile output path" checked but don't have an Output path specified.
The best solution I've found involves 2 parts. I tested this on both versions of IntelliJ 2019.
1. Set the Project compiler output as shown in this SO answer: <https://stackoverflow.com/a/40675201>.
2. Add `inheritOutputDirs = true` to the idea plugin configuration in `ide.gradle`. This causes IntelliJ to import gradle sub-projects with the …
=> GEODE-7164: Fix issue with IntelliJ Gradle import

geode-core/build.gradle, geode-core/src/test/resources/expected-pom.xml
=> GEODE-7107: Make jetty-server optional in geode-core pom

geode-core/src/main/java/org/apache/geode/internal/cache/FindRemoteTXMessage.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXManagerImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXStateProxyImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/TXFailoverCommand.java, geode-core/src/test/java/org/apache/geode/internal/cache/TXManagerImplTest.java
* Only clean up transaction if not hosted caused by fail over.
* unmasquerade should not clean transaction in other cases e.g. transaction
has been committed.
=> GEODE-7087: Do not always clean up transaction if not hosted.

geode-core/src/distributedTest/java/org/apache/geode/pdx/PdxTypeGenerationDUnitTest.java, geode-core/src/main/java/org/apache/geode/pdx/internal/PeerTypeRegistration.java, geode-core/src/main/java/org/apache/geode/pdx/internal/PeerTypeRegistrationReverseMap.java, geode-core/src/test/java/org/apache/geode/pdx/internal/PeerTypeRegistrationReverseMapTest.java, geode-core/src/test/java/org/apache/geode/pdx/internal/PeerTypeRegistrationTest.java
- Brought Enum behaviour in line with PdxType behaviour in PeerTypeRegistration
- Refactored ReverseMap to not be an internal class of PeerTypeRegistration
- Added unit tests for PeerTypeRegistration and PeerTypeRegistrationReverseMap …
=> GEODE-7035 - adding a new enumInfo will check from local map, the same behavior as adding a pdxType

geode-core/src/main/java/org/apache/geode/cache/query/internal/aggregate/AbstractAggregator.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/aggregate/Avg.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/aggregate/AvgBucketNode.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/aggregate/AvgPRQueryNode.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/aggregate/Count.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/aggregate/CountPRQueryNode.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/aggregate/AvgBucketNodeTest.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/aggregate/AvgPRQueryNodeTest.java
- Use 'long' instead of 'int' to compute OQL COUNT results.
- Use 'long' instead of 'int' to compute OQL AVG internal results.
=> GEODE-7150: Use Long in OQL COUNT and AVG

geode-redis/src/main/java/org/apache/geode/redis/GeodeRedisServer.java
- Removed references to the deprecated AttributesFactory from the
geode-redis module.
=> GEODE-7161: Remove AttributesFactory in geode-redis

extensions/geode-modules/build.gradle, geode-assembly/build.gradle, geode-assembly/geode-assembly-test/build.gradle, geode-connectors/build.gradle, geode-connectors/src/test/resources/expected-pom.xml, geode-core/build.gradle, geode-core/src/test/resources/expected-pom.xml, geode-cq/build.gradle, geode-cq/src/test/resources/expected-pom.xml, geode-dunit/build.gradle, geode-dunit/src/test/resources/expected-pom.xml, geode-junit/build.gradle, geode-lucene/build.gradle, geode-lucene/src/test/resources/expected-pom.xml, geode-memcached/build.gradle, geode-memcached/src/test/resources/expected-pom.xml, geode-protobuf/build.gradle, geode-protobuf/geode-protobuf-test/build.gradle, geode-protobuf/src/test/resources/expected-pom.xml, geode-rebalancer/build.gradle, geode-rebalancer/src/test/resources/expected-pom.xml, geode-redis/build.gradle, geode-redis/src/test/resources/expected-pom.xml, geode-wan/build.gradle, geode-wan/src/test/resources/expected-pom.xml, geode-web-api/build.gradle, geode-web-management/build.gradle, geode-web/build.gradle, geode-web/src/test/resources/expected-pom.xml
Fixes transitive API dependency on geode-common. Some classes in the
geode-core API extend classes in the geode-common module, thus making
geode-common API as well.
=> GEODE-7185: Partial revert of a7e0b2edefc6f52315ce92ea3b8cd29d5be3fd1c.

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/GemfireCacheImplDUnitTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java, geode-core/src/test/java/org/apache/geode/internal/cache/GemFireCacheImplIntegrationTest.java
Add null check before closing GatewayReceiverServers in emergencyClose()
Please ensure that once the PR is …
=> GEODE-7202 Add null check before closing GatewayReceiverServers

geode-core/src/main/java/org/apache/geode/admin/internal/AdminDistributedSystemImpl.java
Prevent NPE in AdminDistributedSystemImpl.getDistributionManager()
during shutdown.
Fix race condition involving null volatile field by using a single
local reference.
=> GEODE-7173: Prevent NullPointerException in AdminDistributedSystemImpl

geode-core/src/integrationTest/java/org/apache/geode/distributed/ServerLauncherIntegrationTestCase.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/ServerLauncherLocalIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/ServerLauncherRemoteIntegrationTestCase.java
GEODE-5940: Disable server port in many ServerLauncher tests
Disable default server in all launcher tests that do not require it.
This will decrease the number of failures to launch the server caused
by an underlying BindException because a port is already in use.
GEODE-5940: Use destroyForcibly in ServerLauncherRemoteIntegrationTest tearDown
=> GEODE-5940: Disable server port in many ServerLauncher tests

geode-core/src/main/java/org/apache/geode/cache/client/internal/ClientMetadataService.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/QueryUtils.java, geode-core/src/main/java/org/apache/geode/internal/cache/ColocationHelper.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/execute/FunctionExecutionNodePruner.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CommandInitializer.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySenderEventProcessor.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueue.java, geode-core/src/main/java/org/apache/geode/internal/datasource/AbstractPoolCache.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/DistributedSystemBridge.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListRegionCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/result/model/TabularResultModel.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/shell/Gfsh.java
* Using the constructor with initial value rather than using addAll after the constructor.
=> GEODE-7218: Redundant addAll call.

geode-core/src/main/java/org/apache/geode/internal/jndi/JNDIInvoker.java
* In GMSLocator null check for service is done before that point.
* In JNDIInvoker datasource null check is done in the first section of OR.
=> GEODE-6014: Removal of unnecessary null checks.

geode-core/src/distributedTest/java/org/apache/geode/management/CacheManagementDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/management/internal/JMXMBeanFederationDUnitTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/HasCachePerfStats.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/main/java/org/apache/geode/management/internal/FederatingManager.java, geode-core/src/main/java/org/apache/geode/management/internal/LocalManager.java, geode-core/src/main/java/org/apache/geode/management/internal/MBeanJMXAdapter.java, geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionTest.java, geode-core/src/test/java/org/apache/geode/management/internal/FederatingManagerTest.java, geode-core/src/test/java/org/apache/geode/management/internal/LocalManagerTest.java
1) [Cleanup and unit test FederatingManager](https://github.com/apache/geode/pull/4072/commits/a47be7a495b8a62b5372a4ec0d2b8bcb259ea92d)
```
commit a47be7a495b8a62b5372a4ec0d2b8bcb259ea92d
Date:   Thu Sep 19 11:30:07 2019 -0700
GEODE-7221: Cleanup and unit test FederatingManager
* Move inner classes to bottom of outer class
* Extract addMemberArtifacts from GIITask
* Remove unnecessary code
* Create FederatingManagerTest
```
2) [Cleanup and unit test LocalManager](https://github.com/apache/geode/pull/4072/commits/74e4467410e58f32897715a763ede0bff3020f77)
```
commit 74e4467410e58f32897715a763ede0bff3020f77
Date:   Thu Sep 19 11:47:59 2019 -0700
GEODE-7221: Cleanup and unit test LocalManager
* Move inner class to …
```
=> GEODE-7221: Ensure management regions close CachePerfStats

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/GMSQuorumChecker.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessenger.java
Use reflection to poke a new Receiver into JGroups to avoid
synchronization problems in JGroups code.
No new tests were needed.
=> GEODE-7220 NPE in the logs on reconnect

geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt, geode-core/src/main/java/org/apache/geode/internal/cache/versions/VersionTag.java, geode-core/src/test/java/org/apache/geode/internal/cache/versions/AbstractVersionTagTestBase.java, geode-core/src/test/java/org/apache/geode/internal/cache/versions/DiskVersionTagTest.java
VersionTag serialization was being affected by concurrent modification
of its memberId/previousMemberId fields, causing the HAS_PREVIOUS_MEMBER_ID
flag bit to be set and the DUPLICATE_MEMBER_IDS flag to _not_ be set.
It then went on to perform the same checks later in toData() and make
different decisions, winding up by not serializing the previousMemberId
field because it was then == to the memberId field.
1) decide on what the flags are going to be in toData and do not perform
the same calculations again.
2) use equals() when seeing if memberId and previousMemberId are equal. …
=> GEODE-7219 BufferUnderflowException in PutReplyMessage deserialization

geode-core/src/main/java/org/apache/geode/cache/query/internal/DefaultQueryService.java, geode-core/src/main/java/org/apache/geode/cache/query/security/MethodInvocationAuthorizer.java, geode-core/src/main/java/org/apache/geode/cache/query/security/RestrictedMethodAuthorizer.java, geode-core/src/test/java/org/apache/geode/cache/query/security/RestrictedMethodAuthorizerTest.java
- Made the class final, immutable and thread safe.
- Added comprehensive javadocs to all public methods.
- Added several unit tests for the class and all public methods.
- Added methods 'isAllowedGeodeMethod' and 'isKnownDangerousMethod'.
=> GEODE-6985: Implement RestrictedMethodAuthorizer

ci/pipelines/examples/jinja.template.yml, ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/metrics/jinja.template.yml, ci/pipelines/pull-request/jinja.template.yml, ci/pipelines/reaper/jinja.template.yml, ci/pipelines/shared/shared_jinja.yml
Use Concourse resources for better image caching, instead of downloading the runtime image in the task container itself.
email to …
=> GEODE-7234 Better Concourse image caching

geode-wan/src/main/java/org/apache/geode/internal/cache/wan/GatewayReceiverImpl.java, geode-wan/src/test/java/org/apache/geode/internal/cache/wan/GatewayReceiverImplTest.java
The test was failing on machines with ports 2000 or 2001 in use.
This change replaces GatewayReceiverImpl's dependency on AvailablePort
with functions that are now injected by the unit tests.
Specifically, this test was failing for @dickcav and @onichols-pivotal.
=> GEODE-7165: Remove networking dependency from GatewayReceiverImplTest

geode-assembly/src/integrationTest/java/org/apache/geode/rest/internal/web/DevRestSwaggerVerificationIntegrationTest.java, geode-web-api/src/main/java/org/apache/geode/rest/internal/web/security/RestSecurityConfiguration.java, geode-web-api/src/main/resources/swagger.properties
we should not change the api docs link for dev rest api.
=> GEODE-6897: revert accidental change of apidoc's link for dev rest api.

geode-docs/developing/query_select/aggregates.html.md.erb
Fixed the documentation for the aggregate functions AVG and SUM, the
result value will always be an instance of `java.lang.Number` but the
actual type might vary depending on the value size and wether it has a
decimal componen or not.
=> GEODE-7242: Fix AVG and SUM documentation

geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/commands/ConnectCommandAcceptanceTest.java, geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/internal/ProcessLogger.java
Creation of geode-log4j widened a race condition in GfshRule in which
the process being forked would start printing output before the
ProcessLogger had been created and started in order to intercept that
output.
The widening of that race condition resulted in CI failures of
ConnectCommandAcceptanceTest.
ProcessLogger does not appear to have any real need for manipulating
log4j-core which is what widens the race condition far enough to fail
in CI.
Removing the manipulation of log4j-core from ProcessLogger reduces
the race condition for consistent passing. The window itself is still
there but without resorting to something like MainLauncher [1], there's
no way to completely close the window.
[1] geode-junit: org.apache.geode.test.process.MainLauncher
If ConnectCommandAcceptanceTest or other …
=> GEODE-7237: Fix race condition in GfshRule

geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/shell/GfshInitFileIntegrationTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/ColocationHelperTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/execute/FunctionContextImplTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/ShowMissingDiskStoresFunctionTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/shell/GfshConfigTest.java
Remove use of log4j-core from geode-core unit tests. After this PR merges in, we should be able to remove geode-log4j dependency from geode-junit.
GfshInitFileTest and ShowMissingDiskStoresFunctionTest had significant issues as tests so both of these have been pretty much rewritten.
In all tests I did the following:
a) Extracted any tests that more appropriately belonged in a different unit test.
b) Replace use of Fakes with just the minimum needed Mockito mocks.
c) Use AssertJ catchThrowable for any testing of expected exceptions.
d) Replace JUnit Assert with AssertJ which is 1000% better.
e) Use MockitoRule with STRICT_STUBS to keep the mocking precise.
1) [Remove log4j-core from ColocationHelperTest](https://github.com/apache/geode/pull/4093/commits/f9541824f8e015961f3b493ffd48c2fa01096 …
=> GEODE-7239: Remove log4j-core from unit tests

geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/shell/GfshInitFileIntegrationTest.java
GfshInitFileIntegrationTest fails intermittently and currently uses
reflection to alter values of static variables in Gfsh.
It needs to be disabled in CI until someone has the time and desire to
rewrite this test.
=> GEODE-7249: Disable GfshInitFileIntegrationTest

geode-assembly/build.gradle, geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ManagementRequestLoggingDUnitTest.java, geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ManagementRequestLoggingDistributedTest.java, geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/GfshParserAutoCompletionIntegrationTest.java, geode-dunit/build.gradle, geode-dunit/src/test/resources/expected-pom.xml, geode-junit/build.gradle, geode-junit/src/main/java/org/apache/geode/test/golden/GoldenTestCase.java, geode-junit/src/test/resources/expected-pom.xml, geode-pulse/build.gradle, geode-pulse/src/test/resources/expected-pom.xml, geode-serialization/build.gradle, geode-serialization/src/test/resources/expected-pom.xml
Reimplement tests without using log4j-core:
* ManagementRequestLoggingDistributedTest
* GfshParserAutoCompletionIntegrationTest
* GoldenTestCase
Remove log4j-core and log4j-core:tests dependency from:
* geode-assembly
* geode-junit
* geode-pulse
* geode-serialization
Please review: @aaronlindsey
=> GEODE-7257: Remove unnecessary uses of log4j-core

geode-lucene/src/upgradeTest/java/org/apache/geode/cache/lucene/RollingUpgradeQueryReturnsCorrectResultsAfterClientAndServersAreRolledOverAllBucketsCreated.java
GEODE-7258: Pulling a test while it is fixed.
=> GEODE-7258: Pulling the failing test while fixing

geode-management/src/main/java/org/apache/geode/management/configuration/ClassName.java, geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/PdxManagementTest.java
Changed PdxManagementTest to include a ClassName attribute which caused the test to fail.
Added default constructor to ClassName so that it can be serialized and test now passes.
=> GEODE-7227: ClassName now has a default constructor allowing it to be serialized

geode-core/src/main/java/org/apache/geode/cache/Region.java, geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/EntriesCollection.java, geode-core/src/main/java/org/apache/geode/internal/cache/EntriesSet.java, geode-logging/src/main/java/org/apache/geode/internal/logging/LogWithToString.java, geode-logging/src/main/java/org/apache/geode/internal/logging/log4j/message/GemFireParameterizedMessage.java
- EntriesCollection put back into internal.cache and AbstractRegion now implements the marker
- Formerly known as Loggable renamed to LogWithToString
- [x ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?
- [ x] Does `gradlew build` run cleanly?
email to …
=> GEODE-7172: Move and rename marker classes

geode-assembly/src/integrationTest/resources/assembly_content.txt, geode-core/src/main/java/org/apache/geode/cache/query/security/MethodInvocationAuthorizer.java, geode-core/src/main/java/org/apache/geode/cache/query/security/RestrictedMethodAuthorizer.java, geode-core/src/main/java/org/apache/geode/cache/query/security/UnrestrictedMethodAuthorizer.java, geode-core/src/test/java/org/apache/geode/cache/query/security/RestrictedMethodAuthorizerTest.java, geode-core/src/test/java/org/apache/geode/cache/query/security/UnrestrictedMethodAuthorizerTest.java
- Made the class final, immutable and thread safe.
- Added comprehensive javadocs to the class and its methods.
- Added several unit tests for the class and all public methods.
- Improved javadocs for 'RestrictedMethodAuthorizer' and
'MethodInvocationAuthorizer'.
- Fixed 'RestrictedMethodAuthorizer.isAllowedGeodeMethod()' to allow
the execution of 'toString' and 'equals' on Geode objects.
- Removed 'getNanos' from the accepted methods for 'java.lang.Date' in
'RestrictedMethodAuthorizer' (the method belong to 
'java.sql.Timestamp' instead). …
=> GEODE-6986: Implement UnrestrictedMethodAuthorizer

geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/commands/ConnectCommandAcceptanceTest.java
The test invalidHostname continues to fail intermittently. In the
failure, something fails to throw UnknownHostException. Having
spaces in the "invalid host name" should guarantee that it always
throws UnknownHostException now.
Also, remove the double negative from the assumeTrue by flipping it
to assumeFalse. Move the comment into the assumeFalse as a message.
Please review: @aaronlindsey
=> GEODE-7237: Use invalid host name in ConnectCommandAcceptanceTest

geode-core/src/main/java/org/apache/geode/cache/query/internal/DefaultQueryService.java
- Added warning log when the property is specified
=> GEODE-6992: Deprecate allowUntrustedMethodInvocation System Property

geode-assembly/src/integrationTest/resources/assembly_content.txt, geode-core/src/main/java/org/apache/geode/cache/query/security/RegExMethodAuthorizer.java, geode-core/src/test/java/org/apache/geode/cache/query/security/RegExMethodAuthorizerTest.java
- Made the class final, immutable and thread safe.
- Added comprehensive javadocs to the class and its methods.
- Added several unit tests for the class and all public methods.
=> GEODE-6987: Implement RegExMethodAuthorizer

geode-core/src/distributedTest/java/org/apache/geode/management/MemberMXBeanAttributesDistributedTest.java
1) [Rename MemberMBeanAttributesDUnitTest as MemberMXBeanAttributesDistributedTest](https://github.com/apache/geode/pull/4138/commits/5e389b200e80c70ac5c7659193b4f2f2705937c3)
```
commit 5e389b200e80c70ac5c7659193b4f2f2705937c3
Date:   Wed Oct 9 09:55:36 2019 -0700
GEODE-6566: Rename to MemberMXBeanAttributesDistributedTest
Rename MemberMBeanAttributesDUnitTest as MemberMXBeanAttributesDistributedTest.
```
2) [Cleanup and deflakify MemberMXBeanAttributesDistributedTest](https://github.com/apache/geode/pull/4138/commits/ad917f314eb9e7e66b30697a55ab510f0f594ca5)
```
commit ad917f314eb9e7e66b30697a55ab510f0f594ca5
Date:   Wed Oct 9 11:01:04 2019 -0700
GEODE-6566: Prevent MemberMXBeanAttributesDistributedTest flakiness …
```
=> GEODE-6566: Prevent MemberMXBeanAttributesDistributedTest flaky failures

geode-core/src/integrationTest/java/org/apache/geode/distributed/LauncherIntegrationTestCase.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/LocatorCommand.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/LocatorLauncherJmxManagerLocalRegressionTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/LocatorLauncherRemoteFileIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/LocatorLauncherRemoteIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/LocatorLauncherRemoteIntegrationTestCase.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/ServerCommand.java
* Increase await timeout (these tests fork external process)
* Set locator port to zero where possible to reduce BindExceptions
* Include statusFailedWithException details for Errors
* Fix GEODE-7026 on Windows as well
This should reduce failures caused by GEODE-6183 and GEODE-7026. It should also increase the available information for debugging by including statusFailedWithException details for Errors (so we'll see info about the Process when the ConditionTimeoutException occurs).
Please review: @aaronlindsey
=> GEODE-6183: Increase await timeout for LocatorLauncher tests

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/DiskStoreImplIntegrationTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java, geode-core/src/main/java/org/apache/geode/management/DiskStoreMXBean.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/DiskStoreMBean.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/DiskStoreMBeanBridge.java
=> GEODE-6871: Disk free space info exposed via JMX

geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/UpdateVersionDUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/CacheClientNotifierDUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueueOverflowDUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelWANPersistenceEnabledGatewaySenderDUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderQueueDUnitTest.java, geode-wan/src/integrationTest/java/org/apache/geode/internal/cache/wan/misc/WANConfigurationJUnitTest.java
- Removed references to the deprecated AttributesFactory from the
geode-wan module.
- Reduced default configured off-heap size in WanTestBase to 128m.
=> GEODE-7160: Remove AttributesFactory in geode-wan

geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySender.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/InternalGatewaySender.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/concurrent/ConcurrentSerialGatewaySenderOperationsDUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/concurrent/ConcurrentSerialGatewaySenderOperationsDistributedTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/concurrent/ConcurrentSerialGatewaySenderOperationsOffHeapDUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/concurrent/ConcurrentSerialGatewaySenderOperationsOffHeapDistributedTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderOperationsDUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderOperationsDistributedTest.java
GEODE-6731: Cleanup SerialGatewaySenderOperationsDUnitTest (and its subclasses)
* Inline super class to make the test easier to read and debug
* Minimize what needs to be overridden in concurrent subclasses
* Remove all statics
* Convert all VM invocations into lambdas
* Rename and reorder fields, vars, and methods
* Add getEventQueueSize to InternalGatewaySender interface
Please review @aaronlindsey 
Note: I couldn't find the actual cause of flakiness in SerialGatewaySenderOperationsDUnitTest but the test and its subclasses were a total mess.
=> GEODE-6731: Cleanup SerialGatewaySenderOperationsDUnitTest

dev-tools/release/commit_rc.sh, dev-tools/release/deploy_rc_pipeline.sh, dev-tools/release/prepare_rc.sh
- Detect SHA sum utility on Mac OS (shasum vs. sha512sum)
=> GEODE-7296: Fix Geode release scripts

geode-core/src/main/java/org/apache/geode/management/internal/configuration/converters/GatewayReceiverConverter.java, geode-core/src/test/java/org/apache/geode/management/internal/configuration/converters/GatewayReceiverConverterTest.java
Added unit test for GatewayReceiverConverter.
GatewayReceiverConverter now handles the transport filters.
=> GEODE-7278: convert transport filters

geode-web-api/src/integrationTest/java/org/apache/geode/rest/internal/web/controllers/GetOrderDescriptionFunction.java, geode-web-api/src/integrationTest/java/org/apache/geode/rest/internal/web/controllers/RestAccessControllerTest.java
=> GEODE-7287: Add test to REST function exec with a filter

geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/CacheCommonTagsTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/ClientCacheCommonTagsTest.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/InternalClientCache.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalCacheBuilder.java, geode-core/src/main/java/org/apache/geode/internal/metrics/CacheMeterRegistryFactory.java, geode-core/src/main/java/org/apache/geode/internal/metrics/CompositeMeterRegistryFactory.java, geode-core/src/test/java/org/apache/geode/internal/cache/GemFireCacheImplTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/InternalCacheBuilderTest.java, geode-core/src/test/java/org/apache/geode/internal/metrics/CacheMeterRegistryFactoryBindersTest.java, geode-core/src/test/java/org/apache/geode/internal/metrics/CacheMeterRegistryFactoryTest.java
* Do not include member meter tag if member name is missing
* Do not include cluster meter tags in a client
=> GEODE-7291: Prevent empty micrometer tags

geode-core/src/test/java/org/apache/geode/distributed/ServerLauncherTest.java
Use disable-default-server to prevent binding to default port in unit
test.
=> GEODE-7328: Prevent BindExceptions in ServerLauncherTest

geode-management/src/test/script/update-management-wiki.sh
* only runs on a mac
* automatically updates the correct page, depending whether run on master or develop
The following pages were generated using this script:
https://cwiki.apache.org/confluence/display/GEODE/1.10.0+Management+REST+API+-+experimental
https://cwiki.apache.org/confluence/display/GEODE/develop+Management+REST+API+-+experimental
=> GEODE-7205: add script to auto-generate wiki docs for management REST API

ci/pipelines/geode-build/jinja.template.yml, ci/scripts/attach_sha_to_branch.sh
Use `git merge-base --is-ancestor <old> <new>` to check that the SHA we
publish as 'passing' is moving forward in git history.
=> GEODE-7281: UpdatePassingTokens only moves git sha forward.

geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/TomcatSessionBackwardsCompatibilityTomcat7079WithOldModuleCanDoPutsTest.java, geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/TomcatSessionBackwardsCompatibilityTomcat7079WithOldModulesMixedWithCurrentCanDoPutFromCurrentModuleTest.java, geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/TomcatSessionBackwardsCompatibilityTomcat7079WithOldModulesMixedWithCurrentCanDoPutFromOldModuleTest.java, geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/TomcatSessionBackwardsCompatibilityTomcat8WithOldModuleCanDoPutsTest.java, geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/TomcatSessionBackwardsCompatibilityTomcat8WithOldModulesMixedWithCurrentCanDoPutFromCurrentModuleTest.java, geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/TomcatSessionBackwardsCompatibilityTomcat8WithOldModulesMixedWithCurrentCanDoPutFromOldModuleTest.java
These tests keep failing for reasons that are not clear
and further not clearly related to any changes.
=> GEODE-7336: Pulling failing tests during investigation.

geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/function/executions/FunctionExecutionsTimerClusterTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/function/executions/FunctionExecutionsTimerLonerTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/function/executions/FunctionExecutionsTimerNoResultTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/function/executions/FunctionToTimeWithResult.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/function/executions/FunctionToTimeWithoutResult.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/function/executions/ThreadSleep.java
`Thread.sleep()` is not guaranteed to sleep for the given duration. Add new method for testing which sleeps for at least as long as the given duration.
Here is an example of the type of failures that are currently happening in the Windows acceptance test jobs:
```
org.apache.geode.metrics.function.executions.FunctionExecutionsTimerClusterTest > timersRecordCountAndTotalTime_ifFunctionExecutedOnReplicateRegion FAILED
java.lang.AssertionError: [Total time of function executions across all servers] 
Expecting:
<9.99305729E8>
to be between:
[1.0E9, 2.0E9]
at org.apache.geode.metrics.function.executions.FunctionExecutionsTimerClusterTest.timersRecordCountAndTotalTime_ifFunctionExecutedOnReplicateRegion(FunctionExecutionsTimerClusterTest.java:171)
```
This change prevents these failures by …
=> GEODE-7184: Fix failing Windows acceptance tests

geode-core/src/test/java/org/apache/geode/distributed/internal/tcpserver/TcpServerDependenciesTest.java
- Created an ArchUnit test that TcpServer only depends on geode-serialization
and geode-logging. This test currently has many TODOs, which represent
dependencies that need to be broken.
=> GEDOE-7172: Initial work to break TcpServer dependencies on geode-core.

geode-core/src/main/java/org/apache/geode/management/internal/FederatingManager.java, geode-core/src/test/java/org/apache/geode/management/internal/FederatingManagerTest.java
* Catch and ignore CancelException in removeMemberArtifacts
* Add try-catch around call to memberDeparted
* Handle both CancelException and RegionDestroyedException
* Fix unfinished test in FederatingManagerTest
* Add more test cases to FederatingManagerTest
=> GEODE-7084: Prevent CancelException in FederatingManager

geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImplJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TCPClientSSLIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TCPServerSSLJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TcpServerJUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java, geode-core/src/main/java/org/apache/geode/distributed/internal/PrimaryHandler.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ProtocolCheckerImpl.java, geode-core/src/main/java/org/apache/geode/distributed/internal/RestartableTcpHandler.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ServerLocator.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/adapter/GMSLocatorAdapter.java, geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/ProtocolChecker.java, geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpHandler.java, geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpServer.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/TcpServerFactory.java, geode-core/src/main/java/org/apache/geode/management/internal/JmxManagerLocator.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/handlers/ClusterManagementServiceInfoRequestHandler.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/handlers/SharedConfigurationStatusRequestHandler.java, geode-core/src/test/java/org/apache/geode/distributed/internal/tcpserver/TcpServerDependenciesTest.java
- Removed DistributedSystem, GemFireCache,
InternalConfiguratinPersistenceService dependencies that were used in the
restarting method. Now there is a RestartableTcpHandler that lives inside core
and extends TcpHandler. Core directly calls restarting on the
RestartableTcpHandler.
- Extracted ProtocolChecker interface to remove Protobuf dependency.
=> GEODE-7348: Removing dependencies on core god classes from TcpServer

geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/CacheGetsTimerTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/function/executions/FunctionExecutionsTimerNoResultTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/CachePerfStats.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/RegionPerfStats.java, geode-core/src/main/java/org/apache/geode/internal/cache/RegionStats.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Get70.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/GetEntry70.java, geode-core/src/test/java/org/apache/geode/internal/cache/RegionPerfStatsTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/Get70Test.java, geode-junit/src/main/java/org/apache/geode/test/assertj/Conditions.java, geode-junit/src/main/java/org/apache/geode/test/micrometer/AbstractMeterAssert.java, geode-junit/src/main/java/org/apache/geode/test/micrometer/TimerAssert.java
- Add timers to record get operations from a Java client
- Tag each timer with region name and result (hit/miss)
- Close existing entries gauge when closing `RegionPerfStats`
- Improve micrometer assertj assertions
=> GEODE-7326: Add cache gets timers

geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/internal/CqSecurityExecutionContextTamperingDistributedTest.java
- Use 'await().untilAsserted()' instead of direct assertion when
checking amount of events and errors received by the CQListerer.
=> GEODE-7360: Fix Flaky Cq Security Test

geode-docs/reference/topics/gemfire_properties.html.md.erb
Rewriting the documentation for the member-timeout property. The old
documentation did to accurately describe the health check process or the
amount of time it would take to remove an unresponsive member.
=> GEODE-7357: Updating the documentation for member-timeout

geode-dunit/src/main/java/org/apache/geode/test/greplogs/LogConsumer.java, geode-dunit/src/main/java/org/apache/geode/test/greplogs/Patterns.java, geode-dunit/src/test/java/org/apache/geode/test/greplogs/LogConsumerTest.java
This prevents "hydra.MasterDescription.master.locators={}" from being suspected as a malformed log4j message.
=> GEODE-7350: Do not suspect hydra.MasterDescription.master.locators={}

ci/pipelines/shared/jinja.variables.yml
this will hopefully alleviate timeouts such as https://concourse.apachegeode-ci.info/teams/main/pipelines/apache-develop-main/jobs/DistributedTestOpenJDK8/builds/1231
=> GEODE-7365: increase DistributedTest timeout by 45m (to 3h)

geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/CacheGetsTimerTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/GatewayReceiverMetricsTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/MemberTypeCommonTagsTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/MicrometerBinderTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/RegionEntriesGaugeTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/function/executions/FunctionExecutionsTimerClusterTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/function/executions/FunctionExecutionsTimerLonerTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/metrics/function/executions/FunctionExecutionsTimerNoResultTest.java, geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/GfshExecution.java
Some metrics acceptance tests uses hard-coded ports, and others used
default ports for various processes. This caused failures in CI on
Windows.
These tests have been updated to allocate random ports.
=> GEODE-7375: Fix metrics test port allocation

ci/pipelines/shared/jinja.variables.yml
AcceptanceTest has started timing out a lot, with no apparent hang, just tests are still running.  Successful runs were coming in just barely under the timeout.  This increases the timeout to give acceptance tests more time to finish.
=> GEODE-7365: Increase AcceptanceTest timeout by 30m to 1h30m

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TCPClientSSLIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TCPServerSSLJUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpServer.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/TcpServerFactory.java, geode-core/src/test/java/org/apache/geode/distributed/internal/tcpserver/TcpServerDependenciesTest.java
[GEODE-7361](https://issues.apache.org/jira/browse/GEODE-7361)
As part of the effort to sever dependencies on `geode-core` in `geode-membership` we are severing ties on `geode-core` in `TcpServer`. This PR eliminates two such dependencies on `geode-core` in `TcpServer`:
* `PoolStatsHelper`
* `CoreLoggingExecutors`
Formerly, the `TcpServer` constructor took a `PoolStatHelper poolHelper` parameter. `TcpServer` retained that parameter. It then constructed a new `ExecutorService` via `CoreLoggingExecutors.newThreadPoolWithSynchronousFeed()`. In the `TcpServer.restarting()` method it also had to create an `ExecutorService` the same way.
This PR changes the `TcpServer` constructor to take a `Supplier<ExecutorService>`. That supplier hides both the `PoolStatHelper` class and the …
=> GEODE-7361: sever ties to PoolStatHelper & CoreLoggingExecutors

geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/TomcatSessionBackwardsCompatibilityTomcat7079WithOldModulesMixedWithCurrentCanDoPutFromCurrentModuleTest.java
=> GEODE-7367: Unignored Tomcat7079WithOldModulesMixedWithCurrentCanDoPutFromCurrentModuleTest

geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/TomcatSessionBackwardsCompatibilityTomcat7079WithOldModulesMixedWithCurrentCanDoPutFromOldModuleTest.java
=> GEODE-7367: Unignored Tomcat7079WithOldModulesMixedWithCurrentCanDoPutFromOldModuleTest

geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/TomcatSessionBackwardsCompatibilityTomcat8WithOldModulesMixedWithCurrentCanDoPutFromOldModuleTest.java
=> Geode 7367: Remove Ignore annotation for TomcatSessionBackwardsCompatibilityTomcat8WithOldModulesMixedWithCurrentCanDoPutFromOldModuleTest

geode-core/src/main/java/org/apache/geode/management/internal/cli/remote/MemberCommandService.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/remote/MemberCommandServiceTest.java
Added test to replicate the issue and fixed code so that `ResultModel` is wrapped in `CommandResult` to fix the issue
=> GEODE-7374: Fix class cast exception

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ClientServerNotColocatedTransactionDistributedTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXState.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXStateProxyImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/tx/PartitionedTXRegionStub.java, geode-core/src/test/java/org/apache/geode/internal/cache/TXStateProxyImplTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/tx/PartitionedTXRegionStubTest.java
* Able to detect not colocated transaction if it is caused by the first operation on a
replicate region and then on a partitioned region.
* Make sure transaction host can detect this and throw TransactionDataNotColocatedException.
* Transaction host will throw appropriate TransactionException based on the operations
exectued.
* Remote non host will rely on the TransactionException thrown from the tx host.
=> GEODE-7273: Able to detect not colocated transaction

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TcpServerJUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InfoRequestHandler.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java, geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpServer.java, geode-core/src/test/java/org/apache/geode/distributed/internal/tcpserver/TcpServerDependenciesTest.java
- Creating a handler for TcpClient InfoRequests.
- Handler is added to the PrimaryHandler's list of handlers
=> GEODE-7358: Remove TcpServer's dependencies on GemFireVersion

geode-core/src/main/java/org/apache/geode/SystemFailure.java
[GEODE-7369](https://issues.apache.org/jira/browse/GEODE-7369)
Deprecate SystemFailure class.
=> GEODE-7369: Deprecate SystemFailure Class

geode-core/src/main/java/org/apache/geode/cache/query/security/JavaBeanAccessorMethodAuthorizer.java, geode-core/src/test/java/org/apache/geode/cache/query/security/JavaBeanAccessorMethodAuthorizerTest.java
=> GEODE-7396: Fixed incorrect regex in JavaBeanAccessorMethodAuthorizer

geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PersistenceAdvisorImpl.java, geode-core/src/test/java/org/apache/geode/internal/cache/persistence/PersistenceAdvisorImplTest.java
* Always remove old Persistent Member Id if persisting its new Id.
=> GEODE-7384: Members's old Persistent Member Id should be removed

boms/geode-all-bom/src/test/resources/expected-pom.xml, buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy, geode-assembly/src/integrationTest/resources/assembly_content.txt, geode-assembly/src/integrationTest/resources/dependency_classpath.txt
Upgrading ClassGraph from 4.0.6 to 4.8.52 fixes a memory leak that
appeared after introducing geode-log4j even though logging does not
use ClassGraph.
=> GEODE-7370: Upgrade ClassGraph to 4.8.52

geode-dunit/src/main/java/org/apache/geode/internal/cache/CommitFunction.java, geode-dunit/src/main/java/org/apache/geode/internal/cache/NestedTransactionFunction.java, geode-dunit/src/main/java/org/apache/geode/internal/cache/PartitionedRegionGetSomeKeys.java, geode-dunit/src/main/java/org/apache/geode/internal/cache/RollbackFunction.java
These test functions should not use an internal logging API.
=> GEODE-7399: Use LogManager instead of LogService in test functions

ci/pipelines/examples/jinja.template.yml, ci/pipelines/meta/deploy_meta.sh, ci/scripts/create_instance.sh
* fix geode-examples resource to pull from upstream fork.
* fetch alpine-tools-image before creating the instance.
=> Clean up deploy_meta.sh and don't get sha if geode's not there.

geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/LocatorSSLJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TCPClientSSLIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TCPServerSSLJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/internal/SSLConfigIntegrationJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/internal/SSLConfigJUnitTest.java, geode-core/src/main/java/org/apache/geode/admin/internal/AdminDistributedSystemImpl.java, geode-core/src/main/java/org/apache/geode/internal/admin/SSLConfig.java, geode-core/src/main/java/org/apache/geode/internal/admin/remote/DistributionLocatorId.java, geode-core/src/main/java/org/apache/geode/internal/admin/remote/RemoteTransportConfig.java, geode-core/src/main/java/org/apache/geode/internal/net/SSLConfigurationFactory.java, geode-core/src/main/java/org/apache/geode/internal/net/SocketCreatorFactory.java, geode-core/src/main/java/org/apache/geode/management/internal/JmxManagerAdvisee.java, geode-core/src/test/java/org/apache/geode/internal/net/SSLConfigurationFactoryJUnitTest.java, geode-core/src/test/java/org/apache/geode/internal/net/SocketCreatorJUnitTest.java, geode-http-service/src/test/java/org/apache/geode/management/internal/InternalHttpServiceJunitTest.java, geode-protobuf/src/integrationTest/java/org/apache/geode/internal/protocol/protobuf/v1/acceptance/CacheConnectionIntegrationTest.java, geode-protobuf/src/integrationTest/java/org/apache/geode/internal/protocol/protobuf/v1/acceptance/CacheOperationsJUnitTest.java, geode-pulse/geode-pulse-test/src/main/java/org/apache/geode/tools/pulse/tests/rules/ServerRule.java, geode-wan/src/test/java/org/apache/geode/internal/cache/wan/GatewaySenderEventRemoteDispatcherIntegrationTest.java
SSLConfig and SSLConfigFactory have been changed to be
tread-safe by means of the following:
* SSLConfig has been converted into an immutable class
* The registeredSSLConfig HashMap member of SSLConfigurationFactory
has been changed into a ConcurrentHashMap and accesses to this
map other than put and get has been synchronized.
=> GEODE-7157: SSLConfig&SSLConf..Factory thread-safe

ci/pipelines/examples/jinja.template.yml, ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/pull-request/jinja.template.yml
directory
Update geode-ci resource declarations to look for changes in all of the
ci directory.
=> GEODE-7383: geode-ci concourse resource doesn't care about all of ci

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/backup/IncrementalBackupDistributedTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupService.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/CacheRule.java
*  The test can hang if the backup task is nulled out but hasn't countdown(ed) the latch.  This state was possible due to the test not waiting for a cache to be completely closed before executing a backup.  So the fix is to abort the task (countdown the latch) and also modify the test not to get into this state.
* Added membership listener to test to have member departed callback before starting backup
=> GEODE-7310: Aborting backup when member departs

ci/pipelines/pull-request/jinja.template.yml
since branch protection requires them always now
=> GEODE-7417: never skip triggering of PR checks

ci/pipelines/geode-build/jinja.template.yml
Allows re-triggering due to network or other glitches without so many
button-clicks.
=> Trigger downstream CI jobs on build-number changes as well as SHA.

geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/RegionAttributesCreation.java, geode-lucene/geode-lucene-test/src/main/java/org/apache/geode/cache/lucene/test/LuceneTestUtilities.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneIndexForPartitionedRegion.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneRegionListener.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/LuceneIndexForPartitionedRegionTest.java
- Removed references to the deprecated AttributesFactory from the
geode-lucene module.
=> GEODE-7162: Remove AttributesFactory in geode-lucene

geode-assembly/src/distributedTest/java/org/apache/geode/rest/internal/web/controllers/RestAPIsOnGroupsFunctionExecutionDUnitTest.java
This is one the commits to remove the deprecated 'AttributesFactory'
class from the geode-assembly module. The work is splitted to avoid
hitting issues in CI.
- Replaced usages of 'junit.Assert' by 'assertj'.
=> GEODE-7407: Remove AttributesFactory (4/4)

geode-assembly/src/distributedTest/java/org/apache/geode/rest/internal/web/controllers/RestAPITestBase.java, geode-assembly/src/distributedTest/java/org/apache/geode/rest/internal/web/controllers/RestAPIsOnMembersFunctionExecutionDUnitTest.java
This is one the commits to remove the deprecated 'AttributesFactory'
class from the geode-assembly module. The work is splitted to avoid
hitting issues in CI.
- Replaced usages of 'junit.Assert' by 'assertj'.
- Replaced usages of 'JUnit4DistributedTestCase' by Geode test rules.
=> GEODE-7407: Remove AttributesFactory (3/4)

geode-assembly/src/distributedTest/java/org/apache/geode/rest/internal/web/controllers/RestAPIOnRegionFunctionExecutionDUnitTest.java
This is one the commits to remove the deprecated `AttributesFactory`
class from the geode-assembly module. The work is splitted to avoid
hitting issues in CI.
- Replaced usages of 'junit.Assert' by 'assertj'.
- Removed references to the deprecated AttributesFactory class from
the RestAPIOnRegionFunctionExecutionDUnitTest class.
=> GEODE-7407: Remove AttributesFactory (1/4)

geode-core/src/distributedTest/java/org/apache/geode/management/internal/MBeanFederationErrorHandlingDistributedTest.java, geode-core/src/integrationTest/java/org/apache/geode/management/internal/FederatingManagerConcurrencyIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/management/internal/FederatingManagerIntegrationTest.java, geode-core/src/main/java/org/apache/geode/management/internal/FederatingManager.java, geode-core/src/main/java/org/apache/geode/management/internal/FederatingManagerFactory.java, geode-core/src/main/java/org/apache/geode/management/internal/SystemManagementService.java, geode-core/src/test/java/org/apache/geode/management/internal/FederatingManagerTest.java
Commit f0c96db changed the `FederatingManager` class so that it reuses the same `ExecutorService` between restarts. After that change, if we start the manager after previously starting and stopping it, we get `RejectedExecutionException` because it tries to invoke a task on the same `ExecutorService` which has been shut down.
This PR changes the `FederatingManager` so that it invokes a supplier to get a new `ExecutorService` each time it is started to prevent the `RejectedExecutionException`.
=> GEODE-7400: Prevent RejectedExecutionException in FederatingManager

ci/pipelines/geode-build/jinja.template.yml
For example, https://concourse.apachegeode-ci.info/teams/main/pipelines/apache-develop-main/jobs/Benchmark/builds/677 failed because there were already 3 benchmarks jobs running at the time.
Since the quota is 40 and each benchmark job uses 12, this PR restricts `max_in_flight` to `3`
=> GEODE-7431: limit Benchmarks to three-at-a-time to stay within quota

geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/DUnitLauncher.java
- Make sure that log4j is being used as the logging provider.
=> GEODE-7427: Avoid failure when configuring DUnit suspect logging

dev-tools/release/promote_rc.sh
Updates release scripts to publish the Native docker image too, as suggested by @alb3rtobr 
Notes: www.apache.org is used for geode because it is the only mirror that will have it at this point in the release process, while archive.apache.org is selected for rat because some versions we use are too old to expect on closer.cgi mirrors.  These links are patched on the fly to allow the release scripts to continue to work with older branches too.
The resulting Dockerfile is committed back to master, but I'm not sure if or how develop should be affected as a result of a release...
=> GEODE-7440: Automate build and publish of Native docker image

extensions/geode-modules/src/integrationTest/java/org/apache/geode/modules/session/catalina/callback/SessionExpirationCacheListenerIntegrationTest.java
- Fixed flakiness in SessionExpirationCacheListenerIntegrationTest.
=> GEODE-7453: Fix Flaky Test

geode-core/src/main/java/org/apache/geode/internal/net/NioSslEngine.java, geode-core/src/test/java/org/apache/geode/internal/net/NioSslEngineTest.java, geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientTestCase.java
The expansion logic for the decrypted buffer in NioSslEngine was
expanding the buffer to twice its old capacity and wouldn't go
beyond that.  Some ciphers will compress data a lot more than that, so
we need to continually increase available space in the decryption buffer
if the SslEngine reports a BUFFER_OVERFLOW status.  The changes in
this commit do that by always doubling the available space in the
decryption buffer in response to a BUFFER_OVERFLOW.
Along with that I found it unnecessary to take preemptive action to
increase the size of the buffer and deleted that code.
Please ensure that once the PR is submitted, check …
=> GEODE-7450 SSL peerAppDataBuffer expansion needs work

geode-dunit/src/distributedTest/java/org/apache/geode/test/greplogs/LogConsumerDistributedTest.java, geode-dunit/src/test/java/org/apache/geode/test/greplogs/LogConsumerTest.java
Adds new tests for all log levels within all DUnit VM types to verify
that the DUnit grep for suspect strings mechanism works as expected.
Add LogConsumer unit and distributed tests for context initialization
failed with underlying ClassNotFoundException.
NOTE: GEODE-7403 is closed but I'd like to merge in these new tests
for LogConsumer.
=> GEODE-7403: Add LogConsumer distributed tests

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/backup/IncrementalBackupDistributedTest.java, geode-core/src/integrationTest/java/org/apache/geode/internal/cache/backup/IncrementalBackupIntegrationTest.java, geode-core/src/main/java/org/apache/geode/internal/ClassPathLoader.java, geode-core/src/main/java/org/apache/geode/internal/JarDeployer.java, geode-core/src/main/java/org/apache/geode/internal/admin/remote/MissingPersistentIDsRequest.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/FileSystemIncrementalBackupLocation.java, geode-core/src/main/java/org/apache/geode/internal/util/TransformUtils.java
* Extract integration tests from IncrementalBackupDistributedTest
* Use TemporaryFolder for deploy directory
* Reduce unnecessary VM invocations in the DistributedTest
I also touched up some product code:
• Improved toString on ClassPathLoader and JarDeployer for debugging
• Removed an unnecessary cast of DistributionManager to ClusterDistributionManager (prevented testing the behavior with a loner)
• Replaced public static variable in TransformUtils with a public static getter
Verify that [6d3f82](https://github.com/apache/geode/commit/6d3f82) fixes GEODE-7252, GEODE-7293 and GEODE-7310.
=> GEODE-7252: Create IncrementalBackupIntegrationTest

geode-core/src/distributedTest/java/org/apache/geode/cache/client/internal/LocatorLoadBalancingDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/tcpserver/TcpServerBackwardCompatDUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImplJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/LocatorIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/MembershipJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocatorIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocatorRecoveryIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TCPClientSSLIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TCPServerSSLJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TcpServerJUnitTest.java, geode-core/src/main/java/org/apache/geode/admin/internal/DistributionLocatorConfigImpl.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImpl.java, geode-core/src/main/java/org/apache/geode/distributed/LocatorLauncher.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/adapter/GMSLocatorAdapter.java, geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/InfoResponse.java, geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpClient.java, geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpServer.java, geode-core/src/main/java/org/apache/geode/internal/DistributionLocator.java, geode-core/src/main/java/org/apache/geode/internal/SystemAdmin.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/TcpServerFactory.java, geode-core/src/main/java/org/apache/geode/management/internal/JmxManagerLocatorRequest.java, geode-core/src/main/java/org/apache/geode/management/internal/api/GeodeClusterManagementServiceBuilder.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/utils/ClusterConfigurationStatusRetriever.java, geode-core/src/test/java/org/apache/geode/distributed/internal/tcpserver/TcpServerDependenciesTest.java, geode-wan/src/main/java/org/apache/geode/cache/client/internal/locator/wan/LocatorDiscovery.java, geode-wan/src/main/java/org/apache/geode/cache/client/internal/locator/wan/LocatorMembershipListenerImpl.java, geode-wan/src/main/java/org/apache/geode/internal/cache/wan/AbstractRemoteGatewaySender.java
This PR implements the first half of [GEODE-7344](https://issues.apache.org/jira/browse/GEODE-7344), to wit, eliminating dependencies on `DataSerializer` from classes in the `org.apache.geode.distributed.internal.tcpserver` package.
The main change is that now we are injecting an `ObjectSerializer` and an `ObjectDeserializer` into the `TcpClient` constructor in order to break the dependency from the latter to the `DataSerializer` class. Also `TcpServer` got the same treatment!
I'd like to get this approved and merged before tackling the harder second half (eliminating dependencies on `DataSerializable`).
email to …
=> GEODE-7344: break dependencies on DataSerializer

ci/pipelines/images/jinja.template.yml
=> GEODE-7338: Trigger test container builds on bionic-scm, not openjdk-8

ci/scripts/create_instance.sh
Increasing the time-to-live value to 12 hrs as the new tests take longer
than 6 hrs. And as this value is used to delete heavy-lifter instance it
might to be too close to kill them.
=> GEODE-7448: Increase heavy-lifter instance time-to-live value

geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/TomcatContainer.java
* Currently only proxy session region is being tested. We should be able to
test caching proxy as well for Tomcat as caching proxy is the default setting.
=> GEODE-7477: Allow tests to test different client/server settings.

geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/index/IndexManagerIntegrationTest.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/IndexManager.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/index/IndexManagerTest.java
- Added unit and integration tests for the IndexManager class.
- Fixed IndexManager to mark indexes as invalid whenever there's an
exception while adding or removing a mapping from the index.
=> GEODE-7486: Fix IndexManager

ci/scripts/execute_build.sh, ci/scripts/execute_tests.sh
Adding the ServerAliveCountMax as a additional property for long
standing ssh remote commands.This will help in intermittent
disconnections which happen during peak hours.
=> GEODE-7488: Add ServerAliveCountMax to the ssh options.

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/xmlcache/CacheXmlGeneratorIntegrationTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/RegionAttributesCreation.java
- Do not automatically override the 'off-heap' property when
configuring the 'PartitionAttributes' declaratively.
=> GEODE-7442: Fix RegionAttributesCreation

geode-junit/src/test/java/org/apache/geode/test/junit/rules/ExpectedTimeoutRuleTest.java
Use GeodeAwaitility timeout for larger timeout values.
The actual fix is to use GeodeAwaitility timeout (5 minutes) for expectMaximumDuration:
```
timeout.expectMaximumDuration(TIMEOUT_MILLIS);
```
On this branch, ExpectedTimeoutRuleTest passes 1000 dunitrunner runs as well as cross-section 16 1000.
=> GEODE-7137: Fix ExpectedTimeoutRuleTest

geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedNoAckRegionCCEDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PRQueryWithIndexDistributedTest.java, geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/tests/AsyncInvocationTimeoutDistributedTest.java, geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/tests/BasicDistributedTest.java, geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/tests/StackTraceDistributedTest.java, geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/tests/VMDumpThreadsDistributedTest.java, geode-dunit/src/main/java/org/apache/geode/cache30/CacheSerializableRunnable.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/AsyncInvocation.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/DUnitEnv.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/RMIException.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/SerializableCallable.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/SerializableRunnable.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/SerializableRunnableIF.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/VM.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/AsyncThreadId.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/Identifiable.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/IdentifiableCallable.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/IdentifiableRunnable.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/Invocable.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/RemoteDUnitVM.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/StackTrace.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/StackTraceInfo.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/StandAloneDUnitEnv.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
Update AsyncInvocation and dunit with these changes:
1) Add stack trace of remote thread as the cause of an AsyncInvocation TimeoutException.
2) Clean up AsyncInvocation and SerializableRunnable/SerializableCallable hierarchy of classes.
3) New tests for StackTrace, VM.dumpThreads, and AsyncInvocation asyncTimeoutHandler.
4) Deprecate and reorganize some additional dunit methods that are either not used or have a newer preferred alternative.
5) Trigger remote VM to dump all threads to stdout when an AsyncInvocation times out.
Presently, when an AsyncInvocation times out, it throws a TimeoutException that doesn't really provide enough information to debug the underlying cause.
The current stack trace of a TimeoutException thrown from AsyncInvocation looks like:
``` …
```
=> GEODE-7475: Include remote stack trace in AsyncInvocation timeout

geode-core/src/distributedTest/java/org/apache/geode/cache/client/internal/AutoConnectionSourceDUnitTest.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImpl.java, geode-dunit/src/main/java/org/apache/geode/cache/client/internal/LocatorTestBase.java
fixed an issue where the test was not waiting for getOnlineLocators' value
to become 1. It can take a moment to update.
=> GEODE-6616: fix testClientDynamicallyDropsStoppedLocator

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitor.java
* Use computeIfAbsent to construct TimeStamp and avoid locking
behavior in Java 8.
=> GEODE-7434: Remove unnecessary locking and allocations.

geode-core/build.gradle, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/DistributionArchUnitTest.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/MembershipDependenciesJUnitTest.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/gms/api/MembershipAPIArchUnitTest.java, geode-core/src/test/java/org/apache/geode/distributed/internal/tcpserver/TcpServerDependenciesTest.java, geode-serialization/src/test/java/org/apache/geode/internal/serialization/SerializationDependenciesJUnitTest.java
Added archive excludes to all membership arch unit tests.  Moved
DistributionArchUnitTest to integrationTests and added an exclude
for another integration test to it.
=> GEODE-7489 DistributionArchUnitTest is running out of memory for some users

geode-docs/managing/security/implementing_authorization.html.md.erb
I only found one item on the wiki that did not have the proper permission listed in the docs.
=> GEODE-7212: update docs permission for CqQuery.stop()

geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/DefaultQuerySecurityIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/DefaultQueryServiceIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/ExecutionContextIntegrationTest.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/DefaultQueryService.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/ExecutionContext.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/cq/ServerCQ.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/AttributeDescriptorTest.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/CompiledAggregateFunctionTest.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/ExecutionContextTest.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/MethodDispatchTest.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/NWayMergeResultsTest.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/QCompilerTest.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/QueryExecutionContextTest.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/index/CompactRangeIndexTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionQueryEvaluatorTest.java, geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/ServerCQImpl.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/internal/ServerCQImplTest.java
- Added unit and integration tests.
- Implemented method to invalidate the cache used by CQs.
- Updated the context implementation to change the internal
MethodInvocationAuthorizer used whenever the CQ resets the
ExecutionContext.
=> GEODE-7487: Update Running CQ Context

geode-docs/managing/security/implementing_authorization.html.md.erb
The previous PR for this change contained an error.  New PR to correct the error. DATA:MANAGE:QUERY was incorrect.  CLUSTER:MANAGE:QUERY is the correct permission listed in our wiki.
=> GEODE-7212: Docs update of CLUSTER:MANAGE:QUERY for CqQuery.stop()

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/AlterQueryServiceCommandWithSecurityDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/AlterQueryServiceCommandWithoutSecurityDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DescribeQueryServiceCommandDUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/DefaultQuerySecurityIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/DefaultQueryServiceDeprecationTest.java, geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/ExecutionContextIntegrationTest.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/QueryConfigurationService.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/QueryConfigurationServiceImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheCreation.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/AlterQueryServiceCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/AlterQueryServiceFunction.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/QueryConfigurationServiceImplTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/AlterQueryServiceCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/AlterQueryServiceFunctionTest.java, geode-cq/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/AlterQueryServiceCommandDistributedTest.java, geode-docs/tools_modules/gfsh/command-pages/alter.html.md.erb
The QueryConfigurationService now requires an extra flag to determine,
in the presence of continuous queries, whether to update the configured
MethodInvocationAuthorizer and invalidate the CQ's internal cache or
throw an exception and abort the update.
- Updated docs for alter query-service command.
- Added 'forceUpdate' flag to 'AlterQueryServiceFunction' and
'AlterQueryServiceCommand'.
- Fixed 'AlterQueryServiceCommand' to always require the
'method-authorizer' parameter.
submit an …
=> GEODE-7497: Check CQs prior to change authorizer

geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/GatewayManagementControllerSpringTest.java, geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/MemberManagementControllerSpringTest.java, geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RebalanceOperationControllerSpringTest.java, geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RegionManagementControllerSpringTest.java, geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/GatewayManagementController.java, geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/MemberManagementController.java, geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RebalanceOperationController.java, geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RegionManagementController.java
By default, when Spring parses a request mapping parameter at the end of a URL, it treats the last dot in the paramater value to be the start of a file extension, and discards the 'extension" before passing the parameter to the handler method.
Several of our configurable items allow dots in their IDs. And several of our REST request mappings place those IDs at the end of the URL. In those cases, Spring's default behavior truncates the ID at the last dot, and passes the truncated ID to the request handler. As a result, the request fails.                                                
This commit configure all current management REST API request mappings to allow dots in their final parameters. …
=> GEODE-7485: REST URLs accept dots in trailing parameters

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/PersistentColocatedPartitionedRegionDistributedTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/colocation/SingleThreadColocationLogger.java, geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/colocation/SingleThreadColocationLoggerTest.java
Move flaky test coverage from distributed test to unit test.
Add more unit tests to SingleThreadColocationLoggerTest.
The assertions that now fail intermittently in this test on develop
are easier to test in a low level unit test.
=> GEODE-7513: Fix PersistentColocatedPartitionedRegionDistributedTest

geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/examples/DistributedReferenceCacheExampleTest.java, geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/examples/DistributedReferenceLocatorLauncherExampleTest.java, geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/examples/DistributedReferenceServerLauncherExampleTest.java, geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/examples/DistributedReferenceSystemExampleTest.java, geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedReferenceTest.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedReference.java
JUnit Rule that provides a static reference in every distributed test
VMs including the main JUnit controller VM. If the referenced value is
is an AutoCloseable or Closeable then it will be auto-closed in every
VM during tear down.
If the referenced value is not an AutoCloseable or Closeable, the
DistributedReference will use reflection to invoke any method named
close or disconnect regardless of what interfaces are implemented.
If the referenced value is null in any VM then it will be ignored in
that VM during tear down.
To disable auto-close, simply specify autoClose(false).
See the javadocs on DistributedReference for more info.
=> GEODE-5644: Add new DistributedReference JUnit Rule

geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedExecutorServiceRuleTest.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedExecutorServiceRule.java, geode-junit/src/test/java/org/apache/geode/test/junit/rules/ExecutorServiceRuleTest.java
JUnit Rule that provides an ExecutorService in every distributed test
VM including the main JUnit controller VM.
See the javadocs on DistributedExecutorServiceRule for more info.
=> GEODE-7526: Add new DistributedExecutorServiceRule JUnit Rule

ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/meta/deploy_meta.sh, ci/pipelines/shared/jinja.variables.yml
To enable more granular re-run in Concourse, split the Benchmarks into
independently triggerable jobs in the main pipeline.
Extract variables from the template into the jinja.variables file.
Make better use of YML anchors.
Co-authored-by: Helena Bales <hbales@pivotal.io>
=> Separate benchmark tasks into jobs.

extensions/geode-modules-session-internal/src/main/java/org/apache/geode/modules/session/internal/common/ClientServerSessionCache.java, extensions/geode-modules-tomcat8/src/distributedTest/java/org/apache/geode/modules/session/Tomcat8SessionsClientServerDUnitTest.java, extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/ClientServerSessionCache.java, extensions/geode-modules/src/test/java/org/apache/geode/modules/session/catalina/ClientServerSessionCacheTest.java, geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/TomcatInstall.java, geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/CargoTestBase.java, geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Tomcat6CachingClientServerTest.java, geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Tomcat7CachingClientServerTest.java, geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Tomcat8CachingClientServerTest.java, geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Tomcat9CachingClientServerTest.java
* register intesest only when local cache is enabled for Tomcat
* add register interest in other app server when local cache is enabled.
* add cache client test cases for tomcat cases.
* modify test to allow gets mutliple times on containers when local cache is enabled
on client cache to verify the fix.
=> GEODE-7478: Register interest in appropriate cases.

ci/pipelines/examples/jinja.template.yml, ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/images/jinja.template.yml, ci/pipelines/pull-request/jinja.template.yml, ci/pipelines/shared/jinja.variables.yml
Instead of immediately launching all jobs at once, this PR evens out the load by setting lower max_in_flight settings for shorter jobs. I estimate this will cut peak load in half without builds taking any longer (for a scenario where 6 commits are in the pipeline at the same time).
Reducing load on concourse is desirable because we tend to have more unexplained rsync failures, etc, when concourse is under heavy load.
Also dial down unnecessarily-high retry counts from `10` to `2`, which rarely helped but greatly increased number of containers when things were already overloaded.
Note: This PR does NOT throttle PR pipeline.
=> GEODE-7540: use max_in_flight to spread out peak load on CI

geode-management/src/test/script/update-management-wiki.sh
updated wiki generator script to name the page with the actual version rather than `develop` so that corresponding documentation can be created with a link that will remain valid through development phase, release phase, and after release.  This helps #4390 avoid awkwardness.
@jmelchio this script change renames https://cwiki.apache.org/confluence/display/GEODE/develop+Management+REST+API+-+v1 to https://cwiki.apache.org/confluence/display/GEODE/1.12.0+Management+REST+API+-+v1
=> GEODE-7522: always put version in REST wiki page title

ci/scripts/rsync_code_down.sh, ci/scripts/rsync_code_up.sh
Reverts apache/geode#4391 as it broke rsync on Windows
=> Revert "rsync all inputs and outputs between the heavy-lifter and concourse"

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/MembershipJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/GMSMembershipJUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/Distribution.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionImpl.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMembership.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/MembershipBuilderImpl.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/api/MemberIdentifier.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/api/Membership.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/api/MembershipBuilder.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/interfaces/Manager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/MembershipDependenciesJUnitTest.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/gms/api/MembershipAPIArchUnitTest.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java
ClusterDistributionManager was only being used to get canonical IDs and
to check for shutdown conditions.  I've modified the CDM to set shutdown
status in membership in its shutdown() method and have modified
membership to just use the current MembershipView (which contains any
surprise members) instead of asking CDM for a canonical ID, which just
grabs said MembershipView and does the same thing.
I haven't added any tests because there are already tests for shutdown/closing conditions in manager/joinleave/CDM tests.
submit an update to your …
=> GEODE-7551: Remove membership API dependency on ClusterDistributionManager

geode-core/src/distributedTest/java/org/apache/geode/cache/query/internal/QueryConfigurationServiceConstraintsDistributedTest.java, geode-cq/src/distributedTest/java/org/apache/geode/cache/query/internal/QueryConfigurationServiceConstraintsDistributedTest.java
Added distributed tests to verify the required constraints are met
whenever the MethodInvocationAuthorizer is changed in runtime.
- Once the authorizer is changed, all queries executed afterwards
should use the newly configured authorizer.
- Once a query execution starts, the authorizer used can not be
changed for that particular query.
- Continuous queries already running should pick up the new authorizer
the next time the query is internally executed to detect whether an
event matches or not. If the CQ has methods not allowed by the newly
configured authorizer, any matching events from that moment on should
invoke 'onError' instead of 'onEvent' on the associated 'CqListener'.
- Indexes should pick up the newly configured authorizer the next time
an entry is added or removed from the …
=> GEODE-7351: OQL Method Authorizer Constraints

geode-core/src/distributedTest/java/org/apache/geode/cache30/ReconnectDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/ClusterDistributionManagerDUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/MembershipJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocatorIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/messenger/GMSQuorumCheckerJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessengerJUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/Distribution.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionImpl.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/NetLocator.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/adapter/GMSLocatorAdapter.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMembership.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/api/Membership.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/interfaces/Messenger.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocator.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/GMSQuorumChecker.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessenger.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/MembershipInformationImpl.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/gms/api/MembershipAPIArchUnitTest.java
Rewrote locator installation to use Membership rather than the "hidden"
Services interface.
I rewrote some tests to stop using the internal interfaces of membership
as well, and along the way saw that JGroupsMessenger was maintaining a
collection of old identifiers that was only being consumed by a test & I
removed it.
submit an update to your PR as …
=> GEODE-7552: Break dependency on Services

ci/images/google-windows-geode-builder/windows-packer.json
May mitigate our loss of connection to instances in the middle of jobs.
=> Disable windows update on heavy-lifter instances.

ci/pipelines/geode-build/jinja.template.yml, ci/scripts/create_instance.sh
Improve cleanup logic in create_instance.sh
Delete any existing instance with our name in all available zones.
=> GEODE-7567: Improve cleanup logic in create_instance.sh

geode-core/src/integrationTest/java/org/apache/geode/management/internal/configuration/mutators/RegionConfigMutatorIntegrationTest.java, geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/CacheConfigurationManager.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/ConfigurationManager.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/DeploymentManager.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/GatewayReceiverConfigManager.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/IndexConfigManager.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/PdxManager.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/mutators/RegionConfigManager.java, geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java, geode-core/src/test/java/org/apache/geode/management/internal/configuration/mutators/IndexConfigManagerTest.java, geode-core/src/test/java/org/apache/geode/management/internal/configuration/mutators/PdxManagerTest.java, geode-core/src/test/java/org/apache/geode/management/internal/configuration/mutators/RegionConfigManagerTest.java, geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/MemberValidatorTest.java
Pass the persistence service to each manager on construction, rather
than passing it to each method.
@jmelchio Please review
=> GEODE-7568: Pass persistence service to config mgr constructors

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ClientCachingProxyRegionDistributedTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionTest.java
Added a try-catch block during basicGetAll to avoid throwing
EntryDestroyedException whenever the value is locally destroyed as a result
of another concurrent region operation (like eviction/expiration).
The  operation will try to retrieve the value from the server as it
regularly does for any entry that doesn't exist locally.
=> GEODE-7535: Prevent exception throw during getAll

geode-core/src/test/java/org/apache/geode/distributed/internal/membership/MembershipDependenciesJUnitTest.java
Follow-on test cleanup for [GEODE-7397](https://issues.apache.org/jira/browse/GEODE-7397). There were 5 dependencies we had eliminated in the PR, but had neglected to remove the ArchUnit clauses for those dependencies. This brings down the total number of clauses to 14.
=> GEODE-7397:  remove spurious archunit clauses

ci/scripts/run_benchmarks.sh
There are still some flaky benchmarks. Retry tests that have failed, up
to 5 times, to determine if the failure is legitimate or just a flaky
test. If the test fails 5 times in a row, we know that it is a
legitimate failure.
With each run of run_against_baseline (in the apache/geode-benchmarks
repo), the class names of all failed tests will be written to a file.
The run_benchmarks script called by CI will read the failed tests from
the file and run only those tests. Once the return code is 0, or once
we've tried 5 times, exit.
submit an …
=> GEODE-7554: Add retry mechanism for failed tests

ci/pipelines/meta/deploy_meta.sh, ci/pipelines/meta/destroy_pipelines.sh, ci/pipelines/metrics/deploy_metrics_pipeline.sh
scripts
Update all the deploy scripts to use team specific fly targets, so that
we do not accidentally deploy to wrong teams.
=> GEODE-7575: Add concourse team specific fly targets in the deploy

geode-core/src/main/java/org/apache/geode/management/internal/FederatingManager.java, geode-core/src/test/java/org/apache/geode/management/internal/FederatingManagerTest.java
FederatingManager should not invoke MBeanProxyFactory.removeAllProxies
when monitoringRegion is null.
=> GEODE-7525: Prevent NPE in MBeanProxyFactory

geode-assembly/src/acceptanceTest/java/org/apache/geode/cache/persistence/MissingDiskStoreAcceptanceTest.java, geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/DistributionAdvisorDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentRecoveryOrderDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentRecoveryOrderOldConfigDUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionAdvisor.java, geode-core/src/main/java/org/apache/geode/internal/admin/remote/MissingPersistentIDsRequest.java, geode-core/src/main/java/org/apache/geode/internal/cache/BucketPersistenceAdvisor.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PersistentBucketRecoverer.java, geode-core/src/main/java/org/apache/geode/internal/cache/persistence/MembershipChangeListener.java, geode-core/src/main/java/org/apache/geode/internal/cache/persistence/MembershipChangeListenerFactory.java, geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PersistenceAdvisorImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PersistenceInitialImageAdvisor.java, geode-core/src/main/java/org/apache/geode/internal/process/ProcessLauncherContext.java, geode-core/src/main/java/org/apache/geode/internal/process/StartupStatus.java, geode-core/src/main/java/org/apache/geode/internal/process/StartupStatusListener.java, geode-core/src/main/java/org/apache/geode/internal/process/StartupStatusListenerRegistry.java, geode-core/src/main/java/org/apache/geode/internal/util/TransformUtils.java, geode-core/src/test/java/org/apache/geode/internal/cache/persistence/MembershipChangeListenerFactoryTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/persistence/PersistenceAdvisorImplTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/persistence/PersistenceInitialImageAdvisorTest.java, geode-core/src/test/java/org/apache/geode/internal/process/ProcessLauncherContextTest.java, geode-core/src/test/java/org/apache/geode/internal/process/StartupStatusTest.java
GEODE-4267: Fix PersistentRecoveryOrderOldConfigDUnitTest
This started out trying to fix flaky failures in PersistentRecoveryOrderOldConfigDUnitTest and PersistentRecoveryOrderDUnitTest (GEODE-4267). I found that the log statement about waiting for missing persistent members was no longer working, so I ended up filing GEODE-7577 and fixing that as well.
New tests:
* MissingDiskStoreAcceptanceTest -- acceptance test to verify that a server logs when it is waiting for missing persistent members
* MembershipChangeListenerFactoryTest -- unit test for the new MembershipChangeListenerFactory
* New test methods in PersistenceAdvisorImplTest for the formatting of the messages
Changes:
* Separate StartupStatusListenerRegistry from StartupStatus to allow non-static injection of StartupStatus into …
=> GEODE-7577: Log when waiting for missing persistent members

geode-core/src/main/java/org/apache/geode/internal/admin/remote/RemoteGfManagerAgent.java, geode-core/src/test/java/org/apache/geode/internal/admin/remote/RemoteGfManagerAgentTest.java
If the thread invoking disconnect gets enough cpu cycles before the
thread invoking removeMember, then it tries to invoke listApplications
with null for system.
The fix sets the system so the field is non-null which also simulates a 
real run more closely as well.
=> GEODE-7586: Fix NPE in RemoteGfManagerAgentTest

ci/pipelines/meta/deploy_meta.sh, ci/pipelines/meta/jinja.template.yml
CONCOURSE_HOST is referenced in deploy_metrics.sh but was not defined when deploying the meta pipeline.
=> add missing variable

ci/images/google-windows-geode-builder/build_image.sh, ci/images/google-windows-geode-builder/windows-packer.json
Trying to have Packer be more careful (lots of restarts) when creating
the Windows heavy-lifter image.
* Move from Packer v1.3.5 to latest, v1.4.5
* Drop unused openjdk:8 docker image from Windows compute image. …
=> GEODE-7590 - More Packer restarts to fix Windows image.

ci/pipelines/pull-request/jinja.template.yml
For polling GitHub for PRs, don't waste ASF rate-limitted API calls.
* Use apachegeode-ci account for all queries.
* Use asf-ci account for all status-sets. …
=> GEODE-7596 - Use ASF repo:status token sparingly.

ci/images/google-geode-builder/packer.json, ci/pipelines/examples/jinja.template.yml, ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/meta/deploy_meta.sh, ci/pipelines/pull-request/jinja.template.yml, ci/pipelines/shared/jinja.variables.yml, ci/scripts/create_instance.sh, ci/scripts/rsync_code_down.sh
* Parameterize gcp image-family-name.
* Change geode-build template to set image-family-name.
* Remove reduntant 'do' in pipeline definition.
* Add image-family-name for pr and examples pipelines.
* Remove intermediatary files when deploying meta pipeline.
* Test jobs track when new compute image is used.
* Use gci-resource correctly per platform image family
- [n/a] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF …
=> GEODE-7599 - Use Google Compute Image resource in Concourse.

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessenger.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/MembershipDependenciesJUnitTest.java
Look for the jgroups configuration file using regular class loaders
instead of geode-core's ClassPathLoader.
- [tests already exist] Have you written or updated unit tests to verify your changes?
=> GEODE-7544 Break dependency on ClassPathLoader

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocatorIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocatorRecoveryIntegrationTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/adapter/GMSLocatorAdapter.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocator.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/MembershipDependenciesJUnitTest.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/gms/GMSMemberDataJUnitTest.java
Inject a serializer and deserializer into GMSLocator for use in reading
and writing its persistent membership view.
Note to reviewers: there are already unit tests for creating and recovering a locator persistent view.
=> GEODE-7606 Break dependency on InternalDataSerializer

geode-core/src/main/java/org/apache/geode/management/internal/SystemManagementService.java, geode-core/src/test/java/org/apache/geode/management/internal/SystemManagementServiceTest.java
LGTM complained about a possible NPE in startManager(). There was no
possibility of an NPE, but precondition-checking code was overly
complex, and difficult for LGTM and humans to analyze.
It turns out that much of the complexity was due to the code checking
for impossible conditions.
This PR greatly simplifies the precondition checks, and adds a suite of
tests for the startManager() method.
Adding the tests required injecting several dependencies.
Please ensure that once the PR is submitted, check Concourse for build …
=> GEODE-7592: Simplify startManager() precondition checks

geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionImpl.java
added a few more translation points.  These changes are for
non-opensource legacy tests that are looking for
ForcedDisconnectException as a cause for a cache disconnecting.  There
is nothing in Geode that expects this so I have not added tests that
require it.
=> GEODE-7556e - catch and translate exceptions into geode-core exceptions

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSUtil.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/MembershipDependenciesJUnitTest.java
One of the changes for this ticket is causing unit test failures on
some machines - especially Macs - in the form of
java.lang.RuntimeException: Failed to start locator
Caused by:
org.apache.geode.GemFireConfigException: This process is attempting to join with a loopback address (gzhou-mbpro/127.0.0.1) using a locator that does not have a local address (/10.255.200.197:60167). On Unix this usually means that /etc/hosts is misconfigured.
email to …
=> GEODE-7541: Revert back to SocketCreator in GMSUtil

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessenger.java, geode-core/src/main/java/org/apache/geode/internal/admin/remote/AlertListenerMessage.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/MembershipDependenciesJUnitTest.java
The only place where JGroupsMessenger called AlertingAction was when
sending a message. The only message that could be sent while that thread
local is true is AlertListenerMessage.
Setting isHighPriority to true on AlertListenerMessage instead.
JGroupsMessenger is the only place that flag is checked, so this should
have the same effect as testing the thread local.
=> GEODE-7545: Remove dependency on AltertingAction from membership

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/MembershipOnlyTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/MembershipOnlyTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeaveJUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/Locator.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/adapter/ServiceConfig.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/AuthenticatorNoOp.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMembership.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/LifecycleListenerNoOp.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/MembershipBuilderImpl.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/MembershipListenerNoOp.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/MembershipStatisticsNoOp.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/api/MembershipConfig.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessenger.java
Moving the defaults of membership related settings to the
MembershipConfig class, and referencing them from DistributionConfig.
This makes it easier to create a Membership with the correct default
values.
Adding default implementations of many of the Membership colaborators,
such as AuthenticatorNoOp and MembershipStatisticsNoOp.
Adding a test of creating a Membership using only membership classes.
This test still has several TODOs related to core classes which were
necessary or helpful to make this work.
submit an update to your PR as soon …
=> GEODE-7627: Moving defaults to MembershipConfig

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/GeodeClientClusterManagementSSLTest.java
This test had an awaitility clause, but it fails because within the
clause an IllegalStateException was thrown, which is not handled by
awaitility.
=> GEOE-7617: Retry awaits in GeodeClientClusterManagementSSLTest

ci/pipelines/shared/jinja.variables.yml, ci/scripts/run_benchmarks.sh
Running SSL benchmarks with JDK12 improves their stability. This change
only supports using JDK11 as an alternative JDK since each different JDK
option that Benchmarks supports would have to be installed individually
on the cluster.
* Add flag to SSL Benchmark jinja variables for using JDK11
* Use jdk11 baked into the image
=> GEODE-7581: Run SSL Benchmarks with JDK11

geode-core/src/integrationTest/java/org/apache/geode/alerting/internal/api/AlertingServiceWithClusterIntegrationTest.java, geode-core/src/main/java/org/apache/geode/alerting/internal/ClusterAlertMessaging.java, geode-core/src/test/java/org/apache/geode/alerting/internal/ClusterAlertMessagingTest.java, geode-log4j/src/main/java/org/apache/geode/alerting/log4j/internal/impl/AlertAppender.java
After the change to send alerts in a executor, there was a possibiltiy for
sending alerts to generate new alerts, resulting an in infinite loop.
Setting the AlertingAction threadlocal in the executor thread that is sending
alerts, to prevent recursion.
Adding a test that we do not generate recursive alert messages.
=> GEODE-7623: Preventing recursion in alert generation

ci/images/alpine-tools/Dockerfile, ci/images/google-windows-geode-builder/windows-packer.json, ci/pipelines/geode-build/jinja.template.yml, ci/scripts/create_instance.sh, ci/scripts/delete_instance.sh
* Fix instance cleanup per zone.
* delete_instanch.sh deletes in all zones just in case.
* Ask for zones, don't assume.
* Use Packer release 1.4.5, not latest prerelease.
* Need reboot before running GCESysPrep in case of windows update. …
=> GEODE-7590 - Use GCESysprep as last-step in Windows Packer build.

dev-tools/release/promote_rc.sh
Sometimes, pipeline or infrastructure fixed need to be committed to a release branch after the final RC has already been tagged.  This PR adds a `git pull` before pushing the Dockerfile changes to ensure success in this scenario.
=> GEODE-7636: insulate release scripts from stray changes

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java
Removing some code which set the coord and coordIsNoob local variables but
never used them.
=> GEODE-7647: Removing unused code from GMSJoinLeave

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocatorRecoveryIntegrationTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocator.java
Geode v1.11 inadvertently changed the form of its saved membership view
by using a FileOutputStream to write it to disk instead of using
an ObjectOutputStream.  The latter writes additional information during
serialization.
Note: there is already a test for this change that will start running
when v1.12 is created and v1.11 is added as a geode-old-version in
settings.gradle.
=> GEODE-7649 upgrade tests fail when v1.11 is added to geode-old-versions

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSUtil.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/gms/GMSUtilTest.java
[GEODE-7648](https://issues.apache.org/jira/browse/GEODE-7648) second try at a fix
The original fix (already merged to `develop`) failed to condition resolving the locator address, on the bind addy being a loopback addy. That is a particular problem when starting a locator in a Docker container where other locators are in neighboring containers that might not be running yet, and so, might not have their names in the DNS.
=> GEODE-7648: elide hostname resolution if bind addy not loopback

geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledSelect.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/Functions.java, geode-dunit/src/main/java/org/apache/geode/management/internal/cli/commands/NestedQueryClassCastExceptionFailureDUnitTest.java, geode-dunit/src/main/java/org/apache/geode/management/internal/cli/commands/Product.java
* After a recursion step within Compiled Select's evaluate statement, the distinct flag was lost for the outer query.
* The solution was to reset the distinct state back using a temp variable to store the initial distinct flag value.
* Also, in this diff a else part section was missing converting PDX strings to normal strings for comparison of distinct.
* When we place this else section converting the PDX string to string for distinct comparison, we don't need to perform this check in the 'element' query function.
Removing the JPMC related configurations …
=> GEODE-7655:Restore context with distinct state after a recursion step.

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessengerJUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/adapter/TcpSocketCreatorAdapter.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/Services.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessenger.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/gms/messenger/StatRecorderJUnitTest.java, geode-tcp-server/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpSocketCreator.java
We didn't need these methods on TcpSocketCreatorAdapter.
* resolveDns is based on whether network partition detection is enabled, which
we can access directly in membership.
* getHostName uses a static hostname cache that we don't need to use
for membership when creating the local address.
* getLocalHost has moved to a utility in geode-common.
=> GEODE-7658: Removing hostname resolution from TcpSocketCreatorAdapter

geode-core/src/distributedTest/java/org/apache/geode/cache/ConnectionPoolAutoDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/cache/ConnectionPoolDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/cache30/ClientMembershipDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ClientDeserializationCopyOnReadRegressionTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/HAOverflowMemObjectSizerDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionHAFailureAndRecoveryDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ha/FailoverDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ha/HARQueueNewImplDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DestroyEntryPropagationDUnitTest.java, geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/CqDataDUnitTest.java, geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/CqDataUsingPoolDUnitTest.java, geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/CqQueryDUnitTest.java, geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/CqQueryUsingPoolDUnitTest.java, geode-cq/src/distributedTest/java/org/apache/geode/cache/query/dunit/QueryIndexUpdateRIDUnitTest.java, geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/ha/CQListGIIDUnitTest.java, geode-dunit/src/main/java/org/apache/geode/cache30/CertifiableTestCacheListener.java, geode-dunit/src/main/java/org/apache/geode/cache30/ClientServerTestCase.java, geode-dunit/src/main/java/org/apache/geode/cache30/TestCacheCallback.java
- Changes to ClientServerTestCase to allow for the use of RegionFactory
- Removing Wait.pauses from run-time for testing.
- clean out a bunch of runnables
=> GEODE-7600-2: ConnectionPoolDUnitTest Cleanup.

geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt, geode-core/src/main/java/org/apache/geode/internal/cache/EventID.java, geode-core/src/test/java/org/apache/geode/internal/cache/EventIDTest.java
We create an serialize an EventID with a null membershipID. When serializing to
a Geode 1.0.0 member, this resulted in an NPE in some version transalation
logic. Fixing the version translation logic to check for null.
=> GEODE-7661: Check for null membershipID when serializing EventID

geode-core/src/main/java/org/apache/geode/internal/cache/AbstractBucketRegionQueue.java, geode-core/src/main/java/org/apache/geode/internal/cache/AbstractUpdateOperation.java, geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegionQueue.java, geode-core/src/main/java/org/apache/geode/internal/cache/DistPeerTXStateStub.java, geode-core/src/main/java/org/apache/geode/internal/cache/DistTXStateOnCoordinator.java, geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalDataView.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegionDataView.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/PausedTXStateProxyImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXState.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXStateProxyImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXStateStub.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderEventProcessor.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderQueue.java, geode-core/src/test/java/org/apache/geode/internal/cache/UpdateOperationJUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/UpdateVersionDUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderQueueDUnitTest.java
Allow LocalRegion.virtualPut() to throw ConcurrentCacheModificationException
Added throwsConcurrentModifiaction boolean argument to LocalRegion.virtualPut() to determine if the exception should be thrown
Added invokeCallbacks boolean argument to LocalRegion.virtualPut() to determine if bridge clients and gateway senders should be notified of the event
Fixed issue with inheriting new virtualPut implementations
Added DUnit test to confirm fix …
=> GEODE-7643: Gateway unprocessedTokensMap appears to grow without bounds with replicated regions and peer accessors

ci/pipelines/meta/deploy_meta.sh
for any context other than the public apache-develop-main or release pipelines, metrics and examples aren't going to work, so don't insist on enabling them just to create a sea of red
=> GEODE-7662: don't automatically enable metrics and examples if not public

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/MembershipJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/MembershipOnlyTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionImpl.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/api/MembershipBuilder.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/api/MembershipLocatorBuilder.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMembership.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/MembershipBuilderImpl.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/MembershipLocatorBuilderImpl.java
[GEODE-7653](https://issues.apache.org/jira/browse/GEODE-7653)
> Right now it is not clear from the API which attributes of MembershipBuilder and MembershipLocatorBuilder are required vs. which ones are optional.
> Ideally, it should be enforced at compile time that all required fields are specified, maybe by passing all required fields to the constructor
=> GEODE-7653: move required settings to MembershipBuilder constructor

ci/scripts/run_benchmarks.sh
To run Benchmarks against a personal fork, it's not immediately obvious where to override the repo default of "apache/geode"
This PR adds variables for this at the top of run_benchmarks.sh so they can be easily set in your environment without having to figure out how to update the very long run_against_baseline commandline.
=> GEODE-7690: make it less difficult to run benchmarks against a PR

ci/pipelines/meta/deploy_meta.sh
some people run deploy_meta.sh from the meta directory, so hardcoding the paths relative to the top of the repo doesn't work for them.
=> GEODE-7688: clean up temp files after deploy meta

geode-docs/managing/statistics/how_statistics_work.html.md.erb, geode-docs/managing/statistics/setting_up_statistics.html.md.erb
The User Guide advises against enabling time-based statistics in production environments. As of Geode v1.9, this limitation is no longer significant, so the warning against it should be removed from the user guide.
=> GEODE-7687: User Guide - Remove time-based statistics caveat

geode-core/src/distributedTest/java/org/apache/geode/management/JMXMBeanReconnectDUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java, geode-dunit/src/main/java/org/apache/geode/test/junit/rules/GfshCommandRule.java
```
GEODE-5407: Fix JMXMBeanReconnectDUnitTest
```
```
* Rewrite test with standard Geode and JMX APIs
* Use CountDownLatch instead of Blackboard
* Use SharedErrorCollector for remote listener errors
* Always consistently use Awaitility before checking GemFire MXBeans
Co-authored-by: Ivan Godwin <igodwin@pivotal.io>
```
=> GEODE-5407: Fix JMXMBeanReconnectDUnitTest

geode-docs/managing/monitor_tune/performance_on_vsphere.html.md.erb
Removed some blanket prohibitions.
Acknowledged that vMotion migration introduces a performance hit, but it's temporary.
Recommended that users conduct tests to evaluate the impacts on their specific configurations.
=> GEODE-7686: Update the vMotion recommendations in the User Guide

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentRecoveryOrderDUnitTest.java
Ignore RegionDestroyedException while waiting for region to be
destroyed.
=> GEODE-7605: Fix PersistentRecoveryOrderDUnitTest

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/api/CoreOnlyUsesMembershipAPIArchUnitTest.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/MembershipDependenciesJUnitTest.java
This commit has a little ArchUnit cleanup to GEODE-6833 which was just merged.
=> GEODE-6833: remove redundant ArchRule and layer spec

geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandPersistsConfigurationDUnitTest.java
Ensure region MBeans exist on locator prior to creating colocated region
=> GEODE-7115: Fix CreateRegionCommandPersistsConfigurationDUnitTest

geode-lucene/src/distributedTest/java/org/apache/geode/cache/lucene/internal/IndexRepositoryFactoryDistributedTest.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/IndexRepositoryFactory.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/IndexRepositoryFactoryTest.java
The IndexWriter initialization might fail when other threads are
updating the fileAndChunkRegion, which can be triggered by other normal
operations (query, event listener, close, reindex, etc.). This doesn't
happen often and, instead of propagating the exception to the caller
and failing, Geode now catches it and returns null to let the callers
retry.
- Added unit and distrbuted tests.
- Return null instead of re-throwing the IOException while building
the Lucene IndexWriter.
submit an update …
=> GEODE-7703: Catch IndexWriter Exceptions

geode-assembly/src/main/dist/LICENSE
Updates geode-assembly/src/main/dist/LICENSE to remove obsolete references to:
paranamer
scala-reflect
scala-library
as requested on the dev list here: https://lists.apache.org/thread.html/c9c73e726742c78a1ff9739379a51f7eeab33a05d99531a38b537670%40%3Cdev.geode.apache.org%3E
=> GEODE-7726: remove obsolete references from LICENSE file

geode-core/src/test/java/org/apache/geode/internal/admin/remote/RemoteGfManagerAgentTest.java
RemoteGfManagerAgentTest intermittently fails strict stubbing for
system.getCancelCriterion. Strict stubbing isn't necessary and it looks
like RemoteGfManagerAgent would require more refactoring and other
changes to make this more deterministic.
=> GEODE-7730: Remove strict stubbing from RemoteGfManagerAgentTest

geode-core/src/main/java/org/apache/geode/cache/client/internal/PutOp.java, geode-core/src/main/java/org/apache/geode/internal/cache/EntryEventImpl.java, geode-core/src/test/java/org/apache/geode/cache/client/internal/PutOpJUnitTest.java, geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/ClientToServerDeltaDUnitTest.java
* When performing delta update on client, there is a possibility that
some delta update is not yet applied on client cache.
* If apply delta update, some queued delta update would be lost -- as
entry versioning will discard these delta updates when received later.
* Now it will check if there is a versioning mismatch, if it happened,
the full value from server will be applied instead of just the delta.
=> GEODE-7663: Fix delta update inconsistency in client cache.

ci/images/google-geode-builder/build_image.sh, ci/images/google-geode-builder/packer.json, ci/images/google-windows-geode-builder/build_image.sh, ci/images/google-windows-geode-builder/windows-packer.json
The Geode instance reaper job looks for 'label:time-to-live' to exist on
instances, as the criterion for stopping and deleting old instances.
Make sure we put that onto the Packer instances we use to build Google
Compute Images
submit an update to your PR as soon as possible. If you …
=> GEODE-7741 - Instance labels and TTL on packer GCE instances

geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
Adjust the text of javadocs for "locators" and add IPv4 examples.
=> GEODE-7710: Add examples to javadocs for "locators"

ci/pipelines/pull-request/jinja.template.yml
Try to work around spurious DNS/HTTP issues
Co-authored-by: Steve Sienkowski <ssienkowski@pivotal.io>
=> Add 'attempts: 2' to all Git 'get' steps in CI.

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/MembershipOnlyTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/InternalDistributedMember.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/api/MemberIdentifierImpl.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/api/MembershipLocatorBuilder.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/MembershipLocatorBuilderImpl.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/Services.java, geode-serialization/src/main/java/org/apache/geode/internal/serialization/DataSerializableFixedID.java, geode-serialization/src/main/java/org/apache/geode/internal/serialization/StaticSerialization.java
Removing some dependencies on geode-core from the MembershipOnlyTest and adding a test of two members.
As part of this PR, I ran into several problems with MembershipOnlyTest that needed product fixes. Please look at the individual commits in this PR for details.
* GEODE-7736: Adding a test of two members connecting to MembershipOnlyTest
* GEODE-7735: Giving a separate DSFID to MemberIdentifierImpl
* GEODE-7734: Registering DSFIDS inside MembershipLocatorBuilder.create
* GEODE-7733: Don't use geode-core serializer and IDM in MembershipOnlyTest
=> GEODE-7736: Remove depencies on core from MembershipOnlyTest and add two member test

geode-core/src/distributedTest/java/org/apache/geode/cache30/ReconnectWithClusterConfigurationDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/distributed/LocatorDUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/MembershipJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/MembershipOnlyTest.java, geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocatorRecoveryIntegrationTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionImpl.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java, geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocatorIntegrationTest.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/api/LifecycleListener.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/api/MembershipBuilder.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/api/MembershipLocator.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMembership.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/LifecycleListenerNoOp.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/MembershipBuilderImpl.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/Services.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/locator/GMSLocator.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/locator/MembershipLocatorImpl.java
[GEODE-7652](https://issues.apache.org/jira/browse/GEODE-7652)
The main goal here is to make it straightforward to start up a locator vis-à-vis membership. So code that looked like this (in `MembershipOnlyJUnitTest`):
```java
final Membership<MemberIdentifierImpl> membership =
MembershipBuilder.<MemberIdentifierImpl>newMembershipBuilder(
socketCreator, locatorClient, dsfidSerializer, memberIdFactory)
.setConfig(config)
.setLifecycleListener(lifeCycleListener)
.create();
// TODO - the membership *must* be installed in the locator at this special
// point during membership startup for the start to succeed
doAnswer(invocation -> {
membershipLocator.setMembership(membership);
return null;
}).when(lifeCycleListener).started();
membership.start();
```
can look like this:
```java
final …
```
=> GEODE-7652: MembershipBuilder lets you set the local locator

geode-redis/src/integrationTest/java/org/apache/geode/redis/SetCommandNegativeCaseTest.java, geode-redis/src/main/java/org/apache/geode/redis/GeodeRedisServer.java, geode-redis/src/main/java/org/apache/geode/redis/internal/ExecutionHandlerContext.java, geode-redis/src/main/java/org/apache/geode/redis/internal/KeyRegistrar.java, geode-redis/src/main/java/org/apache/geode/redis/internal/RegionProvider.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/AbstractExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/DBSizeExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/DelExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/ExistsExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/FlushAllExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/KeysExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/ScanExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/TTLExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/TypeExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hll/HllExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/BitOpExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/DecrExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/MSetNXExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/SetExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/StringExecutor.java
KeyRegistrar encapsulates info about keys that are inserted via the
Redis API. It uses a Geode Region to store a map from key -> RedisDataType
=> GEODE-7747: Refactor - extract class KeyRegistrar

dev-tools/release/deploy_rc_pipeline.sh, dev-tools/release/prepare_rc.sh
as requested here: https://lists.apache.org/thread.html/c7bd84b6e6f5464ed674ed447fe8922097237932967b4ed1966e79d3%40%3Cdev.geode.apache.org%3E
Since Geode 1.8.0, we stopped distributing both .tgz AND .zip for Geode, instead favoring .tgz only. However, geode-examples is still shipping both.
For the same reasons cited in GEODE-5694, we only need to ship examples as a .tar.gz, no need for multiple archive formats.
DO NOT MERGE unless consensus has been reached and/or a vote has passed on the dev list. Until then, this PR is provided only as an exhibit of the changes being proposed.
=> GEODE-7719: no need to release examples as both .tgz AND .zip

geode-tcp-server/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpSocketCreatorImpl.java
reinstate connect() timeout and do not set socket read-timeout
=> GEODE-7597: Factor out code needed in Membership from SocketCreator

geode-assembly/src/integrationTest/java/org/apache/geode/tools/pulse/PulseConnectivityTest.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/data/Cluster.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/data/JMXDataUpdater.java
Cluster now makes itself a daemon if embedded.
If the JMXDataUpdater loses its connection it now tells the Cluster it is no longer connected.
The Cluster run loop now checks that it is still connected.
=> GEODE-7755: change Pulse to not keep locator alive

geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/GroupJunctionIntegrationTest.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledComparison.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/GroupJunction.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/CompiledComparisonTest.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/GroupJunctionTest.java
- Added unit and integration tests.
- Back off from the single index optimisation during join queries if
we can't find the (single) best filter, allowing the regular
execution to continue and use multiple indexes.
- If there are multiple indexes, add the filter evaluable operand at
the beginning of the internal list to evaluate it first in the chain.
=> GEODE-7728: Fix Assertion Failures in OQL

geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedAckRegionCCEDUnitTest.java
GEODE-7600: Disabling a test until the underlying code is implemented.
=> GEODE-7600: Disabling a test until the underlying code is implemented.

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/DeltaPropagationDUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImplJUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/QueueManagerJUnitTest.java, geode-core/src/main/java/org/apache/geode/cache/client/ClientRegionFactory.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/ClientRegionFactoryImpl.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/InternalPool.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/PoolImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalCacheForClientAccess.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalPoolFactory.java, geode-core/src/main/java/org/apache/geode/internal/cache/PoolFactoryImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxy.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxyFactory.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientInterestList.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/MessageDispatcher.java, geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxyFactoryTest.java
Improve testability of CacheClientProxy
* Extract inner classes
* Introduce CacheClientProxyFactory with support for property injection
* Pull getPrimaryPort up to InternalPool interface
* Define InternalPoolFactory and pull up init and getPoolAttributes
Replace flaky sleep-based test-hook in product code with custom
MessageDispatcher injected by property in CacheClientProxyFactory
which uses CountDownLatch.
=> GEODE-5595: Fix DeltaPropagationDUnitTest flakiness

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/fixed/FixedPartitioningWithColocationAndPersistenceDUnitTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionDataStore.java
Main fix for flakiness involved using ResourceObservers. Search for these lines:
```
await().until(() -> observer.isRecoveryFinished());
```
The secondary fix involved using custom enum, serializable classes, etc with proper Atomic fields. The shared classes that this test was using from geode-dunit are not thread safe but were used from multiple threads.
=> GEODE-7356: Fix FixedPartitioningWithColocationAndPersistenceDUnitTest

geode-core/build.gradle, geode-core/src/test/resources/expected-pom.xml
There is a build / runtime cycle between geode-core and geode-gfsh, defined as a runtime-only dependency in Gradle. Can we break this optional, runtime-only declaration?
=> GEODE-7776 - Proposed changes to remove build cycle

ci/images/alpine-tools/Dockerfile
winrm-cli changes.
Change the dockerfile to do go get instead of git clone which does
cloning, pulling dependencies and building as part of its process.
This eliminates the manual winrm-cli build process that was
being done before.
Signed-off-by: Bala Kaza Venkata <bkazavenkata@pivotal.io>
=> GEODE-7788: Alpine tools docker image creation fails due to internal

geode-core/src/distributedTest/java/org/apache/geode/distributed/LocatorDUnitTest.java
The new test hung during a CI run due to a flaw in Geode.  I'm disabling
it until the flaw is corrected.
=> GEODE-7796: CI failure in LocatorDUnitTest

geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/InternalDistributedMember.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/InternalDistributedMemberTest.java
Keep the last known 'DurableClienAttributes' cached within the
'InternalDistributedMember' class to avoid the overhead of creating a
new instance every time.
=> GEODE-7789: Cache DurableClienAttributes

geode-core/src/main/java/org/apache/geode/cache/query/internal/AttributeDescriptor.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/MethodDispatch.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/QueryExecutionContext.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/AttributeDescriptorTest.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/MethodDispatchTest.java, geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/internal/CqSecurityExecutionContextTamperingDistributedTest.java, geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/CqQueryImpl.java
CQs are executed on individual entries whenever an event is triggered
for them and the execution context is always cleared before the actual
evaluation, thus using an internal cache to keep already authorized
methods is useless (will always be a cache miss and the computation
required just adds overhead).
- Fixed the CQ creation to always set the 'cqQueryContext' flag.
- Modified the query engine to avoid using the internal cache for
already authorized methods when the context belongs to a CQ.
- Avoid the creation and concatenation of unnecessary Strings, using
the Method class directly instead.
Please ensure that once the …
=> GEODE-7756: Do not use authorization cache for CQs

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/RedundancyLevelPart1DUnitTest.java
- Asynchronous operations require awaiting.
Co-authored-by: Kirk Lund <klund@pivotal.io>
=> GEODE-7210: Fix RedundancyLevelPart1DUnitTest by Adding Awaits to Asserts

geode-redis/src/integrationTest/java/org/apache/geode/redis/PubSubTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/mocks/MockSubscriber.java, geode-redis/src/main/java/org/apache/geode/redis/GeodeRedisServer.java, geode-redis/src/main/java/org/apache/geode/redis/internal/AbstractSubscription.java, geode-redis/src/main/java/org/apache/geode/redis/internal/ChannelSubscription.java, geode-redis/src/main/java/org/apache/geode/redis/internal/PatternSubscription.java, geode-redis/src/main/java/org/apache/geode/redis/internal/PubSub.java, geode-redis/src/main/java/org/apache/geode/redis/internal/PubSubImpl.java, geode-redis/src/main/java/org/apache/geode/redis/internal/PublishResult.java, geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java, geode-redis/src/main/java/org/apache/geode/redis/internal/Subscription.java, geode-redis/src/main/java/org/apache/geode/redis/internal/Subscriptions.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PsubscribeExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PunsubscribeExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/org/apache/hadoop/fs/GlobPattern.java, geode-redis/src/main/resources/org/apache/geode/redis/internal/sanctioned-geode-redis-serializables.txt, geode-redis/src/test/java/org/apache/geode/redis/internal/PubSubImplJUnitTest.java, geode-redis/src/test/java/org/apache/geode/redis/internal/SubscriptionsTest.java
Similar to `SUBSCRIBE` and `UNSUBSCRIBE`, `PSUBSCRIBE` allows a client
to subscribe to a pattern. For example: `PSUBSCRIBE sal*s`
The subscription pattern is in the form of a glob supporting `*`, `?`
and ranges. https://redis.io/commands/psubscribe
Pattern subscriptions must be unsubscribed verbatim. i.e., the above
subscription would not be unsubscribed using the pattern `s*`, but must
be unsubscribed using the complete subscribed pattern, namely `sal*s`.
When clients subscribe to overlapping patterns (or channels) they will
receive a message for every matched subscription. Matches for a single
client are not conflated.
Co-authored-by: Sarah Abbey <sabbey@pivotal.io>
Co-authored-by: John Hutchison <jhutchison@pivotal.io>
Co-authored-by: …
=> GEODE-7800: Add Redis PSUBSCRIBE and PUNSUBSCRIBE commands

geode-core/src/distributedTest/java/org/apache/geode/distributed/LocatorDUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionImpl.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMembership.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/locator/MembershipLocatorImpl.java, geode-tcp-server/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpServer.java
This reinstates the test (removes Ignore annotation) and fixes the underlying problems...
To fix the "hang" I reduced the locator-wait-time (seconds, not millis) in the test
I also made several other changes to fix the underlying failure:
1) add a synchronization to the services restart thread so only one
thread is active at a time
2) shut down membership cleanup executor and avoid creating multiple
TcpServer executors on auto-reconnect
3) remove setting the locator as a dependent of the
InternalDistributedSystem.  This was causing locator.stop() to be
invoked multiple times (as Dale noticed in his analysis)
4) when stopping a locator for auto-reconnect wait for it to stop in
order to avoid creating multiple restart threads when there are
cascading failures.
Thank you for submitting a …
=> Feature/geode 7796: CI hang in LocatorDUnitTest.testCrashLocatorMultipleTimes

extensions/geode-modules/src/main/java/org/apache/geode/modules/util/BootstrappingFunction.java, geode-core/src/main/java/org/apache/geode/internal/admin/remote/RemoteApplicationVM.java, geode-core/src/main/java/org/apache/geode/internal/admin/statalerts/DummyStatisticInfoImpl.java, geode-core/src/main/java/org/apache/geode/internal/admin/statalerts/StatisticInfoImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/FilterProfile.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionHelper.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXCommitMessage.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXEntryState.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXState.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/HAEventWrapper.java, geode-core/src/main/java/org/apache/geode/internal/cache/versions/RegionVersionHolder.java, geode-core/src/main/java/org/apache/geode/pdx/internal/PdxField.java, geode-core/src/main/java/org/apache/geode/pdx/internal/PdxType.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java, geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeMemberCommand.java, geode-junit/src/main/java/org/apache/geode/DeltaTestImpl.java, geode-junit/src/main/java/org/apache/geode/cache/query/data/PortfolioData.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMemberData.java
A null check is not needed before using instanceof.
The expression `x instanceof SomeClass` is **false** if _x_ is _null_.
=> GEODE-7768: remove redundant null checks

geode-core/build.gradle
The version info already includes the version of the compiler in `Build-Java-Version`. As there are now several java compiler vendors and a multitude of ways Geode may get compiled (various pipeline jobs, by a release manager, by users, etc) it makes sense to record the provider of that javac version as well. This is also helpful to audit that only open-source tools are being used to produce Geode artifacts.
=> GEODE-7813: add Build-Java-Vendor to gfsh version --full

geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt, geode-core/src/main/java/org/apache/geode/alerting/internal/ClusterAlertMessaging.java, geode-core/src/main/java/org/apache/geode/alerting/internal/spi/AlertingIOException.java, geode-core/src/main/java/org/apache/geode/internal/tcp/TCPConduit.java, geode-core/src/test/java/org/apache/geode/alerting/internal/ClusterAlertMessagingTest.java, geode-core/src/test/java/org/apache/geode/internal/tcp/TCPConduitTest.java
Change from FATAL log level to WARNING log level for log statement with stack trace when unable to create a connection to an alert listener.
Note to reviewers: let me know if you think this should be ERROR log level instead of warning. I picked WARNING because I think that FATAL is too high. This doesn't prevent any operations or represent data corruption or the inability to continue to run as a data server. It just means that we couldn't create a new connection for a remote alert listener (probably because the member left or is about to depart the view).
=> GEODE-7810: Change alert listener connection warning from fatal

geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/PutAllClientServerDistributedTest.java
The two lists of VersionTag in the original test may contain the same elements, but in different order. This fixes the test to compare the elements of the lists regardless of order.
=> GEODE-7784: Region entry has wrong RVV version after removeAll retried

geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionMessage.java
Avoid unnecessary object allocations by making the attributes static.
=> GEODE-7814: Avoid Messaging Unnecessary Allocations

geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/ProduceDateMessages.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ClientServerTransactionFailoverDistributedTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/Distribution.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionImpl.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionMessage.java, geode-core/src/main/java/org/apache/geode/internal/admin/remote/AdminRequest.java, geode-core/src/main/java/org/apache/geode/internal/admin/remote/AdminResponse.java, geode-core/src/main/java/org/apache/geode/internal/admin/remote/CompactRequest.java, geode-core/src/main/java/org/apache/geode/internal/admin/remote/ShutdownAllRequest.java, geode-core/src/main/java/org/apache/geode/internal/cache/StateFlushOperation.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PartitionMessage.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PutMessage.java, geode-core/src/main/java/org/apache/geode/internal/cache/tx/RemoteOperationMessage.java, geode-core/src/main/java/org/apache/geode/management/internal/messages/CompactRequest.java, geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionTest.java
Avoid unnecessary invocations to the 'toArray' method and directly
use the java collection received instead.
=> GEODE-7820: Avoid Unnecessary toArray Invocations

geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerImplTest.java, geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerJUnitTest.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/OpExecutorImpl.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/PoolImpl.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/ConnectionManager.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerImpl.java, geode-core/src/test/java/org/apache/geode/cache/client/internal/OpExecutorImplJUnitTest.java
This reverts commit 9da2cd49e2e04564b446eaad579b51e986bc2179.
Hangs were observed in internal tests and this commit was determined to be responsible. As of yet, no local reproduction of the issue is available, but work is ongoing to provide a test that can be used to debug the issue.
In addition to the hangs caused by this commit, it should be noted that no additional tests were checked in to validate the change, as required in the "For all changes" checklist that accompanies every PR. This alone could be seen as a reason to revert, as changes without associated tests to go with them should not really be merged in the first place.
to ensure the following steps have …
=> Revert "GEODE-6536: Added retry in borrowConnection/single hop (#4719)"

geode-junit/src/integrationTest/java/org/apache/geode/test/junit/rules/serializable/SerializableTemporaryFolderIntegrationTest.java, geode-junit/src/main/java/org/apache/geode/test/junit/rules/serializable/SerializableTemporaryFolder.java, geode-junit/src/main/java/org/apache/geode/test/junit/runners/TestRunner.java, geode-junit/src/test/java/org/apache/geode/test/junit/rules/serializable/SerializableTemporaryFolderTest.java
When we are debugging a distributed test that uses 
SerializableTemporaryFolder for Server and Locator files, we need a 
way to save off the files.
```
GEODE-7819: Add debugging support to SerializableTemporaryFolder
Specifying delete(false) will prevent deletion of the temporary folder
tree during tear down.
Specifying copyTo(directory) with optional when(When) will result in
copying the contents of the temporary folder tree to the destination
directory during tear down.
```
I'm using this change on several branches to debug various dunit
tests. I think this is ready to merge to develop, and having it on 
develop will make it unnecessary to cherry-pick for debugging.
=> GEODE-7819: Add debugging support to SerializableTemporaryFolder

geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterOperationExecutors.java, geode-core/src/main/java/org/apache/geode/distributed/internal/direct/DirectChannel.java, geode-core/src/main/java/org/apache/geode/internal/cache/properties.html, geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
Removed the semaphores and related methods from DirectChannel and
Connection classes. They were used to constrain messaging when some
undocumented system properties were set.
=> GEODE-7832: Remove Connection Semaphores

geode-redis/README.md, geode-redis/src/performanceTest/aggregator.sh, geode-redis/src/performanceTest/benchmark.sh, geode-redis/src/performanceTest/shacompare.sh
We have created some scripts to measure the performance of Geode-Redis versus native Redis. They use the standard 'redis-benchmark' tool to run various Redis commands against either Geode or native Redis.
The benchmark tools consist of three scripts:
- aggregator.sh runs the actual tests
- benchmark.sh handles validating the Redis server (e.g. starting and stopping Geode Redis if needed) then runs aggregator.sh
- shacompare.sh takes two git SHAs as arguments and runs benchmark.sh on each of them, generating separate output files for each.
=> GEODE-7841 Add benchmarking scripts for Geode-Redis module

geode-core/src/main/java/org/apache/geode/internal/InternalDataSerializer.java
Remove unused field and avoid unnecessary calls to
Logger.isTraceEnabled().
=> GEODE-7853: Remove unused field

dev-tools/release/promote_rc.sh, docker/Dockerfile
=> GEODE-7849: change release urls from www.apache.org/dist/ to downloads.apache.org

ci/pipelines/pull-request/jinja.template.yml
The PR resource supports rebase instead of merging against the latest
base-branch. Do that instead of merging.
=> Geode prefers not to use merge-commits, so do not test against them.

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/DestroyRegionDuringGIIDistributedTest.java
This text is being fixed, but it is causing a fair number of failures in the mean time.
=> GEODE-4194: Re-ignoring a failing test that was previously ignored

geode-core/src/main/java/org/apache/geode/management/internal/FederatingManager.java, geode-core/src/main/java/org/apache/geode/management/internal/NotificationCacheListener.java, geode-core/src/test/java/org/apache/geode/management/internal/NotificationCacheListenerTest.java
JMX Manager may fail to broadcast one or more JMX notifications
during startup because of a race condition involving FederatingManager
and NotificationCacheListener.
Change NotificationCacheListener to be ready upon construction.
Since NotificationCacheListener is a test without unit test, I have created
NotificationCacheListenerTest which follows these unit testing standards:
* it uses Mockito for all dependencies
* follows Michael Feather's definition of a unit test
* uses terminology and patterns from http://xunitpatterns.com/
* uses TextDox inspired test method naming
=> GEODE-7710: Fix race condition in sending JMX notifications

geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedRule.java, geode-tcp-server/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpClient.java, geode-tcp-server/src/test/java/org/apache/geode/distributed/internal/tcpserver/TcpServerJUnitTest.java
The server-version map that tracks Locator versions is now an instance
variable instead of a static.
I looked into removing the map altogether but it's really needed for
rolling-upgrade purposes.  When one locator is rolled to a new version
of Geode but another locator is still running the old version it's
essential that the new locator know that it's communicating with an old
locator.
=> GEODE-7877: deal with the static Version map in TcpClient

boms/geode-all-bom/src/test/resources/expected-pom.xml, buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy, geode-assembly/src/integrationTest/resources/assembly_content.txt, geode-assembly/src/integrationTest/resources/dependency_classpath.txt, geode-redis/build.gradle, geode-redis/src/integrationTest/java/org/apache/geode/redis/RedisLockServiceIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/GeodeRedisServer.java, geode-redis/src/main/java/org/apache/geode/redis/internal/ByteArrayWrapper.java, geode-redis/src/main/java/org/apache/geode/redis/internal/KeyHashIdentifier.java, geode-redis/src/main/java/org/apache/geode/redis/internal/RedisLockService.java, geode-redis/src/test/java/org/apache/geode/redis/internal/KeyHashIdentifierTest.java, geode-redis/src/test/java/org/apache/geode/redis/internal/RedisLockServiceJUnitTest.java, geode-redis/src/test/resources/expected-pom.xml
- RedisLockService was not able to automatically free keys/locks after
unlocking since keys were also beging referenced in regions.
- Fix synchronization while iterating over keySet to avoid
ConcurrentModifiactionExceptions.
Co-Authored-By: Sarah Abbey <sabbey@pivotal.io>
Co-Authored-By: Ray Ingles <ringles@pivotal.io>
Co-Authored-By: John Hutchison <jhutchison@pivotal.io>
=> GEODE-7885: Improve RedisLockService - fix synchronization and memory leak

geode-assembly/src/integrationTest/java/org/apache/geode/rest/internal/web/RestRegionAPIDUnitTest.java, geode-assembly/src/integrationTest/java/org/apache/geode/rest/internal/web/RestSecurityIntegrationTest.java, geode-assembly/src/integrationTest/java/org/apache/geode/rest/internal/web/RestSecurityPostProcessorTest.java, geode-web-api/src/integrationTest/java/org/apache/geode/rest/internal/web/controllers/RestAccessControllerTest.java, geode-web-api/src/main/java/org/apache/geode/rest/internal/web/controllers/AbstractBaseController.java, geode-web-api/src/main/java/org/apache/geode/rest/internal/web/controllers/CommonCrudController.java, geode-web-api/src/main/java/org/apache/geode/rest/internal/web/controllers/FunctionAccessController.java, geode-web-api/src/main/java/org/apache/geode/rest/internal/web/controllers/PdxBasedCrudController.java, geode-web-api/src/main/java/org/apache/geode/rest/internal/web/controllers/QueryAccessController.java, geode-web-management/src/main/java/org/apache/geode/management/internal/rest/security/RestSecurityConfiguration.java
Older tests struggle with the deprecated symbols being replaced. Should be revisited later as a wider effort to cleanup deprecated usage. This ticket is focused on not making deprecated usage worse.
=> GEODE-7869: Revert content type changes.

geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java, geode-core/src/main/java/org/apache/geode/internal/SystemTimer.java, geode-core/src/main/java/org/apache/geode/internal/admin/StatAlertsManager.java, geode-core/src/main/java/org/apache/geode/internal/cache/ExpirationScheduler.java, geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PRSanityCheckMessage.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/AcceptorImpl.java, geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java, geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java, geode-core/src/test/java/org/apache/geode/internal/SystemTimerTest.java
Added cancellation check before scheduling an idle-timeout or
ack-wait-threshold timer task.  I had to add a new method to
SystemTimerTask and then noticed there were no tests for SystemTimer, so
I cleaned up that class and added tests.
=> GEODE-7884: server hangs due to IllegalStateException

geode-assembly/src/acceptanceTest/java/org/apache/geode/client/ClientSNIAcceptanceTest.java
Our windows CI machines don't have docker-compose, so don't run this test.
=> Ignore ClientSNIAcceptanceTest on windows

geode-core/src/distributedTest/java/org/apache/geode/internal/tcp/CloseConnectionTest.java
- Use await().untilAsserted() to allow connections to settle
- Use setup and tear down methods
- Do not extend CacheTestCase as it is an empty abstract with a deprecated super
email to …
=> GEODE-7889: Fix CloseConnectionTest

geode-assembly/src/acceptanceTest/java/org/apache/geode/client/ClientSNIAcceptanceTest.java, geode-junit/src/main/java/org/apache/geode/test/junit/rules/IgnoreOnWindowsRule.java
The rule to mark this test ignored has to run before the docker compose rule,
to prevent the test from failing first.
=> GEODE-7852: Ignore ClientSNIAcceptanceTest on windows

geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
It turns out the JDK sometimes automatically sets the SNI hostname and
sometimes does not.  With openjdk 8, it only sets SNI hostname if there is a
dot in the hostname. See sun.security.ssl.Utilities#addToSNIServerNameList
For this reason, we need to only set the SNI hostname if the JDK did not.
Otherwise it will complain that there is a `Duplicated server name of type 0`
Note, this fixes the Windows distributed tests failures we are seeing - for example this run https://concourse.apachegeode-ci.info/teams/main/pipelines/apache-develop-main/jobs/WindowsGfshDistributedTestOpenJDK8/builds/1391. Those failures aren't really because of windows, its because our windows CI instances have fully qualified hostnames as opposed to the linux docker containers.
=> GEODE-7900: Only set the SNI hostname if it is not present

geode-redis/src/integrationTest/java/org/apache/geode/redis/StringsIntegrationTest.java
One test for atomicity had too small a timeout to run reliably in CI. This has been increased to a safe value. (The timeout sometimes caused the subsequent test to fail as well.)
=> GEODE-7901: Redis testGetSet_shouldBeAtomic and testGetRange_rangePastEndOfValue_returnsEmptyString tests failing

dev-tools/release/deploy_rc_pipeline.sh, dev-tools/release/finalize_release.sh
.zip is no longer produced (as per GEODE-7719) so `run-geode-examples-from-src-zip` is no longer needed
also adds `verify-no-binaries`
also fixes `verify-keys` to check that no unexpected files are present
=> GEODE-7915: rc pipeline fixes and improvements

geode-tcp-server/src/test/java/org/apache/geode/distributed/internal/tcpserver/HostAndPortTest.java, geode-tcp-server/src/test/java/org/apache/geode/distributed/internal/tcpserver/TcpServerJUnitTest.java
In the case of DNS hijacking by an ISP, unresolvable hostnames may be
redirected to a search page. Log this breadcrumb in the test failures.
=> GEODE-7918: Add assertion message to DNS resolution assertions.

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionClearDUnitTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
Co-authored-by: Anil <agingade@pivotal.io>
=> GEODE-7912: cacheWriter should be triggered when PR.clear

dev-tools/release/set_versions.sh, geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/Tomcat8ClientServerRollingUpgradeTest.java
fix Tomcat8ClientServerRollingUpgradeTest to use product version instead of serialization version for building test classpath
with this fix, the test should work correctly regardless of whether the current release ends in -SNAPSHOT or not or .0 or not.
=> GEODE-7937: fix Tomcat test to get product version correctly

geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/Tomcat8ClientServerRollingUpgradeTest.java
fix Tomcat8ClientServerRollingUpgradeTest to use product version instead of serialization version for building test classpath
with this fix, the test should work correctly regardless of whether the current release ends in `-SNAPSHOT` or not or `.0` or not.
PLEASE NOTE that this PR targets **support/1.12**, not develop.  It was cherry-picked from develop (#4889).
=> GEODE-7937: [support/1.12] fix Tomcat test to get product version correctly

geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/MembershipIntegrationTest.java
CI failures yesterday: `MembershipIntegrationTest > secondMembershipCanJoinUsingTheSecondLocatorToStart`
It’s failing in both JDK8 and JDK11:
https://concourse.apachegeode-ci.info/teams/main/pipelines/apache-develop-main/jobs/IntegrationTestOpenJDK8/builds/4#A
```java
org.apache.geode.distributed.internal.membership.gms.MembershipIntegrationTest > secondMembershipCanJoinUsingTheSecondLocatorToStart FAILED
java.lang.AssertionError: 
Expected size:<2> but was:<1> in:
<[172.17.0.26(1:locator)<ec><v0>:41002]>
at org.apache.geode.distributed.internal.membership.gms.MembershipIntegrationTest.secondMembershipCanJoinUsingTheSecondLocatorToStart(MembershipIntegrationTest.java:144)
```
Looks like in a number of tests we expect to see two members in the view but see only one. I ran the test a couple …
=> GEODE-7919-fix-flaky: shut down threads after tests

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionSingleHopDUnitTest.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/InternalClientCache.java, geode-core/src/main/java/org/apache/geode/internal/cache/util/UncheckedUtils.java
Intermittent failures were caused by trying to stop and then restart
server(s) with the previously used ports which are no longer free on
the host machine.
This PR overhauls all of PartitionedRegionSingleHopDUnitTest while 
also fixing flaky failures caused by underlying BindExceptions in both:
* testMetadataIsSameOnAllServersAndClients
* testSingleHopWithHAWithLocator
I've added comments below that point to the actual BindException
fixes to aid in reviewing.
=> GEODE-6819: Fix PartitionedRegionSingleHopDUnitTest BindExceptions

geode-core/src/main/java/org/apache/geode/internal/cache/LatestLastAccessTimeMessage.java, geode-core/src/test/java/org/apache/geode/internal/cache/LatestLastAccessTimeMessageTest.java, geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/GMSMembershipJUnitTest.java, geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/TestMessage.java, geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessengerJUnitTest.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessenger.java
Don't deliver cache-level messages that were queued while disconnected
for auto-reconnect.  During auto-reconnect there is a QuorumChecker that
receives messages on the jgroups channel and tries to establish
communications with a quorum of the old membership view.  It may also
get JoinRequest messages and other membership-level messages but I
observed one case where it also queued cache-level messages when the
property disable-tcp was set to true (funnelling all comms through
jgroups).
I also added some null checks to the LatestLastAccessTimeMessage and a
small test for that. …
=> GEODE-7921: NullPointerExceptions logged during auto-reconnect

geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/GMSMemberDataJUnitTest.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMemberData.java
Removed hostname lookup from GMSMemberData a serialization method.
InternalDistributedMember does its own hostname lookup & there's no
reason for the lookup in GMSMemberData.  I found it was slowing down UDP
communications.
=> GEODE-7926: GMSMemberData is doing unnecessary reverse-DNS lookups

geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterOperationExecutors.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionMessage.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ShutdownMessage.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ThrottlingMemLinkedQueueWithDMStats.java, geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionMessageTest.java
Modified DistributionMessage to look for JGroups "internal" executor
threads.  We thought we'd turned off all JGroups thread pools but this
one is still around.  We don't want to process DistributionMessages in
these threads unless absolutely necessary since they're needed when
processing incoming messages.
=> GEODE-7920: Geode UDP INT thread found processing cache operations

geode-redis/src/main/java/org/apache/geode/redis/internal/AbstractSubscription.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PsubscribeExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/SubscribeExecutor.java
- Reduce logging verbosity of `ClosedChannelxception`s 
=> GEODE-7946: Fix redis publish/subscribe leaking netty buffers

extensions/geode-modules-tomcat8/src/distributedTest/java/org/apache/geode/modules/session/TestSessionsTomcat8Base.java, extensions/geode-modules-tomcat8/src/distributedTest/java/org/apache/geode/modules/session/Tomcat8SessionsClientServerDUnitTest.java, extensions/geode-modules-tomcat8/src/distributedTest/java/org/apache/geode/modules/session/Tomcat8SessionsDUnitTest.java
- They were using SocketUtils.getAvailableTCPPort
- Moved tests to use AvailablePortHelper class
- Added Sanity check to setup
=> GEODE-7098: Tomcat8SessionsClientServerDUnitTest Tests were getting bind failures

geode-docs/configuring/running/cluster-management-service.html.md.erb, geode-docs/reference/topics/gemfire_properties.html.md.erb
Edit for style - clarify default (username/password) vs token-based auth. Uppercase REST.
=> GEODE-7156: add docs for security-auth-token-enabled-components

geode-redis/src/acceptanceTest/java/org/apache/geode/redis/ExpireAtDockerAcceptanceTest.java, geode-redis/src/acceptanceTest/java/org/apache/geode/redis/ExpireDockerAcceptanceTest.java, geode-redis/src/acceptanceTest/java/org/apache/geode/redis/GeoDockerAcceptanceTest.java, geode-redis/src/acceptanceTest/java/org/apache/geode/redis/HashesDockerAcceptanceTest.java, geode-redis/src/acceptanceTest/java/org/apache/geode/redis/ListsDockerAcceptanceTest.java, geode-redis/src/acceptanceTest/java/org/apache/geode/redis/PexpireDockerAcceptanceTest.java, geode-redis/src/acceptanceTest/java/org/apache/geode/redis/PubSubDockerAcceptanceTest.java, geode-redis/src/acceptanceTest/java/org/apache/geode/redis/RenameDockerAcceptanceTest.java, geode-redis/src/acceptanceTest/java/org/apache/geode/redis/SetsDockerAcceptanceTest.java, geode-redis/src/acceptanceTest/java/org/apache/geode/redis/SortedSetsDockerAcceptanceTest.java, geode-redis/src/acceptanceTest/java/org/apache/geode/redis/StringsDockerAcceptanceTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ExpireAtIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ExpireIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/general/PexpireIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/ExpireAtExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/ExpireExecutor.java, geode-redis/src/test/java/org/apache/geode/redis/internal/executor/general/ExpireAtExecutorJUnitTest.java, geode-redis/src/test/java/org/apache/geode/redis/internal/executor/general/PExpireAtExecutorJUnitTest.java
This does not cover concurrent tests. It ensures correctness of single-threaded functionality compared to native Redis. A few fixes to commands have been implemented when identified by the new tests.
=> GEODE-7947 Implement tests for EXPIRE-related functionality

geode-web-api/src/integrationTest/java/org/apache/geode/rest/internal/web/controllers/RestAccessControllerTest.java, geode-web-api/src/main/java/org/apache/geode/rest/internal/web/controllers/AbstractBaseController.java, geode-web-api/src/main/java/org/apache/geode/rest/internal/web/controllers/CommonCrudController.java, geode-web-api/src/main/java/org/apache/geode/rest/internal/web/controllers/PdxBasedCrudController.java, geode-web-api/src/main/java/org/apache/geode/rest/internal/web/controllers/support/UpdateOp.java
The previous fix did not handle initial slashes (see GEODE-7938).
So now we have a new queryParam "?keys=" that can be used in place of the old {keys} pathVar. 
The new queryParam expects its keys to be encoded with UTF-8.
The previous fixes "/**" has been removed since it did harm to swagger.
=> GEODE-7938: added keys query param to GET, PUT, and DELETE /{region} endpoints

geode-docs/reference/topics/gemfire_properties.html.md.erb
I modified some code examples to accommodate narrower column width.
Reviewers: please verify that code samples for `locators` and `remote-locators` are valid.
(OK if these properties specify a single value rather than a comma-separated pair of values?)
=> GEODE-7966: User Guide - properties list - reformat oversized table

boms/geode-all-bom/src/test/resources/expected-pom.xml, buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy, geode-assembly/src/integrationTest/resources/assembly_content.txt, geode-assembly/src/integrationTest/resources/dependency_classpath.txt
as part of GEODE-7798: Fix flakiness in PubSubTest, the netty version was increased on develop; this version should be the minimum used on support branches as well.
Note: this PR targets a support branch, not develop.
=> GEODE-7969: [support/1.12] bump netty version to match develop

boms/geode-all-bom/src/test/resources/expected-pom.xml, buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy, geode-assembly/src/integrationTest/resources/assembly_content.txt, geode-assembly/src/integrationTest/resources/dependency_classpath.txt
go to netty 4.1.48 now ahead of #4867 which is not quite ready yet
=> GEODE-7969: bump netty version to latest

geode-assembly/src/acceptanceTest/java/org/apache/geode/client/sni/ClientSNIAcceptanceTest.java, geode-core/src/integrationTest/java/org/apache/geode/cache/client/ClientCacheFactoryJUnitTest.java, geode-core/src/integrationTest/resources/org/apache/geode/cache/client/ClientCacheFactoryJUnitTest_single_pool.xml, geode-core/src/main/java/org/apache/geode/cache/client/proxy/SniSocketFactory.java, geode-docs/reference/topics/client-cache-elements-list.html.md.erb, geode-docs/reference/topics/client-cache.html.md.erb, geode-docs/topologies_and_comm/cs_configuration/setting_up_a_client_server_system.html.md.erb, geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/ProcessManager.java
Modified SNISocketFactory so it can be used in cache.xml
Added a test for the new cache.xml element.
Updated docs for cache.xml and updated client configuration
instructions.
Please point me at any other docs that should be updated or suggestions for new sections.
=> GEODE-7852: SNI extension support

ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/shared/jinja.variables.yml
Update the bump jobs to increment and add the semver release token which
clears the wrong semver picking happening in past few days.
Signed-off-by: Robert Houghton <rhoughton@pivotal.io>
=> GEODE-7779: Concourse BumpXYZ does not include {prerelease}

geode-redis/src/integrationTest/java/org/apache/geode/redis/HashesIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/StringsIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/KeyRegistrar.java, geode-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/GetExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/SetExecutor.java, geode-redis/src/test/java/org/apache/geode/redis/internal/executor/string/StringGetExecutorJUnitTest.java, geode-redis/src/test/java/org/apache/geode/redis/internal/executor/string/StringSetExecutorJUnitTest.java
Get/Set commands for RedisString datatype to cover new parameters
=> GEODE-7949: Geode Redis - Get/Set commands for RedisString datatype to cover new parameters

geode-redis/src/main/java/org/apache/geode/redis/GeodeRedisServer.java, geode-redis/src/main/java/org/apache/geode/redis/internal/Command.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/GeodeRedisHashSynchronized.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HDelExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HGetAllExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HMSetExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HSetExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/RedisHash.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/GeodeRedisSetSynchronized.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/RedisSet.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SAddExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SMembersExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SRemExecutor.java
This commit builds a GeodeRedisSetSynchronized class that brings
together "set" methods.  These three are necessary for Spring-Session so
they are the only ones included.
Hey team,
The commit brings together two ideas in this PR:
1.  It synchronizes all calls to the set (at least sadd,srem,smembers) via compute.
2. It decouples all geode related code from the Executors.  We have discussed this a couple times, but I wanted to show it, and see if you all are on board.
=> Decouple geode in sadd,srem,smembers

geode-redis/src/main/java/org/apache/geode/redis/GeodeRedisServer.java
Change the redis API to have redundant regions by default.
=> GEODE-7981: Change the redis default region type to PARTITION_REDUNDANT

geode-assembly/src/acceptanceTest/java/org/apache/geode/client/sni/ClientSNIAcceptanceTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/client/sni/NotOnWindowsDockerRule.java, geode-assembly/src/acceptanceTest/resources/org/apache/geode/client/sni/scripts/geode-starter.gfsh, geode-core/src/main/java/org/apache/geode/cache/client/proxy/SniSocketFactory.java, geode-tcp-server/src/main/java/org/apache/geode/distributed/internal/tcpserver/HostAndPort.java, geode-tcp-server/src/test/java/org/apache/geode/distributed/internal/tcpserver/HostAndPortTest.java
Adding tests for query, putAll, getAll.  Ensuring that a client can
receive responses that are streamed through "chunking" from the server.
The test now creates the server cluster and client cache in a class rule
for faster execution.
=> GEODE-7852: Add bulk operation / large result tests for SNI gateway

geode-redis/src/integrationTest/java/org/apache/geode/redis/PubSubIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/mocks/MockSubscriber.java
The complete fix also builds on the following prior fixes
- GEODE-7943 add synchronization to Subscriptions class
- GEODE-7946: Fix redis publish/subscribe leaking netty buffers
=> GEODE-7870: Fix PubSubIntegrationTest flakiness

geode-redis/src/acceptanceTest/java/org/apache/geode/redis/ExpireAtDockerAcceptanceTest.java, geode-redis/src/acceptanceTest/java/org/apache/geode/redis/PersistDockerAcceptanceTest.java, geode-redis/src/acceptanceTest/java/org/apache/geode/redis/PexpireDockerAcceptanceTest.java, geode-redis/src/acceptanceTest/java/org/apache/geode/redis/RenameDockerAcceptanceTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/PersistDUnitTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ExpireIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/general/PersistIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/PersistExecutor.java, geode-redis/src/test/java/org/apache/geode/redis/internal/executor/general/PersistExecutorJUnitTest.java
The Redis PERSIST command removes the existing timeout on a key (https://redis.io/commands/persist).  The PERSIST command was previously implemented, but not tested. This PR adds tests for this command.
=>  GEODE-7979: Implement a test class for the PERSIST Redis API command

geode-redis/src/test/java/org/apache/geode/redis/internal/RedisLockServiceJUnitTest.java
Ensure thread that originally obtained the lock has released the lock and died prior to attempting to lock again.
=> GEODE-7986: RedisLockServiceJUnitTest fails intermittently in CI on WindowsUnitTestOpenJDK8

ci/pipelines/shared/jinja.variables.yml, dev-tools/release/promote_rc.sh
develop pipeline is still using 1.10.0 as baseline for benchmarks.  because we've made some improvements since then, we won't be catching any regressions against those gains.
now that 1.12.0 is released, use that as the baseline
=> GEODE-7985: benchmark develop against 1.12.0 rather than 1.10.0

geode-assembly/src/acceptanceTest/java/org/apache/geode/client/sni/ClientSNICQAcceptanceTest.java, geode-assembly/src/acceptanceTest/resources/org/apache/geode/client/sni/geode-config/gemfire.properties, geode-core/src/main/java/org/apache/geode/internal/statistics/StatArchiveReader.java
This ensures that a server sitting behind an SNI gateway detects the
loss of a client and cleans up after it.  In this case the test detects
that the server has closed CQs created by the non-durable client.
Since test code is not accessible in the Docker container that's running
the server I've enhanced the StatArchiveReader to be able to report the
values of a statistic and have enabled statistics recording in the
server.  Much of this code came from the deprecated SystemAdmin class.
(cherry picked from commit 376df4cc7abc6db38b4b298f8af6f3c53baedf15)
Please ensure that once the PR is submitted, check Concourse for build …
=> GEODE-7852: test ClientHealthMonitor functionality behind a SNI gateway

geode-core/src/main/java/org/apache/geode/internal/cache/BucketAdvisor.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionDataStore.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueue.java, geode-core/src/test/java/org/apache/geode/internal/cache/BucketAdvisorTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderOperationsDUnitTest.java
The BucketAdvisor can now keep track of more than just one shadow
bucket to avoid incorrectly marking all of them as destroyed.
=> GEODE-7940: Fix Tracking of ShadowBuckets Destroyed

geode-assembly/src/acceptanceTest/java/org/apache/geode/client/sni/ClientSNICQAcceptanceTest.java
[GEODE-7991](https://issues.apache.org/jira/browse/GEODE-7991)
Test was flaky. Added awaitility calls to wait for test `CqListener` to see all events.
=> GEODE-7991: wait for test CqListener to see events

geode-docs/tools_modules/pulse/pulse-auth.html.md.erb, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/data/Repository.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/security/CustomSecurityConfig.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/security/DefaultSecurityConfig.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/security/GemFireAuthentication.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/security/GemFireAuthenticationProvider.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/security/GemfireSecurityConfig.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/security/OAuthClientConfig.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/security/OAuthSecurityConfig.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/security/RepositoryLogoutHandler.java, geode-pulse/src/main/resources/pulse.properties, geode-pulse/src/test/java/org/apache/geode/tools/pulse/internal/security/RepositoryLogoutHandlerTest.java
When Pulse is configured to use OAuth, and a user logs out of Pulse,
Pulse redirects the browser to a page where the user can take action to
end their session. The available actions depend on the OAuth provider,
but may include revoking the token or logging out of the OAuth provider
entirely.
Main changes:
- Changed OAuthSecurityConfig to install two logout handlers: A
RepositoryLogoutHandler (renamed from LogoutHandler) and an
OidcClientInitiatedLogoutSuccessHandler.
- Added a pulse.security.oauth.endSessionEndpoint property to specify
the URL to which the OidcClientInitiatedLogoutSuccessHandler should
redirect the browser on logout.
- Configured the OAuthSecurityConfig to add the "end session endpoint"
property value to the client configuration metadata.  On logout, the …
=> GEODE-7851: Pulse logout requests end of OAuth session

geode-lucene/src/upgradeTest/java/org/apache/geode/cache/lucene/RollingUpgradeQueryReturnsCorrectResultsAfterClientAndServersAreRolledOverAllBucketsCreated.java
To prevent suspect strings from a background thread in the client, close the
client before the locator in this test.
=> GEODE-7982: Close the client first in rolling upgrade test

geode-redis/src/integrationTest/java/org/apache/geode/redis/HashesIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/StringsIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ConcurrentLoopingThreads.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ExistsIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/general/LoopingThreads.java
=> improvement/GEODE-8002 Refactor: Extract class to encapsulate concurrent execution

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionClearWithExpirationDUnitTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionTest.java
Added distributed tests to verify the clear operation on Partitioned
Regions works as expected when expiration is configured.
- Fixed LocalRegion class to clear the entryExpiryTasks Map whenever
the cancelAllEntryExpiryTasks method is invoked.
=> GEODE-7676: Add PR clear with expiration tests

geode-docs/tools_modules/redis_adapter.html.md.erb, geode-redis/src/integrationTest/java/org/apache/geode/redis/RedisServerIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/GeodeRedisServer.java
Fixed docs to describe the new default.
Also if the system property it set to an unknown shortcut
then it now defaults to PARTITION_REDUNDANT instead of PARTITION.
The test now validates this case and now uses assertThat instead of assert.
=> GEODE-7981: Redis default should be PARTITION_REDUNDANT

geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/MultiServerPartitionedRegionQueryDUnitTest.java, geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt, geode-core/src/main/java/org/apache/geode/cache/query/internal/CumulativeNonDistinctResults.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/NWayMergeResults.java
* Previously, when a query is executed in a function, the toData on specific results
set types would write directly to the wrong output stream, causing deserialization issues
=> GEODE-7957: query results toData will write to correct output stream 

geode-assembly/src/integrationTest/java/org/apache/geode/tools/pulse/PulseLoggingTest.java, geode-pulse/build.gradle
Pulse was not logging because its war file had no slf4j implementation.
This commit adds the log4j2 implementation to the war file.
Authored-by: Dale Emery <demery@pivotal.io>
=> GEODE-7851: Add slf4j implementation to Pulse

dev-tools/release/promote_rc.sh
Need to add the old version on the support branch too now, not just develop (e.g. as soon as 1.12.0 was released, the support branch became 1.12.1 so 1.12.0 is an "old" version for both develop and support/1.12)
This was a non-issue before when we had release branches that were discarded after release.
This PR updates the release scripts so this will happen automatically.
=> GEODE-8023: add old version on support branch

geode-lucene/src/upgradeTest/java/org/apache/geode/cache/lucene/RollingUpgradeReindexShouldBeSuccessfulWhenAllServersRollToCurrentVersion.java
This Lucene upgrade test is aimed at old versions that are incompatible with the current version.  The test assumed that ALL old versions are incompatible.  However on a support branch, the current could be 1.12.1 and the "old" version could be 1.12.0, which are compatible.
To avoid hangs, skip this test when the minors are the same, since that is not the intended precondition for the test.
=> GEODE-8025: fix lucene test to not hang on support branches

dev-tools/release/deploy_rc_pipeline.sh, dev-tools/release/prepare_rc.sh
* make release artifact names consistent (-src if its src, .tgz not .tar.gz, .sha256 not .sha512, internal top-level-dir matches filename)
* verify file size, LICENSE, NOTICE, and copyright year
* verify version and SHA reported by gfsh
=> GEODE-8026: release improvements

geode-core/src/distributedTest/java/org/apache/geode/ClusterCommunicationsDUnitTest.java, geode-core/src/main/java/org/apache/geode/internal/net/NioSslEngine.java, geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java, geode-core/src/test/java/org/apache/geode/internal/net/NioSslEngineTest.java
revert change in GEODE-6661 that made NioSslEngine use a direct buffer.
This class is not designed to share its buffer with a pool in
BufferPool.  Connection is also modified to use a heap buffer for
reading encrypted SSL packets for consistency.  New tests ensure that
these buffers are the correct type when using SSL or plain sockets.
=> GEODE-8020: buffer corruption in SSL communications

geode-core/src/test/java/org/apache/geode/internal/net/SocketCreatorFactoryJUnitTest.java
- Ensure that any existing SocketCreatorFactory instances created by
previously-run tests are closed before each test execution in
SocketFactoryCreatorJUnitTest
=> GEODE-8031: Close lingering SocketCreatorFactory instances

geode-assembly/src/integrationTest/resources/assembly_content.txt, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/control/RestoreRedundancyOperationDUnitTest.java, geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt, geode-core/src/main/java/org/apache/geode/cache/control/RegionRedundancyStatus.java, geode-core/src/main/java/org/apache/geode/cache/control/ResourceManager.java, geode-core/src/main/java/org/apache/geode/cache/control/RestoreRedundancyOperation.java, geode-core/src/main/java/org/apache/geode/cache/control/RestoreRedundancyResults.java, geode-core/src/main/java/org/apache/geode/internal/DSFIDFactory.java, geode-core/src/main/java/org/apache/geode/internal/cache/control/InternalResourceManager.java, geode-core/src/main/java/org/apache/geode/internal/cache/control/RegionRedundancyStatusImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/control/ResourceManagerStats.java, geode-core/src/main/java/org/apache/geode/internal/cache/control/RestoreRedundancyOperationImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/control/RestoreRedundancyResultsImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PartitionedRegionRebalanceOp.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/rebalance/CompositeDirector.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/rebalance/SatisfyRedundancy.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/rebalance/model/PartitionedRegionLoadModel.java, geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/ResourceManagerCreation.java, geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt, geode-core/src/test/java/org/apache/geode/internal/cache/control/RegionRedundancyStatusImplTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/control/RestoreRedundancyOperationImplTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/control/RestoreRedundancyResultsImplTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/rebalance/BucketOperatorImplTest.java, geode-serialization/src/main/java/org/apache/geode/internal/serialization/DataSerializableFixedID.java
- Add RestoreRedundancyOperation interface and Impl class
- Add RestoreRedundancyResults interface and Impl class
- Add RegionRedundancyStatus interface and Impl class
- Add accessor methods for RestoreRedundancyOperation to ResourceManager interface
- Replace manually-synchronized sets in InternalResourceManager with
ConcurrentHashMap
- Add stats for restore redundancy operations
- Add unit and DUnit tests for all the above
This commit undoes the previous revert of these changes.
- [N/A] If adding new dependencies to the code, are these dependencies licensed in a way that is …
=> GEODE-7953: Restore Redundancy Internal API

geode-redis/src/integrationTest/java/org/apache/geode/redis/HashesIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/SetsIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/GeodeRedisServer.java, geode-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/GeodeRedisHashSynchronized.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HDelExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/GeodeRedisSetSynchronized.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SRemExecutor.java, geode-redis/src/test/java/org/apache/geode/redis/internal/executor/string/GetSetExecutorJUnitTest.java
Redis completely removes keys for sets and hashes once they are empty.  Currently the implementation leaves a key for an empty set/hash once the last element is removed.
=> GEODE 8014: Sets and Hashes should be deleted once they are empty

geode-redis/src/integrationTest/java/org/apache/geode/redis/HashesIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/RedisLockServiceIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/general/PexpireIntegrationTest.java
=> GEODE-8050: Ensure tests cleanup consistently to allow running them all within one JVM instance

geode-core/src/distributedTest/java/org/apache/geode/ClusterCommunicationsDUnitTest.java, geode-core/src/main/java/org/apache/geode/internal/net/NioSslEngine.java, geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java, geode-core/src/test/java/org/apache/geode/internal/net/NioSslEngineTest.java
This reverts commit ec8db54ad7f342542762beb8f3e912dff44e3a53.
The fix for GEODE-8020 reduced performance in SSL benchmark tests.
Unfortunately this revert leaves SSL communications broken, but there
are no CI tests that show that this is the case.
=> Revert "GEODE-8020: buffer corruption in SSL communications (#4994)"

geode-redis/build.gradle, geode-redis/src/commonTest/java/org/apache/geode/redis/ConcurrentLoopingThreads.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/HMsetDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/HsetDUnitTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/HashesIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/StringsIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ExistsIntegrationTest.java
HSET (https://redis.io/commands/hset) and HMSET (https://redis.io/commands/hmset) set fields and values on hashes. We created distributed tests to ensure HSET and HMSET can happen concurrently on multiple servers.
=> GEODE-8051: Create multi-node concurrency (distributed) tests for HSET and HMSET

geode-core/src/test/java/org/apache/geode/internal/cache/GemFireCacheImplCloseTest.java
GemFireCacheImplCloseTest.close_blocksUntilFirstCallToCloseCompletes
has failed for a couple other developers. I'm marking it with Ignore
while I try to reproduce and fix the problem.
=> GEODE-8060: Ignore flaky GemFireCacheImplCloseTest test

geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/Oplog.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/PersistentGatewaySenderWithIsolatedDiskStoreDistributedTest.java
The OpLog initialization now delete unused drf files to prevent the
proliferation of unused records and files within the system, which
can could cause members to fail during startup while recovering
disk-stores (especially when they are isolated for gateway-senders).
- Added distributed tests.
- Delete orphaned drf files when deleting the corresponding
crf during recovery.
=> GEODE-8029: Delete orphaned drf files

geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java, geode-core/src/test/java/org/apache/geode/internal/cache/GemFireCacheImplCloseTest.java
I found and fixed the issues causing memcached IntegrationJUnitTest to fail. Please re-review and hopefully it should pass all precheckin jobs this time.
I hate creating a special package-private method just for the test BUT I can't think of an effective test without getting some sort of state from GemFireCacheImpl that identifies which call or which thread actually performed the close.
Without identifying which call or thread performed the close, the test devolves to just asserting that two threads can call close but it can't really assert which call did the actual work of closing GemFireCacheImpl. From a really high level, we don't really care. But at a low level, we don't want the 2nd callers to return before the 1st caller has finished the close (doesn't matter if the 1st caller …
=> GEODE-8060: Fix flakiness in GemFireCacheImplCloseTest

geode-core/src/distributedTest/java/org/apache/geode/ClusterCommunicationsDUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java, geode-core/src/main/java/org/apache/geode/internal/cache/properties.html, geode-core/src/main/java/org/apache/geode/internal/net/BufferPool.java, geode-core/src/main/java/org/apache/geode/internal/net/NioSslEngine.java, geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java, geode-core/src/main/java/org/apache/geode/internal/tcp/MsgStreamer.java, geode-core/src/main/java/org/apache/geode/internal/tcp/MsgStreamerList.java, geode-core/src/test/java/org/apache/geode/internal/net/NioSslEngineTest.java, geode-core/src/test/java/org/apache/geode/internal/tcp/MsgStreamerTest.java
This fixes some buffer handling in MsgStreamerList and alters
MstStreamer to avoid creating MsgStreamerList and VersionedMsgStreamers
during normal, non-upgrade, operations.
It also changes NioSslEngine to use synchronization in more places,
notably the close() method, which was possibly allowing multiple threads to
change the state of the engine.
=> GEODE-8020: buffer management problems

geode-junit/src/main/java/org/apache/geode/test/junit/rules/ExecutorServiceRule.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/PubSubDUnitTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/PubSubIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/DummySubscription.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/mocks/MockSubscriberWithLatch.java, geode-redis/src/main/java/org/apache/geode/redis/GeodeRedisServer.java, geode-redis/src/main/java/org/apache/geode/redis/internal/AbstractSubscription.java, geode-redis/src/main/java/org/apache/geode/redis/internal/Client.java, geode-redis/src/main/java/org/apache/geode/redis/internal/ExecutionHandlerContext.java, geode-redis/src/main/java/org/apache/geode/redis/internal/PubSubImpl.java, geode-redis/src/main/java/org/apache/geode/redis/internal/PublishResultCollector.java, geode-redis/src/main/java/org/apache/geode/redis/internal/Subscription.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PublishExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/UnsubscribeExecutor.java, geode-redis/src/test/java/org/apache/geode/redis/internal/PubSubImplJUnitTest.java
- Now delegate PUBLISH responses to a background executor in order to
free up the Netty worker thread. This prevents possible deadlocks.
Co-authored-by: Murtuza Boxwala <mboxwala@vmware.com>
Co-authored-by: Ray Ingles <ringles@vmware.com>
Co-authored-by: Jens Deppe <jdeppe@vmware.com>
=> GEODE-7998: Do not block Netty threads when publishing

geode-redis/src/main/java/org/apache/geode/redis/internal/executor/AbstractScanExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/CommandFunction.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/ScanExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HScanExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/RedisSet.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/RedisSetCommands.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/RedisSetCommandsFunctionExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SCardExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SIsMemberExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SMembersExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SMoveExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SPopExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SRandMemberExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SScanExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SetOpExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZScanExecutor.java
All set op executors should use the CommandFunction to route the op to the partitionRegion primary.
The following redis set commands have been changed to use functions in the PR:
SCARD
SISMEMBER
SPOP
SRANDMEMBER
SSCAN
This pull request is a WIP to see how easy it would be to change the current implementation to one that uses functions.
=> GEODE-8089: more redis set ops use functions

geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueue.java, geode-core/src/test/java/org/apache/geode/internal/cache/DistributedRegionTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/misc/WanValidationsDUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/AlterRegionCommandDUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandDUnitTest.java, geode-wan/src/integrationTest/java/org/apache/geode/internal/cache/wan/misc/WANConfigurationJUnitTest.java
Attaching a parallel gateway-sender or async-event-queue to a
Replicate Region through the AttributesMutator class now throws an
exception instead of wrongly assigning the dispatcher to the region.
- Fixed several warnings.
- Replaced usages of 'junit.Assert' by 'assertj'.
- Changed test methods to use more meaningful names.
- Removed references to old ids used by another ticketing system.
=> GEODE-8079: Fix DistributedRegion Validations

geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java, geode-docs/tools_modules/gfsh/command-pages/connect.html.md.erb
this PR aligns the command help and documentation with the code, there is no default value for `--url` parameter.
Command help will look as follows:
```
gfsh>connect --url
optional --url: Indicates the base URL to the Manager's HTTP service.  For example: 'http://<host>:<port>/geode-mgmt/v1'; no default value
```
=> GEODE-7707: Tab completing '--url' on 'connect' gives two default values

geode-core/src/distributedTest/java/org/apache/geode/management/MemberMXBeanDistributedTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/PRHARedundancyProvider.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java, geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionTest.java
In case we are creating persistent colocated region, and parent region is already initialized,
show metrics per server will show incorrect values for totalBucketCount and totalPrimaryCount.
This is the solution.
submit an update to your PR as soon …
=> GEODE-7963: solution for faulty bucket metrics

geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb
Documentation of `--manual-start` option of `create gateway-receiver` gfsh command wrongly states that the default option is `true`.
But taking a look at the code it can be verified that the default option is false.
=> GEODE-8111: Fix create gw receiver --manual-start doc

geode-redis/src/main/java/org/apache/geode/redis/internal/executor/CommandFunction.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/EmptyRedisHash.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisHashInRegion.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/RedisHash.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/EmptyRedisSet.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/RedisSet.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/RedisSetInRegion.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SMoveExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SetOpExecutor.java
I broke up the `RedisSet` and `RedisHash` classes by moving the static methods into separate non-static classes.  I also made canonical empty classes, so we don't have to do as much null-checking.
=> GEODE-8114: Refactor set

geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/SharedErrorCollector.java, geode-junit/src/main/java/org/apache/geode/test/junit/rules/accessible/AccessibleErrorCollector.java
Test coverage is provided by SharedErrorCollectorDistributedTest which requires
no changes since this is a simple extraction refactor.
=> GEODE-8125: Extract AccessibleErrorCollector from SharedErrorCollector

build.gradle, gradle/standard-subproject-configuration.gradle
This was broken due to a change in Gradle default task names in the root project.
=> GEODE-8133: Fix task chaining for 'devBuild'

geode-membership/build.gradle, geode-membership/src/integrationTest/resources/log4j2.xml
hexTid is not available to the geode-membership module.  I'm replacing
it with tid, which is supported by the logger implementation used by
membership tests.  This will let us see thread ID numbers in the logs.
=> GEODE-7792: configure logging for geode-membership integration tests

geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java, geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java, geode-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java, geode-redis/src/main/java/org/apache/geode/redis/internal/RegionProvider.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/AbstractExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/CommandFunction.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/DelExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/ExistsExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/FlushAllExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisDataInRegion.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisKeyCommands.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisKeyCommandsFunctionExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisKeyInRegion.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RenameExecutor.java, geode-redis/src/main/resources/org/apache/geode/redis/internal/sanctioned-geode-redis-serializables.txt, geode-redis/src/test/java/org/apache/geode/redis/internal/executor/AbstractExecutorJUnitTest.java, geode-redis/src/test/java/org/apache/geode/redis/internal/executor/general/ExistsExecutorJUnitTest.java, geode-redis/src/test/java/org/apache/geode/redis/internal/executor/string/DelExecutorJUnitTest.java
=> GEODE-8147: DELETE and EXISTS implement Function-Delta

boms/geode-all-bom/src/test/resources/expected-pom.xml, buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
Analysis has determined that Geode is not vulnerable to known issues with spring-security 5.3.1, so this update to 5.3.2 is just to avoid unnecessary noise in automated scans
=> GEODE-8167: bump spring security to recommended version

boms/geode-all-bom/src/test/resources/expected-pom.xml, buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy, geode-assembly/src/integrationTest/resources/assembly_content.txt, geode-assembly/src/integrationTest/resources/dependency_classpath.txt, geode-assembly/src/main/dist/LICENSE
A performance degradation was introduced when upgrading this library
to a more recent version, downgrading to the last known working one
until a full fix is found.
=> GEODE-8150: Downgrade classgraph to 4.8.52

ci/images/alpine-tools/Dockerfile, ci/pipelines/meta/jinja.template.yml
* Built cleanly in multistage build
* Moved from python2 -> python3
* Pin concourse-pipeline resource
=> GEODE-8146: use latest winrm in tools image

geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
This PR does not solve the problem of the alert system causing a P2P
message reader to block but instead ensures that the reader thread will
write deserialization information to the log before issuing a fatal
alert.  If the alert level is set to "info" this won't help, but no-one
would set the alert level to that level.
Along the way I removed some duplicate strings.
=> GEODE-8131: reader thread blocked attempting to issue an alert

geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java, geode-core/src/main/java/org/apache/geode/distributed/internal/AbstractDistributionConfig.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfigImpl.java, geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java, geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionConfigJUnitTest.java, geode-docs/reference/topics/gemfire_properties.html.md.erb, geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/StartServerCommand.java, geode-redis/src/commonTest/java/org/apache/geode/redis/GeodeRedisServerRule.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/GeodeRedisServerStartupDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/PubSubDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/RedisDistDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/ExpireDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/hash/HMsetDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/hash/HsetDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/keys/ExistsDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/keys/PersistDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/set/SaddDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/set/SremDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionDUnitTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/ConcurrentStartIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/SSLTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java, geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisService.java
- Introduce a Geode parameter - `redis-enabled` which is `false` by default. This parameter determines whether the service is started or not.
- Set the default `redis-port` value to `6379`
- `redis-port` range is 0..65535
- When `redis-port=0`, and `redis-enabled=true` the service will start on an ephemeral port.
- When `gfsh` is used with `--redis-port`, `--redis-password`, or `--redis-bind-address`, it should automatically set `redis-enabled=true`
`gemfire_properties.html.md.erb` updated as part of this PR: https://github.com/apache/geode/pull/5130
=> GEODE-8138: Improve semantics of the redis-port option

geode-redis/src/distributedTest/java/org/apache/geode/redis/session/springRedisTestApplication/config/SessionListener.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/StringsIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/SubscriptionsIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
Ticket description, reported by @dschneider-pivotal :
> 
> I noticed in SMoveExecutor a number of System.out.println calls. This should not be done. 
> Either remove the calls (that is what I recommend for SMoveExecutor) or use a logger. 
> I don't know if SMoveExecutor is the only place this happens so a code scan should be done.
`SMoveExecutor` class was already fixed but I searched for other calls to `System.out.println` in `geode-redis` and I have removed them.
I also updated the logger of `GeodeRedisServer` class.
=> GEODE-8108: Remove System.out.println calls from geode-redis

geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java, geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsDUnitTest.java, geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/AlterDiskStoreCommandIntegrationTest.java, geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/DescribeDiskStoreCommandIntegrationTest.java, geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/AlterOfflineDiskStoreCommand.java, geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/CompactOfflineDiskStoreCommand.java, geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeOfflineDiskStoreCommand.java, geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsUtils.java, geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/UpgradeOfflineDiskStoreCommand.java, geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/ValidateDiskStoreCommand.java
This reverts commit c3c226a822538cb25e3945b75eef6977a985716e.
Intermittent errors were observed while executing some internal tests and commit [c3c226a](https://github.com/apache/geode/commit/c3c226a822538cb25e3945b75eef6977a985716e) was determined to be responsible. As of yet, no local reproduction of the issue is available, but work is ongoing to provide a test that can be used to debug the issue.
=> Revert "GEODE-8119: closing threads when offline disk store is executed"

geode-docs/reference/statistics_list.html.md.erb
The link of region entry heap-based eviction is wrong and shows the html anchor id in the statistics lists:
* Region Entry Eviction - Heap-based eviction (HeapLRUStatistics)#section_3B74F6FA08A374FBD92AA23047929B4F)
https://geode.apache.org/docs/guide/112/reference/statistics_list.html
=> GEODE-8193: Broken link in statistics list

geode-common/src/main/java/org/apache/geode/util/internal/TeeOutputStream.java, geode-core/src/main/java/org/apache/geode/internal/InternalDataSerializer.java, geode-core/src/main/java/org/apache/geode/internal/io/CompositeOutputStream.java, geode-core/src/test/java/org/apache/geode/internal/io/CompositeOutputStreamJUnitTest.java, geode-web-api/src/main/java/org/apache/geode/rest/internal/web/http/converter/CustomMappingJackson2HttpMessageConverter.java, geode-web-management/src/main/java/org/apache/geode/management/internal/rest/converter/CustomMappingJackson2HttpMessageConverter.java
* Prevent overheads of writing one byte at a time.
=> GEODE-7864: Override the default implementation of write(byte[],int,int)

geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
The RedisData region name now starts with "__".
Also it now always tries to create the region and will fail
if it already exists.
=> GEODE-8201: change internal redis region name to start with double underscore

geode-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt, geode-redis/src/main/java/org/apache/geode/redis/internal/ByteArrayWrapper.java, geode-redis/src/main/java/org/apache/geode/redis/internal/Coder.java, geode-redis/src/main/java/org/apache/geode/redis/internal/Command.java, geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisService.java, geode-serialization/src/main/java/org/apache/geode/internal/serialization/DataSerializableFixedID.java
ByteArrayWrapper now implements DataSerializableFixedID which should save us ~40 bytes each time it is serialized.
ByteArrayWrapper no longer caches its "hash" and "string" form which will cut down its memory overhead by over 70%.
When we convert a sequence of bytes to a String, the Coder no longer calls "intern" which will also save some memory and time.
=> GEODE-8199: optimize ByteArrayWrapper serialization and memory usage

geode-web/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ShutdownCommandOverHttpDUnitTest.java
Use IgnoredException for DistributedSystemDisconnectedException.
=> GEODE-6070: Fix ShutdownCommandOverHttpDUnitTest flakiness

ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/images/jinja.template.yml
Created a new gcs-resource to print out the contents of a output file.
Change the existing passing token resource to the newer one.
=> GEODE-7759: Print out the Passing token file contents.

geode-core/src/main/java/org/apache/geode/internal/cache/RegionNameValidation.java, geode-core/src/test/java/org/apache/geode/internal/cache/RegionNameValidationTest.java, geode-docs/basic_config/data_regions/region_naming.html.md.erb
With existing regex we supported also: [, ], ^, `, \ in region name.
With a new regex we supported only characters described in the documentation.
=> GEODE-7956: correct legal region names

geode-docs/reference/topics/gemfire_properties.html.md.erb
Added information about a new system property that prevents disabling logging to standard out when a log file is present
=> GEODE-8203: Adding standard-output-always-on to docs

geode-common/src/main/java/org/apache/geode/internal/inet/LocalHostUtil.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/GeodeRedisServerStartupDUnitTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
Changed redis to have its default bind address to be anyLocalAddress instead of a single local address.
LocalHostUtil now has anyLocalAddress support.
=> GEODE-8158: enhance LocalHostUtil to support anyLocalAddress

geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java, geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java, geode-docs/reference/topics/gemfire_properties.html.md.erb
Geode Redis API now listens on all local addresses when bind-address is not specified. The docs should be updated to reflect this change.
=> GEODE-8218: Update docs to reflect changes to default redis-bind-address behavior

geode-redis/src/distributedTest/java/org/apache/geode/redis/PubSubDUnitTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PublishExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSub.java, geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSubImpl.java
Changed PubSubDUnitTest to have an additional non-redis server.
This caused multiple tests in it to fail.
Changed the publish code that uses the FunctionService
to only execute the function on members that have the redis data region.
The tests started passing.
=> GEODE-8226: change publish to work with non-redis servers present 

geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/Oplog.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/PersistentGatewaySenderWithIsolatedDiskStoreDistributedTest.java
This reverts the revert of the original commit and also fixes the
originally introduced issues.
----
The OpLog initialization now delete unused drf files to prevent the
proliferation of unused records and files within the system, which
can could cause members to fail during startup while recovering
disk-stores (especially when they are isolated for gateway-senders).
- Added distributed tests.
- Delete orphaned drf files when deleting the corresponding
crf during recovery.
submit an update to your PR as soon as possible. If you need help, …
=> GEODE-8029: Delete orphaned drf files (2nd try)

geode-redis/src/acceptanceTest/java/org/apache/geode/redis/RenameNativeRedisAcceptanceTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/RenameIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandSupportLevel.java, geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java, geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Command.java, geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java, geode-redis/src/main/resources/org/apache/geode/redis/internal/sanctioned-geode-redis-serializables.txt, geode-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java
If a known redis command that is not implemented is executed then
it will fail with the message '<command> is not implemented'.
=> GEODE-8232: add better error message for unimplemented redis commands

ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/shared/jinja.variables.yml
before, we ran Build, then all <x>Test jobs in parallel (which takes ~5 hours), then all Benchmark<x> jobs (which takes ~5 hours).
Presumably the benchmarks were run after all tests, on the premise that benchmarks are meaningless if the code is not correct.  However, required PR checks now prevent incorrect code from getting into develop in the first place, and the remaining occasional failures are flaky, so it's rather arbitrary to gate benchmarks on a lottery.
However, faster feedback has clear benefits, hence this PR to cut our CI pipeline from 10 hours to 5 hours.
Also eliminates redundant jobs (ApiCheck and UnitTest are deterministic and already have required JDK11 flavors in the PR pipeline, so JDK8 flavor only is more than sufficient in the develop pipeline)
Also decreases …
=> GEODE-8230: run benchmarks in parallel with other CI jobs

geode-assembly/src/acceptanceTest/java/org/apache/geode/launchers/LocatorLauncherWithCustomLogConfigAcceptanceTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/launchers/LocatorLauncherWithPulseAcceptanceTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/launchers/LocatorLauncherWithPulseAndCustomLogConfigAcceptanceTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/launchers/ServerLauncherWithCustomLogConfigAcceptanceTest.java
The Launcher acceptance tests fail on Windows because the tests are hardcoded to use java instead of java.exe.
=> GEODE-8243: Use java.exe on Windows in Launcher tests

geode-dunit/src/main/java/org/apache/geode/management/internal/cli/commands/QueryCommandIntegrationTestBase.java, geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/GfshParser.java, geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/GfshParserJUnitTest.java
When parsing the user input in gfsh, the first `=` character position was used to split strings which were expected to follow the pattern `--parameter=value`. But if the `=` sign is not introduced, the `=` is deleted in `--parameter` and `value` (if exists).
In the case of `--query` parameter, the value of the parameter (the query itself) is very likely to contain a `=`, which could be removed from the query.
With this modification, if a query is introduced without the `=` between `--query` and the query statement, the `=` will not be removed from the query.
I also have included the `--J` parameter in this check, because its value is always containing a `=`.
=> GEODE-8179: gfsh query cmd returns incorrect results if '=' sign is missing

geode-core/src/integrationTest/java/org/apache/geode/internal/net/SSLSocketIntegrationTest.java, geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
I've modified the fix for GEODE-8144 to not set the SNI server name parameter
if endpoint verification is disabled.  The parameter is only needed if endpoint
verification is enabled.  Some performance tests that had endpoint identification
disabled were showing degraded perf.
=> GEODE-8144: setting SNI server name is not needed if endpoint verification is disabled

geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/SubscribeExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/server/ShutDownExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
The ShutdownExecutor now implements the shutdown command
instead of it being embedded in the ExecutionHandlerContext.
The SubscribeExecutor now takes care of changing its channel to a different thread group.
=> GEODE-8268: clean up ExecutionHandlerContext

geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/ClusterDistributionManagerDUnitTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java
Added timeout after which it will be periodically checked whether
distribution manager is disconnecting while waiting on the membership
view installation to avoid hanging
=> GEODE-7591: Fix for hang in ClusterDistributionManager

geode-redis/src/test/java/org/apache/geode/redis/internal/data/RedisHashTest.java, geode-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSetTest.java, geode-redis/src/test/java/org/apache/geode/redis/internal/data/RedisStringTest.java
Added unit tests for RedishHash, RedisSet, and RedisString.
Currently the tests cover serialization, delta, and equals.
=> GEODE-8264: add serialization tests for RedisData classes

geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/MembershipIntegrationTest.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java
In the case where a locator starts up and is unable to connect to any
other locators, it may decide to become the membership coordinator even
if locator-wait-time has not elapsed.
This change addresses this issue by requiring a locator to wait for
locator-wait-time before deciding to become the coordinator.
Co-authored-by: Aaron Lindsey <alindsey@vmware.com>
Co-Authored-By: Vincent Ford <vford@pivotal.io>
=> GEODE-8241: Locator observes locator-wait-time

geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/GfshExecution.java, geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/GfshScript.java
* Use GeodeAwaitility timeout instead of hardcoded timeouts.
* Prefer newer JDK APIs over Guava.
* Use linefeeds in fluent API calls.
* Minor formatting changes.
=> GEODE-8273: Cleanup GfshExecution and GfshScript

geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/GlobPatternNativeRedisAcceptanceTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/GlobPatternIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/KeysIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/GlobPattern.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/key/KeysExecutor.java
Redis has their own glob-style pattern (https://redis.io/commands/keys). Change our implementation to match that of Redis
=> GEODE-8288: Match Redis's glob-style pattern

geode-assembly/src/acceptanceTest/java/org/apache/geode/logging/LocatorWithCustomLogConfigAcceptanceTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/logging/ServerWithCustomLogConfigAcceptanceTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/commands/StartLocatorAcceptanceTest.java, geode-assembly/src/acceptanceTest/resources/org/apache/geode/logging/LocatorWithCustomLogConfigAcceptanceTestWithGeodePlugins.xml, geode-assembly/src/acceptanceTest/resources/org/apache/geode/logging/LocatorWithCustomLogConfigAcceptanceTestWithoutGeodePlugins.xml, geode-assembly/src/acceptanceTest/resources/org/apache/geode/logging/ServerWithCustomLogConfigAcceptanceTestWithGeodePlugins.xml, geode-assembly/src/acceptanceTest/resources/org/apache/geode/logging/ServerWithCustomLogConfigAcceptanceTestWithoutGeodePlugins.xml, geode-junit/src/main/java/org/apache/geode/test/assertj/internal/AbstractLogFileAssert.java
New tests to discover and verify that use of custom log configs works
when using GFSH to start Locator and Server.
=> GEODE-8250: Create new custom log config acceptance tests

extensions/geode-modules-test/src/main/java/org/apache/geode/modules/session/catalina/AbstractDeltaSessionIntegrationTest.java, extensions/geode-modules-test/src/main/java/org/apache/geode/modules/session/catalina/AbstractDeltaSessionManagerTest.java, extensions/geode-modules-test/src/main/java/org/apache/geode/modules/session/catalina/AbstractDeltaSessionTest.java, extensions/geode-modules-tomcat7/src/integrationTest/java/org/apache/geode/modules/session/catalina/DeltaSession7Test.java, extensions/geode-modules-tomcat7/src/test/java/org/apache/geode/modules/session/catalina/DeltaSession7Test.java, extensions/geode-modules-tomcat7/src/test/java/org/apache/geode/modules/session/catalina/Tomcat7DeltaSessionManagerTest.java, extensions/geode-modules-tomcat8/build.gradle, extensions/geode-modules-tomcat8/src/integrationTest/java/org/apache/geode/modules/session/catalina/DeltaSession8Test.java, extensions/geode-modules-tomcat8/src/test/java/org/apache/geode/modules/session/catalina/DeltaSession8Test.java, extensions/geode-modules-tomcat8/src/test/java/org/apache/geode/modules/session/catalina/DeltaSessionTest.java, extensions/geode-modules-tomcat8/src/test/java/org/apache/geode/modules/session/catalina/Tomcat8DeltaSessionManagerTest.java, extensions/geode-modules-tomcat9/src/integrationTest/java/org/apache/geode/modules/session/catalina/DeltaSession9Test.java, extensions/geode-modules-tomcat9/src/test/java/org/apache/geode/modules/session/catalina/DeltaSession9Test.java, extensions/geode-modules-tomcat9/src/test/java/org/apache/geode/modules/session/catalina/Tomcat9DeltaSessionManagerTest.java, extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/DeltaSession.java, extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/DeltaSessionManager.java, extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/DeltaSessionManagerConfiguration.java, extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/JvmRouteBinderValve.java, extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/SessionManager.java, extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/callback/SessionExpirationCacheListener.java, extensions/session-testing-war/src/main/java/org/apache/geode/modules/session/AccessAttributeValueListener.java, extensions/session-testing-war/src/main/webapp/WEB-INF/web.xml, geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/CargoTestBase.java, geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/LogChecker.java
When preferDeserializedForm is true we deserialize the previous attributes before update or remove.
Deprecates preferDeserializedForm since when false it's unclear when you will get serialized or unserialized forms of attributes.
=> GEODE-8217: Deserialize attribute before update and remove.

dev-tools/docker/docs/README.md
Make it clearer that neither a local Bookbinder nor Ruby interpreter is
needed to build our documentation book.
No tests added, since this is just a readme change.
=> GEODE-8304 - Better highlight steps for building documentation

geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/connection/PingNativeRedisAcceptanceTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/PingIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/connection/PingExecutor.java
Added ping integration tests.
Now if ping is given a parameter it will be returned instead of PONG.
=> GEODE-8309: fix ping to return its parameter

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscDUnitTest.java
The DistributedPingMessage is handled asynchronously: I have check that if I introduce a sleep `process()` method of `DistributedPingServer`, the test case fails because the `ClientHealthMonitor` has not received the ping.
I suspect that in the ocassions where the test failed was due to a race condition between the check of the `ClientHealthMonitor` content and the process of the message. So Im introducing a wait when checking the `ClientHealthMonitor` to avoid this.
=> GEODE-8176: Fix for flaky testPingWrongServer

geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/pubsub/SubscriptionsIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/mocks/DummySubscription.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/mocks/MockSubscriber.java, geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PublishExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PunsubscribeExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/SubscribeExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/UnsubscribeExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java, geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java, geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/AbstractSubscription.java, geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/ChannelSubscription.java, geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PatternSubscription.java, geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSub.java, geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSubImpl.java, geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/Subscription.java, geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/Subscriptions.java, geode-redis/src/test/java/org/apache/geode/redis/internal/pubsub/PubSubImplJUnitTest.java, geode-redis/src/test/java/org/apache/geode/redis/internal/pubsub/SubscriptionsJUnitTest.java
- Add ability to [P]UNSUBSCRIBE from multiple channels.
- Match Redis semantics when subscribing to empty channel name - (`""`)
- Interact with plain channel names as `byte[]`s instead of `String`s - (fixes issues on Windows when subscribing with arbitrary byte[] names).
=> GEODE-8312: Improve Redis pub/sub capabilities

geode-core/src/distributedTest/java/org/apache/geode/management/JMXMBeanReconnectDUnitTest.java
JMXMBeanReconnectDUnitTest has JMX Managers reconnecting so it will
very likely generate AlertingIOException during execution.
=> GEODE-8110: Ignore AlertingIOException in JMXMBeanReconnectDUnitTest

geode-docs/basic_config/data_regions/region_naming.html.md.erb
Fix how the back-quote is displayed in the compiled user guide.
=> GEODE-7956: Correct documentation of legal region names (format fix)

geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledComparison.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/CompiledComparisonTest.java
=> GEODE-8346: Add try/catch around Entry.getValue in CompiledComparison

ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/shared/jinja.variables.yml
Geode 1.12 release included geode-benchmarks from support/1.12, but the pipeline definition is still using benchmarks from develop, as is 1.13.  Fix to use matching branch names between geode and geode-examples.  Also rebalance max_in_flight based on how long each benchmark job takes.
=> GEODE-8347: use same benchmarks branch as geode branch

geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PutAllPRMessage.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/RemoveAllPRMessage.java, geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/PutAllPRMessageTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/RemoveAllPRMessageTest.java
Co-authored-by: Anil <agingade@pivotal.io>
=> GEODE-8334: PR.clear should sync with putAll or removeAll on rvvLock

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/fixed/FixedPartitioningWithTransactionDistributedTest.java
=> GEODE-8326: remove 5 minutes wait to get stack dump

ci/pipelines/mass-test-run/jinja.template.yml
=> GEODE-8355: add `public: true` to the test job in long-running-test

.gitignore, ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/images/jinja.template.yml, ci/pipelines/meta/deploy_meta.sh, ci/pipelines/meta/jinja.template.yml, ci/scripts/run_benchmarks.sh
* Add EC2 builder job to images.
* Benchmarks job uses branch-specific image.
* Change benchmarks source repository location to the deployed fork's repo instead
of forcing apache.
* download our own copy of fly to use when deploying pipelines via deploy_meta.sh.
=> GEODE-8348: Add benchmarks EC2 image builder job.

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/InternalDistributedMember.java, geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/GMSMemberDataVersionJUnitTest.java, geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/GMSMembershipJUnitTest.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/api/MemberData.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/api/MemberIdentifier.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMemberData.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMembership.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/MemberIdentifierImpl.java
[GEODE-8298](https://issues.apache.org/jira/browse/GEODE-8298)
These changes fix inconsistent version comparison in `GMSMembership.processView()`.
The goal of the comparison is to find the oldest Geode version and if that version is older than the local version, disable multicast. The code responsible for this was extracted from `processView` to a new method `containsOldVersionMember` to allow for better unit testing.
=> GEODE-8298: Member version comparison sense inconsistent when deciding on multicast

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionClearWithConcurrentOperationsDUnitTest.java, geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
Added distributed tests to verify that the clear operation on
Partitioned Regions works as expected when there are other
concurrent operations happening on the cache (puts, gets, members
added and members removed).
=> GEODE-7670: Add Tests for PR clear

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionClearWithRebalanceDUnitTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/ColocationHelper.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionClear.java
- Added DUnit tests to confirm that clear does not interfere with
rebalance or vice versa
- Fixed typo in PartitionedRegionClearWithExpirationDUnitTest
- Fixed typo in PartitionedRegion
=> GEODE-7680: PR.clear must be successful when interacting with rebalance

geode-redis/src/commonTest/java/org/apache/geode/redis/GeodeRedisServerRule.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/GeodeServerRunTest.java
No-op test to run Redis API for Geode for local development
=> GEODE-8375: No-op test to run Redis API for Geode for local development

geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubDUnitTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java, geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PublishExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/SubscribeExecutor.java, geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Command.java, geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java, geode-redis/src/main/java/org/apache/geode/redis/internal/netty/NettyRedisServer.java, geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/AbstractSubscription.java, geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSubImpl.java, geode-redis/src/test/java/org/apache/geode/redis/internal/pubsub/PubSubImplJUnitTest.java
PUBSUB hangs with concurrent publishers and subscribers on multiple
servers. Changed Publish executor to execute publish on background
thread (the DistributionManager's waiting pool is used). Removed separate separate subscriber group.  Added DUnit test to
recreate failure.
To preserve the order of incoming commands, even when some of them are running asynchronously in background threads, a command queue now exists. When an async commands comes in (currently only PUBLISH is async) then it goes in the queue and is started. Any other commands that come in while it is in progress are added to the a queue. Once the async command completes it also drains the command queue down to the next async command it finds in it.
Co-authored-by: Murtuza Boxwala <mboxwala@pivotal.io>
=> GEODE-8333: Fix PUBSUB hang

geode-core/src/integrationTest/java/org/apache/geode/internal/AvailablePortJUnitTest.java
An assertion in AvailablePortJUnitTest.testIsPortAvailable() assumes
that the InetAddress for the local host is not a loopback address.
Though this assumption holds in our CI containers, it fails on some
developer's Macs, and perhaps on other hosts.
This commit changes the test to skip that assertion if the local host
address is a loopback address.
=> GEODE-8391: Skip assertion if unsupported by host

geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SDiffIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SInterIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SUnionIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSet.java
=> GEODE-8387: fix SET*STORE commands handling of empty results

geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/Launcher.java
New (fixed) behavior:
gfsh --help
Apache Geode v1.14.0 Command Line Shell
Old (incorrect) behavior:
gfsh --help
Pivotal GemFire(R) v1.14.0 Command Line Shell
=> GEODE-8395: fix product name in gfsh help banner

ci/images/google-geode-builder/scripts/setup.sh, ci/pipelines/shared/jinja.variables.yml, ci/scripts/execute_redis_tests.sh, ci/scripts/execute_tests.sh, geode-redis/build.gradle
We would like to run Redis's tests against Redis API for Geode.  Tests will run a separate job in the PR and main pipelines.  It has been included in the 'tests' jinja variables.
Co-authored-by: Murtuza Boxwala <mboxwala@pivotal.io>
=> GEODE-8382: Run Redis tests against Redis API for Geode

geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/locator/MembershipLocatorImpl.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/locator/PrimaryHandler.java, geode-membership/src/test/java/org/apache/geode/distributed/internal/membership/gms/locator/PrimaryHandlerTest.java
The ticket had a suggested fix for the locator's hot loop and I've implemented that.  I modified PrimaryHandler to make the issue testable and added a couple of other tests for registered and fallback request handlers.
=> GEODE-6950: hot loop in PrimaryHandler.processRequest()

geode-core/src/distributedTest/java/org/apache/geode/cache30/ClientServerCacheOperationDUnitTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/Part.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/PartTest.java
This change rewinds the message part on command failure. Without this during retry on failure, the message (Part) is sent from the place where it was previously failed, instead of starting from the beginning, causing it to transmit partial data.  
- [NA] If …
=> GEODE-8394: Rewind the message Part on command failure

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommand.java, geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/MappingCommandUtils.java, geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/CreateMappingCommandTest.java, geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/MappingCommandUtilsTest.java
Fixed the determination of partitioned region in CreateMappingCommand#createAsyncQueue.
------
=> GEODE-8396: Fixing NullPointerException in create jdbc-mapping command

geode-core/src/integrationTest/java/org/apache/geode/internal/logging/MergeLogFilesIntegrationTest.java, geode-core/src/integrationTest/resources/org/apache/geode/internal/logging/MergeLogFilesIntegrationTest.txt
Fixing directory path formation problem for Windows.  I've tested these changes on a Mac and on a Windows machine.
=> GEODE-8413: CI failure: MergeLogFilesIntegrationTest.testDircountZero fails on Windows

geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/CrashAndNoRepeatDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HashesAndCrashesDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionDUnitTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
The fix for GEODE-8393 seems to have caused both GEODE-8417 and GEODE-8418.
This revert should fix those new issues.
This reverts commit 0a91484b05f1caffa8cc3a59cc7fc38abe4376ed.
=> GEODE-8417: Revert GEODE-8393

geode-book/master_middleman/source/subnavs/geode-subnav.erb, geode-docs/reference/topics/gemfire_properties.html.md.erb, geode-docs/tools_modules/book_intro.html.md.erb, geode-docs/tools_modules/redis_api_for_geode.html.md.erb
Documentation for Redis API for Geode that will currently be published for 1.13 are not accurate and need to be updated.
=> GEODE-8423: Updates Redis API for Geode docs 1.13

geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SDiffIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SInterIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SUnionIntegrationTest.java
Restore tests for nonexistent keys against a Set data type.
=> GEODE-8409: S*STORE need to handle target that is not a redis set

geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/TimeIntegrationTest.java
Fix flaky test, Redis "TIME" command microseconds value can be zero.
=> GEODE-8379: Allow microseconds value to be zero

geode-redis/README.md
Update geode-redis README with a short explanation of how to run a Geode server that accepts Redis commands.
=> GEODE-8428: Update geode-redis README 

geode-redis/src/acceptanceTest/java/session/NativeRedisSessionAcceptanceTest.java, geode-redis/src/acceptanceTest/java/session/NativeRedisSessionExpirationAcceptanceTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/CrashAndNoRepeatDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HashesAndCrashesDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/session/RedisSessionDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionDUnitTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionExpirationDUnitTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
The flaky test is being disabled by this PR and the jira ticket for it will remain open.
Instead of throwing a "memberDeparted" exception message the server will now
log a warning and then disconnect the client. Depending on the client it may then
initiate a reconnect and retry the operation.
=> GEODE-8427: fix flaky test and do not throw memberDeparted

geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
Redis API for Geode should properly handle DistributedSystemDisconnectedException and ForcedDisconnectException when member disconnects. Client should be closed and a null response should be returned.
=> GEODE-8459: Redis API for Geode handles errors when member disconnects

geode-core/src/main/java/org/apache/geode/internal/net/SSLUtil.java, geode-core/src/test/java/org/apache/geode/internal/net/SSLUtilTest.java
This disables the use of TLSv1.3 selection if "any" is specified as the
protocol and throws an exception if TLSv1.3 is requested in a JVM older
than Java 11.  Most Java 8 implementations do not support TLSv1.3 - this
is only an issue (presently) with Oracle's 1.8.0_261 and above.
=> GEODE-8463: server's log filled with SSLException: Tag mismatch!

geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java, geode-core/src/test/java/org/apache/geode/internal/cache/GemFireCacheImplTest.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMembership.java
Catch exceptions that occur during XML generation and disable auto
reconnect.
Ensure that the DisconnectThread is launched by placing it in a
"finally" block.
@kamilla1201 @Bill
=> GEODE-8467: server fails to notify of a ForcedDisconnect and fails to tear down the cache

geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/GfshExecution.java, geode-redis/build.gradle, geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/GeodeRedisServerStartUpAcceptanceTest.java, geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/key/ExpireAtNativeRedisAcceptanceTest.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/GeodeRedisServerStartupDUnitTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/netty/NettyRedisServer.java
=> GEODE-8462: Make geode server startup fail if geode redis server has a port conflict

geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/CrashAndNoRepeatDUnitTest.java, geode-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt, geode-redis/src/main/java/org/apache/geode/redis/internal/data/AbstractRedisData.java, geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisString.java, geode-redis/src/main/java/org/apache/geode/redis/internal/delta/AppendDeltaInfo.java
- There seems to be an intermittent problem when Deltas arrive and a GII
is in progress. This fix introduces a sequence number that is used for
APPEND operations only. Since APPEND is NOT idempotent, duplicate
deltas can be a problem and will cause data issues if applied when they
should not be.
Co-Authored-By: Darrel Schneider <darrel@vmware.com>
=> GEODE-8393: Add sequence number to RedisString to support delta and APPEND

geode-core/src/main/java/org/apache/geode/internal/cache/TXState.java, geode-core/src/test/java/org/apache/geode/internal/cache/TXStateTest.java
This is used to handle a retry of transactional put.
=> GEODE-8486: record TransactionDataRebalancedException if tx put failed

geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/GMSMembershipJUnitTest.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMembership.java
ReplyProcessor21 will not stop waiting for responses to a message during a Forced Disconnect unless ClusterDistributionManager is informed of the disconnect.  It sets a rootCause in its CancelCriterion that is polled by ReplyProcessor21's StoppableCountDownLatch.
This commit ensures that ClusterDistributionManager is notified of the disconnect so that it can perform this action.
This is a follow-up PR to GEODE-8467, which ensures that a DisconnectThread is launched to execute the GMSMembership.uncleanShutdown() method.
@kamilla1201 
submit an …
=> GEODE-8473: Hang in ReplyProcessor21 when forced-disconnect does not establish a cancellation cause

geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/SubscriptionsIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/pubsub/SubscriptionsIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java, geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Client.java, geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/AbstractSubscription.java, geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSubImpl.java, geode-redis/src/test/java/org/apache/geode/redis/internal/pubsub/SubscriptionsJUnitTest.java
Subscription structures leak if clients disconnect without unsubscribing. Normally subscriptions should be cleaned up when a PUBLISH is attempted but fails. We should try and detect clients disconnecting and remove the necessary subscription structures.
This code will properly shutdown a subscription when the connection is closed.
=> GEODE-8499: Redis subscriptions leak if they are not explicitly unsubscribed

geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubDUnitTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
Changes type of executor service we used so that it does not log a stuck threads warning when Redis clients are idle
=> GEODE-8493: Redis idle clients can cause server stuck thread warning

geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/QuitIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
Added tests, and now clear command queue when channelInactive() is called.
=> GEODE-8500: Tests for Redis QUIT command

geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/GeodeRedisServerStartUpAcceptanceTest.java
GeodeRedisServerStartUpAcceptanceTest tests were using GFSH to start up servers. This meant the Geode server would listen on the default port (40404), and if any other process had that port bound, startup would fail. The GFSH command has been updated to specify a random Geode server port.
=> Redis StartUp tests use ephemeral port for Geode server

geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/pubsub/LettucePubSubNativeRedisAcceptanceTest.java, geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/pubsub/SubscriptionsNativeRedisAcceptanceTest.java, geode-redis/src/commonTest/java/org/apache/geode/redis/mocks/MockSubscriber.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/LettucePubSubIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/SubscriptionsIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java, geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
The commands that are allowed in the context of a subscribed client are SUBSCRIBE, PSUBSCRIBE, UNSUBSCRIBE, PUNSUBSCRIBE, PING and QUIT.
Tests were added for these commands.  We also discovered that we were not throwing the proper error if we tried to do commands that were not supported while subscribed.  We corrected this issue.  The test for PING while subscribed was ignored because it is a different issue (https://issues.apache.org/jira/browse/GEODE-8515).
=> GEODE-8516: Add Redis tests for multiple subscriptions for the same client

geode-core/src/main/java/org/apache/geode/internal/net/SSLUtil.java, geode-core/src/test/java/org/apache/geode/internal/net/SSLUtilTest.java
This reverts commit 20a35ece18054e96eccda70c65a015f4af26b4c7.
Changes for GEODE-8506 have fixed the problems with using TLSv1.3 in
Java 8 so this commit needs to be reverted.
=> Revert "GEODE-8463: server's log filled with SSLException: Tag mismatch! (#5482)"

dev-tools/dependencies/bump.sh, geode-junit/src/test/java/org/apache/geode/test/junit/rules/ExpectedTimeoutRuleTest.java
newer dependency version uses platform-specific line separators, test did not
=> GEODE-8469: fix windows test failure

geode-redis/src/commonTest/java/org/apache/geode/redis/mocks/MockSubscriber.java, geode-redis/src/distributedTest/java/org/apache/geode/redis/TempTestSuite.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/SubscriptionsIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/connection/PingExecutor.java
From PING documentation (https://redis.io/commands/ping):
If the client is subscribed to a channel or a pattern, it will instead return a multi-bulk with a "pong" in the first position and an empty bulk in the second position, unless an argument is provided in which case it returns a copy of the argument.
=> GEODE-8515: Redis PING should respond appropriately when called from within a SUBSCRIBE/PSUBSCRIBE

geode-redis/src/commonTest/java/org/apache/geode/redis/mocks/MockSubscriber.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/LettucePubSubIntegrationTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/AbstractSubscription.java, geode-redis/src/test/java/org/apache/geode/redis/internal/pubsub/PubSubImplJUnitTest.java
Adds punsubscriptionlatch countdown
WIP pipeline experiment without syncUninterupptibly
GEODE-8498 keep published messages to same client in order
=> GEODE-8498: make AbstractSubscription write to channel synchronously

geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java
This log message happens during the course of normal startup of multiple
locators. We should not be logging a full stack trace during normal startup.
=> GEODE-8522: Switching a exception log back to debug

boms/geode-all-bom/src/test/resources/expected-pom.xml, buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy, dev-tools/dependencies/README.md, dev-tools/dependencies/bump.sh
#5537 passed in PR checked, which run only JDK11, but under JDK8 a bug in archunit is encountered which results in OOM:
https://concourse.apachegeode-ci.info/teams/main/pipelines/apache-develop-main/jobs/IntegrationTestOpenJDK8/builds/462
> java.lang.OutOfMemoryError: Java heap space
> 	at java.util.Formatter.parse(Formatter.java:2560)
> 	at java.util.Formatter.format(Formatter.java:2501)
> 	at java.util.Formatter.format(Formatter.java:2455)
> 	at java.lang.String.format(String.java:2940)
> 	at com.tngtech.archunit.core.domain.SourceCodeLocation.formatLocation(SourceCodeLocation.java:60)
> 	at com.tngtech.archunit.core.domain.SourceCodeLocation.<init>(SourceCodeLocation.java:78)
> 	at com.tngtech.archunit.core.domain.SourceCodeLocation.of(SourceCodeLocation.java:52)
> 	...
This archunit …
=> GEODE-8496: un-upgrade archunit to avoid OOM on JDK8

geode-dunit/src/main/java/org/apache/geode/test/dunit/VM.java
Fixing an issue where the VM class will not properly start a versioned server.
=> GEODE-8544: Making VM class start versioned VM

geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java
This log message happens during the course of normal startup of multiple
locators. We should not be logging a full stack trace during normal startup.
(cherry picked from commit 3df057ce1ad9913ee7991377d02e86faa371fef0)
=> GEODE-8522: Switching exception log back to debug (merge to 1.13)

ci/pipelines/pull-request/jinja.template.yml
In a [recent discussion on the dev list](https://lists.apache.org/x/thread.html/r4d0ad5898654525e59a5367e3ad101a14307118932a6d61fbf3d72cf@%3Cdev.geode.apache.org%3E), some felt it was unnecessary to add Windows PR checks to *every* PR.  However at least 8 times this year alone, this has led to changes being committed to develop that broke on Windows, stalling the pipeline.
This poses a problem, because even once you know your commit broke Windows, developers often have no way to test a fix.
A comment from Kirk asked if we could find a way to request extra (Windows) PR checks only for certain PRs, e.g. opt-in once you have found yourself in the position of having to fix a Windows failure.
This enables the PR pipeline to do just that.  Ordinary PRs will continue to behave exactly as before. …
=> GEODE-8561: Ability to request Windows PR checks for an individual PR

ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/mass-test-run/jinja.template.yml, ci/pipelines/pull-request/jinja.template.yml
in particular, 5 minutes for rsync_down is not enough for windows jobs
=> GEODE-8561: update pr timeouts, retries, and variables to match develop

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/fixed/FixedPartitioningDUnitTest.java
Update FixedPartitioningDUnitTest after two PRs collided.
=> GEODE-8252: Fix FixedPartitioningDUnitTest

geode-junit/build.gradle, geode-junit/src/main/java/org/apache/geode/test/junit/rules/CloseableReference.java, geode-junit/src/test/java/org/apache/geode/test/junit/rules/CloseableReferenceTest.java
Create CloseableReference JUnit Rule for unit and integration tests.
=> GEODE-8550: Create CloseableReference

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/SimpleDiskRegionJUnitTest.java, geode-junit/src/main/java/org/apache/geode/internal/cache/DiskRegionTestingBase.java
Co-authored-by: Ray Ingles <ringles@pivotal.io>
Updating Junit to 4.13, one test failed on Windows due to failure to delete some temporary test files.
https://concourse.apachegeode-ci.info/teams/main/pipelines/apache-develop-main/jobs/WindowsCoreIntegrationTestOpenJDK8/builds/455
```
org.apache.geode.internal.cache.SimpleDiskRegionJUnitTest > testBasicClose FAILED
java.lang.AssertionError:  Exception in createOverflowOnly due to java.lang.IllegalStateException: The region "/testRegion" has been persisted to disk so it can not be recreated on the same disk store without persistence. Either destroy the persistent region, recreate it as overflow and persistent, or create the overflow only region on a different disk store.
at org.junit.Assert.fail(Assert.java:89)
at …
```
=> GEODE-8555: SimpleDiskRegionJunitTest fails on Windows

geode-core/src/jca/java/org/apache/geode/internal/ra/spi/JCAManagedConnection.java, geode-core/src/main/java/org/apache/geode/internal/CopyOnWriteHashSet.java, geode-core/src/test/java/org/apache/geode/internal/CopyOnWriteHashSetJUnitTest.java
Updated CopyOnWriteHashSet's iterator implementation to support iterator.remove().
Updated JCAManagedConnection to not use iterator.remove(). It will now
collect all items to remove and then use the CopyOnWriteHashSet removeAll
functionality to avoid unnecessary intermediary collection creations.
=> GEODE-8564: Updated CopyOnWriteHashSet's iterator implementation to support iterator.remove()

geode-docs/managing/disk_storage/compacting_disk_stores.html.md.erb
One more garbage vs. non-garbage clarification, and added a link to making current oplog eligible for compaction by forcing oplog rotation
=> GEODE-8533: Docs - compaction-threshold description refinements

geode-core/src/distributedTest/java/org/apache/geode/cache30/CacheXml66DUnitTest.java
The testClientSubscriptionQueueUsingDefaultDS() test in
CacheXml66DUnitTest and its subclasses assumed that the system’s default
disk directory is the JVM’s current working directory.
This change removes that assumption by making the tests honor the
defaultDiskDirs system property.
=> GEODE-8495: Make tests honor default disk dir property

geode-lucene/src/distributedTest/java/org/apache/geode/cache/lucene/internal/IndexRepositoryFactoryDistributedTest.java, geode-lucene/src/integrationTest/java/org/apache/geode/cache/lucene/internal/IndexRepositoryFactoryIntegrationTest.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/IndexRepositoryFactory.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/IndexRepositoryFactoryTest.java
=> GEODE-8536: Allow limited retries when creating Lucene IndexWriter

geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubNativeRedisAcceptanceTest.java, geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractPubSubIntegrationTest.java
- Apparently we need more time between retrying for a new connection on
docker.
=> GEODE-8577: Fix flaky PubSubNativeRedisAcceptanceTest

geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/util/LogExporterFileIntegrationTest.java, geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/util/LogExporterIntegrationTest.java, geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/util/LogExporter.java
Changed LogExporter to refrain from attempting to read directories, even
when a directory's path matches the exporter's file selector predicates.
Changed LogExporterIntegrationTest to configure the server to write
files in a unique subdirectory of the current working directory. Some
tests were configuring the server to use a temporary folder that could
be reused by other tests.
=> GEODE-8572: Make LogExporter not read dirs

geode-core/src/main/java/org/apache/geode/internal/net/BufferPool.java, geode-core/src/main/java/org/apache/geode/internal/net/NioFilter.java, geode-core/src/main/java/org/apache/geode/internal/net/NioSslEngine.java, geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java, geode-core/src/main/java/org/apache/geode/internal/tcp/MsgReader.java, geode-core/src/test/java/org/apache/geode/internal/net/NioSslEngineTest.java
Add appropriate synchronization when using ioFilter's buffers.
Originally NioFilters were accessed only by a single thread at a time.  Eventually this changed, with Connection.asyncClose now invoking the close() method on the filter.  In the NioSslEngine this modifies the encrypted buffer, and that conflicted with the use of the buffer in Connection.writeFully().
Rather than just add additional synchronization to Connection.writeFully() I've examined all uses of NioSslEngine's buffers and have added synchronization around all of these uses. …
=> GEODE-8584: Message transmission fails with IllegalStateException in socket i/o code

geode-assembly/build.gradle, geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/shell/StatusLocatorExitCodeAcceptanceTest.java, geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/shell/StatusServerExitCodeAcceptanceTest.java, geode-core/src/integrationTest/java/org/apache/geode/codeAnalysis/RestrictUseOfInetAddressJUnitTest.java, geode-junit/build.gradle, geode-junit/src/main/java/org/apache/geode/internal/AvailablePortHelper.java, geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/MembershipIntegrationTest.java, geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java, geode-membership/src/main/java/org/apache/geode/internal/AvailablePort.java, geode-memcached/build.gradle, geode-pulse/geode-pulse-test/build.gradle
If we can contact all other locators, we should stop waiting for
locator-wait-time to elapse.
=> GEODE-8579: Stop waiting locator-wait-time if all locators are available

geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/AbstractKeysIntegrationTest.java, geode-redis/src/main/java/org/apache/geode/redis/internal/executor/GlobPattern.java
Glob pattern should match carriage return, line feed, and tab
=> GEODE-8587: Redis glob pattern does not match carriage return, line feed, and tab

geode-core/src/main/java/org/apache/geode/internal/cache/EntryEventImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/FilterProfile.java, geode-core/src/main/java/org/apache/geode/internal/cache/FilterRoutingInfo.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalCacheEvent.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXCommitMessage.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXEntryState.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXState.java, geode-core/src/main/java/org/apache/geode/internal/cache/TxCallbackEventFactoryImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientRegistrationEventQueueManager.java, geode-core/src/main/java/org/apache/geode/internal/cache/tx/DistTxEntryEvent.java, geode-core/src/test/java/org/apache/geode/internal/cache/EntryEventImplTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/FilterProfileTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/TXCommitMessageTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/TXStateTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifierTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientRegistrationEventQueueManagerTest.java, geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/RemoteCQTransactionDUnitTest.java
* Compute interest routing info after transactional event has been
applied to cache. This will make sure an interested client will
either get the event through region snapshot taken or through
HARegionQueue.
* Add test coverage for CQ with transactional destroy event to make
sure CQ routing is computed correctly.
* Remove sleep in exiting test code.
=> GEODE-8559: Compute interest routing info after transaction committed.

geode-core/src/distributedTest/java/org/apache/geode/cache/ReplicateRegionNetsearchDistributedTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/fixed/FixedPartitioningDUnitTest.java, geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/examples/DistributedReferenceCacheExampleTest.java, geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/examples/DistributedReferenceLocatorLauncherExampleTest.java, geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/examples/DistributedReferenceServerLauncherExampleTest.java, geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/examples/DistributedReferenceSystemExampleTest.java, geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedReferenceTest.java, geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedReference.java
This prevents line-wrapping in tests using DistributedReference
improving readability.
=> GEODE-8606: Rename DistributedReference
