- geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/SaddDUnitTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/SremDUnitTest.java
SREM (https://redis.io/commands/srem) removes members from a set.  We created distributed tests to ensure SREM can happen concurrently on multiple servers.
> GEODE-8034: Create distributed tests for SREM command

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- geode-module/build.gradle
- geode-module/src/main/java/org/apache/geode/module/ModuleDescriptor.java
- geode-module/src/main/java/org/apache/geode/module/ModuleService.java
- geode-module/src/test/resources/expected-pom.xml
- settings.gradle
> GEODE-8033 - Create geode-module sub-project and ModuleService interface.

- geode-core/src/main/java/org/apache/geode/cache/configuration/CacheConfig.java
- geode-core/src/test/java/org/apache/geode/cache/configuration/CacheConfigTest.java
- geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreateIndexCommandDUnitTest.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/CreateIndexCommand.java
- geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/commands/CreateIndexCommandTest.java
- geode-wan/src/distributedTest/java/org/apache/geode/management/internal/configuration/ClusterConfigurationIndexWithFromClauseDUnitTest.java
> GEODE-8055: create index command should work on sub regions

- geode-core/src/integrationTest/java/org/apache/geode/net/SSLSocketParameterExtensionIntegrationTest.java
- geode-core/src/main/java/org/apache/geode/internal/admin/SSLConfig.java
- geode-core/src/main/java/org/apache/geode/net/SSLParameterExtension.java
> GEODE-7414_2: modify init() method argument

- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
- geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionTest.java
> GEODE-8073: Fix NPE after FetchKeysMessage failed.

- dev-tools/release/README.md
Reformat geode/dev-tools/release/README.md to improve readability
> Reformat geode/dev-tools/release/README.md to improve readability

- geode-common-services/src/main/java/org/apache/geode/services/bootstrapping/BootstrappingService.java
> GEODE-8037 - Create BootstrappingService interface.

- geode-common-services/build.gradle
- geode-common-services/src/main/java/org/apache/geode/services/management/ManagementService.java
- geode-common-services/src/test/resources/expected-pom.xml
> GEODE-8041 - Create ManagementService interface.

- geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/SaddDUnitTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/SremDUnitTest.java
Other concurrent DUnit and integration tests are utilizing the ConcurrentLoopingThreads class to generate and run concurrent threads.  We wanted to be consistent across DUnit and integration tests.
> GEODE-8054: Refactor Sadd and Srem DUnit tests to use ConcurrentLoopingThreads class

- build.gradle
- ci/pipelines/shared/jinja.variables.yml
- ci/scripts/archive_results.sh
- geode-assembly/build.gradle
- geode-web-api/build.gradle
- geode-web-management/build.gradle
- geode-web/build.gradle
- gradle/spotless.gradle
* Add API check gradle task.
* Add CI job that calls API check gradle task.
* Fix spotless rules so it doesn't mistakenly mess up our gradle.
> [GEODE-8083] Add API Checking to Geode.

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/PingOpDistributedTest.java
- geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/LocatorLoadSnapshotIntegrationTest.java
- geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
- geode-core/src/main/java/org/apache/geode/cache/client/internal/CacheServerLoadMessage.java
- geode-core/src/main/java/org/apache/geode/cache/client/internal/LiveServerPinger.java
- geode-core/src/main/java/org/apache/geode/cache/client/internal/PingOp.java
- geode-core/src/main/java/org/apache/geode/cache/client/internal/ServerProxy.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/LocatorLoadSnapshot.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/ServerLocationAndMemberId.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/ServerLocator.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/membership/InternalDistributedMember.java
- geode-core/src/main/java/org/apache/geode/internal/DSFIDFactory.java
- geode-core/src/main/java/org/apache/geode/internal/cache/DistributedPingMessage.java
- geode-core/src/main/java/org/apache/geode/internal/cache/GridAdvisor.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Ping.java
- geode-core/src/test/java/org/apache/geode/distributed/internal/LocatorLoadSnapshotJUnitTest.java
- geode-core/src/test/java/org/apache/geode/distributed/internal/ServerLocationAndMemberIdTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/DistributedPingMessageTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/PingTest.java
- geode-dunit/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscDUnitTestBase.java
- geode-serialization/src/main/java/org/apache/geode/internal/serialization/DataSerializableFixedID.java
This PR reverts the revert of GEODE-7565 and introduces a fix for the problem identified
> GEODE-8004: Fix for regression introduced by GEODE-7565

- geode-redis/src/commonTest/java/org/apache/geode/redis/ConcurrentLoopingThreads.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/ExpireDUnitTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/StringsIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ExpireIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisService.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/TTLExecutor.java
> GEODE-8058: Create Dunit tests for EXPIRE, PEXPIRE, EXPIREAT, and PEXPIREAT

- geode-core/src/main/java/org/apache/geode/cache/client/internal/SingleHopClientExecutor.java
- geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/PutAllClientServerDistributedTest.java
Fixed issues causing testEventIdOutOfOrderInPartitionRegionSingleHop to fail
> Geode 7812: Changes to PutAllClientServerDistributionTest

- geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedAckRegionCCEDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/cache30/PutAllMultiVmDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/cache30/RegionReliabilityTestCase.java
- geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegionDataView.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tx/RemotePutAllMessage.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tx/RemoteRemoveAllMessage.java
> GEODE-7702: bulkOp from accessor or NORMAL should sync with clear

- build.gradle
- buildSrc/src/main/groovy/org/apache/geode/gradle/japicmp/AllowMajorBreakingChanges.groovy
- buildSrc/src/main/groovy/org/apache/geode/gradle/japicmp/ParentIsExperimental.groovy
- geode-assembly/build.gradle
- geode-core/src/integrationTest/java/org/apache/geode/net/SSLSocketParameterExtensionIntegrationTest.java
- geode-core/src/main/java/org/apache/geode/internal/admin/SSLConfig.java
- geode-core/src/main/java/org/apache/geode/net/SSLParameterExtension.java
- gradle/japicmp.gradle
> GEODE-8087: Fix Geode API compliance

- ci/pipelines/geode-build/jinja.template.yml
fixes a few typos in the original PR for GEODE-8016
> GEODE-8016: publish with non-zero-padded build ids instead of SNAPSHOT

- geode-redis/src/main/java/org/apache/geode/redis/GeodeRedisServer.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/serverinitializer/NamedThreadFactory.java
> GEODE-8082: Refactor GeodeRedisServer

- geode-assembly/src/integrationTest/resources/assembly_content.txt
- geode-core/src/integrationTest/java/org/apache/geode/cache/client/ClientCacheFactoryJUnitTest.java
- geode-core/src/integrationTest/resources/org/apache/geode/cache/client/ClientCacheFactoryJUnitTest_single_pool.xml
- geode-core/src/main/java/org/apache/geode/cache/client/proxy/ProxySocketFactories.java
- geode-core/src/main/java/org/apache/geode/cache/client/proxy/SniProxySocketFactory.java
- geode-docs/reference/topics/client-cache.html.md.erb
- geode-docs/topologies_and_comm/cs_configuration/setting_up_a_client_server_system.html.md.erb
> GEODE-8103: Renames SniSocketFactory to SniProxySocketFactory

- geode-management/src/test/java/org/apache/geode/management/internal/ClientClusterManagementServiceTest.java
> GEODE-8097: expects at least one callback instead of exactly one.

- ci/resource-types/gce-instances-resource/check
> GEODE-8107: Sort GCE instances by creationTimestamp for concourse

- geode-core/src/main/java/org/apache/geode/distributed/internal/InternalConfigurationPersistenceService.java
> GEODE-8091: fix AuthenticationRequiredException when starting a locator

- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HExistsExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HGetExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HKeysExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HLenExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HMGetExecutor.java
> GEODE-8113: getMap never returns null

- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/CommandFunction.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/SingleResultRedisFunction.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/RedisHashCommandsFunctionExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/RedisSet.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/RedisSetCommandsFunctionExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SMoveExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SingleResultCollector.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/StripedExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SynchronizedStripedExecutor.java
- geode-redis/src/main/resources/org/apache/geode/redis/internal/sanctioned-geode-redis-serializables.txt
- geode-redis/src/test/resources/expected-pom.xml
> GEODE-8098: Refactor RedisSetCommandsFunctionExecutor

- build.gradle
- buildSrc/src/main/groovy/org/apache/geode/gradle/japicmp/AllowMajorBreakingChanges.groovy
- buildSrc/src/main/groovy/org/apache/geode/gradle/japicmp/ParentIsExperimental.groovy
- ci/pipelines/shared/jinja.variables.yml
- ci/scripts/archive_results.sh
- geode-assembly/build.gradle
- geode-web-api/build.gradle
- geode-web-management/build.gradle
- geode-web/build.gradle
- gradle/japicmp.gradle
- gradle/spotless.gradle
* Add API check gradle task.
* Add CI job that calls API check gradle task.
* Fix spotless rules so it doesn't mistakenly mess up our gradle.
* Allow changes if a class or superclass is marked @Experimental
> GEODE-8083: Add API Checking to Geode. (#5066)

- geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
> GEODE-8124: Fix the error logging to display stacktrace

- geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java
- geode-redis/build.gradle
- geode-redis/src/commonTest/java/org/apache/geode/redis/GeodeRedisServerRule.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/GeodeRedisServerStartupDUnitTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/ConcurrentStartIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/GeoIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/HashesIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/ListsIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/PubSubIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/RedisLockServiceIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/RedisServerIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/RenameIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/SortedSetsIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/StringsIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ExistsIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ExpireAtIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ExpireIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/general/PersistIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/general/PexpireIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/sets/SDiffIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/sets/SInterIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/sets/SMoveIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/sets/SPopIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/sets/SRemIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/sets/SUnionIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/sets/SetsIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisService.java
> GEODE-8123: Allow Redis to start on a random port

- geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
- geode-core/src/main/java/org/apache/geode/management/internal/functions/CacheRealizationFunction.java
- geode-core/src/test/java/org/apache/geode/management/internal/functions/CacheRealizationFunctionTest.java
- geode-web-management/src/distributedTest/java/org/apache/geode/management/client/GetStartingMemberTest.java
- geode-web-management/src/distributedTest/java/org/apache/geode/management/client/MemberManagementServiceRestDUnitTest.java
* For get operation, if cache is not ready, just don't report any runtime information
* We would still log errors in case the stack trace is useful.
> GEODE-8078: log and report error at the correct place.

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- geode-redis/build.gradle
- geode-redis/src/distributedTest/java/org/apache/geode/redis/session/RedisSessionDistDUnitTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionDUnitTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionExpirationDUnitTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/session/springRedisTestApplication/RedisSpringTestApplication.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/session/springRedisTestApplication/SessionController.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/session/springRedisTestApplication/config/DUnitSocketAddressResolver.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/session/springRedisTestApplication/config/SessionListener.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/session/springRedisTestApplication/config/WebMvcConfig.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/Command.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/ExecutionHandlerContext.java
Co-authored-by: Murtuza Boxwala <mboxwala@vmware.com>
Co-authored-by: Raymond Ingles <ringles@vmware.com>
Co-authored-by: Jens Deppe <jdeppe@vmware.com>
> GEODE-8094: Create HA test to ensure Spring Boot sessions expire correctly

- geode-core/src/integrationTest/java/org/apache/geode/internal/ClassPathLoaderJUnitTest.java
* Same JAR names among tests in the same folder may be deleted by clean up from previously run tests.
> GEODE-8096: Providing unique names for the JARs in the tests

- geode-docs/configuring/running/cluster-management-service.html.md.erb
> GEODE-8100: update cluster-management-service documentation

- geode-docs/configuring/running/cluster-management-service.html.md.erb
A few edits for style and clarity:
- Changed future tense to present, here and there. 
- Clarified the meaning of 'default' in a few places. 
- Shortened an example line to better fit page width
@jinmeiliao Please verify that I did not introduce technical errors. Thank you.
> GEODE-8100: Update cluster management service docs - style edit

- geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java
- geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsDUnitTest.java
- geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/AlterDiskStoreCommandIntegrationTest.java
- geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/DescribeDiskStoreCommandIntegrationTest.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/AlterOfflineDiskStoreCommand.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/CompactOfflineDiskStoreCommand.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeOfflineDiskStoreCommand.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsUtils.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/UpgradeOfflineDiskStoreCommand.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/ValidateDiskStoreCommand.java
> GEODE-8119:closing threads when offline disk store is executed

- geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
- geode-docs/reference/topics/gemfire_properties.html.md.erb
- geode-docs/tools_modules/redis_api_for_geode.html.md.erb
redis-password, redis-bind-address, and redis-port need to be added to this page
> GEODE-8145: Add Redis configuration properties to gemfire_properties.html

- geode-assembly/src/integrationTest/resources/assembly_content.txt
- geode-common-services/src/main/java/org/apache/geode/services/module/ModuleService.java
- geode-modules/build.gradle
- geode-modules/src/main/java/org/apache/geode/services/module/impl/GeodeModuleLoader.java
- geode-modules/src/main/java/org/apache/geode/services/module/impl/JBossModuleServiceImpl.java
- geode-modules/src/test/java/org/apache/geode/InvalidService.java
- geode-modules/src/test/java/org/apache/geode/TestService.java
- geode-modules/src/test/java/org/apache/geode/services/module/impl/JBossModuleServiceImplTest.java
- geode-modules/src/testModules/module1/resources/META-INF/services/org.apache.geode.TestService
- geode-modules/src/testModules/module2/java/org/apache/geode/Module2.java
- geode-modules/src/testModules/module2/resources/META-INF/services/org.apache.geode.TestService
> GEODE-8137 - Implement loadService.

- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/CheckPrimaryBucketFunction.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/EnsurePrimaryStaysPut.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/EnsurePrimaryStaysPutDUnitTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/RedisDistDUnitTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/SingleResultRedisFunction.java
> GEODE-8127: ensure that function executes on primary 

- geode-common-services/src/main/java/org/apache/geode/services/module/ModuleService.java
- geode-modules/build.gradle
- geode-modules/src/main/java/org/apache/geode/services/module/impl/GeodeModuleLoader.java
- geode-modules/src/main/java/org/apache/geode/services/module/impl/JBossModuleServiceImpl.java
- geode-modules/src/test/java/org/apache/geode/services/module/impl/JBossModuleServiceImplTest.java
- geode-modules/src/testModules/module3/java/org/apache/geode/Module3.java
- geode-modules/src/testModules/module3/resources/META-INF/services/org.apache.geode.TestService
> GEODE-8148 - Implement unloadModule.

- geode-redis/src/integrationTest/java/org/apache/geode/redis/CommandPipeliningIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/Command.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/ExecutionHandlerContext.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PublishExecutor.java
- geode-redis/src/test/java/org/apache/geode/redis/internal/ExecutionHandlerContextJUnitTest.java
> GEODE-8168: Redis pipelined command responses can be corrupted

- geode-redis/src/integrationTest/java/org/apache/geode/redis/HashesIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/RedisResponse.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/AbstractScanExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HDelExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HExistsExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HGetAllExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HGetExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HIncrByExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HIncrByFloatExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HKeysExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HLenExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HMGetExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HMSetExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HScanExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HSetExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HValsExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SIsMemberExecutor.java
- Convert hash tests to use assertj
> GEODE-8151: Convert hash commands to return RedisResponse

- geode-management/src/test/script/update-management-wiki.sh
add new wiki page id for 1.14 to generator script, and update to support -build.n convention as well as -SNAPSHOT
> GEODE-8180: add 1.14 to management wiki

- geode-common/src/main/java/org/apache/geode/util/internal/UncheckedUtils.java
- geode-common/src/test/java/org/apache/geode/util/internal/UncheckedUtilsTest.java
- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionSingleHopDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/DistributedRegionFunctionExecutionDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/fixed/FixedPartitioningWithColocationAndPersistenceDUnitTest.java
- geode-core/src/integrationTest/java/org/apache/geode/internal/cache/execute/FunctionExecutionOnLonerRegressionTest.java
- geode-core/src/main/java/org/apache/geode/cache/client/internal/ClientMetadataService.java
- geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
- geode-core/src/main/java/org/apache/geode/internal/cache/InternalCacheForClientAccess.java
- geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/execute/util/TypedFunctionService.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxyFactory.java
- geode-core/src/test/java/org/apache/geode/alerting/internal/ClusterAlertMessagingTest.java
- geode-core/src/test/java/org/apache/geode/internal/tcp/TCPConduitTest.java
Create UncheckedUtilsTest to unit test UncheckedUtils.
Extract FunctionExecution methods to new TypedFunctionService in
geode-core.
> GEODE-8136: Move UncheckedUtils to geode-common

- geode-core/src/jca/java/org/apache/geode/internal/ra/spi/JCAManagedConnection.java
> GEODE-8174: Fix ConcurrentModificationException when using JTA transaction

- geode-core/src/jca/java/org/apache/geode/internal/ra/spi/JCAManagedConnection.java
(cherry picked from commit 93ef47c8c4d8712f60c2961fce1b28457fe447cc)
> 1.13 GEODE-8174: Fix ConcurrentModificationException when using JTA transaction.

- geode-core/src/main/java/org/apache/geode/cache/Region.java
- geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/PutAllClientServerDistributedTest.java
> GEODE-8171: javadoc for putAll need to have accurate exception

- build.gradle
- buildSrc/src/main/groovy/org/apache/geode/gradle/japicmp/AllowMajorBreakingChanges.groovy
- buildSrc/src/main/groovy/org/apache/geode/gradle/japicmp/ParentIsExperimental.groovy
- ci/pipelines/shared/jinja.variables.yml
- ci/scripts/archive_results.sh
- geode-assembly/build.gradle
- geode-web-api/build.gradle
- geode-web-management/build.gradle
- geode-web/build.gradle
- gradle/japicmp.gradle
- gradle/spotless.gradle
* Add API check gradle task.
* Add CI job that calls API check gradle task.
* Fix spotless rules so it doesn't mistakenly mess up our gradle.
* Allow changes if a class or superclass is marked @Experimental
(cherry picked from commit 9f0d4c9f91fb89821227e7d94d02d75d0ccbf0a9)
> GEODE-8083: Add API Checking to Geode. (#5066) (#5103)

- geode-core/src/jca/java/org/apache/geode/internal/ra/spi/JCAManagedConnection.java
…ction.
(cherry picked from commit 93ef47c8c4d8712f60c2961fce1b28457fe447cc)
> 1.12 - GEODE-8174: Fix ConcurrentModificationException when using JTA transaction.

- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/CheckPrimaryBucketFunction.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/EnsurePrimaryStaysPutDUnitTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/RedisDistDUnitTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/SingleResultRedisFunction.java
flaky test ignored
This reverts commit f243c4d99e1a223af0a3134d6a423b972195c507.
> GEODE-8127: Reintroduces changes that account for primary bucket changing

- geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ShutdownIntegrationTest.java
> GEODE-8211: fix flaky ShutdownIntegrationTest

- geode-redis/src/main/java/org/apache/geode/redis/internal/GlobPattern.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/PatternSubscription.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/PubSub.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/PubSubImpl.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/AbstractScanExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/KeysExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PsubscribeExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PunsubscribeExecutor.java
- geode-redis/src/test/java/org/apache/geode/redis/internal/SubscriptionsJUnitTest.java
> GEODE-8209: repackage GlobPattern

- geode-core/src/main/java/org/apache/geode/logging/internal/LoggingSession.java
- geode-core/src/test/java/org/apache/geode/logging/internal/LoggingSessionTest.java
> GEODE-8203: Provide ability to prevent disabling geode console appender

- geode-core/src/main/java/org/apache/geode/logging/internal/LoggingSession.java
> GEODE-8203: Removed camel casing for system property

- geode-redis/src/distributedTest/java/org/apache/geode/redis/CheckPrimaryBucketFunction.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/EnsurePrimaryStaysPutDUnitTest.java
> GEODE-8127: Remove statics from test function and re-enable tests

- geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ShutdownIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
> GEODE-8211: fix flaky shutdown test

- geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ShutdownIntegrationTest.java
> GEODE-8211: ignore flaky test

- geode-redis/src/acceptanceTest/java/org/apache/geode/redis/RenameNativeRedisAcceptanceTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/RedisDistDUnitTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/keys/RenameDUnitTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/RenameIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ExpireIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ShutdownIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/CommandFunction.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisKeyCommands.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisKeyCommandsFunctionExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisKeyInRegion.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RenameExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RenameFunction.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/StripedExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SynchronizedStripedExecutor.java
- geode-redis/src/main/resources/org/apache/geode/redis/internal/sanctioned-geode-redis-serializables.txt
> GEODE-8147: key commands implement Function-Delta

- geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
I found that if the passive expiration code threw an exception it would cause
the scheduled periodic task to no longer be run in the future.
It also would not show the exception.
The passive expiration code will no longer become disabled
if it throws an exception. It will now log the exception as a warning.
> GEODE-8222: fix flaky passive expiration

- geode-redis/src/commonTest/java/org/apache/geode/redis/GeodeRedisServerRule.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/general/ShutdownIntegrationTest.java
> GEODE-8211: Fix flaky test by increasing client timeout

- geode-docs/basic_config/data_entries_custom_classes/managing_data_entries.html.md.erb
This PR changes the user guide to go with the Javadocs update that was in GEODE-8171.
> GEODE-8198: Revise docs description of putAll()

- geode-core/src/distributedTest/java/org/apache/geode/cache/PRCacheListenerDistributedTest.java
- geode-core/src/distributedTest/java/org/apache/geode/cache/ReplicateCacheListenerDistributedTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionClear.java
- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionClearMessage.java
- geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionClearTest.java
- [ NA] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? …
> GEODE-8173: Add unit test (coverage) for PartitionedRegionClear class.

- geode-book/master_middleman/source/subnavs/geode-subnav.erb
- geode-docs/tools_modules/book_intro.html.md.erb
- geode-docs/tools_modules/redis_api_for_geode.html.md.erb
Update documentation to match changes in Redis API for Geode.
> GEODE-8223: Update documentation of expiration accuracy as well as supported, unsupported, and unimplemented commands in Redis API for Geode docs

- geode-redis/src/main/java/org/apache/geode/redis/internal/data/AbstractRedisData.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/EmptyRedisSet.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHash.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisString.java
> GEODE-8233: added equals and hashCode to RedisData classes

- geode-dunit/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscDUnitTestBase.java
Hi @metatype 
I have been trying to reproduce the failure reported in the ticket, but I have not been able to do it yet.
I dont know if you have progressed with this issue but just in case I think that we could add these checks to the test case in develop branch to have more information next time it appears.
> GEODE-8176: Add more checks in a flaky test

- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/SingleResultRedisFunction.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/key/RenameFunction.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSubImpl.java
> GEODE-8234: redis functions now implement InternalFunction

- geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
> GEODE-8222: Also ignore EntryDestroyedException during passive expiration

- geode-modules/build.gradle
- geode-modules/src/test/java/org/apache/geode/services/module/impl/JBossModulesServiceImplWithPopulatedManifestFileTest.java
- geode-modules/src/test/java/org/jboss/modules/GeodeJarModuleFinderTest.java
> GEODE-8190: Clean up tests and automate Geode version.

- geode-redis/src/distributedTest/java/org/apache/geode/redis/RedisDistDUnitTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/executors/ExpireDUnitTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/StringsIntegrationTest.java
> GEODE-8244: review ignored redis tests and enabled those that should now pass

- geode-redis/src/integrationTest/java/org/apache/geode/redis/StringsIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/sets/SetsIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisString.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisStringInRegion.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/CommandFunction.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisResponse.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SRandMemberExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/AppendExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/BitCountExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/BitOpExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/BitPosExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/DecrByExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/GetBitExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/GetRangeExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/GetSetExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/IncrByExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/IncrByFloatExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/MGetExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/MSetExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/MSetNXExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/RedisStringCommands.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/RedisStringCommandsFunctionExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/SetBitExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/SetEXExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/SetExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/SetNXExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/SetRangeExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/StrlenExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
> GEODE-8249: change more string commands to have CommandFunction support

- geode-redis/src/integrationTest/java/org/apache/geode/redis/HashesIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHash.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHashInRegion.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/CommandFunction.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HStrLenExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/RedisHashCommands.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/RedisHashCommandsFunctionExecutor.java
- geode-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java
- Also define PUBSUB as an unimplemented command
> GEODE-8242: Add HSTRLEN redis command

- geode-redis/src/distributedTest/java/org/apache/geode/redis/RedisDistDUnitTest.java
> GEODE-8253: Add additional concurrency tests for redis DEL

- buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/DeltaSession.java
- geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/TomcatInstall.java
Quick test to see what happens on tomcat 9.0.33
> GEODE-7896:  Update tomcat version

- geode-redis/src/main/java/org/apache/geode/redis/internal/data/AbstractRedisData.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHash.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisString.java
> GEODE-8260: add toString to RedisData classes

- geode-core/src/main/java/org/apache/geode/internal/cache/ha/HARegionQueue.java
- geode-core/src/test/java/org/apache/geode/internal/cache/ha/HARegionQueueTest.java
> GEODE-8261: Added a null check for the proxyID before executing a get.

- geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/AvailableConnectionManager.java
- geode-dunit/src/main/java/org/apache/geode/internal/cache/functions/TestFunction.java
- geode-junit/src/main/java/org/apache/geode/DeltaTestImpl.java
- geode-junit/src/main/java/org/apache/geode/internal/cache/PartitionedRegionTestHelper.java
- geode-junit/src/main/java/org/apache/geode/pdx/TestObjectForJSONFormatter.java
- geode-junit/src/main/java/org/apache/geode/security/query/data/PdxQueryTestObject.java
- geode-junit/src/main/java/org/apache/geode/security/query/data/QueryTestObject.java
> GEODE-7864: Overriding hashCode when equals is overridden.

- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/StringsIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/SetExecutor.java
> GEODE-8263: KEEPTTL should fail on SET command

- geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/key/KeysNativeRedisAcceptanceTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/KeysIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/key/KeysExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
> GEODE-8276: fix KEYS command to handle non-ASCII keys

- geode-redis/src/commonTest/java/org/apache/geode/redis/GeodeRedisServerRule.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/GeodeRedisServerStartupDUnitTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HMsetDUnitTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/UnknownIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/AuthIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/ExpireIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisService.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/AbstractExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Command.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
Adding some additional tests that were missing.
> GEODE-8269: Improve test coverage

- geode-core/build.gradle
- geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgrade2DUnitTestBase.java
- geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgradeWithGfshDUnitTest.java
- geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/GfshRule.java
- geode-management/src/main/java/org/apache/geode/management/configuration/AbstractConfiguration.java
- geode-management/src/main/java/org/apache/geode/management/configuration/Deployment.java
- geode-management/src/main/resources/org/apache/geode/internal/sanctioned-geode-management-serializables.txt
Co-authoried-by: Alberto Gomez <alberto.gomez@est.tech>
> GEODE-8251: make sure Configuration can be deserialized post 1.12.

- geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/connection/AuthNativeRedisAcceptanceTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/AuthIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisResponse.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
> GEODE-8280: Return correct Redis AUTH errors

- ci/bin/concourse_job_performance.py
- ci/bin/concourse_job_performance_requirements.txt
- ci/images/meta-mini/Dockerfile
- ci/pipelines/mass-test-run/deploy_pipeline.sh
- ci/pipelines/mass-test-run/jinja.template.yml
- ci/pipelines/meta/deploy_meta.sh
- ci/pipelines/meta/destroy_pipelines.sh
- ci/pipelines/meta/jinja.template.yml
- ci/pipelines/shared/jinja.variables.yml
This commit includes:
* Creating a new test run pipeline that runs the distributed test
multiple number of times.
* Update the meta pipeline to add mass test run pipeline.
* Logs into concourse using Vault creds to get fly token.
* Report-generation job runs often, but only generates a report every
N iterations.
* Use 'try' around test job, so we can trigger on it's completion state
- [n/a] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF …
> Add Mass Test Run pipeline.

- geode-old-versions/build.gradle
> GEODE-8289: Add gradle task chaining for geode-old-versions:clean

- ci/bin/concourse_job_performance.py
- ci/pipelines/mass-test-run/jinja.template.yml
> GEODE-8275: Improvements to mass-test-run after first pass deployment

- geode-docs/managing/logging/configuring_log4j2.html.md.erb
- geode-docs/managing/logging/how_logging_works.html.md.erb
Updates regarding log4j 2 customization.
@kirklund Please provide a JIRA number, if there is one. Thanks!
> Geode Logging doc changes

- gradle/java.gradle
- gradle/publish-java.gradle
> GEODE-8239 - Add gradle config to add 'Class-Path' and 'Dependent-Modules' attirbutes to manifest file

- ci/images/metric-tools/Dockerfile
> Fix metric-tools image python requirements.

- geode-junit/src/main/java/org/apache/geode/codeAnalysis/AnalyzeDataSerializablesJUnitTestBase.java
https://issues.apache.org/jira/browse/GEODE-8285
The test generated serialized data text file is now correctly placed in the build dir when running from IntelliJ (using default settings) and gradlew. Previously, when running an implementation of AnalyzeSerializablesJUnitTestBase using IntelliJ, generated test files would be placed under geode/\<geode module\>/src. The current fix will place those same files in geode/out/production/\<module's fully qualified class name\>.integratedTest when run from IntelliJ.
Improved the logic used by error message to build directory paths for sanctioned data file. This message is triggered when detecting a diff between test-generated serialized data and sanctioned data. A regular expression is used to address both IntelliJ and gradlew output error …
> GEODE-8285: Fix error message's directory path for sanctioned text file

- geode-assembly/src/upgradeTest/java/org/apache/geode/management/DeploymentManagementUpgradeTest.java
- geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgradeWithGfshDUnitTest.java
- geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/GfshRule.java
- geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/GfshScript.java
* improve some backward compatibility test to cover more versions.
> GEODE-8200: enhance GfshRule to specify a working dir

- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/mocks/DummySubscription.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/mocks/MockSubscriber.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PunsubscribeExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/UnsubscribeExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/ChannelSubscription.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PatternSubscription.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSub.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSubImpl.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/Subscription.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/Subscriptions.java
- geode-redis/src/test/resources/expected-pom.xml
This reverts commit 5e2baea7516b5e900f2699afddb63c59a20a1ab3.
Tests are causing hangs on Windows
> GEODE-8305: Revert "Feature/expand pubsub support (#5284)"

- geode-core/src/main/java/org/apache/geode/internal/cache/FilterProfile.java
- geode-core/src/main/java/org/apache/geode/internal/cache/TxCallbackEventFactoryImpl.java
- geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/CQDistributedTest.java
> GEODE-8247: modified FilterRoutingInfo checks

- geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/PassiveExpirationManager.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/RedisStats.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHashInRegion.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisKeyInRegion.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSetInRegion.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisStringInRegion.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/CommandFunction.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/key/RenameFunction.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/NettyRedisServer.java
- geode-redis/src/main/resources/org/apache/geode/redis/internal/sanctioned-geode-redis-serializables.txt
> GEODE-8301: redis stats

- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/SetRangeIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisStringInRegion.java
> GEODE-8311: fix setrange to prefix value

- ci/images/test-container/Dockerfile
- geode-assembly/Dockerfile
> Fix test-container and internal docker image.

- geode-redis/src/commonTest/java/org/apache/geode/redis/GeodeRedisServerRule.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/AuthIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisService.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/PassiveExpirationManager.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/NettyRedisServer.java
also simplified initialization of the NettyRedisServer to have
all final instance fields and do all its intialization in the
constructor
> GEODE-8310: removed the numThreads redis sys prop

- geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RestoreRedundancyManagementDUnitTest.java
- geode-core/src/main/java/org/apache/geode/management/internal/operation/OperationManager.java
- geode-core/src/test/java/org/apache/geode/internal/cache/control/SerializableRestoreRedundancyResultsImplTest.java
- geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/RestoreRedundancyRequestControllerIntegrationTest.java
- geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/RestoreRedundancyOperationController.java
These are the core changes that will allow the invocation of Restore Redundancy from REST
> GEODE-8095: Changes to make GEODE Respond to Restore Redundancy REST Command

- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/offheap/ParallelWANPersistenceEnabledGatewaySenderOffHeapDUnitTest.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelWANPersistenceEnabledGatewaySenderDUnitTest.java
> GEODE-8172: flaky test

- geode-core/src/main/java/org/apache/geode/internal/AvailablePort.java
- geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PartitionMemberInfoImpl.java
- geode-core/src/main/java/org/apache/geode/internal/cache/persistence/query/mock/ByteComparator.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/BaseCommandQuery.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientDataSerializerMessage.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientInstantiatorMessage.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/DeployCommand.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/ListJndiBindingCommand.java
> GEODE-7864: Fix array index out of bounds alerts

- geode-assembly/src/integrationTest/java/org/apache/geode/test/junit/rules/GfshRuleIntegrationTest.java
Add .bat to gfsh binary on Windows.
> GEODE-8328: Fix GfshRuleIntegrationTest on Windows

- geode-core/src/main/java/org/apache/geode/internal/cache/HARegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/ha/HARegionQueue.java
- geode-core/src/main/java/org/apache/geode/internal/cache/ha/QueueRemovalMessage.java
- geode-core/src/test/java/org/apache/geode/internal/cache/HARegionTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/ha/HARegionQueueTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/ha/QueueRemovalMessageTest.java
> GEODE-8323: Process QueueRemovalMessage after queue initialized.

- geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/data/DeltaDUnitTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/ByteArrayWrapper.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSet.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
Need to confirm that when deltas are propagated, the data is correctly stored on the secondary
> GEODE-8351: DUnit tests for Delta Propagation

- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/RegisterInterest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/RegisterInterest61.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/RegisterInterestList.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/RegisterInterestList61.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/RegisterInterestList66.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/UnregisterInterest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/UnregisterInterestList.java
Fix to an NPE in RegisterInterestList66, needed to validate that a we were not getting a null.
> GEODE-8359

- geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionClear.java
- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionClearMessage.java
- geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionClearTest.java
> GEODE-8361: Use Set instead of List to track cleared buckets

- geode-assembly/build.gradle
> GEODE-8369: Do not build docker images on Windows for geode-assembly:acceptanceTest

- geode-docs/tools_modules/micrometer/micrometer-configuration.html.md.erb
- geode-docs/tools_modules/micrometer/micrometer-overview.html.md.erb
> GEODE-8363: Label Micrometer docs as experimental

- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/HashesIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/DelIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SetsIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AppendIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/SetIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/StrLenIntegrationTest.java
> GEODE-8362: Add redis tests to ensure that commands can access binary data

- geode-redis/src/acceptanceTest/java/session/NativeRedisSessionAcceptanceTest.java
- geode-redis/src/acceptanceTest/java/session/NativeRedisSessionExpirationAcceptanceTest.java
- geode-redis/src/commonTest/java/org/apache/geode/test/dunit/rules/RedisClusterStartupRule.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/data/DeltaDUnitTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionDUnitTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionExpirationDUnitTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/session/springRedisTestApplication/SessionController.java
Write test verifying that maxInactiveInterval propagates correctly to all buckets
> GEODE-8370: Add test for maxInactiveInterval

- geode-docs/rest_apps/put_update_cas_data.html.md.erb
Reduced indent size in code samples that were located inside table cells. Allows more space for other columns' contents.
> GEODE-8381: User Guide - Reformat table in REST command description

- ci/scripts/execute_tests.sh
> Revert "GEODE-8373: For CI test runs, split the assemble and test invocation, to set max-…"

- geode-docs/tools_modules/gfsh/command-pages/connect.html.md.erb
> GEODE-8331: allow GFSH to connect to other versions of cluster

- geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubDUnitTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PublishExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/SubscribeExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Command.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/NettyRedisServer.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/AbstractSubscription.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSubImpl.java
- geode-redis/src/test/java/org/apache/geode/redis/internal/pubsub/PubSubImplJUnitTest.java
This reverts commit 067194e8f82414b6103c4335beb6567947edcfbc.
This fix has a bug in which responses to the client can now be out of order.
> Revert "GEODE-8333: Fix PUBSUB hang (#5349)"

- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/SetEXIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/SetEXExecutor.java
> GEODE-8384: fix SETEX error message

- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SetsIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
> GEODE-8386: fix SRANDMEMBER with negative count

- geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
- geode-core/src/test/java/org/apache/geode/internal/cache/ReplicateWithExpirationClearIntegrationTest.java
> GEODE-6564: fix entryExpiryTasks leak

- geode-core/src/main/java/org/apache/geode/cache/query/internal/cq/ServerCQ.java
- geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/CQDistributedTest.java
- geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/CqServiceImpl.java
- geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/ServerCQImpl.java
- geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/ServerCQResultsCache.java
- geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/ServerCQResultsCacheNoOpImpl.java
- geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/ServerCQResultsCachePartitionRegionImpl.java
- geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/ServerCQResultsCacheReplicateRegionImpl.java
> GEODE-8292: Added check if key is destroyed in CQResults

- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SDiffIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SInterIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SUnionIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSet.java
> GEODE-8409: S*STORE need to handle target that is not a redis set

- ci/scripts/execute_redis_tests.sh
Include more .tcl files in the Redis Tests CI job
> GEODE-8416: Add more Redis tests files to pipeline

- ci/scripts/archive_results.sh
- ci/scripts/create_instance.sh
- ci/scripts/delete_instance.sh
- ci/scripts/execute_build.sh
- ci/scripts/execute_tests.sh
- ci/scripts/repeat-new-tests.sh
- ci/scripts/rsync_code_down.sh
- ci/scripts/rsync_code_up.sh
- ci/scripts/shared_utilities.sh
> GEODE-8406: Make early-return immune to the Geode dir not existing

- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelWANPersistenceEnabledGatewaySenderDUnitTest.java
> GEODE-8172_1: additional check added

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/GIIDeltaDUnitTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/TombstoneService.java
- geode-core/src/main/java/org/apache/geode/internal/cache/versions/RegionVersionVector.java
- geode-core/src/test/java/org/apache/geode/internal/cache/TombstoneServiceTest.java
> Changes to help reduce the occurence of GEODE-8422

- geode-book/master_middleman/source/subnavs/geode-subnav.erb
- geode-docs/reference/topics/gemfire_properties.html.md.erb
- geode-docs/tools_modules/book_intro.html.md.erb
- geode-docs/tools_modules/redis_api_for_geode.html.md.erb
The docs should be updated to describe the Redis API for the upcoming 1.14 release.
> GEODE-8424: Updates Redis API for Geode docs 1.14

- geode-core/src/distributedTest/java/org/apache/geode/cache/ReplicateRegionNetsearchDistributedTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/CachePerfStats.java
- geode-core/src/main/java/org/apache/geode/internal/cache/SearchLoadAndWriteProcessor.java
- geode-core/src/test/java/org/apache/geode/internal/cache/CachePerfStatsTest.java
- geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedRule.java
Add new statistics for the server that receives and handles a netsearch request.
> GEODE-8425: Add new handling netsearch statistics

- geode-core/src/distributedTest/java/org/apache/geode/cache/RegionClearStatsDistributedTest.java
- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionClearDUnitTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegionMap.java
- geode-core/src/main/java/org/apache/geode/internal/cache/CachePerfStats.java
- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionClear.java
- geode-core/src/main/java/org/apache/geode/internal/cache/RegionPerfStats.java
- geode-core/src/main/java/org/apache/geode/internal/cache/RegionStats.java
- geode-core/src/test/java/org/apache/geode/internal/cache/CachePerfStatsTest.java
> GEODE-7846: Adding Stats for Partitioned Region Clear

- geode-core/src/integrationTest/java/org/apache/geode/cache/RegionFactoryJUnitTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/RegionAttributesCreation.java
> GEODE-8433: added inheritance of off-heap attribute

- geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java
- geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsDUnitTest.java
- geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/OfflineDiskStoreCommandsDUnitTest.java
- geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/AlterDiskStoreCommandIntegrationTest.java
- geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/DescribeDiskStoreCommandIntegrationTest.java
> GEODE-8119: Threads hangs when offline disk store command is invoked

- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisResponse.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/connection/PingExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
> GEODE-8451 Redis ping response contains unneeded quotes

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- geode-core/build.gradle
- geode-core/src/integrationTest/java/org/apache/geode/management/internal/beans/DistributedSystemMBeanIntegrationTest.java
- geode-core/src/main/java/org/apache/geode/management/internal/json/AbstractJSONFormatter.java
- geode-core/src/main/java/org/apache/geode/management/internal/json/QueryResultFormatter.java
- geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/json/QueryResultFormatterTest.java
> GEODE-8447: QueryResultFormatter should show dates in localized strings

- geode-redis/README.md
Update Redis API readme based on user testing feedback.
> GEODE-8448: Update README based on user feedback

- extensions/geode-modules-session/src/main/java/org/apache/geode/modules/session/filter/SessionCachingFilter.java
- geode-core/src/main/java/org/apache/geode/cache/query/internal/NullToken.java
- geode-core/src/main/java/org/apache/geode/cache/query/internal/Undefined.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java
- geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java
- geode-core/src/main/java/org/apache/geode/internal/cache/InitialImageOperation.java
- geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/Oplog.java
- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/ha/HARegionQueue.java
- geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/DumpB2NRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueue.java
- geode-core/src/main/java/org/apache/geode/management/internal/security/MBeanServerWrapper.java
- geode-core/src/test/java/org/apache/geode/internal/cache/AbstractRegionJUnitTest.java
- geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMembership.java
> GEODE-7864: Fix some LGTM alerts and suppress some false positives

- build.gradle
- geode-core/build.gradle
- geode-core/src/main/java/org/apache/geode/internal/GemFireVersion.java
- geode-core/src/main/java/org/apache/geode/internal/VersionDescription.java
- geode-core/src/main/java/org/apache/geode/internal/logging/Banner.java
- geode-core/src/test/java/org/apache/geode/internal/GemFireVersionJUnitTest.java
- geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/VersionCommandJUnitTest.java
- geode-pulse/src/integrationTest/java/org/apache/geode/tools/pulse/controllers/PulseControllerJUnitTest.java
- geode-pulse/src/integrationTest/java/org/apache/geode/tools/pulse/internal/context/PulseControllerTestContext.java
- geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/PulseAppListener.java
- geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/controllers/PulseController.java
- geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/data/PulseConstants.java
- geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/data/PulseVersion.java
- geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/service/PulseVersionService.java
- geode-pulse/src/main/webapp/accessDenied.html
- geode-pulse/src/main/webapp/clusterDetail.html
- geode-pulse/src/main/webapp/dataBrowser.html
- geode-pulse/src/main/webapp/memberDetails.html
- geode-pulse/src/main/webapp/queryStatistics.html
- geode-pulse/src/main/webapp/regionDetail.html
- geode-pulse/src/main/webapp/scripts/pulsescript/PulseCallbacks.js
- geode-pulse/src/main/webapp/scripts/pulsescript/common.js
* Rebuilds GemFireVersion.properties on Git repo or property changes
* version
* build user
* java version
* productName
* etc
> GEODE-8458: Use build metadata properties as task inputs

- geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/PdxLocalQueryDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/PdxLocalQueryVersionedClassDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/PdxQueryDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/PdxStringQueryDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/QueryParamsAuthorizationDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/SelectStarQueryDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/PingOpDistributedTest.java
- geode-core/src/integrationTest/java/org/apache/geode/internal/AvailablePortHelperIntegrationTest.java
- geode-dunit/src/main/java/org/apache/geode/internal/cache/wan/AsyncEventQueueTestBase.java
- geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/OfflineDiskStoreCommandsDUnitTest.java
- geode-junit/src/main/java/org/apache/geode/internal/AvailablePortHelper.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/GeodeRedisServerStartupDUnitTest.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/UpdateVersionDUnitTest.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/misc/SenderWithTransportFilterDUnitTest.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/misc/WANLocatorServerDUnitTest.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/misc/WanAutoDiscoveryDUnitTest.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/misc/WanValidationsDUnitTest.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderOperationsDUnitTest.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/GatewayReceiverDUnitTest.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderEventListenerDUnitTest.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/WANHostNameVerificationDistributedTest.java
- geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeDUnitTest.java
Removed the following unused methods:
- getRandomAvailableTCPPortRange(int)
- getRandomAvailableTCPPorts(int,bool)
- getRandomAvailableTCPPortRangeKeepers(int)
- getRandomAvailableTCPPortRangeKeepers(int,bool)
Removed two methods that used an ineffective, incorrect calculation to
try to distribute ports evenly across VMs:
- getRandomAvailablePortForDUnitSite()
- getRandomAvailableTCPPortsForDUnitSite()
These methods attempted to distribute ports by using the VM id as a
modulus. The intention was something like this (assuming 5 VMs):
VM 1 would get ports 20001, 20006, 20011, 20016, ...
VM 2 would get ports 20002, 20007, 20012, 20017, ...
VM 3 would get ports 20003, 20008, 20013, 20018, ...
VM 4 would get ports 20004, 20009, 20014, 20019, ...
VM 5 would get ports 20000, 20005, 20010, 20015, …
> GEODE-8404: Simplify AvailablePortHelper

- geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueue.java
- geode-core/src/test/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueueJUnitTest.java
Co-authored-by: Darrel Schneider <darrel@vmware.com>
> GEODE-8475: Resolve a potential dead lock in ParallelGatewaySenderQueue

- geode-core/src/distributedTest/java/org/apache/geode/cache/query/partitioned/PRClearQueryIndexDUnitTest.java
- geode-core/src/main/java/org/apache/geode/cache/query/internal/DefaultQueryService.java
- geode-core/src/main/java/org/apache/geode/cache/query/internal/index/IndexManager.java
- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionClear.java
- geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java
- geode-junit/src/main/java/org/apache/geode/cache/query/data/City.java
* allow ClusterStartupRule to launch dunit default locator
> GEODE-7672: add dunit test to verify OQL index after PR clear.

- geode-wan/src/main/java/org/apache/geode/internal/cache/wan/GatewaySenderEventRemoteDispatcher.java
- geode-wan/src/test/java/org/apache/geode/internal/cache/wan/GatewaySenderEventRemoteDispatcherJUnitTest.java
> GEODE-8485: When connection is closed, its server could be null

- geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
- geode-core/src/main/java/org/apache/geode/internal/DSFIDFactory.java
- geode-core/src/main/java/org/apache/geode/internal/cache/ha/HARegionQueue.java
- geode-core/src/main/java/org/apache/geode/internal/cache/ha/QueueRemovalMessage.java
- geode-core/src/main/java/org/apache/geode/internal/cache/ha/QueueSynchronizationProcessor.java
- geode-core/src/test/java/org/apache/geode/internal/cache/ha/HARegionQueueTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/ha/QueueRemovalMessageTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/ha/QueueSynchronizationProcessorTest.java
- geode-serialization/src/main/java/org/apache/geode/internal/serialization/DataSerializableFixedID.java
A seconary HARegionQueue will try to sync with primary after GII
to remove any events have been already dispatched from primary.
> GEODE-8465: secondary HARegionQueue to sync with primary queue

- geode-core/build.gradle
- geode-core/src/jca/java/org/apache/geode/internal/ra/spi/JCALocalTransaction.java
- geode-core/src/test/java/org/apache/geode/internal/ra/spi/JCALocalTransactionTest.java
Note: This change was tested using the websphere-liberty docker image.
> GEODE-8483: Remove JNDI lookup and check

- geode-core/src/main/java/org/apache/geode/internal/cache/control/InternalResourceManager.java
- geode-core/src/test/java/org/apache/geode/internal/cache/control/InternalResourceManagerTest.java
> GEODE-8482: Concurrent access to ArrayList should be synchronized

- geode-book/master_middleman/source/subnavs/geode-subnav.erb
- geode-docs/tools_modules/redis_api_for_geode.html.md.erb
> GEODE-8487: Document Redis_API HA model, requirements, guarantees

- ci/pipelines/shared/jinja.variables.yml
- geode-lucene/src/upgradeTest/java/org/apache/geode/cache/lucene/LuceneSearchWithRollingUpgradeTestBase.java
- geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeDUnitTest.java
- settings.gradle
> add 1.13.0 to old versions and set as Benchmarks baseline on develop

- geode-redis/src/commonTest/java/org/apache/geode/test/dunit/rules/RedisClusterStartupRule.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubDUnitTest.java
> GEODE-8503: Limit netty threads used in PubSubDUnitTest

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- geode-assembly/src/integrationTest/resources/assembly_content.txt
- geode-assembly/src/integrationTest/resources/dependency_classpath.txt
> GEODE-8505: Upgrade netty from 4.1.48 to 4.1.52

- geode-docs/tools_modules/http_session_mgmt/tomcat_installing_the_module.html.md.erb
- geode-docs/tools_modules/http_session_mgmt/weblogic_setting_up_the_module.html.md.erb
* geode-tcp and geode-membership added to the list
* removed geode-json as it does not exist anymore.
> GEODE-8523: Session state document update

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- geode-core/src/test/java/org/apache/geode/pdx/internal/PeerTypeRegistrationTest.java
- geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/functions/GetRegionsFunctionTest.java
- geode-web/src/test/java/org/apache/geode/management/internal/web/controllers/support/LoginHandlerInterceptorTest.java
Adopt me! (otherwise I will be abandoned if no progress by Oct 16)
> Bump mockito from 3.3.3 to 3.5.11

- geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ListIndexManagementDUnitTest.java
- geode-management/src/main/java/org/apache/geode/management/configuration/Index.java
- geode-management/src/test/java/org/apache/geode/management/configuration/IndexTest.java
> GEODE-8496: fix rest management test after dependency bump

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- buildSrc/build.gradle
- buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RestoreRedundancyManagementDUnitTest.java
- geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/rest/SwaggerManagementVerificationIntegrationTest.java
- geode-assembly/src/integrationTest/java/org/apache/geode/rest/internal/web/DevRestSwaggerVerificationIntegrationTest.java
- geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/RegionMappingTest.java
- geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/SqlHandlerTest.java
- geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/SqlToPdxInstanceCreatorTest.java
- geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/SqlToPdxInstanceTest.java
- geode-experimental-driver/build.gradle
- geode-experimental-driver/src/integrationTest/java/org/apache/geode/experimental/driver/SSLTest.java
- geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/RestoreRedundancyCommandDUnitTest.java
- geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/functions/UserFunctionExecutionTest.java
- geode-junit/src/main/java/org/apache/geode/test/junit/rules/serializable/SerializableTemporaryFolder.java
- geode-junit/src/test/java/org/apache/geode/test/junit/rules/serializable/SerializableTemporaryFolderTest.java
- geode-junit/src/test/java/org/apache/geode/test/junit/runners/CategoryWithParameterizedRunnerFactoryTest.java
- geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/ClearRequestOperationHandlerJUnitTest.java
- geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/ExecuteFunctionOnGroupRequestOperationHandlerJUnitTest.java
- geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/GetAllRequestOperationHandlerJUnitTest.java
- geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/GetSizeRequestOperationHandlerJUnitTest.java
- geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/PutIfAbsentRequestOperationHandlerJUnitTest.java
- geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/PutRequestOperationHandlerJUnitTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SDiffIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SInterIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SMoveIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SPopIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SRemIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SUnionIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SetsIntegrationTest.java
Adopt me! (otherwise I will be abandoned if no progress by Oct 16)
> Bump junit from 4.12 to 4.13

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/MembershipDependenciesJUnitTest.java
- geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/api/MembershipAPIArchUnitTest.java
- geode-serialization/src/test/java/org/apache/geode/internal/serialization/SerializationDependenciesJUnitTest.java
- geode-tcp-server/src/test/java/org/apache/geode/distributed/internal/tcpserver/TcpServerDependenciesTest.java
Adopt me! (otherwise I will be abandoned if no progress by Oct 16)
> Bump archunit from 0.12.0 to 0.14.1

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- geode-management/src/test/java/org/apache/geode/management/configuration/ClassNameTest.java
- geode-management/src/test/java/org/apache/geode/management/configuration/DeploymentTest.java
- geode-management/src/test/java/org/apache/geode/management/runtime/DeploymentInfoTest.java
Adopt me! (otherwise I will be abandoned if no progress by Oct 16)
> Bump assertj from 3.15.0 to 3.17.2

- extensions/geode-modules-test/src/main/java/org/apache/geode/modules/session/catalina/AbstractDeltaSessionManagerTest.java
- extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/DeltaSessionManager.java
Removes query that resulted in casting issue in antlr.
Clears all locally cached entries.
> GEODE-8513: Remove (de)serialization of local sessions.

- CODE_OF_CONDUCT.md
> added code of conduct to  project

- geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/connection/AuthNativeRedisAcceptanceTest.java
- geode-redis/src/commonTest/java/org/apache/geode/NativeRedisTestRule.java
> GEODE-8549: Remove use of junit EnvironmentVariables rule from geode-redis

- geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/internal/DUnitBlackboardDUnitTest.java
- geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedBlackboardDistributedTest.java
- geode-dunit/src/main/java/org/apache/geode/test/dunit/Blackboard.java
- geode-dunit/src/main/java/org/apache/geode/test/dunit/DUnitBlackboard.java
- geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/InternalBlackboardImpl.java
- geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedBlackboard.java
Package up DUnitBlackboard as a JUnit Rule named DistributedBlackboard.
> GEODE-8540: Create new DistributedBlackboard Rule

- ci/pipelines/pull-request/jinja.template.yml
fix for jinja template variable that isn't always present for windows
> GEODE-8561: Add support to PR pipeline for running Windows checks

- geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/StartServerCommandDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/cache/ReplicateCacheListenerDistributedTest.java
- geode-core/src/distributedTest/java/org/apache/geode/distributed/LocatorDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/ClusterDistributionManagerDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/DistributionAdvisorDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/BucketCreationCrashRegressionTest.java
- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/DeltaPropagationDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PRQueryWithPdxDuringRebalanceRegressionTest.java
- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentRVVRecoveryDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/management/DistributedSystemMXBeanDistributedTest.java
- geode-core/src/distributedTest/java/org/apache/geode/management/DistributedSystemMXBeanWithAlertsDistributedTest.java
- geode-core/src/distributedTest/java/org/apache/geode/management/DistributedSystemMXBeanWithNotificationsDistributedTest.java
- geode-core/src/distributedTest/java/org/apache/geode/management/JMXMBeanReconnectDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/management/internal/MBeanFederationErrorHandlingDistributedTest.java
- geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedErrorCollectorDistributedTest.java
- geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedErrorCollector.java
Rename SharedErrorCollector as DistributedErrorCollector.
> GEODE-8252: Rename DistributedErrorCollector

- geode-core/src/distributedTest/java/org/apache/geode/cache/ReplicateCacheListenerDistributedTest.java
- geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedCountersDistributedTest.java
- geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedCounters.java
Rename SharedCountersRule as DistributedCounters.
> GEODE-8252: Rename DistributedCounters

- geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubNativeRedisAcceptanceTest.java
> GEODE-8577: PubSubNativeRedisAcceptanceTest is flaky

- geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueue.java
> GEODE-8421: replace cleaning of region with destroy/create

- geode-redis/src/integrationTest/java/org/apache/geode/redis/AbstractCommandPipeliningIntegrationTest.java
> GEODE-8538: Create test to validate ordering of redis pipeline commands

- geode-docs/reference/topics/gemfire_properties.html.md.erb
> GEODE-8576: fix doc on "security-peer-auth-init"

- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractPubSubIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/connection/PingExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/connection/QuitExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PsubscribeExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PunsubscribeExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/SubscribeExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/UnsubscribeExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
Co-Authored-by: Jens Deppe <jdeppe@vmware.com>
Co-Authored-by: Sarah Abbey <sabbey@vmware.com>
> GEODE-8525: Ensure that all pubsub related commands run on the correct EventLoopGroup

- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelWANPersistenceEnabledGatewaySenderDUnitTest.java
> GEODE-8172_2: refactoring of failing testcase

- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialWANPersistenceEnabledGatewaySenderDUnitTest.java
> GEODE-8216: modify test

- geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/key/ScanNativeRedisAcceptanceTest.java
- geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubNativeRedisAcceptanceTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/AbstractScanIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/ScanIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/key/ScanExecutor.java
Co-authored-by: Darrel Schneider <darrel@vmware.com>
> GEODE-8582: Redis SCAN returns internal server error

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- extensions/geode-modules-session-internal/build.gradle
- extensions/geode-modules-test/build.gradle
- extensions/geode-modules-tomcat7/build.gradle
- extensions/geode-modules-tomcat8/build.gradle
- extensions/geode-modules-tomcat8/src/test/resources/expected-pom.xml
- extensions/geode-modules-tomcat9/build.gradle
- extensions/geode-modules/build.gradle
- extensions/geode-modules/src/test/resources/expected-pom.xml
- gradle/publish-java.gradle
> GEODE-8590: Cleanup dependencies in the session state modules

- geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueue.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelWANStatsDUnitTest.java
> GEODE-8600: Fix for faulty statistics QueueSize

- geode-lucene/src/distributedTest/java/org/apache/geode/cache/lucene/internal/IndexRepositoryFactoryDistributedTest.java
- geode-lucene/src/integrationTest/java/org/apache/geode/cache/lucene/internal/IndexRepositoryFactoryIntegrationTest.java
- geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/IndexRepositoryFactory.java
- geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/IndexRepositoryFactoryTest.java
> GEODE-8536: Allow limited retries when creating Lucene IndexWriter

- geode-core/src/main/java/org/apache/geode/internal/cache/RegionMapFactory.java
- geode-core/src/main/java/org/apache/geode/management/GatewaySenderMXBean.java
- geode-core/src/main/java/org/apache/geode/management/internal/beans/GatewaySenderMBean.java
- geode-core/src/main/java/org/apache/geode/management/internal/beans/GatewaySenderMBeanBridge.java
- geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/GatewaySenderOverflowMonitor.java
- geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/StatsKey.java
- geode-core/src/test/java/org/apache/geode/management/internal/beans/stats/GatewaySenderOverflowMonitorTest.java
> GEODE-8497: added getTotalQueueSizeBytesInUse

- geode-core/src/main/java/org/apache/geode/internal/cache/control/SerializableRegionRedundancyStatusImpl.java
- geode-core/src/test/java/org/apache/geode/internal/cache/control/RegionRedundancyStatusImplTest.java
- geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/RestoreRedundancyCommandDUnitTest.java
> GEODE-8620: Do not include non-created buckets in redundancy calculation

- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/AbstractTTLIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/key/TTLExecutor.java
> GEODE-8629: Redis TTL should round up the returned value

- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AbstractIncrByFloatIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisString.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/IncrByFloatExecutor.java
> GEODE-8622: Redis INCRBYFLOAT error messages are consistent with native Redis

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/versions/TombstoneDUnitTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/TombstoneService.java
- Need an API to tell how many how long until the oldest tombstone expires.
> GEODE-8607: Adding some test API to get oldest tombstone

- geode-junit/src/main/java/org/apache/geode/test/junit/rules/GsRandom.java
- geode-junit/src/main/java/org/apache/geode/test/junit/rules/RandomRule.java
- geode-junit/src/test/java/org/apache/geode/test/junit/rules/RandomRuleTest.java
> GEODE-8595: Create new RandomRule for tests

- ci/pipelines/pull-request/jinja.template.yml
> GEODE-8639: Increase PR resource-get attempts to match develop

- geode-redis/src/commonTest/java/org/apache/geode/redis/ConcurrentLoopingThreads.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HdelDUnitTest.java
- Also add the ability for ConcurrentLoopingThreads to be run
asynchronously.
> GEODE-8633: Add concurrency tests for Redis HDEL

- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/NettyRedisServer.java
> GEODE-8636: Remove hard-coded value from String in NettyRedisServer

- geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedMapDistributedTest.java
- geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedMap.java
> GEODE-8594: Create new DistributedMap for dunit

- geode-docs/tools_modules/redis_api_for_geode.html.md.erb
- geode-redis/README.md
- geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/key/UnlinkNativeRedisAcceptanceTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/AbstractUnlinkIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/UnlinkIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java
- This does not implement async deletes
> GEODE-8630: Add Redis UNLINK command as synonym to DEL

- geode-common/src/main/java/org/apache/geode/util/internal/CompletionUtils.java
- geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedReferenceTest.java
- geode-dunit/src/main/java/org/apache/geode/test/dunit/VM.java
- geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedReference.java
Includes additional improvements for usage of DistributedReference
in tests.
> GEODE-8650: Support multiple instances of DistributedReference

- build.gradle
> GEODE-8660: Remove mavenLocal from build.gradle.

- ci/pipelines/geode-build/jinja.template.yml
- ci/pipelines/pull-request/jinja.template.yml
- ci/scripts/create_instance.sh
> [GEODE-8661] Use version provided by *-builder-image-family.

- ci/pipelines/pull-request/jinja.template.yml
> [GEODE-8661] - Fix problem with pr pipeline. Used wrong variable in template.

- ci/pipelines/examples/jinja.template.yml
> Update exmples CI to use the builder_image

- ci/pipelines/mass-test-run/jinja.template.yml
> [GEODE-8661] Fix mass-test-run pipeline.

- geode-core/src/main/java/org/apache/geode/cache/query/internal/DefaultQuery.java
- geode-docs/developing/query_additional/query_debugging.html.md.erb
> GEODE-8675: Log at query start when <trace> is enabled

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionClearWithAlterRegionDUnitTest.java
- geode-serialization/src/main/java/org/apache/geode/internal/serialization/DataSerializableFixedID.java
> GEODE-7679 Partitioned Region clear is successful while region is being altered

- geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ShowMissingDiskStoreCommandDUnitTest.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/ShowMissingDiskStoreCommand.java
> GEODE-8547: Added impacts to show missing disk-stores

- geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/server/HitsMissesNativeRedisAcceptanceTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
> GEODE-8691: Add test to cover native Redis hits and misses statistics

- extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/DeltaSession.java
- geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/TomcatContainer.java
- geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/TomcatInstall.java
- geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/CargoTestBase.java
- geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Tomcat6ClientServerTest.java
- geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Tomcat6Test.java
- geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Tomcat7CachingClientServerTest.java
- geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Tomcat7ClientServerTest.java
- geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Tomcat7Test.java
- geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Tomcat8CachingClientServerTest.java
- geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Tomcat8ClientServerTest.java
- geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Tomcat8Test.java
- geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Tomcat9CachingClientServerTest.java
- geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Tomcat9CachingClientServerValveDisabledTest.java
- geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Tomcat9ClientServerTest.java
- geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Tomcat9Test.java
- geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/Tomcat8ClientServerRollingUpgradeTest.java
- geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/TomcatSessionBackwardsCompatibilityTestBase.java
> GEODE-8684: Setting a session's maxInactiveInterval does not work when the commit valve is disabled

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/versions/TombstoneDUnitTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/TombstoneService.java
- Adding some test API to get oldest tombstone timestamp
- Adding some test API for getting the oldest tombstone
(cherry picked from commit eb91e9517f579c005c7b69937b8cfced7d3cc37e)
> Geode 8607 - Changes to check the oldest tombstone

- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractInfoIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/server/InfoExecutor.java
> GEODE-8715: Redis INFO command 'Keyspace' section should not be present if no keys in database

- geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueue.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelWANPersistenceEnabledGatewaySenderDUnitTest.java
> GEODE-8714: return event to queue at stoping of gw sender

- geode-core/src/main/java/org/apache/geode/distributed/internal/FunctionExecutionPooledExecutor.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/OverflowQueueWithDMStats.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/SerialQueuedExecutorWithDMStats.java
- geode-core/src/main/java/org/apache/geode/internal/ScheduledThreadPoolExecutorWithKeepAlive.java
- geode-core/src/main/java/org/apache/geode/internal/logging/CoreLoggingExecutors.java
- geode-core/src/test/java/org/apache/geode/internal/logging/CoreLoggingExecutorsTest.java
- geode-logging/src/main/java/org/apache/geode/logging/internal/executors/LoggingExecutors.java
Cleanup constructors of logging executors and add tests for
CoreLoggingExecutors.
> GEODE-8521: Add tests for CoreLoggingExecutors

- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelWANPersistenceEnabledGatewaySenderDUnitTest.java
> GEODE-8714_1: update test according to comments

- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractInfoIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/server/InfoExecutor.java
- [ X] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?
- [ X] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?
- [ X] Is your initial contribution a single, squashed commit?
- [ X] Does `gradlew build` run cleanly?
> GEODE-8717: INFO command returns specified sections

- settings.gradle
- [x ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?
- [ x] Does `gradlew build` run cleanly?
> add 1.13.1 to old versions on develop

- geode-common/build.gradle
- geode-common/src/main/java/org/apache/geode/annotations/internal/DeprecatedButRequiredForBackwardsCompatibilityTesting.java
- geode-common/src/main/java/org/apache/geode/annotations/internal/SuppressDeprecationForBackwardsCompatibilityTesting.java
- geode-common/src/main/java/org/apache/geode/internal/Retry.java
- geode-common/src/main/java/org/apache/geode/internal/inet/LocalHostUtil.java
- geode-common/src/test/java/org/apache/geode/internal/RetryTest.java
- geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
- geode-dunit/src/main/java/org/apache/geode/test/dunit/NetworkUtils.java
- geode-tcp-server/src/distributedTest/java/org/apache/geode/distributed/internal/tcpserver/TcpServerProductVersionDUnitTest.java
This is a continuation of the work done by https://github.com/apache/geode/pull/5680
> GEODE-8623: Retry getting local host if it fails.

- geode-core/src/integrationTest/java/org/apache/geode/internal/statistics/LinuxSystemStatsTest.java
- geode-core/src/main/java/org/apache/geode/internal/statistics/platform/LinuxProcFsStatistics.java
- geode-core/src/main/java/org/apache/geode/internal/statistics/platform/LinuxSystemStats.java
> GEODE-8734: Parse netstat file to ensure correct stats are retrieved

- geode-core/src/integrationTest/java/org/apache/geode/distributed/LauncherMemberMXBeanIntegrationTest.java
- This change is specifically to see if things improve on Windows
> GEODE-5782: Try to improve memory reporting stats for Windows

- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderQueueDUnitTest.java
SerialGatewaySenderQueueDUnitTest.unprocessedTokensMapShouldDrainCompletely()
now waits until the queues are drained rather than sleeping for 2
seconds before asserting.
> GEODE-8644: Change sleep to awaitility in sender queue test

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
> GEODE-8758: Downgrade testcontainers from 1.15.0 to 1.14.3

- geode-docs/tools_modules/http_session_mgmt/tomcat_installing_the_module.html.md.erb
- geode-docs/tools_modules/http_session_mgmt/weblogic_setting_up_the_module.html.md.erb
> GEODE-8532: Corrected the geode-tcp-server jar name in doc

- geode-docs/tools_modules/redis_api_for_geode.html.md.erb
- geode-redis/README.md
- geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
> GEODE-8759: Update docs to include HSTRLEN and INFO as unsupported

- geode-log4j/src/main/resources/log4j2-cli.xml
- geode-log4j/src/main/resources/log4j2.xml
> GEODE-2644: Adding memberName to the log pattern

- geode-log4j/src/main/resources/log4j2-cli.xml
- geode-log4j/src/main/resources/log4j2.xml
> Revert "GEODE-2644: Adding memberName to the log pattern"

- geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderEventProcessor.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderOperationsDistributedTest.java
> GEODE-8745: locking maps, to prevent concurrent use by Listeners

- geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/tests/AsyncInvocationTimeoutDistributedTest.java
Null out latch and threadId before each test.
The bug was caused by:
1. The previous test left threadId set to a non-zero value*
2. The await() in the second thread completes before the threadId.set() in the first thread executes
3. The second thread returns the wrong value for remoteThreadId
4. The wrong remoteThreadId is then compared to the caught exception's message which has a different thread id
*Previous test was await_callable_timeout_includesStackTraceAsCause in all three recorded test failures
Fix is simple: always set threadId to zero value before running each test.
> GEODE-8634: Fix AsyncInvocationTimeoutDistributedTest flakiness

- CODEOWNERS
submitting a PR as per the self-nomination process proposed on the [dev list](https://lists.apache.org/x/thread.html/r1975489455c88ad8a016f3e953d3e507f847caea5636eb880b4c6148@%3Cdev.geode.apache.org%3E)
> nominate myself as codeowner for dependency, license, and release scripts

- geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgradeDUnitTest.java
RollingUpgradeDUnitTest now assigns available HTTP and JMX ports when
launching and rolling locators, rather than using the default ports.
This allows the tests to run in parallel outside of docker.
> GEODE-8770: RollingUpgradeDUnitTest assigns ports

- ci/scripts/run_benchmarks.sh
> GEODE-8763: run benchmark tests up to 5 times

- geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySender.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/BatchDestroyOperation.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderEventProcessor.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialWANPersistenceEnabledGatewaySenderDUnitTest.java
> GEODE-8745: Handle race between batch destroy msg and sec event.

- geode-core/src/integrationTest/java/org/apache/geode/cache/query/partitioned/PRClearIntegrationTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegionMap.java
- geode-core/src/main/java/org/apache/geode/internal/cache/versions/RegionVersionVector.java
> GEODE-8771: invalidate should acquire the lock before initIndex

- geode-core/src/main/java/org/apache/geode/distributed/internal/OperationExecutors.java
- geode-core/src/main/java/org/apache/geode/internal/cache/properties.html
- geode-core/src/test/java/org/apache/geode/distributed/internal/ClusterOperationExecutorsTest.java
> GEODE-8780: Increase the default number of function execution threads.

- geode-redis/build.gradle
- geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubNativeRedisAcceptanceTest.java
- geode-redis/src/commonTest/java/org/apache/geode/NativeRedisTestRule.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractPubSubIntegrationTest.java
- gradle/docker.gradle
- Could not reproduce after ~8000 runs
- Added some debugging to dump 'docker ps' output if a connection cannot
be obtained.
> GEODE-8577: Re-enable PubSubNativeRedisAcceptanceTest

- extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/DeltaSessionManager.java
- extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/PeerToPeerSessionCache.java
> GEODE-8781: Added ReconnectListener to PeerToPeerSessionCache

- extensions/geode-modules-session-internal/src/main/java/org/apache/geode/modules/session/internal/common/ClientServerSessionCache.java
- extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/ClientServerSessionCache.java
- extensions/geode-modules/src/test/java/org/apache/geode/modules/session/catalina/AbstractSessionCacheTest.java
- extensions/geode-modules/src/test/java/org/apache/geode/modules/session/catalina/ClientServerSessionCacheTest.java
> GEODE-8779: Register interest only when local cache is enabled.

- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/RedisStatsIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/RedisStats.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/server/InfoExecutor.java
> GEODE-8769: help ensure stats are settled before testing

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ValidateOfflineDiskStoreDUnitTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/Oplog.java
> GEODE-8665: validate offline-disk-store command is missing information

- geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubNativeRedisAcceptanceTest.java
> GEODE-8577: Ignoring PubSubNativeRedisAcceptanceTest since it is still flaky

- geode-core/src/main/java/org/apache/geode/internal/cache/properties.html
> GEODE-7864: Clean up properties.html

- geode-docs/tools_modules/gfsh/command-pages/start.html.md.erb
> GEODE-8796: doc max-threads incompatible with TLS

- geode-core/build.gradle
> GEODE-8496: Add tools.jar to integrationTest classpath for geode-core

- geode-docs/developing/querying_basics/restrictions_and_unsupported_features.html.md.erb
Disclaimer: OQL queries are not pre-validated for nonexistent attributes
and methods
> GEODE-7802: Add disclaimer for OQL queries in UG

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- geode-assembly/src/integrationTest/resources/assembly_content.txt
- geode-assembly/src/integrationTest/resources/dependency_classpath.txt
needs changes to make 1 test pass.  to reproduce: `./gradlew :geode-web-management:integrationTest --tests DeploymentIntegrationTest`
> GEODE-8496: Bump spring from 5.3.1 to 5.3.2

- geode-docs/configuring/running/firewalls_ports.html.md.erb
- geode-docs/reference/topics/gemfire_properties.html.md.erb
> GEODE-8802: clarify mcast-port default in docs

- geode-core/src/integrationTest/java/org/apache/geode/internal/SSLConfigJUnitTest.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfigImpl.java
Co-authored-by: Xiaojian Zhou <zhouxh@vmware.com>
Co-authored-by: Bill Burcham <bill.burcham@gmail.com>
> GEODE-8800: Slower receiver is not allowed with cluster TLS/SSL

- geode-junit/src/main/java/org/apache/geode/test/util/StressNewTestHelper.java
- geode-junit/src/test/java/org/apache/geode/test/util/WhatExtendsJUnitTest.java
> GEODE-8819: StressNewTestHelper should handle non org.apache.geode changed files

- geode-core/src/main/java/org/apache/geode/internal/cache/map/RegionMapDestroy.java
- geode-core/src/test/java/org/apache/geode/internal/cache/AbstractRegionMapTest.java
> GEODE-8790: Evicted entries sometimes remain in region map

- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/RedisStatsIntegrationTest.java
-change offset to be a percentage of total commands
> GEODE-8803:increase offset of flakey test

- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/RedisStatsIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/statistics/RedisStats.java
Co-authored-by: Ray Ingles <ringles@vmware.com>
> GEODE-8821: Add tests to validate Geode redis stats

- geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
- geode-core/src/test/java/org/apache/geode/internal/cache/GemFireCacheImplTest.java
> GEODE-8815: Cache could close with uncaught exception

- geode-book/master_middleman/source/subnavs/geode-subnav.erb
- geode-docs/basic_config/data_entries_custom_classes/chapter_overview.html.md.erb
- geode-docs/basic_config/data_entries_custom_classes/copy_on_read.html.md.erb
- geode-docs/basic_config/data_entries_custom_classes/managing_data_entries.html.md.erb
- geode-docs/developing/transactions/design_considerations.html.md.erb
- geode-docs/reference/archive_transactions/JTA_transactions.html.md.erb
- geode-docs/tools_modules/gfsh/command-pages/alter.html.md.erb
This PR includes updating all links to this subsection. And, I changed the title of the section.
> GEODE-8818: Make copy on read info more visible

- geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegionMap.java
- geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
- geode-core/src/test/java/org/apache/geode/internal/cache/AbstractRegionMapTest.java
> GEODE-8278: Modified to cause lruEntryUpdate to be called

- geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueue.java
- geode-core/src/main/java/org/apache/geode/management/internal/beans/GatewaySenderMBeanBridge.java
- geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/GatewaySenderOverflowMonitor.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/GatewaySenderOverflowMBeanAttributesDistributedTest.java
> GEODE-8822: Clear statistics when clean queue option is used

- geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerImplTest.java
- geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerImpl.java
> GEODE-8835: Increment connection count if create successfully

- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CommandInitializer.java
- geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/CommandInitializerJUnitTest.java
- geode-serialization/src/main/java/org/apache/geode/internal/serialization/KnownVersion.java
> GEODE-8841: Add version ordinals for GEODE_1_12_1 and GEODE_1_13_1

- geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
> GEODE-8844: Fixes double check locking.

- ci/pipelines/images/deploy_images_pipeline.sh
> Revert upgrade to Ubuntu 20.04.

- ci/images/google-geode-builder/scripts/setup.sh
> GEODE-8843: Fix package names.

- ci/scripts/repeat-new-tests.sh
> GEODE-8849: Improve failure output when running stress tests in CI

- geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/AlterRegionCommandDUnitTest.java
* Tests use unique names for the regions used in them
* This is in sync with the same test class used in WAN module.
* Region destroy moved into the tests.
> GEODE-8854: Tests use unique region names

- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/AbstractSMoveIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisKeyCommandsFunctionExecutor.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/CommandFunction.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/key/RedisKeyCommands.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/key/RedisKeyCommandsFunctionInvoker.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SMoveExecutor.java
- geode-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java
- This fixes an issue with hits/misses stats.
> GEODE-8857: Redis SMOVE command should not do type checking in the executor

- .asf.yaml
Pretty sure this goes on `develop` branch as it is our default. Otherwise, we'll need to cherry-pick to `master` to take effect.
> Enable require_code_owner_reviews: true via .asf.yaml

- geode-core/src/main/java/org/apache/geode/internal/cache/tx/DistributedTXRegionStub.java
- geode-core/src/test/java/org/apache/geode/internal/cache/tx/DistributedTXRegionStubTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/tx/PartitionedTXRegionStubTest.java
> GEODE-8797: Increase code coverage on TXRegionStub classes

- geode-redis/src/commonTest/java/org/apache/geode/redis/ConcurrentLoopingThreads.java
- Can be invoked by calling `.runInLockstep()`.
- This simply adds a CyclicBarrier before the invocation of each
iteration and should produce a bit more contention.
> GEODE-8913: Add ability for ConcurrentLoopingThreads to run in lockstep

- ci/pipelines/examples/jinja.template.yml
- ci/pipelines/geode-build/jinja.template.yml
- ci/pipelines/images/jinja.template.yml
- ci/pipelines/mass-test-run/jinja.template.yml
- ci/pipelines/meta/jinja.template.yml
- ci/pipelines/pull-request/jinja.template.yml
- ci/pipelines/reaper/jinja.template.yml
> GEODE-8915: - update CI pipelines for concourse 6.x

- geode-wan/src/main/java/org/apache/geode/cache/client/internal/locator/wan/LocatorDiscovery.java
- geode-wan/src/test/java/org/apache/geode/cache/client/internal/locator/wan/LocatorDiscoveryTest.java
> GEODE-8890: Catch ClassCastException in LocatorDiscovery.java

- geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java
> GEODE-8374: Remove no-op of unsupported system property.

- geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/string/StringNativeRedisAcceptanceTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/string/StringsDUnitTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AbstractStringIntegrationTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/StringIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java
> GEODE-8911: Redis - DECR tests

- geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HGetDUnitTest.java
> GEODE-8903: fix timing issue in HGET dunit test

- geode-docs/tools_modules/gfsh/command-pages/export.html.md.erb
> GEODE-8917: Revise gfsh export stack-traces docs

- geode-docs/configuring/cluster_config/persisting_configurations.html.md.erb
- geode-docs/developing/eviction/how_eviction_works.html.md.erb
Updated example output with current verbiage, paths, and options.
Added a typo correction from an unrelated eviction page for (my own) convenience.
> GEODE-8866: User Guide - Update Cluster Config Tutorial "deploy" example

- geode-core/src/main/java/org/apache/geode/internal/cache/tx/RemoteOperationMessage.java
- geode-core/src/test/java/org/apache/geode/internal/cache/tx/RemoteOperationMessageTest.java
> GEODE-8930: Using WaitingThreadPool to process the message.

- geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ExportStackTraceCommandDUnitTest.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/ExportStackTraceCommand.java
- geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/commands/ExportStackTraceCommandTest.java
> GEODE-8916: Added locators to the export stack traces command

- geode-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionDUnitTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionsAndCrashesDUnitTest.java
- Use Spring repositories to perform fetch and save operations.
> GEODE-8924: Add VM restart tests for Redis and Spring sessions

- geode-core/src/distributedTest/java/org/apache/geode/cache/management/MemoryThresholdsDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/cache/management/MemoryThresholdsOffHeapDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/cache/management/ResourceManagerDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/ResourceManagerWithQueryMonitorDUnitTest.java
- geode-core/src/integrationTest/java/org/apache/geode/internal/cache/control/MemoryMonitorJUnitTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/control/HeapMemoryMonitor.java
- geode-core/src/main/java/org/apache/geode/internal/cache/control/InternalResourceManager.java
- geode-core/src/main/java/org/apache/geode/internal/cache/control/OffHeapMemoryMonitor.java
- geode-core/src/main/java/org/apache/geode/internal/cache/control/ResourceMonitor.java
- geode-core/src/main/java/org/apache/geode/internal/cache/eviction/HeapEvictor.java
- Remove duplicate fine-level logging from deliverEventFromRemote()
- Clean up raw use of parameterized classes
- Clean up other static analyzer warnings
> GEODE-7864: Clean up InternalResourceManager

- geode-management/src/test/java/org/apache/geode/management/internal/ClientClusterManagementServiceTest.java
> GEODE-8097: expects at least one callback

- geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeaveJUnitTest.java
- geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java
> GEODE-8919: undid polymorphic naming for processMessage methods.

- geode-core/src/main/java/org/apache/geode/internal/cache/TXCommitMessage.java
> GOEDE-8964: Entry created via TX putIfAbsent with null value can write incorrect data to cache

- geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeaveJUnitTest.java
- geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java
(cherry picked from commit 6edf69546b784f67ed125bc4b1d592496ee1f5ee)
> [BACKPORT] GEODE-8919: undid polymorphic naming for processMessage methods. (#6055)

- ci/pipelines/shared/jinja.variables.yml
- dev-tools/release/promote_rc.sh
- bump benchmark baseline version to most recent release
- change release script to automatically change the baseline to the
latest released version
> GEODE-8986: bump benchmark baseline version

- geode-core/src/main/java/org/apache/geode/distributed/internal/direct/DirectChannel.java
- geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
… (#6041)
(cherry picked from commit fc2fc9f890c5673bd6d0954048efb525b0098126)
> Back-port GEODE-8920 to support/1.14: Modify debug logging to make it easier to trace a message

- geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/GatewaySenderAdvisor.java
- geode-core/src/test/java/org/apache/geode/internal/cache/wan/GatewaySenderAdvisorTest.java
- geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeVerifyGatewaySenderProfile.java
Getting rid of a write and a read in the wrong place...
> GEODE-8886 fix

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ClientServerTransactionDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/RemoteTransactionDUnitTest.java
> GEODE-8907: CI Failure: ClientServerTransactionCCEDUnitTest.testTxRemoveAll

- geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/GatewaySenderEventImpl.java
- geode-core/src/test/java/org/apache/geode/internal/cache/wan/GatewaySenderEventImplTest.java
> GEODE-8992: Added operationDetail to toData/fromData

- geode-core/src/integrationTest/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionIntegrationTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java
- geode-core/src/main/java/org/apache/geode/internal/monitoring/ThreadsMonitoring.java
- geode-core/src/main/java/org/apache/geode/internal/monitoring/ThreadsMonitoringImpl.java
- geode-core/src/main/java/org/apache/geode/internal/monitoring/executor/ServerConnectionExecutorGroup.java
- geode-core/src/main/java/org/apache/geode/internal/monitoring/executor/SuspendableExecutor.java
- geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionFactoryTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionTest.java
- geode-core/src/test/java/org/apache/geode/internal/monitoring/ThreadsMonitoringImplJUnitTest.java
- geode-core/src/test/java/org/apache/geode/internal/monitoring/ThreadsMonitoringJUnitTest.java
- geode-core/src/test/java/org/apache/geode/internal/monitoring/executor/P2PReaderExecutorGroupTest.java
- geode-core/src/test/java/org/apache/geode/internal/monitoring/executor/ServerConnectionExecutorGroupTest.java
- geode-core/src/test/java/org/apache/geode/internal/monitoring/executor/SuspendableExecutorTest.java
- geode-protobuf/src/test/java/org/apache/geode/internal/cache/tier/sockets/OutputCapturingServerConnectionTest.java
- geode-protobuf/src/test/java/org/apache/geode/internal/cache/tier/sockets/ProtobufServerConnectionTest.java
> GEODE-8761: detect stuck server connection threads

- .asf.yaml
> GEODE-9012: turn off Github PR to Jira comment mirroring

- geode-core/src/integrationTest/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionIntegrationTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java
- geode-core/src/main/java/org/apache/geode/internal/monitoring/ThreadsMonitoring.java
- geode-core/src/main/java/org/apache/geode/internal/monitoring/ThreadsMonitoringImpl.java
- geode-core/src/main/java/org/apache/geode/internal/monitoring/executor/ServerConnectionExecutorGroup.java
- geode-core/src/main/java/org/apache/geode/internal/monitoring/executor/SuspendableExecutor.java
- geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionFactoryTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionTest.java
- geode-core/src/test/java/org/apache/geode/internal/monitoring/ThreadsMonitoringImplJUnitTest.java
- geode-core/src/test/java/org/apache/geode/internal/monitoring/ThreadsMonitoringJUnitTest.java
- geode-core/src/test/java/org/apache/geode/internal/monitoring/executor/P2PReaderExecutorGroupTest.java
- geode-core/src/test/java/org/apache/geode/internal/monitoring/executor/ServerConnectionExecutorGroupTest.java
- geode-core/src/test/java/org/apache/geode/internal/monitoring/executor/SuspendableExecutorTest.java
- geode-protobuf/src/test/java/org/apache/geode/internal/cache/tier/sockets/OutputCapturingServerConnectionTest.java
- geode-protobuf/src/test/java/org/apache/geode/internal/cache/tier/sockets/ProtobufServerConnectionTest.java
(cherry picked from commit df7b5b167472d87d8d262515533e7c80d7306e67)
> GEODE-8761: detect stuck server connection threads (#6094)

- .asf.yaml
> GEODE-9012: Turn off Github Comments Causing Jira Ticket Comments

- geode-core/src/main/java/org/apache/geode/internal/cache/DistributedCacheOperation.java
- geode-core/src/main/java/org/apache/geode/internal/cache/DistributedPutAllOperation.java
- geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRemoveAllOperation.java
- geode-core/src/test/java/org/apache/geode/internal/cache/DistributedCacheOperationTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/DistributedPutAllOperationTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/DistributedRemoveAllOperationTest.java
- geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/PartitionedRegionCqQueryDUnitTest.java
> GEODE-9016: Fix the NPE for PutAll with CQ LOCAL_DESTROY message type

- geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/string/StringsDUnitTest.java
- geode-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
- geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisService.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/AbstractRedisData.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/ByteArrayWrapper.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisData.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisData.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHash.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisString.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/CommandFunction.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/SingleResultRedisFunction.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/key/RenameFunction.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/SetOptions.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/gfsh/RedisCommandFunction.java
- geode-redis/src/main/resources/org/apache/geode/redis/internal/sanctioned-geode-redis-serializables.txt
- geode-redis/src/test/java/org/apache/geode/redis/internal/data/RedisHashTest.java
- geode-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSetTest.java
- geode-redis/src/test/java/org/apache/geode/redis/internal/data/RedisStringTest.java
- geode-serialization/src/main/java/org/apache/geode/internal/serialization/DataSerializableFixedID.java
* DataSerializable classes were converted in DataSerializableFixedID
* serialVersionID were added to the unavoidable Serializable classes
> GEODE-9019: Serialization improvements in geode-redis

- geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisResponse.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
> GEODE-9021: Remove unnecessary buffer allocation in redis Coder

- geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeaveJUnitTest.java
- geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java
> GEODE-9000: Added logic to avoid NPE during processing Network Partition

- geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/InequalityQueryWithRebalanceDistributedTest.java
- geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/index/PartitionedIndexJUnitTest.java
- geode-core/src/main/java/org/apache/geode/cache/query/internal/index/PartitionedIndex.java
> GEODE-9030: Modified PartitionedIndex to reset arbitraryBucketIndex

- geode-book/config.yml
- geode-book/master_middleman/source/subnavs/geode-subnav.erb
- geode-docs/configuring/running/cluster-management-service.html.md.erb
- geode-docs/getting_started/upgrade/upgrade_clients.html.md.erb
- geode-docs/getting_started/upgrade/upgrade_offline.html.md.erb
- geode-docs/getting_started/upgrade/upgrade_overview.html.md.erb
- geode-docs/getting_started/upgrade/upgrade_planning.html.md.erb
- geode-docs/getting_started/upgrade/upgrade_rolling.html.md.erb
Add an upgrade section to the Geode User Guide.
> GEODE-8946: User Guide - add an Upgrade section

- geode-docs/developing/partitioned_regions/checking_region_redundancy.html.md.erb
- geode-docs/developing/partitioned_regions/restoring_region_redundancy.html.md.erb
> GEODE-8985: Fix doc references to 'startup-recovery-delay'

- CODEWATCHERS
> GEODE-9041: Add albertogpz to several sections of CODEWATCHERS

- geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledLike.java
- geode-dunit/src/main/java/org/apache/geode/management/internal/cli/commands/QueryCommandDUnitTestBase.java
> GEODE-8962: add an option to escape dollar($) character in query

- geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/PartitionedRegionCqQueryDUnitTest.java
(cherry picked from commit 4e0c8aa6937ad2b5935a11994138381fa29a8644)
> GEODE-9016: Fixed missing imports

- geode-core/src/main/java/org/apache/geode/cache/client/internal/locator/wan/LocatorMembershipListener.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java
- geode-wan/build.gradle
- geode-wan/src/main/java/org/apache/geode/cache/client/internal/locator/wan/LocatorMembershipListenerImpl.java
- geode-wan/src/test/java/org/apache/geode/cache/client/internal/locator/wan/LocatorMembershipListenerTest.java
- geode-wan/src/test/resources/expected-pom.xml
> GEODE-8956: added thread pool to LocatorMembershipListener

- geode-docs/tools_modules/redis_api_for_geode.html.md.erb
- geode-redis/README.md
…tible-with-redis commands
(cherry picked from commit 58116cc759076ee093ec1627795cae431a0b7265)
> GEODE-9001: Update Documents to be match recent code changes in compatible-with-redis commands

- CODEOWNERS
> Adding additional engineers to CODEOWNERS sections.

- geode-wan/src/main/java/org/apache/geode/cache/client/internal/locator/wan/LocatorHelper.java
> GEODE-8955: using marshal instead of toString method

- geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegion.java
- geode-core/src/test/java/org/apache/geode/internal/cache/AbstractRegionTest.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderOperationsDUnitTest.java
> GEODE-8918: fix replication in multisite systems

- ci/pipelines/shared/jinja.variables.yml
- settings.gradle
> add 1.13.2 to old versions and set as Benchmarks baseline on develop

- geode-docs/tools_modules/geode_apis_compatible_with_redis.html.md.erb
- geode-redis/README.md
this corresponds with commit 39c0abf96ae93a2a49fd0ab28ad2e96c1fa9e7a8
> GEODE-9086: update docs to show support for DECRBY

- geode-docs/tools_modules/geode_apis_compatible_with_redis.html.md.erb
- geode-redis/README.md
this corresponds with commit 39c0abf96ae93a2a49fd0ab28ad2e96c1fa9e7a8
(cherry picked from commit 4c286d6d7373cf9c1cb3fef8f5df23d930c879fc)
> GEODE-9086 backport

- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java
* The threadMonitorExecutor is now created in the run() method
which causes the correct thread id to be set on it.
* changed threadMonitorExecutor field from protected to private
(cherry picked from commit 89200dca57a3ab57fd98bd1af438944a9aff5f23)
> GEODE-8761: detect stuck ServerConnection threads (#6226)

- geode-core/src/main/java/org/apache/geode/internal/cache/wan/GatewaySenderEventImpl.java
- https://github.com/apache/geode/pull/6222 added this and it the lgtm review was missed
> GEODE-9100: Fix self assignment in GatewaySenderEventImpl

- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/common/UnsupportedCommandsIntegrationTest.java
> GEODE-9119: Move file missed during module renaming

- ci/scripts/execute_redis_tests.sh
- geode-redis/src/commonTest/java/org/apache/geode/redis/GeodeRedisServerRule.java
- geode-redis/src/commonTest/java/org/apache/geode/test/dunit/rules/RedisClusterStartupRule.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/GeodeRedisServerStartupDUnitTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/CrashAndNoRepeatDUnitTest.java
- geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HashesAndCrashesDUnitTest.java
- geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/common/UnsupportedCommandsIntegrationTest.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandSupportLevel.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Command.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
- geode-redis/src/main/java/org/apache/geode/redis/internal/statistics/GeodeRedisStats.java
- geode-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java
* update handling of unsupported commands
(cherry picked from commit cf4c3395644af48bcbda81bef7a6d1e01b2c47cf)
> GEODE-9037: Remove unimplemented commands

- CODEOWNERS
> Add ringles as codeowner to geode-apis-compatible-with-redis

- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/common/UnsupportedCommandsIntegrationTest.java
(cherry picked from commit 9570f4ec2663646ea51a48d217ae9db1f423c865)
> GEODE-9119: Move file missed during module renaming (#6258)

- geode-apis-compatible-with-redis/README.md
- geode-docs/tools_modules/geode_apis_compatible_with_redis.html.md.erb
(cherry picked from commit 9964531d146c49a7094b8f534d6fa6468b14835e)
> GEODE-9087: redis docs for HSCAN command (#6235)

- buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/DeltaSession.java
- geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/TomcatInstall.java
Update tomcat integration to work with versions after 9.0.21.
(cherry picked from commit 70fe060bbdba951512403cc0795f29bd2d7d21d6)
> GEODE-7896 Update tomcat support

- geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeVerifyGatewaySenderProfile.java
This test was pulled from the code because it failed once in the CI. I have since run thousands of times with 0 failures.
Creating a PR to run it through the pipeline to see if it happens there. If not merge it and wait.
> Geode 8886 new test

- ci/pipelines/examples/jinja.template.yml
- ci/pipelines/geode-build/jinja.template.yml
- ci/pipelines/mass-test-run/jinja.template.yml
- ci/pipelines/pull-request/jinja.template.yml
- ci/pipelines/shared/jinja.variables.yml
- ci/scripts/create_instance.sh
> GEODE-9142: Parameterize heavy lifter instace storage.

- geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisHashTest.java
> GEODE-9113-extend wait period for hscanSnaphots_shouldExpireAfterExpiryPeriod

- geode-core/src/main/java/org/apache/geode/cache/asyncqueue/internal/AsyncEventQueueFactoryImpl.java
- geode-core/src/main/java/org/apache/geode/cache/asyncqueue/internal/AsyncEventQueueImpl.java
- geode-core/src/main/java/org/apache/geode/cache/wan/GatewaySender.java
- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionClear.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySender.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/GatewaySenderAttributes.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/InternalGatewaySender.java
- geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionClearTest.java
- geode-lucene/src/distributedTest/java/org/apache/geode/cache/lucene/LuceneIndexCreationDUnitTest.java
- geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneIndexImpl.java
> GEODE-7674: Clear on PR with lucene index should throw exception

- CODEOWNERS
Removing myself from CODEOWNERS as I'm retiring soon and shouldn't be
blocking any pull requests.  Ernie & Bill are taking my place for now.
> GEODE-9145: update CODEOWNERS

- CODEWATCHERS
> add CODEWATCHERS for jar-deployment

- geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisHashTest.java
Co-authored-by: john Hutchison <hutchisonjo@vmware.com>
(cherry picked from commit ac4ebe9457285c7b0658cd6d8fa7ec05231d71f7)
> backport GEODE-9113 (extend hscan expiration period)

- dev-tools/release/promote_rc.sh
- docker/Dockerfile
remove it since the other two are the good ones anyway
> GEODE-9181: bad url first caused checksum error during release

- geode-http-service/src/main/java/org/apache/geode/internal/cache/http/service/InternalHttpService.java
- geode-http-service/src/main/resources/META-INF/services/org.apache.geode.internal.cache.CacheService
- geode-http-service/src/test/java/org/apache/geode/management/internal/InternalHttpServiceJunitTest.java
- geode-pulse/geode-pulse-test/src/main/java/org/apache/geode/tools/pulse/tests/rules/ServerRule.java
> GEODE-9095: Resolve package splitting http-service

- CODEWATCHERS
> GEODE-9041: add mkevo to several sections of CODEWATCHERS

- ci/images/test-container/Dockerfile
- ci/pipelines/images/jinja.template.yml
- ci/pipelines/meta/deploy_meta.sh
* Use ubuntu as the base
* Install packages we got from the old base
* Install ca-certificates with the initial batch
* Adjust test-container build job
> GEODE-9192: test-container fixes

- geode-apis-compatible-with-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/GeodeServerRunTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/PassiveExpirationManager.java
increase the time between checks for keys to expire. this reduces the
cpu utilization but causes longer collections when they do collect.
> GEODE-9155: change frequency of passive expiration

- geode-dunit/src/main/java/org/apache/geode/management/internal/cli/commands/QueryCommandDUnitTestBase.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/domain/DataCommandResult.java
> GEODE-9174: fix displaying the result of a gfsh query containing a UUID

- geode-apis-compatible-with-redis/README.md
- geode-book/master_middleman/source/subnavs/geode-subnav.erb
- geode-docs/tools_modules/geode_apis_compatible_with_redis.html.md.erb
> GEODE-9163: Mark docs for apis compatible with Redis as experimental

- geode-apis-compatible-with-redis/build.gradle
- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/NativeRedisClusterTest.java
- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/cluster/ClusterNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/ClusterNode.java
- geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/ClusterNodes.java
- geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/NativeRedisClusterTestRule.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/cluster/ClusterSlotsAndNodesDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/cluster/JedisAndLettuceClusterDUnitTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/cluster/AbstractClusterIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/cluster/ClusterIntegrationTest.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/ParameterRequirements/ClusterParameterRequirements.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/cluster/BucketInfoRetrievalFunction.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/cluster/ClusterExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/NettyRedisServer.java
- geode-apis-compatible-with-redis/src/main/resources/org/apache/geode/redis/internal/sanctioned-geode-apis-compatible-with-redis-serializables.txt
- geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java
- geode-apis-compatible-with-redis/src/test/resources/expected-pom.xml
- None of the commands will return 'replica' information since Geode does
make the distinction of a primary vs a secondary member.
> GEODE-9158: Add CLUSTER NODES, SLOTS and INFO commands

- buildSrc/build.gradle
- ci/pipelines/geode-build/jinja.template.yml
- ci/pipelines/shared/jinja.variables.yml
- ci/scripts/rsync_code_down.sh
> GEODE-9079: downsize non-intentensive CI instances

- geode-common/src/jmh/java/org/apache/geode/internal/lang/ComputeIfAbsentBenchmark.java
- geode-common/src/main/java/org/apache/geode/internal/inet/LocalHostUtil.java
- geode-common/src/main/java/org/apache/geode/internal/lang/utils/JavaWorkarounds.java
- geode-common/src/main/java/org/apache/geode/internal/utils/Retry.java
- geode-common/src/test/java/org/apache/geode/internal/utils/RetryTest.java
- geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/TableMetaDataManager.java
- geode-core/src/main/java/org/apache/geode/cache/query/internal/AttributeDescriptor.java
- geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupDefinition.java
- geode-core/src/main/java/org/apache/geode/internal/cache/execute/metrics/FunctionStatsManager.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientHealthMonitor.java
- geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java
- geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/CqServiceImpl.java
- geode-lucene/src/main/java/org/apache/geode/cache/lucene/FlatFormatSerializer.java
- geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitor.java
- geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/GMSEncrypt.java
> GEODE-9092 - Resolve package splitting geode-common

- geode-apis-compatible-with-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/GeodeServerRunTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/PassiveExpirationManager.java
This reverts commit 85183489c8c47de7f356e1ae55eaf31b9658276c.
this commit caused some tests to fail.
> Revert "GEODE-9155: change frequency of passive expiration (#6325)"

- geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
- geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionClear.java
- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionClearMessage.java
- geode-core/src/main/java/org/apache/geode/internal/cache/RegionEventFactory.java
- geode-core/src/test/java/org/apache/geode/internal/cache/BucketRegionJUnitTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/DistributedRegionTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionClearMessageTest.java
Unit test changes in BucketRegion and DistributedRegion.
Unit test most of PartitionedRegionClearMessage.
This is a PR for a feature branch NOT develop. Please do not review if someone accidentally changes it from DRAFT mode.
> FEATURE-BRANCH: GEODE-9195: Remove PR clear local locking

- geode-core/src/integrationTest/java/org/apache/geode/internal/cache/event/DistributedEventTrackerIntegrationTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/event/DistributedEventTracker.java
- Refactored DistributedEventTracker to move the logging into hasSeenEvent
- Added tests to DistributedEventTrackerIntegrationTest for other cases
- Modified DistributedEventTrackerIntegrationTest to use TemporaryDirectory
- Fixed comparison bug in BucketRegion.hasLowRedundancy
> GEODE-9138: Refactored and added tests

- geode-core/src/main/java/org/apache/geode/internal/cache/TxCallbackEventFactoryImpl.java
- geode-core/src/test/java/org/apache/geode/internal/cache/TxCallbackEventFactoryImplTest.java
> GEODE-9109: Clean up when to set local filter info for tx.

- buildSrc/src/main/resources/japicmp_exceptions.json
- geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
- geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/StartServerCommand.java
- make redis properties in ConfigurationProperties experimental
- add experimental annotation to cli strings
- add experimental marker to help messages
> GEODE-9162: Mark Radish as experimental

- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/RedundancyCommand.java
> GEODE-9225: Remove unused code in RedundancyCommand.java

- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/set/SaddDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/set/SremDUnitTest.java
> GEODE-9220: Switch set DUnit tests to use JedisCluster

- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HExistsDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HGetDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HKeysDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HMgetDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HMsetDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HScanDunitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HSetNXDunitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HashesAndCrashesDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HlenDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HsetDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HstrlenDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HvalsDUnitTest.java
> GEODE-9238: Switch hash DUnit tests to use JedisCluster/RedisClusterClient

- ci/scripts/create_instance.sh
> GEODE-9244: Fix SSH passwordless login for windows

- geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/ServerContainer.java
> GEODE-8990: Resolve memory issue with Jetty9 Cargo Test

- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/set/SDiffNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/set/SInterNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/set/SIsMemberNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/set/SMoveNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/set/SPopNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/set/SRemNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/set/SScanNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/set/SUnionNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/set/SetsNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/AbstractSDiffIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/AbstractSInterIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/AbstractSIsMemberIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/AbstractSMoveIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/AbstractSPopIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/AbstractSRemIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/AbstractSScanIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/AbstractSUnionIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/AbstractSetsIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SScanIntegrationTest.java
> GEODE-9220: Switch Redis set tests to use JedisCluster

- ci/images/google-geode-builder/scripts/setup.sh
- ci/images/google-windows-geode-builder/packer.json
- ci/images/test-container/Dockerfile
- ci/scripts/execute_build.sh
- ci/scripts/execute_build_examples.sh
- ci/scripts/execute_publish.sh
- ci/scripts/execute_tests.sh
- ci/scripts/rsync_code_down.sh
- docker/Dockerfile
- geode-assembly/Dockerfile
This is the final cleanup following successful conversion in Part 2 (#5474)
(all three phases were 1: add liberica  2: switch  3: remove adoptopenjdk)
> GEODE-8321: part 3 - remove adoptopenjdk

- ci/images/google-windows-geode-builder/packer.json
- ci/scripts/execute_tests.sh
> GEODE-9251: openssh update waits for orphan child-processes. Kill them

- geode-assembly/src/acceptanceTest/java/org/apache/geode/rules/DockerComposeRule.java
> GEODE-9257: Use local docker-compose binary in DockerComposeRule

- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HExistsDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HGetDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HKeysDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HMgetDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HMsetDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HScanDunitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HSetNXDunitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HashesAndCrashesDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HlenDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HsetDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HstrlenDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HvalsDUnitTest.java
> GEODE-9238: Restructure Hash-related DUnit tests to handle cluster mode

- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/AbstractKeysIntegrationTest.java
> GEODE-9220: Fix failing test on Windows Server 2016

- CODEOWNERS
> Add additional redis codeowner

- CODEWATCHERS
Before merging this PR, please verify I have the proper permissions in `apache/geode` project.
I have been added as Geode committer, but I think I dont have the correct permissions yet.
Thanks!
> GEODE-9282: Add alb3rtobr to CODEWATCHERS file

- geode-apis-compatible-with-redis/src/acceptanceTest/java/session/NativeRedisSessionAcceptanceTest.java
- geode-apis-compatible-with-redis/src/acceptanceTest/java/session/NativeRedisSessionExpirationAcceptanceTest.java
- geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/NativeRedisClusterTestRule.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/session/RedisSessionDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionsAndCrashesDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/session/springRedisTestApplication/config/WebMvcConfig.java
> GEODE-9283: Convert session related redis DUnit tests to be cluster-aware

- CODEOWNERS
> Add donalevans as codeowner for Redis API module

- geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/DistributionAdvisorIntegrationTest.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionAdvisor.java
> GEODE-9307: Removed MembershipListener after force disconnect

- geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeDUnitTest.java
> GEODE-9299: Assert greater than or equal instead of equals

- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/sortedset/ZCardNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/sortedset/ZCardDUnitTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZAddIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZCardIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/ZCardIntegrationTest.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSetCommandsFunctionExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/CommandFunction.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/RedisSortedSetCommandsFunctionInvoker.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZCardExecutor.java
- geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java
> GEODE-9292: Implement ZCARD

- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/sortedset/ZRemNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/sortedset/ZRemDUnitTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZRemIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/ZRemIntegrationTest.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSetCommandsFunctionExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/CommandFunction.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/RedisSortedSetCommandsFunctionInvoker.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZRemExecutor.java
- geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java
- geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSortedSetTest.java
This is same as https://github.com/apache/geode/pull/6524
Due to merge conflict - has to do a new PR instead. Sorry for the extra review request.
> GEODE-9318: Implement ZREM command.

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PREntryIdleExpirationDistributedTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/LatestLastAccessTimeMessage.java
- geode-core/src/test/java/org/apache/geode/internal/cache/LatestLastAccessTimeMessageTest.java
- sender now tells if expiration is invalid or destroy
- message now checks for removed and invalid entries
> GEODE-9146: idle expiration should ignore removed remote entries

- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/sortedset/ZIncrByNativeRedisIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZIncrByIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/ZIncrByIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSortedSet.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSetCommandsFunctionExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/CommandFunction.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisResponse.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/RedisSortedSetCommandsFunctionInvoker.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZIncrByExecutor.java
- geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java
-implement the command
-add integration test
-add concurrency test
-support infinity as a valid increment
> GEODE-9306: support ZINCRBY command

- geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/NativeRedisClusterTestRule.java
- Seems that waiting for the 'cluster ready' message is not enough, so
now loop for up to 5 seconds waiting for all primaries to appear.
> GEODE-9252: Improve NativeRedisClusterTestRule waiting for cluster to be ready

- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/RedisTestHelper.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractInfoIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractRedisInfoStatsIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractRedisMemoryStatsIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AbstractAppendMemoryIntegrationTest.java
> GEODE-9343: Extract getInfo() helper method from tests.

- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
put all the tests in the right sections of the test class to indicate
which commands of each type are supported or unsupported.
> GEODE-9335: Organize HitsMissesIntegrationTest

- geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
- geode-core/src/main/java/org/apache/geode/internal/cache/ClusterConfigurationLoader.java
- geode-core/src/main/java/org/apache/geode/management/internal/configuration/domain/Configuration.java
- geode-gfsh/src/upgradeTest/java/org/apache/geode/management/ConfigurationCompatibilityTest.java
* Configuration sent from 1.12.0 locators and later can be interpreted by pre 1.12.0 version locators
> GEODE-9289: Configuration compatible with pre-1.12.0 versions

- geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
- geode-core/src/main/java/org/apache/geode/internal/cache/ClusterConfigurationLoader.java
- geode-core/src/main/java/org/apache/geode/management/internal/configuration/domain/Configuration.java
- geode-gfsh/src/upgradeTest/java/org/apache/geode/management/ConfigurationCompatibilityTest.java
* Configuration sent from 1.12.0 locators and later can be interpreted by pre 1.12.0 version locators
(cherry picked from commit c1e59b23a89d4eac89334f525cd4a8bfaebefe1d)
> GEODE-9289: Configuration compatibile with pre-1.12.0 versions.

- geode-gfsh/src/main/resources/META-INF/services/org.springframework.shell.core.CommandMarker
> GEODE-7665: Missing file is causing trouble

- geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java
Removed the threadConnMaps ArrayList.
This removal also means that the HashMap is now
only referenced by a ThreadLocal so it no longer
is synchronized which simplified the code.
(cherry picked from commit 88918f1221e7bf90c88596d19c06ec41eec8315e)
> GEODE-9331: remove the threadConnMaps ArrayList (#6535)

- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/SynchronizedStripedExecutor.java
- geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/executor/SynchronizedStripedExecutorTest.java
> GEODE-9366: Redis SynchronizedStripeExecutor can throw IndexOutOfBoundsException

- geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/DistributionAdvisorIntegrationTest.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionAdvisor.java
(cherry picked from commit 2bc4bd93a6c24ea32c3a44c502fcb20c0a255cb4)
> GEODE-9307: Removed MembershipListener after force disconnect (#6515)

- geode-core/src/main/java/org/apache/geode/distributed/internal/DMStats.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionStats.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/LonerDistributionManager.java
- geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java
- geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionStatsTest.java
> GEODE-9372: Added createSenderTime and createSenderInProgress stats

- dev-tools/release/prepare_rc.sh
release process does check this at the end, but checking it at the beginning saves time and wasted RC#'s...
> GEODE-8481: validate java version and vendor earlier

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/LatestLastAccessTimeMessageDistributedTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/LatestLastAccessTimeMessage.java
- geode-core/src/test/java/org/apache/geode/internal/cache/LatestLastAccessTimeMessageTest.java
> Feature/geode 9295 1.14

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/LatestLastAccessTimeMessageDistributedTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/LatestLastAccessTimeMessage.java
- geode-core/src/test/java/org/apache/geode/internal/cache/LatestLastAccessTimeMessageTest.java
> Feature/geode 9295 1.13

- geode-apis-compatible-with-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractPubSubIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractSubCommandsIntegrationTest.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PubSubExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/StringBytesGlossary.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSub.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSubImpl.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/Subscriptions.java
> GEODE-9203: Implement Radish PUBSUB NUMSUB subcommand

- CODEOWNERS
Temporarily removing myself as a codeowner from Radish so I can focus on the session state module.
- [ N/A] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?
- [ X] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?
- [X ] Is your initial contribution a single, squashed commit?
- [X ] Does `gradlew build` run cleanly?
- [ N/A] Have you written or updated unit tests to verify your changes?
- [ N/A] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF …
> Temporarily remove sabbey37 from Radish CODEOWNERS

- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZRankIntegrationTest.java
> GEODE-9400: Use positive bytes to create random strings

- geode-core/src/main/java/org/apache/geode/internal/net/NioSslEngine.java
- geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
(cherry picked from commit 1b97c7c25f1fb68a94d5c7008b98630de45d48b6)
> Back-port GEODE-9380 to 1.14

- geode-core/src/main/java/org/apache/geode/internal/net/NioSslEngine.java
- geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
(cherry picked from commit 1b97c7c25f1fb68a94d5c7008b98630de45d48b6)
> Back-port GEODE-9380 to 1.13

- geode-core/src/main/java/org/apache/geode/internal/net/NioSslEngine.java
- geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
(cherry picked from commit 1b97c7c25f1fb68a94d5c7008b98630de45d48b6)
> Back-port GEODE-9380 to 1.12

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/LatestLastAccessTimeMessageDistributedTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/LatestLastAccessTimeMessage.java
- geode-core/src/test/java/org/apache/geode/internal/cache/LatestLastAccessTimeMessageTest.java
> Feature/geode 9295 1.12

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ha/HAGIIDUnitTest.java
- geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
- geode-core/src/main/java/org/apache/geode/distributed/internal/ReliableReplyProcessor21.java
- geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/CommitReplyException.java
- geode-core/src/main/java/org/apache/geode/internal/cache/CountingDataInputStream.java
- geode-core/src/main/java/org/apache/geode/internal/cache/DiskInitFile.java
- geode-core/src/main/java/org/apache/geode/internal/cache/DiskRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java
- geode-core/src/main/java/org/apache/geode/internal/cache/DistributedTombstoneOperation.java
- geode-core/src/main/java/org/apache/geode/internal/cache/InitialImageOperation.java
- geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/Oplog.java
- geode-core/src/main/java/org/apache/geode/internal/cache/PersistentOplogSet.java
- geode-core/src/main/java/org/apache/geode/internal/cache/TXCommitMessage.java
- geode-core/src/main/java/org/apache/geode/internal/cache/TXEntryState.java
- geode-core/src/main/java/org/apache/geode/internal/cache/TXRegionState.java
- geode-core/src/main/java/org/apache/geode/internal/cache/TombstoneService.java
- geode-core/src/main/java/org/apache/geode/internal/cache/persistence/CanonicalIdHolder.java
- geode-core/src/main/java/org/apache/geode/internal/cache/persistence/DiskInitFileInterpreter.java
- geode-core/src/main/java/org/apache/geode/internal/cache/persistence/DiskInitFileParser.java
- geode-core/src/main/java/org/apache/geode/internal/cache/persistence/DiskRegionView.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/BaseCommandQuery.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientUpdater.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientTombstoneMessage.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientUpdateMessageImpl.java
- geode-core/src/test/java/org/apache/geode/internal/DataSerializableJUnitTest.java
- geode-serialization/src/main/java/org/apache/geode/internal/serialization/KnownVersion.java
The PR is intentionally broken into multiple commits. The work to just remove the version is in the first commit. 
The followup commits are to cleanup all the compiler and static analyzer warnings in the changed files.
> GEODE-8870: Removes GFE_70.

- .asf.yaml
- The merge button is disabled in the PRs
> Enabling only rebase and squash buttons

- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractSubCommandsIntegrationTest.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PubSubExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/StringBytesGlossary.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSub.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSubImpl.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/Subscriptions.java
> GEODE-9205: Implement Radish PUBSUB NUMPAT subcommand

- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/server/MemoryStatsNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractRedisMemoryStatsIntegrationTest.java
- rename test to be more specific
- increase size of data added in test
- remove unused fields and methods
(cherry picked from commit 6d5398747871a5c27c1eb936b299ba311a1444c1)
> GEODE-9006: fix flaky native Redis memory usage test (#6456)

- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
- geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContextTest.java
> GEODE-9411: Do not close channel on IOException processing Redis command

- geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxy.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/GetAll70.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySenderEventProcessor.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/GatewaySenderEventImpl.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ConcurrentParallelGatewaySenderEventProcessor.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderEventProcessor.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueue.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/ConcurrentSerialGatewaySenderEventProcessor.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderEventProcessor.java
- geode-core/src/test/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueueJUnitTest.java
- geode-serialization/src/main/java/org/apache/geode/internal/serialization/KnownVersion.java
- geode-wan/src/main/java/org/apache/geode/cache/wan/internal/parallel/RemoteConcurrentParallelGatewaySenderEventProcessor.java
- geode-wan/src/main/java/org/apache/geode/cache/wan/internal/parallel/RemoteParallelGatewaySenderEventProcessor.java
> GEODE-8870: Removes GFE_701.

- geode-core/src/main/java/org/apache/geode/pdx/internal/json/PdxToJSON.java
- geode-core/src/test/java/org/apache/geode/pdx/internal/json/PdxToJSONTest.java
- geode-web-api/src/main/java/org/apache/geode/rest/internal/web/util/JsonWriter.java
- geode-web-api/src/test/java/org/apache/geode/rest/internal/web/util/JsonWriterTest.java
> GEODE-9384: Fix exception messages in PdxToJSON and JsonWriter

- geode-core/src/main/java/org/apache/geode/distributed/internal/AbstractDistributionConfig.java
- geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionConfigJUnitTest.java
`testCheckerChecksValidAttribute` in `DistributionConfigJUnitTest` has a "TODO" comment about a missing check in the test.
I have also changed JUnit asserts by AssertJ asserts, which are more descriptives in case of error.
> GEODE-9209: Complete test in DistributionConfigJUnitTest

- geode-serialization/src/main/java/org/apache/geode/internal/serialization/KnownVersion.java
> GEODE-8870: Removes GFE_7099

- CODEOWNERS
- Sarah will no longer be focusing on Geode, so remove her as a
codeowner
> Remove sabbey37 from codeowners

- ci/scripts/capture-call-stacks.sh
Change `ci/scripts/capture-call-stacks.sh` to capture call stacks from
both Dockerized and non-Dockerized Java processes, regardless of the
value of `PARALLEL_DUNIT`.
If `jps` reports any processes, capture their call stacks. If `docker
ps` reports any Docker containers, capture the call stacks of all Java
processes running in those containers.
This ensures that we capture all call stacks from all lingering Java
test worker processes, regardless of whether the workers were run in
Docker containers.
Co-authored-by: Dale Emery <demery@vmware.com>
> GEODE-9462: Capture call stacks from all sources

- settings.gradle
> add 1.12.4 to old versions on develop

- geode-core/src/main/java/org/apache/geode/cache/client/internal/AuthenticateUserOp.java
- geode-core/src/main/java/org/apache/geode/cache/client/internal/OpExecutorImpl.java
- geode-core/src/main/java/org/apache/geode/cache/client/internal/PoolImpl.java
- geode-core/src/main/java/org/apache/geode/cache/client/internal/UserAttributes.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientProxyMembershipID.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientUserAuths.java
- geode-core/src/test/java/org/apache/geode/cache/client/internal/TXFailoverOpTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientProxyMembershipIDTest.java
While spending some time in multi-user auth I cleaned up some of the classes I was spending time in understanding.
> GEODE-6588: Cleanup multi-user auth.

- geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
- geode-core/src/main/java/org/apache/geode/distributed/DistributedMember.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/membership/InternalDistributedMember.java
- geode-core/src/main/java/org/apache/geode/internal/cache/FilterRoutingInfo.java
- geode-membership/build.gradle
- geode-membership/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
- geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/api/MemberIdentifier.java
- geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/MemberIdentifierImpl.java
- geode-serialization/src/main/java/org/apache/geode/internal/serialization/KnownVersion.java
- geode-serialization/src/main/java/org/apache/geode/internal/serialization/SerializationVersions.java
> GEODE-8870: Removes GFE_71

- ci/pipelines/shared/jinja.variables.yml
- settings.gradle
> add 1.13.4 to old versions and set as Benchmarks baseline on develop

- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/sortedset/ZPopMaxNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZPopMaxIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/ZPopMaxIntegrationTest.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSortedSet.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSetCommandsFunctionExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/RedisSortedSetCommands.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZPopMaxExecutor.java
- geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java
- geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSortedSetTest.java
> GEODE-9185: Add ZPOPMAX Radish command

- geode-assembly/src/upgradeTest/java/org/apache/geode/rest/internal/web/controllers/RestAPICompatibilityTest.java
PROBLEM
A `RestAPICompatibilityTest` backward compatibility test assumed that
two ephemeral ports would remain available while not in use. The test:
1. Launched two locators, each on an ephemeral port.
2. Stopped each locator.
3. Restarted each locator on its original (ephemeral) port.
In between steps 2 and 3, some other process can bind to the port,
causing the restart to fail.
SOLUTION
Change the test to assign a non-ephemeral port to each locator.
> GEODE-9491: Fix REST API test use of ephemeral ports

- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/functions/RegionCreateFunction.java
- geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/functions/RegionCreateFunctionJUnitTest.java
> GEODE-9409: wait for PdxRegistry before executing create region

- CODEOWNERS
> made dschneider code owner of redis apis

- geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/NativeRedisClusterTestRule.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionDUnitTest.java
> GEODE-9490: Correctly ignore RedisProxy exceptions in NativeRedisClusterTestRule

- geode-core/src/main/java/org/apache/geode/cache/client/internal/QueryOp.java
- geode-core/src/main/java/org/apache/geode/internal/lang/SystemPropertyHelper.java
- geode-core/src/test/java/org/apache/geode/internal/lang/SystemPropertyHelperTest.java
> GEODE-9496: Enhance the usage of newly introduced system property

- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction70.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunction66.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunctionSingleHop.java
- geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/RegisterInterest61Test.java
- geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/RegisterInterestList66Test.java
- geode-serialization/src/main/java/org/apache/geode/internal/serialization/KnownVersion.java
> GEODE-8870: Removes GFE_8009

- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/sortedset/ZLexCountNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZLexCountIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/ZLexCountIntegrationTest.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSortedSet.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSetCommandsFunctionExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/RedisSortedSetCommands.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/SortedSetLexRangeOptions.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZLexCountExecutor.java
- geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java
- geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSortedSetTest.java
> GEODE-9184: Add Radish ZLEXCOUNT command

- ci/pipelines/geode-build/jinja.template.yml
> GEODE-9525: Add Radish benchmarks to CI - with fix

- ci/pipelines/shared/jinja.variables.yml
> GEODE-9525: Add Radish benchmarks to CI - fix 2

- geode-core/src/integrationTest/java/org/apache/geode/management/internal/ManagementAgentIntegrationTest.java
- geode-core/src/main/java/org/apache/geode/management/internal/ManagementAgent.java
- geode-core/src/test/java/org/apache/geode/management/internal/ManagementAgentTest.java
> GEODE-9515: Skip setting MBeanServer when JMXConnectorServer will set it

- geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/NativeRedisTestRule.java
> GEODE-9442: Add logging when Native Redis container is stopped

- geode-core/src/upgradeTest/java/org/apache/geode/security/AuthExpirationDUnitTest.java
- geode-core/src/upgradeTest/java/org/apache/geode/security/AuthExpirationFunctionDUnitTest.java
- geode-junit/src/main/java/org/apache/geode/security/UpdatableUserAuthInitialize.java
> GEODE-9458: function execution with expiring authentication

- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/connection/EchoNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/AbstractEchoIntegrationTest.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/connection/EchoExecutor.java
- Move ECHO command to supported commands
- Refactor tests to use cluster mode
- Minor refactor for cleaner code
> GEODE-9560: Implement Radish ECHO command

- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractSubCommandsIntegrationTest.java
- Jedis does not track psubscribe and subscribe requests separately.
Thus a psubscribe followed by unsubscribe, (when no subscribes exist),
will cause the client to think everything is unsubscribed and
disconnect the MockSubscriber. This makes cleanup in a generic way
difficult, if not impossible. Now, instead of trying to clean up in
`@After`, each test does its own cleanup.
> GEODE-9541: Explicitly unsubscribe after each test in SubCommandsIntegrationTest

- geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/CqQueryUsingPoolDUnitTest.java
> GEODE-9537: Ensure that servers do not start on ephemeral ports

- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/parameters/ClusterParameterRequirements.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/parameters/EvenParameterRequirements.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/parameters/ExactParameterRequirements.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/parameters/MaximumParameterRequirements.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/parameters/MinimumParameterRequirements.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/parameters/MultipleParameterRequirements.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/parameters/OddParameterRequirements.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/parameters/ParameterRequirements.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/parameters/RedisParametersMismatchException.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/parameters/SlowlogParameterRequirements.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/parameters/SpopParameterRequirements.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/parameters/UnspecifiedParameterRequirements.java
- geode-apis-compatible-with-redis/src/main/resources/org/apache/geode/redis/internal/sanctioned-geode-apis-compatible-with-redis-serializables.txt
> GEODE-9564: Rename package from ParameterRequirements to parameters

- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/sortedset/ZUnionStoreNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/ConcurrentLoopingThreads.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/RedisCommandArgumentsTestHelper.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/AbstractSUnionIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZUnionStoreIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/ZUnionStoreIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RegionProvider.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSortedSet.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisDataCommandsFunctionExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisKeyCommandsFunctionExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSetCommandsFunctionExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisResponse.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/RedisSortedSetCommands.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZAggregator.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZKeyWeight.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZUnionStoreExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/StringBytesGlossary.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/services/StripedCoordinator.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/services/SynchronizedStripedCoordinator.java
- geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/executor/SynchronizedStripedCoordinatorTest.java
- Add ability to lock multiple keys in a consistent order
- Add validation option to ConcurrentLoopingThreads
- Add CROSSSLOTS error message
> GEODE-9518: Implement Radish ZUNIONSTORE command

- CODEOWNERS
> Add kirklund to more CODEOWNER areas

- geode-experimental-driver/src/integrationTest/java/org/apache/geode/experimental/driver/SSLTest.java
> GEODE-9527: Use TLS v 1.2 in test

- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/sortedset/ZRemRangeByRankNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/sortedset/ZRemRangeByRankDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/sortedset/ZRemRangeByScoreDUnitTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZRemRangeByRankIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/ZRemRangeByRankIntegrationTest.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSortedSet.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSetCommandsFunctionExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/RedisSortedSetCommands.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZRemRangeByRankExecutor.java
Adds support for the Redis ZREMRANGEBYRANK command with associated tests.
> GEODE-9435: Implement ZREMRANGEBYRANK

- ci/pipelines/shared/jinja.variables.yml
- settings.gradle
> add 1.14.0 to old versions and set as Benchmarks baseline on develop

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/control/RebalanceOperationComplexDistributedTest.java
- geode-core/src/distributedTest/resources/org/apache/geode/internal/cache/RebalanceOperationComplex-client.xml
- geode-core/src/distributedTest/resources/org/apache/geode/internal/cache/RebalanceOperationComplex-server.xml
- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionDataStore.java
- geode-core/src/main/java/org/apache/geode/internal/cache/control/PartitionRebalanceDetailsImpl.java
- geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PartitionedRegionRebalanceOp.java
- geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/rebalance/model/Member.java
- geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/rebalance/model/PartitionedRegionLoadModel.java
- geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/rebalance/model/RefusalReason.java
- geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/rebalance/MemberTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/rebalance/PartitionedRegionLoadModelJUnitTest.java
If there is no redundancy zone, exit and allow delete
Adding xml files to git
Adding xml files to git
Added new tests
Move change from support/1.12
> GEODE-9554: Change up the rebalance calls to use new canDelete call

- geode-apis-compatible-with-redis/README.md
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AbstractPSetEXIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AbstractSetEXIntegrationTest.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/string/SetEXExecutor.java
> GEODE-9577: Make PSETEX and SETEX supported commands

- geode-core/src/main/java/org/apache/geode/internal/tcp/BaseMsgStreamer.java
- geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
- geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java
- geode-core/src/main/java/org/apache/geode/internal/tcp/MsgStreamer.java
- geode-core/src/main/java/org/apache/geode/internal/tcp/MsgStreamerList.java
- geode-core/src/main/java/org/apache/geode/internal/tcp/VersionedMsgStreamer.java
- geode-core/src/test/java/org/apache/geode/internal/tcp/ConnectionTest.java
- geode-serialization/build.gradle
- geode-serialization/src/main/java/org/apache/geode/internal/serialization/VersionedDataStream.java
* Cleanup Connection and related classes.
> GEODE-6588: Cleanup Connection

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/control/RebalanceOperationComplexDistributedTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/rebalance/model/Member.java
- geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/rebalance/PartitionedRegionLoadModelJUnitTest.java
Added some additional cleanup from a late review.
> GEODE-5994: Cleanup from some additional review comments

- geode-apis-compatible-with-redis/README.md
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/string/StringsDUnitTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AbstractSetRangeIntegrationTest.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisStringQuickCheckTest.java
> GEODE-9589: Support SETRANGE command

- ci/scripts/execute_redis_tests.sh
- geode-apis-compatible-with-redis/README.md
- geode-apis-compatible-with-redis/build.gradle
- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/connection/AuthNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch
- geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/GeodeRedisServerRule.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/AbstractAuthIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/AuthIntegrationTest.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisResponse.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/connection/AuthExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/NettyRedisServer.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/StringBytesGlossary.java
- geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/AbstractDistributionConfig.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfigImpl.java
- geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/StartServerCommand.java
> GEODE-9546: Integrate Security Manager into Radish AUTH flow

- geode-core/src/integrationTest/java/org/apache/geode/management/internal/security/SecurityWithExpirationIntegrationTest.java
- geode-core/src/upgradeTest/java/org/apache/geode/security/AuthExpirationDUnitTest.java
- geode-core/src/upgradeTest/java/org/apache/geode/security/AuthExpirationFunctionDUnitTest.java
- geode-core/src/upgradeTest/java/org/apache/geode/security/AuthExpirationMultiServerDUnitTest.java
- geode-junit/src/main/java/org/apache/geode/security/ExpirableSecurityManager.java
- geode-junit/src/main/resources/org/apache/geode/test/junit/internal/sanctioned-geode-junit-serializables.txt
* remove the static methods in ExpirableSecurityManager
> GEODE-9521: add more multi-server test scenario

- ci/scripts/execute_redis_tests.sh
- geode-apis-compatible-with-redis/README.md
- geode-apis-compatible-with-redis/build.gradle
- geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/connection/AuthNativeRedisAcceptanceTest.java
- geode-apis-compatible-with-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch
- geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/GeodeRedisServerRule.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/AbstractAuthIntegrationTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/AuthIntegrationTest.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisResponse.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/connection/AuthExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/NettyRedisServer.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/StringBytesGlossary.java
- geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/AbstractDistributionConfig.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfigImpl.java
- geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/StartServerCommand.java
This reverts commit b97370facd0b02307a3562e312fbc08945a86956.
> Revert "Revert "GEODE-9546: Integrate Security Manager into Radish AUTH flow (#6844)" (#6864)"

- geode-dunit/src/main/java/org/apache/geode/cache30/MultiVMRegionTestCase.java
> GEODE-9583: Flush the disk stores before unregistering all serializers

- geode-core/src/upgradeTest/java/org/apache/geode/security/AuthExpirationDUnitTest.java
- geode-core/src/upgradeTest/java/org/apache/geode/security/AuthExpirationFunctionDUnitTest.java
- geode-core/src/upgradeTest/java/org/apache/geode/security/AuthExpirationMultiServerDUnitTest.java
- geode-core/src/upgradeTest/java/org/apache/geode/security/ClientAuthenticationTestUtils.java
Added multi server testing
Exercise all client executable FunctionService interfaces
> GEODE-9458: Enhance function execution testing auth expiry

- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/KeyHashUtil.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/connection/SelectExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/SortedSetLexRangeOptions.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/SortedSetScoreRangeOptions.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
This PR opened to address additional feedback that was left after the original PR (#6872) was merged.
> GEODE-9605: Remove unnecessary casts to byte

- geode-core/src/integrationTest/java/org/apache/geode/internal/cache/ha/BlockingHARegionJUnitTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/HARegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/ha/HARegionQueue.java
> GEODE-9365: Removing unnecessary synchronization

- geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
- geode-docs/developing/geode_apis_compatible_with_redis.html.md.erb
> GEODE-9566: Radish is not experimental

- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxy.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientUserAuths.java
- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java
- geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxyTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientUserAuthsTest.java
- geode-core/src/upgradeTest/java/org/apache/geode/security/AuthExpirationDUnitTest.java
- geode-core/src/upgradeTest/java/org/apache/geode/security/AuthExpirationFunctionDUnitTest.java
- geode-core/src/upgradeTest/java/org/apache/geode/security/AuthExpirationMultiServerDUnitTest.java
- geode-core/src/upgradeTest/java/org/apache/geode/security/ClientAuthenticationTestUtils.java
- geode-junit/src/main/java/org/apache/geode/security/ExpirableSecurityManager.java
- geode-junit/src/main/java/org/apache/geode/security/UpdatableUserAuthInitialize.java
* add more tests
* minor refactor
Most of this PR is adding tests, with minor refactor in `ClientUserAuth`
> GEODE-9570: make sure re-authentication works with registered interests

- geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RestoreRedundancyManagementDUnitTest.java
- geode-core/src/main/java/org/apache/geode/management/internal/operation/OperationHistoryManager.java
- geode-core/src/main/java/org/apache/geode/management/internal/operation/OperationState.java
- geode-core/src/test/java/org/apache/geode/management/internal/operation/OperationHistoryManagerTest.java
- geode-core/src/test/java/org/apache/geode/management/internal/operation/OperationStateTest.java
After checking locator presence store the status in OperationStateStore
> GEODE-8200: After checking locator presence store the status in OperationStateStore

- geode-apis-compatible-with-redis/README.md
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/string/MSetDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/string/MSetNXDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/string/MSetnxDUnitTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AbstractMSetNXIntegrationTest.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisStringCommandsFunctionExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/key/AbstractRenameExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/string/AbstractMSetExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/string/MSetExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/string/MSetNXExecutor.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/string/RedisStringCommands.java
> GEODE-9587: Support MSETNX command

- geode-apis-compatible-with-redis/build.gradle
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/key/AbstractRenameRedirectionsDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/key/NativeRedisRenameRedirectionsDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/key/RadishRenameRedirectionsDUnitTest.java
- geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/key/RenameDUnitTest.java
- geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/key/AbstractRenameExecutor.java
> GEODE-9665 Fix multiple redirections in RENAME and RENAMENX

- settings.gradle
> add 1.12.5 to old versions on develop

- ci/pipelines/mass-test-run/jinja.template.yml
> [GEODE-9775] Add heavy-lifter variables to mass-test.

- geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/sortedset/ZAddIncrOptionDUnitTest.java
> GEODE-9671: fixed test's expectations

- geode-for-redis/src/main/java/org/apache/geode/redis/internal/PassiveExpirationManager.java
> GEODE-9794: Radish PassiveExpirationManager can throw NPE

- geode-docs/managing/security/authentication_examples.html.md.erb
- geode-docs/managing/security/implementing_authentication.html.md.erb
> GEODE-9797: User guide typo repairs

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- geode-assembly/src/integrationTest/resources/assembly_content.txt
- geode-assembly/src/integrationTest/resources/dependency_classpath.txt
don't merge until after #7031, #7032
> GEODE-9767: Bump netty from 4.1.48.Final to 4.1.68.Final

- ci/pipelines/meta/deploy_meta.sh
- ci/pipelines/meta/jinja.template.yml
> Add required pipeline path dependencies

- geode-core/src/integrationTest/java/org/apache/geode/cache/query/functional/LimitClauseJUnitTest.java
- geode-core/src/integrationTest/java/org/apache/geode/cache/query/functional/NonDistinctOrderByReplicatedJUnitTest.java
- geode-core/src/integrationTest/java/org/apache/geode/cache/query/functional/OrderByReplicatedJUnitTest.java
- geode-core/src/main/java/org/apache/geode/cache/query/internal/AbstractGroupOrRangeJunction.java
- geode-core/src/main/java/org/apache/geode/cache/query/internal/QueryUtils.java
- geode-core/src/main/java/org/apache/geode/cache/query/internal/index/CompactRangeIndex.java
- geode-core/src/main/java/org/apache/geode/cache/query/internal/index/HashIndex.java
- geode-core/src/main/java/org/apache/geode/cache/query/internal/index/IndexManager.java
- geode-core/src/main/java/org/apache/geode/cache/query/internal/index/PrimaryKeyIndex.java
- geode-core/src/main/java/org/apache/geode/cache/query/internal/index/RangeIndex.java
- geode-cq/src/distributedTest/java/org/apache/geode/cache/query/dunit/QueryWithRangeIndexDUnitTest.java
> GEODE-9632: Allow INDEX_THRESHOLD_SIZE System property to override CompiledValue.RESULT_LIMIT

- CODEOWNERS
Assign @kirklund and @jchen21 as codeowners for serialization filtering.
> Add codeowners for serialization filtering

- geode-common/build.gradle
- geode-common/src/main/java/org/apache/geode/internal/version/ComponentVersion.java
- geode-common/src/main/java/org/apache/geode/internal/version/DistributionVersion.java
- geode-core/src/integrationTest/java/org/apache/geode/internal/util/ProductVersionUtilTest.java
- geode-core/src/integrationTest/resources/META-INF/services/org.apache.geode.internal.version.ComponentVersion
- geode-core/src/integrationTest/resources/META-INF/services/org.apache.geode.internal.version.DistributionVersion
- geode-core/src/main/java/org/apache/geode/internal/GemFireVersion.java
- geode-core/src/main/java/org/apache/geode/internal/GeodeVersion.java
- geode-core/src/main/java/org/apache/geode/internal/SystemDescription.java
- geode-core/src/main/java/org/apache/geode/internal/VersionDescription.java
- geode-core/src/main/java/org/apache/geode/internal/logging/Banner.java
- geode-core/src/main/java/org/apache/geode/internal/util/ProductVersionUtil.java
- geode-core/src/main/resources/META-INF/services/org.apache.geode.internal.version.ComponentVersion
- geode-core/src/test/java/org/apache/geode/internal/logging/BannerTest.java
- geode-core/src/test/java/org/apache/geode/internal/util/ProductVersionUtilTest.java
- geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/VersionCommandJUnitTest.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/Launcher.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/shell/Gfsh.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/web/http/support/HttpRequester.java
> GEODE-9793: Implementation of Version Interfaces

- geode-for-redis/README.md
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractPubSubIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractInfoIntegrationTest.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/server/InfoExecutor.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/statistics/RedisStats.java
added pubsub_channels and pubsub_patterns to stats section of info command
> GEODE-9769: add pubsub stats to INFO

- geode-for-redis/src/commonTest/java/org/apache/geode/redis/NativeRedisClusterTestRule.java
> GEODE-9821: Remove use of local docker-compose from Radish native tests

- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/shell/Gfsh.java
> GEODE-9793: Fix duplicate 'Running on' in gfsh version --full

- geode-core/src/main/java/org/apache/geode/internal/cache/ProxyBucketRegion.java
- geode-core/src/test/java/org/apache/geode/internal/cache/ProxyBucketRegionTest.java
> GEODE-9806: added skip recovery of recovered bucket

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableRegistrationDUnitTest.java
> GEODE-1537: Re-order ephemeral port acquisition to fix flaky DurableRegistrationDUnitTest

- geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/index/IndexManagerIntegrationTest.java
- geode-core/src/main/java/org/apache/geode/cache/query/internal/index/IndexManager.java
> GEODE-9838: Log key info for deserialization issue while index update

- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/CommandIntegrationTest.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/server/COMMANDCommandExecutor.java
> GEODE-9727: Updated COMMAND error message

- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/cluster/AbstractClusterIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/cluster/ClusterIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/AbstractClientIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/ClientIntegrationTest.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/cluster/ClusterExecutor.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/connection/ClientExecutor.java
> GEOGE-9823: CLUSTER & CLIENT error messages list supported subcommands.

- geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/P2PMessagingConcurrencyDUnitTest.java
- geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
- geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedExecutorServiceRuleLimitedThreadCountTest.java
- geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedExecutorServiceRuleLimitedVmCountTest.java
- geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedExecutorServiceRuleUnlimitedThreadCountTest.java
- geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedExecutorServiceRule.java
- geode-dunit/src/main/resources/org/apache/geode/test/dunit/internal/sanctioned-geode-dunit-serializables.txt
- geode-junit/src/main/java/org/apache/geode/test/junit/rules/ExecutorServiceRule.java
- geode-junit/src/main/resources/org/apache/geode/test/junit/internal/sanctioned-geode-junit-serializables.txt
This PR will be rebased onto support/1.13. It has two cherry-picked commits.
> GEODE-9825: Back-Port to 1.13

- geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/P2PMessagingConcurrencyDUnitTest.java
- geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
This PR will be rebased onto support/1.12. It has two cherry-picked commits.
> GEODE-9825: Back-Port to 1.12

- geode-dunit/src/main/java/org/apache/geode/management/internal/cli/commands/GcCommandDistributedTestBase.java
- geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/GcCommandDistributedTest.java
- geode-web/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/GcCommandOverHttpDistributedTest.java
> GEODE-9709: Clean up GcCommandDUnitTestBase

- geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/SerializableFunction.java
- geode-for-redis/src/commonTest/java/org/apache/geode/test/dunit/rules/RedisClusterStartupRule.java
- geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/auth/AuthWhileServersRestartDUnitTest.java
> GEODE-9855: Radish authentication during HA test

- geode-docs/tools_modules/geode_for_redis.html.md.erb
- geode-for-redis/README.md
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSDiffIntegrationTest.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/RedisCommandType.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/set/SetOpExecutor.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
> GEODE-9827: SDIFF command supported

- geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerImplTest.java
- geode-core/src/main/java/org/apache/geode/cache/client/internal/pooling/ConnectionManagerImpl.java
> GEODE-9865: Decrement the count if the connection is unsuccessful

- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/AbstractRedisMemoryStatsIntegrationTest.java
- Just use SET to create a bunch of content
> GEODE-9866: Improvements to AbstractRedisMemoryStatsIntegrationTest

- geode-docs/tools_modules/geode_for_redis.html.md.erb
- geode-for-redis/README.md
- geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/commands/executor/set/SCardNativeRedisAcceptanceTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSCardIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSetsIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/SCardIntegrationTest.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/RedisCommandType.java
> GEODE-9826: SCARD command supported

- geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImplJUnitTest.java
- geode-core/src/main/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImpl.java
> GEODE-9808: Throw appropriate exception in AutoConnectionSourceImpl

- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/AbstractRedisInfoStatsIntegrationTest.java
> GEODE-9871: Improve Radish test for network KB/s verification

- geode-docs/tools_modules/micrometer/micrometer-meters.html.md.erb
> GEODE-9882: User Guide, Micrometer section, fix product_name typo

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/versions/TombstoneDUnitTest.java
> GEODE-9850: resolve the flaky test in getting the oldest tombstone

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/persistence/PersistentRecoveryOrderDUnitTest.java
> GEODE-9770: Retry creating region when cache is closed

- .asf.yaml
> Enable LGTM as PR-gating checks

- geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/sortedset/ZRemRangeByScoreDUnitTest.java
Just a smidge extra logging to help track this error down if it happens again.
> GEODE-9716: Add extra info to error message for assert

- NOTICE
- geode-assembly/src/main/dist/NOTICE
- geode-pulse/src/main/webapp/META-INF/NOTICE
- geode-web-api/src/main/webapp/META-INF/NOTICE
- geode-web-management/src/main/webapp/META-INF/NOTICE
- geode-web/src/main/webapp/META-INF/NOTICE
> Bump copyright year to 2022

- geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/ProcessManager.java
> GEODE-9912: Add unique identifier to DUnit log lines

- geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/hash/HashesAndCrashesDUnitTest.java
> GEODE-9692: Enable tests in HashesAndCrashesDUnitTest

- geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/sortedset/ZRemDUnitTest.java
- Adjust expectation and ensure that no ephemeral ports are used for
restarted VMs.
> GEODE-9691: Fix flaky ZRemDUnitTest

- buildSrc/src/main/resources/japicmp_exceptions.json
- geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementOperation.java
> GEODE-9930: Mark ClusterManagementOperation @Experimental

- geode-core/src/distributedTest/java/org/apache/geode/management/CacheManagementDUnitTest.java
> GEODE-7934: Use thread safe list type.

- geode-docs/tools_modules/geode_for_redis.html.md.erb
- geode-for-redis/README.md
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSMoveIntegrationTest.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/RedisCommandType.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/set/SMoveExecutor.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
> feature/GEODE-9832: SMOVE Command Support

- ci/bin/concourse_job_performance.py
- ci/pipelines/mass-test-run/jinja.template.yml
- dev-tools/release/deploy_rc_pipeline.sh
* fix mass test report trigger
* fix mass test report hang
* fix rc pipeline to trigger right the first time
> GEODE-9940: ci improvements

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/control/RebalanceOperationComplexDistributedTest.java
- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/control/RebalanceOperationComplexPart2DistributedTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/rebalance/model/Member.java
- geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/rebalance/model/PartitionedRegionLoadModel.java
- geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/rebalance/PartitionedRegionLoadModelJUnitTest.java
Just testing the changes against the pipeline at this point.
> GEODE-9815: Prefer to remove a redundant copy in the same zone

- build.gradle
- buildSrc/build.gradle
> Fix for jcenter shutdown.

- geode-core/src/main/java/org/apache/geode/internal/net/filewatch/FileWatchingX509ExtendedKeyManager.java
- geode-core/src/main/java/org/apache/geode/internal/net/filewatch/FileWatchingX509ExtendedTrustManager.java
> GEODE-9937: Add convenience methods to FileWatchingX509Extended*Manager

- geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
- geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionTest.java
> GEODE-9913: Added basicBridgePut condition to ensure VersionTag set

- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSDiffIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSDiffStoreIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSInterIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/sortedset/AbstractZInterStoreIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/sortedset/AbstractZUnionStoreIntegrationTest.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
> GEODE-9936: Modified multi-key commands for wrong type key

- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/GatewayReceiverCommand.java
- geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/GatewayReceiverCommandTest.java
> GEODE-9961: GatewayReceiver catch CancelException

- settings.gradle
> add 1.13.7 to old versions on develop

- geode-docs/managing/monitor_tune/socket_communication_have_enough_sockets.html.md.erb
> GEODE-9973: Correct docs regarding P2P socket timeout behaviour

- geode-assembly/src/upgradeTest/java/org/apache/geode/management/internal/cli/commands/ConnectCommandUpgradeTest.java
* Previously the tests only checked with 1.3.0 version of locator
* The test now checks the behavior of the all the versions
* New version gfsh could not connect with locators versions below 1.10.0
* New version gfsh are now able to connect with locators 1.10.0 and above.
* This is now reflected in the test.
* Previously a race condition between the execution of the two scripts caused the second script to be executed before the locator startup had completed.
* Now the locator is started using the cluster startup rule.
> GEODE-6751: Improved the tests for locator-gfsh compatibility

- geode-core/src/distributedTest/java/org/apache/geode/cache30/ClientServerCacheOperationDUnitTest.java
* Re-enabling the windows test.
* Refactored to remove the deprecated APIs
> GEODE-8616: Refactoring the test to remove deprecated APIs

- geode-assembly/src/acceptanceTest/java/org/apache/geode/cache/persistence/MissingDiskStoreAfterServerRestartAcceptanceTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionHelper.java
- geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionHelperJUnitTest.java
> GEODE-9969: Fix unescaping the region name with underscore

- ci/pipelines/shared/jinja.variables.yml
- settings.gradle
> add 1.14.3 to old versions and set as Benchmarks baseline on develop

- geode-book/master_middleman/source/subnavs/geode-subnav.erb
- geode-docs/tools_modules/geode_for_redis.html.md.erb
> GEODE-9883 Update Geode for Redis docs file

- geode-core/src/main/java/org/apache/geode/internal/cache/BucketAdvisor.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ConcurrentParallelGatewaySenderEventProcessor.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueue.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelQueueRemovalMessage.java
- geode-core/src/test/java/org/apache/geode/internal/cache/BucketAdvisorTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/wan/parallel/ParallelQueueRemovalMessageJUnitTest.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderOperationsDUnitTest.java
> GEODE-9853: get all members hosting bucket

- geode-for-redis/README.md
- geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/commands/executor/set/SInterStoreNativeRedisAcceptanceTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSInterIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSInterStoreIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/SInterStoreIntegrationTest.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/RedisCommandType.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/set/SDiffExecutor.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/set/SDiffStoreExecutor.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/set/SInterExecutor.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/set/SInterStoreExecutor.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/set/SUnionExecutor.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/set/SetOpExecutor.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
> GEODE-9830: SINTERSTORE Command Support

- geode-core/src/main/java/org/apache/geode/internal/jndi/JNDIInvoker.java
> GEODE-9988: Log full exception when JNDI binding fails during cache creation

- geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/string/MSetNXDUnitTest.java
The previous fix for GEODE-9604 fixed MSetDUnitTest, but MSetNXDUnitTest needs the fix as well.
> GEODE-9604 Also fix MSetNXDUnitTest

- dev-tools/release-testing/README.md
- dev-tools/release-testing/smoketest_rc.sh
- dev-tools/release/smoketest_rc.sh
This script currently
- downloads all packages
- validates the signatures
- verifies that the source tag matches the source release
- builds from the source releases of everything but native client
> Adding a script which performs validation of a release candidate

- geode-for-redis/README.md
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSPopIntegrationTest.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/RedisCommandType.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/set/SPopExecutor.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/set/SRandMemberExecutor.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/set/SetRandomExecutor.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSet.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/collections/SizeableObjectOpenCustomHashSetWithCursor.java
> GEODE-9833: SPOP Command Support

- geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/QueueManagerJUnitTest.java
- geode-core/src/main/java/org/apache/geode/cache/client/internal/QueueManagerImpl.java
> GEODE-10009: Invoked internalClose with keepAlive true

- geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxy.java
We got a NPE message without getting the entire stack trace of the NPE.
> GEODE-10022: fix the logging to log the entire stack trace.

- dev-tools/release/commit_rc.sh
- dev-tools/release/create_support_branches.sh
- dev-tools/release/prepare_rc.sh
- dev-tools/release/promote_rc.sh
- dev-tools/release/set_copyright.sh
- dev-tools/release/set_versions.sh
to comply with Geode commit message standards
> GEODE-10019: prefix all release-related commits with a JIRA ticket

- geode-for-redis/src/distributedTest/java/org/apache/geode/redis/OutOfMemoryDUnitTest.java
- Add larger values to get over critical memory threshold faster and
make it more likely to stay there
- Force GC before each attempt to add a large value to make it less
likely that we'll drop back below critical threshold due to small
objects being GCd while over critical threshold
> GEODE-10052: Fix flakiness in OutOfMemoryDUnitTest

- geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
Only logging message is added for future debug
> GEODE-10092: add more logging for future debug when region size gets below 0.

- extensions/geode-modules-test/src/main/java/org/apache/geode/modules/session/catalina/AbstractDeltaSessionIntegrationTest.java
- extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/DeltaSession.java
> GEODE-10093 - Fixed attr issue in Delta Session

- extensions/geode-modules-test/src/main/java/org/apache/geode/modules/session/catalina/AbstractDeltaSessionIntegrationTest.java
- extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/DeltaSession.java
* GEODE-10093 - Fixed attr issue in Delta Session
(cherry picked from commit e040759cd1e42df377501cd423967d549ce2bfab)
> GEODE-10093 - Fixed attr issue in Delta Session (#7405)

- ci/pipelines/pull-request/jinja.template.yml
- ci/scripts/repeat-new-tests.sh
- ci/scripts/shared_utilities.sh
> change CI to use merge not rebase

- geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/InternalDistributedSystemBuilderIntegrationTest.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java
> GEODE-9910: Stopped embedded locator after failed start

- geode-core/src/test/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImplTest.java
> GEODE-10066: Disables test.

- settings.gradle
Adds 1.12.9 to old versions on develop
> GEODE-10099: Add 1.12.9 as old version

- geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
- geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionTest.java
* When creating indexes on bucket region failed with an exception,
geode only logs the exception to indicate an index creation failed
without throwing the exception to the caller.
* IndexManager can be null if bucket region is destroyed due to cache
is closing. In this case, checkReadiness is invoked to make sure
CacheClosedException is thrown and logged instead of NullPointerException.
> GEODE-10114: Always checkReadiness if indexManager is null

- geode-core/src/integrationTest/java/org/apache/geode/internal/cache/TombstoneCreationJUnitTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegionMap.java
- geode-core/src/main/java/org/apache/geode/internal/cache/ProxyRegionMap.java
- geode-core/src/main/java/org/apache/geode/internal/cache/RegionMap.java
- geode-core/src/main/java/org/apache/geode/internal/cache/TombstoneService.java
- geode-core/src/test/java/org/apache/geode/internal/cache/AbstractRegionMapTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/TombstoneServiceTest.java
more code cleanup while investigating an issue in this code base.
> GEODE-10092: cleanup unnecessary method arguments

- geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PersistentBucketRecoverer.java
- geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PersistenceAdvisorImpl.java
- geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/PersistentBucketRecovererTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/persistence/PersistenceAdvisorImplTest.java
> GEODE-9809: stop monitoring of destroyed regions

- geode-docs/tools_modules/geode_for_redis.html.md.erb
- geode-for-redis/README.md
- geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/commands/executor/list/RPushNativeRedisAcceptanceTest.java
- geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/key/RenameDUnitTest.java
- geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/list/RPushDUnitTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/list/AbstractRPushIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/list/RPushIntegrationTest.java
- geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/AbstractHitsMissesIntegrationTest.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/RedisCommandType.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/list/RPushExecutor.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/AbstractRedisData.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisList.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisList.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/AddByteArraysTail.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/DeltaType.java
- geode-for-redis/src/test/java/org/apache/geode/redis/internal/data/RedisListTest.java
> GEODE-9954: Implement Radish RPUSH command

- geode-assembly/src/acceptanceTest/java/org/apache/geode/cache/wan/SeveralGatewayReceiversWithSamePortAndHostnameForSendersTest.java
> GEODE-10127: Disables test until this issue is resolved.

- geode-core/src/main/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImpl.java
- geode-core/src/main/java/org/apache/geode/cache/client/internal/LocatorList.java
- geode-core/src/test/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImplTest.java
- geode-core/src/test/java/org/apache/geode/cache/client/internal/LocatorListTest.java
* Extract inner class LocatorList.
* Make LocatorList iterator that extends Iterator act like Iterator.
* Add tests for LocatorList.
> GEODE-10066: Fixes testing issues.

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/RebalanceWhileCreatingRegionDistributedTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/CacheDistributionAdvisor.java
- geode-core/src/main/java/org/apache/geode/internal/cache/CreateRegionProcessor.java
- geode-core/src/main/java/org/apache/geode/internal/cache/DestroyRegionOperation.java
- geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionHelper.java
- geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/RegionAdvisor.java
- geode-core/src/main/java/org/apache/geode/internal/cache/persistence/MembershipViewRequest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PersistentStateQueryMessage.java
- geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PrepareNewPersistentMemberMessage.java
- geode-core/src/main/java/org/apache/geode/internal/cache/persistence/RemovePersistentMemberMessage.java
- geode-core/src/test/java/org/apache/geode/internal/cache/DestroyRegionOperationJUnitTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/DestroyRegionOperationTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionHelperJUnitTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/RegionAdvisorJUnitTest.java
> GEODE-10039: Fix the issue that BucketProfile can be stale in rare cases.

- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisList.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/AddByteArrays.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/DeltaType.java
Add versioning for lpush.
Authored-by: Bala Kaza Venkata <bkazavenkata@vmware.com>
> GEODE-10138: Add Versioning Support for LPUSH

- ci/pipelines/pull-request/jinja.template.yml
In order to keep develop changes from breaking PR behavior on older
support branches, create a separate pipeline for each branch. Each
branch will use images, tests, and job-descriptions from it's own
branch.
> GEODE-10079: Create PR pipelines for all support versions

- geode-core/src/upgradeTest/java/org/apache/geode/security/AuthExpirationTransactionUpgradeTest.java
- AuthExpirationTransactionUpgradeTest had issues with serialization of
TXId class between different versions of test VMs during the
upgradeTest.
- Change made to the test so that we serialize a String instead of the
TXId to avoid this issue and gain the ability to run the test across a
wider range of client versions.
> GEODE-10163: upgradeTest serialization issues

- geode-core/src/main/java/org/apache/geode/internal/size/ReflectionSingleObjectSizer.java
- geode-core/src/test/java/org/apache/geode/internal/size/ReflectionObjectSizerJUnitTest.java
- geode-core/src/test/java/org/apache/geode/internal/size/ReflectionSingleObjectSizerTest.java
> GEODE-10133: change sizeof to handle UnsupportedOperationException

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- geode-assembly/src/integrationTest/resources/assembly_content.txt
- geode-assembly/src/integrationTest/resources/dependency_classpath.txt
fixes https://github.com/FasterXML/jackson-databind/issues/2816
> [1.14] GEODE-10179: Bump jackson-databind to 2.12.6.1

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- geode-assembly/src/integrationTest/resources/assembly_content.txt
- geode-assembly/src/integrationTest/resources/dependency_classpath.txt
see https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement
> GEODE-10201: Bump spring from 5.2.15 to 5.2.20

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- geode-assembly/src/integrationTest/resources/assembly_content.txt
- geode-assembly/src/integrationTest/resources/dependency_classpath.txt
see https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement
> GEODE-10201: Bump spring version from 5.2.15 to 5.2.20

- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisList.java
Modified lrem to not update versioning if nothing was removed from the
list.
> GEODE-10171: Update versioning for no-op operations

- CODEOWNERS
> Add @pivotal-jbarrett to CODEOWNERS

- geode-core/src/main/java/org/apache/geode/internal/net/SSLConfig.java
- geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
- geode-core/src/test/java/org/apache/geode/internal/net/SSLConfigTest.java
- geode-core/src/test/java/org/apache/geode/internal/net/SocketCreatorTest.java
* Combine common configuration into method for consistency.
* Adds tests for new extracted methods.
> GEODE-9991: Refactor for consistency and add tests.

- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/AbstractRedisData.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisList.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/collections/SizeableByteArrayList.java
- geode-for-redis/src/test/java/org/apache/geode/redis/internal/data/RedisListTest.java
- geode-for-redis/src/test/java/org/apache/geode/redis/internal/data/collections/SizeableByteArrayListTest.java
- The size must be updated as part of cloning an existing list.
> GEODE-10221: Fix sizing when creating a RedisList copy

- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisList.java
- geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/collections/SizeableByteArrayList.java
- geode-for-redis/src/test/java/org/apache/geode/redis/internal/data/collections/SizeableByteArrayListTest.java
Added additional test cases for public methods.
Authored-by: Bala Kaza Venkata <bkazavenkata@vmware.com>
> GEODE-10204: Add Test Coverage for SizeableByteArrayList

- geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegionMap.java
- geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java
- geode-core/src/test/java/org/apache/geode/internal/cache/AbstractRegionMapTxApplyDestroyTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/BucketRegionTest.java
> GEODE-10234: Do not generate tailKey if parallel wan not enabled.

- geode-junit/src/main/java/org/apache/geode/test/junit/rules/DescribedExternalResource.java
- geode-junit/src/test/java/org/apache/geode/test/junit/rules/DescribedExternalResourceTest.java
Co-authored-by: Dale Emery <demery@vmware.com>
> GEODE-10251: Make DescribedExternalResource report all exceptions

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ClearDuringNetSearchOplogRegressionTest.java
ClearDuringNetSearchOplogRegressionTest uses an await statement to
allow the timing of a region clear to be correct. An invocation of
CacheObserver.afterSettingDiskRef() is used as the trigger for the
await to pass and allow the clear to begin.
The test was failing due to CacheObserver.afterSettingDiskRef() being
invoked more than once in the await statement, but this method is
expected to be invoked multiple times during the test, so occasionally
the await would check and find 0 invocations,then check again and find
2 or more, causing the test to fail.
Replacing the times(1) in the assertion with atLeast(1) allows the test
to pass while preserving the intended behaviour of the await.
Some incidental code clean-up was also done in the test to remove
compiler warnings.
Authored-by: Donal …
> GEODE-10258: Assert at least 1 invocation

- geode-core/src/main/java/org/apache/geode/internal/process/ControlFileWatchdog.java
- geode-core/src/main/java/org/apache/geode/internal/process/FileControllableProcess.java
> GEODE-10184: Open status file for reading before handling request to avoid race conditions when accessing the file

- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/MemberJvmOptions.java
- geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/commands/MemberJvmOptionsTest.java
added opens required by geode features and added javadoc comments
that link to the class in geode that requires an open or export
> GEODE-10263: add opens required by geode features

- geode-core/src/main/java/org/apache/geode/internal/cache/FilterProfile.java
- geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/CQDistributedTest.java
Problem:
When server2 initializes at the same time as client register CQ while connected to server1, when below sequence happened, server2 will have a wrong idea what cq server1 should serve:
1. server2 creates the partitioned region and sends a CreateRegionMessage to server1
2. server1 process this message and adds server2 to its profile list
3. server1 reply to server2 with a CreateRegionReplyMessage
4. At thee same time server1 does register cq locally and send a REGISTER_CQ message to server2
5. REGISTER_CQ message reaches server2, server2 doesn't have server1's cache profile yet, so it wants to save the message to the "to_be_processed" queue, but get stuck there.
6. meanwhile, the CreateRegionReplyMessage in step 3 reaches server2, server2 now has server1's cache profile, processed …
> GEODE-10260: make sure message is added before they are processed.

- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/MemberJvmOptions.java
> GEODE-10263: add additional import for VMStats50

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- geode-assembly/src/integrationTest/resources/assembly_content.txt
- geode-assembly/src/integrationTest/resources/dependency_classpath.txt
latest (5.3.19) is recommended for support/1.14
> GEODE-10275: Bump spring from 5.3.18 to 5.3.19

- geode-assembly/src/acceptanceTest/java/org/apache/geode/cache/persistence/MissingDiskStoreAcceptanceTest.java
- geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/DistributionStatsNodesDistributedTest.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java
This is a continuation of PR #7554: https://github.com/apache/geode/pull/7554
> GEODE-9390: Guarding membership addition code paths to omit membership duplicates

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/UpdatePropagationDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/UpdatePropagationPRDUnitTest.java
- geode-core/src/distributedTest/java/org/apache/geode/internal/tcp/CloseConnectionTest.java
- geode-core/src/distributedTest/java/org/apache/geode/internal/tcp/TCPConduitDUnitTest.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/direct/DirectChannel.java
- geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
- geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java
- geode-core/src/main/java/org/apache/geode/internal/tcp/TCPConduit.java
- geode-core/src/test/java/org/apache/geode/internal/tcp/ConnectionTransmissionTest.java
- geode-core/src/test/java/org/apache/geode/internal/tcp/TCPConduitTest.java
> Revert "GEODE-9484: Improve sending message to multy destinations"

- extensions/geode-modules/build.gradle
- extensions/geode-modules/src/main/java/org/apache/geode/modules/session/bootstrap/AbstractCache.java
- extensions/geode-modules/src/main/java/org/apache/geode/modules/util/ResourceManagerValidator.java
- extensions/geode-modules/src/test/resources/expected-pom.xml
- geode-core/src/main/java/org/apache/geode/cache/EvictionAttributes.java
- geode-core/src/main/java/org/apache/geode/cache/control/ResourceManager.java
Product comments referring to CMS have been improved.
The ResourceManagerValidator now only does CMS checks if Java version supports CMS.
> GEODE-10206: clean up product references to CMS

- geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java
- geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb
- geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandDUnitTest.java
- geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/GfshParserAutoCompletionIntegrationTest.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java
> GEODE-10284: Add partition-listener option to gfsh create region command

- geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java
- geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb
- geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandDUnitTest.java
- geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/GfshParserAutoCompletionIntegrationTest.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java
* Update documentation
Co-authored-by: Dave Barnes <daveba@vmware.com>
(cherry picked from commit d4b80d27277d3eda22f692cf95d95026096470d5)
> GEODE-10284: Add partition-listener option to gfsh create region command (#7666)

- geode-core/src/integrationTest/java/org/apache/geode/internal/cache/tier/sockets/ConnectionProxyIntegrationTest.java
- geode-core/src/integrationTest/java/org/apache/geode/internal/cache/tier/sockets/ConnectionProxyJUnitTest.java
> GEODE-10271: ConnectionProxyJUnitTest cleanup

- ci/pipelines/shared/jinja.variables.yml
> GEODE-10303: Increase memory for windows-gfsh-distributed-test

- geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PersistenceAdvisorImpl.java
- geode-core/src/test/java/org/apache/geode/internal/cache/DistributedRegionTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/persistence/PersistenceAdvisorImplTest.java
* GEODE-10287: do distAdvisor.close after waitForCurrentOperations()
> GEODE-10286: handle CancelException in PersistenceAdvisor.close

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionRestartRebalanceDUnitTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/InitialImageOperation.java
- geode-core/src/main/java/org/apache/geode/internal/cache/versions/RegionVersionHolder.java
- geode-core/src/main/java/org/apache/geode/internal/cache/versions/RegionVersionVector.java
- geode-core/src/test/java/org/apache/geode/internal/cache/InitialImageOperationTest.java
> GEODE-10290: GII requester should remove departed members

- geode-core/src/main/java/org/apache/geode/security/SecurityManager.java
> GEODE-10115: fix javadoc

- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/MemberJvmOptions.java
> GEODE-10315: removed unneeded add-opens

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/PartitionedRegionCacheCloseNoRetryDistributedTest.java
- geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PartitionMessage.java
> GEODE-10310: Add disable reatempt on CacheClose

- geode-core/src/main/java/org/apache/geode/metrics/internal/InternalDistributedSystemMetricsService.java
(cherry picked from commit 802137f5487cc72927c4026895400f54dd2efc1b)
> GEODE-10319: Clear meters when closing the meter registry

- geode-junit/src/main/java/org/apache/geode/test/junit/rules/ClassAnalysisRule.java
> GEODE-10322: Run various Analyze Serializable tests from IntelliJ

- geode-core/src/distributedTest/java/org/apache/geode/distributed/HostedLocatorsDUnitTest.java
* The tests were refactored to remove deprecated functions.
* The second test was removed as using 0 as port numbers may result in port already in use and may cause flakiness.
> GEODE-9987: Refactored/Removal of deprecated APIs

- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
- geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionTest.java
> GEODE-10328: close data store stats on cache close

- geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java
- geode-core/src/main/java/org/apache/geode/internal/monitoring/ThreadsMonitoring.java
- geode-core/src/main/java/org/apache/geode/internal/monitoring/ThreadsMonitoringImpl.java
- geode-core/src/main/java/org/apache/geode/internal/monitoring/executor/AbstractExecutor.java
- geode-core/src/main/java/org/apache/geode/internal/monitoring/executor/AsyncWriterExecutorGroup.java
- geode-core/src/main/java/org/apache/geode/internal/monitoring/executor/SuspendableExecutor.java
- geode-core/src/test/java/org/apache/geode/internal/cache/DiskStoreImplValueRecoveryTest.java
- geode-core/src/test/java/org/apache/geode/internal/cache/FlusherThreadTest.java
- geode-core/src/test/java/org/apache/geode/internal/monitoring/ThreadsMonitoringImplJUnitTest.java
- geode-core/src/test/java/org/apache/geode/internal/monitoring/ThreadsMonitoringJUnitTest.java
- geode-core/src/test/java/org/apache/geode/internal/monitoring/executor/SuspendableExecutorTest.java
> GEODE-10226: Added monitoring of async writer

- geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueue.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelWANPersistenceEnabledGatewaySenderDUnitTest.java
> GEODE-10277: For destroyed region don`t check size

- geode-assembly/src/distributedTest/java/org/apache/geode/management/JQFilterVerificationDUnitTest.java
- geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/DeveloperRestSecurityConfigurationDUnitTest.java
- geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ManagementRestSecurityConfigurationDUnitTest.java
- geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/rest/SwaggerManagementVerificationIntegrationTest.java
- geode-assembly/src/integrationTest/java/org/apache/geode/rest/internal/web/DevRestSwaggerVerificationIntegrationTest.java
- geode-web-api/src/main/java/org/apache/geode/rest/internal/web/security/RestSecurityConfiguration.java
- geode-web-api/src/main/java/org/apache/geode/rest/internal/web/swagger/config/SwaggerConfig.java
- geode-web-api/src/main/resources/swagger.properties
- geode-web-management/src/main/java/org/apache/geode/management/internal/rest/security/RestSecurityConfiguration.java
- geode-web-management/src/main/java/org/apache/geode/management/internal/rest/swagger/SwaggerConfig.java
- geode-web-management/src/main/resources/swagger-management.properties
> GEODE-10312: Works, just need to fix the v1/v3 mismatch.

- geode-assembly/src/upgradeTest/java/org/apache/geode/session/tests/TomcatSessionBackwardsCompatibilityTestBase.java
Instead of saving locator and server logs to a temp dir, which will be deleted at the end of the tests, save the logs to a different dir, so that it will collected in the final artifacts.
> GEODE-10305: Change locator and server dirs

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PartitionedRegionStatsDistributedTest.java
* Renamed to PartitionedRegionStatsDistributedTest
* Used the new test framework
* Compartmentalize the cluster members so that parallel tests do not
affect the individual tests.
> GEODE-10347: Refactor PartitionedRegionStatsDUnitTest

- ci/pipelines/shared/jinja.variables.yml
> GEODE-10309: Give more memory to windows-core-integration-test

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- build-tools/geode-dependency-management/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/rest/StandaloneClientManagementAPIAcceptanceTest.java
- geode-assembly/src/integrationTest/resources/assembly_content.txt
- geode-assembly/src/integrationTest/resources/expected_jars.txt
- geode-assembly/src/integrationTest/resources/gfsh_dependency_classpath.txt
- geode-common/build.gradle
- geode-common/src/main/java/org/apache/geode/util/internal/GeodeJsonMapper.java
- geode-common/src/test/resources/expected-pom.xml
- geode-core/src/integrationTest/java/org/apache/geode/management/internal/beans/DistributedSystemMBeanIntegrationTest.java
- geode-core/src/test/java/org/apache/geode/management/internal/json/QueryResultFormatterTest.java
- geode-dunit/src/main/java/org/apache/geode/management/internal/cli/commands/QueryCommandIntegrationTestBase.java
- geode-dunit/src/main/resources/org/apache/geode/test/dunit/internal/sanctioned-geode-dunit-serializables.txt
- geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/GetCommandIntegrationTest.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/domain/DataCommandResult.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/functions/DataCommandFunction.java
- geode-junit/build.gradle
- geode-junit/src/main/java/org/apache/geode/management/model/Employee.java
- geode-junit/src/test/resources/expected-pom.xml
- geode-server-all/src/integrationTest/resources/dependency_classpath.txt
Co-authored-by: Jinmei Liao <jliao@pivotal.io>
- include libraries so that end-users won't have to add them to the java
path
- ensure proper serialization in gfsh and pulse
> GEODE-10301: support LocalDate and JodaTime

- geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderQueue.java
* The previous comment on removeOldEntry mentioned that the old entry
was replaced
* This has been corrected to mention that the old entry is removed and
the new entry has been added to the region queue
> GEODE-10356: Corrected the comment

- geode-docs/reference/topics/cache_xml.html.md.erb
- geode-docs/tools_modules/gfsh/command-pages/alter.html.md.erb
- geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb
> GEODE-10346: Correct batch-time-interval description in documentation

- geode-core/src/main/java/org/apache/geode/distributed/AbstractLauncher.java
- geode-core/src/main/java/org/apache/geode/distributed/ServerLauncher.java
- geode-core/src/test/java/org/apache/geode/distributed/ServerStateTest.java
> GEODE-10280: add Status Message to Status Server Command

- geode-docs/managing/security/implementing_ssl.html.md.erb
Port of PR #7775 to support/1.15 branch
> GEODE-10365: add missing components to table

- geode-docs/tools_modules/http_session_mgmt/tomcat_installing_the_module.html.md.erb
Port of PR #7778 to support/1.15
> GEODE-10342: Simplify copying jars

- geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitor.java
- geode-membership/src/test/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitorTest.java
Do not throw RejectedExecutionException if the GMSHealthMonitor is
stopping
> GEODE-10329: Handle RejectedExecutionException

- geode-core/src/integrationTest/java/org/apache/geode/cache/RegionExpirationIntegrationTest.java
* Using instant class instead of nanos.
* Nanos is not updated that often hence not proper resolution.
* Using millis instead of seconds to avoid ceiling issues.
> GEODE-6504: Instant class used.

- ci/images/alpine-tools/Dockerfile
- ci/pipelines/shared/jinja.variables.yml
- ci/scripts/create_instance.sh
- ci/scripts/delete_instance.sh
> GEODE-10369: Calculate heavy lifter costs.

- geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ConcurrentParallelGatewaySenderEventProcessor.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/ConcurrentSerialGatewaySenderEventProcessor.java
> GEODE-10384: Add stack trace to logging

- .asf.yaml
- ci/pipelines/pull-request/jinja.template.yml
Other JDK will be by request (label) only.
> GEODE-10378: Change PRs to default to JDK11 only

- geode-docs/managing/security/implementing_authentication.html.md.erb
- geode-docs/managing/security/implementing_authentication_expiry.html.md.erb
Incorporating reviewer improvements to authentication expiry instructions.
> GEODE-10390: User guide: update authentication expiry instructions

- geode-book/master_middleman/source/subnavs/geode-subnav.erb
- geode-docs/getting_started/system_requirements/host_machine.html.md.erb
- geode-docs/getting_started/system_requirements/java_support.html.md.erb
> GEODE-10386:Document JDK 17 for 1.15 release

- geode-assembly/src/acceptanceTest/java/org/apache/geode/cache/wan/SeveralGatewayReceiversWithSamePortAndHostnameForSendersTest.java
- geode-core/src/main/java/org/apache/geode/cache/client/internal/ConnectionImpl.java
- geode-core/src/main/java/org/apache/geode/cache/client/internal/OpExecutorImpl.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/ServerLocation.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/ServerLocationExtension.java
- geode-core/src/test/java/org/apache/geode/cache/client/internal/ConnectionImplTest.java
- geode-core/src/test/java/org/apache/geode/distributed/internal/ServerLocationExtensionTest.java
- geode-core/src/test/java/org/apache/geode/distributed/internal/ServerLocationTest.java
> GEODE-10020: For Ping task avoid registering new destination endpoint

- geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java
- geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
- geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueue.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelWANOverflowStatsDistributedTest.java
> GEODE-10392: when cleanqueue remove EvictionController from diskstore

- geode-core/src/main/java/org/apache/geode/distributed/AbstractLauncher.java
- geode-core/src/main/java/org/apache/geode/distributed/LocatorLauncher.java
- geode-core/src/main/java/org/apache/geode/distributed/ServerLauncher.java
> GEODE-10055: fix AbstractLauncher to print info and debug with stdout

- geode-core/src/main/java/org/apache/geode/internal/offheap/MemoryAllocatorImpl.java
- geode-core/src/test/java/org/apache/geode/internal/offheap/MemoryAllocatorJUnitTest.java
- geode-core/src/test/java/org/apache/geode/internal/offheap/OffHeapHelperJUnitTest.java
- geode-core/src/test/java/org/apache/geode/internal/offheap/OffHeapRegionEntryHelperInstanceTest.java
- geode-core/src/test/java/org/apache/geode/internal/offheap/OffHeapStorageJUnitTest.java
- geode-core/src/test/java/org/apache/geode/internal/offheap/OffHeapStoredObjectJUnitTest.java
This PR is a continuation of the original one (https://github.com/apache/geode/pull/7715) addressing some small review comments that were received after the PR was merged.
> GEODE-10323: Add small changes after review

- geode-core/src/main/java/org/apache/geode/internal/statistics/ResourceInstance.java
- geode-core/src/main/java/org/apache/geode/internal/statistics/SampleCollector.java
- geode-core/src/main/java/org/apache/geode/internal/statistics/StatArchiveWriter.java
> GEODE-10398: fix updating stats after restart

- geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/DistributionStatsNodesDistributedTest.java
- geode-core/src/distributedTest/java/org/apache/geode/management/CacheManagementDUnitTest.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java
> GEODE-9101: fix VisibleNode attribute

- geode-core/src/main/java/org/apache/geode/internal/classloader/ClassPathLoader.java
- geode-core/src/main/java/org/apache/geode/internal/classloader/ClasspathService.java
- geode-core/src/main/java/org/apache/geode/internal/classloader/DeployJarChildFirstClassLoader.java
- geode-deployment/geode-deployment-legacy/src/integrationTest/java/org/apache/geode/internal/deployment/JarDeployerIntegrationTest.java
- geode-deployment/geode-deployment-legacy/src/main/java/org/apache/geode/classloader/internal/LegacyClasspathServiceImpl.java
When loading class from jar, check if class is already loaded.
> GEODE-10407: check if class allready loaded

- geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java
- geode-core/src/main/java/org/apache/geode/internal/cache/InitialImageOperation.java
- geode-core/src/main/java/org/apache/geode/internal/cache/Oplog.java
> GEODE-10408: in case corrupted oplogs, use fullGII

- geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PersistenceAdvisorImpl.java
- geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelWANPersistenceEnabledGatewaySender2DUnitTest.java
> GEODE-10405: added ignore exceprion for GW queue region

- geode-core/src/main/java/org/apache/geode/internal/cache/TXManagerImpl.java
- geode-core/src/test/java/org/apache/geode/internal/cache/TXManagerImplTest.java
> GEODE-10335: TXManagerImpl.close resets currentInstance

- geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java
- geode-core/src/test/java/org/apache/geode/internal/tcp/ConnectionTableTest.java
> GEODE-10336: set lastInstance to null

- geode-core/src/main/java/org/apache/geode/internal/cache/TXManagerImpl.java
- geode-core/src/test/java/org/apache/geode/internal/cache/TXManagerImplTest.java
> GEODE-10335_1: add compareAndSet

- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/UpdatePropagationDistributedTest.java
- geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/UpdatePropagationPRDistributedTest.java
- geode-core/src/distributedTest/java/org/apache/geode/internal/tcp/CloseConnectionTest.java
- geode-core/src/distributedTest/java/org/apache/geode/internal/tcp/TCPConduitDUnitTest.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/direct/DirectChannel.java
- geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
- geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java
- geode-core/src/main/java/org/apache/geode/internal/tcp/TCPConduit.java
- geode-core/src/test/java/org/apache/geode/internal/tcp/ConnectionTransmissionTest.java
- geode-core/src/test/java/org/apache/geode/internal/tcp/TCPConduitTest.java
> GEODE-9484: Improve sending message to multy destinations (#7664)

- geode-docs/managing/disk_storage/optimize_availability_and_performance.html.md.erb
> GEODE-10422: add Note for parallel recovery disk store

- geode-core/src/integrationTest/java/org/apache/geode/management/internal/beans/DistributedSystemBridgeIntegrationTest.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/InternalConfigurationPersistenceService.java
- geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupConfigFactory.java
- geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupOperation.java
- geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupService.java
- geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupTask.java
- geode-core/src/main/java/org/apache/geode/internal/cache/backup/FileSystemBackupWriterConfig.java
- geode-core/src/main/java/org/apache/geode/internal/cache/backup/PrepareBackup.java
- geode-core/src/main/java/org/apache/geode/internal/cache/backup/PrepareBackupFactory.java
- geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java
- geode-docs/tools_modules/gfsh/command-pages/backup.html.md.erb
- geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/BackupDiskStoreCommandDUnitTest.java
- geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/BackupDiskStoreCommand.java
> GEODE-10419: Enhancment of backup disk-store command

- geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionImpl.java
- geode-core/src/main/java/org/apache/geode/distributed/internal/direct/DirectChannel.java
- geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionTest.java
- geode-core/src/test/java/org/apache/geode/distributed/internal/direct/DirectChannelTest.java
> GEODE-10331: schedule delayed CloseEndpoint

- .asf.yaml
> GEODE-10433: remove concourse ci checks

- .github/workflows/gradle.yml
- build-tools/geode-dependency-management/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- geode-core/src/integrationTest/java/org/apache/geode/internal/cache/partitioned/PartitionedRegionRebalanceOpIntegrationTest.java
- geode-core/src/integrationTest/java/org/apache/geode/internal/tcp/MsgStreamerIntegrationTest.java
> GEODE-10442: Add acceptanceTest step to GHA pipeline

- README.md
> Minor: correct README.md

- .github/workflows/codeql.yml
- .github/workflows/gradle.yml
- settings.gradle
This PR publishes a build scan for every CI build on Jenkins and GitHub Actions and for every local build from an authenticated Apache committer. The build will not fail if publishing fails.
The build scans of the Apache Geode project are published to the Gradle Enterprise instance at [ge.apache.org](https://ge.apache.org/), hosted by the Apache Software Foundation and run in partnership between the ASF and Gradle. This Gradle Enterprise instance has all features and extensions enabled and is freely available for use by the Apache Geode project and all other Apache projects.
This pull request enhances the functionality of publishing build scans to the publicly available [scans.gradle.com](https://scans.gradle.com/) by instead publishing build scans to …
> GEODE-10446: Capture build scans on ge.apache.org to benefit from deep build insights

- boms/geode-all-bom/src/test/resources/expected-pom.xml
- build-tools/geode-dependency-management/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
- geode-assembly/src/integrationTest/resources/assembly_content.txt
- geode-assembly/src/integrationTest/resources/gfsh_dependency_classpath.txt
- geode-server-all/src/integrationTest/resources/dependency_classpath.txt
> Upgrade JGroups to 3.6.20.Final

- .asf.yaml
> GEODE-10434: Update required reviews to 0
