geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/ClusterDistributionManagerDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/StateFlushOperation.java

Co-authored-by: Darrel Schneider <darrel@vmware.com>
Co-authored-by: Anil <agingade@pivotal.io>
Co-authored-by: Bill Burcham <bill.burcham@gmail.com>

GEODE-8608: StateFlush could hang when the target member is shutdown

---

geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/MembershipIntegrationTest.java

Wait for the view to have size 2 instead of asserting it in
MembershipIntegrationTest.locatorsStopWaitingForLocatorWaitTimeIfAllLocatorsContacted,
because the view is updated asynchronously.

GEODE-8602: Wait for view to change in locator test

---

geode-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/key/ExpireAtExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/key/ExpireExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/key/PExpireAtExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/key/PExpireExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/key/PTTLExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/key/TTLExecutor.java

Remove constants we no longer use in `RedisConstants`

GEODE-8612: Remove unused Redis constants

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/AbstractSPopIntegrationTest.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SPopExecutor.java

- Without a count argument, SPOP should return the result as a bulk
string.

GEODE-8621: Redis SPOP can return incorrect string type

---

geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/hash/HScanNativeRedisAcceptanceTest.java
geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/set/SScanNativeRedisAcceptanceTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/AbstractHScanIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/HScanIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/AbstractScanIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/AbstractSScanIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SScanIntegrationTest.java
geode-redis/src/main/java/org/apache/geode/redis/internal/ParameterRequirements/OddParameterRequirements.java
geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
geode-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSet.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHash.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHashCommandsFunctionExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSetCommandsFunctionExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/CommandFunction.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisResponse.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HScanExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/RedisHashCommands.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/RedisHashCommandsFunctionInvoker.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/key/ScanExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/RedisSetCommands.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/RedisSetCommandsFunctionInvoker.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SScanExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
geode-redis/src/main/resources/org/apache/geode/redis/internal/sanctioned-geode-redis-serializables.txt

Add integration tests and functionality to match native Redis.

GEODE-8585: Redis SCAN, HSCAN, and SSCAN do not detect illegal parameters

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/GeodeServerRunTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractPubSubIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractSubscriptionsIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/mocks/DummySubscription.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/connection/PingExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PunsubscribeExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/UnsubscribeExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/ChannelSubscription.java
geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PatternSubscription.java
geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSub.java
geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSubImpl.java
geode-redis/src/main/java/org/apache/geode/redis/internal/pubsub/Subscription.java
geode-redis/src/main/resources/org/apache/geode/redis/internal/sanctioned-geode-redis-serializables.txt

Geode Redis should unsubscribe from all channels (not including patterns) when no channel is provided and punsubscribe from all patterns (not including channels) when no pattern is provided.

GEODE-8627: Redis not unsubscribing and punsubscribing correctly when no channel/pattern provided

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/AbstractUnknownIntegrationTest.java
geode-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/UnknownExecutor.java

Unknown command error message should have trailing space like native Redis.

GEODE-8632: Redis Unknown command error message should have trailing space

---

geode-core/src/integrationTest/java/org/apache/geode/internal/net/SSLUtilIntegrationTest.java
geode-core/src/main/java/org/apache/geode/internal/net/SSLUtil.java
geode-core/src/test/java/org/apache/geode/internal/net/SSLUtilTest.java

* Uses the default KeyManagerFactory algorithm property.
* Adds unit test.
* Adds integration test.

GEODE-8611: Fixes default KeyManagerFactory instantiation.

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractPubSubIntegrationTest.java

- When this is present, it causes OOM errors when run under
StressNewTest.

GEODE-8654: Remove debug logging from AbstractPubSubIntegrationTest

---

geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitor.java

The catch block was just for logging what was considered an "unexpected exception" in the past.
This should more properly bubble up as it represents a state that is not internal to membership.

GEODE-7696: Add comment to GMSHealthMonitor explaining when IllegalStateException may be thrown

---

geode-dunit/src/main/java/org/apache/geode/management/internal/cli/commands/RebalanceCommandDistributedTest.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/RebalanceCommand.java

Different versions of the embedded Jetty server can launch non-daemon
threads, so the fix implies preventing any flakiness by just checking
for the thread we're interested in.

GEODE-8071: Prevent Test Flakiness

---

buildSrc/src/main/java/org/apache/geode/gradle/RunInSubdirectoryTestFramework.java
extensions/geode-modules-test/src/main/java/org/apache/geode/modules/session/AbstractSessionsTest.java
gradle/test.gradle

Before running a test task, wrap its TestFramework in a wrapper that creates a unique working dir for each new test worker.
The affected test tasks are:
- acceptanceTest
- distributedTest
- integrationTest
- uiTest
- upgradeTest
- All repeat*Test tasks

GEODE-8637: Give each test worker a unique working dir

---

geode-core/src/distributedTest/java/org/apache/geode/cache30/ReconnectDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/ClusterDistributionManagerDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/RedundancyLevelTestBase.java
geode-core/src/distributedTest/java/org/apache/geode/management/internal/security/MultiGfshDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscDUnitTestBase.java
geode-dunit/src/main/java/org/apache/geode/management/internal/cli/commands/QueryCommandDUnitTestBase.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/IgnoredException.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/DUnitLauncher.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/StandAloneDUnitEnv.java
geode-dunit/src/main/java/org/apache/geode/test/greplogs/LogConsumer.java
geode-dunit/src/test/java/org/apache/geode/test/greplogs/LogConsumerTest.java
geode-web/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/AlterRuntimeCommandDistributedTest.java

- Create a new `dunit_suspect` log for each VM. The logs will now
be named `dunit_suspect-vm<VMID>.log`. The locator VM and the test
runner VM will have logs named `dunit_suspect-locator.log` and
`dunit_suspect-local.log` respectively.

GEODE-8609: Create a dunit suspect file per VM

---

geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedMapTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedMap.java

* Additional improvements for usage of DistributedMap.
* Improve fluent style API usage of dunit VM.
NOTE: #5664 should be merged before this PR.

GEODE-8647: Support multiple instances of DistributedMap

---

ci/pipelines/mass-test-run/jinja.template.yml

this is helpful if someone accidentally plussed DistributedTestOpenJDK8 in the apache-develop-mass-test-run-pipeline, then tried to cancel it
you will still need to manually adjust the next run to 199x instead of 200x, but this change will at least allow the report to be generated, as otherwise it will not run if there is an extra job

GEODE-8275: exclude cancelled jobs when looking for last completed job

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AbstractDecrByIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AbstractIncrIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AbstractStrLenIntegrationTest.java
geode-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisString.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/DecrByExecutor.java
geode-redis/src/test/java/org/apache/geode/redis/internal/data/RedisStringTest.java

GEODE-8662: add integration tests for strlen

---

buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/AbstractKeysIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AbstractAppendIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AbstractGetRangeIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AbstractLettuceAppendIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AbstractStrLenIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/LettuceAppendIntegrationTest.java
geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java

Remove a forced encoding to UTF-8, and confirm that other forms of binary data are sent and received in the same way as native Redis.

Geode-8677: Confirm binary data storage

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/control/RebalanceOperationDistributedTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/LocalRegionTest.java

* The DESTROYED token is only needed to prevent concurrent destroy op
is lost in GII. If concurrency checks are enabled, the version tag
should be able to prevent the destroy op being lost.

GEODE-8672: No need in token mode if concurrencyChecksEnabled

---

geode-core/src/distributedTest/java/org/apache/geode/ClusterCommunicationsDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/net/NioSslEngine.java
geode-core/src/test/java/org/apache/geode/internal/net/NioSslEngineTest.java

A socket-read could pick up more than one message and a single unwrap()
could decrypt multiple messages.
Normally the engine isn't closed and it reports normal
status from an unwrap() operation, and Connection.processInputBuffer
picks up each message, one by one, from the buffer and dispatches them.
But if the SSLEngine is closed we were ignoring any already-decrypted
data sitting in the unwrapped buffer and instead we were throwing an SSLException.
email to …

GEODE-8681: peer-to-peer message loss due to sending connection closing with TLS enabled

---

ci/scripts/repeat-new-tests.sh

it seems that devBuild is not sufficient to ensure that StressNewTestHelper and all tests are built before running the helper.  Therefore, explicitly call `compileTestJava` to ensure that we do the needful regardless of branch.

GEODE-8603: fix StressNew for support branches

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/Acceptor.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/AcceptorImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientHealthMonitor.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientHealthMonitorTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelWANStatsDUnitTest.java

The maximum-time-between-pings set when creating a gateway receiver
was not honored because the ClientHealthMonitor, that is the singleton
class monitoring all clients, supported just one value for maximum
time between pings for all clients. This value is set
when the server in which the receiver is running is started
and when the gateway receiver provides a different value
it is ignored.
With this fix, it is allowed to have different values
for maximum-time-between-clients for different clients. …

GEODE-8683: Honor maximum-time-between-pings in gateway receiver

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/versions/TombstoneDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegionMap.java

- Do not call AbstractRegionMap.removeTombstone() outside of
TombstoneService class
- Add test to confirm that tombstones are correctly scheduled and
collected with this change

GEODE-8686: Prevent potential deadlock during GII and tombstone GC

---

geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/RegionAdvisor.java
geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/RegionAdvisorJUnitTest.java

If `RegionAdvisor.buckets == null` at the time the value of `serials` is generated, an `ArrayIndexOutOfBoundsException` may be thrown in `RegionAdvisor.processProfilesQueuedDuringInitialization` if buckets have been initialized at that point.
Code where `ArrayIndexOutOfBoundsException` might be thrown in `RegionAdvisor.processProfilesQueuedDuringInitialization()`:
```
for (int i = 0; i < buckets.length; i++) {
BucketAdvisor ba = buckets[i].getBucketAdvisor();
int serial = qbp.serials[i]; <<< Exception thrown here
if (serial != ILLEGAL_SERIAL) {
ba.removeIdWithSerial(qbp.memberId, serial, qbp.destroyed);
}
}
```
We ultimately decided that if the buckets were not created at the time the value of `serials` is generated, there is no need to worry about their profiles getting deleted later. …

GEODE-8692: ArrayIndexOutOfBoundsException may be thrown in RegionAdvisor.processProfilesQueuedDuringInitialization

---

geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java
geode-core/src/main/java/org/apache/geode/internal/SystemTimer.java
geode-core/src/main/java/org/apache/geode/internal/admin/StatAlertsManager.java
geode-core/src/main/java/org/apache/geode/internal/cache/ExpirationScheduler.java
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PRSanityCheckMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/AcceptorImpl.java
geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java
geode-core/src/test/java/org/apache/geode/internal/SystemTimerTest.java

* GEODE-7884: server hangs due to IllegalStateException
Added cancellation check before scheduling an idle-timeout or
ack-wait-threshold timer task.  I had to add a new method to
SystemTimerTask and then noticed there were no tests for SystemTimer, so
I cleaned up that class and added tests.
* adding missing copyright header to new test
* fixing LGTM issues
* reinstating 'continue' when encountering a null timer during a sweep
* addressing Bill's comments
renamed swarm everwhere
made the collection of timers associated with a DistributedSystem into a Set
made timer task variables in Connection volatile
added checks in tasks to cancel themselves if their Connection is closed
(cherry picked from commit 2d2a3f80bd5053749963889c1898df48e9aa0be7)
Thank you for submitting a contribution to …

Back-port GEODE-7884 to 1.12: server hangs due to IllegalStateException (#4822)

---

geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionImpl.java
geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionTest.java

- If while calling DistributionImpl.start there was either a
MembershipConfigurationException or MemberStartupException exceptions, its
original cause was not propagated, therefore being unable to properly
tackling issues on startup.
- This commit propagates the cause for both exceptions.
- Also 2 JUint test were added to make sure this is working.
---

GEODE-8664: Nest errors in DistributionImpl.start

---

geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionImpl.java
geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionTest.java

email to [dev@geode.apache.org](mailto:dev@geode.apache.org).
---
As it seems there were some spurious failures during CI execution and that hid some test cases which were actually failing.
Reverting this commit for now and will be included again once tests have been fixed.
Reverts: apache/geode#5725

Revert "GEODE-8664: Nest errors in DistributionImpl.start"

---

geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Jetty9CachingClientServerTest.java

Ignoring this test class until issue with JDK update is resolved.
- [ x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?
- [ x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?
- [ x] Does `gradlew build` run cleanly?
- [ x] Have you written or updated unit tests to verify your changes?
- [ x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF …

GEODE-8704: many CI failures in Jetty9CachingClientServerTest

---

geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java
geode-core/src/test/java/org/apache/geode/distributed/internal/ClusterDistributionManagerTest.java
geode-dunit/src/main/java/org/apache/geode/test/greplogs/ExpectedStrings.java

avoid setting MemberDisconnectedException as a rootCause in
ClusterDistributionManager, even temporarily, as it's an internal
exception that should not be exposed to applications.
@kamilla1201 

GEODE-8697: Propagate ForcedDisconnectException to the user application

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/GetClientPartitionAttributesCommand66.java
geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/CQMetricsDUnitTest.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/ServerCQImpl.java
geode-docs/reference/statistics_list.html.md.erb

For partitioned regions if the CQ is registered on one server, it will be created on all the nodes/servers hosting the region.
In this case activeCQCount is increment only on one server.
After close/stop CQ it found that it has CQ on all members and decrement num of active CQs, despite of that it is only incremented on one server, so we got negative values.
With fix it will increment activeCQCount on all nodes/servers that hosting the region. So when it close/stop it will not go to the negative values.
This change will not have effects on non-partitioned(replicated) regions. …

GEODE-8293: fix activeCQCount has negative value after close/stop cq for PR

---

geode-core/src/main/java/org/apache/geode/internal/cache/EntrySnapshot.java
geode-core/src/main/java/org/apache/geode/internal/cache/snapshot/SnapshotPacket.java
geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/ExportDataIntegrationTest.java

Modified test to fail if it attempts to deserialize values during export.
Fixed product export code to no longer deserialize and test now passes.

GEODE-8685: change export to not deserialize region values

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/launchers/ServerStartupRedundancyRecoveryNotificationTest.java

Use --disable-default-server to avoid one cause of BindExceptions.

GEODE-7016: Fix ServerStartupRedundancyRecoveryNotificationTest

---

ci/scripts/execute_redis_tests.sh
geode-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch

use the redis/redis repo's test with a patch containing changes to tests
that fail on unimplemented commands when testing geode-redis.

GEODE-8694: use redis tests with patch

---

dev-tools/dependencies/README.md
dev-tools/release/commit_rc.sh
dev-tools/release/deploy_rc_pipeline.sh
dev-tools/release/prepare_rc.sh
dev-tools/release/promote_rc.sh

* use license review script from develop
* don't expect prod version in builds from source
* placeholders for releasing from not-the-latest SHA

GEODE-8707: fix release scripts for 1.13.1

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
extensions/geode-modules-tomcat9/build.gradle
extensions/geode-modules-tomcat9/src/test/resources/expected-pom.xml

We need to publish geode-modules-tomcat9 to Maven so it can be utilized properly when consuming Geode via Maven.

GEODE-8732: Update Tomcat9 module to publish to Maven

---

geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitorJUnitTest.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitor.java

If a server is in the process of performing an availability check on
another server we shouldn't update the contact timestamp for
the suspected server based on gossip from another server.  Doing so
will make the availability check pass and send out another gossip
message that would likewise update their timestamps for the suspected
server, perpetuating the notion that the suspect is still around.
@kamilla1201 

GEODE-8721: member that should become coordinator never detects loss of current coordinator

---

geode-core/src/integrationTest/java/org/apache/geode/internal/net/SSLSocketHostNameVerificationIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/net/SSLSocketIntegrationTest.java
geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
geode-core/src/test/java/org/apache/geode/internal/net/SocketCreatorJUnitTest.java

**NOT READY FOR MERGE YET**
This is the fix for [GEODE-8419](https://issues.apache.org/jira/browse/GEODE-8419). I couldn't cherry-pick it directly from `develop` because `support/1.12` is missing some other changes that the GEODE-8419 fix on `develop` was dependent on. As a result I had to make the changes manually. Nevertheless I intend to manually add this comment to the squashed commit when I merge so as to satisfy the "commit check" CI checks:
(cherry picked from commit 537721ff815cf40eff85fde65db9b5e787471c89)
^ that's the SHA of the fix for GEODE-8419 on `develop`
See also:
* Original PR on `develop` https://github.com/apache/geode/pull/5465
* port to `support/1.13` branch https://github.com/apache/geode/pull/5594

GEODE-8419: backported forward to support/1.12

---

dev-tools/release/create_support_branches.sh
dev-tools/release/deploy_rc_pipeline.sh
dev-tools/release/prepare_rc.sh
dev-tools/release/promote_rc.sh
dev-tools/release/set_versions.sh

travis, lgtm, and Dockerfile in native (support branch and develop) are now updated when a new version of Geode is released
product_version for Geode docs are now updated when a new version of Geode is released

GEODE-8736: maintain geode version for native and docs

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy

develop and 1.12 release binaries contain only json-smart 2.3, but 1.13.1 contained both 1.3.1 and 2.3 due to the particular version of spring-security-oauth2-client in this release.  this change makes sure 2.3 is used in all places.
try `./gradlew :geode-pulse:dependencies | grep json-smart` with and without this fix to see the issue.

GEODE-8744: fix multiple versions of json-smart

---

ci/pipelines/geode-build/jinja.template.yml
ci/pipelines/shared/jinja.variables.yml

Recently UpgradeTestOpenJDK8 has been taking ~59 minutes and its job timeout is 1h.  After adding 1.13.1 as old version, it tipped to taking slightly over an hour.  Timeout for this job is increased to 1h30m as there's no need to cut it so close.
Recent changes to Benchmarks have also caused longer runs (from 4h -> 7h in the best case, and much much longer in the worst case).  The current job timeout of 8h is being hit frequently, and after trying a temporary increase to 16h, we still saw successful runs taking 15h, and still some timing out, so timeout is increased to 24h for now.  Also added separate timeouts for the other Benchmarks jobs which are more predictable and much shorter.

GEODE-8740: increase test job timeouts

---

geode-core/src/main/java/org/apache/geode/cache/asyncqueue/internal/SerialAsyncEventQueueImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySenderEventProcessor.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderEventProcessor.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderQueue.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderOperationsDistributedTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialWANPersistenceEnabledGatewaySenderDUnitTest.java
geode-wan/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderImpl.java

* cleanQueues are applicable only while using persistence
* when we are closing the region, the disk files are not deleted.
* hence the values will still be maintained on restart.
* Advantage will be that we are creating the queue region and its cache listener together
* previously the region was not closed and cache listener was attached using mutators.
* this caused secondary events to be missed before the cache listener is activated
email to …

GEODE-8745: Closing the queue region when senders are stopped.

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/partitioned/PersistentPartitionedRegionDistributedTest.java

When revoking a persistent member,
PersistentPartitionedRegionDistributedTest now uses the to-be-revoked
member's actual inet address in the revocation pattern.

GEODE-8752: Revoke using member's actual address

---

geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/AlterTimeToLiveExpirationOnProxyRegionDUnitTest.java

* When a region is created with zero local memory, there is no bucket regions created.
* When alter region is called on this proxy region to alter expiry, it tries to manipulate the bucket region.
* But there are no buckets and hence NPE is thrown.
* In this commit a null check is done before alter the bucket regions.
* Configs still need to changed to prevent restart issues.
* This similar to the check done in setEntryTimeToLive in PartitionedRegion class
email …

GEODE-8748: Prevents NPE on alter expiry on proxy regions

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientUpdater.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientCQAutoSerializer.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientCQAutoSerializerDUnitTest.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/TestAutoSerializerCqListener.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/TestAutoSerializerObject1.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/TestAutoSerializerObject2.java

* Whenever PdxSerializationException is thrown on client for problematic CQ event, client will try to log that exception
together with the problematic event value. But the problem is that client has to de-serialize event value in order to log it.
When client tries to do that, it gets another PdxSerializationException which is now catched at higher level and cause
shutdown of CacheClientUpdater and subscription queue connection.
* Behavior with this fix: At the reception of event that provoke
PdxSerializationException client will only log the exception and ignore
PdxSerializationException that happen during logging
Please …

GEODE-8687: Fix for handling of PdxSerializationException on client

---

geode-assembly/src/integrationTest/java/org/apache/geode/AssemblyContentsIntegrationTest.java
geode-assembly/src/integrationTest/java/org/apache/geode/BundledJarsJUnitTest.java
geode-assembly/src/integrationTest/java/org/apache/geode/GeodeDependencyJarIntegrationTest.java

BundledJarsJUnitTest, AssemblyContentsIntegrationTest, and GeodeDependencyJarIntegrationTest once again write their output to the file paths indicated in their failure messages.
Please review @yozaner1324

GEODE-8755: Write content list files to integration test dir

---

geode-assembly/src/acceptanceTest/resources/org/apache/geode/client/sni/docker-compose.yml
geode-assembly/src/acceptanceTest/resources/org/apache/geode/client/sni/haproxy.cfg
geode-assembly/src/acceptanceTest/resources/org/apache/geode/client/sni/scripts/geode-starter-2.gfsh
geode-assembly/src/acceptanceTest/resources/org/apache/geode/client/sni/scripts/geode-starter.gfsh

2 Dockerized cache servers (in test) were binding to ephemeral ports 40404, 40405. These can conflict with some ephemeral port that is bound in the container before the Geode cluster is started. They also can conflict with the RMI port bound by each cache server.
Changed the test to bind to ports 8501, 8502.

GEODE-8730: DualServerSNIAcceptanceTest fails to start server because port is in use

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/QueueManagerImpl.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientCQDUnitTest.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientTestBase.java

This change solves the issue when the client without configured HA is
wrongly re-registering durable CQs as non durable during the server
failover.

GEODE-8329: Fix for durable CQ reqistration recovery

---

geode-dunit/src/main/java/org/apache/geode/test/junit/rules/LocatorLauncherStartupRule.java

LocatorLauncherStartupRule now assigns available HTTP and JMX ports rather than launching with the product's default ports. Assigning available ports reduces bind conflicts when the tests that use this rule run in parallel outside of Docker.

GEODE-8772: Launcher rule assigns available ports

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/AbstractHashesIntegrationTest.java

In AbstractHashesIntegrationTest putting the value would fail in the test setup. It was using a pseudo-random method to generate keys. That method was not random enough and was causing collisions, making the put fail. This in turn caused the number of keys to be incorrect so the test would never hget all the keys it was expecting.

GEODE-8766: reduce collisions during hget in AbstractHashesIntegrationTest

---

geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/ClusterDistributionManagerDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/tcp/CloseConnectionTest.java
geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java
geode-docs/managing/logging/logging_categories.html.md.erb
geode-docs/managing/monitor_tune/socket_communication_have_enough_sockets.html.md.erb
geode-docs/managing/monitor_tune/sockets_and_gateways.html.md.erb
geode-docs/reference/topics/gemfire_properties.html.md.erb
geode-docs/reference/topics/memory_requirements_for_cache_data.html.md.erb
geode-docs/topologies_and_comm/multi_site_configuration/setting_up_a_multisite_system.html.md.erb

- Update certain tests to explicitly set conserve-sockets=true to allow
them to pass with the new default
- Update docs to reflect new default

GEODE-8778: Change conserve-sockets default value to false

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/BaseCommand.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/CreateRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Destroy.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Destroy65.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/DestroyRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Get70.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Invalidate.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/KeySet.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Put.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Request.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Size.java

- Do not format the String containing the reason for the exception to
contain the region name

GEODE-8789: Prevent region name from being incorrectly logged twice

---

buildSrc/src/main/resources/japicmp_exceptions.json
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/FunctionExecutionWithPrincipalDUnitTest.java
geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-core/src/main/java/org/apache/geode/cache/execute/FunctionContext.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionDataStore.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/AbstractExecution.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/FunctionContextImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/FunctionRemoteContext.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/RegionFunctionContextImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PartitionedRegionFunctionStreamingMessage.java
geode-core/src/main/java/org/apache/geode/internal/security/IntegratedSecurityService.java
geode-core/src/main/java/org/apache/geode/internal/security/LegacySecurityService.java
geode-core/src/main/java/org/apache/geode/internal/security/SecurityService.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/ClientCacheRule.java
geode-junit/src/main/java/org/apache/geode/management/internal/security/TestFunctions.java

- Add the ability to retrieve the Principal from the FunctionContext
when a SecurityManager is enabled.

GEODE-8782: Add getPrincipal method to FunctionContext interface

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/AuthIntegrationTest.java
geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandSupportLevel.java
geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Command.java
geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
geode-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java

- This deals with some specfics related to how the lettuce v6 client
determines what protocol to use when authentication is also enabled.

GEODE-8794: Support redis 6 HELLO command

---

geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeCreateGatewaySenderMixedSiteOneCurrentSiteTwo.java
geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeEventProcessingMixedSiteOneCurrentSiteTwo.java
geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeEventProcessingOldSiteOneCurrentSiteTwo.java
geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeMultipleReceiversDefinedInClusterConfiguration.java
geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeSecondaryEventsNotReprocessedAfterCurrentSiteMemberFailover.java
geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeSecondaryEventsNotReprocessedAfterOldSiteMemberFailover.java
geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeVerifyGatewayReceiverDoesNotSendRemoveCacheServerProfileToMembersOlderThan1dot5.java
geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeVerifyGatewaySenderProfile.java

Before: WANRollingUpgradeSecondaryEventsNotReprocessedAfterCurrentSiteMemberFailover allocated ports for two locators by making two separate calls to AvailablePort. AvailablePort randomly samples ports with replacement, and so two calls can return the same port if the port is not put into use between the calls.
Now: The test allocates both ports at the same time, and does so via AvailablePortHelper, which samples ports round robin rather than random with replacement.

GEODE-6622: WAN rolling upgrade test bind exception

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
build.gradle
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
extensions/geode-modules-tomcat7/build.gradle
extensions/geode-modules-tomcat8/build.gradle
extensions/geode-modules-tomcat9/build.gradle
extensions/geode-modules/build.gradle
geode-core/build.gradle
geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/api/CoreOnlyUsesMembershipAPIArchUnitTest.java
geode-membership/build.gradle
geode-membership/src/test/resources/expected-pom.xml
geode-redis/build.gradle
gradle/test.gradle

GEODE-8496: Bump nebula-facets plugin. Fix deprecated gradle configuration use.

---

geode-lucene/geode-lucene-test/src/main/java/org/apache/geode/cache/lucene/test/TestPdxObject.java
geode-lucene/src/distributedTest/java/org/apache/geode/cache/lucene/LuceneClientSecurityPostProcessingDUnitTest.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/results/LuceneGetPageFunction.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/results/LuceneGetPageFunctionJUnitTest.java

- This now relies on the principal being available in the
FunctionContext.
- PDX objects are passed directly to the post-processor thus avoiding
any possible serialization issues.

GEODE-8795: Lucene queries should utilize post-processing if enabled

---

geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderQueue.java

reverting 3ed37a754d789bb52cf190db23088e819955fd58, which caused enqueuing time for async queues to triple.

GEODE-5922: concurrency problems in SerialGatewaySenderQueue

---

geode-junit/src/main/java/org/apache/geode/test/util/StressNewTestHelper.java
geode-junit/src/test/java/org/apache/geode/test/util/WhatExtendsJUnitTest.java

- Multiple tests should each declare a separate `--tests` option instead
of being comma separated.

GEODE-8814: StressNewTestHelper is not specifying multiple tests correctly

---

geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterOperationExecutors.java
geode-core/src/main/java/org/apache/geode/distributed/internal/OperationExecutors.java
geode-core/src/main/java/org/apache/geode/internal/cache/properties.html
geode-core/src/test/java/org/apache/geode/distributed/internal/ClusterOperationExecutorsTest.java

- OperationExecutors.MAX_THREADS new default is 300
- ClusterOperationExecutors.MAX_PR_THREADS new default is
Math.max(Runtime.getRuntime().availableProcessors() * 32, 200))
- Removed unit test case for setting system property, since it cannot be
cleared afterwards without unloading the class
submit an …

GEODE-8799: Increase defaults for OperationExecutors.MAX_THREADS and ClusterOperationExecutors.MAX_PR_THREADS

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/FunctionExecutionWithPrincipalDUnitTest.java
geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-core/src/main/java/org/apache/geode/cache/execute/FunctionContext.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionDataStore.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/FunctionContextImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/FunctionRemoteContext.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/RegionFunctionContextImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PartitionedRegionFunctionStreamingMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CommandInitializer.java
geode-core/src/main/java/org/apache/geode/internal/security/IntegratedSecurityService.java
geode-core/src/main/java/org/apache/geode/internal/security/LegacySecurityService.java
geode-core/src/main/java/org/apache/geode/internal/security/SecurityService.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/ClientCacheRule.java
geode-junit/src/main/java/org/apache/geode/management/internal/security/TestFunctions.java
geode-serialization/src/main/java/org/apache/geode/internal/serialization/Version.java
geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeCreateGatewaySenderMixedSiteOneCurrentSiteTwo.java

- Add the ability to retrieve the Principal from the FunctionContext
when a SecurityManager is enabled.
(cherry picked from commit a42f89ab48aaca9aac96a34e80a9b3b2d46bcddd)

GEODE-8782: Add getPrincipal method to FunctionContext interface (#5840)

---

geode-core/src/distributedTest/java/org/apache/geode/distributed/LocatorDUnitTest.java
geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeaveJUnitTest.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMembership.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/interfaces/JoinLeave.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java

When a member is unable to contact a join the system due to a failure to contact a locator, we could be a lot more specific, which would help users debug issues in their environment. We currently print out
> Unable to join the distributed system.  Operation either timed out, was stopped or Locator does not exist.
This change makes the exception message more specific. Instead of printing out the same message for 3 different problems, this change separates it out into 3 different messages. In case of a failure to contact a locator, the exception will include the underlying exception from the last locator we tried to contact as a cause. Also, the exception message will include the list of locators we tried to contact.
In order to …

GEODE-7861: Improve error reporting in GMSJoinLeave.join()

---

geode-docs/tools_modules/gfsh/command-pages/export.html.md.erb
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/ExportLogsInterceptor.java
geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/commands/ExportLogsInterceptorTest.java

- Validate the format of the --start-time and --end-time arguments
- Validate that the --start-time and --end-time arguments can be
correctly parsed
- Output the values for --start-time and --end-time as used by the
function to allow users to check that they're as expected when specified
- Update documentation to reflect the new output and better explain the
behaviour when the arguments are provided
- [N/A] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF …

GEODE-8798: Improve output from export logs command

---

geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubNativeRedisAcceptanceTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractPubSubIntegrationTest.java

- It's possible that the test is exhausting the number of available
sockets. Closed connections sit in TIME_WAIT for 60 seconds on Linux.
This change increases the time to get a connection beyond that to
allow for connections to be fully closed and ports to be released.

GEODE-8577: Increase time to get Redis native connection

---

geode-core/src/main/java/org/apache/geode/management/internal/FederatingManager.java

FederatingManager now uses a ReentrantLock instead of synchronization. Remove
the redundant synchronization keywords that result in the deadlock.
This PR fixes the following deadlock:
```
Found one Java-level deadlock:
=============================
"Pooled High Priority Message Processor 5":
waiting to lock monitor 0x00007f3ac400d558 (object 0x00000000fd486c20, a java.util.HashMap),
which is held by "vm_0_thr_0_locator_managing1_host1_13259"
"vm_0_thr_0_locator_managing1_host1_13259":
waiting for ownable synchronizer 0x00000000fd2f3fb0, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
which is held by "DM-MemberEventInvoker"
"DM-MemberEventInvoker":
waiting to lock monitor 0x00007f3af8002d28 (object 0x00000000fd3d12a8, a org.apache.geode.management.internal.FederatingManager), …
```

GEODE-8696: Fix deadlock in FederatingManager

---

geode-docs/basic_config/data_regions/region_naming.html.md.erb

GEODE-8828: State that region names are case sensitive

---

geode-lucene/geode-lucene-test/src/main/java/org/apache/geode/cache/lucene/test/TestPdxObject.java
geode-lucene/src/distributedTest/java/org/apache/geode/cache/lucene/LuceneClientSecurityPostProcessingDUnitTest.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/results/LuceneGetPageFunction.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/results/LuceneGetPageFunctionJUnitTest.java

- Some adjustments to the initial implementation
- This now relies on the principal being available in the
FunctionContext.
- PDX objects are passed directly to the post-processor thus avoiding
any possible serialization issues.
Co-authored-by: Nabarun Nag <nag@cs.wisc.edu>
(cherry picked from commit 8785b84efcabf9a74691ae65d7c1015a9c698893)

GEODE-8795: Lucene queries should utilize post-processing if enabled (#5858)

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Put65.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/Put65Test.java

For persistent region, even though a version tag is not recovered, the possibleDuplicate
flag is still needed to be set for the cleint retry message.

GEODE-8833: Set possible duplicate flag for persistent region

---

geode-docs/basic_config/data_entries_custom_classes/copy_on_read.html.md.erb

I spoke with @boglesby about documenting how to set copy-on-read via the API. We decided that it would be best not to document it.  There's no correct/good way to do it for a production-grade cluster, and the API appears to exist so that a gfsh alter command can use it to set copy-on-read in a way that gets propagated to the cluster's configuration.

GEODE-8829: Improve copy-on-read docs

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
extensions/geode-modules-session-internal/build.gradle
extensions/geode-modules-test/build.gradle
extensions/geode-modules-tomcat7/build.gradle
extensions/geode-modules-tomcat8/build.gradle
extensions/geode-modules-tomcat8/src/test/resources/expected-pom.xml
extensions/geode-modules-tomcat9/build.gradle
extensions/geode-modules-tomcat9/src/test/resources/expected-pom.xml
extensions/geode-modules/build.gradle
extensions/geode-modules/src/test/resources/expected-pom.xml
gradle/publish-java.gradle

- Fixes Geode session state dependencies.
- Fixes module manifest project detection.

GEODE-8590: Cleanup dependencies in the session state modules and GEODE-8732: Update Tomcat9 module to publish to Maven

---

ci/images/google-geode-builder/scripts/setup.sh
ci/pipelines/images/deploy_images_pipeline.sh

* Update Ubuntu to 20.04
* Use docker 19.03.14 because of breaking API changes.

GEODE-8334: Fix an issue with testcontainers because of a change in Docker's API

---

geode-dunit/src/main/java/org/apache/geode/test/dunit/DUnitEnv.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/VM.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/ChildVM.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/ChildVMLauncher.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/DUnitHost.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/DUnitLauncher.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/Master.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/MasterRemote.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/ProcessManager.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/RemoteDUnitVM.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/StandAloneDUnitEnv.java

- This change is intended to address an issue with port bind conflicts
specifically when VMs are restarted. Thus this change only specifies a
specific port when bouncing a VM. In this case we use a RMI port
outside the usual range of ephemeral ports for MacOS (49152–65535) and
Linux (32768-60999).
- We typically try and use ephemeral ports everywhere. However,
sometimes an ephemeral port created during a prior start needs to be
used as a fixed port on subsequent bounces. In this case, ephemeral
ports that are allocated early may end up conflicting with these fixed
ports.
- Remove various unused methods related to bounce()ing VMs.
to ensure the following steps have been …

GEODE-8838: Provide some ability to launch ChildVM with specific port for RemoteDUnitVM stub

---

geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-core/src/main/java/org/apache/geode/internal/cache/execute/FunctionRemoteContext.java
geode-serialization/src/main/java/org/apache/geode/internal/serialization/Version.java

- Also adds KnownVersion.isNewerThanOrEqualTo as synonym to
KnownVersion.isNotOlderThan.

GEODE-8851: FunctionRemoteContext should support version ordinals GEODE_1_12_1 and GEODE_1_13_1

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/ManagementRequestLoggingDistributedTest.java
geode-assembly/src/distributedTest/java/org/apache/geode/rest/internal/web/controllers/RestAPIsAndInterOpsDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/versions/TombstoneDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/cache/client/internal/LocatorTestBase.java

Some tests in ManagementRequestLoggingDistributedTest and
RestAPIsAndInterOpsDUnitTest were using the default JMX port (1099).
Some tests in TombstoneDUnitTest were using the default cache server
port (40404). When these tests run in parallel outside of docker, they
can fail to bind these ports if another test has already bound them.
These tests now assign ports via AvailablePortHelper.

GEODE-8772: Make tests assign ports

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/AbstractHashesIntegrationTest.java

Add missing unit/integration tests for HSETNX. Confirm "WRONGTYPE" error when operating on non-hash keys.

GEODE-8858: unit/integration tests for HSETNX

---

geode-core/src/main/java/org/apache/geode/internal/cache/EntrySnapshot.java
geode-core/src/main/java/org/apache/geode/internal/cache/snapshot/SnapshotPacket.java
geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/ExportDataIntegrationTest.java

Modified test to fail if it attempts to deserialize values during export.
Fixed product export code to no longer deserialize and test now passes.
Co-authored-by: Darrel Schneider <dschneider@vmware.com>
(cherry picked from commit 078ceb0187b718d86d6f6e6ec058d2c743e2655a)

GEODE-8685: change export to not deserialize region values (#5735)

---

geode-docs/tools_modules/redis_api_for_geode.html.md.erb
geode-redis/README.md
geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HstrlenDUnitTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/AbstractHashesIntegrationTest.java

Add DUNIT test for HSTRLEN Redis command, promote to "supported".

Geode-8853: DUNIT tests for HSTRLEN command

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-common/build.gradle
geode-core/build.gradle
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/SocketMessageWriter.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/SocketMessageWriterTest.java

[GEODE-8882](https://issues.apache.org/jira/browse/GEODE-8882)
This new annotation support is documented in the Geode Wiki: https://cwiki.apache.org/confluence/display/GEODE/@NotNull+Annotation
Oh and woopsie! We've already found our first bug via the `@NotNull` annotation:
Under "more actions" I pick:
Where I find this little gem passing a `null` for `clientVersion`:
Which will blow up with the recently-merged-to-`develop` changes from PR #5947 (which removed the null-check in the method of interest.)
Incidentally that call location is `ClientRegistrationMetadata.getAndValidateClientVersion()` where we were unable to ascertain the client's version! In that case our latest code on `develop` will generate an NPE on the server.

GEODE-8882: Enable JetBrains NotNull Annotation

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/MessageDispatcher.java

- For benign exceptions encountered after stopping the MessageDispatcher, do not log the entire Exception stack trace at info level
email to …

GEODE-8873: Do not log stack trace for Exception in MessageDispatcher

---

geode-core/src/main/java/org/apache/geode/distributed/internal/direct/DirectChannel.java
geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java
geode-core/src/main/java/org/apache/geode/internal/tcp/TCPConduit.java
geode-core/src/test/java/org/apache/geode/internal/tcp/TCPConduitTest.java

A NPE was being thrown in TCPConduit.getBufferPool() because the conTable instance
variable is nulled out when the TCPConduit is stopped.  This commit
moves the buffer pool from TCPConduit's conTable object up to the enclosing
DirectChannel object.  This removes the need for DirectChannel to ask
TCPConduit for the buffer pool.

GEODE-8767: NullPointerException in TCPConduit.getBufferPool due to conTable being null

---

geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/AbstractUnknownIntegrationTest.java
geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java

when internal commands are called directly, they should return a helpful
error message

GEODE-8879: add error messages for internal commands

---

geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HMgetDUnitTest.java

previously the threads were not being run. this runs them and adds an
assertion that the fields and values are correct at the end of the test.

GEODE-8898: run threads in HMGetDUnitTest

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt
geode-core/src/integrationTest/java/org/apache/geode/management/internal/beans/DistributedSystemMBeanIntegrationTest.java

1 test fails after this bump.  it appears that the test was capturing a "bad" behavior that is now [prevented](https://github.com/FasterXML/jackson-databind/issues/2683) in Jackson 2.12
to reproduce: `./gradlew :geode-core:integrationTest --tests DistributedSystemMBeanIntegrationTest.queryAllUsingGfshDoesNotFormatDate`

GEODE-8496: Bump jackson from 2.11.3 to 2.12.1

---

geode-assembly/src/acceptanceTest/resources/org/apache/geode/launchers/LocatorLauncherWithCustomLogConfigAcceptanceTest.xml
geode-assembly/src/acceptanceTest/resources/org/apache/geode/launchers/LocatorLauncherWithPulseAndCustomLogConfigAcceptanceTestWithGeodePlugins.xml
geode-assembly/src/acceptanceTest/resources/org/apache/geode/launchers/ServerLauncherWithCustomLogConfigAcceptanceTest.xml
geode-assembly/src/acceptanceTest/resources/org/apache/geode/logging/LocatorWithCustomLogConfigAcceptanceTestWithGeodePlugins.xml
geode-assembly/src/acceptanceTest/resources/org/apache/geode/logging/ServerWithCustomLogConfigAcceptanceTestWithGeodePlugins.xml
geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/RestartOfMemberDistributedTest.java
geode-core/src/test/resources/org/apache/geode/test/golden/log4j2-test.xml
geode-docs/managing/logging/configuring_log4j2.html.md.erb
geode-log4j/src/integrationTest/resources/org/apache/geode/alerting/log4j/internal/impl/AlertAppenderIntegrationTest_log4j2.xml
geode-log4j/src/integrationTest/resources/org/apache/geode/logging/log4j/internal/impl/BothLogWriterAppendersIntegrationTest_log4j2.xml
geode-log4j/src/integrationTest/resources/org/apache/geode/logging/log4j/internal/impl/CacheWithCustomLogConfigIntegrationTest_log4j2.xml
geode-log4j/src/integrationTest/resources/org/apache/geode/logging/log4j/internal/impl/ConfigurationWithLogLevelChangesIntegrationTest_log4j2.xml
geode-log4j/src/integrationTest/resources/org/apache/geode/logging/log4j/internal/impl/DistributedSystemWithBothLogWriterAppendersIntegrationTest_log4j2.xml
geode-log4j/src/integrationTest/resources/org/apache/geode/logging/log4j/internal/impl/DistributedSystemWithLogLevelChangesIntegrationTest_log4j2.xml
geode-log4j/src/integrationTest/resources/org/apache/geode/logging/log4j/internal/impl/GemfireVerboseMarkerFilterAcceptIntegrationTest_log4j2.xml
geode-log4j/src/integrationTest/resources/org/apache/geode/logging/log4j/internal/impl/GemfireVerboseMarkerFilterDenyIntegrationTest_log4j2.xml
geode-log4j/src/integrationTest/resources/org/apache/geode/logging/log4j/internal/impl/GeodeConsoleAppenderIntegrationTest_log4j2.xml
geode-log4j/src/integrationTest/resources/org/apache/geode/logging/log4j/internal/impl/GeodeConsoleAppenderWithCacheIntegrationTest_log4j2.xml
geode-log4j/src/integrationTest/resources/org/apache/geode/logging/log4j/internal/impl/GeodeConsoleAppenderWithSystemOutRuleIntegrationTest_log4j2.xml
geode-log4j/src/integrationTest/resources/org/apache/geode/logging/log4j/internal/impl/GeodeVerboseMarkerFilterAcceptIntegrationTest_log4j2.xml
geode-log4j/src/integrationTest/resources/org/apache/geode/logging/log4j/internal/impl/GeodeVerboseMarkerFilterDenyIntegrationTest_log4j2.xml
geode-log4j/src/integrationTest/resources/org/apache/geode/logging/log4j/internal/impl/LogServiceWithCustomLogConfigIntegrationTest_log4j2.xml
geode-log4j/src/integrationTest/resources/org/apache/geode/logging/log4j/internal/impl/LogWriterAppenderIntegrationTest_log4j2.xml
geode-log4j/src/integrationTest/resources/org/apache/geode/logging/log4j/internal/impl/LogWriterAppenderWithLimitsIntegrationTest_log4j2.xml
geode-log4j/src/integrationTest/resources/org/apache/geode/logging/log4j/internal/impl/LogWriterAppenderWithMemberNameInXmlIntegrationTest_log4j2.xml
geode-log4j/src/integrationTest/resources/org/apache/geode/logging/log4j/internal/impl/SecurityLogWriterAppenderIntegrationTest_log4j2.xml
geode-log4j/src/main/resources/log4j2-cli.xml
geode-log4j/src/main/resources/log4j2.xml
geode-membership/src/integrationTest/resources/log4j2.xml
geode-pulse/src/main/resources/log4j2.xml

This element causes log4j to scan all geode jars on startup. This slows down
the startup time of all geode processes, including gfsh.
It is not necessary because log4j has an annotation processor to generate a
config file that helps it find plugs that it needs.

GEODE-8875: Removing packages element from log4j2 configuration file

---

ci/scripts/shared_utilities.sh

see https://concourse.apachegeode-ci.info/teams/main/pipelines/apache-support-1-13-main/jobs/DistributedTestOpenJDK11/builds/77#L5fc8ddb7:378 ... the only logs produced were not included in the artifacts captured

GEODE-8906: capture additional crash artifacts

---

geode-core/src/test/java/org/apache/geode/cache/util/ObjectsTest.java

Adds testing for Java hashcode for comparison with other languages.
Pairs with https://github.com/apache/geode-native/pull/740

GEODE-8910: Add test of hashcode generation.

---

geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitorJUnitTest.java
geode-membership/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeaveJUnitTest.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitor.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/interfaces/HealthMonitor.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java

We saw multiple failures during network partition when a server on the winning side gets forcefully disconnected. It happens because GMSHealthMonitor.checkIfAvailable() gives the suspect a pass if it's already being checked by another thread. As a result, the losing side locator sends a Network Partition message to the server on the winning side, and the server gets forcefully disconnected.
This change adds a boolean flag to GMSHealthMonitor.checkIfAvailable() that can disable checking if a suspect is already being checked by another thread.
It also changes the behavior of GMSHealthMonitor.processMessage() so that the method ignores network partition messages from non-members.
In order to streamline the review of the contribution we …

GEODE-8901: Surviving side server forcefully disconnected after network drop

---

ci/scripts/rsync_code_down.sh
ci/scripts/shared_utilities.sh

* fix previous PR #5992 to pull in the gradle logs _before_ the rsync

GEODE-8906: capture gradle artifacts too

---

geode-docs/tools_modules/gfsh/command-pages/export.html.md.erb

This PR updates the docs for the code commit already in GEODE-8916.  The single docs change is that the export command (for stack-traces) now operates on all cluster members, not just servers.

GEODE-8916: Update gfsh export stack-traces docs

---

geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/server/MemoryStatsNativeRedisAcceptanceTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractInfoIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractRedisMemoryStatsIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/MemoryStatsIntegrationTest.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/server/InfoExecutor.java

Updates the Geode Redis INFO command to return the new field "maxmemory". (Also fixes an issue with the mem_fragmentation_ratio field, which should always be greater than zero.)

GEODE-8933: update INFO to return maxmemory field

---

gradle/docker.gradle

Change docker.gradle to stop appending the Gradle worker ID onto the
test worker JVM's working directory name. As of GEODE-8637, the working
directory is already unique by the time docker.gradle operates on it,
and appending the worker ID makes the test run in the wrong directory.

GEODE-8942: Fix docker.gradle working dir

---

geode-core/src/distributedTest/java/org/apache/geode/cache/query/partitioned/PRClearCreateIndexDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistributedClearOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionClear.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionClearMessage.java
geode-core/src/test/java/org/apache/geode/internal/cache/BucketRegionJUnitTest.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/MemberStarterRule.java

GEODE-8878: PR clear should also send a lock message to the secondary members.

---

geode-core/src/main/java/org/apache/geode/internal/cache/tx/RemoteOperationMessage.java
geode-core/src/test/java/org/apache/geode/internal/cache/tx/RemoteOperationMessageTest.java

* Only when processing transactional message and when conserve-sockets set to true case, a
separate thread in waiting pool will be used to process the message.
* This is to addresses performance issue if there won't be deadlock.

GEODE-8947: Use waiting thread pool only in limited senario.

---

geode-core/src/main/java/org/apache/geode/distributed/internal/direct/DirectChannel.java
geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java

This PR changes the debug log messages to include the uniqueId of each outgoing Connection.
Before connections are formed, DirectChannel.sendToMany prints out a message and the destinations:
`[debug 2021/02/18 17:00:07.408 CST peergemfire_2_3_host1_69611 <vm_7_thr_17_peer_2_3_host1_69611> tid=0x139] Sending (CloseCacheMessage@65a3824f processorId=11477 sender=192.168.1.74(peergemfire_2_3_host1_69611:69611)<ec><v1>:41005 (processorId=11477)) to 2 peers ([192.168.1.74(peergemfire_2_2_host1_69609:69609)<ec><v2>:41007, 192.168.1.74(peergemfire_2_1_host1_69607:69607)<ec><v1>:41003]) via tcp/ip
`
After connections are formed, it prints them out, including the uids:
`[debug 2021/02/18 17:00:07.408 CST peergemfire_2_3_host1_69611 <vm_7_thr_17_peer_2_3_host1_69611> tid=0x139] Sending on these 2 …

GEODE-8920: Modify debug logging to make it easier to trace a message

---

CODEOWNERS

There are some cache directories that had me as a code owner, but I haven't worked on that code in many years.  A couple of recent PRs made it clear to me that I shouldn't be a required reviewer for those directories.
I've also replaced myself with @mivanac in the directory with the SSL extension parameter.  He wrote that code and should be a reviewer for any changes made to it.

Removing myself from a few code-owner directories

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/DeltaFaultInDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/DeltaForceSizingFlagDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/TestDelta.java
geode-core/src/main/java/org/apache/geode/Delta.java
geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/EntryEventImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/EntryEventImplTest.java

The Redis subsystem uses Deltas heavily, but by default deltas do not trigger an update to the size of their buckets. This leads to incorrect memory usage accounting over the long term, especially with the use of Redis commands like "APPEND". (See GEODE-8859.)
It is possible to set the system property "DELTAS_RECALCULATE_SIZE", but this is a global value that would affect the processing of all deltas, including non-Redis operations.
Instead, this update adds a new default method to the Delta interface, that can be overridden by individual Delta implementations (such as Redis). This triggers the same behavior as DELTAS_RECALCULATE_SIZE, but on a per-delta basis. Thus, other Geode operations will not force bucket size recalculations unless the global property is set, but Redis statistics …

GEODE-8894 allow individual deltas to trigger bucket size recalculation

---

geode-core/src/main/java/org/apache/geode/internal/cache/TXCommitMessage.java
geode-core/src/test/java/org/apache/geode/internal/cache/TXCommitMessageTest.java

GEODE-8964: Entry created via TX putIfAbsent with null value can write incorrect data to cache

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/versions/TombstoneDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/TombstoneService.java

The system would wait, now it does expires it and moves on.

GEODE-8958: When timestamps get corrupted.

---

geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/api/MembershipView.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMembership.java

This change replaces most uses of `latestViewReadLock` with a volatile read of the latestView.
It also makes access to `shutdownMembers` synchronized. Currently, modification of `shutdownMembers` is done under a sync but access isn't synchronized.
GEODE-7245 is an improvement ticket, so it shouldn't require writing new tests.

GEODE-7245: Remove most uses of latestViewReadLock in GMSMembership

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/ClientSideHandshakeImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/ConnectionProxy.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CommandInitializer.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerSideHandshakeFactory.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerSideHandshakeImpl.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/CommandInitializerTest.java
geode-cq/src/upgradeTest/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscBCDUnitTest.java
geode-serialization/src/main/java/org/apache/geode/internal/serialization/KnownVersion.java
geode-serialization/src/test/java/org/apache/geode/internal/serialization/KnownVersionJUnitTest.java

A client's version is used for deserializing data received from the client and for
serializing data sent to the client. It is also used to locate the map of Commands
used to process client requests. Every time we cut a new release we bump this version
in KnownVersions and create a new map of Commands, even though client/server
communications protocols rarely change.
This PR changes KnownVersions to hold a client/server protocol version that is
used to identify clients for command-table selection and serialization rather than
the client's CURRENT_VERSION. …

GEODE-8963: separate client/server compatibility from server/server version compatibility

---

geode-core/src/distributedTest/java/org/apache/geode/cache/snapshot/ParallelSnapshotDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache/snapshot/SnapshotByteArrayDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache/snapshot/SnapshotDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache/snapshot/SnapshotPerformanceDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/snapshot/GFSnapshotDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/snapshot/CacheSnapshotJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/snapshot/RegionSnapshotJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/snapshot/WanSnapshotJUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/snapshot/SnapshotOptions.java
geode-cq/src/distributedTest/java/org/apache/geode/cache/snapshot/ClientSnapshotDUnitTest.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/functions/ExportDataFunction.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/functions/ImportDataFunction.java
geode-lucene/src/distributedTest/java/org/apache/geode/cache/lucene/LuceneIndexDestroyDUnitTest.java

Deprecates old format name.
Creates new format name.

GEODE-8975: Deprecate old format.

---

geode-assembly/build.gradle
geode-assembly/src/distributedTest/java/org/apache/geode/rest/internal/web/controllers/RestAPICompatibilityTest.java
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/CacheRealizationFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/RebalanceFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/functions/CacheRealizationFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/operation/RebalanceOperationPerformer.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt
geode-core/src/test/java/org/apache/geode/management/internal/operation/RebalanceOperationPerformerTest.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/RebalanceCommand.java
geode-gfsh/src/upgradeTest/java/org/apache/geode/management/GfshCompatibilityTest.java

* Moved new child RebalanceFunction and CacheRealizationFunction to pre 1.12.0 locations.
* While talking to pre-1.12.0 servers, the locators send the function from the old package.
* While talking to 1.12.0 server, the new package function is used.
* For RebalanceFunction and CacheRealizationFunction the serialVersionUID is set to the one create by 1.11.0 for old package location and serialVersionUID created by 1.12.0 for the later.
email to …

GEODE-8996: Fixed rebalance gfsh and REST API in mixed version mode

---

geode-core/src/distributedTest/java/org/apache/geode/cache/ThreadMonitorDisabledDistributedTest.java
geode-core/src/main/java/org/apache/geode/internal/monitoring/ThreadsMonitoringImplDummy.java
geode-core/src/main/java/org/apache/geode/internal/monitoring/executor/AbstractExecutor.java
geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java

The P2PReaderExecutorGroup is now called directly since the p2p reader always needs
a non-null instance. When thread monitoring is disabled, the p2p reader will still call
suspend and resume even though the P2PReaderExecutorGroup is not being monitored.
But these calls are very cheap so it is better to call them instead of doing a bunch of
null checks.

GEODE-8998: fix NPE caused by thread-monitor-enabled=false

---

geode-assembly/build.gradle
geode-assembly/src/distributedTest/java/org/apache/geode/rest/internal/web/controllers/RestAPICompatibilityTest.java
geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/CacheRealizationFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/RebalanceFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/functions/CacheRealizationFunction.java
geode-core/src/main/java/org/apache/geode/management/internal/operation/RebalanceOperationPerformer.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt
geode-core/src/test/java/org/apache/geode/management/internal/operation/RebalanceOperationPerformerTest.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/RebalanceCommand.java
geode-gfsh/src/upgradeTest/java/org/apache/geode/management/GfshCompatibilityTest.java

* Moved new child RebalanceFunction and CacheRealizationFunction to pre 1.12.0 locations.
* While talking to pre-1.12.0 servers, the locators send the function from the old package.
* While talking to 1.12.0 server, the new package function is used.
* For RebalanceFunction and CacheRealizationFunction the serialVersionUID is set to the one created by 1.11.0 for old package location and serialVersionUID created by 1.12.0 for the latter.
(cherry picked from commit 3faf283c038880755a7356fe570a4f92a46826cd) …

GEODE-8996: Fixed rebalance gfsh and REST API in mixed version mode 

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/DeltaFaultInDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/DeltaForceSizingFlagDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/TestDelta.java
geode-core/src/main/java/org/apache/geode/Delta.java
geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/EntryEventImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/EntryEventImplTest.java
geode-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/server/MemoryStatsNativeRedisAcceptanceTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/AbstractHashesIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractInfoIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractRedisMemoryStatsIntegrationTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/MemoryStatsIntegrationTest.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/server/InfoExecutor.java

cherry picking redis changes to 1.14 release branch

---

dev-tools/release/create_support_branches.sh
geode-serialization/src/main/java/org/apache/geode/internal/serialization/KnownVersion.java

also fix the comment in KnownVersion to match the new policy in the release scripts to increment by 10 per minor instead of 5

GEODE-8963: fix release scripts to implement revised client serialization version rules

---

geode-core/src/integrationTest/java/org/apache/geode/internal/net/SSLSocketHostNameVerificationIntegrationTest.java

This test was closing a client socket before ensuring that a thread it
had created was finished.  If the socket is closed quickly enough it
could cause that thread to get an IOException and cause the test to
fail.
The fix is to ensure that the thread is finished before closing the
client socket in the tearDown method.  There are many other edits
to remove the use of "this.".
@kamilla1201 

GEODE-8979: CI Failure: SSLSocketHostNameVerificationIntegrationTest

---

geode-core/src/distributedTest/java/org/apache/geode/cache/ThreadMonitorDisabledDistributedTest.java
geode-core/src/main/java/org/apache/geode/internal/monitoring/ThreadsMonitoringImplDummy.java
geode-core/src/main/java/org/apache/geode/internal/monitoring/executor/AbstractExecutor.java

If thread monitoring is enable, the Connection class will not get a DummyExecutor
instead of null thus preventing the NPE.
(cherry picked from commit c650095d74ca0b88a33a1089a0e0caa331b42ea0)

GEODE-8998: fix NPE caused by thread-monitor-enabled=false (#6083)

---

geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeVerifyGatewaySenderProfile.java

Reverting my test out due to presumed interactions with tests in the test class. Working on fixing and re-adding at a later date

GEODE-8886: upgradeTest sometimes fails with new test

---

geode-docs/developing/transactions/design_considerations.html.md.erb

Restore some cautionary text that was removed during an earlier re-write of the transaction section.

GEODE-8953: Re-introduce transaction details regarding non-transactional changes

---

geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/api/Membership.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMembership.java

GMSMembership has a shunnedMembers collection that is used to track the IDs of nodes that are no longer part of the cluster. This collection is no longer needed since we can tell if a node is old by comparing the view ID in its identifier to that of the current view (called latestView in that class. Checks like this are already in place in some parts of the code.
All uses of shunnedMembers should be replaced with this check.
```
MembershipView<ID> view = latestView;
boolean shunned = memberId.getVmViewId() <= view.getViewId() && !view.contains(memberId);
``` …

GEODE-8972: remove shunnedMembers collection from GMSMembership

---

geode-core/src/main/java/org/apache/geode/distributed/internal/locks/DLockGrantor.java
geode-core/src/test/java/org/apache/geode/distributed/internal/locks/DLockGrantorTest.java
geode-core/src/test/java/org/apache/geode/management/internal/LocalManagerTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/realizers/RegionConfigRealizerTest.java

Inspired by @kirklund's email about not using PowerMockito, I saw there were some easy ones to change in 30 minutes, so here's a PR
It is two commits to show the actual change and some cleanup.  The person who merges may squash if they like

GEODE-6143: Use Mockito.when instead of PowerMockito.when

---

geode-core/src/main/java/org/apache/geode/internal/cache/control/HeapMemoryMonitor.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/AllowExecutionInLowMemory.java
geode-redis/src/distributedTest/java/org/apache/geode/redis/OutOfMemoryDUnitTest.java
geode-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisResponse.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/SingleResultRedisFunction.java
geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java

This allows behavior simulating the Redis "noevict" out-of-memory policy. Operations that exceed the Geode configuration value of "critical-heap-percentage" will return a Redis-style "OOM" error message, which clients can respond to.
Because we want to allow things like deleting and expiring Redis keys, this add an "AllowExecutionInLowMemory" interface that allows functions to attempt to execute even in low memory conditions. This way, operations that free memory will be allowed, but operations that attempt to allocate new memory will still fail with LowMemoryException.

GEODE-8965  Support Redis-style OOM error message

---

CODEOWNERS
CODEWATCHERS
ci/pipelines/geode-build/jinja.template.yml

* introduce CODEWATCHERS 
* move docs from owners to watchers as they requested
* add myself and @rhoughton-pivot as watchers for community-owned CODEOWNERS, CODEWATCHERS, and .asf.yml

GEODE-9028: Introduce CODEWATCHERS 

---

geode-docs/developing/function_exec/chapter_overview.html.md.erb

Fix for https://geode.apache.org/docs/guide/113/developing/function_exec/chapter_overview.html
- Removal of the link from the first sentence before the list.
- Chapter sections are shown as part of the list of use cases solved by function execution. I have introduced a sentence just to separate both lists.

GEODE-8343: Fix 'Function execution' main doc page

---

geode-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisService.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/AbstractRedisData.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/ByteArrayWrapper.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisData.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisData.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHash.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisString.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/CommandFunction.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/SingleResultRedisFunction.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/key/RenameFunction.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/SetOptions.java
geode-redis/src/main/java/org/apache/geode/redis/internal/gfsh/RedisCommandFunction.java
geode-redis/src/main/resources/org/apache/geode/redis/internal/sanctioned-geode-redis-serializables.txt
geode-redis/src/test/java/org/apache/geode/redis/internal/data/RedisHashTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSetTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/data/RedisStringTest.java
geode-serialization/src/main/java/org/apache/geode/internal/serialization/DataSerializableFixedID.java

* DataSerializable classes were converted in DataSerializableFixedID
* serialVersionID were added to the unavoidable Serializable classes
(cherry picked from commit 7aae7b8158a0c8aecc15468a81a421bd6ffdc05e)

GEODE-9019: Serialization improvements in geode-redis (#6115)

---

geode-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHash.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisString.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/string/SetOptions.java
geode-redis/src/test/java/org/apache/geode/redis/internal/data/RedisHashTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSetTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/data/RedisStringTest.java

GEODE-9019: Fixed synchronization blocks missed in previous commit 

---

geode-pulse/build.gradle

Removing powermock from build.gradle in geode-pulse. 
No tests use it in this module.

GEODE-6143: Remove powermock from geode-pulse

---

geode-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch

This enables native Redis TCL tests for all of the Hash commands so that they can be run against Geode's compatibility-with-Redis module in the pipeline. This helps ensure that Geode's implementations of the commands match native Redis behavior.

GEODE-9035: Enable Redis TCL tests for all Hash commands

---

geode-redis/src/main/java/org/apache/geode/redis/internal/data/CommandHelper.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisDataStructures.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisData.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHash.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSetCommandsFunctionExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisString.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisStringCommandsFunctionExecutor.java
geode-redis/src/test/java/org/apache/geode/redis/internal/data/RedisHashTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSetTest.java

* NULL_REDIS_STRING, NULL_REDIS_HASH, NULL_REDIS_SET, and NULL_REDIS_DATA are moved to a separate class
* This is done so that super classes do not reference subclasses to avoid class loading deadlocks.

GEODE-9046: Refactor null redis structures to separate classes

---

geode-docs/getting_started/book_intro.html.md.erb

Loose end from previous PR: Add an entry on the top-level Getting Started page to the Upgrade section

GEODE-8946: User Guide - add Upgrade link to Getting Started page

---

geode-gfsh/build.gradle
geode-lucene/build.gradle

- it is no longer needed in those projects
Authored-by: M. Oleske <michael@oleske.engineer>
tagging @DonalEvans and @kirklund  since they have done a lot of the real work recently in removing powermock

GEODE-6143: Remove powermock from gfsh and lucene

---

buildSrc/src/main/java/com/pedjak/gradle/plugins/dockerizedtest/DockerizedExecHandle.java

Increase timeout in the dockerized tests, to avoid timeouts on processes that take a little longer to complete

GEODE-9048 - Increase timeout in the dockerized tests, to avoid timeouts

---

geode-redis/src/main/java/org/apache/geode/redis/internal/data/CommandHelper.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisDataStructures.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisData.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHash.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSetCommandsFunctionExecutor.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisString.java
geode-redis/src/main/java/org/apache/geode/redis/internal/data/RedisStringCommandsFunctionExecutor.java
geode-redis/src/test/java/org/apache/geode/redis/internal/data/RedisHashTest.java
geode-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSetTest.java

* NULL_REDIS_STRING, NULL_REDIS_HASH, NULL_REDIS_SET, and NULL_REDIS_DATA are moved to a separate class
* This is done so that superclasses do not reference subclasses to avoid class loading deadlocks.
(cherry picked from commit 8e1f8a807d9b133cedf69866078415e0ab4d9d60)

GEODE-9046: Refactor null redis structures to separate classes (#6152)

---

CODEWATCHERS
dev-tools/release/create_support_branches.sh
dev-tools/release/set_versions.sh

* drop patch version in docs if 0
* maintain product_version_old_minor
* drop CODEOWNERS and CODEWATCHERS on support branch to avoid confusion

GEODE-9055: drop patch version in docs if 0

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/ssl/CertificateRotationTest.java

The test is overly specific about the cause of the exception being thrown.

GEODE-9017: Fix failing acceptance test in CI

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/ClientSideHandshakeImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/ConnectionProxy.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CommandInitializer.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerSideHandshakeFactory.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/CommandInitializerTest.java
geode-cq/src/upgradeTest/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscBCDUnitTest.java
geode-serialization/src/main/java/org/apache/geode/internal/serialization/KnownVersion.java
geode-serialization/src/test/java/org/apache/geode/internal/serialization/KnownVersionJUnitTest.java

[This will require a subsequent change in develop to update KnownVersion 1.15]
A client's version is used for deserializing data received from the client and for
serializing data sent to the client. It is also used to locate the map of Commands
used to process client requests. Every time we cut a new release we bump this version
in KnownVersions and create a new map of Commands, even though client/server
communications protocols rarely change.
This PR changes KnownVersions to hold a client/server protocol version that is
used to identify clients for command-table selection and serialization rather than
the client's CURRENT_VERSION.
Altered KnownVersions to just mark each version that has client/server
protocol changes rather than store the last one having changes in the
more recent …

GEODE-8963: backport to support/1.14

---

geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/api/Membership.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/api/MembershipView.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMembership.java

Back-porting these 2 fixes together as both of them change the same class (GMSMembership)
GEODE-7245:
This change replaces most uses of `latestViewReadLock` with a volatile read of the `latestView`.
It also makes access to `shutdownMembers` synchronized. Currently, modification of `shutdownMembers` is done under a sync but access isn't synchronized.
(cherry picked from commit [477ffba](https://github.com/apache/geode/commit/477ffba8e155dca0bdeeefd312b6b32b4b481100))
GEODE-8972:
This change removes the `shunnedMembers` collection from `GMSMembership` that is used to track the IDs of nodes that are no longer part of the cluster. This collection is no longer needed since we can tell if a node is old by comparing the view ID in its identifier to that of the current view (called `latestView` …

Back-port GEODE-7245 and GEODE-8972 to support/1.14

---

geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionTest.java

Basically this code was being run to individually get keys for "older versions" that could have been done in bulk except this code didn't have a version limit. Older versions of the correct vintage are not supported anymore so this code should be (have been) removed. Unfortunately older versions for this code mean any previous version, so it was choosing the single entry approach when it should have been using the bulk approach. 
This gets rid of the single approach.

GEODE-9067: register-interest done during rolling upgrade can take longer than needed

---

geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/InequalityQueryWithRebalanceDistributedTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/index/PartitionedIndexJUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/PartitionedIndex.java

(cherry picked from commit d7342cd0266010313a245920dee8e82034593608)

GEODE-9030: Modified PartitionedIndex to reset arbitraryBucketIndex

---

geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/colocation/SingleThreadColocationLogger.java
geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/colocation/SingleThreadColocationLoggerTest.java

(cherry picked from commit d7342cd0266010313a245920dee8e82034593608)

GEODE-9040: Shutdown ExecutorService when the SingleThreadColocationLogger is stopped

---

geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HExistsDUnitTest.java

the timeout for these DUnit tests were set to 1 second. because these
DUnit tests are run through CI, they can have noisy neighbors that can
cause the condition to time out. This test should not be sensitive to
timing like that because DUnits are not the place for performance
testing.

GEODE-9069: increase timeouts for HExistsDUnitTest

---

geode-assembly/build.gradle
geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/TomcatInstall.java
geode-core/src/main/java/org/apache/geode/internal/net/BufferPool.java
geode-unsafe/src/main/java/org/apache/geode/unsafe/internal/sun/nio/ch/DirectBuffer.java
geode-unsafe/src/test/java/org/apache/geode/unsafe/internal/sun/nio/ch/DirectBufferTest.java

* New geode-unsafe access to non-SDK API for DirectBuffer.
* Use geode-unsafe to access DirectBuffer.attachment().
* Removes latency of reflection.
* Removes transient Object[] allocation in Method.invoke().

GEODE-9081: Remove transient allocation.

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java

The previous fix for GEODE-8761 ended up monitoring the thread that created the server connection
instead of the thread that was executing its run() method.
Now the threadMonitorExecutor is created in the run() method
which causes the correct thread id to be set on it.

GEODE-8761: detect stuck ServerConnection threads

---

ci/scripts/execute_redis_tests.sh
geode-redis/src/commonTest/java/org/apache/geode/redis/GeodeRedisServerRule.java
geode-redis/src/commonTest/java/org/apache/geode/test/dunit/rules/RedisClusterStartupRule.java
geode-redis/src/distributedTest/java/org/apache/geode/redis/GeodeRedisServerStartupDUnitTest.java
geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/CrashAndNoRepeatDUnitTest.java
geode-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HashesAndCrashesDUnitTest.java
geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/common/UnsupportedCommandsIntegrationTest.java
geode-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandSupportLevel.java
geode-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
geode-redis/src/main/java/org/apache/geode/redis/internal/netty/Command.java
geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
geode-redis/src/main/java/org/apache/geode/redis/internal/statistics/GeodeRedisStats.java
geode-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java

*update handling of unsupported commands
Co-authored-by: Ray Ingles <ringles@vmware.com>
Co-authored-by: john Hutchison <hutchisonjo@vmware.com>

GEODE-9037: Do not expose unsupported commands in Geode compatibility with Redis

---

geode-core/src/main/java/org/apache/geode/internal/cache/control/HeapMemoryMonitor.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/AllowExecutionInLowMemory.java
geode-redis/src/distributedTest/java/org/apache/geode/redis/OutOfMemoryDUnitTest.java
geode-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisResponse.java
geode-redis/src/main/java/org/apache/geode/redis/internal/executor/SingleResultRedisFunction.java
geode-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java

- Allow execution of Redis commands in low-memory conditions
- Test with large key size to guarantee OOM error
- In tests use multiple key sizes to pack used memory more tightly
- force multiple GCs as memory is filled, add memory-pressure thread in tests
- Add memory pressure to del and expire tests
Co-authored-by: Ray Ingles <ringles@vmware.com>
(cherry picked from commit 08da3aaa1dd3dd5dd212353ecead32819e584c62)

GEODE-8965:  Support Redis-style OOM error message (#6085)

---

geode-core/src/main/java/org/apache/geode/internal/cache/FilterProfile.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionQueryEvaluator.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXEntryState.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXState.java
geode-core/src/main/java/org/apache/geode/internal/cache/TxCallbackEventFactoryImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/BaseCommand.java
geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionQueryEvaluatorTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/TXStateTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/FilterProfileJUnitTest.java
geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/PartitionedRegionTxDUnitTest.java

* Calculate filter routing on tx host node for partitioned regions after tx is applied to cache.
This is to avoid concurrent register interest or cq registration miss the operations either
from snapshot/query results or through client cache update.
* Register interest snapshot taken or cq query with inital results are taken on primary buckets now
to make sure the results are correct.

GEODE-8926: Calculate filter information after tx is applied to cache.

---

geode-core/src/main/java/org/apache/geode/internal/cache/control/HeapMemoryMonitor.java
geode-core/src/main/java/org/apache/geode/internal/cache/control/InternalResourceManager.java
geode-core/src/main/java/org/apache/geode/internal/cache/control/TenuredHeapConsumptionMonitor.java
geode-core/src/test/java/org/apache/geode/internal/cache/control/HeapMemoryMonitorTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/control/TenuredHeapConsumptionMonitorTest.java

This feature prints out the tenured heap in the logs after the garbage collection. It works with JDK 1.8 build 212 and above.

GEODE-9051: Added a feature to measure the Tenured heap consumption

---

ci/images/google-windows-geode-builder/packer.json
ci/pipelines/meta/deploy_meta.sh

As a precursor to right-sizing our Windows instances, we need to know
their resource use. The jobs are not long-lived enough for the GCP
Recommendation system to tell us, so we need our own monitoring. Thus,
add stackdriver, so that we can see the data for memory and details
about CPU use.

GEODE-9080: Add new stackdriver agent to Windows compute images

---

ci/scripts/execute_build.sh
ci/scripts/execute_tests.sh

Change CI scripts to support running parallel DUnit tests with either
Geode's current Gradle 5.5 build or the upcoming Gradle 6.8.3 build.
This allows testing the upgrade to Gradle 6.8.3 in the PR precheckin
pipeline.
Where the current build uses a single command line option
(-PdunitParallelForks) to specify the maximum number of parallel
dockerized test workers, the upcoming build uses two (--max-workers and
-PtestMaxParallelForks).
This commit changes the CI build scripts to specify all three options on
the Gradle command line for parallel DUnit tests. With this commit:
- If the scripts run a Gradle 5.5 build, the old option will configure
the tests, and the new options will have no effect.
- If the scripts run a Gradle 6.8.3 build, the new options will
configure the tests, and the old …

GEODE-8899: Prep CI scripts for upcoming DUnit command line changes

---

geode-core/src/main/java/org/apache/geode/internal/monitoring/executor/AbstractExecutor.java
geode-core/src/test/java/org/apache/geode/internal/monitoring/executor/AbstractExecutorGroupJUnitTest.java

The thread monitor report's stack frames now use "at " to look like a standard JVM stack dump.
If a frame holds a synchronization then it will be followed by a line that says " - locked " and shows the identity of the object synced on.
After the stack a section titled "Locked ownable synchronizers:" will show what locks the thread holds just like a standard JVM stack dump.
Also before the first frame the ThreadState is printed just like a JVM stack dump.
email …

GEODE-8977: include syncs in thread monitor stack

---

geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractLettucePubSubIntegrationTest.java

- Even when we explicitly quit a connection, lettuce seems to want to
reconnect which causes intermittent test failures.

GEODE-9115: Do not have lettuce redis client autoreconnect

---

geode-apis-compatible-with-redis/README.md
geode-docs/tools_modules/geode_apis_compatible_with_redis.html.md.erb

GEODE-9087: redis docs for HSCAN command

---

extensions/geode-modules-test/src/main/java/org/apache/geode/modules/session/catalina/DeltaSessionManagerJUnitTest.java
extensions/geode-modules/src/main/java/org/apache/geode/modules/session/catalina/DeltaSessionManager.java

* GEODE-8513: Remove (de)serialization of local sessions.
Removes query that resulted in casting issue in antlr.
Clears all locally cached entries.
Remove dead code and tests.
(cherry picked from commit d4b9ecd8569281f257e384d397422e7ef4336fb9)

GEODE-8513: Remove (de)serialization of local sessions. (#5532)

---

geode-book/master_middleman/source/subnavs/geode-subnav.erb

Fixes one bad link in the user guide left-hand navigation panel.
Eliminates 537 warnings when generating the user guide.

GEODE-9068: Follow-up to APIs compatible with Redis doc update 

---

geode-gfsh/src/upgradeTest/java/org/apache/geode/management/GfshRebalanceCommandCompatibilityTest.java

* Support for gfsh rebalance compatibilty is from 1.11.0
* Remaining connectivity tests should be run with all other versions.
* In the previous commit for GEODE-8996, the existing tests missed certain versions.

GEODE-8996: Separated the gfsh rebalance test from other tests.

---

geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGAddress.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessenger.java

toString() was including the host name of the address, which is overkill
for the limited use of JGAddress.
JGroupsMessenger's logging that included this class wasn't checking the
log level before invoking logDebug() and other methods.  I've added
that.

GEODE-9128: Remove host name look-up from JGAddress

---

ci/images/alpine-tools/Dockerfile

* Use same image for builder as deployment
* Add py3-yaml package so python doesn't try to build it.

GEODE-9153: Fix alpine-tools docker image

---

dev-tools/release/create_support_branches.sh
dev-tools/release/set_versions.sh

docs would prefer product version to just always be major.minor, not sometimes also patch

Revert "GEODE-9055: drop patch version in docs if 0"

---

ci/scripts/execute_build.sh
ci/scripts/execute_tests.sh

In my earlier commit to upgrade Gradle to v6.8.3, I inadvertently
removed the `-PdunitParallelForks` option from the build and test CI
scripts.
Some PRs do not yet include the Gradle upgrade. Without this option, the
Dockerized tests for those those PRs use only 8 test workers. Those
test tasks will likely time out.
The CI scripts must continue to specify `-PdunitParallelForks=<N>` until
all PRs include the Gradle upgrade. …

GEODE-8899: Temporarily restore dunitParallelForks

---

buildSrc/build.gradle
extensions/geode-modules-session/build.gradle
extensions/session-testing-war/build.gradle
geode-apis-compatible-with-redis/build.gradle
geode-assembly/build.gradle
geode-assembly/geode-assembly-test/build.gradle
geode-concurrency-test/build.gradle
geode-connectors/build.gradle
geode-core/build.gradle
geode-dunit/build.gradle
geode-http-service/build.gradle
geode-junit/build.gradle
geode-logging/build.gradle
geode-lucene/geode-lucene-test/build.gradle
geode-management/build.gradle
geode-membership/build.gradle
geode-pulse/build.gradle
geode-pulse/geode-pulse-test/build.gradle
geode-rebalancer/build.gradle
geode-serialization/build.gradle
geode-wan/build.gradle
geode-web-api/build.gradle
geode-web-management/build.gradle
geode-web/build.gradle
gradle/java.gradle
gradle/test.gradle

- testRuntime to testRuntimeOnly
- some compile to api
- version to archiveVersion
- basename to distributionbasename
Authored-by: M. Oleske <michael@oleske.engineer>
This does not fix all Gradle 7 warnings, but figured a start was better than no start.  I have checked the "Allow edits and access to secrets by maintainers" box, so if there is something else you see that you want to fix, please collaborated and push to this branch.  You can do this without me needing to grant you access to my fork directly.  The other fixes require actual thought to fix instead of just not using the deprecated name.
Please ensure that once …

GEODE-9161: Fix simple Gradle 7 warnings

---

geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGAddress.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessenger.java

(note: the branch for this is misnamed.  It should be feature/GEODE-9128-backport)
toString() was including the host name of the address, which is overkill
for the limited use of JGAddress.  Logging the InetAddress is sufficient to identify
a member.
JGroupsMessenger's logging that included this class wasn't checking the
log level before invoking logDebug() and other methods.  I've added
that.
(cherry picked from commit 8e1c7cdbab0fe806de14355af4dae938f8ddedda) …

GEODE-9128: Remove host name look-up from JGAddress (#6298)

---

geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/NativeRedisClusterTest.java
geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/internal/proxy/ClusterNodesResponseProcessor.java
geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/internal/proxy/ClusterSlotsResponseProcessor.java
geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/internal/proxy/HostPort.java
geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/internal/proxy/MovedResponseHandler.java
geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/internal/proxy/NoopRedisResponseProcessor.java
geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/internal/proxy/RedisProxy.java
geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/internal/proxy/RedisProxyInboundHandler.java
geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/internal/proxy/RedisProxyOutboundHandler.java
geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/internal/proxy/RedisResponseProcessor.java
geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/test/dunit/rules/ClusterNode.java
geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/test/dunit/rules/NativeRedisClusterTestRule.java
geode-apis-compatible-with-redis/src/commonTest/resources/redis-cluster-compose.yml

The fun part here is that some redis commands will respond with internal
IP addresses which need to be rewritten so that clients are able to make
use of them. Currently CLUSTER SLOTS and CLUSTER NODES are implemented
with this functionality. If docker could do host networking on Mac OS, all these
shenanigans could be avoided.

GEODE-9172: Add Junit rule to start docker-based redis cluster

---

CODEOWNERS
CODEWATCHERS

After fixing the overly-broad rule, I added each specific area left unowned to the appropriate existing code area

fix CODEOWNERS rule that was intended to match dependencies only, not tests

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/management/LocatorManagerConfiguresJmxSerialFilterAcceptanceTest.java
geode-assembly/src/acceptanceTest/java/org/apache/geode/management/ServerManagerConfiguresJmxSerialFilterAcceptanceTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/LocatorManagerConfiguresJmxSerialFilterIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/ServerManagerConfiguresJmxSerialFilterIntegrationTest.java
geode-core/src/main/java/org/apache/geode/management/internal/JmxRmiOpenTypesSerialFilter.java
geode-core/src/main/java/org/apache/geode/management/internal/JmxRmiSerialFilter.java
geode-core/src/main/java/org/apache/geode/management/internal/ManagementAgent.java
geode-core/src/main/java/org/apache/geode/management/internal/ManagementAgentFactory.java
geode-core/src/main/java/org/apache/geode/management/internal/SystemManagementService.java
geode-core/src/test/java/org/apache/geode/management/internal/JmxRmiOpenTypesSerialFilterTest.java
geode-core/src/test/java/org/apache/geode/management/internal/SystemManagementServiceTest.java

The Geode JMX layer will configure the system property
“jmx.remote.rmi.server.serial.filter.pattern" to only accept
JDK classes identified as open-types required for JMX.
If the system property already has a value then Geode will log
a statement and leave the system property alone.
[reintroducing this after previously reverting but this was found to not be the cause of any timeout issues]

GEODE-9064: Configure serial filter during ManagementAgent start (#6196)

---

geode-core/src/main/java/org/apache/geode/internal/monitoring/executor/AbstractExecutor.java
geode-core/src/test/java/org/apache/geode/internal/monitoring/executor/AbstractExecutorGroupJUnitTest.java

This reverts commit 903afb5332b06b10e7f53a1abe9c53775a94f39e.
This thread monitor improvement caused members to at times be forced out of the geode cluster because the new getThreadInfo call blocks all threads from running.

Revert "GEODE-8977: include syncs in thread monitor stack (#6248)"

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/management/LocatorManagerConfiguresJmxSerialFilterAcceptanceTest.java
geode-assembly/src/acceptanceTest/java/org/apache/geode/management/ServerManagerConfiguresJmxSerialFilterAcceptanceTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/LocatorManagerConfiguresJmxSerialFilterIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/ServerManagerConfiguresJmxSerialFilterIntegrationTest.java
geode-core/src/main/java/org/apache/geode/management/internal/JmxRmiOpenTypesSerialFilter.java
geode-core/src/main/java/org/apache/geode/management/internal/JmxRmiSerialFilter.java
geode-core/src/main/java/org/apache/geode/management/internal/ManagementAgent.java
geode-core/src/main/java/org/apache/geode/management/internal/ManagementAgentFactory.java
geode-core/src/main/java/org/apache/geode/management/internal/SystemManagementService.java
geode-core/src/test/java/org/apache/geode/management/internal/JmxRmiOpenTypesSerialFilterTest.java
geode-core/src/test/java/org/apache/geode/management/internal/SystemManagementServiceTest.java
geode-junit/build.gradle
geode-junit/src/main/java/org/apache/geode/test/junit/rules/CloseableReference.java
geode-junit/src/test/java/org/apache/geode/test/junit/rules/CloseableReferenceTest.java

The Geode JMX layer will configure the system property
“jmx.remote.rmi.server.serial.filter.pattern" to only accept
JDK classes identified as open-types required for JMX.
If the system property already has a value then Geode will log
a statement and leave the system property alone.
(cherry picked from commit b280355a22a77efd90bed49626998aea5bc800f1)

GEODE-9064: Configure serial filter during ManagementAgent start

---

ci/scripts/repeat-new-tests.sh

a revert PR or a module refactoring are common scenarios where tests may appear as deleted, so StressNew shouldn't try to run them

GEODE-9197: don't stress deleted tests

---

geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb

Documentation wrongly states that `end-port` value is not included on the port range in which gateway receivers will randomly select a port when they are created.

GEODE-5337: End-port is not exclusive when creating a gw receiver

---

geode-assembly/build.gradle
geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/CargoTestBase.java
geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Jetty9CachingClientServerTest.java

GEODE-8990: Add await logic to prevent CargoTestBase tests from running before members

---

extensions/geode-modules-assembly/build.gradle
extensions/geode-modules-session/build.gradle
geode-assembly/build.gradle
geode-core/build.gradle

- use non deprecated naming of variables
Authored-by: M. Oleske <michael@oleske.engineer>
There are two gradle warnings about property names that are deprecated that seem to keep breaking things in ways I don't understand.  They are
```console
The AbstractArchiveTask.version property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the archiveVersion property instead. See https://docs.gradle.org/6.8.3/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:version for more details.
at build_6euirgls21gn4lcb28jgunnoc$_run_closure6$_closure48$_closure50.doCall(/Users/pivotal/workspace/geode/extensions/geode-modules-assembly/build.gradle:209)
(Run with --stacktrace to get the full stack trace of this …
```

GEODE-9161: Fix some more gradle 7 warnings

---

geode-docs/tools_modules/gfsh/command-pages/list.html.md.erb
geode-docs/topologies_and_comm/multi_site_configuration/setting_up_a_multisite_system.html.md.erb

`list gateways` command had no output example in the documentation. This PR also fixes other formatting errors in the `list.html.md.erb` file

GEODE-4709: Add list gateways output sample in UG

---

geode-core/src/integrationTest/java/org/apache/geode/internal/net/SSLSocketHostNameVerificationIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/net/SSLSocketIntegrationTest.java
geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
geode-core/src/main/java/org/apache/geode/internal/net/BufferPool.java
geode-core/src/main/java/org/apache/geode/internal/net/ByteBufferSharing.java
geode-core/src/main/java/org/apache/geode/internal/net/ByteBufferSharingNoOp.java
geode-core/src/main/java/org/apache/geode/internal/net/ByteBufferVendor.java
geode-core/src/main/java/org/apache/geode/internal/net/NioSslEngine.java
geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
geode-core/src/test/java/org/apache/geode/internal/net/ByteBufferConcurrencyTest.java
geode-core/src/test/java/org/apache/geode/internal/net/ByteBufferVendorTest.java
geode-core/src/test/java/org/apache/geode/internal/net/NioSslEngineTest.java
geode-core/src/test/java/org/apache/geode/internal/tcp/ConnectionTest.java

@bschuchardt has a PR https://github.com/apache/geode/pull/6314 to fix this same ticket and his PR is passing all tests.
Bruce's PR adds protection (under `stateLock`) for the `inputBuffer`. This PR takes an alternate approach. It reuses the `ByteBufferSharing` framework we introduced last year to fix GEODE-8652. The GEODE-8652 work applied the framework in the `NioFilter` (and related classes) to protect the input and output buffers in the `NioSslEngine`. This PR applies the same idea at the (lower) `Connection` level, to protect the `Connections` input buffer (input from the network).
A nice thing about the `ByteBufferSharing` framework is that it takes control of buffer resizing. This let us consolidate the resizing code, eliminating redundancy.
Before this PR, the class that is now …

GEODE-9141: fixed via ByteBufferSharing on Connection input buffer

---

geode-core/src/integrationTest/java/org/apache/geode/internal/monitoring/ThreadsMonitoringIntegrationTest.java
geode-core/src/main/java/org/apache/geode/internal/monitoring/ThreadsMonitoringProcess.java
geode-core/src/main/java/org/apache/geode/internal/monitoring/executor/AbstractExecutor.java
geode-core/src/main/java/org/apache/geode/internal/monitoring/executor/SuspendableExecutor.java
geode-core/src/test/java/org/apache/geode/internal/monitoring/executor/AbstractExecutorGroupJUnitTest.java

This fix looks the same as the previous fix for GEODE-8977 but it performs much better.
The expensive form of getThreadInfo (the one that requests lock info) is now called at
most once each time the thread monitor wakes up. Before it was called at least once for every
thread that was stuck. With a high number of stuck threads this could cause operations like the
membership heartbeat to timeout resulting in a forced disconnect.

GEODE-8977: improve thread monitor to log lock information

---

extensions/geode-modules-assembly/build.gradle
geode-assembly/build.gradle

- remember friends that if you switch from string to property, you need
a `.get()`
Authored-by: M. Oleske <michael@oleske.engineer>

GEODE-9161: Use not deperacted property in gradle build

---

ci/scripts/repeat-new-tests.sh

When detecting which tests to run for StressNewTest, we use paths like the following:
```
'*/src/distributedTest/java'
```
This will pick up a file like this one:
```
geode-assembly/src/distributedTest/java/org/apache/geode/session/tests/Jetty9CachingClientServerTest.java
```
But won't pick up this file since the `src` dir here is more than one directory deep:
```
extensions/geode-modules/src/distributedTest/java/org/apache/geode/modules/util/ClientServerSessionCacheDUnitTest.java 
```
We can use git's pathspec `:glob` keyword described [here](https://git-scm.com/docs/gitglossary) to pick up any number of directories preceding our desired path:
```
':(glob)**/src/distributedTest/java/**'
```

GEODE-9208: Allow StressNewTest to pick up tests from all directories

---

geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/hash/HGetDUnitTest.java

* Similar to the previous commit for GEODE-9069, the timeout is increased for HGetDUnitTest

GEODE-9069: Increasing the timeout in HGetDUnitTest

---

geode-assembly/src/distributedTest/java/org/apache/geode/rest/internal/web/controllers/RestAPIsWithSSLDUnitTest.java
geode-assembly/src/integrationTest/java/org/apache/geode/rest/internal/web/RestSecurityWithSSLTest.java
geode-core/src/distributedTest/java/org/apache/geode/distributed/LocatorDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/management/JMXMBeanDUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/net/SSLUtilTest.java
geode-core/src/test/java/org/apache/geode/internal/net/SocketCreatorFactoryJUnitTest.java

Recent versions of JDK11 and 8 have disabled TLSv1 and TLSv1.1 by default.
We shouldn't be using these protocols so we shouldn't be testing them anymore either.

GEODE-9218: Remove TLSv1 and TLSv1.1 from tests.

---

ci/pipelines/pull-request/jinja.template.yml
ci/pipelines/shared/jinja.variables.yml

recently a number of tests have been added that seem to be flaky on JDK8 only.  Since the PR pipeline only tests on JDK11, these were not being caught.  Adding back JDK8 testing at the PR stage should help.

GEODE-9231: increase pipeline quotas and add Distributed and StressNew for JDK8 to PR pipeline

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/event/DistributedEventTrackerIntegrationTest.java

This test is being ignored because windows tests are failing with:
```
java.io.FileNotFoundException: C:\Users\geode\geode\geode-core\build\integrationTest\test-worker-000283\server.log (Access is denied)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.open(FileOutputStream.java:270)
at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
at org.apache.geode.internal.logging.ManagerLogWriterFactory.createPrintStream(ManagerLogWriterFactory.java:131)
```
I'm working on a fix.
submit an update to your PR as …

GEODE-9138: Ignore failing test

---

geode-assembly/build.gradle

Might fix issues we've seen on support/1.14 with classes not in classpath during execution. We'll run a few test iterations and see how this goes...

force all upgradeTest and integrationTest tasks to depend on installDist

---

geode-core/src/integrationTest/java/org/apache/geode/internal/net/SSLSocketHostNameVerificationIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/net/SSLSocketIntegrationTest.java
geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
geode-core/src/main/java/org/apache/geode/internal/net/ByteBufferSharing.java
geode-core/src/main/java/org/apache/geode/internal/net/ByteBufferSharingNoOp.java
geode-core/src/main/java/org/apache/geode/internal/net/ByteBufferVendor.java
geode-core/src/main/java/org/apache/geode/internal/net/NioSslEngine.java
geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
geode-core/src/test/java/org/apache/geode/internal/net/ByteBufferConcurrencyTest.java
geode-core/src/test/java/org/apache/geode/internal/net/ByteBufferVendorTest.java
geode-core/src/test/java/org/apache/geode/internal/net/NioSslEngineTest.java
geode-core/src/test/java/org/apache/geode/internal/tcp/ConnectionTest.java

This PR has two cherry-picked commits that both need to be retained.
**Do not squash-and-merge**
**use rebase-and-merge**

GEODE-9141: (back-port to support/1.14) Hang while shutting down a cache server due to corrupted message

---

geode-apis-compatible-with-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/GeodeServerRunTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/PassiveExpirationManager.java

change the interval in the PassiveExpirationManager from 1 second to 3
minutes. this significantly reduces the CPU load of passive expiration.
this change requires that one redis test must be commented out in the
patch file.

GEODE-9155: Change frequency of passive expiration

---

geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/hash/MemoryOverheadNativeRedisAcceptanceTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/AbstractMemoryOverheadIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/MemoryOverheadIntegrationTest.java
geode-core/src/main/java/org/apache/geode/internal/size/ObjectGraphSizer.java
gradle/test.gradle

Adding integration tests that measure the memory overhead of both native redis
and radish.  These tests measure the memory used before and after adding
entries. They assert that the measured per entry overhead is within 1 byte of
the expected per entry overhead. They are measuring the all of the overhead -
whether it's from geode region entries or our radish data structures.
These are essentially the same tests from the feature/redis-memory-overhead
branch, but with assertions added that our expected overhead didn't change.

GEODE-9217: Adding memory overhead tests for redis

---

buildSrc/src/main/resources/japicmp_exceptions.json
geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/StartServerCommand.java

* GEODE-9162: Mark Radish as experimental
- make redis properties in ConfigurationProperties experimental
- add experimental annotation to cli strings
- add experimental marker to help messages
* recommended changes
- add @experimental annotation to ConfigurationProperties.java
- remove @experimental annotation from internal class (CliStrings.java)
* chnage wording based on docs team reccomendations
(cherry picked from commit de8cfe49a37681a741f116c1bd33eb9347a62493) …

GEODE-9162: Mark Radish as experimental (#6367)

---

ci/images/google-windows-geode-builder/packer.json
ci/scripts/rsync_code_down.sh

* DRY the commands per platform.
* Use tar-pipe over ssh, instead of bad windows rsync
* Delete some gradle cache files that are not part of this build

GEODE-9244: Improve the rsync_code_down CI script

---

CODEOWNERS

* add missing package to dlock section
* add missing sanctionedDataSerializables.txt and excludedClasses.txt to serialization section
* add missing apache license.txt to licenses section
* re-order rules where a more-general catchall was inadvertently overriding more-specific targeted rules

Fix codeowners rules that weren't capturing what they were intended to

---

geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/key/ExistsDUnitTest.java
geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/key/ExpireDUnitTest.java
geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/key/PersistDUnitTest.java

This reverts commit 8be8ebf010e8e6a7de3cadab4994655e9692359c.

Revert "GEODE-9239: Update PersistDUnitTest to use JedisCluster (#6438)"

---

geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/index/CompactRangeIndexJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/index/IndexMaintenanceJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/index/IndexStatisticsJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/index/MapRangeIndexMaintenanceJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/query/partitioned/PRIndexStatisticsJUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledComparison.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/AbstractMapIndex.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/CompactMapRangeIndex.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/IndexManager.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/MemoryIndexStore.java
geode-core/src/test/java/org/apache/geode/cache/query/internal/CompiledComparisonTest.java
geode-docs/developing/query_index/creating_map_indexes.html.md.erb
geode-junit/src/main/java/org/apache/geode/cache/query/data/Portfolio.java

Queries in which map fields are involved
in the condition, sometimes do not return the same entries
if map indexes are used, compared to when map indexes
are not used.
Differences were found when the condition on the
map field was of type '!=' and also when the condition
on the map field was comparing the value with null.
Example1:
Running a query with the following condition:
positions['SUN'] = null
in a region with the following entries:
entry1.positions=null
entry2.positions={'a'=>'b'}
entry3.positions={'SUN'=>null}
- will return entry1 and entry3 if there are no
indexes defined.
- will return no entries if the following index is defined:
positions['SUN','c']
- will return entry3 if the following index is defined:
positions[*]
Example2:
Running a query with the following condition: …

GEODE-9004: Align results of queries with and without map indexes

---

geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/string/StringsDUnitTest.java

- change all Jedis clients to JedisCluster Clients
- change some tests to use ConcurrentLoopingThreads.runInLockStep where appropriate
- reword test names to reflect what is now being tested in cluster mode

GEODE-9199: Restructure String Dunit tests to work with compatible with Redis cluster mode

---

geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/test/dunit/rules/RedisClusterStartupRule.java
geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/data/PartitionedRegionStatsUpdateTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/MemoryOverheadIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AbstractAppendIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisService.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/AbstractRedisData.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisData.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisData.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHash.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisString.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisHashTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSetTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisStringTest.java

- make RedisData implement Sizeable
- reimplement delta force recalculate size
- add tests for hash add/remove/edit wo size change
- add tests for string add/append/remove/edit wo size change
- add tests for set add/remove/edit wo size change
- add tests to verify our math is right
- keep track of the data size as part of RedisHash, RedisString,
and RedisSet
Signed-off-by: Ray Ingles <ringles@vmware.com>

GEODE-9136: make RedisData implement Sizeable

---

gradle/test.gradle

Repeat test tasks are now configured to `forkEvery 1` in order to run
each test class in a fresh test worker JVM. Many of the tests run by
these tasks leave the JVM in a state that other test classes cannot
tolerate.

GEODE-9260: One test class per JVM in repeat tests

---

gradle/publish-common.gradle

We have not implemented this for geode-all-bom, so the .module file is
incomplete for downstream projects compared to the .pom.

Disable Gradle-metadata-module publishing.

---

geode-apis-compatible-with-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/GeodeServerRunTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/PassiveExpirationManager.java

* GEODE-9155: Change frequency of passive expiration
change the interval in the PassiveExpirationManager from 1 second to 3
minutes. this significantly reduces the CPU load of passive expiration.
this change requires that one redis test must be commented out in the
patch file.
* use the keys command instead of hkeys. hkeys increments the hit/miss stats, which the test is sensitive to
(cherry picked from commit 113aa7d487e2cf717cfbeb986114f28f6d988932)
email to …

GEODE-9155: Change frequency of passive expiration (#6419)

---

geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/server/MemoryStatsNativeRedisAcceptanceTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractRedisMemoryStatsIntegrationTest.java

- move test to only be run against apis-compatable-with-redis
- rename test be more specific

GEODE-9006: fix flaky native Redis memory usage test

---

geode-core/src/main/java/org/apache/geode/distributed/internal/locks/DLockGrantor.java
geode-core/src/test/java/org/apache/geode/distributed/internal/locks/DLockGrantorTest.java

* When handling TXLockService, always trying to acquire destroy read lock
before getting the synchronized batchLocks.
* If destroy read lock is not acuried, thread will wait until the grantor
is destoryed.

GEODE-9269: Make the lock holding has the same order.

---

geode-apis-compatible-with-redis/build.gradle
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/AbstractHScanIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/HScanIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/MemoryOverheadIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/collections/Object2ObjectOpenCustomHashMapWithCursor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHash.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHashCommandsFunctionExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/CommandFunction.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HScanExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/RedisHashCommands.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/RedisHashCommandsFunctionInvoker.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/Client.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/collections/Object2ObjectOpenCustomHashMapWithCursorQuickCheckTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/collections/Object2ObjectOpenCustomHashMapWithCursorTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisHashTest.java

Adding a new subclass, Object2ObjectOpenCustomHashMapWithCursor, that
implements the redis HSCAN operation. This method uses the same algorithm as
redis by incrementing the reverse of the cursor for each step. See
https://github.com/redis/redis/blob/e504583b7806d946da9c3627784d551a742be4d0/src/dict.c#L651
Replacing our stateful hscan implementation with a stateless implementation
based on the same algorithm as redis. This uses the stateless cursor method above.

GEODE-9256: Use a stateless hscan implementation

---

ci/pipelines/geode-build/jinja.template.yml

GEODE-9278: Increase timeout for rsync_down task

---

geode-core/src/main/java/org/apache/geode/management/DistributedRegionMXBean.java
geode-core/src/main/java/org/apache/geode/management/RegionMXBean.java
geode-docs/tools_modules/pulse/pulse-views.html.md.erb

Descriptions of EntrySize for Pulse, RegionMXBean, and DistributedRegionMXBean are inconsistent in the user guide and the javadocs.
This PR reconciles those differences by modifying one user guide source and two sets of javadocs embedded in source code comments.
Note that the DistributedRegionMXBean description used to say the value was reported in megabytes, but now says bytes like the other two passages.

GEODE-9224: Resolve doc discrepancy on region's entrysize description

---

geode-apis-compatible-with-redis/build.gradle
geode-apis-compatible-with-redis/src/jmh/java/org/apache/geode/redis/internal/collections/Object2ObjectOpenCustomHashmapWithCursorBenchmark.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/collections/Object2ObjectOpenCustomHashMapWithCursor.java

The test compares the performance of the cursor with the performance
of an iterator. Although the cursor is about an order of magnitude
slower than an iterator, the iteration time still looks like it's
O(1) - eg the time to iterate per entry does not go up with the
number of entries.
Tweaking the name of the elementAtHashesTo method, based on feedback from the
last PR. Trying to make that code a little more readable.

GEODE-9256: Adding a jmh test of the Object2ObjectOpenCustomHashmapWithCursor

---

ci/pipelines/shared/jinja.variables.yml

Ignores new Redis protocol benchmarks that require different topology.

Only run Geode protocol benchmarks.

---

geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/test/dunit/rules/RedisClusterStartupRule.java
geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/data/DeltaDUnitTest.java
geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/cluster/ClusterSlotsAndNodesDUnitTest.java
geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionExpirationDUnitTest.java
geode-apis-compatible-with-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
geode-apis-compatible-with-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisService.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RegionProvider.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/SlotAdvisor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/cluster/RedisMemberInfo.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/cluster/RedisMemberInfoRetrievalFunction.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHashCommandsFunctionExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisKey.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/Executor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/cluster/ClusterExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/cluster/RedisPartitionResolver.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/Command.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/NettyRedisServer.java
geode-apis-compatible-with-redis/src/main/resources/org/apache/geode/redis/internal/sanctioned-geode-apis-compatible-with-redis-serializables.txt
geode-serialization/src/main/java/org/apache/geode/internal/serialization/DataSerializableFixedID.java

We're currently using a function to pull bucket/slot info from each
member. However, members already contain the most current view of bucket
locations so we should use that instead. This will avoid an unnecessary
fn call as well as providing more up-to-date information.
This commit introduces a `SlotAdvisor` which is intended to be the
central point of information regarding buckets/slots/members. This will
also be used to support the MOVED response.
email to …

GEODE-9265: Introduce redis SlotAdvisor to manage slot information

---

geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionsAndCrashesDUnitTest.java

Change `SessionsAndCrashesDUnitTest` to assign its test app's server
port, rather than using Spring's fixed default server port 8080.
PROBLEM
`SessionsAndCrashesDUnitTest` was running its test app using Spring's
fixed default server port 8080.  If this test runs outside of Docker,
the fixed default port may be in use in another test.

GEODE-8772: SessionsAndCrashesDUnitTest assign app port

---

geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/MemberStarterRule.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/ServerStarterRule.java

Change `ClusterStartupRule` to assign ports only in the test JVM.
BACKGROUND
==========
As part of my project to allow Geode tests to run in parallel outside of
Docker, I am changing our build system to allocate a distinct range of
ports to each test JVM, and changing `AvailablePort` and
`AvailablePortHelper` to honor these allocated port ranges.
This commit prepares for those changes.
PROBLEM
=======
Certain tests use `ClusterStartupRule` to start a member in a child VM
using a prior version of Geode.  When such tests run in parallel outside
of Docker, the child VM can attempt to bind to ports that are in use by
tests in other JVMs.
CAUSE
=====
When the `ClusterStartupRule` starts a member in a child VM, it does so
by creating the appropriate member starter rule (`LocatorStarterRule` or …

GEODE-8772: Pre-assign ports in the test JVM

---

geode-core/src/main/java/org/apache/geode/distributed/internal/locks/DLockGrantor.java
geode-core/src/test/java/org/apache/geode/distributed/internal/locks/DLockGrantorTest.java

* When handling TXLockService, always trying to acquire destroy read lock
before getting the synchronized batchLocks.
* If destroy read lock is not acquired, thread will wait until the grantor
is destroyed.
(cherry picked from commit 235cd1b6529f292db0212f212245308e6ebe518b)

GEODE-9269: Make the lock holding has the same order. (#6470)

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/EntriesDoNotExpireDuringGiiRegressionTest.java

The test was asserting that we did more than 100 expirations.
But race conditions exist that allow the test to do exactly 100 expirations.
Since this test is only meant to make sure that expirations are disabled during GII,
I changed the assertion to allow 100 or more expirations.
I also added an assertion that all invalidates should be from expiration.

GEODE-6685: fix flaky test

---

geode-core/src/main/java/org/apache/geode/internal/cache/LatestLastAccessTimeMessage.java
geode-core/src/test/java/org/apache/geode/internal/cache/LatestLastAccessTimeMessageTest.java

The process method on LatestLastAccessTimeMessage 
will now send a reply of zero when it finds a null cache, region, or entry.
This will prevent the thread that sent the message from waiting forever for a reply.

GEODE-9295: prevent expiry message hangs

---

geode-core/src/main/java/org/apache/geode/internal/statistics/ResourceInstance.java
geode-core/src/main/java/org/apache/geode/internal/statistics/SampleCollector.java
geode-core/src/main/java/org/apache/geode/internal/statistics/StatArchiveWriter.java
geode-core/src/main/java/org/apache/geode/internal/statistics/ValueMonitor.java
geode-core/src/test/java/org/apache/geode/internal/statistics/SampleCollectorTest.java

It seems that in some cases, creation of buckets of colocated region can take some time to finish. Until it is finished, recovery threads are updating statistics, but since ValueMonitor is not notified to monitor PartitionedRegionStats (this will happen when creation of region is finished), this info is not propagated. When finally creation of region is finished, SampleCollector will interpret stats as old info, and will not propagate it. 
- [*] Has your PR been rebased against the latest commit within the target branch (typically …

GEODE-8191: update flaky test

---

CODEWATCHERS

also adds a few lines of explanatory detail at the top.  this PR is also a test to confirm that watchers are not added until PR has exited draft mode.

clean up CODEWATCHERS formatting

---

dev-tools/progress/.gitignore
dev-tools/progress/INSTALLATION.md
dev-tools/progress/README.md
dev-tools/progress/go.mod
dev-tools/progress/internal/cli/cli.go
dev-tools/progress/internal/progress/build.go
dev-tools/progress/internal/progress/cmd.go
dev-tools/progress/internal/progress/event.go
dev-tools/progress/internal/progress/filter.go
dev-tools/progress/internal/progress/filter_test.go
dev-tools/progress/internal/progress/find.go
dev-tools/progress/internal/progress/find_test.go
dev-tools/progress/internal/progress/format.go
dev-tools/progress/internal/progress/json.go
dev-tools/progress/main.go
gradle/rat.gradle

Add a `progress` tool to find, filter, and format information from Geode
test progress files.
INSTALLATION.md describes how to install the tool.
README.md gives detailed examples of how to use the tool.
Running `progress -h` concisely describes the options for finding,
filtering, and formating test results from progress files.

GEODE-9309: Tool to filter/format progress info

---

geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/SingleResultRedisFunction.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/AllowExecutionInLowMemory.java

The current implementation assumes that the function inputs are always
Object[] and don't allow for specifying them generically.

GEODE-9313: Allow AllowExecutionInLowMemory to be usable generically

---

geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/cluster/ClusterSlotsAndNodesDUnitTest.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/SlotAdvisor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/cluster/ClusterExecutor.java

- Node information may be reported incorrectly. Specifically, host/port
info may end up being duplicated between nodes (in the output).

GEODE-9314: Redis CLUSTER NODES incorrect when primary buckets are moving

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscDUnitTest.java
geode-cq/src/upgradeTest/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscBCDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscDUnitTestBase.java

Change `ClientServerMiscDUnitTestBase`, `ClientServerMiscDUnitTest`, and
`ClientServerMiscBCDUnitTest` to assign ports only in the test JVM.
BACKGROUND
As part of my project to allow Geode tests to run in parallel outside of
Docker, I am changing our build system to allocate a distinct range of
ports to each test JVM, and changing `AvailablePort` and
`AvailablePortHelper` to honor these allocated port ranges.
This commit prepares for those changes.
PROBLEM
To test compatibility, `ClientServerMiscDUnitTestBase` executes
`createServerCache()` in a child VMs running old versions of Geode. The
`createServerCache()` method assigns a server port via
`AvailablePortHelper`.  The old implementation of `AvailablePortHelper`
in the child VM does not honor the range of ports allocated to the child …

GEODE-8772: ClientServer test port assignment

---

geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeCreateGatewaySenderMixedSiteOneCurrentSiteTwo.java
geode-wan/src/upgradeTest/java/org/apache/geode/cache/wan/WANRollingUpgradeDUnitTest.java

Change `WANRollingUpgradeDUnitTest` and
`WANRollingUpgradeCreateSenderGatewaySenderMixedSiteOneCurrentSiteTwo`
to assign ports only in the test JVM.
BACKGROUND
As part of my project to allow Geode tests to run in parallel outside of
Docker, I am changing our build system to allocate a distinct range of
ports to each test JVM, and changing `AvailablePort` and
`AvailablePortHelper` to honor these allocated port ranges.
This commit prepares for those changes.
PROBLEM
- `WANRollingUpgradeCreateSenderGatewaySenderMixedSiteOneCurrentSiteTwo`
calls `startLocatorWithJmxManager()` in a child VM running a prior
version of Geode. This method then calls `AvailablePortHelper` to get
a JMX manager port.
- `WANRollingUpgradeDUnitTest` calls `addCacheServer()` in a child VM
running a prior version of …

GEODE-8772: WAN upgrade test port assignment

---

geode-apis-compatible-with-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch
geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/RedisDistDUnitTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/MemoryOverheadIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RegionProvider.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSetCommandsFunctionExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/delta/AddsDeltaInfo.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/delta/RemsDeltaInfo.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/CommandFunction.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/RedisSetCommands.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/RedisSetCommandsFunctionInvoker.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SAddExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SCardExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SDiffExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SInterExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SIsMemberExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SMembersExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SMoveExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SPopExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SRandMemberExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SRemExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SScanExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SUnionExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SetExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SetOpExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSetTest.java

- Replace uses of ByteArrayWrapper with byte[] in RedisSet,
NullRedisSet and other Set-related classes
- Replace internal Set in RedisSet with fastutil
ObjectOpenCustomHashSet
- Replace the membersAddAll and membersRemoveAll methods with looped
calls to membersAdd and membersRemove, as ObjectOpenCustomHashSet does
not implement addAll and removeAll, which causes errors when comparing
the contents of Sets
- Replace uses of implementations with interfaces where possible
- These changes break the sizing tests, but these tests have been
determined to be inconsistent due to the current implementation of
sizeable in RedisSet. GEODE-9279 will address the issues with sizeable
in a future commit …

GEODE-9222: Remove ByteArrayWrapper from RedisSet

---

geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/ClientServerTransactionFailoverWithMixedVersionServersDistributedTest.java

PROBLEM
`ClientServerTransactionFailoverWithMixedVersionServersDistributedTest`
launches a locator with HTTP service enabled on the default port (7070).
If these tests run in parallel outside of docker, each locator tries to
bind the HTTP service to port 7070, and all but the first will fail.
This happens even though the tests do not need the HTTP service.
THIS COMMIT
Starts the locators with HTTP service disabled.

GEODE-8772: Disable HTTP service in Client Server TX test

---

CODEOWNERS
CODEWATCHERS

* for consistency use canonical usernames throughout
* clean up overly-broad rule now that dev-tools has more in it
* add Robert for more ci ownership

tidy CODEOWNERS

---

dev-tools/progress/internal/progress/build.go
dev-tools/progress/internal/progress/build_test.go

If a test has no end event, report its duration as 0 instead of
negative.

GEODE-9309: Fix progress tool duration calc

---

geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RegionProvider.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
geode-core/src/upgradeTest/java/org/apache/geode/ClusterCommunicationsDUnitTest.java

Change `ClusterCommunicationsDUnitTest` to assign the locator port in
the test JVM and to not start the HTTP service.
BACKGROUND
I am working on a project to allow Geode tests to run in parallel
outside of Docker. Running in parallel outside of Docker requires tests:
- To assign ports only in the test JVM, to ensure that ports are
assigned only by the latest implementation of `AvailablePortHelper`,
which knows how to allocate a unique range of ports to each test.
- Not to start services using default ports, to ensure that no two tests
try to use a default port at the same time.
This commit prepares for those changes.
PROBLEMS
`ClusterCommunicationsDUnitTest` inhibits running in parallel outside of
Docker in two ways:
- It calls `createLocator()` in child VMs running prior versions of …

GEODE-8772: Fix ClusterComms test port conflicts

---

.asf.yaml
ci/pipelines/examples/jinja.template.yml
ci/pipelines/geode-build/jinja.template.yml
ci/pipelines/images/jinja.template.yml
ci/pipelines/mass-test-run/jinja.template.yml
ci/pipelines/pull-request/jinja.template.yml
ci/pipelines/reaper/jinja.template.yml
ci/pipelines/shared/jinja.variables.yml
dev-tools/release/deploy_rc_pipeline.sh

Merging this PR will wipe Concourse history due to pipeline and/or job
name changes.

GEODE-9298: remove concourse deprecation warnings

---

geode-assembly/build.gradle

Using spotlessApply as an input to srcDistTar allowed `build` and other
CI tasks to pass while still having style errors on the repo.
- [n/a ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
email to …

GEODE-4826: Use spotlessCheck, not spotlessApply, as input to srcDistTar

---

geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/NativeRedisClusterTestRule.java

- Sometimes the docker cluster startup appears to complete but cluster
nodes reports fewer than expected primaries.

GEODE-9252: Improve startup of NativeRedisClusterTestRule

---

geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java

The threadConnMaps ArrayList has been removed which will improve performance of new threads
creating their first thread owned connection.
This removal also means that the HashMap is now
only referenced by a ThreadLocal so it no longer
is synchronized which simplifies the code.

GEODE-9331: remove the threadConnMaps ArrayList

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy

updates json-smart from 2.3 -> 2.3.1
json-smart is used by json-path, not directly by Geode

GEODE-9339: bump json-smart from 2.3 to 2.3.1

---

geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/internal/SuspiciousLogCheckDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/DUnitLauncher.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java

* When a VM is stopped, the suspect string file is deleted
* Log checker is called at the end of the test.
* If a VM is restarted during a test, the logs are deleted and is not checked at the end of the test.
* With the fix the logs are checked when the VM is stopped.

GEODE-8609: Check logs for suspicious logs when VM is stopped

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/RemoteTransactionDUnitTest.java

-Adds suspend and resume calls between for sequential invoke() calls to
allow transaction to resume if started by a different thread

GEODE-5304: Remote transactions DUnit test fails to resume a transaction started by another tread

---

geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/rollingupgrade/RollingUpgradeDUnitTest.java

The fix for GEODE-8609 now detects the following suspect string logged by FederatingManager just before the test bounces the JVM to upgrade it.
I believe the best fix for the following suspect string is to `addIgnoredException(DistributedSystemDisconnectedException.class)` to the setup of RollingUpgradeDUnitTest.
```
> Task :geode-core:upgradeTest
org.apache.geode.internal.cache.rollingupgrade.RollingUpgradeRollServersOnReplicatedRegion_dataserializable > testRollServersOnReplicatedRegion_dataserializable[from_v1.13.2] FAILED
java.lang.AssertionError: Suspicious strings were written to the log during this run.
Fix the strings or use IgnoredException.addIgnoredException to ignore.
-----------------------------------------------------------------------
Found suspect string in …
```

GEODE-9344: Ignore DistributedSystemDisconnectedException in RollingUpgradeDUnitTest

---

geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/pubsub/NativeRedisSubCommandsIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/RedisCommandArgumentsTestHelper.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractSubCommandsIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/SubCommandsIntegrationTest.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PubSubExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSub.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSubImpl.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/Subscriptions.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/pubsub/SubscriptionsJUnitTest.java

-add PUBSUB to supported commands in RedisCommandType
-create subcommands executor in PubSub dir
-implement mehtod for finding channel names in subscriptions class
-implement pattern matching for finding channel names
-add methods to pubsub impl and PubSub interface for returning channel names
-add to PUBSUB to Supported Comands list in SupportedCommandsJunitTest

GEODE-9202: implement PUBSUB CHANNELS subcommand

---

geode-core/src/main/java/org/apache/geode/management/internal/configuration/realizers/RegionConfigRealizer.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/realizers/RegionConfigRealizerTest.java

(cherry picked from commit 63c681d217bdcc3d6ed0150f977f18461be1a785)

GEODE-7664: calling RegionConfigRealizer.exists methods doesn't need …(#4932)

---

geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java

Removed the threadConnMaps ArrayList.
This removal also means that the HashMap is now
only referenced by a ThreadLocal so it no longer
is synchronized which simplified the code.
(cherry picked from commit 88918f1221e7bf90c88596d19c06ec41eec8315e)

GEODE-9331: remove the threadConnMaps ArrayList (#6535)

---

geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/sortedset/ZAddIncrOptionDUnitTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZAddIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSortedSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSetCommandsFunctionExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/RedisSortedSetCommands.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZAddExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZAddOptions.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZIncrByExecutor.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSortedSetTest.java

* allow zadd to return byte[] if INCR option is specified.
* fixes a race issue of ZAddExecutorState in ZAddExecutor
* added an ignored dunit test case showing score incrmented multiple times due to retry

GEODE-9362: Implement zadd with INCR option.

---

geode-core/src/main/java/org/apache/geode/internal/cache/AbstractCacheServer.java
geode-core/src/test/java/org/apache/geode/internal/cache/AbstractCacheServerTest.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/PutAllClientServerDistributedTest.java

GEODE-9103: Fix ServerConnectivityExceptions in PutAllClientServerDistributedTest
Prevent ServerConnectivityExceptions when test encounters long GCs or
slow CPUs.
Add test-only system property to AbstractCacheServer for
maximumTimeBetweenPings.
Use system property to set maximumTimeBetweenPings to GeodeAwaitility
timeout.
Use GeodeAwaitility timeout for client pool readTimeout.
Remove unnecessary client pool settings within each test.
Inline getCause within Throwable assertions.
Fixes the flakiness in GEODE-9103, GEODE-9296, and GEODE-8528.

GEODE-9103: Fix ServerConnectivityExceptions in PutAllClientServerDistributedTest

---

ci/images/google-windows-geode-builder/packer.json

* Do './gradlew.bat clean' before C:/geode.

[GEODE-9386] Fix windows builder cleanup

---

geode-docs/tools_modules/gfsh/command-pages/start.html.md.erb

Fix format issues in the start command page of the user guide.
`start locator` and `start server` command tables have been transformed from html to markdown format. Also, some html tags have been substituted by markdown tags.

GEODE-7967: User Guide - gfsh start locator - reformat oversize table

---

geode-core/src/main/java/org/apache/geode/internal/net/NioSslEngine.java
geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java

We noticed a 4-5x increase in the worst-case P2P send latency (most notably sendReplication) in 1.12 vs 1.8. Further analysis showed that the increase in sendReplicationTime is related to how long it takes to create the sender connection. More specifically, all the time spent creating the sender is in the handshake. Experiments with various sleep durations in NioSslEngine.handshake() method showed that this issue can be fixed by replacing both sleeps handshake() method with Thread.yield() calls. …

GEODE-9380: Replace sleep()s from Nio.SslEngine replace with yields

---

ci/pipelines/shared/jinja.variables.yml
settings.gradle

due to release of Geode 1.13.3

add 1.13.3 to old versions and set as Benchmarks baseline on support/1.14

---

geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/ClusterNodes.java
geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/key/RenameDUnitTest.java
geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/sortedset/ZAddIncrOptionDUnitTest.java
geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/sortedset/ZRemDUnitTest.java
geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionDUnitTest.java
geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionExpirationDUnitTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/RedisCommandArgumentsTestHelper.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/AbstractUnknownIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/AbstractHScanIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/AbstractHashesIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/AbstractHincrByFloatIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/AbstractDelIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/AbstractKeysIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/AbstractRenameIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/AbstractScanIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/AbstractUnlinkIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractPubSubIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractSubCommandsIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/AbstractSPopIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/AbstractSScanIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/AbstractSetsIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/set/SScanIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZAddIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZIncrByIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZRankIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AbstractIncrByFloatIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/pubsub/SubscriptionsIntegrationTest.java

- Replace uses of Coder conversion methods in DUnit and Integration
tests with implementations that do not assume knowledge of the way we
internally handle such conversions.
submit an update to your PR as soon as possible. If you need …

GEODE-9400: Do not use Coder conversion methods in tests

---

geode-core/src/integrationTest/java/org/apache/geode/internal/net/SSLSocketHostNameVerificationIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/net/SSLSocketIntegrationTest.java
geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
geode-core/src/main/java/org/apache/geode/internal/net/ByteBufferSharing.java
geode-core/src/main/java/org/apache/geode/internal/net/ByteBufferSharingNoOp.java
geode-core/src/main/java/org/apache/geode/internal/net/ByteBufferVendor.java
geode-core/src/main/java/org/apache/geode/internal/net/NioSslEngine.java
geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
geode-core/src/test/java/org/apache/geode/internal/net/ByteBufferConcurrencyTest.java
geode-core/src/test/java/org/apache/geode/internal/net/ByteBufferVendorTest.java
geode-core/src/test/java/org/apache/geode/internal/net/NioSslEngineTest.java
geode-core/src/test/java/org/apache/geode/internal/tcp/ConnectionTest.java

**Important:**
- when merging **be sure to rebase-and-merge** so this is merged as two commits!
This is a back-port of the fix for GEODE-9141 to `support/1.13`.
This work was confounded by four other tickets that have not been back-ported. Those tickets were not back-ported as part of this PR, so I worked around them instead:
GEODE-8337  7/17/2020 the `Version` -> `KnownVersion` changes
GEODE-8521  12/3/2020 detect if P2P reader thread hung
GEODE-8882 1/28/2021 introduction of JetBrains `NotNull` annotation
-> this ticket GEODE-9141 is from 4/17/2021
GEODE-9139 4/27/2021 `SSLException` starting locator
**NO this needs to be merged as two commits**
**NO this is a back-port**

Back-port GEODE-9141 "handle inBuffer concurrency" to support/1.13

---

geode-core/src/integrationTest/java/org/apache/geode/internal/net/SSLSocketHostNameVerificationIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/net/SSLSocketIntegrationTest.java
geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
geode-core/src/main/java/org/apache/geode/internal/net/ByteBufferSharing.java
geode-core/src/main/java/org/apache/geode/internal/net/ByteBufferSharingNoOp.java
geode-core/src/main/java/org/apache/geode/internal/net/ByteBufferVendor.java
geode-core/src/main/java/org/apache/geode/internal/net/NioSslEngine.java
geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
geode-core/src/test/java/org/apache/geode/internal/net/ByteBufferConcurrencyTest.java
geode-core/src/test/java/org/apache/geode/internal/net/ByteBufferVendorTest.java
geode-core/src/test/java/org/apache/geode/internal/net/NioSslEngineTest.java
geode-core/src/test/java/org/apache/geode/internal/tcp/ConnectionTest.java

**Important:**
- merge the back-port to 1.13 PR [#6626](https://github.com/apache/geode/pull/6626) before merging this one so we don't run afoul of commit check.
- when merging **be sure to rebase-and-merge** so this is merged as two commits!
These two commits were cherry-picked from the support/1.13 back-port PR [#6618](https://github.com/apache/geode/pull/6618) since that PR had to resolve a number of tricky conflicts.
In addition to those conflicts I saw on support/1.12, I had to resolve issues with a confounding commit:
GEODE-8419 "SSL Configuration ignored" had been back-ported already to 1.12 but there was an error in that back-port:
`clientSocket` was still referenced in `SocketCreator.handshakeSSLSocketChannel()`. I removed those remnants since the fix for GEODE-8419 moved all …

back-port GEODE-9141 to support/1.12

---

geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/netty/CoderTest.java

Updates Coder.java to convert doubles with the value of Double.POSITIVE_INFINITY as "inf" and Double.NEGATIVE_INFINITY as "-inf". This matches native Redis behavior.

GEODE-9342: Handle a double reply of "inf" in the same way as Redis

---

geode-docs/configuring/cluster_config/export-import.html.md.erb
geode-docs/tools_modules/gfsh/command-pages/import.html.md.erb
geode-docs/tools_modules/gfsh/quick_ref_commands_by_area.html.md.erb

Two write-ups on the gfsh import cluster-configuration command seem to differ with regard to whether the operation is allowed on running cache servers.
The operation is allowed, but with restrictions. The correct details are provided in the gfsh import command description.
This PR modifies the corresponding section under Exporting and Importing Cluster Configurations to be consistent with the gfsh write-up.

GEODE-9410: User Guide - resolve inconsistencies in gfsh import command description

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/control/RestoreRedundancyOperationDUnitTest.java

The PR is intentionally split into two commits. The first replaces the deprecated junit `assertThat()` with AssertJ assertions throughout the file. The second adds an `await()` to assertions around stats, which is necessary because of a race condition in `RestoreRedundancyOperationImpl` where the stats aren't updated until after the `CompletableFuture` for the results finishes:
```
resultsFuture.thenRun(() -> {
manager.removeInProgressRestoreRedundancy(resultsFuture);
manager.getStats().endRestoreRedundancy(start);
});
``` …

GEODE-9374: Use await() in RestoreRedundancyOperationDUnitTest

---

geode-core/src/main/java/org/apache/geode/internal/cache/TXCommitMessage.java
geode-dunit/build.gradle
geode-dunit/src/test/resources/expected-pom.xml
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderAndCQDurableClientDUnitTest.java

Issue reproduces when following conditions are fulfilled:
- Redundant partition region must be configured
- Number of servers must be greater than number of redundant copies of partition region
- Parallel gateway sender must be configured on partition region
- Client must register CQs for the region
- Transactions must be used with put operations
- Events must be enqueued in parallel gateway senders (remote site is unavailable)
Server that is hosting primary bucket will send TXCommitMessage to the secondary
server, and also to the server that is hosting CQ subscription queue (if CQ condition is fulfilled).
The problem occurs when the server that is hosting CQ subscription queue does not host
the bucket for which event is received. In that case the server will store the event in …

GEODE-9248: Server hosting CQ queue uneccessary fills bucketToTempQueue

---

geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/sortedset/ZRevRankNativeRedisAcceptanceTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZRevRankIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/ZRevRankIntegrationTest.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSortedSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSetCommandsFunctionExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/RedisSortedSetCommands.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZRevRankExecutor.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java

- Add ZREVRANK to supported commands
- Arrange RedisSortedSet commands alphabetically in classes
- Remove redundant zrank implementation in NullRedisSet
- Add tests for ZREVRANK command

GEODE-9187: Implement Radish ZREVRANK command

---

geode-core/src/main/java/org/apache/geode/management/internal/util/ManagementUtils.java
geode-core/src/test/java/org/apache/geode/management/internal/util/ManagementUtilsTest.java

GetMemberInformationFunction may throw RegionDestroyedException if a
hosted region is destroyed while the function is checking the region
names. This exception is logged as an "error" level message which is
confusing to users.
Catch the exception and omit the destroyed region from the list of
hosted region names.

GEODE-9407: Handle exception getting region names

---

geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/sortedset/ZCountNativeRedisAcceptanceTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZCountIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/ZCountIntegrationTest.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/collections/OrderStatisticsSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/collections/OrderStatisticsTree.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSortedSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSetCommandsFunctionExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/SortedSetRangeOptions.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZCountExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/StringBytesGlossary.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/collections/OrderStatisticsTreeTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/collections/OrderedStatisticTreeQuickCheckTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSortedSetTest.java

- Add ZCOUNT to supported commands
- Modify OrderStatisticsTree.indexOf() to return the index of elements that are
not present in the collection instead of -1, to make the behaviour of
OrderStatisticsTree and IndexibleTreeSet match
- Add constants to the StringBytesGlossary to support parsing Redis
range values and doing more comparisons on String member names
- Replace hardcoded Strings with constants in
AbstractHitsMissesIntegrationTest
- Fix an inaccurate Javadoc introduced by a previous commit
- Small code clean-ups in code related to ZRANGE
- Add tests for ZCOUNT and new behaviour in OrderStatisticsTree
to ensure the …

GEODE-9182: Implement Radish ZCOUNT command

---

geode-core/src/main/java/org/apache/geode/internal/cache/TXCommitMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXLastEventInTransactionUtils.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXState.java
geode-core/src/test/java/org/apache/geode/internal/cache/TXLastEventInTransactionUtilsTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialWANPropagation_PartitionedRegionDUnitTest.java

* This is normal case for serial wan configuration. Error message should not be
logged when executing transactions.

GEODE-9404: Do not log error message if sender is not configured.

---

geode-core/src/test/java/org/apache/geode/cache/asyncqueue/internal/ParallelAsyncEventQueueImplTest.java
geode-wan/src/test/java/org/apache/geode/cache/wan/internal/parallel/ParallelGatewaySenderImplTest.java

ParallelAsyncEventQueueImplTest and ParallelGatewaySenderImplTest classes were mocking InternalRegion
but were not providing an implementation for cache.getCancelCriterion().
This led to a null pointer exception in the BatchRemoval thread code that,
even though it did not affect the tests, provoked that a log message with
a null pointer exception was printed.
The solution consists of adding a response in the mock using when() for the cache.getCancelCriterion() method. …

GEODE-9421: Remove BatchRemoval NPE logs from JUnit tests

---

geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java
geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/CreateDiskStoreCommand.java
geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/commands/CreateDiskStoreCommandTest.java

`gfsh` handling of wrong disk store directories sizes can be improved. This is the output when trying to use wrong values:
Negative size:
```
gfsh>create disk-store --name=storage --dir=dataStore#-100
Member   | Status | Message
--------- | ------ | -----------------------------------------------------------------------
theServer | ERROR  |  java.lang.IllegalArgumentException: Dir size cannot be negative : -100
Did not complete waiting for Disk Store MBean proxy creation
```
Using a wrong number string:
```
gfsh>create disk-store --name=storage --dir=dataStore#123ABC
For input string: "123ABC"
```
Using a value bigger than the maximum allowed value which is `2147483647` (`Integer.MAX_VALUE`):
```
gfsh>create disk-store --name=storage --dir=dataStore#2147483648
For input string: …
```

GEODE-8282: Improve disk-store dir sizes constraints handling in gfsh

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/control/RestoreRedundancyOperationDUnitTest.java

- Convert assertions to AssertJ
- Add await() to assertions around stats
(cherry picked from commit 7b3693ddc14d631200c81926c0072d1546f28169)

GEODE-9374: Use await() in RestoreRedundancyOperationDUnitTest (#6649)

---

geode-core/src/distributedTest/java/org/apache/geode/distributed/DistributedSystemDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/distributed/FailDeserializationFunction.java
geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/ClusterDistributionManagerDUnitTest.java
geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/GMSMembership.java

This change modifies GMSMembership.processView() method to call MembershipListener.newMemberConnected() only after the new view is installed. This avoids a race condition where a MembershipEventListener receives MmeberJoinedEvent before the view was updated.

GEODE-9350: MemberJoinedEvent should be triggered after new view is installed

---

geode-apis-compatible-with-redis/build.gradle
geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/sortedset/ZRevRangeNativeRedisAcceptanceTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZRevRangeIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/ZRevRangeIntegrationTest.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/collections/IndexibleTreeSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/collections/OrderStatisticsSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/collections/OrderStatisticsTree.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSortedSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSetCommandsFunctionExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZRangeExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZRankExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/RedisSortedSetCommands.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZRangeExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZRevRangeExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZRevRankExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/StringBytesGlossary.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/collections/OrderStatisticsTreeTest.java

- Add ZREVRANGE to supported commands
- Add reverse range iterator implementation to OrderStatisticsTree
- Introduce AbstractZRangeExecutor class
- Add tests for ZREVRANGE
- Add tests for new reverse iterator in OrderStatisticsTree
- Introduce AbstractZRankExecutor class to reduce code duplication and
refactor ZRankExecutor and ZRevRankExecutor to use it
- Fix incorrect implementation of ZRANGE in NullRedisSortedSet
- Fix ZRANGE not updating stats
- Add missing hits/misses tests for ZRANGE
Co-authored-by: Donal Evans <doevans@vmware.com>
Co-authored-by: Hale Bales <hbales@vmware.com>
Please ensure that once the PR is …

GEODE-9376: Implement Radish ZREVRANGE command

---

geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZRangeIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZRevRangeIntegrationTest.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/ParameterRequirements/SpopParameterRequirements.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HScanExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/key/ScanExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SPopExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SRandMemberExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SScanExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZRangeExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/string/BitPosExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/string/GetBitExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/string/SetBitExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/string/SetRangeExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/netty/CoderTest.java

- Do not return errors when arguments are specified that are less than
Integer.MIN_VALUE or less than Integer.MAX_VALE
- Convert long arguments outside the above range to Integer.MIN_VALUE
or Integer.MAX_VALUE to be used internally
- Add tests for new Coder method and coverage for existing supported
commands that take integer arguments, except HSCAN which will require
GEODE-9429 to be fixed first
email to …

GEODE-9424: Accept Long arguments for Redis commands

---

geode-core/src/main/java/org/apache/geode/internal/cache/TXCommitMessage.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXLastEventInTransactionUtils.java
geode-core/src/main/java/org/apache/geode/internal/cache/TXState.java
geode-core/src/test/java/org/apache/geode/internal/cache/TXLastEventInTransactionUtilsTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialWANPropagation_PartitionedRegionDUnitTest.java

* This is normal case for serial wan configuration. Error message should not be
logged when executing transactions.
* Log error message only if some events in a tx configured to group transaction but
others do not have sender configured.
* Should not wait for lastTransactionEvent in a tx if no sender configured or sender
does not set must group transaction.
(cherry picked from commit f0e328ba3eb4a1b2b47bdca5d565b79e88fecdca)

GEODE-9404: Do not log error message if sender is not configured. 

---

extensions/geode-modules/src/distributedTest/java/org/apache/geode/modules/util/ClientServerSessionCacheDUnitTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionImpl.java

This issue occurs when the function tries to execute on a member that has just joined the cluster, but because the new view is not done processing by membership, the member is considered shunned and nonexistent.  This root issue will be fixed by [GEODE-9350](https://issues.apache.org/jira/projects/GEODE/issues/GEODE-9350).  
This PR just makes some small test improvements and adds additional logging to assist in diagnosing the problem if it occurs in the future.

GEODE-9070: Improve ClientServerSessionCacheDUnitTest and add additional logging

---

geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/internal/SuspiciousLogCheckDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/DUnitLauncher.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java

* When a VM is stopped, the suspect string file is deleted
* Log checker is called at the end of the test.
* If a VM is restarted during a test, the logs are deleted and is not checked at the end of the test.
* With the fix the logs are checked when the VM is stopped.
(cherry picked from commit e39c4c5ad79ee07d7760c98a85259cfb68c64e4c)

GEODE-8609: Check logs for suspicious logs when VM is stopped.

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/NestedFunctionExecutionDistributedTest.java

Change `NestedFunctionExecutionDistributedTest` to create fewer threads.
The test creates a number of threads that is a multiple of
`MAX_FE_THREADS`. On a CI machine, the default value of `MAX_FE_THREADS`
can be very high, causing this test to create thousands of threads. This
can leave the system unable to create threads for other processes, which
in turn can cause Gradle processes or other tests to fail or hang.
This test now sets `MAX_FE_THREADS` to a lower value (100), which
suffices for the purpose of the test, and results in greatly reduced
consumption of threads.
Co-authored-by: Dale Emery <demery@vmware.com>

GEODE-9441: Reduce Nested func test thread count

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-junit/build.gradle
geode-junit/src/main/java/org/apache/geode/cache/ssl/CertificateBuilder.java
geode-junit/src/main/java/org/apache/geode/cache/ssl/CertificateMaterial.java
geode-junit/src/test/java/org/apache/geode/cache/ssl/CertificateBuildingTest.java
geode-junit/src/test/resources/expected-pom.xml

- Makes it easier to de/serialize created certificates
- Remove the requirement for the Bouncy Castle library
- Java 9 has a very similar utility which we should be able
to switch to once we move away from 8.

GEODE-9439: Convert CertificateBuilder to sun/jdk APIs

---

ci/images/google-geode-builder/scripts/setup.sh

Certain Geode tests create a lot of threads. When these tests run in
parallel with many other tests (as they do in CI), the whole set of
concurrently running tests can overwhelm the Linux kernel's ability to
assign PIDs to new threads. When this happens, test processes, Gradle
processes, and other processes can become unable to create new threads.
The relevant system parameter is `kernel.pid_max`. In our CI images,
`pid_max` is 98,304.
This commit raises CI images' `pid_max` to 983040 (10x the default
value). A build can run 24 concurrent instances of even our most
thread-heavy tests without exceeding this threshold.
Co-authored-by: Dale Emery <demery@vmware.com>

GEODE-9443: Increase pid_max in CI images

---

geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-core/src/main/java/org/apache/geode/management/internal/configuration/domain/Configuration.java

* This was suppose to be a part of the initial commit for GEODE-9289
* However we had to wait for a revert in the deployement data structure in GEODE-9377
* This commit is already a part of the previous releases of Apache Geode

GEODE-9289: Configuration class modified into VersionedDataSerializable

---

geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/RedisIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/AbstractHScanIntegrationTest.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHash.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHashCommandsFunctionExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HScanExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/RedisHashCommands.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisHashTest.java

This PR is intentionally split into two commits; first an initial test clean-up and refactor, and then the commit containing the changes related to the ticket.
- Refactor and clean up AbstractHScanIntegrationTest
- Refactor RedisHash.hscan() to handle large COUNT values
- Add tests to cover new behaviour

GEODE-9429: Allow Radish HSCAN to handle all valid values for COUNT

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/DiskStoreImplIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/OplogRVVJUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/Oplog.java
geode-core/src/main/java/org/apache/geode/internal/cache/OverflowOplog.java
geode-core/src/main/java/org/apache/geode/internal/cache/properties.md
geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java
geode-core/src/test/java/org/apache/geode/internal/cache/OplogTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/OverflowOplogTest.java
geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb

According to the Geode User Guide, it is possible to set the write buffer size by using the `--write-buffer-size` option when creating a disk store.
Nevertheless, setting a value for that parameter either by using gfsh, cache.xml or the `DiskStoreFactory.setWriteBuffer()` method has no effect.
The current implementation checks if the `WRITE_BUF_SIZE` system property is set, and if that is not the case, the default value of `32768` bytes is used.
This PR changes the behavior so first the disk store write buffer size is obtained (which default value is `32768`). Then, if the `WRITE_BUF_SIZE` system property is set, its value will take precedence over the disk store buffer size.
References:
* `create disk-store` command reference: https://geode.apache.org/docs/guide/113/tools_modules/gfsh/com …

GEODE-9300: write-buffer-size value not used when creating disk store

---

geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/sortedset/ZRangeByLexNativeRedisAcceptanceTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZRangeByLexIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZRangeByScoreIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/ZRangeByLexIntegrationTest.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSortedSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSetCommandsFunctionExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/AbstractSortedSetRangeOptions.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/RedisSortedSetCommands.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/SortedSetLexRangeOptions.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/SortedSetScoreRangeOptions.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZCountExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZRangeByLexExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZRangeByScoreExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/StringBytesGlossary.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/SupportedCommandsJUnitTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSortedSetTest.java

- Add ZRANGEBYLEX to supported commands
- Introduce AbstractSortedSetRangeOptions class to handle behaviour
common to -BYSCORE and -BYLEX ranges
- Introduce SortedSetLexRangeOptions to handle parsing lexical ranges
- Rename SortedSetRangeOptions to SortedSetScoreRangeOptions
- Introduce MemberDummyOrderedSetEntry to support getting rank by lex
- Rename DummyOrderedSetEntry to ScoreDummyOrderedSetEntry
- Add unit tests for MemberDummyOrderedSetEntry
- Add integration tests for ZRANGEBYLEX
- Refactor RedisSortedSet.zrangebyscore() to use
SortedSetScoreRangeOptions
- Add missing HitsMissesIntegrationTest for ZRANGEBYSCORE
- Refactor argument parsing in ZRangeByScoreExecutor to allow correct
error behaviour with multiple LIMIT options, one of which is
incorrectly formatted
- Add tests to …

GEODE-9388: Implement Radish ZRANGEBYLEX Command

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
extensions/geode-modules/build.gradle
geode-common/build.gradle
geode-concurrency-test/build.gradle
geode-jmh/build.gradle
geode-junit/build.gradle
geode-junit/src/test/java/org/apache/geode/test/junit/rules/ConcurrencyRuleTest.java
geode-junit/src/test/resources/expected-pom.xml
geode-rebalancer/build.gradle
gradle/test.gradle
static-analysis/pmd-rules/build.gradle

Added JUnit 5 support to all Geode projects that use `geode-junit`.
STANDARD TEST TASKS
Updated **./gradle/test.gradle** to configure these standard test tasks
to use JUnit Platform to run tests:
- `test` and `repeatUnitTest`
- `acceptanceTest` and `repeatAcceptanceTest`
- `distributedTest` and `repeatDistributedTest`
- `integrationTest` and `repeatIntegrationTest`
- `performanceTest`
- `uiTest`
- `upgradeTest` and `repeatUpgradeTest`
STANDARD TEST MODULES
Updated **./geode-junit/build.gradle**:
- Added `junit-jupiter-api` and `junit-jupiter-params` as API
dependencies.
- Added `junit-jupiter-engine` and `junit-vintage-engine` as
implementation dependencies.
These changes add JUnit 5 support to any source set that depends on
`geode-junit`, either directly or via `geode-dunit`.
OTHER …

GEODE-4181: Add JUnit 5 Support

---

gradle/test.gradle

Change `./gradle/test.gradle` to use the new JUnit Platform property
name `includeTags` instead of the now-obsolete `includeCategories`.

GEODE-4181: Use new includeTags property name

---

geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/GeodeRedisServerStartupDUnitTest.java
geode-junit/src/main/java/org/apache/geode/test/junit/categories/IgnoreInRepeatTestTasks.java
gradle/test.gradle

PROBLEM
`GeodeRedisServerStartupDUnitTest.startupOnDefaultPort()` tests the
system's use of a fixed port. Repeat test tasks run multiple instances
of this test concurrently. Most of the concurrently running instances of
the test are likely to fail when they find that port already in use.
SOLUTION
- Add an `IgnoreInRepeatTestTasks` test category.
- Configure repeat tests to exclude tests with the
`IgnoreInRepeatTestTasks` category.
- Add the `IgnoreInRepeatTestTasks` category to
`GeodeRedisServerStartupDUnitTest.startupOnDefaultPort()`

GEODE-9492: Ignore default port test in stress tests

---

geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandIntegrationTest.java

Two of the tests in `StartLocatorCommandIntegrationTest` launch a locator
process that binds to the default HTTP service port (7070). This can
interfere with the tests that explicitly verify that the system uses the
correct HTTP service port by default.
Neither test actually needs the launched locator for any purpose.
Neither test makes a single assertion about the locator. When the tests
exit, they leave the locator running. In fact, the locator typically
finishes launching well after the tests have all exited.
Rather than fix the port assignment, this commit changes the tests so
that they do not actually launch a locator. Two of the tests in this
class already do this.

GEODE-9483: Make StartLocatorCommandIntegrationTest not start unneeded locator

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RestoreRedundancyManagementDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/control/SerializableRegionRedundancyStatusImpl.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt

* SerializableRegionRedundancyStatusImpl is stored in RegionOperationStateStore region as
part of OperationState used for REST client.
* OperationState implements Serializable, which causes it to be serialized as a java
Serialiable and also nested SerializableRegionRedundancyStatusImpl.
* Ideally OperationState should implement DSFID to avoid this issue, however, it has been
released already. So we will add SerializableRegionRedundancyStatusImpl to the accept list
to avoid this serialization issue when validate-serializable-objects is set to true.
Co-authored-by: Dan Smith <dasmith@vmware.com>
Please ensure that once the …

GEODE-9463: Add SerializableRegionRedundancyStatusImpl to accept list

---

geode-core/src/main/java/org/apache/geode/internal/cache/execute/FunctionRemoteContext.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CommandInitializer.java
geode-serialization/src/main/java/org/apache/geode/internal/serialization/KnownVersion.java
geode-serialization/src/test/java/org/apache/geode/internal/serialization/KnownVersionJUnitTest.java

This protocol change actually happened in 1.13.2. 1.13.1 is still using the
same protocol ordinal as 1.13.0, which is 120.
Evidence
* b2d205459bf is the commit that introduced this version in support/1.13
* b2d205459bf is only contained in rel/v1.13.2 and above
* Running geode 1.13.1, it reports its protocol version as 120.

GEODE-9480: Changing the version with ordinal 121 to be 1.13.2

---

geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/CqQueryDUnitTest.java

PROBLEM
`CqPerfDUnitTest.testFailOverMatchingCQsWithMultipleServers`:
1. Starts a server on an ephemeral port
2. Stops the server
3. Restarts the server on the same port
This test failed in CI because, between steps 2 and 3, another process
bound to the ephemeral port.
SOLUTION
Change `CqPerfDUnitTest.createServer(VM)` to assign an available port via
`AvailablePortHelper`, rather than specify an ephemeral port. The ports
assigned by `AvailablePortHelper` are outside of each OS's ephemeral
port range.
CONSIDERED
I could have changed just the one failing test to assign a port. But
because there is no good reason for tests to prefer ephemeral ports by
default, I decided to change the `createServer(VM)` to always assign a
port. This change preempts this kind of problem in other tests. If a …

GEODE-9488: Make CqQuery test assign port

---

extensions/geode-modules/src/main/java/org/apache/geode/modules/session/bootstrap/AbstractCache.java
extensions/geode-modules/src/test/java/org/apache/geode/modules/session/bootstrap/AbstractCacheTest.java
extensions/geode-modules/src/test/java/org/apache/geode/modules/session/bootstrap/ClientServerCacheTest.java
extensions/geode-modules/src/test/java/org/apache/geode/modules/session/bootstrap/PeerToPeerCacheTest.java

Consider all properties starting with "security-" as valid when
configuring the HTTP Session Management Module.

GEODE-9494: Security Properties for HTTP Module

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
extensions/geode-modules/build.gradle
geode-common/build.gradle
geode-concurrency-test/build.gradle
geode-jmh/build.gradle
geode-junit/build.gradle
geode-junit/src/test/java/org/apache/geode/test/junit/rules/ConcurrencyRuleTest.java
geode-junit/src/test/resources/expected-pom.xml
geode-rebalancer/build.gradle
gradle/test.gradle
static-analysis/pmd-rules/build.gradle

due to large number of Windows CI failures starting after #6740 + #6742 were merged, I want to see if reverting this change makes a difference.  If so, we should go through with this revert and try again to make Junit5 work in a new PR with Windows label.

Revert GEODE-4181: Add JUnit 5 Support

---

geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/QuitIntegrationTest.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/NettyRedisServer.java

GEODE-9169: remove netty context switch

---

geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/AbstractRedisData.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisHashTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSetTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSortedSetTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisStringTest.java

DeltaInfo is now cleared right after region.put is called and in the same method that set it.
The size tests no longer clear it.
The unit tests for delta needed to change because the deltaInfo is now cleared earlier. Using a mockito Answer allowed for the delta implementation to be validated.

GEODE-9500: clear DeltaInfo earlier

---

geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/ProcessManager.java

PROBLEM
Windows limits command lines to a maximum length of ~32k characters. The
command line for DUnit child VMs is very close to this limit.
Currently this prevents us from adding JUnit 5 support. JUnit 5 adds 8
more jars to the classpath, which adds ~1300 characters to the command
line, which puts the command line over the limit.
SOLUTION
Write the ChildVM's entire classpath to a "pathing" jar, then include
only that pathing jar on the command line. This results in command line
that is shorter by many thousands of characters, and which does not grow
as we add more jars or other classpath elements.

GEODE-4181: Reduce ChildVM command line length

---

ci/pipelines/geode-build/jinja.template.yml
ci/pipelines/shared/jinja.variables.yml
dev-tools/release/promote_rc.sh

- Runs Radish benchmarks on the same topology as the Geode benchmarks (2
x servers, 1 x locator, 1 x client). Current systems are large 72 vCPU
instances.
- Baseline is taken from when most of the major performance updates have
been implemented.

GEODE-9525: Add Radish benchmarks to CI

---

geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/netty/CoderTest.java

Added convertLongToAsciiDigits to Coder so that ints and longs can more efficiently be converted to bytes. The goal was to reduce
the number of short lived object allocations based on this observation:
Refactor the getIntegerResponse(ByteBuf buffer, long l) method to write byte string representation to avoid allocating transient char[], String, and byte[]. The existing allocations accounted for 17% of objects requiring GC.
So now when converting an int or long we never convert it to a String and for some values (-99..99) we don't allocate a new byte array. The same is also true when converting a sequence of bytes from command input into a long; we no longer allocate a short lived String.
In order to streamline the review of the …

GEODE-9514: optimize how Coder reads and writes "int" and "long" values

---

geode-core/src/upgradeTest/java/org/apache/geode/security/AuthExpirationDUnitTest.java
geode-junit/src/main/java/org/apache/geode/security/ExpirableSecurityManager.java
geode-junit/src/main/java/org/apache/geode/security/UpdatableUserAuthInitialize.java

GEODE-9460: Add testing for mutli-user scenarios

---

geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/ContainerInstall.java

PROBLEM
`ContainerInstall` fetches a resource URL, then applies a chain of
conversions before passing the resulting URL to the `ZipURLInstaller`
constructor.  One of the conversions attempts to create a `Path` from a
string.  On Windows, the string value is not a valid path, and
`Paths.get(...)` throws an exception.
SOLUTION
Change `ContainerInstall` to remove all of the conversions. The original
resource URL is acceptable to `ZipURLInstaller` without any conversion.

GEODE-9523: Fix invalid path in ContainerInstall

---

geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsDUnitTest.java

PROBLEM
`DiskStoreCommandsDUnitTest.verifyDiskStoreInServer(...)` incorrectly
assumes thatif a file path does not start with a file separator, it must
be relative. It attempts to convert such a path to absolute by
prepending the current directory onto it:
```
String absoluteDiskDirectoryName = diskDirectoryName.startsWith(File.separator)
? diskDirectoryName
: CURRENT_DIRECTORY + File.separator + diskDirectoryName;
```
On Windows, an absolute file path can begin with a letter, e.g.
`C:\Users\geode\AppData\Local\Temp\junit783716437098694709\DISKSTORE`.
The test incorrectly interprets a path like this as relative, and
prepends the current directory onto it, producing an invalid path. It
then uses this incorrect path in an assertion, causing the test to fail
when it should pass.
SOLUTION
Use …

GEODE-9526: Fix path computation in DiskStore test

---

geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/PartitionedRegionCqQueryDUnitTest.java

* Cq events sent to client asynchronously. Need to wait events are
all delivered.

GEODE-9071: Add wait before checking cq listener invocations.

---

geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/PartitionedRegionCqQueryDUnitTest.java

* Cq events sent to client asynchronously. Need to wait events are
all delivered.
(cherry picked from commit 018fb585b1750a3186ad4693744ed5630d869182)

GEODE-9071: Add wait before check cq listener invocations. (#6785)

---

geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/AbstractRedisData.java

Using a static ThreadLocal in the RedisData class, we can avoid carrying around an object reference for all instances of RedisData. This saves 4-8 bytes of memory per instance.

Create ThreadLocal instance, use to manage DeltaInfos

---

geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/test/dunit/rules/RedisClusterStartupRule.java
geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionsAndCrashesDUnitTest.java

GEODE-9506: Do not use random ephemeral port to start Redis servers

---

geode-book/master_middleman/source/subnavs/geode-subnav.erb
geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedAckRegionCCEDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/EnumListenerEvent.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheServerStats.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/GatewayReceiverCommand.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Put70.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/GatewaySenderEventCallbackDispatcher.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/GatewaySenderEventDispatcher.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/GatewaySenderEventImpl.java
geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java
geode-core/src/test/java/org/apache/geode/internal/cache/EnumListenerEventJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/Put70Test.java
geode-docs/tools_modules/gfsh/command-pages/wan_copy_region.html.md.erb
geode-docs/tools_modules/gfsh/gfsh_command_index.html.md.erb
geode-docs/tools_modules/gfsh/quick_ref_commands_by_area.html.md.erb
geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/GfshParserAutoCompletionIntegrationTest.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/CommandAvailabilityIndicator.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/WanCopyRegionCommand.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/functions/WanCopyRegionFunction.java
geode-gfsh/src/main/resources/META-INF/services/org.springframework.shell.core.CommandMarker
geode-gfsh/src/main/resources/org/apache/geode/gfsh/internal/management/sanctioned-geode-gfsh-serializables.txt
geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/commands/WanCopyRegionCommandTest.java
geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/functions/WanCopyRegionFunctionTest.java
geode-gfsh/src/test/resources/expected-pom.xml
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelWANPropagationClientServerDUnitTest.java
geode-wan/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/WanCopyRegionCommandDUnitTest.java
geode-wan/src/main/java/org/apache/geode/cache/wan/internal/GatewaySenderEventRemoteDispatcher.java
geode-wan/src/main/java/org/apache/geode/cache/wan/internal/client/locator/GatewaySenderBatchOp.java

The command has been implemented as proposed in
https://cwiki.apache.org/confluence/display/GEODE/Geode+Command+to+replicate+region+data+from+one+site+to+another+connected+via+WAN
with some modifications with respect to the initial proposal.
The command will get the entries of a region
in a WAN site and will put them in batches
that will be sent by a gateway sender to a remote
WAN site.

GEODE-9369: Command to copy region entries from a WAN site to another

---

geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/netty/CoderTest.java

In addition to the change to have bytesToLong fail if the bytes begin with "-0" or "+",
this pr also has some other cleanup of Coder.
The double conversion was doing some extra comparisons (both byte[] and String comparisons). Now it just does byte[] comparisons.
The long conversion is has now also been influenced by the javolution project.

GEODE-9482: change Coder.bytesToLong to fail if bytes start with "-0" or "+"

---

geode-apis-compatible-with-redis/src/commonTest/java/org/apache/geode/redis/NativeRedisClusterTestRule.java

- Increase the wait from 5 to 60 seconds

GEODE-9252: Wait longer for Redis cluster to be formed

---

geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/services/StripedExecutorService.java

- StripedExecutorService contained two instances of if statements
withoug curly braces

GEODE-7864: Add missing curly braces to if statements

---

ci/docker/cache_dependencies.sh
ci/images/google-geode-builder/scripts/cache_dependencies.sh
geode-assembly/src/main/dist/LICENSE

fixes for issues identified by 1.14-rc pipeline

Fix 1.14.0 rc1

---

geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/MemoryOverheadIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
geode-apis-compatible-with-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/collections/Bytes2ObjectOpenHashMap.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/collections/SizeableBytes2ObjectOpenCustomHashMapWithCursor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHash.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/collections/SizeableBytes2ObjectOpenCustomHashMapWithCursorQuickCheckTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/collections/SizeableBytes2ObjectOpenCustomHashMapWithCursorTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisHashTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSortedSetTest.java

Bytes2ObjectOpenHashMap is now used by RedisHash and RedisSortedSet for its map.
This saves around 20 bytes per "hash" or "zset" instance.
Bytes2ObjectOpenHashMap is derived from Object2ObjectOpenCustomHashMap so if you see
some code in it that you question, compare it to the original. The class comment on Bytes2ObjectOpenHashMap describes the changes made to it. The goal was to keep the code as
close to the original, but to make some changes to save on memory. Some cosmetic changes were
also made using intellij automated cleanup (for example adding curly braces, getting rid of extra parens).
Some new top level methods were added to allow users to avoid the overhead of creating a new instance
when calling keySet(), entrySet(), or values(). These methods use to cache their result but no …

GEODE-9497: create new hash map class with fewer fields

---

geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionManager.java
geode-core/src/main/java/org/apache/geode/distributed/internal/LonerDistributionManager.java
geode-core/src/main/java/org/apache/geode/distributed/internal/ReplySender.java
geode-core/src/main/java/org/apache/geode/internal/tcp/DirectReplySender.java
geode-core/src/test/java/org/apache/geode/internal/tcp/DirectReplySenderTest.java

Updates API with null annotations.
Updates Javadocs with comments on mutable collections.
New test to assert that DirectReplySender always uses a mutable connection list.

GEODE-9573: Uses mutable list for connections.

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/OpExecutorImpl.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/OpExecutorImplTest.java

* Reverts some changes to exception handling in OpExecutorImpl that specifically depends on cause being null.
* Coverts the handleException method to static for easier testing.
* Adds test to assert these two exceptions get thrown without cause.

GEODE-9574: Sets cause to null on certain exceptions.

---

LICENSE
ci/pipelines/shared/jinja.variables.yml
ci/scripts/execute_build.sh
dev-tools/dependencies/bump.sh
dev-tools/release/deploy_rc_pipeline.sh
dev-tools/release/license_review.sh
dev-tools/release/promote_rc.sh
dev-tools/release/set_versions.sh
geode-assembly/src/main/dist/LICENSE
geode-management/src/test/script/update-management-wiki.sh

fix issues encountered during 1.14.0 release:
* ignore apt update failure, as it may still work (apt install is the true test)
* actually commit files modified by set-versions
* fix the version of checker-qual and asm in the license
* fix the omission of OrderStatisticTree from the binary license
* suggest running the license review script and adding Windows label and checking gradle plugin versions after a batch of dependency bumps
* sync up the callstack timeout for stressnew and add java -version to Build job
* suggest running CMS REST APIdoc update script and autodetect python3
* improve docker build flakiness with auto-retries and skip closer.lua which likely won't be working yet
Note: I'll leave this pull request open until the end of the week in case any other release script issues …

GEODE-9447: fix release scripts

---

geode-dunit/src/main/java/org/apache/geode/cache30/MultiVMRegionTestCase.java

(cherry picked from commit 10abff6cb6722a56b03305251076c9c78e948dd3)

GEODE-9532: Register LongWrapperSerializer before Region.put() (#6799)

---

geode-docs/managing/management/jmx_manager_operations.html.md.erb

jmx-manager-ssl, which no longer exists, was superseded by jmx-manager-ssl-enabled, which does exist but has subsequently been deprecated.
For now, we’ll fix the small issue in front of us by updating the property to jmx-manager-ssl-enabled.

GEODE-9561:  jmx-manager-ssl-enabled supersedes jmx-manager-ssl

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/control/RebalanceOperationComplexDistributedTest.java
geode-core/src/distributedTest/resources/org/apache/geode/internal/cache/RebalanceOperationComplex-client.xml
geode-core/src/distributedTest/resources/org/apache/geode/internal/cache/RebalanceOperationComplex-server.xml
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionDataStore.java
geode-core/src/main/java/org/apache/geode/internal/cache/control/PartitionRebalanceDetailsImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PartitionedRegionRebalanceOp.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/rebalance/model/Member.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/rebalance/model/PartitionedRegionLoadModel.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/rebalance/model/RefusalReason.java
geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/rebalance/MemberTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/rebalance/PartitionedRegionLoadModelJUnitTest.java

GEODE-9554: Change up the rebalance calls to use new canDelete call (#6845) (#6853)
GEODE-9554: Change up the rebalance calls to use new canDelete call
If there is no redundancy zone, exit and allow delete
Adding xml files to git
Adding xml files to git
Added new tests
(cherry picked from commit d1d605b24787698c5d8f47b8538808d6b990c0a4)
(cherry picked from commit 142e06fe001aae428c32ec602992e45bcefa2259)
GEODE-5994: Cleanup from some additional review comments (#6852)
(cherry picked from commit 7b924b5ccef4646f28615bab290447824f9f9f45)
(cherry picked from commit 69ca9cdf75904f70d6272286f4322ba90ee8bfa3)

GEODE-9554 backport

---

geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/cluster/ClusterSlotsAndNodesDUnitTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/cluster/AbstractClusterIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RegionProvider.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/KeyHashUtil.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisKey.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/cluster/ClusterExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/StringBytesGlossary.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/parameters/ClusterParameterRequirements.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/KeyHashUtilTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisKeyJUnitTest.java

Adding support for the keyslot command. refactoring the RedisKey code a little
bit to move the slot calculation into a static method that can be used and
tested separately. Changing RedisKey.crc16 to slot, because that is only thing
we are using the crc16 field for.

GEODE-9585: adding support for the KEYSLOT command

---

geode-apis-compatible-with-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/MemoryOverheadIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZAddIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZIncrByIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZScoreIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/AbstractRedisData.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSortedSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSetCommandsFunctionExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/delta/DeltaType.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/delta/ZAddsDeltaInfo.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/delta/ZaddsDeltaInfo.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/RedisSortedSetCommands.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/SortedSetScoreRangeOptions.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZAddExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZIncrByExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
geode-apis-compatible-with-redis/src/main/resources/org/apache/geode/redis/internal/sanctioned-geode-apis-compatible-with-redis-serializables.txt
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/collections/OrderStatisticsTreeTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/collections/SizeableBytes2ObjectOpenCustomHashMapWithCursorTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSortedSetTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/netty/CoderTest.java

RedisSortedSet previously stored the score as both a double and a byte
array in order to cut down on conversions using Coder. This refactor
gets rid of the byte array score and instead does a couple of
conversions. Other refactors were done to accomodate this change and
to improve on what was there

GEODE-9446: Remove unecessary byte arrays from RedisSortedSet

---

geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/sortedset/ZScanNativeRedisIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/AbstractHScanIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/hash/HScanIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZScanIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/ZScanIntegrationTest.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSortedSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHash.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSetCommandsFunctionExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisResponse.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HScanExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/key/AbstractScanExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/key/ScanExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SScanExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/RedisSortedSetCommands.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZScanExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisHashTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSortedSetTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/executor/sortedset/ZScanExecutorTest.java

This PR is intentionally split into two commits, the first refactors the existing *SCAN implementations and some related code. The second implements the ZSCAN command and adds tests. The changes in the first commit also address GEODE-9427 as a side-effect.

GEODE-9519: Implement Radish ZSCAN command

---

geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java

- Close client connection on CancelException
- Fix handling of RedisCommandParserException
- Remove unused constants

GEODE-9552: Change how Radish server shutdown/disconnect is handled

---

geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/KeyHashUtil.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/connection/SelectExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/SortedSetLexRangeOptions.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/SortedSetScoreRangeOptions.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/StringBytesGlossary.java

GEODE-9605: Allow use of character literals in Radish module

---

geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubNativeRedisAcceptanceTest.java

The TIME_WAIT delay for Windows is much larger than either Linux or OSX. This patch allows the test class to determine the actual value of the 'socket reaping' delay in Linux and OSX so that the tests will complete much faster, particularly in CI.

GEODE-9495: Limit Thread Sleep In PubSubNativeRedisAcceptanceTest

---

geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubDUnitTest.java
geode-apis-compatible-with-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RegionProvider.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSubImpl.java
geode-apis-compatible-with-redis/src/main/resources/org/apache/geode/redis/internal/sanctioned-geode-apis-compatible-with-redis-serializables.txt

- getRegionMembers now uses the advisor to compute
the set of members hosting the redis region.
- PubSubImpl now has a PublishFunction in place of the old
anonymous inner class.
- PubSubDUnitTest had a timing issue after killing a server.
The next test would fail due to the state left around by
the test that did the kill. Now this test gives each test
method a new clean slate and is passing consistently.

GEODE-9575: improve how publish executes a function

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/ha/HARegionQueueJUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/ha/HARegionQueue.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientUpdateMessageImpl.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientUpdateMessageImplTest.java
geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/CqDUnitTest.java

* This can occur if HAContainer enables eviction.
* Also addClientCq can be accessed concurrently by intialization threads during queue registration.

GEODE-9596: Avoid creating multiple cq maps in ClientUpdateMessage

---

geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/AbstractGlobPatternIntegrationTest.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHash.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHashCommandsFunctionExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSetCommandsFunctionExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSetCommandsFunctionExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/GlobPattern.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/HScanExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/hash/RedisHashCommands.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/key/AbstractScanExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/key/KeysExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/key/ScanExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/RedisSetCommands.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SScanExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/RedisSortedSetCommands.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZScanExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/AbstractSubscriptionManager.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/ChannelClientSubscriptionManager.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/ClientSubscriptionManager.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PatternClientSubscriptionManager.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PatternSubscriptionManager.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/Subscriptions.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisHashTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSortedSetTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/executor/GlobPatternTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/pubsub/ChannelClientSubscriptionManagerTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/pubsub/SubscriptionsJUnitTest.java

GlobPattern now uses code derived from native redis's glob matching.
It should be completely compatible with native redis unless I broke something
in the conversion to java. This has the benefit of being able to do the match with
a byte array (the jdk matcher required a conversion to a String).
This also cleaned up some of our other code that handled the exception
thrown from the jdk when compiling a pattern.

GEODE-9582: make radish pattern match compatible with redis

---

geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/BadCacheLoaderDUnitTest.java
geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-core/src/main/java/org/apache/geode/distributed/internal/ReplyMessage.java
geode-core/src/test/java/org/apache/geode/distributed/internal/ReplyMessageTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/PutPutReplyMessageJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/tx/RemotePutReplyMessageJUnitTest.java

The original PR #6392 was closed because I took over the work on this ticket.
A not serializable exception can cause a ServerConnection thread to get stuck
waiting for a reply from another member. This is caused by ReplyMessage
not handling a non-serializable "returnValue".
The fix is to catch and log the exception in the sending node and then
handle the problem in the receiving node.
I would have liked to serialize the "returnValue" field into a separate buffer
so as not to transmit a partial serialization of the object but that would require
an extra buffer copy for every ReplyMessage sent, and we send a lot of them. …

GEODE-9204: thread hung waiting for response

---

geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractPubSubIntegrationTest.java

GEODE-9606: Fix flaky PubSubIntegrationTest.testPatternWithoutAGlob

---

README.md

Jira ticket: https://issues.apache.org/jira/projects/GEODE/issues/GEODE-9619
Came here from ApacheCon, saw this and thought I'll start my contributions here 😄 
This PR adds changes to format the contents section of the README in a way that the 9th and 10th list element are not rendered on to the same line. I've also changed the numbering from 1,2,3,4 to 1,1,1,1 so that Markdown can figure out the numbering (lesser chance of missing a number in the list)

GEODE-9619: [documentation] Align contents section in README

---

geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheXmlPropertyResolver.java

This PR fixes the spelling for one of the important error log messages for configuration settings coming from XML for parameterized attribute values.

GEODE-9611: fixed the incorrect spelling

---

geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/connection/AuthNativeRedisAcceptanceTest.java
geode-apis-compatible-with-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/AbstractAuthIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/AuthIntegrationTest.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/RedisResponse.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/StringBytesGlossary.java

- A default ResourcePermission of DATA:WRITE:REDIS_DATA is used. This
can be overridden by setting the system property
redis.resource-permission.
- If available, every request is authorized against the SecurityManager.

GEODE-9547: Radish commands are authorized by the SecurityManager

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt
geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalCache.java
geode-core/src/main/java/org/apache/geode/internal/cache/InternalCacheForClientAccess.java
geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/CacheCreation.java
geode-docs/tools_modules/lucene_integration.html.md.erb
geode-lucene/build.gradle
geode-lucene/src/integrationTest/java/org/apache/geode/cache/lucene/internal/repository/IndexRepositoryImplJUnitTest.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/IndexRepositoryFactory.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneEventListener.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneIndexStats.java
geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/repository/IndexRepositoryImpl.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/IndexRepositoryFactoryTest.java
geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/LuceneServiceImplJUnitTest.java
geode-lucene/src/upgradeTest/java/org/apache/geode/cache/lucene/LuceneSearchWithRollingUpgradeDUnit.java
geode-lucene/src/upgradeTest/java/org/apache/geode/cache/lucene/LuceneSearchWithRollingUpgradeTestBase.java
geode-lucene/src/upgradeTest/java/org/apache/geode/cache/lucene/RollingUpgradeQueryReturnsCorrectResultAfterTwoLocatorsWithTwoServersAreRolled.java
geode-lucene/src/upgradeTest/java/org/apache/geode/cache/lucene/RollingUpgradeQueryReturnsCorrectResultsAfterClientAndServersAreRolledOver.java
geode-lucene/src/upgradeTest/java/org/apache/geode/cache/lucene/RollingUpgradeQueryReturnsCorrectResultsAfterClientAndServersAreRolledOverAllBucketsCreated.java
geode-lucene/src/upgradeTest/java/org/apache/geode/cache/lucene/RollingUpgradeReindexShouldBeSuccessfulWhenAllServersRollToCurrentVersion.java

The fix for GEODE-7309 causes failures during the rolling upgrade. This commit needs to be reverted while we are investigating the root cause.
This reverts commit 68629356f561a932f5dfbace70b01d9971a42473.

Revert "GEODE-7309: uplift lucene to 7.1.0 (#6351)"

---

geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/misc/AuthenticationExpiredWANDunitTest.java

- Confirm that client operations propagate across WAN connections when
client connections expire and reconnect

GEODE-9459: testing clients with WAN connected cluster

---

geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb

This PR adds a note on the user guide about the correct order to start regions and gateway receivers to avoid the issue described in [this dev list thread](https://markmail.org/thread/qq32z5hducjoqndz)

GEODE-9479: Document receivers & regions start order

---

geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/pubsub/PubSubNativeRedisAcceptanceTest.java

Update how we get and calculate the TIME_WAIT value on Linux, as well as reduce the default thread sleep to 90 seconds.

GEODE-9495: limit thread sleep in pub sub native redis acceptance test

---

geode-apis-compatible-with-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/sortedset/ZInterStoreNativeRedisAcceptanceTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/AbstractHitsMissesIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZInterStoreIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/AbstractZUnionStoreIntegrationTest.java
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/sortedset/ZInterStoreIntegrationTest.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RegionProvider.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisSortedSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSetCommandsFunctionExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/RedisSortedSetCommands.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZAggregator.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZInterStoreExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZKeyWeight.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZStoreExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZUnionStoreExecutor.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSortedSetTest.java

ZINTERSTORE command takes the intersection of N sorted sets and stores
the results, either summing, taking the max, or taking the min of all
the scores for each member. The provided destination key will be
overridden if it already exists.

GEODE-9516: add ZINTERSTORE command

---

geode-apis-compatible-with-redis/src/distributedTest/java/org/apache/geode/redis/OutOfMemoryDUnitTest.java
geode-apis-compatible-with-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
geode-apis-compatible-with-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisService.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RegionProvider.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/AbstractExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PublishExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/SubscribeExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSub.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/PubSubImpl.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/pubsub/Publisher.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/pubsub/PubSubImplTest.java
geode-apis-compatible-with-redis/src/test/java/org/apache/geode/redis/internal/pubsub/PublisherTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/control/HeapMemoryMonitor.java
geode-serialization/src/main/java/org/apache/geode/internal/serialization/DataSerializableFixedID.java

Moved all of the publish code from PubSubImpl to Publisher.
This new class is able to batch the publish requests instead
of always sending them one at a time to other servers.
Also the ExecutorService used for publishing is now correctly configured (thanks to Jens for figuring this out) so that it can use more than one thread for publishing.
Both the publish and subscribe executor now do a critical memory check and will throw a  LowMemoryException

GEODE-9607: prevent pubsub from running server out of memory

---

geode-core/src/main/java/org/apache/geode/cache/wan/GatewaySender.java
geode-core/src/main/java/org/apache/geode/cache/wan/GatewaySenderFactory.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySender.java

The following setter has been removed from the GatewaySender
interface: setRetriesToGetTransactionEventsFromQueue()

GEODE-9629: Remove from the GatewaySender API one setter method.

---

geode-core/src/main/java/org/apache/geode/internal/cache/control/SerializableRegionRedundancyStatusImpl.java
geode-core/src/test/java/org/apache/geode/internal/cache/control/SerializableRegionRedundancyStatusImplTest.java
geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/StatusRedundancyCommandDUnitTest.java

When a partition redundant region is empty, `status redundancy` command shows a wrong redundancy value for that region.
```
gfsh>status redundancy
Number of regions with zero redundant copies = 0
Number of regions with partially satisfied redundancy = 1
Number of regions with fully satisfied redundancy = 0
Redundancy is partially satisfied for regions: 
test redundancy status: NOT_SATISFIED. Desired redundancy is 1 and actual redundancy is 2147483647.
```
Problem is in `SerializableRegionRedundancyStatusImpl` class. The `calculateLowestRedundancy` initializes `minRedundancy` variable with `Integer.MAX_VALUE`. But for empty regions, all buckets have redundancy -1, so `minRedundancy` is not modified, and returned with that value.
I propose to check `minRedundancy` value before returning it. …

GEODE-9624: Fix 'status redundancy' result for empty regions

---

geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/LolWutIntegrationTest.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/server/LolWutExecutor.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/netty/StringBytesGlossary.java

This implements a version of the Redis LOLWUT command, which is supposed to (a) algorithmically generate computer art, and (b) output the program version. Optionally, the LOLWUT command can take arguments to affect the output.
This implementation generates arbitrary-size mazes. By default, it generates a 40-cell-wide maze of height 10, but given arguments it can generate a valid maze of any width and height, while consuming a small and fixed amount of memory. After the maze, it outputs the Geode version.

GEODE-9650: LOLWUT command

---

geode-apis-compatible-with-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch

- Until we can evaluate whether it is feasible to re-enable this test
(and provide an underlying fix).

GEODE-9672: Disable native redis multibulk test

---

geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/server/CommandIntegrationTest.java
geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/executor/server/CommandExecutor.java

- If the `enable-unsupported-commands` system property is not enabled
then the COMMAND command should not return information about
unsupported commands in its response.

GEODE-9623: Unsupported commands should not be returned by COMMAND when not enabled

---

geode-core/src/main/java/org/apache/geode/internal/cache/EventID.java
geode-core/src/test/java/org/apache/geode/internal/cache/EventIDTest.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientCQClusterRestartDUnitTest.java

* This is to make sure a new EventID can be generated after server restarted
after a whole cluster is shut down.

GEODE-9640: Initiate threadId in EventID.

---

geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
geode-core/src/main/java/org/apache/geode/distributed/internal/AbstractDistributionConfig.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfigImpl.java
geode-core/src/main/java/org/apache/geode/distributed/internal/LonerDistributionManager.java
geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionConfigJUnitTest.java
geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/GeodeRedisServerStartupDUnitTest.java
geode-for-redis/src/commonTest/java/org/apache/geode/redis/GeodeRedisServerRule.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/RegionProvider.java

We decided to rename this new property
This reverts commit caa561f9fbdd98af9c06b6312d79559866c29a4e.

Revert "GEODE-9756: add geode-for-redis-replica-count gemfire property"

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/ConnectionFactoryImpl.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/ConnectionFactoryImplTest.java
geode-cq/src/distributedTest/java/org/apache/geode/security/MultiUserAPIDUnitTest.java
geode-junit/src/main/java/org/apache/geode/security/templates/TrackableUserPasswordAuthInit.java

It's observed that AuthenticationRequest will come in multiple times in the same connection by different threads. This PR would fix that.

GEODE-9792: avoid sending in multiple authentication request on the same connection by different threads

---

geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
geode-core/src/main/java/org/apache/geode/distributed/internal/AbstractDistributionConfig.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java
geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfigImpl.java
geode-core/src/main/java/org/apache/geode/distributed/internal/LonerDistributionManager.java
geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionConfigJUnitTest.java
geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/GeodeRedisServerStartupDUnitTest.java
geode-for-redis/src/commonTest/java/org/apache/geode/redis/GeodeRedisServerRule.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/RegionProvider.java

This is the same as the previous pull request for GEODE-9756 except that the name of the property is now "geode-for-redis-redundant-copies".

GEODE-9756: add  "geode-for-redis-redundant-copies" gemfire property

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/PRClientServerRegionFunctionExecutionSingleHopDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/execute/PartitionedRegionFunctionExecutor.java
geode-core/src/test/java/org/apache/geode/internal/cache/execute/PartitionedRegionFunctionExecutorTest.java
geode-dunit/src/main/java/org/apache/geode/internal/cache/functions/TestFunction.java

GEODE-9774: Clear networkHop variable at function execution exit

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-apis-compatible-with-redis/build.gradle
geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/pubsub/AbstractPubSubIntegrationTest.java
geode-apis-compatible-with-redis/src/test/resources/expected-pom.xml
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt
geode-assembly/src/integrationTest/resources/expected_jars.txt

Upgrading the version of netty we are using.
In order to upgrade, Putting sleep in PubSubIntegrationTest to work around  GEODE-9050. 
This is not a fix for the underlying race condition in the product but just a
workaround to make this test pass so we can continue to upgrade netty on this
support branch. The actual fix will in 1.15.
The race condition is that a subscription may miss events that are published 
immediately after the subscription but before the subscription finishes changing
the event loop group for the channel.

GEODE-9767: Bump netty from 4.1.59.Final to 4.1.70.Final

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt

don't merge until after #7031, #7032, and #7033

GEODE-9767: Bump netty from 4.1.48.Final to 4.1.68.Final

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/OpExecutorImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/UserAttributes.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/OpExecutorImplUnitTest.java
geode-cq/src/distributedTest/java/org/apache/geode/security/MultiUserAPIDUnitTest.java
geode-junit/src/main/java/org/apache/geode/security/templates/CountableUserPasswordAuthInit.java

Avoid making multiple authentication requests in multi-user case.
Also remove some unnecessary code and small refactoring.

GEODE-9792: synchronize multi-user authentication on different threads

---

geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/AuthIntegrationTest.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/netty/Command.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
geode-for-redis/src/test/java/org/apache/geode/redis/internal/netty/CommandJUnitTest.java

- Rather than returning the arguments of the AUTH command, only return
how many arguments there are when toString() is called

GEODE-9805: Do not log arguments of Radish AUTH command

---

geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/ClusterDistributionManagerDUnitTest.java

This test has a number of problems, in addition to the flakiness described in the bug report, to wit:
- The comment “Demonstrate that a new UDP port is used…” is at odds with the assertion at the end of the method (which asserts that the same port is used).
- Contrary to the comment, GMSMembership doesn’t “shun” members when they are shutting down, rather it keeps them in a shutdownMembers set so as to attenuate failure detection signals from them. Perhaps in the dim past these members were actually “shunned”?
- I have no idea why the test disconnect()s, then re-acquires system and membership and then disconnect()s again before calling getLocalMember() on the membership acquired before the second disconnect!
- The TODO at line 167 seems superfluous since we proceed to set just such a …

GEODE-9675: remove useless but flaky test

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/DeltaPropagationDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/ClientServerConnectDisconnectDistributedTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/security/SecurityWithExpirationIntegrationTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxy.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientUserAuths.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxyTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientUserAuthsTest.java
geode-junit/src/main/java/org/apache/geode/security/ExpirableSecurityManager.java

In some cases, client will send in Authentication request with existing uniqueId (in both re-auth or non-re-auth cases), we used to just replace the old subject with the new subject and log out the old subject immediately, but this old subject might already be bound with a running thread, hence causing "FailedToFindSubject" exception on that thread. We can't immediately log out the old subject, so we have to keep reference of them and log out them all at connection closing time.
This PR also includes a minor fix in CacheClientProxy for completeness of the logic

GEODE-9746: do not logout old subjects immediately when we get a new subject for the same uniqueId

---

geode-core/src/distributedTest/java/org/apache/geode/logging/internal/LoggingWithReconnectDistributedTest.java

- Change LoggingWithReconnectDistributedTest.createServer() to use
AvailablePortHelper

GEODE-9802: Do not use ephemeral port in test

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/cache/wan/SeveralGatewayReceiversWithSamePortAndHostnameForSendersTest.java
geode-assembly/src/integrationTest/java/org/apache/geode/rest/internal/web/RestInterfaceIntegrationTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/QueryIndexUsingXMLDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ha/EventIdOptimizationDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/management/internal/unsafe/ReadOpFileAccessControllerJUnitTest.java
geode-core/src/main/java/org/apache/geode/admin/internal/DistributedSystemConfigImpl.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/HashIndex.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/IndexManager.java
geode-core/src/main/java/org/apache/geode/internal/cache/AbstractDiskRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/DiskInitFile.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/main/java/org/apache/geode/internal/lang/StringUtils.java
geode-core/src/main/java/org/apache/geode/internal/lang/SystemUtils.java
geode-core/src/main/java/org/apache/geode/internal/shared/StringPrintWriter.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/BeanUtilFuncs.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/MemberMBeanBridge.java
geode-dunit/src/main/java/org/apache/geode/management/internal/cli/commands/ShowLogCommandDistributedTestBase.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/CliUtils.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/AlterRuntimeConfigCommand.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/RebalanceCommand.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommand.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/StartServerCommand.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/domain/DataCommandRequest.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/functions/ExportConfigFunction.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/shell/Gfsh.java
gradle/test.gradle

* Replace synchronized System.getProperty("line.separator") calls with
System.lineSeparator().

GEODE-6588: Use System.lineSeparator()

---

geode-web-management/src/main/java/org/apache/geode/management/internal/rest/ManagementLoggingFilter.java

- This can cause spurious DUnit suspect logging failures.

GEODE-9090: Do not log non-printable characters when debug logging from ManagementLoggingFilter

---

geode-for-redis/README.md
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/StartServerCommand.java

-- fixed README.md to not say experimental
-- fixed gfsh start server radish option help to not say experimental

GEODE-9566: change geode-for-redis to not be experimental

---

geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/key/DumpRestoreIntegrationTest.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/AbstractRedisData.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisData.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/cluster/ClusterExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/connection/PingExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/key/AbstractScanExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/key/RestoreExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/key/ScanExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PsubscribeExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/PubSubExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/pubsub/SubscribeExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/server/InfoExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/server/LolWutExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/server/SlowlogExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/set/SScanExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/AbstractSortedSetRangeOptions.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/SortedSetLexRangeOptions.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZAddExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/sortedset/ZStoreExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/string/SetExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/netty/ByteToCommandDecoder.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/netty/Coder.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/netty/StringBytesGlossary.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/parameters/SlowlogParameterRequirements.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/pubsub/Publisher.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/pubsub/Subscriptions.java
geode-for-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSortedSetTest.java
geode-for-redis/src/test/java/org/apache/geode/redis/internal/netty/CoderTest.java
geode-for-redis/src/test/java/org/apache/geode/redis/internal/pubsub/SubscriptionsJUnitTest.java

Removed 'b' prefix on all byte arrays and added "_STRING" to string constants.
- [ x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?
- [NA] Have you written or updated unit tests to verify your changes?

GEODE-9449: Remove 'b' prefix from constants

---

geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/executor/connection/ClientNativeRedisAcceptanceTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/AbstractClientIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/connection/ClientIntegrationTest.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/RedisCommandType.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/executor/connection/ClientExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/netty/Client.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/netty/StringBytesGlossary.java
geode-log4j/src/main/resources/log4j2.xml

GEODE-9816: Added CLIENT SETNAME and GETNAME commands.

---

geode-connectors/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeConnectorsSerializablesIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeCoreSerializablesIntegrationTest.java
geode-cq/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeCQSerializablesIntegrationTest.java
geode-dunit/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeDUnitSerializablesIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeRedisSerializablesIntegrationTest.java
geode-gfsh/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeGfshSerializablesIntegrationTest.java
geode-junit/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeJUnitSerializablesIntegrationTest.java
geode-junit/src/main/java/org/apache/geode/codeAnalysis/AnalyzeDataSerializablesTestBase.java
geode-junit/src/main/java/org/apache/geode/codeAnalysis/AnalyzeDataSerializablesWithClassAnalysisRuleTestBase.java
geode-junit/src/main/java/org/apache/geode/codeAnalysis/AnalyzeSerializablesTestBase.java
geode-junit/src/main/java/org/apache/geode/codeAnalysis/AnalyzeSerializablesWithClassAnalysisRuleTestBase.java
geode-junit/src/main/java/org/apache/geode/codeAnalysis/SanctionedSerializablesServiceIntegrationTestBase.java
geode-junit/src/main/java/org/apache/geode/test/junit/rules/ClassAnalysisRule.java
geode-junit/src/main/resources/org/apache/geode/test/junit/internal/sanctioned-geode-junit-serializables.txt
geode-lucene/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeLuceneSerializablesIntegrationTest.java
geode-management/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeManagementSerializablesIntegrationTest.java
geode-membership/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeMembershipSerializablesIntegrationTest.java
geode-memcached/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeMemcachedSerializablesIntegrationTest.java
geode-pulse/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzePulseSerializablesIntegrationTest.java
geode-wan/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeWANSerializablesIntegrationTest.java
geode-web-api/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeWebApiSerializablesIntegrationTest.java

Adds support for pluggable source set paths to ClassAnalysisRule.
PROBLEM
Modules external to Geode must be structured the same as Geode
source code in order to use ClassAnalysisRule and the
Analyze*Serializables tests. This is necessary to better facilitate
pluggability of modules that need to provide sanctioned serializable 
lists.
SOLUTION
Add source set path customization to ClassAnalysisRule, introduce
a new layer of Analyze*Serializables test base classes that can be
directly extended in order to customize source set paths in
ClassAnalysisRule. Also includes improvements to some iterating
of classes during analysis.

GEODE-9817: Enable customized source set paths for ClassAnalysisRule

---

geode-core/src/upgradeTest/java/org/apache/geode/security/AuthExpirationBackwardCompatibleDUnitTest.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/command/StopCQ.java

Problem:
StopCQ with expired credentials does not trigger re-authentication.
Cause:
the server side doesn't send the AuthenticationExpiredException to the client with the `MessageType.EXCEPTION`, rather it only sends down only the error message with `MessageType.CQ_EXCEPTION_TYPE`, that's now how it's generally handled.

GEODE-9820: stopCQ should handle general exception same way as ExecuteCQ61

---

geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/P2PMessagingConcurrencyDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java

[GEODE-9825](https://issues.apache.org/jira/browse/GEODE-9825)
When `Connection.processInputBuffer()` needed to expand the input buffer, it was also destroying unprocessed data. This resulted in `IOException: "Unknown header byte..."` and hangs.
The `P2PMessagingConcurrencyDUnitTest` has been enhanced to test a matrix of configurations:
[conserve-sockets, useTLS, socket-buffer-size for sender, socket-buffer-size for receiver]
```
"true, true, 32768, 32768",
"true, true, 65536, 32768",
"true, true, 32768, 65536",
"true, true, 1024, 1024",
"true, false, 32768, 32768",
"true, false, 65536, 32768",
"true, false, 32768, 65536",
"true, false, 1024, 1024",
"false, true, 32768, 32768",
"false, true, 65536, 32768",
"false, true, 32768, 65536",
"false, true, 1024, 1024",
"false, false, 32768, …
```

GEODE-9825: Disparate socket-buffer-size Results in "IOException: Unknown header byte" and Hangs

---

geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/string/StringsKillMultipleServersDUnitTest.java

- Despite data loss, the test ensures that operations continue without
errors related to MOVED responses or missing slots.

GEODE-9812: Add Radish tests that kills multiple servers

---

geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/P2PMessagingConcurrencyDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedExecutorServiceRuleLimitedThreadCountTest.java
geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedExecutorServiceRuleLimitedVmCountTest.java
geode-dunit/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/DistributedExecutorServiceRuleUnlimitedThreadCountTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/DistributedExecutorServiceRule.java
geode-dunit/src/main/resources/org/apache/geode/test/dunit/internal/sanctioned-geode-dunit-serializables.txt
geode-junit/src/main/java/org/apache/geode/test/junit/rules/ExecutorServiceRule.java
geode-junit/src/main/resources/org/apache/geode/test/junit/internal/sanctioned-geode-junit-serializables.txt

This PR will be _rebased_ onto `support/1.14`. It has two cherry-picked commits.

GEODE-9825: Back-Port to 1.14

---

geode-core/src/integrationTest/java/org/apache/geode/internal/AvailablePortHelperIntegrationTest.java
geode-junit/src/main/java/org/apache/geode/internal/AvailablePortHelper.java

PROBLEMS
- In test JVMs, `AvailablePortHelper` initialized its next candidate
port by selecting a random port within the available port range. This
often caused the test JVM's first few candidates to overlap with the
first few candidates of a child VM.
- `AvailablePortHelper` updated its next candidate port in non-atomic
way, making it possible for multiple threads to receive the same port
number.
SOLUTION
Change `AvailablePortHelper` to:
- Initialize its next candidate port to `AVAILABLE_PORT_LOWER_BOUND`
instead of randomly selecting an initial candidate.
- Update its next candidate port atomically by calling
`AtomicInteger.getAndUpdate(...)`.

GEODE-9824: Initialize AvailablePortHelper safely

---

buildSrc/build.gradle

* dependency of grgit used in GemFireVersion.properties

GEODE-9862: pin Gradle use of jgit

---

geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/AbstractRedisInfoStatsIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/string/AbstractAppendMemoryIntegrationTest.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/server/InfoExecutor.java

- For this implementation, this value is the ratio of memory available
to the partitioned region (Java heap) vs. the memory used by data in
the region.

GEODE-9669: Improve reporting of Radish mem_fragmentation_ratio

---

geode-core/src/main/java/org/apache/geode/internal/security/IntegratedSecurityService.java
geode-core/src/test/java/org/apache/geode/internal/security/IntegratedSecurityServiceTest.java

The client will receive this exception instead so that it can try to talk to another available server

GEODE-9811: Turn UnavailableSecurityManagerException into CacheClosedException

---

ci/pipelines/shared/jinja.variables.yml

- In the future, when the baseline needs to be moved, this branch can
simply be reset to the required SHA.

GEODE-9863: Point redis benchmarks at geode-for-redis-benchmark-baseline branch

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/Handshake.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java
geode-core/src/main/java/org/apache/geode/internal/security/IntegratedSecurityService.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/HandshakeTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionTest.java
geode-core/src/test/java/org/apache/geode/internal/security/IntegratedSecurityServiceTest.java

* fix this in the login method as well. CacheClosedException should be thrown all the way back to the client.

GEODE-9811: Turn UnavailableSecurityManagerException into CacheClosedException (part 2)

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxy.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/MessageDispatcher.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/MessageDispatcherTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionTest.java

* Only to update suject on the ClientCacheProxy if it's waiting for re-auth
* logout the subject in one place when we close the dispatcher

GEODE-9803: Fix the flaky "Failed To find authenticated user" problem

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionTest.java

Connection would continue to process message even after it's been marked as terminated by the message dispatcher

GEODE-9867: do not process the message if the connection is terminated

---

geode-for-redis/src/distributedTest/java/org/apache/geode/redis/ExpiringSecurityManager.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/UserExpirationDUnitTest.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java

- For requests that result in an AuthenticationExpiredException, the
response will be: `-ERR Authentication expired: <Exception message>`.
Clients will be expected to handle this error and take the necessary
action to re-authenticate.

GEODE-9873: Add AuthenticationExpiredException message to Radish error response

---

geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/ClientServerTransactionFailoverWithMixedVersionServersDistributedTest.java

PROBLEM
`ClientServerTransactionFailoverWithMixedVersionServersDistributedTest`
misused ephemeral ports. Some tests start a locator on an ephemeral
port, stop the locator, and attempt to restart it on the same port.
During the time the locator is stopped, the OS can assign that port to another process. When that happens, as in these failures, the test is unable to restart the locator.
SOLUTION
Change the test to use `AvailablePortHelper` to assign an available
port, rather than requesting an ephemeral port.

GEODE-9622: Make failover test not use ephemeral port

---

geode-for-redis/src/commonTest/java/org/apache/geode/test/dunit/rules/RedisClusterStartupRule.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/auth/AuthWhileServersRestartDUnitTest.java

- Since servers have been stopped and restarted, as part of the test,
buckets may be moving. Occasionally this may still be the case when
the test is done and flushAll is cleaning up. To avoid that, make sure
that everything is rebalanced before flushAll is called.

GEODE-9870: Avoid Radish MOVED error during flushAll in AuthWhileServersRestartDUnitTest

---

geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/DUnitLauncher.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java
geode-dunit/src/main/resources/org/apache/geode/test/dunit/internal/sanctioned-geode-dunit-serializables.txt

PROBLEM
`DistTXPersistentDebugDUnitTest ` failed in CI because it accidentally
connected to a locator from another test
(`ClusterConfigLocatorRestartDUnitTest`).
CAUSE
`ClusterConfigLocatorRestartDUnitTest` attempts to restart a
locator on a port in the ephemeral port range.
Here is the sequence of events:
1. `ClusterConfigLocatorRestartDUnitTest ` started a locator on an
ephemeral port. In this CI run it got port 37877.
2. `ClusterConfigLocatorRestartDUnitTest` stopped the locator on port
37877.
3. `DistTXPersistentDebugDUnitTest` started a locator on an ephemeral
port. In this CI run it got 37877.
4. `ClusterConfigLocatorRestartDUnitTest ` attempted to restart the
locator on port 37877. That port was already in use in
`DistTXPersistentDebugDUnitTest`'s locator, and as a result the two …

GEODE-9872: Make test framework code assign ports

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/DiskRegionCompactorClearsObjectThatAreNoLongerNeededIntegrationTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/Oplog.java

Issue:
An OpLog files are compacted, but the .drf file is left because it contains deletes of 
entries in previous .crfs. The .crf file is deleted, but the orphaned .drf is not until all 
previous .crf files (.crfs with smaller id) are deleted.
The problem is that compacted Oplog object representing orphaned .drf file holds
a structure in memory (Oplog.regionMap) that contains information that is not useful 
after the compaction and it takes certain amount of memory. Besides, there is a special 
case when creating .krf files that, depending on the execution order, 
could make the problem more severe (it could leave pendingKrfTags structure
on the regionMap and this could take up a significant amount of memory). This
pendingKrfTags HashMap is actually empty, but consumes memory because it …

GEODE-9854: Orphaned .drf file causing memory leak

---

geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/GeodeRedisServerStartupAcceptanceTest.java
geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/commands/executor/GeodeRedisServerStartupUsingGfshAcceptanceTest.java

- For some unknown reason `startupFailsGivenPortAlreadyInUse` started to
fail after a seemingly innocuous Ubuntu base image bump. The problem
may also have been triggered by arbitrary test ordering changes since
the test did not fail on its own, but only in conjunction with running
other tests beforehand.
Specifically, the test was failing when binding the interfering port
(bind exception). The port used was always in the TIME_WAIT state left
from previous tests.
Using a `ServerSocket`, instead of a regular socket, fixes the problem
since it actually 'uses' the port and implicitly allows for port
reuse.

GEODE-9877: Use ServerSocket to create interfering port

---

geode-common/src/main/java/org/apache/geode/internal/lang/utils/ClassUtils.java
geode-common/src/test/java/org/apache/geode/internal/lang/utils/ClassUtilsTest.java
geode-core/src/main/java/org/apache/geode/distributed/AbstractLauncher.java
geode-core/src/main/java/org/apache/geode/internal/InternalDataSerializer.java
geode-core/src/test/java/org/apache/geode/internal/InternalDataSerializerSerializationAcceptlistTest.java
geode-core/src/test/java/org/apache/geode/internal/InternalDataSerializerShiroAcceptListTest.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeDiskStoreCommand.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/shell/Gfsh.java
geode-junit/src/main/java/org/apache/geode/codeAnalysis/CompiledClassUtils.java
geode-serialization/src/test/java/org/apache/geode/internal/serialization/SerializationDependenciesTest.java
geode-web-api/src/main/java/org/apache/geode/rest/internal/web/util/NumberUtils.java

Serialization filtering pull requests can be very large so it may be
better to submit this change separately to help with reviews.
This PR consists of just the one commit below on top of #7165.
Please review only this commit:
[GEODE-9758: Move ClassUtils to geode-common ](https://github.com/apache/geode/pull/7166/commits/e2c65a14f6adba10ed4596c59850b9fee9ab4002)
Move ClassUtils to geode-common so that geode-serialization
can use ClassUtils.
Remove "JUnit" from the name of a couple tests.

GEODE-9758: Move ClassUtils to geode-common

---

geode-core/src/main/java/org/apache/geode/internal/cache/EntryExpiryTask.java
geode-core/src/main/java/org/apache/geode/internal/cache/ExpiryTask.java
geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
geode-core/src/main/java/org/apache/geode/internal/cache/RegionIdleExpiryTask.java
geode-core/src/main/java/org/apache/geode/internal/cache/RegionTTLExpiryTask.java
geode-core/src/test/java/org/apache/geode/internal/cache/ExpiryTaskTest.java

If we are within half of a second of the scheduled
expiration time then expiration will now happen.
Before we would reschedule for a fraction of a second.

GEODE-9148: prevent expiration reschedules

---

geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
geode-for-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSetTest.java

- This adds synchronization for methods where there is interaction
between core Geode functionality and Radish operations. Specifically
where `toData` may be called (during GII) and regular operations that
mutate the underlying data structure in a `RedisSet`.

GEODE-9899: Fix synchronization for RedisSet

---

geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/NativeRedisClusterTest.java
geode-for-redis/src/commonTest/java/org/apache/geode/redis/ClusterNodes.java
geode-for-redis/src/commonTest/java/org/apache/geode/redis/NativeRedisClusterTestRule.java

- This fix also addresses GEODE-9428 where CLUSTERDOWN is occasionally
reported.
- The NativeRedisClusterTestRule now checks each node to make sure they
are all reporting the correct node count instead of just one. Nodes
are not always all ready at once.
- When processing CLUSTER INFO sometimes a 'master' reports with no
slots which indicates it is transitioning or will become a replica.
Originally we would mark such a node as a replica even before it had
fully transitioned. However, this would cause problems since it then
resulted in a too early report that the cluster was ready.

GEODE-9810: More robust waiting for native Redis cluster to start

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt
geode-docs/managing/logging/configuring_log4j2.html.md.erb
geode-docs/managing/logging/how_logging_works.html.md.erb

just to show we're keeping up; Geode is not vulnerable to the recursive substitution issue fixed in Log4j 2.17

GEODE-9905: Bump log4j from 2.16.0 to 2.17.0

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt
geode-docs/managing/logging/configuring_log4j2.html.md.erb
geode-docs/managing/logging/how_logging_works.html.md.erb
geode-wan/build.gradle

(cherry picked from commit 45714b36b04f89b56c81e97cb03fc0fbf95f58c9)

GEODE-9905: [1.14] Bump log4j from 2.16.0 to 2.17.0

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt
geode-docs/managing/logging/configuring_log4j2.html.md.erb
geode-docs/managing/logging/how_logging_works.html.md.erb
geode-wan/build.gradle

Co-authored-by: Owen Nichols <34043438+onichols-pivotal@users.noreply.github.com>
(cherry picked from commit 45714b36b04f89b56c81e97cb03fc0fbf95f58c9)
(cherry picked from commit 9805c506a34e173a1da829acd3a4450ab3349f03)

GEODE-9905: [1.13] Bump log4j from 2.16.0 to 2.17.0 (#7216)

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt
geode-docs/managing/logging/configuring_log4j2.html.md.erb
geode-docs/managing/logging/how_logging_works.html.md.erb
geode-wan/build.gradle

Co-authored-by: Owen Nichols <34043438+onichols-pivotal@users.noreply.github.com>
(cherry picked from commit 45714b36b04f89b56c81e97cb03fc0fbf95f58c9)
(cherry picked from commit 9805c506a34e173a1da829acd3a4450ab3349f03)
(cherry picked from commit c257bdd545a1749b8709fd4bc25c819ea6a06c76)

GEODE-9905: [1.12] Bump log4j from 2.16.0 to 2.17.0

---

ci/images/google-geode-builder/packer.json

with half a dozen releases last month, the default size is running out of space...

increase disk quota to hold more old versions

---

geode-wan/src/main/java/org/apache/geode/cache/wan/internal/GatewaySenderEventRemoteDispatcher.java
geode-wan/src/test/java/org/apache/geode/cache/wan/internal/GatewaySenderEventRemoteDispatcherJUnitTest.java

This deadlock happens when server is shutdown gracefully.
"Distributed system shutdown hook" thread initiates shutdown threads
"ConcurrentParallelGatewaySenderEventProcessor Stopper Thread"
and waits for them to finish.
Every "ConcurrentParallelGatewaySenderEventProcessor Stopper Thread"
then set flag AckReaderThread.shutdown indicating that AckReaderThread
should be also shutdown and waits for it by joining the threads for max 15 seconds.
The "AckReaderThread for : Event Processor for GatewaySender_sender"
thread blocks during shutdown because it tries to acquire the lock that was
already acquired by "Distributed system shutdown hook" thread.
This deadlock only last for 15 seconds, because thread join
will expire for all  "ConcurrentParallelGatewaySenderEventProcessor
Stopper Thread" …

GEODE-9887: Fix for deadlock during server shutdown

---

geode-junit/src/main/java/org/apache/geode/test/junit/rules/ExecutorServiceRule.java

- This can be used in tests to create custom named executor threads. For
example, something like:
```
@Rule
public ExecutorServiceRule executor = new ExecutorServiceRule()
.withThreadNameFunction((p, t) -> "CUSTOMNAME-pool-%d-thread-%d");
```

GEODE-9911: Allow ExecutorServiceRule to name threads

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/MessageDispatcher.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifierTest.java

Added unit test that reproduced the socket leak.
This involved some change to the product classes
to make them unit testable.
Fixed the leak by making sure socket.close is called
if the response code was not successful.

GEODE-9819: fix durable client socket leak

---

geode-core/src/upgradeTest/java/org/apache/geode/security/AuthExpirationBackwardCompatibleDUnitTest.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/command/CloseCQ.java
geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/command/StopCQ.java
geode-cq/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/CloseCQTest.java
geode-cq/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/StopCQTest.java

- in CloseCQ command
- minor modification in response writing in StopCQ command where we now
check if need to use chunked response
- triage involved checking all other commands that require authorization on their handling of `AuthenticationExpiredException` (either direct or bubble up)

GEODE-9900: ensure AuthenticationExpiredException handling

---

geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/data/PartitionedRegionStatsUpdateTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/key/AbstractDelIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/key/AbstractExistsIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/key/AbstractExpireIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/key/AbstractPexpireIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/key/AbstractRenameIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/key/AbstractRenameNXIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/key/AbstractScanIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/key/AbstractUnlinkIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/key/ScanIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSCardIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSDiffIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSDiffStoreIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSInterIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSIsMemberIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSMoveIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSUnionIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/sortedset/AbstractZInterStoreIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/sortedset/AbstractZUnionStoreIntegrationTest.java
geode-for-redis/src/test/java/org/apache/geode/redis/internal/data/KeyHashUtilTest.java

- Instead of {user1} or variants thereof, use {tag1} to prevent
confusion

GEODE-9932: Change naming convention for Redish hash tags in tests

---

buildSrc/src/main/groovy/org/apache/geode/gradle/testing/repeat/RepeatTest.groovy
buildSrc/src/main/java/org/apache/geode/gradle/testing/repeat/ExecutionTrackingTestClassProcessor.java
buildSrc/src/main/java/org/apache/geode/gradle/testing/repeat/ExecutionTrackingTestResultProcessor.java
buildSrc/src/main/java/org/apache/geode/gradle/testing/repeat/RepeatTestExecuter.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/ProcessManager.java

PROBLEM
Our repeat test tasks merge the output from all executions of a given
test class, making it very difficult to diagnose failures in repeat
tests.
CAUSE
In order to run tests repeatedly, our repeat test tasks override Gradle
code to allow a test class to execute more than once. Gradle's test
reporting code does not expect this. It directs the output from each
test to a log associated with the test class name, not with the specific
execution of the test class. This results in merging the outputs from
different executions of the same class.
SOLUTION
Change Gradle to distinguish separate executions of a test class, and to
log the output from each execution separately.
Components:
- New `ExecutionTrackingTestResultProcessor` class: Wraps a given test
result processor to append an …

GEODE-9924: Avoid merging repeat test logs

---

ci/scripts/execute_redis_tests.sh
geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java
geode-core/src/test/resources/org/apache/geode/management/internal/cli/commands/golden-help-offline.properties
geode-docs/reference/topics/gemfire_properties.html.md.erb
geode-docs/tools_modules/geode_for_redis.html.md.erb
geode-for-redis/README.md
geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/commands/executor/GeodeRedisServerStartupUsingGfshAcceptanceTest.java
geode-for-redis/src/performanceTest/environment-setup.sh
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/StartServerCommand.java
geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/util/HyphenFormatterTest.java

Remove the GFSH options related to geode-for-redis and update docs, examples, and tests to set such options via Java properties.

GEODE-9869: Remove geode-for-redis properties from gfsh options

---

geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/data/MemoryOverheadNativeRedisAcceptanceTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/data/AbstractMemoryOverheadIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/data/MemoryOverheadIntegrationTest.java

- Change package for AbstractMemoryOverheadIntegrationTest and child
classes from org.apache.geode.redis.internal.commands.executor.hash to
org.apache.geode.redis.internal.data

GEODE-9934: Move Redis MemoryOverheadIntegration test classes

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/DiskRegionCompactorClearOplogAfterRecoveryIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/cache/DiskRegionCompactorClearOplogAfterRecoveryJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/offheap/OffHeapRegionBase.java
geode-core/src/main/java/org/apache/geode/internal/cache/Oplog.java

Oplogs that are recovered after Region.close() will never be marked as
eligible for compaction. This is because unrecoveredRegionCount 
is not cleared from Oplog during recovery of the region. When DiskRegion with
AbstractDiskRegionInfo.unrecovered flag is recovered, then unrecoveredRegionCount
should be decreased for the Oplog (check checkForRecoverableRegion function).
Problem here is that AbstractDiskRegionInfo objects are deleted in 
Region.close(DiskRegion) and then recreated during recovery with flag 
AbstractDiskRegionInfo.unrecovered set to false. Due to this unrecoveredRegionCount
for the Oplog is not decreased during the recovery. This issue doesn't happen when
cache/server is restarted because in that case unrecoveredRegionCount will be cleared.
Solution:
During close() create …

GEODE-9881: Oplog not compacted after recovery

---

geode-junit/src/main/java/org/apache/geode/test/util/StressNewTestHelper.java

PROBLEM
JUnit 5 test classes need not be public. Indeed, IntelliJ's default
inspections discourage making JUnit 5 classes public.
`StressTestHelper` uses a `ClassGraph` to gather information about test
classes. By default, the `ClassGraph` scans only public classes. So by
default, the `ClassGraph` does not gather information about JUnit 5
classes with non-public visibility.
As a result, our stress test scripts do not run JUnit 5 tests.
SOLUTION
Call `ignoreClassVisibility()` to configure the `ClassGraph` to scan all
classes, not just public ones.
A few poorly-controlled, unsophisticated experiments (on a 2016 MacBook)
show that this increases the scan duration from 3 seconds to 3.4
seconds.

GEODE-9942: Include JUnit 5 tests in stress tests

---

build.gradle
buildSrc/build.gradle
geode-docs/tools_modules/geode_for_redis.html.md.erb
geode-for-redis/README.md
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/AbstractHitsMissesIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSInterIntegrationTest.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/RedisCommandType.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/set/SetOpExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java

SINTER command is implemented and integration tests and added to test this
command.
Co-authored-by: Bala Kaza Venkata <bkazavenkata@vmware.com>
Co-authored-by: Steve Sienkowski <ssienkowski@vmware.com>
Co-authored-by: Kristen Oduca <koduca@vmware.com>

GEODE-9829: Add SINTER command to Redis supported commands.

---

geode-core/src/main/java/org/apache/geode/internal/cache/ha/QueueSynchronizationProcessor.java
geode-core/src/test/java/org/apache/geode/internal/cache/ha/QueueSynchronizationProcessorTest.java

GEODE-9944: Handle a race when HARegionQueue is not initialized yet.

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/MessageDispatcher.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifierTest.java

Added unit test that reproduced the socket leak.
This involved some change to the product classes
to make them unit testable.
Fixed the leak by making sure socket.close is called
if the response code was not successful.
(cherry picked from commit 97601eb2cd585f844b7f02bb73ba42fcb86a7cb4)

Backport GEODE-9819 to 1.14

---

dev-tools/release/promote_rc.sh

ignore anything that doesn't start with a number, such as KEYS and kafka-connector-n.n.n

GEODE-9965: don't assume the Geode release directory contains only Geode releases

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/MessageDispatcher.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifierTest.java

Added unit test that reproduced the socket leak.
This involved some change to the product classes
to make them unit testable.
Fixed the leak by making sure socket.close is called
if the response code was not successful.
(cherry picked from commit 97601eb2cd585f844b7f02bb73ba42fcb86a7cb4)

Backport GEODE-9819 to 1.13

---

geode-dunit/src/main/java/org/apache/geode/test/junit/rules/MemberStarterRule.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/ServerStarterRule.java

Do not use ephemeral port when starting a locator/server using ClusterStartupRule

GEODE-9644: Remove use of ephemeral ports for tests

---

geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/commands/executor/server/InfoNativeRedisAcceptanceTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/AbstractInfoIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/InfoIntegrationTest.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/server/InfoExecutor.java

- Redis version is set to `5.0`
- InfoNativeRedisAcceptanceTest changed to use an actual Redis cluster
- Responses in cluster mode match native Redis

GEODE-9962: Update redis INFO command for cluster mode responses

---

CODEOWNERS

Remove kirklund as owner from several code areas.
Introduce geode-serialization/**/internal/serialization/filter/*
as a new code area with kirklund and jchen21 as owners.

GEODE-9976: Edit CODEOWNERS mappings for kirklund

---

geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/RedisCommandSupportLevel.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/RedisCommandType.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/server/COMMANDCommandExecutor.java

GEODE-9977: Remove defunct RedisCommandSupportLevel.INTERNAL type

---

geode-for-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/key/AbstractRenameIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/key/AbstractRenameNXIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSDiffIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSDiffStoreIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSInterIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSMoveIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSUnionIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSUnionStoreIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/string/AbstractMSetIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/string/AbstractMSetNXIntegrationTest.java
geode-for-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
geode-for-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/key/AbstractRenameExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/set/SMoveExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/set/SetOpExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/sortedset/ZInterStoreExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/sortedset/ZStoreExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/sortedset/ZUnionStoreExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/string/AbstractMSetExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisCrossSlotException.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/services/RegionProvider.java
geode-for-redis/src/test/java/org/apache/geode/redis/internal/services/RegionProviderTest.java

- Move duplicated logic for determining if Keys are in different slots
from various Executors to RegionProvider
- Removed manual checks for if the key is local, as this is performed
as part of locking the primary bucket
- Created RedisCrossSlotException class
- Added unit tests for new method in RegionProvider
- Refactor SetOpExecutor to also lock the destination key for *STORE
commands
- Add missing test cases for cross-slot errors
- Correct some tests for cross-slot behaviour that were inadvertently
testing the Jedis client's response rather than the Geode for Redis
server
- Changed name format for constants in AbstractSMoveIntegrationTest
- [N/A] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF …

GEODE-9922: Move Redis cross-slot checking to RegionProvider

---

geode-book/master_middleman/source/subnavs/geode-subnav.erb
geode-docs/managing/troubleshooting/chapter_overview.html.md.erb
geode-docs/managing/troubleshooting/log_messages_and_solutions.html.md.erb
geode-docs/tools_modules/geode_for_redis.html.md

The GemFire support team (who are also Geode community members) have compiled a troubleshooting guide that maps log messages to suggested solutions.
They have contributed this to the Geode user guide. I worked with them to format it and to minimize proprietary references.
Big chapter, great material!

GEODE-9923: Add log message troubleshooting info from support team

---

geode-docs/managing/monitor_tune/socket_communication_have_enough_sockets.html.md.erb

Reverts apache/geode#7294
Format & grammar looked good, so I merged.
Turns out the documented behavior needs more validation first, so taking a step back.

Revert "GEODE-9973: Correct docs regarding P2P socket timeout behaviour"

---

geode-wan/src/main/java/org/apache/geode/management/internal/cli/functions/WanCopyRegionFunctionDelegate.java
geode-wan/src/test/java/org/apache/geode/management/internal/cli/functions/WanCopyRegionFunctionDelegateTest.java

GEODE-9859: Do not copy entry if it is a destroyed entry

---

geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/commands/executor/GeodeRedisServerStartupUsingGfshAcceptanceTest.java

GEODE-9995: Use ephemeral ports to avoid flaky port in use issues

---

geode-for-redis/src/test/java/org/apache/geode/redis/internal/data/collections/SizeableBytes2ObjectOpenCustomHashMapWithCursorQuickCheckTest.java

- The test scanWithNoModificationsDoesNotReturnDuplicates in
SizeableBytes2ObjectOpenCustomHashMapWithCursorQuickCheckTest should
only perform a second scan if the first one was not a complete scan of
the map

GEODE-10011: Do not perform second scan if first scanned entire map

---

geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/key/RenameDUnitTest.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/key/AbstractRenameExecutor.java

Most of the work here was on getting a DUnit test to fail with the old version of the code. The test doesn't fail every time when run with the old code, but it does fail sometimes. With the new code, i.e. the fix, I haven't seen the test fail at all.

GEODE-9994 Make Redis RENAME atomic

---

geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/hash/HExistsDUnitTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/hash/HGetDUnitTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/hash/HKeysDUnitTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/hash/HMgetDUnitTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/hash/HMsetDUnitTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/hash/HsetDUnitTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/key/ExpireDUnitTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/pubsub/PubSubConcurrentDUnitTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/pubsub/PubSubDUnitTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/set/SaddDUnitTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/set/SremDUnitTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/hash/AbstractHashesIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/set/AbstractSetsIntegrationTest.java

Remove redundant server.stop() calls and unnecessary "canStoreBinaryData" tests from Geode for Redis tests.

GEODE-10013: Remove unused code in Geode for Redis tests

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/PRTransactionDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/internal/cache/execute/PRColocationDistributedTestHelper.java
geode-dunit/src/main/java/org/apache/geode/internal/cache/execute/data/Customer.java
geode-dunit/src/main/java/org/apache/geode/internal/cache/execute/data/Order.java
geode-dunit/src/main/java/org/apache/geode/internal/cache/execute/data/Shipment.java

GEODE-9710: Cleanup PRColocationDUnitTestHelper

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-core/build.gradle
geode-core/src/integrationTest/java/org/apache/geode/management/internal/ManagementAgentIntegrationTest.java
geode-core/src/main/java/org/apache/geode/management/internal/ManagementAgent.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt
geode-core/src/test/java/org/apache/geode/management/internal/ManagementAgentTest.java
geode-gfsh/build.gradle
geode-gfsh/src/acceptanceTest/java/org/apache/geode/gfsh/GfshWithSslAcceptanceTest.java
geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/shell/JmxOperationInvokerIntegrationTest.java
geode-junit/src/main/java/org/apache/geode/cache/ssl/CertStores.java

When SSL is enabled we set the java.rmi.server.hostname System Property
to force creation of endpoints bound to that address rather than the
default, which is the local IP address. When RMI clients make
connections for these endpoints they will use the correct hostname,
which should match the hostname in the SSL certificate.
(cherry picked from commit 1da903901bf4bb4d339d83a244051eaf58d8b690)

GEODE-10015: Set java.rmi.server.hostname when SSL enabled. (#7337)

---

geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/string/AbstractMSetExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/string/MSetExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/string/MSetNXExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/string/SetOptions.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisString.java

GEODE-10018: Remove redundant TX flag from SetOptions

---

geode-for-redis/build.gradle
geode-for-redis/src/commonTest/java/org/apache/geode/redis/ClusterNode.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/OutOfMemoryDUnitTest.java

- Start servers using gfsh to allow setting
XX:CMSInitiatingOccupancyFraction and other VM memory/GC settings
- Add test coverage for commands being allowed again after recovering
from critical
- Add test that non-critical member does not allow write operations if
there is a critical member in the cluster

GEODE-9845: Refactor OutOfMemoryDUnitTest

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ClientServerTransactionDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/RemoteTransactionDUnitTest.java

Clean up RemoteTransactionDUnitTest for the next time this failure
occurs.
While trying to reproduce the failure described by GEODE-9929 I did some
clean up so I would be able to get more useful information out of the
failures. I cleaned up a lot of warnings, mostly using IntelliJ's tools.
I have determined the test failure to not be a 1.15 release blocker so I
will not be pursuing the issue further, but I hope this cleanup will
help the next person to work on this ticket.

GEODE-10021: Clean up RemoteTransactionDUnitTest

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxyTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxy.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientHealthMonitor.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionTest.java

handleTermination method is setting the clientUserAuth null even when we are not unregister client.
* make cleanUserAuths synchronized to avoid NPE
* This also pass down client termination reason when we clean up client threads

GEODE-10042: do not make ClientUserAuths null when we are not unregister client yet.

---

geode-apis-compatible-with-redis/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeRedisSerializablesIntegrationTest.java
geode-connectors/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeConnectorsSerializablesIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeCoreSerializablesIntegrationTest.java
geode-cq/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeCQSerializablesIntegrationTest.java
geode-dunit/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeDUnitSerializablesIntegrationTest.java
geode-gfsh/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeGfshSerializablesIntegrationTest.java
geode-junit/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeJUnitSerializablesIntegrationTest.java
geode-junit/src/main/java/org/apache/geode/codeAnalysis/AnalyzeDataSerializablesTestBase.java
geode-junit/src/main/java/org/apache/geode/codeAnalysis/AnalyzeDataSerializablesWithClassAnalysisRuleTestBase.java
geode-junit/src/main/java/org/apache/geode/codeAnalysis/AnalyzeSerializablesTestBase.java
geode-junit/src/main/java/org/apache/geode/codeAnalysis/AnalyzeSerializablesWithClassAnalysisRuleTestBase.java
geode-junit/src/main/java/org/apache/geode/codeAnalysis/SanctionedSerializablesServiceIntegrationTestBase.java
geode-junit/src/main/java/org/apache/geode/test/junit/rules/ClassAnalysisRule.java
geode-lucene/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeLuceneSerializablesIntegrationTest.java
geode-management/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeManagementSerializablesIntegrationTest.java
geode-membership/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeMembershipSerializablesIntegrationTest.java
geode-memcached/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeMemcachedSerializablesIntegrationTest.java
geode-pulse/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzePulseSerializablesIntegrationTest.java
geode-serialization/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeSerializationSerializablesIntegrationTest.java
geode-web-api/src/integrationTest/java/org/apache/geode/codeAnalysis/AnalyzeWebApiSerializablesIntegrationTest.java

Adds support for customizing source set paths of ClassAnalysisRule.
PROBLEM
Modules external to Geode must be structured the same as Geode
source code in order to use ClassAnalysisRule and the
Analyze*Serializables tests. This is necessary to better facilitate
pluggability of modules that need to provide sanctioned serializable
lists.
SOLUTION
Add source set path customization to ClassAnalysisRule, introduce
a new layer of Analyze*Serializables test base classes that can be
directly extended in order to customize source set paths in
ClassAnalysisRule. Also includes improvements to some iterating
of classes during analysis.
[prereq for backport of GEODE-9980 and GEODE-9758]
(cherry picked from commit 5d1e91932dff296632916a6ceccfb36039357acd)

[1.14] GEODE-9817: Enable customized source set paths for ClassAnalysisRule

---

geode-docs/tools_modules/geode_for_redis.html.md.erb

- Swap usage of active and passive in descriptions of expiration to
match their usage in open source Redis documentation

GEODE-10057: Correct geode-for-redis docs

---

geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/statistics/GeodeRedisStatsIntegrationTest.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/statistics/GeodeRedisStats.java

- Geode for Redis statistics are broken up by category. For example
stats will appear as `GeodeForRedisStats:STRING` or
`GeodeForRedisStats:HASH`. Each type will then only contain stats
relevant to the commands associated with that category.

GEODE-10034: Organize Geode For Redis Stats By Category

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/DiskInitFileJUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/DiskInitFile.java
geode-core/src/main/java/org/apache/geode/internal/cache/PRHARedundancyProvider.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/CreateBucketMessage.java
geode-core/src/test/java/org/apache/geode/internal/cache/PRHARedundancyProviderTest.java

* GEODE-9990: turn DiskAccessException into CacheClosedException
- when DiskInitFile is in closed state and DiskStoreImpl is closed or
closing
- catch DiskAccessException in PRHARedundancyProvider and turn into
CacheClosedException if cache closing is in progress
- change CreateBucketMessage to handle DiskAccessException as cause of
ReplyException
(cherry picked from commit a98197b5d0a3a2547e0581e475dcabaa82e6e92f)

GEODE-9990: turn DiskAccessException into CacheClosedException (#7334)

---

geode-wan/src/main/java/org/apache/geode/management/internal/cli/functions/WanCopyRegionFunctionDelegate.java

The `wan-copy region` command, when run on a partitioned region using a parallel gateway sender, retrieves the entries from the region and puts them in a Set for further processing. In order to add them to the Set, the `hashCode` method of the entry (`NonTXEntry`) in invoked. If any of those entries was destroyed, then the EntryDestroyedException will be thrown.
In order to avoid this exception, the `wan-copy region` command will not put the entries in a Set for further processing as it is not needed.

GEODE-10008: Avoid possible EntryDestroyed exception in wan copy-region command

---

ci/scripts/archive_results.sh

Before, this was always generated in geode-assembly.
Now on some branches it is in geode-server-all.
Solution: wildcard the top-level module name to always find it.

GEODE-10072: Restore japicmp report

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/QueueManagerImpl.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/QueueManagerImplTest.java

*  When adding QueueConnection to connectionList, also checks if the connection
has been destroyed by another thread to prevent a bad connection is being
added to the list.
*  Schedule RedundancySatisfierTask after remove connection so that bad connection
can be detected.
*  During recoveryPrimary in RedundancySatisfierTask, need to check if primary
connection is destroyed. If so, connection from backups will be promoted to
primary.

GEODE-10063: Correctly set primary queue connection. 

---

geode-for-redis/src/commonTest/java/org/apache/geode/redis/internal/proxy/MovedResponseHandler.java
geode-for-redis/src/commonTest/java/org/apache/geode/redis/internal/proxy/RedisProxyInboundHandler.java
geode-for-redis/src/commonTest/java/org/apache/geode/redis/internal/proxy/RedisProxyOutboundHandler.java

- When a MOVED response is received, the already queued processor needs
to be discarded otherwise subsequent requests may possibly be
corrupted.

GEODE-10083: Fix RedisProxy to correctly process MOVED responses

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Size.java

* Removed StringBuilder
* Using local string

GEODE-10086: Removed StringBuilder variables

---

geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/commands/executor/server/InfoStatsNativeRedisAcceptanceTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/AbstractInfoStatsIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/InfoStatsIntegrationTest.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/statistics/RedisStats.java

- Rather than a value that updates once per second, instantaneous
operations per second and instantaneous kilobytes read per second now
return a rolling average of those stats updated 16 times per second
- Rename AbstractRedisInfoStatsIntegrationTest to match child classes
- Rather than measuring instantaneous per second stats after
operations have finished, sample them while operations are ongoing and
calculate the expected value based on the number of operations
performed in the one second prior to sampling.

GEODE-10010: Sample Redis ops per second during operations in test

---

buildSrc/src/main/java/org/apache/geode/gradle/testing/isolation/WorkingDirectoryIsolator.java
buildSrc/src/test/java/org/apache/geode/gradle/testing/isolation/WorkingDirectoryIsolatorTest.java
gradle/code-analysis.gradle

We haven't been maintaining this gradle build support, but it is useful to be
able to get code coverage from distributed test runs, eg.
./gradlew geode-core:distributedTest -PcodeCoverage \
--tests XXX geode-core:jacocoDistributedTestReport

GEODE-10075 Fix jacoco code coverage reports

---

geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/commands/executor/server/InfoStatsNativeRedisAcceptanceTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/AbstractRedisInfoStatsIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/InfoStatsIntegrationTest.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/statistics/RedisStats.java

This reverts commit ea20f2501a620c3b7baa3c621d2f4d21af3bdf58.

Revert "GEODE-10010: Improve accuracy of per-second Redis stats (#7358)"

---

geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionTest.java

* IndexUtils.getIndexManager can return null if bucket region is
destroyed due to cache is closing. Make sure CancelException is
thrown in this case.

GEODE-10094: Fix NPE when populating index in partitioned region.

---

geode-wan/src/main/java/org/apache/geode/cache/wan/internal/client/locator/LocatorHelper.java
geode-wan/src/main/java/org/apache/geode/cache/wan/internal/client/locator/LocatorMembershipListenerImpl.java

GEODE-6588: Cleanup static analyzer warnings.

---

geode-common/build.gradle
geode-common/src/main/java/org/apache/geode/internal/lang/utils/function/Checked.java
geode-common/src/test/java/org/apache/geode/internal/lang/utils/function/CheckedTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache/client/internal/ClientServerHostNameVerificationDistributedTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache/client/internal/CustomSSLProviderDistributedTest.java
geode-core/src/distributedTest/java/org/apache/geode/distributed/LocatorDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImplIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TCPClientSSLIntegrationTest.java
geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/tcpserver/TCPServerSSLInegrationTest.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImpl.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/AutoConnectionSourceImplTest.java
geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/GfshHostNameVerificationDistributedTest.java
geode-serialization/src/main/java/org/apache/geode/internal/serialization/VersionedDataOutputStream.java
geode-tcp-server/build.gradle
geode-tcp-server/src/main/java/org/apache/geode/distributed/internal/tcpserver/ShutdownResponse.java
geode-tcp-server/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpClient.java
geode-tcp-server/src/test/java/org/apache/geode/distributed/internal/tcpserver/TcpClientTest.java
geode-tcp-server/src/test/java/org/apache/geode/distributed/internal/tcpserver/TcpServerDependenciesTest.java
geode-tcp-server/src/test/java/org/apache/geode/distributed/internal/tcpserver/TcpServerTest.java
geode-tcp-server/src/test/resources/expected-pom.xml
geode-tcp-server/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
geode-tcp-server/src/upgradeTest/java/org/apache/geode/distributed/internal/tcpserver/TcpServerProductVersionUpgradeTest.java
geode-web/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ConnectCommandWithSSLMultiKeyTest.java
geode-web/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ConnectCommandWithSSLTest.java

* IOExceptions thrown by the SSL layer will now bubble up to the
appropriate handlers and cause retries on other locators.
* Refactored for better testing.
* Adds checked exception function utils.

GEODE-10066: Don't wrap IOExceptions in IllegalStateExceptions.

---

CODEWATCHERS
COMMITWATCHERS

Previously, opt-in and unsubscribe required a dev list email,
and this led to complaints.
This self-serve mechanism achieves the same goal of a public
record of opt-in requests, without adding noise to the dev list.

GEODE-10111: Introduce COMMITWATCHERS

---

geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionTest.java

* When creating index, throw CacheClosedException instead of adding it
to exceptionsMap which will eventually converted to
MultiIndexCreationException, with InternalGemFireException thrown
to the user.

GEODE-10110: Do not wrap CacheClosedException unexpectedly.

---

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/rest/RebalanceManagementDunitTest.java
geode-core/src/main/java/org/apache/geode/management/internal/operation/RebalanceOperationPerformer.java
geode-core/src/test/java/org/apache/geode/management/internal/operation/RebalanceOperationPerformerTest.java
geode-core/src/test/java/org/apache/geode/management/internal/operation/RestoreRedundancyPerformerTest.java
geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/RebalanceSubregionDistributedTest.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/RebalanceCommand.java

This commit modifies RebalanceOperationPerformer getMemberRegionList
to invoke listAllRegionPaths instead of listNames.

GEODE-10103: Retrieve full region path names

---

geode-for-redis/src/commonTest/java/org/apache/geode/test/dunit/rules/RedisClusterStartupRule.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/string/StringsDUnitTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/data/DeltaDUnitTest.java
geode-for-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/AbstractRedisData.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisString.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/AddByteArrayDoublePairs.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/AddByteArrayPairs.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/AddByteArrays.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/AppendByteArray.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/DeltaInfo.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/DeltaType.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/RemoveByteArrays.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/RemoveElementsByIndex.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/ReplaceByteArrayAtOffset.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/ReplaceByteArrayDoublePairs.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/ReplaceByteArrays.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/ReplaceByteAtOffset.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/SetByteArray.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/SetByteArrayAndTimestamp.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/SetTimestamp.java
geode-for-redis/src/main/resources/org/apache/geode/redis/internal/services/sanctioned-geode-for-redis-serializables.txt

This change is necessary because GII can retrieve a value that is
currently being updated. This can result in corruption if a Delta change
is subsequently applied.
- Convert DeltaInfo to an abstract class and add a version field
- DeltaTypes indicate whether the type is versioned
- Versioning needs to be added to any operations where the application
of a Delta is not idempotent. In such cases, the version and data
change MUST happen together under synchronization.
- Take care that the version is not inadvertently updated as a result of
applying a delta change.
- Update the String APPEND command to use these changes.
- Other commands will be updated separately.

GEODE-10108: Add version field to AbstractRedisData and deltas

---

geode-docs/developing/storing_data_on_disk/storing_data_on_disk.html.md.erb

* Added section in the doc about lru max memory being over written if
local max memory is set.
* Also mentioned that these two settings are local and not cluster wide

GEODE-10117: Added section in docs about memory

---

geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/commands/executor/server/InfoStatsNativeRedisAcceptanceTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/AbstractInfoStatsIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/InfoStatsIntegrationTest.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/statistics/RedisStats.java

Code changes:
- Rather than a value that updates once per second, instantaneous
operations per second and instantaneous kilobytes read per second now
return a rolling average of those stats updated 16 times per second
- Change instantaneous operations per second type from double to int,
since it's always a whole number
- Introduce RollingAverageStat nested class in RedisStats to handle
calculating the rolling average value of a given stat
Test changes:
- Rename AbstractRedisInfoStatsIntegrationTest to match child classes
- Rather than measuring instantaneous per second stats after
operations have finished, sample them while operations are ongoing
- Assert only that the stats have updated, not that they are close to a
calculated expected value, as this proved too inconsistent and very …

GEODE-10010: Refine per-second Redis stats

---

geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java
geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb
geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/GfshParserAutoCompletionIntegrationTest.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeRegionCommand.java
geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandTest.java
geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeRegionJUnitTest.java
geode-wan/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandDUnitTest.java

* create region now includes a new field called
scope to set the scope
* This field is only valid for Replicated Regions.
* describe region for replicated regions will now
display the scope too.

GEODE-8140: Set scope field in gfsh.

---

settings.gradle

Replace 1.13.7 with 1.13.8 in old versions on develop
to enable rolling upgrade tests from 1.13.8
The serialization version has not changed between 1.13.7 and 1.13.8,
so there should be no need to keep both

GEODE-10100: Replace 1.13.7 with 1.13.8 as old version

---

geode-wan/src/main/java/org/apache/geode/cache/wan/internal/client/locator/LocatorHelper.java

Reverts 516bdc9322e1068c14e901879a7fb4afeac9b181
These changes inadvertently changed the hostname sent to the remote
locators.

GEODE-10127: Reverts changes from GEODE-8955.

---

ci/pipelines/shared/jinja.variables.yml
geode-book/config.yml
geode-book/redirects.rb
geode-serialization/src/main/java/org/apache/geode/internal/serialization/KnownVersion.java
gradle.properties

per dev list discussion on Mar 16, we will roll back the support/1.15 branch cut and return develop to being 1.15 until we are in a better place to try cutting the branch again

Revert "roll develop to 1.16.0 now that support/1.15 has been created"

---

buildSrc/src/main/resources/japicmp_exceptions.json
geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/index/IndexStatisticsJUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/cache/query/partitioned/PRIndexStatisticsJUnitTest.java
geode-core/src/main/java/org/apache/geode/cache/query/IndexStatistics.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/AbstractIndex.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/AbstractMapIndex.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/CompactRangeIndex.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/HashIndex.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/IndexStats.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/PartitionedIndex.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/RangeIndex.java

Replace IndexStatistics int statistic methods.

GEODE-9787: Cascading deprecations for Statistics int methods.

---

gradle/test.gradle

PROBLEM
JDK 17 throws exceptions when product and test code attempts to access
elements in modules that do not make those elements accessible.
SOLUTION
Open and export the required packages when starting a test JVM.

GEODE-10128: Open/export packages for JDK 17

---

geode-cq/src/main/java/org/apache/geode/cache/query/cq/internal/ServerCQResultsCacheReplicateRegionImpl.java
geode-cq/src/test/java/org/apache/geode/cache/query/cq/internal/ServerCQResultsCacheReplicateRegionImplTest.java

* containsKey in HashMap can return false even though the key exists in
the map possibly due to map resizes as other concurrent operations
occur. Now it will be checked under synchronized lock.

GEODE-10130: Check containsKey under synchronization.

---

ci/images/google-geode-builder/scripts/setup.sh
ci/images/google-windows-geode-builder/packer.json
ci/pipelines/geode-build/jinja.template.yml
ci/pipelines/pull-request/jinja.template.yml
ci/pipelines/shared/jinja.variables.yml

Adds JDK17 to Windows and Linux images.
Adds JDK17 Windows and Linux jobs to main pipeline, but not as gating jobs _for now_, so they can be paused if needed.
Note: adding the jdk17 label to a PR only adds linux, not windows jdk17 jobs to the PR (consistent with how jdk8 label works)

GEODE-10137: allow PRs to opt-in to JDK17 via jdk17 label

---

geode-wan/src/main/java/org/apache/geode/management/internal/cli/functions/WanCopyRegionFunctionDelegate.java

When the region to copy is partitioned and
the gateway sender is parallel, the gateway
sender of each server will read and then send only the primary
copies in the local buckets of that server.
Deserialization of the entries will also avoided.

GEODE-10067: Optimize wan-copy region command

---

ci/pipelines/shared/jinja.variables.yml
dev-tools/release/commit_rc.sh
dev-tools/release/deploy_rc_pipeline.sh
dev-tools/release/license_review.sh
dev-tools/release/promote_rc.sh

* increased RC pipeline file size check limits as 1.15 is a little bigger than 1.14
* modified RC pipeline native builds to obtain a required newer cmake than what is distributed by Ubuntu

GEODE-10089: update release scripts to handle 1.15

---

ci/docker/Dockerfile
ci/images/google-geode-builder/scripts/setup.sh
ci/pipelines/mass-test-run/jinja.template.yml
ci/pipelines/meta/deploy_meta.sh
ci/pipelines/pull-request/deploy_pr_pipeline.sh
dev-tools/docker/base/Dockerfile
dev-tools/release/commit_rc.sh
dev-tools/release/deploy_rc_pipeline.sh
dev-tools/release/license_review.sh
dev-tools/release/promote_rc.sh
geode-assembly/src/src/dist/gradlew
geode-management/src/test/script/update-management-wiki.sh

Without -f, curl will succeed (exitcode 0) even if the response is a 404 error, etc.
This is almost never the desired behavior, especially in scripts that rely on `set -e` to fail fast if there is a problem
particular dangerous is `curl http://someurl > file.tgz` ... the only clue that the file has an error page inside instead of a valid tar archive might be a subsequent failure to untar it ... or it might go unnoticed and upload a junk release artifact (not that this happened or anything, just hypothetically ;)

GEODE-10139: add -f to curl

---

geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/ServerContainer.java
geode-core/src/distributedTest/java/org/apache/geode/distributed/ServerLauncherDUnitTest.java
geode-dunit/src/main/java/org/apache/geode/test/dunit/internal/ProcessManager.java
geode-dunit/src/main/java/org/apache/geode/test/junit/rules/GfshCommandRule.java
geode-junit/src/main/java/org/apache/geode/test/process/JavaModuleHelper.java
geode-junit/src/test/java/org/apache/geode/test/process/JavaModuleHelperTest.java
gradle/test.gradle

Several tests and test framework classes launch child JVMs to run Geode
product and test code. Those tests and classes now forward the test
JVM's `--add-opens` and `--add-exports` options to the child JVMs.

GEODE-10129: Forward opens/exports to child JVMs

---

ci/images/alpine-tools/Dockerfile
ci/pipelines/images/jinja.template.yml

Also add concourse resources to track our base-image versions to better
track which dependencies may have caused the build issue. Still only
triggering on the core base image, and our Dockerfile.

GEODE-10145: Organize Dockerfile to work around alpine compat issues

---

geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandDUnitTest.java
geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreateRegionSecurityDUnitTest.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java

Sometimes the "create region" command executes successfully during
servers restart even though region is already available in the cluster
configuration. When this happens, cluster configuration contains a
duplicated region, and servers throw
"org.apache.geode.cache.RegionExistsException" at startup.
CreateRegionCommand checks whether there is already an existing
region using the DistributedRegionMXBean service. This service is
unreliable during restarts, as it takes some time for the locator to
accumulate region information.
In addition to checks done against the DistributedRegionMXBean
information, this solution introduces the same checks against cluster
configuration (if used) stored in locators. This way, the "create region"
command is rejected immediately by the locator instead of the …

GEODE-10123: Improve create region checks

---

ci/pipelines/shared/jinja.variables.yml
settings.gradle

Replace 1.14.3 with 1.14.4 in old versions and set as Benchmarks baseline on develop
to enable rolling upgrade tests from 1.14.4
The serialization version has not changed between 1.14.3 and 1.14.4,
so there should be no need to keep both

GEODE-10101: Replace 1.14.3 with 1.14.4 as old version

---

geode-core/src/distributedTest/java/org/apache/geode/security/AuthExpirationDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxy.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/MessageDispatcher.java
geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/MessageDispatcherTest.java
geode-junit/src/main/java/org/apache/geode/security/ExpirableSecurityManager.java
geode-junit/src/main/resources/org/apache/geode/test/junit/internal/sanctioned-geode-junit-serializables.txt

This checkin has caused some server connectivity exceptions on. the client. Will investigate further before committing again.

Revert "GEODE-10097: Avoid Thread.sleep for reauthentication in MessageDispatcher (#7416)"

---

ci/pipelines/shared/jinja.variables.yml
dev-tools/release/promote_rc.sh

radish benchmarks use a custom branch/tag
on a new minor, the release scripts should reset that to the new minor release
however, the scripts are incorrectly resetting it on every patch, oops
even resetting it on a new minor _could_ be the wrong thing, if the custom baseline on develop is already newer than the point where the release branch was cut, but hopefully that can be caught in PR review if ever a problem; I feel there is bigger concern of forgetting to reset the custom branch when a new minor happens, so best for the script to still do it.

GEODE-10149: don't roll radish baseline except on new minor

---

geode-docs/tools_modules/gfsh/command-pages/alter.html.md.erb
geode-docs/tools_modules/gfsh/command-pages/change.html.md.erb

Release blocker reported by @dkhopade. Two fixes:
- The --log-level parameter was incorrectly shown as --loglevel. (Note: the `change loglevel` command itself is not hyphenated, but its `--log-level` option is.
- The `alter runtime` command is a cluster config command, so affects new and restarted servers, but not locators.
- The `change loglevel` command is not a cluster config command, so it applies to both servers and locators, but only those specified in the command line, not subsequently-added members.

GEODE-10150: alter runtime command and change loglevel command docs

---

ci/images/alpine-tools/Dockerfile

they were accidentally removed by prior PR for GEODE-10145

GEODE-10145: java tools such as javac should be on PATH

---

geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/ReplaceByteArrayAtOffset.java
geode-for-redis/src/test/java/org/apache/geode/redis/internal/data/DeltaClassesJUnitTest.java

- This enum should have been removed in the original versioning code.
It's presence now causes a corruption in the delta deserialization.

GEODE-10108: Remove extra enum written in ReplaceByteArrayAtOffset

---

geode-serialization/src/main/java/org/apache/geode/internal/serialization/filter/SanctionedSerializablesFilterPattern.java

Jar deployment serializes proxies. JDK 17 creates proxy classes in
dynamically created packages with names like `jdk.proxy2` and
`jdk.proxy3`.

GEODE-10134: Add JDK 17 proxy classes to serialization accept list

---

geode-docs/tools_modules/geode_for_redis.html.md.erb
geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/commands/executor/list/RPopLPushNativeRedisAcceptanceTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/list/RPopLPushDUnitTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/list/AbstractRPopLPushIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/list/RPopLPushIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/server/AbstractHitsMissesIntegrationTest.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/Command.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/RedisCommandType.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/key/AbstractRenameExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/key/DumpExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/key/ExistsExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/list/RPopLPushExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/set/SetOpExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisList.java

- Implement RPOPLPUSH command and add associated tests
- Alphabetize command-related methods in RedisList
- Change Command.getProcessedCommandKeys() to not convert the command
name into a RedisKey, because there's no situation in which we'd want
to do that
- Add ignored test for transactional behaviour, blocked by GEODE-10121

GEODE-9983: Implement RPOPLPUSH command

---

geode-docs/managing/troubleshooting/log_messages_and_solutions.html.md.erb

Removed a doubled double-quote.

user guide: typo repair in troubleshooting section

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/gfsh_dependency_classpath.txt
geode-server-all/src/integrationTest/resources/dependency_classpath.txt

shelf life of releases and increases security and reliability; doing so
regularly makes any hiccups easier to identify.
This bump of jackson-databind from 2.13.2 to micropatch 2.13.2.1 is
a little clunkly and once 2.13.3 or 2.14.0 is available, this should
first be reverted...

GEODE-10179: Bump jackson-databind to 2.13.2.1

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt
geode-core/src/integrationTest/java/org/apache/geode/management/internal/beans/DistributedSystemMBeanIntegrationTest.java

to fix https://github.com/FasterXML/jackson-databind/issues/2816

[1.13] GEODE-10179: Bump jackson-databind from 2.10.5.1 to 2.12.6.1

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt
geode-core/src/integrationTest/java/org/apache/geode/management/internal/beans/DistributedSystemMBeanIntegrationTest.java

to fix https://github.com/FasterXML/jackson-databind/issues/2816

[1.12] GEODE-10179: Bump jackson-databind from 2.10.5.1 to 2.12.6.1

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/commands/RebalanceCommandAcceptanceTest.java
geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/NestedQueryClassCastExceptionFailureDistributedTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/InternalCacheForClientAccessDistributedTest.java
geode-dunit/src/main/resources/org/apache/geode/test/dunit/internal/sanctioned-geode-dunit-serializables.txt

- Rename InternalCacheForClientAccessDUnitTest ->
InternalCacheForClientAccessDistributedTest
- Move InternalCacheForClientAccessDistributedTest to geode-core module
- Remove spurious <tearDown> parameterization from
InternalCacheForClientAccessDistributedTest
- Rename NestedQueryClassCastExceptionFailureDUnitTest ->
NestedQueryClassCastExceptionFailureDistributedTest
- Move NestedQueryClassCastExceptionFailureDistributedTest to
geode-core module, change package to cache.query.dunit
- Rename RebalanceCommandDistributesTest to
RelanaceCommandAcceptanceTest
- Move RebalanceCommandAcceptanceTest to geode-assembly module
acceptanceTest directory as it requires that GEODE_HOME is set
- Remove files from sanctioned-geode-dunit-serializables.txt

GEODE-10166: Move tests to correct directory

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/ConnectionFactoryImpl.java
geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java

PROBLEM
On JDK 17, `SslSocket.startHandshake()` can throw
`SSLHandshakeException` in circumstances where JDK 8 and 11 would throw
`SocketException`.
`SocketCreator.configureClientSSLSocket()` catches this exception, logs
it as fatal, and rethrows it.
`ConnectionFactoryImpl.createClientToServerConnection()` then catches it
and logs it as a warning.
This results in lots of warn/fatal log entries for relatively benign
occurrences that, on JDK 8 and 11, would result in debug entries.
Also, `WANSSLDUnitTest.testSenderSSLReceiverNoSSL()` fails when it sees these
unrecognized entries in the log.
SOLUTION
Change `SocketCreator` and `ConnectionFactoryImpl` to recognize when an
`SSLHandshapeException` describes the kind of problem that would have
thrown a `SocketException` on JDK8/11. If so, treat …

GEODE-10119: Handle SSLHandshakeException on JDK17

---

geode-core/src/main/java/org/apache/geode/internal/cache/FilterProfile.java

GEODE-10182: Remove no longer needed null check.

---

geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/key/AbstractRenameIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/string/AbstractMSetIntegrationTest.java

- Reduce the iterations and/or elements used by these tests reducing the
runtimes significantly (down to seconds instead of minutes).

GEODE-10190: Improve runtime of MSetIntegrationTest and RenameIntegrationTest

---

buildSrc/src/main/resources/japicmp_exceptions.json
geode-core/src/distributedTest/java/org/apache/geode/management/MemberMXBeanAttributesDistributedTest.java
geode-core/src/main/java/org/apache/geode/internal/offheap/FreeListManager.java
geode-core/src/main/java/org/apache/geode/internal/offheap/MemoryAllocatorImpl.java
geode-core/src/main/java/org/apache/geode/internal/offheap/OffHeapMemoryStats.java
geode-core/src/main/java/org/apache/geode/internal/offheap/OffHeapStorage.java
geode-core/src/main/java/org/apache/geode/internal/offheap/OffHeapStoredObjectAddressStack.java
geode-core/src/main/java/org/apache/geode/management/MemberMXBean.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/MemberMBean.java
geode-core/src/main/java/org/apache/geode/management/internal/beans/MemberMBeanBridge.java
geode-core/src/test/java/org/apache/geode/internal/offheap/OffHeapStorageNonRuntimeStatsJUnitTest.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/ShowMetricsCommand.java
geode-junit/src/main/java/org/apache/geode/internal/offheap/NullOffHeapMemoryStats.java

As per RFC https://cwiki.apache.org/confluence/display/GEODE/Enhance+Off-heap+memory+fragmentation+visibility
Geode's off-heap fragmentation visibility has been improved
by adding a new stat: "freedChunks" as well as
by the periodic update of the "largestFragment" stat.
The new one stat will also be periodically updated
with a default frequency of one hour that can be changed by the
update-off-heap-stats-frequency-ms system property.
Besides, the new stat, the "fragments" and the "largestFragment" stats
will be published via JMX.

GEODE-10087: Enhance off-heap fragmentation visibility.

---

geode-core/src/main/java/org/apache/geode/cache/execute/Function.java
geode-core/src/test/java/org/apache/geode/cache/execute/FunctionTest.java

PROBLEM
The default implementation of `Function.getId()` returns the canonical
name of the function's class. But:
- On all JDKs, an anonymous class has no canonical name.
- Starting with JDK 15, a hidden class (such as the class of a lambda
expression) has no canonical name.
Given that `Function` is annotated as a functional interface, it is
problematic that its default `getId()` returns `null` for functions
created as anonymous classes and (on JDK 15+) via lambda expressions.
SOLUTION
Change `Function.getId()` to return its class's name if the class has no
canonical name.

GEODE-10136: Make Function.getId() handle null canonical name

---

geode-core/src/main/java/org/apache/geode/internal/cache/DistributedRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/DistributedRegionTest.java

* In geode, version tags are not sent to receiver during GII. When an
operation is retried on the receiver, a valid tag is needed so that the
operation can be distributed to other peers. Valid version tage will
be searched in the cluster and set in the event to make sure the
operation is distributed.

GEODE-10162: Try to find and set version tag if needed

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/gfsh_dependency_classpath.txt
geode-server-all/src/integrationTest/resources/dependency_classpath.txt

This just eliminates the need to override the jackson-bom version, which is a little tidier.  No actual new fixes.

GEODE‑10179: Bump jackson-databind from 2.13.2.1 to 2.13.2.2

---

geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/list/AbstractBLPopIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/eventing/EventDistributorTest.java
geode-for-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/key/AbstractRenameExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/key/RestoreExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/AbstractRedisData.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisData.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisList.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisData.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisList.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/eventing/BlockingCommandListener.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/eventing/EventDistributor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/eventing/EventListener.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/eventing/NotificationEvent.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/netty/ExecutionHandlerContext.java

- Both of these commands have the ability to create events to satisfy
BLPOP.
- Introduce a NotificationEvent enum which is passed to fireEvent.
- Previously the RedisCommandType was being passed, but this does not
work for RENAME which creates RENAME_FROM and RENAME_TO events. In the
future, other commands will need to create multiple events too.

GEODE-10191: Radish RENAME and RESTORE create notification events

---

geode-core/src/main/java/org/apache/geode/internal/cache/map/RegionMapPut.java
geode-core/src/test/java/org/apache/geode/internal/cache/map/RegionMapPutTest.java

* Allow a retried putIfAbsend operation to proceed futher so that the
operation can be distributed to other peers in basicPutPart2 and
dispatch the event to their clients, even if the event has set the
valid version tag already.

GEODE-10199: Make retried putIfAbsent work

---

geode-book/Gemfile.lock

https://issues.apache.org/jira/browse/GEODE-9568
The Geode User Guide build script uses this Gemfile.lock file when it runs Docker, but the "bookbindery" gem v10.1.17 was pulled from RubyGems. This results in the script failing.
Updating the version of the gem to 1.10.18 resolves this issue.

GEODE-9568: Update Bookbindery Ruby gem

---

geode-docs/tools_modules/geode_for_redis.html.md.erb
geode-for-redis/README.md
geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/commands/executor/list/LTrimNativeRedisAcceptanceTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/list/LTrimDUnitTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/list/AbstractLPopIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/list/AbstractLTrimIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/list/AbstractRPopIntegrationTest.java
geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/list/LTrimIntegrationTest.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/RedisCommandType.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/list/LTrimExecutor.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/AbstractRedisData.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisList.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisList.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/collections/SizeableByteArrayList.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/RetainElementsByIndexRange.java
geode-for-redis/src/test/java/org/apache/geode/redis/internal/data/RedisListTest.java
geode-for-redis/src/test/java/org/apache/geode/redis/internal/data/collections/SizeableByteArrayListTest.java

GEODE-9953: Implement LTRIM Command
Implements the Redis LTRIM command using the new versioning scheme.

GEODE-9953: Implement LTRIM Command

---

ci/scripts/execute_redis_tests.sh
geode-for-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch

Updates the geode-for-redis ci integration tests to run the Native Redis TCL tests against Geode for Redis.

GEODE-10116: Enable Redis TCL tests for Lists

---

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Put70.java
geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/Put70Test.java

* To set possible duplicate for an event, whether region is persistent
need to be determined. Allow an accessor to check the setting through
profiles.

GEODE-10211: Correctly check persistence on accessor

---

geode-core/src/main/java/org/apache/geode/cache/client/internal/QueueManagerImpl.java

CacheClientNotifierDUnitTest failed with an NPE because queuedConnection
is occationally null when trying to recover the primary. This is solved
by checking for null before calling any methods on that object.

GEODE-10106: Handle NPE in QueueManagerImpl

---

geode-for-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch
geode-for-redis/src/main/java/org/apache/geode/redis/internal/commands/executor/list/LInsertExecutor.java

LINSERT was case-sensitive with its arguments BEFORE/AFTER.Redis
implementation of LINSERT is not case-sensitive.
Authored-by: Bala Kaza Venkata <bkazavenkata@vmware.com>

GEODE-10198: Fix LINSERT's case-sensitivity for arguments

---

geode-core/src/integrationTest/java/org/apache/geode/distributed/LocatorLauncherLocalIntegrationTest.java
geode-core/src/main/java/org/apache/geode/distributed/LocatorLauncher.java

* While creating SSLConfig no new DistributionConfigImpl is created.
* Now, the DistributionConfig is taken from the InternalLocator class.
*

GEODE-10053: Use stored DistributionConfig to create SSL configurations

---

geode-core/src/distributedTest/java/org/apache/geode/internal/statistics/StatisticsDistributedTest.java

When we started running with JDK 11, some users noticed that a few stats
had gone missing. There was a one line fix in test.gradle, but the
change was not tested. This adds a test for the existence of the VM
stats so that none of the stats go missing in the future.

GEODE-10216: Add test for existence of VM stats

---

geode-core/src/main/java/org/apache/geode/internal/admin/remote/DistributionLocatorId.java
geode-core/src/test/java/org/apache/geode/internal/admin/remote/DistributionLocatorIdTest.java

When unmarshalling an instance with a host name that can't be resolved a
NullPointerException is thrown in hashCode(). Use Objects.hash() to
resolve hash code to avoid NullPointerException.

GEODE-10127: Corrects NullPointerException in hashCode().

---

geode-core/src/main/java/org/apache/geode/management/internal/configuration/functions/GetClusterConfigurationFunction.java
geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt
geode-core/src/upgradeTest/java/org/apache/geode/internal/cache/GetClusterConfigurationFunctionCompatibilityTest.java

* SerialVersionUID added to GetClusterConfigurationFunction.
* Changes to this class will prevent breaking backward compatibility.

GEODE-10203: SerialVersionUID added.

---

geode-core/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
geode-core/src/main/java/org/apache/geode/internal/cache/UpdateOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PutMessage.java
geode-wan/src/distributedTest/java/org/apache/geode/cache/wan/internal/cli/commands/WanCopyRegionCommandDUnitTest.java

The wan-copy region command does not always prevent that callbacks are executed at
the remote site for the entries copied.
The value set by the wan-copy region command for generateCallbacks to false
in the events sent via the gateway sender was not being propagated
by the server that received the events in the remote site (via the gateway
receiver), when proxying the put by means of a PutMessage or UpdateMessage.
The puts are proxied to the server with the primary bucket or to replicate
the put in case there was more than one replica in the region.
The flags in the PutMessage and UpdateMessage have been used to propagate
the value of generateCallbacks.

GEODE-10077: Avoid callbacks in wan-copy region

---

geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/Transport.java

SocketException is now also handled by messenger.handleJGroupsIOException.
This is needed on java 17 because the exception containing "Operation not permitted" is now a SocketException instead of an IOException.
But this change should have been made anyway since handleJGroupsIOException does some good things to suppress noise on shutdown and SocketException is an IOException so it make sense to 
handle it in the same way.

GEODE-10165: change how doSend handles SocketException

---

geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandIntegrationTest.java
geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/StartServerCommandIntegrationTest.java
geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandTest.java
geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartServerCommandTest.java
geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/VerifyCommandLine.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/MemberJvmOptions.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommand.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/StartServerCommand.java
geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/commands/MemberJvmOptionsTest.java

PROBLEM
When run on JDK 17, numerous acceptance tests fail because a launched
locator or server requires access to the following packages:
- java.base/sun.nio.ch
- java.management/com.sun.jmx.remote.security
SOLUTION
- Add a `MemberJvmOptions` class that reports the JDK-dependent options
required to launch a locator or server on the current process's JDK.
- Change `StartLocatorCommand` and `StartServerCommand` to add those
options to the command line when launching locators and servers.
FUTURE
Future PRs will likely put these opens/exports in an argument file, then
configure these commands to use the argument file. We are deferring that
until we identify additional needs for the argument file, so we can
choose an appropriate location for the argument file.
Co-authored-by: Dale Emery …

GEODE-10225: Gfsh start commands add exports on JDK 11+

---

geode-docs/developing/function_exec/how_function_execution_works.html.md.erb

The How Function Execution Works page contains a bullet list with bold elements and en-dashes (apparently entered via keyboard shortcuts) that are not always interpreted in the same way by different Markdown interpreters.
Simplified the layout for more reliable output by replacing each en-dash with a colon+space combination.

GEODE-10232: reformat list for more reliable rendering

---

geode-core/src/main/java/org/apache/geode/management/internal/api/LocatorClusterManagementService.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/DeploymentValidator.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/DiskStoreValidator.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/GatewayReceiverConfigValidator.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/IndexValidator.java
geode-core/src/main/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidator.java
geode-core/src/test/java/org/apache/geode/management/internal/api/LocatorClusterManagementServiceTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/DeploymentValidatorTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/DiskStoreValidatorTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/GatewayReceiverConfigValidatorTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/IndexValidatorTest.java
geode-core/src/test/java/org/apache/geode/management/internal/configuration/validators/RegionConfigValidatorTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/ClusterManagementSecurityRestIntegrationTest.java
geode-web-management/src/integrationTest/java/org/apache/geode/management/internal/rest/PdxIntegrationTest.java
geode-web-management/src/main/java/org/apache/geode/management/internal/rest/controllers/PdxManagementController.java

Add update (HTTP put) and delete (HTTP DELETE) operations support for
PDX in the cluster management REST API service.
- Add and update unit and integration tests.
- Keep old update behaviour (NotImplementedException thrown) for cache
configurations other than PDX.

GEODE-10230: PDX UPDATE/DELETE in Mgmt REST API

---

geode-core/src/main/java/org/apache/geode/internal/cache/InitialImageOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/versions/DiskVersionTag.java
geode-core/src/test/java/org/apache/geode/internal/cache/InitialImageOperationTest.java

- Change the exception thrown by DiskVersionTag.replaceNullIDs() from
AssertionError to IllegalStateException
- Catch the IllegalStateException in
InitialImageOperation.processChunk() and return false, to allow the
GII to be aborted and retried if appropriate
- Add debug log to record if this has occurred
- Add unit test for the new behaviour

GEODE-10222: Handle null memberID in GII

---

geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
geode-core/src/test/java/org/apache/geode/internal/tcp/ConnectionTransmissionTest.java

Currently, if the membership check failed, the receiver thread relies on the sender to close the connection. If the sender attempts to send another (non-handshake) message before closing the connection, the receiver will attempt to read it as a handshake message. To prevent that, we should close the connection from the receiving side if waitForMembershipCheck failed.

GEODE-9512: close receiver connection if membership check timed out

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-core/build.gradle
geode-core/src/distributedTest/java/org/apache/geode/management/QueryPdxDataDUnitTest.java
geode-junit/src/main/java/org/apache/geode/test/compiler/InMemoryClassFileLoader.java
geode-junit/src/main/java/org/apache/geode/test/compiler/InMemoryFileManager.java
geode-junit/src/main/java/org/apache/geode/test/compiler/InMemoryJavaCompiler.java
geode-junit/src/main/java/org/apache/geode/test/compiler/InMemorySourceFile.java

PROBLEM
`QueryPdxDataDUnitTest` compiles and loads classes using the
`net.openhft.compiler` library, which attempts to access a field of
`Unsafe` that does not exist on JDK 17.
SOLUTION
Use the compiler system from `geode-junit`'s
`org.apache.geode.test.compiler` package.

GEODE-10193: Replace openhft compiler with geode-junit compiler

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/rest/GradleBuildWithGeodeCoreAcceptanceTest.java

PROBLEM
GradleBuildWithGeodeCoreAcceptanceTest attempts to run Gradle v5.1.1
using the test JVM. This fails when the test is run in JDK 17, because
Gradle 5.1.1 does not support JDK 17.
SOLUTION
Configure the test's "inner" build to use the value of the GRADLE_JVM
environment variable as its JVM. This makes it use the same JVM that we
use to build Geode.

GEODE-10146: Make GradleBuildWithGeodeCoreAcceptanceTest run on JDK 17

---

geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandTest.java
geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartServerCommandTest.java
geode-gfsh/build.gradle
geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/StartMemberUtilsTest.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/MemberJvmOptions.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/StartMemberUtils.java
geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/commands/MemberJvmOptionsTest.java

The product code will no longer add CMS args for java versions that do not support CMS.

GEODE-10235: fix --maxHeap for java 17

---

geode-core/build.gradle
geode-core/src/main/java/org/apache/geode/internal/net/BufferPool.java
geode-core/src/test/java/org/apache/geode/internal/net/BufferPoolTest.java

Now if either system property is set to true that takes precedence
and heap buffers will be used. Otherwise, direct buffers will be used.

GEODE-10035: fix BufferPool sys prop logic

---

geode-core/src/main/java/org/apache/geode/internal/size/ObjectGraphSizer.java
geode-core/src/main/java/org/apache/geode/internal/size/ObjectTraverser.java
geode-core/src/test/java/org/apache/geode/internal/size/ObjectTraverserJUnitTest.java

MemoryOverheadIntegrationTest is failing on jdk17 because
it tries to make static fields that reference a proxy accessible.
Since the test asked the ObjectTraverser to skip static fields it seems like
this should not have been an issue.
But the internal implementation of ObjectTraverser attempts to make the static
fields accessible even though it will not use them.
So now if ObjectTraverser has been told to skip static fields
then it will no longer attempt to make static fields accessible.

GEODE-10185: fix MemoryOverheadIntegrationTest for jdk17

---

geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/eventing/BlockingCommandListenerTest.java

testTimeoutIsAdjusted is flaky on windows machines. This will fix it to
be less flaky.
Authored-by: Bala Kaza Venkata <bkazavenkata@vmware.com>

GEODE-10223: Fix BlockingCommandListnerTest to be less flaky.

---

geode-for-redis/src/distributedTest/java/org/apache/geode/redis/OutOfMemoryDUnitTest.java

OutOfMemoryDUnitTest now only uses CMS on jdk less than 14.

GEODE-10197: fix test for jdk17

---

geode-core/src/main/java/org/apache/geode/services/result/Result.java
geode-core/src/main/java/org/apache/geode/services/result/impl/Success.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementOperationResult.java
geode-management/src/main/java/org/apache/geode/management/api/ClusterManagementRealizationResult.java

Some javadocs contained @link tags pointing to type parameters. These
should have been @code tags, as type parameters cannot be linked to

GEODE-10023: do not @link to type params

---

geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/list/LInsertDUnitTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/list/LPopDUnitTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/list/LPushDUnitTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/list/LRemDUnitTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/list/LTrimDUnitTest.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/list/RPopDUnitTest.java
geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisList.java

- Now, with the addition of versioning and synchronization at the
higher-level methods, all the synchronization can be removed from the
small, helper methods we have.
- We still need to ensure that there is synchronization between toData
and within methods that are mutating the list.
- Inline various helper methods in RedisList as they are not adding any
value.
- Use AvailablePortHelper to set up the port that the crashing VM will
use. Without this there is interference from other tests when running
multiple tests concurrently (in the stressTest job).
- Ran at least 1000 iterations of all list-related DUnit tests without
any failures.

GEODE-10161: Remove unnecessary synchronization from RedisList

---

geode-core/src/main/java/org/apache/geode/internal/cache/control/HeapMemoryMonitor.java
geode-for-redis/src/distributedTest/java/org/apache/geode/redis/OutOfMemoryDUnitTest.java

Test now configures ZGC for jdk17.
Also changed the product to know about the ZGC memoryMXBean name "ZHeap".

GEODE-10246: fix OutOfMemoryDUnitTest for jdk17

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/gfsh_dependency_classpath.txt
geode-server-all/src/integrationTest/resources/dependency_classpath.txt

- This fixes an issue discovered with the ordering of 'manifest only'
jars and classgraph unable to find classes.

GEODE-10245: Upgrade classgraph 4.8.143 -> 4.8.145

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/GIIDeltaDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegionMap.java
geode-core/src/main/java/org/apache/geode/internal/cache/InitialImageOperation.java
geode-core/src/main/java/org/apache/geode/internal/cache/versions/RegionVersionHolder.java
geode-core/src/test/java/org/apache/geode/internal/cache/AbstractRegionMapTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/versions/RegionVersionHolderJUnitTest.java

There're 2 issues: Tombstone in GII image should save version tag into disk region RVV
even the tombstone is the same as local one. Disk region RVV holder did not use bitset.
Only bitset based holder can fill special exception. Should do it for non-bitset holder too.

GEODE-10229: GII image should fill disk region RVV's exceptions.

---

geode-core/src/distributedTest/java/org/apache/geode/internal/tcp/OffHeapByteSourceTest.java
geode-core/src/main/java/org/apache/geode/internal/tcp/ByteBufferInputStream.java

Instead of using the jdk internal java.nio.Bits.unaligned, the code
now uses the "os.arch" system property that is part of the public
jdk contract. The list of values came from jdk 1.8.

GEODE-9466: change offheap to not use java.nio.Bits.unaligned

---

geode-core/src/main/java/org/apache/geode/internal/admin/remote/DistributionLocatorId.java
geode-core/src/test/java/org/apache/geode/internal/admin/remote/DistributionLocatorIdTest.java

If original hostname was not resolvable then host is null. Use hostname
if host is null when marshaling.

GEODE-10254: Use original hostname if host is null.

---

geode-core/src/integrationTest/java/org/apache/geode/internal/stats50/BufferPoolStatsIntegrationTest.java
geode-core/src/main/java/org/apache/geode/internal/stats50/BufferPoolStats.java
geode-core/src/main/java/org/apache/geode/internal/stats50/VMStats50.java
geode-core/src/test/java/org/apache/geode/internal/stats50/BufferPoolStatsTest.java

* Adds new class for BufferPoolMXBean.
* Adds tests for BufferPoolStats.
* Cleanup VMStats50.

GEODE-10249: Adds BufferPoolMXBean stats.

---

geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/P2PMessagingConcurrencyDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/P2pMessagingSslTlsKeyUpdateDistributedTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/tcp/ConnectionCloseSSLTLSDUnitTest.java
geode-core/src/integrationTest/java/org/apache/geode/internal/net/NioSslEngineKeyUpdateTest.java
geode-core/src/main/java/org/apache/geode/internal/net/NioSslEngine.java
geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
geode-core/src/test/java/org/apache/geode/internal/net/NioSslEngineTest.java

* Key expiration works for TLSv1.3 and GCM-based ciphers
* TLS KeyUpdate messages are processed correctly
(cherry picked from commit d2535394a82ac5faf10f004f4e3c15f756f7b177)

GEODE-10122: (BACK-PORT to 1.14) P2P Messaging Handles TLS KeyUpdate Message  (#7449)

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/cache/wan/SeveralGatewayReceiversWithSamePortAndHostnameForSendersTest.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/LiveServerPinger.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/LiveServerPingerTest.java

As described in RFC, when several gateway receivers have the same value for VIP:PORT, since we have same VIP:PORT for all destinations, theoretically only one connection could be used for pinging destinations. But since all ping tasks are triggered  in parallel, generally each task will request same connection at the same time, and we will create new connection for each task.
To solve this problem, proposal is to introduce configurable option to gradually activate pinging toward destination. This can be accomplish by increasing initial delay of each ping task, when endpoint is registering to be in use. So when initially creating ping tasks, we will set initial start of each task at different time.
For example if we have 5 destinations, and we set ping interval of 5 secs, and initial delay …

GEODE-10020: Introduction of option to gradually activate pinging

---

geode-core/src/distributedTest/java/org/apache/geode/cache/client/ClientServerRegisterInterestsDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientBug39997DUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientNoServerAvailabileDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientNoServerAvailabileDistributedTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientStatsDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableRegistrationDistributedTest.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientCQDUnitTest.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientHAQueuedDUnitTest.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientSimpleDUnitTest.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientTestBase.java
geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientTestCase.java
geode-dunit/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheServerTestUtil.java

There were a couple of basic timing issues with the code.
- Starting the cache server is not a synchronous event.
- We were not waiting for the queues to clear before restarting, this allowed messages to "persist"
across a restart of the durable client.
Basically all of the problems here are timing issues in the tests.
See my PR comments for key changes

Bugfix/GEODE-10228 DurableClientTestCase.testDurableHAFailover is failing

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/UpdatePropagationDUnitTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/UpdatePropagationDistributedTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/UpdatePropagationPRDistributedTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/tcp/CloseConnectionTest.java
geode-core/src/distributedTest/java/org/apache/geode/internal/tcp/TCPConduitDUnitTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/direct/DirectChannel.java
geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectionTable.java
geode-core/src/main/java/org/apache/geode/internal/tcp/TCPConduit.java
geode-core/src/test/java/org/apache/geode/internal/tcp/ConnectionTransmissionTest.java
geode-core/src/test/java/org/apache/geode/internal/tcp/TCPConduitTest.java

Problem:
When replicating to other servers, current logic would first create connections toward all servers, and then replicate data over those connections. Creation of connections will last, until all connections are created, or destination server/s is/are declared dead.
Solution:
New proposal is, when replicating data, first try to create connections to all destinations in one attempt. For all created connections we will replicate data. After this step is completed, we will try to create remaining connections to all unreachable destinations, until connections are established, or destination is declared dead. If connections are established we will replicate data.
For more info see https://cwiki.apache.org/confluence/display/GEODE/Improve+data+inconsistency+in+replicated+regions
- [*] Is …

GEODE-9484: Improve sending message to multy destinations

---

ci/images/google-geode-builder/scripts/setup.sh
ci/images/google-windows-geode-builder/packer.json

Replaces old stackdriver-agent, to enable CI utilization metrics

GEODE-10274: Install GCP ops-agent in CI images

---

geode-core/src/main/java/org/apache/geode/internal/cache/BucketAdvisor.java
geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegion.java
geode-core/src/test/java/org/apache/geode/internal/cache/BucketAdvisorTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelWANConflationDistributedTest.java

* When depose primary during rebalance, do not release the primary lock
before all colocated child buckets has deposed primary. This is to
ensure that the node becomes new primary can only acquire the primary
lock afterwards.
* All colocated buckets now share the same primaryMoveReadWriteLock.
When parent bucket is being moved, no operations will be executed on
child buckets as well. So moving primary for all colocated buckets
shold be faster, and there is no need to hold parent locks anymore.

GEODE-10242: Do not release primary lock prematurely

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/dependency_classpath.txt

dependencies on develop wherever possible.
Latest (5.2.21) is recommended for 5.2-based support branches.

GEODE-10275: Bump spring from 5.2.20 to 5.2.21

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/gfsh_dependency_classpath.txt
geode-server-all/src/integrationTest/resources/dependency_classpath.txt

dependencies on develop wherever possible.

GEODE-10275: Bump spring from 5.3.18 to 5.3.19

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/gfsh_dependency_classpath.txt
geode-server-all/src/integrationTest/resources/dependency_classpath.txt

classgraph 4.8.145 -> 4.8.146
micrometer 1.8.4 -> 1.8.5
netty-handler 4.1.75 -> 4.1.76
spring-boot-starter-web 2.6.6 -> 2.6.7
spring-hateoas 1.4.1 -> 1.4.2
spring-ldap-core 2.3.6 -> 2.3.7
spring-security 5.6.2 -> 5.6.3

GEODE-10046: Bump 3rd-party dependency versions

---

geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderEventProcessor.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelWANConflationDistributedTest.java

* Do not throw RejectedExecutionException if it is caused by cache
closing.

GEODE-10272: Handle RejectedExecutionException during shutdown.

---

geode-assembly/src/main/dist/LICENSE

this was overlooked in #7605 and again in #7650, oops

GEODE-10046: fix classgraph version in LICENSE

---

.asf.yaml

GEODE-10293: Modify .asf.yaml to require CodeQL, drop LGTM

---

geode-docs/configuring/cluster_config/gfsh_persist.html.md.erb
geode-docs/managing/security/enable_security.html.md.erb

- Modified description of security-manager property to incorporate the distinctions requested in the ticket
- Introduced some subheadings for readability
- Added links to subheads in the Configuration Service section to allow a cross-reference from the modified security-manager section.

GEODE-10307: Doc changes needed for enable security-manager property

---

ci/pipelines/shared/jinja.variables.yml

To be 3h45m, 15 minutes shy of the newly increased task timeout.

GEODE-10302: Increase call stack timeout for upgrade tests

---

geode-core/src/main/java/org/apache/geode/internal/cache/CacheServerImpl.java

When stopping the cache server, the acceptor is last to shut down of three services, which should not be the case. It should be first so new data stops coming in. Simple swapping of the order.

GEODE-10306:   Fixing an order issue that can lead to problems when stopping

---

geode-core/src/main/java/org/apache/geode/internal/cache/map/RegionMapPut.java
geode-core/src/test/java/org/apache/geode/internal/cache/map/RegionMapPutTest.java

* During putIfAbsent retry, comparing invalid token value when
putIfAbsent of a null value instead.

GEODE-10294: Compare invalid token during putIfAbsent retry.

---

ci/scripts/execute_tests.sh

- GEODE-10288: Define JDK 8, 11, 17 homes for upgrade tests (#7675)
- GEODE-10288: Fix property assignment syntax (#7678)

backport/geode 10288/java homes

---

ci/pipelines/shared/jinja.variables.yml

Using the test-isolation plugin for parallelism, instead of Docker,
enables parallel testing on Windows for some jobs.

GEODE-10309: Enable parallel tests for windows-gfsh-distributed-test

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
build-tools/geode-dependency-management/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/gfsh_dependency_classpath.txt
geode-server-all/src/integrationTest/resources/dependency_classpath.txt

This will also help out Spring.
* Bump micrometer from 1.8.5 to 1.9.0

GEODE-10320: Bump micrometer from 1.8.5 to 1.9.0

---

geode-core/src/main/java/org/apache/geode/internal/net/SSLUtil.java
geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java
geode-core/src/test/java/org/apache/geode/internal/net/SSLUtilTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/misc/WANSSLDistributedTest.java

- Modify SSLUtil to attempt to create SSLContext using the default
protocols
- Add WANSSLDistributedTest to test protocol/cipher combinations in WAN
context
- Do not hide exception when generating key pair in CertificateBuilder
- Fix javadoc error in SocketCreator

GEODE-10297: Create SSLContext using default protocols

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
build-tools/geode-dependency-management/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/gfsh_dependency_classpath.txt
geode-server-all/src/integrationTest/resources/dependency_classpath.txt

* Bump spring from 5.3.19 to 5.3.20

GEODE-10275: Bump spring from 5.3.19 to 5.3.20

---

geode-assembly/src/acceptanceTest/java/org/apache/geode/cache/wan/SeveralGatewayReceiversWithSamePortAndHostnameForSendersTest.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/ConnectionImpl.java
geode-core/src/main/java/org/apache/geode/cache/client/internal/OpExecutorImpl.java
geode-core/src/main/java/org/apache/geode/distributed/internal/ServerLocation.java
geode-core/src/main/java/org/apache/geode/distributed/internal/ServerLocationExtension.java
geode-core/src/test/java/org/apache/geode/cache/client/internal/ConnectionImplTest.java
geode-core/src/test/java/org/apache/geode/distributed/internal/ServerLocationExtensionTest.java
geode-core/src/test/java/org/apache/geode/distributed/internal/ServerLocationTest.java

As described in RFC, when several gateway receivers have the same value for VIP:PORT, if we are pinging dedicated receiver, there are chance that we will not hit desired receiver. In that case contacted receiver will reply to sender, and forward request to final destination (desired receiver).
But current logic would in this case, saw reply from contacted receiver, as a new active destination, and create new task for pinging this new destination.
So this is proposal that for Ping task (which as prerequisite has defined destination endpoint), when sending ping message, in case connected endpoint is different than the destination endpoint, don't register this new endpoint.
- [*] Has your PR been …

GEODE-10020: For Ping task avoid registering new destination endpoint

---

CODEOWNERS

Add Darrel to geode-dunit and geode-junit while Dale is unavailable.

GEODE-10327: Update geode-dunit and geode-junit codeowners

---

ci/pipelines/shared/jinja.variables.yml

Fixup of previous commit for this PR. Git Merge added the increased memory to the wrong CI job and we didn't notice.

GEODE-10309: fixup: Give more memory to windows-core-integration-test

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
build-tools/geode-dependency-management/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy

* Bump spring-security from 5.6.3 to 5.6.5

GEODE-10355: Bump spring-security from 5.6.3 to 5.6.5

---

ci/scripts/archive_results.sh
ci/scripts/create_instance.sh
ci/scripts/delete_instance.sh
ci/scripts/execute_build.sh
ci/scripts/execute_tests.sh
ci/scripts/repeat-new-tests.sh
ci/scripts/rsync_code_down.sh
ci/scripts/rsync_code_up.sh
ci/scripts/shared_utilities.sh

Examples being CODEOWNERS and .asf.yaml. Saves on CI spend.

Short-circuit CI checks for PRs that don't touch buildable files

---

dev-tools/docker/docs/Dockerfile

The script to preview the documentation of Geode (./preview-user-guide.sh)
is not working anymore.
The following error appears while running it (unless you have a previously downloaded
geodedocs/temp docker image in your local docker repo):
ERROR: Error installing elasticsearch:
The last version of faraday (>= 0) to support your Ruby & RubyGems was 1.10.0. Try installing it with `gem install faraday -v 1.10.0` and then running the current command again
faraday requires Ruby version >= 2.6. The current ruby version is 2.5.9.229.
That error prevents the preview script to work.
It is needed to update the docker image used to preview the documentation to use a Ruby version >= 2.6.
The versions of other gems also need to be updated after the
change of the Ruby version.

GEODE-10352: Update Ruby version in Geode doc preview tool

---

geode-core/src/distributedTest/java/org/apache/geode/cache30/ReconnectDUnitTest.java
geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java

* Also refactor ReconnectDUnitTest to use lamdas instead of `Callable` and `Runnable` interfaces.
This flakiness shows up in a test. In a production environment, the call to `locator.waitToStop()` happened immediately after the locator is launched, not as the test, it happened just before we force to stop the locator, so a rare race condition in the call would make the thread to exit.

GEODE-10304: locator thread should not exit after reconnecting

---

LICENSE
dev-tools/release/license_review.sh
geode-assembly/src/main/dist/LICENSE

we have some dependency changes due to recent redis removal, change to springdoc and inclusion of joda-time

GEODE-10089: update LICENSE

---

geode-dunit/src/main/java/org/apache/geode/management/internal/cli/commands/IndexCommandsIntegrationTestBase.java
geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreateIndexCommandDUnitTest.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/CreateIndexCommand.java
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/functions/CreateIndexFunction.java

The new solution is added regarding comment from the [dev list](https://markmail.org/message/uxhlysb2nx3u7p6y).
When creating an index on the partition region it should just send to one server as it will propagate the create index message to the rest of the members of that group(cluster or one the user specified in the command).

GEODE-7875:  fix create index gfsh command on partitioned region

---

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/partitioned/colocation/ModifyColocationIntegrationTest.java

GEODE-10351: Wait till the cache is completely closed before re-creating

---

geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/deadlock/GemFireDeadlockDetectorDUnitTest.java

* fix GemFireDeadlockDetectorDUnitTest.testDistributedDeadlockWithDLock
Test Issue. Gate signaled before 2nd lock is acquired and the the assertion comes in before the 2nd lock is locked.

GEODE-6489: fix a flaky test

---

geode-wan/src/distributedTest/java/org/apache/geode/cache/CacheXml70GatewayDUnitTest.java
geode-wan/src/distributedTest/java/org/apache/geode/cache/CacheXml80GatewayDUnitTest.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/wancommand/CreateDestroyGatewaySenderCommandDUnitTest.java
geode-wan/src/integrationTest/java/org/apache/geode/internal/cache/wan/misc/WANConfigurationJUnitTest.java
geode-wan/src/main/java/org/apache/geode/cache/wan/internal/GatewaySenderFactoryImpl.java

Problem:
-**parallel gw sender**:
When creating a parallel gw sender with a non-existent disk store it will pass as it will not check if disk store exist.
-**serial gw sender**:
When running the command for creating a serial gw sender with a non-existent disk store it will fail, **but** a serial gw sender will be created. If we then create a disk store and run the same command again it will fail as the gw sender is already created.
Solution:
Check if the disk store parameter is set and check if that disk store exists in the system.

GEODE-10267: fix creating gw sender with non-existent disk store

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/expected_jars.txt

* Bump spring-security from 5.4.8 to 5.6.5

GEODE-10355: Bump spring-security from 5.4.8 to 5.6.5

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
buildSrc/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/expected_jars.txt

* Bump spring-security from 5.2.12.RELEASE to 5.5.8

GEODE-10355: Bump spring-security from 5.2.12 to 5.5.8

---

geode-docs/managing/security/implementing_authentication_expiry.html.md.erb
geode-docs/managing/security/implementing_ssl.html.md.erb

Doc format fixes. Back port to 1.15 ASAP.

(no JIRA ticket) user guide Security section: Typo & format fixes

---

geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/ClusterDistributionManagerDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/monitoring/executor/AbstractExecutor.java
geode-docs/managing/troubleshooting/diagnosing_system_probs.html.md.erb

This is the implementation of the feature
described in RFC:
https://cwiki.apache.org/confluence/display/GEODE/Management+of+threads+stuck+for+a+long+time+in+Geode

GEODE-10344: Send alert when thread stuck for long

---

geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java
geode-core/src/test/java/org/apache/geode/internal/cache/OplogEntryIdSetDrfHashSetThresholdTest.java

Configurable with the jvm parameter:
gemfire.disk.drfHashMapOverflowThreshold
Default value: 805306368
When configured threshold value is reached, then server will overflow to
the new hashmap during the recovery of .drf files. Warning: If you set
threshold parameter over 805306368, then uneeded delay will happen due
to bug in fastutil dependency.

GEODE-10401: Configurable .drf recovery HashMap overflow threshold 

---

geode-core/src/main/java/org/apache/geode/cache/query/internal/AbstractGroupOrRangeJunction.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledJunction.java
geode-core/src/main/java/org/apache/geode/cache/query/internal/index/MemoryIndexStore.java
geode-cq/src/distributedTest/java/org/apache/geode/cache/query/dunit/QueryWithRangeIndexDUnitTest.java

GEODE-9632: fix for queries with multy operations and indexes

---

geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterOperationExecutors.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySender.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderOperationsDistributedTest.java

There is a distributed deadlock that can appear
when stopping the gateway sender if a race condition
happens in which the stop gateway sender command gets blocked
indefinitely trying to get the size of the queue from remote peers
(ParallelGatewaySenderQueue.size() call) and
also one call to store one event in the queue tries to get
the lifecycle lock (acquired by the gateway sender command).
These two calls could get into a deadlock under heavy load and
make the system unresponsive for any traffic request (get, put, ...).
In order to avoid it, in the storage of the event in the gateway
sender queue (AbstractGatewaySender.distribute() call),
instead of trying to get the lifecycle lock without
any timeout, a try with a timeout is added. If the
try returns false it is checked if the gateway …

GEODE-10403: Fix distributed deadlock with stop gw sender

---

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/versions/TombstoneDUnitTest.java
geode-core/src/main/java/org/apache/geode/internal/cache/TombstoneService.java
geode-core/src/test/java/org/apache/geode/internal/cache/TombstoneServiceTest.java

The issue:
During region destroy operation, the expired tombstones aren't cleared
when non-expired ones are available. Later, these expired
tombstones prevent all other regions' tombstones from being cleared
from memory, causing many issues (memory and disk exhaustion).
The solution:
When a region is destroyed, it must clear all the related expired and
non-expired tombstones from memory.

GEODE-10412: Clear expired tombstones during region destroy

---

geode-log4j/src/integrationTest/java/org/apache/geode/logging/log4j/internal/impl/LogWriterAppenderShutdownIntegrationTest.java
geode-log4j/src/main/java/org/apache/geode/logging/log4j/internal/impl/LogWriterAppender.java

When a stop session is called on the LogWriterAppender, it closes the
ManagerLogWriter's files. Still, it does not release
ManagerLogWriter's reference, so the LogWriterAppender instance is
kept around after disconnect. This situation ends up keeping the
InternalDistributedSystem alive.
The fix is to clear the LogWriterAppender's reference to the
ManagerLogWriter when the appender session is stopped.

GEODE-10338: Fix LogWriterAppender shutdown

---

geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegionQueue.java
geode-core/src/test/java/org/apache/geode/internal/cache/BucketRegionQueueJUnitTest.java
geode-core/src/test/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderQueueJUnitTest.java

When the WAN group-transaction-events feature is enabled in
a parallel gateway sender, it is possible to get a NullPointerException
when retrieving events from the queue to complete a transaction if
the event in the queue is null.
If this situation is reached then the gateway sender dispatcher will
not dispatch queue events anymore and therefore the WAN replication
will not progress.
This happens because the predicates that check if elements
in the queue contain a transactionId are not protected
against the event being null.
A null check has been added before the predicates are invoked
so that in case of a null event, the predicate is not invoked
and the event is skipped from the checking.

GEODE-10417: Fix NullPointerException in WAN replication

---

geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java
geode-core/src/main/java/org/apache/geode/internal/net/SocketCreatorFactory.java
geode-core/src/test/java/org/apache/geode/internal/net/SocketCreatorFactoryJUnitTest.java

GEODE-10337: add use of SocketCreatorFactory.close()

---

geode-core/src/main/java/org/apache/geode/internal/cache/EntryEventImpl.java
geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySender.java
geode-core/src/test/java/org/apache/geode/internal/cache/wan/AbstractGatewaySenderTest.java

It is possible that an event of which a gateway sender is to be notified is lost if during the process the thread is interrupted.
The reason is that the distribute() method
in the AbstractGatewaySender when it catches the
InterruptedException at some point, just returns, but does not put the event in the queue and neither
drops it.
The fix consists of handling the event correctly
(put it in the queue or drop it) if the InterruptedException is caught but when the method returns set again
the interrupt flag so that the caller is aware.

GEODE-10420: Finish distribute() work if interrupted

---

geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java
geode-docs/tools_modules/gfsh/command-pages/start.html.md.erb
geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/StartGatewaySenderCommand.java
geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/wancommand/StartGatewaySenderCommandDUnitTest.java

GEODE-10421: Improve start gw sender with clean-queue

---

.github/workflows/gradle.yml

GEODE-10445: Add wan, cq, lucene, assembly, mgmt distributed tests to pipeline 

---

geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/ConcurrentTestRunner.java
geode-concurrency-test/src/main/java/org/apache/geode/test/concurrency/loop/LoopRunner.java

GEODE-10447: use getDeclaredConstructor() for supporting JDK11

---

ci/pipelines/shared/jinja.variables.yml

Replace 1.15.0 with 1.15.1 in old versions and set as default Benchmarks baseline on develop to enable rolling upgrade tests from 1.15.1
The serialization version has not changed between 1.15.0 and 1.15.1, so there should be no need to keep both

GEODE-10401: Replace 1.15.0 with 1.15.1 as old version

---

geode-core/src/main/java/org/apache/geode/internal/cache/EntriesSet.java
geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java

When I compile with jdk11, I got an error below:
This is caused by we have two `toArray` in `PartitionedRegion`, 
one is  
```
public Object[] toArray(Object[] array)
```
other is from `Collection` which is introduced in jdk 11. 
```java
default <T> T[] toArray(IntFunction<T[]> generator) {
return toArray(generator.apply(0));
}
```
This PR aims to fix this.

Fix compile error in jdk11 due to toArray confusion

---

.github/workflows/codeql.yml
.github/workflows/gradle.yml
settings.gradle

This PR migrates the Geode project to publish Build Scans to the the new Develocity instance at develocity.apache.org.
Additionally, this PR migrates from the legacy Gradle Enterprise plugin to the renamed Develocity plugin and sets a projectId for use by Develocity.
https://issues.apache.org/jira/browse/GEODE-10457

Publish build scans to develocity.apache.org

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
build-tools/geode-dependency-management/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/gfsh_dependency_classpath.txt

Upgrade Jackson to 2.17.0

---

.github/workflows/codeql.yml
.github/workflows/gradle.yml

GEODE-10434: Fix deprecated actions/upload-artifact@v3

---

geode-web-api/src/main/java/org/apache/geode/rest/internal/web/controllers/AbstractBaseController.java
geode-web-api/src/main/java/org/apache/geode/rest/internal/web/controllers/BaseControllerAdvice.java
geode-web-api/src/main/java/org/apache/geode/rest/internal/web/controllers/PdxBasedCrudController.java

Unify web api exception return value specification to json.

---

geode-core/src/test/java/org/apache/geode/internal/size/WellKnownClassSizerJUnitTest.java

WellKnownClassSizerJUnitTest

---

boms/geode-all-bom/src/test/resources/expected-pom.xml
build-tools/geode-dependency-management/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-assembly/src/integrationTest/resources/assembly_content.txt
geode-assembly/src/integrationTest/resources/gfsh_dependency_classpath.txt

Upgrade snappy to 0.5

---

build-tools/geode-dependency-management/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
geode-log4j/src/main/java/org/apache/geode/logging/log4j/internal/impl/NullLogWriter.java

Update NullLogWriter to migrate NullOutputStream to INSTANCE

---

geode-assembly/src/main/dist/LICENSE

Updates the SLF4J API version and copyright attribution in the assembled distribution LICENSE file:
- Previous: SLF4J API v1.7.32, Copyright (c) 2004–2017 QOS.ch
- Updated: SLF4J API v1.7.36, Copyright (c) 2004–2025 QOS.ch
- Reflects the actual SLF4J version now bundled and aligns copyright years with upstream project notice. 
- Ensures compliance and accuracy of third‑party attributions.
- Documentation/license metadata only.
- No functional or dependency changes introduced in this PR (dependency was already at 1.7.36, license text lagged behind).
- Confirmed build includes slf4j-api 1.7.36.
- Verified upstream LICENSE/COPYRIGHT years (2025 appears in current SLF4J distribution).
- None to runtime, packaging only. Improves legal clarity.
Checklist

Update LICENSE: SLF4J API version and copyright notice
