apache/geode

COMPILING.txt
Testing pull requests from GitHub
=> [GEODE-41] #comment Fix issue #41

gemfire-core/src/main/java/com/gemstone/gemfire/internal/redis/RegionProvider.java
When creating regions for sorted sets, better handling of index creation
exceptions now correctly deals with possible errors. Also, error logging
from the RegionProvider class has been removed.
=> GEODE-313 Improve redis adpater region exception handling

gemfire-spark-connector/doc/5_rdd_join.md
=> Fix Spark Connector tutorial links flow

gemfire-site/website/content/community/index.html
Update committers' list on website community page
=> Update committers' list

gemfire-core/src/test/java/com/gemstone/gemfire/cache/query/internal/QueryFromClauseCanonicalizationJUnitTest.java, gemfire-core/src/test/java/com/gemstone/gemfire/cache/query/internal/ResultsBagJUnitTest.java
* removed invalid header from ResultsBagJUnitTest and QueryFromClauseCanonicalizationJUnitTest
=> GEODE-901: Remove invalid source headers

gemfire-site/website/layouts/footer.html
Changed copyright from 2015 to 2016.
[fixes #113861077]
=> GEODE-903 Update Copyright

geode-examples/replicated/README.md
- Improved the appearance of the markdown
- Added commands for how to kill a single server
- Added last step to run scripts/stopAll.sh so the system is
shut down when the example ends, not leaving a locator and
a server running
- Improved the prose describing what the example does
=> GEODE-1531: Improve README.md for replicated example

geode-examples/README.md
Clarify prose that identifies value to set for GEODE_HOME,
based on dev feedback.
=> GEODE-33: clarify GEODE_HOME value

geode-core/src/main/java/org/apache/geode/redis/GeodeRedisService.java, geode-redis/src/test/java/org/apache/geode/redis/AuthJUnitTest.java
=> Minor non-functional changes in response to PR comments.

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ExportLogsDUnitTest.java
Precheckin started (still running)
=> GEODE-2621: Reduce time sensitivity of ExportLogsDUnitTest

geode-book/config.yml, geode-book/master_middleman/source/subnavs/geode-subnav.erb, geode-book/redirects.rb
This PR only addresses doc changes in the Apache geode repository.  Any website changes related to releasing a 1.2 version of Geode will need to be done in a separate PR, and on the geode-site repository.
@joeymcallister @davebarnes97 and any other Geode afficionados, will you please review this PR?
=> GEODE-2777 Update docs to be for Geode version 1.2

geode-docs/reference/topics/gemfire_properties.html.md.erb
@bschuchardt @metatype @joeymcallister @davebarnes97 Please review rewritten definition of the revised system property that satisfies GEODE-3249.
=> GEODE-3249 Revise docs for internal msg validation

geode-core/src/main/java/org/apache/geode/internal/cache/ExpiryTask.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/RegionExpiryTask.java, geode-core/src/test/java/org/apache/geode/cache30/MultiVMRegionTestCase.java, geode-core/src/test/java/org/apache/geode/cache30/RegionTestCase.java
=> GEODE-3543: refactor ExpiryTask to not call GemFireCacheImpl.getInstance

geode-docs/tools_modules/gfsh/command-pages/stop.html.md.erb
@kirklund @jinmeiliao @joeymcallister @davebarnes97 @PurelyApplied  Please review.
=> GEODE-3579 Update gfsh stop locator docs

geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/GenericProtocolServerConnectionTest.java
- [] Have you written or updated unit tests to verify your changes?
N/A
N/A
=> GEODE-3079 Ensure emergencyClose() closes socket

geode-protobuf/src/test/java/org/apache/geode/protocol/acceptance/CacheConnectionJUnitTest.java, geode-protobuf/src/test/java/org/apache/geode/protocol/acceptance/CacheConnectionTimeoutJUnitTest.java, geode-protobuf/src/test/java/org/apache/geode/protocol/acceptance/CacheMaxConnectionJUnitTest.java
* Remove 15 second sleep
* bring back max connection test
* stats test should not pollute work dir
* Fix timing around ClientHealthMonintor testing
=> GEODE-3623 Clean up issues caused by bad merges

geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/PersistentColocatedPartitionedRegionDUnitTest.java
This PR seeks to fix a flaky test. The test was checking for asynchronous logging of a warning, then carrying out the action that should stop the warning from happening again. However, this leaves a gap for the warning to be logged an additional time and the test checks to make sure that no more invocations are made on the logger. I have changed it to instead check that no additional loggings of the warning occur AFTER the action that should stop the warning completes.
@dschneider-pivotal 
@pivotal-eshu 
@lgallinat 
@agingade 
@kirklund
=> GEODE-3180: Fix flaky test

geode-docs/configuring/cluster_config/deploying_application_jars.html.md.erb, geode-docs/configuring/cluster_config/gfsh_config_troubleshooting.html.md.erb, geode-docs/configuring/cluster_config/persisting_configurations.html.md.erb, geode-docs/configuring/cluster_config/using_member_groups.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/alter.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/change.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/close.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/compact.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/deploy.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/destroy.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/execute.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/export.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/gc.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/list.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/netstat.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/pause.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/resume.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/show.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/start.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/status.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/stop.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/undeploy.html.md.erb
- option for group extended to groups
- option for member extended to members
- option for jar extended to jars
Note that the documentation will now only state the plural form of --groups, --members, and --jars, while the code accepts both. 
@davebarnes97 @joeymcallister @jaredjstewart @PurelyApplied @jinmeiliao  Please review.
=> GEODE-2818 Document gfsh aliases

geode-assembly/src/test/java/org/apache/geode/management/internal/cli/shell/GfshDisconnectWithinScript.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ShellCommands.java
=> GEODE-3590: Prevent NPE during scripted disconnect.

geode-docs/reference/topics/client-cache.html.md.erb
@joeymcallister @davebarnes97 @kohlmu-pivotal @galen-pivotal Please review.
=> GEODE-2788 Document defn of pool attr socket-connect-timeout

geode-book/master_middleman/source/subnavs/geode-subnav.erb, geode-docs/managing/cache_snapshots/exporting_a_snapshot.html.md.erb, geode-docs/managing/cache_snapshots/filtering_snapshot_entries.html.md.erb, geode-docs/managing/cache_snapshots/importing_a_snapshot.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/export.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/import.html.md.erb, geode-docs/tools_modules/gfsh/quick_ref_commands_by_area.html.md.erb
Documented the new 'parallel' option for gfsh export data and import data commands. Included changes to the Java API and new examples. Some convenient format improvements, while I had the files open.
Request reviews from anyone interested, but especially @nreich, @karensmolermiller and @joeymcallister .
=> GEODE-3378: Document Snapshot Improvements

geode-protobuf/src/test/java/org/apache/geode/protocol/acceptance/CacheMaxConnectionJUnitTest.java
This is joint work with @hiteshk25 , I had to make a few changes to get it to rebase cleanly.
=> GEODE-3080 Add a multiple-connections-per-thread test for new protocol.

geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java, geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpServer.java, geode-protobuf/src/test/java/org/apache/geode/protocol/acceptance/LocatorConnectionDUnitTest.java
- Increment and decrement connection count stats.
- Add stat checking to a locator test.
- Add stats to a second test method.
- Prevent locator state from one test from influencing another test.
=> GEODE-3546: Finish new protocol Locator stats.

geode-core/src/test/java/org/apache/geode/security/ClientAuthDUnitTest.java
=> GEODE-3692: Add Flaky tag to intemittent test failure

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ExecuteFunctionCommand.java
=> GEODE-3704: fix NPE when executing function with no security manager.

geode-docs/developing/query_index/creating_hash_indexes.html.md.erb
@sbawaska @boglesby @joeymcallister @davebarnes97 Please review the stronger wording on the performance of hash indexes.
=> GEODE-3701 Improve docs on hash index performance

geode-assembly/build.gradle, gradle/dependency-resolution.gradle, gradle/ide.gradle
=> GEODE-3699: Prevent gradle warnings by avoiding deprecated << operator.

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateAsyncEventQueueCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DeployCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyFunctionCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/UndeployCommand.java, geode-core/src/main/java/org/apache/geode/security/ResourcePermission.java, geode-core/src/test/java/org/apache/geode/management/internal/security/TestCommand.java
=> GEODE-3703: rename target permission from JAR to DEPLOY

geode-core/src/test/java/org/apache/geode/test/dunit/Disconnect.java, geode-core/src/test/java/org/apache/geode/test/dunit/DistributedTestUtils.java, geode-core/src/test/java/org/apache/geode/test/dunit/cache/rules/CacheRule.java, geode-core/src/test/java/org/apache/geode/test/dunit/cache/rules/tests/CacheRuleTest.java, geode-core/src/test/java/org/apache/geode/test/dunit/internal/JUnit4DistributedTestCase.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/DistributedTestRule.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/RemoteInvoker.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/SharedCountersRule.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/tests/SharedCountersDistributedTest.java, geode-junit/src/main/java/org/apache/geode/test/junit/runners/TestRunner.java
Also minor improvements to DUnit:
* Move disconnect methods to Disconnect
* Add withVMCount support to DistributedTestRule
* Improve API for DUnit Locator in DistributedTestUtils
[These improvements are required for my new tests for GEODE-3693]
=> GEODE-3715: introduce CacheRule and SharedCountersRule

geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsDUnitTest.java
The CliCommandTest was causing this test to be flaky. Refactoring to use
the new test framework.
=> GEODE-3673: Refactored Lucene commands test to use new framework

geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionQueryEvaluator.java, geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionQueryEvaluatorTest.java
=> GEODE-3712: PartitionedRegionQueryEvaluator should shuffle node list

geode-core/src/main/java/org/apache/geode/cache/execute/Function.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction65.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction66.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunction.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunction61.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunction65.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunction66.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunctionSingleHop.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/UserFunctionExecution.java, geode-core/src/main/java/org/apache/geode/security/ResourcePermission.java, geode-core/src/test/java/org/apache/geode/management/internal/security/TestFunctions.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/distributed/LuceneQueryFunction.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/distributed/WaitUntilFlushedFunction.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/results/LuceneGetPageFunction.java
=> GEODE-3723: Remove Optional<String> from getRequiredPermissions

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ShowMetricsCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ShowMetricsCommandJUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ShowMetricsCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ShowMetricsDUnitTest.java, geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshParserRule.java
=> GEODE-3542: Add descriptive error message for gfsh show metrics

geode-core/src/main/java/org/apache/geode/security/ResourcePermission.java
added back the deleted api for backward compatibility
=> GEODE-3621: revert the change to maintain backward compatibility

geode-core/src/main/java/org/apache/geode/cache/execute/Function.java
@jdeppe-pivotal @jaredjstewart @jinmeiliao @davebarnes97 @joeymcallister Please review.
=> GEODE-3723 Revise javadoc defn of getRequiredPermissions parameter

geode-docs/managing/security/implementing_authorization.html.md.erb
@jinmeiliao @sbawaska @jaredjstewart @jdeppe-pivotal @davebarnes97 @joeymcallister  Please review.
=> GEODE-3703 Document JAR resource becomes DEPLOY

geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/AlterRuntimeCommandDUnitTest.java
=> GEODE-3539: Enhanced test coverage for alter runtime command options

geode-core/src/test/java/org/apache/geode/management/internal/cli/shell/GfshInitFileJUnitTest.java, geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshParserRule.java
- Prior commits seem to have introduced some instability
=> GEODE-3542: Add null guards in the case of invalid commands

geode-docs/developing/function_exec/function_execution.html.md.erb, geode-docs/developing/function_exec/how_function_execution_works.html.md.erb, geode-docs/managing/security/implementing_authorization.html.md.erb
@jaredjstewart @jinmeiliao @davebarnes97 @joeymcallister Please review.
=> GEODE-2817 Document user-defined function authorization levels

geode-protobuf/src/main/proto/clientProtocol.proto, geode-protobuf/src/main/proto/region_API.proto
removed create/destroy region messages and responses
- [na] Have you written or updated unit tests to verify your changes?
- [na] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
@kohlmu-pivotal @PivotalSarge @galen-pivotal @WireBaron @hiteshk25
=> GEODE-3695 Remove unused protobuf messages from new protocol

geode-core/src/test/java/org/apache/geode/management/internal/cli/NetstatDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ChangeLogLevelCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeConfigCommandJUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ExportLogsOnServerManagerDUnit.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/GcCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/IndexCommandsDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/IndexCommandsShareConfigurationDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/QueryCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ShowLogCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ShutdownCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/shell/GfshMultilineCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/security/GfshCommandsPostProcessorTest.java, geode-core/src/test/java/org/apache/geode/management/internal/security/GfshCommandsSecurityTest.java, geode-core/src/test/java/org/apache/geode/management/internal/security/MultiUserDUnitTest.java, geode-core/src/test/java/org/apache/geode/security/PDXGfshPostProcessorOnRemoteServerTest.java, geode-core/src/test/java/org/apache/geode/security/PDXPostProcessorDUnitTest.java, geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshShellConnectionRule.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsDUnitTest.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/AlterRuntimeCommandDUnitTest.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/ConnectCommandIntegrationTest.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/ConnectCommandWithSSLTest.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/ConnectCommandWithSecurityTest.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeConfigCommandDUnitTest.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/ExecuteFunctionCommandWithSecurityDUnitTest.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/ExportConfigCommandDUnitTest.java
=> GEODE-3775: Fix typo 'jmxManger' should be 'jmxManager'

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/FunctionCommandsDUnitTest.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/CommandOverHttpDUnitTest.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/FunctionCommandsOverHttpDUnitTest.java
=> GEODE-3746: Refactor FunctionCommandsDUnitTest to use rules

geode-book/master_middleman/source/subnavs/geode-subnav.erb
Add gateway-related elements of the <cache> element in the
cache.xml descriptions.
@davebarnes97 @joeymcallister Please review.
=> GEODE-3773 Fix documentation's subnav

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/FunctionCommandsDUnitTest.java
=> GEODE-3775: Missed a jmxManger typo

geode-core/src/main/java/org/apache/geode/management/internal/cli/domain/IndexDetails.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListIndexCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/domain/IndexDetailsIntegrationTest.java, geode-core/src/test/resources/org/apache/geode/codeAnalysis/sanctionedSerializables.txt, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/CommandOverHttpDUnitTest.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/ListIndexCommandOverHttpDUnitTest.java
=> GEODE-3763: Refactor ListIndexCommandDUnitTest to use rules

geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledIteratorDef.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledSelect.java, geode-core/src/test/java/org/apache/geode/security/query/PartitionedQuerySecurityRestrictedButMethodsDoNotExistQueriesDUnitTest.java, geode-core/src/test/java/org/apache/geode/security/query/QuerySecurityBase.java, geode-core/src/test/java/org/apache/geode/security/query/QuerySecurityRestrictedQueriesDUnitTest.java, geode-core/src/test/java/org/apache/geode/security/query/QuerySecurityRetrictedButMethodsDoNotExistDUnitTest.java
=> GEODE-3787: Do not catch NotAuthorizedExceptions in CompiledIteratorDef

geode-core/src/main/java/org/apache/geode/cache/wan/GatewaySender.java, geode-core/src/main/java/org/apache/geode/cache/wan/GatewaySenderFactory.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java, geode-core/src/main/resources/META-INF/schemas/geode.apache.org/schema/cache/cache-1.0.xsd
=> GEODE-3743: Deprecating manual-start of senders

geode-docs/reference/topics/gfe_cache_xml.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb, geode-docs/topologies_and_comm/multi_site_configuration/setting_up_a_multisite_system.html.md.erb
@davebarnes97 @joeymcallister @upthewaterspout @dihardman @jhuynh1 @boglesby Please review.
=> GEODE-3761 Document manual-start deprecation of gateway senders

geode-lucene/src/main/java/org/apache/geode/cache/lucene/FlatFormatSerializer.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/FlatFormatSerializerJUnitTest.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/NestedObjectSeralizerIntegrationTest.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/repository/serializer/SerializerTestHelper.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/test/Customer.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/test/Page.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/test/Person.java
@upthewaterspout @boglesby @jhuynh1 
=> GEODE-3244: provide a build in LuceneSerializer that flattens objects

geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledIn.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/CompiledInJUnitTest.java
=> GEODE-3714: Removed repetitive looping code when evaluating

geode-docs/tools_modules/lucene_integration.html.md.erb
@upthewaterspout @joeymcallister @davebarnes97 Please do a quick review of this single letter change within the docs.
=> GEODE-3722 Revise one more instance of queryStrings

geode-core/src/test/java/org/apache/geode/internal/cache/ha/HARQueueNewImplDUnitTest.java
=> GEODE-3131: Awaitility clause added to reference count verification.

geode-core/src/main/java/org/apache/geode/cache/query/internal/RestrictedMethodInvocationAuthorizer.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/RestrictedMethodInvocationAuthorizerTest.java
=> GEODE-3803: Added additional string methods to whitelist

geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DescribeDiskStoreFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/ExportDataFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/GarbageCollectionFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/GatewayReceiverCreateFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/GatewaySenderCreateFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/GatewaySenderDestroyFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/GetMemberConfigInformationFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/GetMemberInformationFunction.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/DescribeDiskStoreFunctionJUnitTest.java
This commit is the second set of refactored Function classes.
Precheckin is green.
=> GEODE_3299: Refactor Gfsh functions to acquire Cache from FunctionContex

geode-docs/developing/query_select/the_where_clause.html.md.erb, geode-docs/managing/security/implementing_authorization.html.md.erb
@dihardman @joeymcallister @davebarnes97 @jhuynh1 @metatype @upthewaterspout Please review.
=> GEODE-3247 Document query method invocation changes

geode-docs/tools_modules/gfsh/command-pages/connect.html.md.erb
- Documented the new --skip-ssl-validation option
- Added newline characters to eliminate horizontal
scroll bars within the web page
@joeymcallister @davebarnes97 @jaredjstewart Please review.
=> GEODE-3445 Document new gfsh connect option

geode-core/src/main/java/org/apache/geode/management/cli/ConverterHint.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/CommandManager.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateIndexCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DefineIndexCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyIndexCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/GfshCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/converters/EnumConverter.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/converters/IndexTypeConverter.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/GfshParserAutoCompletionTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/GfshParserParsingTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateIndexCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/IndexCommandsIntegrationTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/converters/IndexTypeConverterTest.java, geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshParserRule.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/IndexCommandOverHttpTest.java
This is part of the effort to add more test coverage of commands
=> GEODE-3539: refactor CreateIndexCommand and add more tests

geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/ProtobufStreamProcessor.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/utilities/ProtobufUtilities.java, geode-protobuf/src/main/proto/clientProtocol.proto, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/MessageUtil.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/acceptance/CacheConnectionJUnitTest.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/acceptance/CacheConnectionTimeoutJUnitTest.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/acceptance/CacheMaxConnectionJUnitTest.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/acceptance/CacheOperationsJUnitTest.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/acceptance/LocatorConnectionDUnitTest.java
=> GEODE-3797: Removal of CorrelationId and MessageHeader from protobuf

geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientProxyWithDeltaTest.java
* verifies that caching clients do receive delta updates
* verifies that empty clients do not receive delta updates
Please review this PR @nreich.
=> GEODE-3828: add tests for clients with use of delta

geode-core/src/main/java/org/apache/geode/internal/statistics/platform/LinuxProcFsStatistics.java, geode-core/src/main/java/org/apache/geode/internal/statistics/platform/LinuxSystemStats.java, geode-core/src/test/java/org/apache/geode/internal/statistics/LinuxSystemStatsTest.java
=> GEODE-3716 - Adding steal time metrics to Geode.

geode-core/src/test/java/org/apache/geode/cache30/MultiVMRegionTestCase.java
* testOrderedUpdates was disabled with @Ignore for unknown reason
Test is reenabled and now passes.
Reviewers + @nreich
=> GEODE-3837: fix and reenable testOrderedUpdates

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandTest.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/LocatorServerStartupRule.java, geode-junit/src/main/java/org/apache/geode/test/compiler/ClassBuilder.java
=> GEODE-3819: Refactor CreateRegionCommandDUnitTest to use gfsh rules

geode-book/config.yml, geode-book/redirects.rb
@davebarnes97 @joeymcallister @bschuchardt  Please review.
=> GEODE-3838 Roll docs to version 1.4

geode-core/src/main/java/org/apache/geode/distributed/internal/InternalLocator.java, geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpServer.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientProtocolServiceLoader.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionFactory.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/TcpServerFactory.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/ProtobufProtocolService.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/ProtobufProtocolServiceJUnitTest.java
=> GEODE-3774: moved service loader initialization to avoid double-check locking

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/membership/GMSJoinLeave.java
This solves a race condition where a second locator (started at
the same time) would fail to get a join response due to the join
request being processed prior to becoming coordinator.
Signed-off-by: Hitesh Khamesra <hiteshk25@yahoo.com>
@hiteshk25 @PivotalSarge @bschuchardt @galen-pivotal @kohlmu-pivotal 
=> GEODE-2542: Push DH keys when locator becomes coordinator

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommandDUnitTest.java
=> GEODE-2563: fix flaky test

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/GetCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/PutCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/RemoveCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DataCommandFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/FetchRegionAttributesFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/ListDiskStoresFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/ListIndexFunction.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/DataCommandFunctionJUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/DataCommandFunctionWithPDXJUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/Geode3544JUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/ListDiskStoresFunctionJUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/ListIndexFunctionJUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/result/CommandResultTest.java
This is the 4th set of updates.
Precheckin run last night was green.
=> GEODE-3299: refactor functions to get Cache from FunctionContext

geode-assembly/src/test/java/org/apache/geode/test/junit/rules/HttpClientRule.java, geode-assembly/src/test/java/org/apache/geode/tools/pulse/PulseSecurityTest.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/data/Repository.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/security/GemFireAuthentication.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/security/GemFireAuthenticationProvider.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/security/LogoutHandler.java
=> GEODE-3857: Pulse login fails after second login

geode-docs/developing/query_index/creating_hash_indexes.html.md.erb
@dihardman, also please review.
The first 2 paragraphs of the hash index description have been rewritten to more accurately represent the performance penalty.
=> GEODE-3701 Emphasize performance penalty of hash indexes in docs

geode-assembly/build.gradle, geode-protobuf/build.gradle
=> GEODE-3864: Added protobuf message file archiving

geode-core/src/main/java/org/apache/geode/admin/AdminDistributedSystem.java, geode-core/src/main/java/org/apache/geode/admin/BackupStatus.java, geode-core/src/main/java/org/apache/geode/admin/internal/AdminDistributedSystemImpl.java, geode-core/src/main/java/org/apache/geode/admin/internal/BackupStatusImpl.java, geode-core/src/main/java/org/apache/geode/internal/SystemAdmin.java, geode-core/src/main/java/org/apache/geode/internal/cache/BackupUtil.java, geode-core/src/main/java/org/apache/geode/management/BackupStatus.java, geode-core/src/main/java/org/apache/geode/management/DiskBackupStatus.java, geode-core/src/main/java/org/apache/geode/management/internal/BackupStatusImpl.java, geode-core/src/main/java/org/apache/geode/management/internal/DiskBackupStatusImpl.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/DistributedSystemBridge.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/BackupDiskStoreCommand.java, geode-core/src/test/java/org/apache/geode/internal/cache/BackupDUnitTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/IncrementalBackupDUnitTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/PersistentPartitionedRegionTestBase.java, geode-core/src/test/java/org/apache/geode/management/DiskBackupStatusTest.java, geode-core/src/test/java/org/apache/geode/management/DiskManagementDUnitTest.java, geode-core/src/test/resources/org/apache/geode/codeAnalysis/excludedClasses.txt
This pull request tries to better standardize across the product how disk store backups get done, moving code out of deprecated locations and into places where logic can be easier unit tested.
@dschneider-pivotal 
@kirklund 
@lgallinat 
@agingade 
@pivotal-eshu
=> GEODE-3719: Improve invocations of disk store backups

geode-lucene/src/main/java/org/apache/geode/cache/lucene/FlatFormatSerializer.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/FlatFormatPdxSerializerJunitTest.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/FlatFormatSerializerJUnitTest.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/LocalCacheRule.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/NestedObjectSeralizerIntegrationTest.java
@upthewaterspout @boglesby @jhuynh1 
=> GEODE-3245: Flattening LuceneSerializer should support PDX values

geode-core/src/test/java/org/apache/geode/cache/query/internal/index/InitializeIndexEntryDestroyQueryDUnitTest.java
* Sleeps replaced with awaitility clauses
* Removed redundant code and tests
* Clearing the index and region when the test ends.
* Reduced the number of loops so that the test end quicker than before.
=> GEODE-1036: Refactored InitializeIndexEntryDestroyQueryDUnitTest

geode-core/src/test/java/org/apache/geode/cache/query/dunit/CorruptedIndexIntegrationTest.java
* Additional asserts added to make sure that no new entries are added to a corrupted index.
=> GEODE-3520: Additional asserts.

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ShutdownCommand.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/GfshParserParsingTest.java
=> GEODE-3843 gfsh shutdown error message suggests non-existent option

geode-lucene/src/main/java/org/apache/geode/cache/lucene/LuceneSerializer.java
=> GEODE-3908: Fixed the javadoc issue with LuceneSerializer.java

geode-core/src/test/java/org/apache/geode/internal/io/MainWithChildrenRollingFileHandlerDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ExportLogsOnServerManagerDUnit.java, geode-core/src/test/java/org/apache/geode/management/internal/configuration/ClusterConfig.java, geode-core/src/test/java/org/apache/geode/security/PDXGfshPostProcessorOnRemoteServerTest.java, geode-core/src/test/java/org/apache/geode/security/SecurityWithoutClusterConfigDUnitTest.java, geode-core/src/test/java/org/apache/geode/security/StartServerAuthorizationTest.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/LocatorServerStartupRule.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/MemberVM.java
=> GEODE-3910: Simplify MemberVM - remove generic type

geode-lucene/src/main/java/org/apache/geode/cache/lucene/LuceneSerializer.java
=> GEODE-3896: Remove Experimental tag from LuceneSerializer

geode-core/src/test/java/org/apache/geode/test/dunit/rules/LocatorServerStartupRule.java
=> GEODE-3914: Allow gfsh test rules to use more than 4 VMs

geode-core/src/main/java/org/apache/geode/cache/query/Query.java
=> GEODE-3909: Use varargs for Query.execute

geode-core/src/test/java/org/apache/geode/security/ClientDestroyInvalidateAuthDUnitTest.java
=> GEODE-3902: Wait for all async invoked commands to complete

geode-wan/src/test/java/org/apache/geode/internal/cache/wan/misc/WanAutoDiscoveryDUnitTest.java
=> GEODE-3899: add expected exception for possible race condition

geode-core/src/test/java/org/apache/geode/security/ClientDestroyInvalidateAuthDUnitTest.java
=> GEODE-3902: Correct region used by test

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandIntegrationTest.java, geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshShellConnectionRule.java
- [ x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?
- [x ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?
- [ x] Does `gradlew build` run cleanly?
- [ x] Have you written or updated unit tests to verify your changes?
- [ x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
Please ensure that once the PR is submitted, you check …
=> GEODE-3872: Remove executeAndVerify method

geode-core/src/test/java/org/apache/geode/distributed/LocatorLauncherRemoteIntegrationTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/DeprecatedCacheServerLauncherIntegrationTest.java, geode-core/src/test/java/org/apache/geode/internal/process/FileProcessControllerIntegrationTest.java
=> GEODE-3778: mark tests flaky

ci/pipelines/docker-images.yml, ci/pipelines/meta.yml
=> Fix up branches. GEODE-3942

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/AcceptorImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java, geode-core/src/test/java/org/apache/geode/internal/SSLConfigJUnitTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/AcceptorImplClientQueueDUnitTest.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/CacheRule.java
=> GEODE-3637: Moved client queue initialization into the ServerConnection.java

geode-core/src/main/java/org/apache/geode/distributed/internal/tcpserver/TcpServer.java, geode-core/src/main/java/org/apache/geode/internal/cache/client/protocol/ClientProtocolService.java, geode-core/src/main/java/org/apache/geode/internal/cache/client/protocol/ClientProtocolServiceLoader.java, geode-core/src/main/java/org/apache/geode/internal/cache/client/protocol/exception/ServiceLoadingFailureException.java, geode-core/src/main/java/org/apache/geode/internal/cache/client/protocol/exception/ServiceVersionNotFoundException.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionFactory.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionFactoryTest.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/ProtobufProtocolService.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/AuthenticationIntegrationTest.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/AuthorizationIntegrationTest.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/HandshakeIntegrationTest.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/acceptance/CacheConnectionJUnitTest.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/acceptance/CacheConnectionTimeoutJUnitTest.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/acceptance/CacheMaxConnectionJUnitTest.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/acceptance/CacheOperationsJUnitTest.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/acceptance/LocatorConnectionDUnitTest.java
@galen-pivotal @PivotalSarge @kohlmu-pivotal @bschuchardt 
Signed-off-by: Galen O'Sullivan <gosullivan@pivotal.io>
=> GEODE-3895: Add Handshake/Message version byte

ci/scripts/build.sh
[GEODE-3942]
Please ensure that once the PR is …
=> Fix version number in email subject.

geode-assembly/src/test/java/org/apache/geode/tools/pulse/PulseSecurityIntegrationTest.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/LocatorMBeanBridge.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/data/JMXDataUpdater.java, geode-pulse/src/main/webapp/WEB-INF/spring-security.xml
- Pulse UI is not updated correctly - missing servers for ex.
- NPE regarding JMXUpdater in pulse.log
=> GEODE-3941: Pulse issues when SecurityManager is enabled

geode-assembly/build.gradle, geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/PutCommandWithJsonTest.java
add the dependency in build.gradle and added an acceptance test to verify the fix.
=> GEODE-3947: add the necessary dependency in geode-dependency.jar

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyIndexCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/domain/IndexInfo.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DestroyIndexFunction.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyIndexCommandsDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/IndexCommandsIntegrationTest.java, geode-core/src/test/resources/org/apache/geode/codeAnalysis/sanctionedSerializables.txt
=> GEODE-2566: Add --if-exists option to destroy index

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyIndexCommandsDUnitTest.java
=> GEODE-2566 Missed merge issues

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientProxy.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientInterestMessageImpl.java
Now the DistributedSystem is passed in to the constructor.
=> GEODE-3591: remove getAnyInstance call

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommandTest.java, geode-core/src/test/java/org/apache/geode/test/junit/assertions/CommandResultAssert.java, geode-core/src/test/java/org/apache/geode/test/junit/assertions/CommandResultExecution.java, geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshParserRule.java, geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshShellConnectionRule.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsDUnitTest.java
=> GEODE-3872: simplify the Command result Assert

.travis.yml
=> GEODE-3970: Remove default Travis _JAVA_OPTIONS

geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneSearchWithRollingUpgradeDUnit.java
=> GEODE-3920: Added test to validate lucene 6 to 7 upgrade

geode-core/src/main/java/org/apache/geode/management/internal/cli/CliUtil.java
This cleans up a build warning.
=> GEODE-3539: Correct typo in javadoc annotation

geode-core/src/test/java/org/apache/geode/security/ClientAuthorizationDUnitTest.java
=> GEODE-3738: Add Flaky category to ClientAuthorizationDUnitTest

geode-assembly/build.gradle, geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StatusLocatorRealGfshTest.java, geode-assembly/src/test/resources/expected_jars.txt, geode-core/build.gradle, geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java, geode-core/src/main/java/org/apache/geode/distributed/internal/AbstractDistributionConfig.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfigImpl.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/MemberMBeanBridge.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/CommandManager.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/GfshParser.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/help/Helper.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/remote/MemberCommandService.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/remote/OnlineCommandProcessor.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/util/ClasspathScanLoadHelper.java, geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionConfigJUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/ClasspathScanLoadHelperJUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/CommandManagerJUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CliCommandTestBase.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/remote/OnlineCommandProcessorTest.java, geode-core/src/test/resources/META-INF/services/org.springframework.shell.core.CommandMarker, geode-lucene/src/main/resources/META-INF/services/org.springframework.shell.core.CommandMarker
=> GEODE-3007: Simplify support for custom GFSH commands

geode-wan/src/test/java/org/apache/geode/internal/cache/wan/misc/WanAutoDiscoveryDUnitTest.java
* More logs were added at the failure points to figure out what caused a failure.
* Refactored by simplifying the code and removing deprecated function calls.
* Removed the flaky tag
=> GEODE-1920 Addition of more logs to the test

geode-wan/src/test/java/org/apache/geode/internal/cache/wan/misc/WanAutoDiscoveryDUnitTest.java
=> Revert "GEODE-1920 Addition of more logs to the test"

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/RegionCreateFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandIntegrationTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/TestObjectSizerNotDeclarable.java
- Minor acceptance test updates
=> GEODE-1897: Ensure that eviction-object-sizer also implements Declarable

geode-assembly/build.gradle, geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StatusLocatorRealGfshTest.java, geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java, geode-core/src/main/java/org/apache/geode/distributed/internal/AbstractDistributionConfig.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfigImpl.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/MemberMBeanBridge.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/CommandManager.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/GfshParser.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/help/Helper.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/remote/MemberCommandService.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/remote/OnlineCommandProcessor.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/util/ClasspathScanLoadHelper.java, geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionConfigJUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/ClasspathScanLoadHelperJUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/CommandManagerJUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CliCommandTestBase.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/remote/OnlineCommandProcessorTest.java, geode-core/src/test/resources/META-INF/services/org.springframework.shell.core.CommandMarker, geode-lucene/src/main/resources/META-INF/services/org.springframework.shell.core.CommandMarker
This reverts commit 0e5dd6ba45519463147337c8265db15e8f1840fc.
=> Revert "GEODE-3007: Simplify support for custom GFSH commands (#1042)"

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyDiskStoreCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DestroyDiskStoreFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/json/GfJsonObject.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/result/CommandResult.java, geode-core/src/test/java/org/apache/geode/internal/cache/SnapshotTestUtil.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListIndexCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/LocatorServerStartupRule.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/MemberVM.java, geode-core/src/test/java/org/apache/geode/test/junit/assertions/CommandResultAssert.java, geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshCommandRule.java, geode-core/src/test/java/org/apache/geode/test/junit/rules/MemberStarterRule.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/CommandOverHttpDUnitTest.java
=> GEODE-3341: Convert DiskStoreCommandsDUnitTest to use gfsh rules

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyDiskStoreCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DestroyDiskStoreFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DestroyDiskStoreFunctionArgs.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DiskStoreCommandsDUnitTest.java
=> GEODE-2567: Add --if-exists to destroy disk-store

geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandIntegrationTest.java, geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartServerCommandIntegrationTest.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/remote/CommandExecutor.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/remote/CommandExecutorTest.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/LocatorServerStartupRule.java, geode-core/src/test/java/org/apache/geode/test/junit/assertions/CommandResultAssert.java, geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshParserRule.java
* Enhance the rule to invoke executor to better mimic a true gfsh execution.
=> GEODE-3788: GfshParserRule enhancement

geode-protobuf/src/main/proto/v1/basicTypes.proto, geode-protobuf/src/main/proto/v1/clientProtocol.proto
@galen-pivotal @kohlmu-pivotal @bschuchardt @PivotalSarge 
=> GEODE-3969: Remove CallbackArgs from protobuf requests

geode-core/src/test/java/org/apache/geode/security/ClientAuthenticationTestCase.java
=> GEODE-1683: fix ClientAuthenticationDUnitTest intermittent failures

geode-docs/developing/partitioned_regions/colocating_partitioned_region_data.html.md.erb, geode-docs/developing/partitioned_regions/custom_partitioning_and_data_colocation.html.md.erb, geode-docs/developing/partitioned_regions/overview_custom_partitioning_and_data_colocation.html.md.erb, geode-docs/developing/partitioned_regions/using_custom_partition_resolvers.html.md.erb
This section on custom partition resolvers has been substantially revised.  Please review carefully to make sure it is technically correct.
=> GEODE-3063 partition resolver doc revisions

geode-docs/developing/partitioned_regions/colocating_partitioned_region_data.html.md.erb, geode-docs/developing/partitioned_regions/custom_partitioning_and_data_colocation.html.md.erb, geode-docs/developing/partitioned_regions/overview_custom_partitioning_and_data_colocation.html.md.erb, geode-docs/developing/partitioned_regions/using_custom_partition_resolvers.html.md.erb
Reverts apache/geode#1077
Accidentally squashed and merged the wrong PR, so this PR will be used to undo the incorrect squash/merge.
=> Revert "GEODE-3063 partition resolver doc revisions"

geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb, geode-docs/tools_modules/lucene_integration.html.md.erb
gfsh create lucene index
Please review.
=> GEODE-3242 Update docs with new --serializer option for

geode-core/src/test/java/org/apache/geode/management/internal/configuration/ImportClusterConfigDistributedTest.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/LocatorServerStartupRule.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/MemberVM.java
=> GEODE-3539: add ability to stop a vm without clean out the working dir

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneIndexCreationProfile.java, geode-old-versions/build.gradle
@nabarunnag @jhuynh1 @boglesby @upthewaterspout 
=> GEODE-4000: The serializerClass is actually introduced in 1.4 not 1.3.

geode-docs/developing/eviction/configuring_data_eviction.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb
Document gfsh create region options for configuring eviction.
=> GEODE-1897 Docs:  configure eviction through gfsh

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DeployCommandRedeployDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/configuration/ClusterConfigDeployJarDUnitTest.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/LocatorServerStartupRule.java
=> GEODE-3539: enhance rule to start locator joining other locators

ci/docker/Dockerfile, ci/docker/docker.list, ci/docker/initdocker, ci/docker/tini-wrapper.go, ci/pipelines/develop.yml, ci/pipelines/docker-images.yml, ci/scripts/build.sh, ci/scripts/test-archive.sh, ci/scripts/test-run.sh
* Add support for running DUnit tests in concourse.
* Add scripts to run and archive test results.
* Add concourse jobs for FlakyTest, IntegrationTest, DistributedTest and
AcceptanceTest.
[GEODE-4023] …
=> GEODE-4023: Add precheckin tests to pipeline.

geode-core/src/test/java/org/apache/geode/security/ClientAuthorizationTestCase.java
=> GEODE-1683: fix ClientAuthorizationDUnit test failures

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeDiskStoreCommandIntegrationTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListDiskStoreCommandIntegrationTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListMembersCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListRegionDUnitTest.java, geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshCommandRule.java
* reduce the default timeout
* add ability to configure the timeout at construction time.
=> GEODE-3539: enhance GfshCommandRule

geode-core/src/test/java/org/apache/geode/security/ClientAuthorizationDUnitTest.java
=> GEODE-1683: temp trial to fix clientAuthorizationDUnitTest

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CommandAvailabilityIndicator.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/help/Helper.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CommandAvailabilityIndicatorTest.java
=> GEODE-3788: add availability indicator for alter aeq command

geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb, geode-docs/tools_modules/lucene_integration.html.md.erb
Also made changes to accommodate nested indexes.
=> GEODE-3241 User can set a LuceneSerializer through XML

geode-protobuf-messages/src/main/proto/v1/clientProtocol.proto, geode-protobuf-messages/src/main/proto/v1/region_API.proto
RemoveAll was never implemented for the new protocol. Removing the message.
@PivotalSarge @WireBaron @galen-pivotal
=> GEODE-4068: Removing RemoveAll from .proto files

geode-core/src/test/java/org/apache/geode/test/dunit/internal/JUnit4DistributedTestCase.java
=> GEODE-4074: Cleanup of PdxSerializers in TypeRegistry

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientUserAuths.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java, geode-core/src/main/java/org/apache/geode/internal/security/IntegratedSecurityService.java, geode-core/src/test/java/org/apache/geode/management/internal/security/MultiClientDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/security/MultiGfshDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/security/MultiUserAuthenticationDUnitTest.java
* added more logging in Client's subject binding/removing
* added more tests for multi-clients and muti-user-authentication mode.
=> GEODE-4076: throw AuthenticationRequiredException instead of GemfireSecurityException

geode-core/src/main/java/org/apache/geode/distributed/internal/ProductUseLog.java
=> GEODE-4078: Display full path when locator view log cannot be opened

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateGatewayReceiverCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateGatewaySenderCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyGatewaySenderCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/GatewaySenderDestroyFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateAsyncEventQueueCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateAsyncEventQueueCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateGatewayReceiverCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateGatewaySenderCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyGatewaySenderCommandTest.java, geode-core/src/test/java/org/apache/geode/test/junit/assertions/CommandResultAssert.java, geode-wan/src/test/java/org/apache/geode/internal/cache/wan/wancommand/CreateDestroyGatewaySenderCommandDUnitTest.java
This is built on top of PR 1127. Only the last commit's content is for this PR.
=>  GEODE-4081: update cluster config after destroy gateway sender 

geode-core/src/main/java/org/apache/geode/management/RegionAttributesData.java, geode-core/src/test/java/org/apache/geode/management/internal/beans/RegionMBeanAttributesTest.java
=> GEODE-3956: Consistent naming for async event queue related variables

geode-core/src/main/java/org/apache/geode/internal/cache/versions/RegionVersionVector.java, geode-core/src/test/java/org/apache/geode/internal/cache/versions/RegionVersionVectorTest.java
=> GEODE-4083: fix infinite loop caused by thread race changing version

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/Size.java
=> GEODE-2296: Internal message SIZE should not have authorization checks

gradle/test.gradle
=> GEODE-4103: Set forkEvery=1 for distributedTest

geode-core/src/test/java/org/apache/geode/internal/cache/ClientServerTransactionDUnitTest.java
=> GEODE-4088: add a dunit test to show the client region keySet() in TX

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListMembersCommandDUnitTest.java
'list member' now shows the coordinator
- [] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?
=> GEODE-4061: Updated DUnit test for changes in list member command

ci/pipelines/develop.yml, ci/scripts/test-archive.sh, ci/scripts/test-run.sh
When the pipeline fails, the email subject contains the pipeline name
and the job name.
Signed-off-by: Robert Houghton <rhoughton@pivotal.io>
=> [GEODE-4123] - Improve output email of concourse.apachegeodeci.info

geode-book/master_middleman/source/subnavs/geode-subnav.erb, geode-docs/tools_modules/gfsh/command-pages/alter.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb
See http://aeq-review.cfapps.io/docs/guide/14/tools_modules/gfsh/command-pages/alter.html#topic_alter_async_event_queue for a compiled draft.
=> GEODE-3788 alter async event queue attributes (document this feature)

geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java
=> GEODE-4124: Move the memory units to the heap flag.

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneCreateIndexFunction.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneDescribeIndexFunction.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneListIndexFunction.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneSearchIndexFunction.java, geode-lucene/src/main/resources/org/apache/geode/internal/sanctioned-geode-lucene-serializables.txt
* This commit is specific to geode-lucene only
* Before making any changes serialVersionUID was generated for the files which were to be modified.
* The FunctionAdapters were replaced with Function
=> GEODE-4112: Replaced FunctionAdapter with Function

geode-core/src/test/java/org/apache/geode/internal/cache/ha/HASlowReceiverDUnitTest.java
=> Replaced WaitCriterion and Thread.sleep() with Awaitility.await().

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyAsyncEventQueueCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DestroyAsyncEventQueueFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DestroyAsyncEventQueueFunctionArgs.java, geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyAsyncEventQueueCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyAsyncEventQueueCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/DestroyAsyncEventQueueFunctionTest.java
New classes added for the Command, Function and FunctionArgs
New test classes added for DUnit and Unit tests
Command supports --if-exists option for idempotency
=> GEODE-2665: Add Gfsh command to delete async event queues

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientHealthMonitor.java
Add generics and make some things private while I'm at it. eventually maybe we can fix GEODE-2678.
- [I don't think this is necessary, be] Have you written or updated unit tests to verify your changes?
@WireBaron @PivotalSarge
=> GEODE-4133: synchronize `ClientHealthMonitor.getClientHeartbeats`

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/StartMemberUtilsTest.java
=> GEODE-4097: Adding a test for this change

geode-book/master_middleman/source/subnavs/geode-subnav.erb, geode-docs/developing/querying_basics/chapter_overview.html.md.erb, geode-docs/developing/querying_basics/query_basics.html.md.erb
=> GEODE-4170: Index docs are easier to locate

ci/pipelines/develop.yml, ci/scripts/update-passing-ref.sh
The endpoint is http://files.apachegeode-ci.info/passing.txt
[GEODE-4185] …
=> Add job to update file in GCS with SHA that passed all tests.

geode-core/src/test/java/org/apache/geode/management/bean/stats/GatewayMBeanBridgeJUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateAsyncEventQueueCommandTest.java, geode-cq/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscBCDUnitTest.java
=> GEODE-4191: Replace imports of io.codearte..Mockito with org.mockito.Mockito

geode-core/src/main/java/org/apache/geode/management/MemberMXBean.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/MemberMBean.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/CliUtil.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/CliUtilTest.java
=> GEODE-4131: add the deprecated API in MemberMXBean

geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/DeployWithLargeJarTest.java
=> GEODE-4131: reduce flakiness of the added acceptance test

geode-docs/managing/heap_use/heap_management.html.md.erb
=> GEODE-4230: fixed the heap example

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListAsyncEventQueuesCommandDUnitTest.java
=> GEODE-3539: fix test category

ci/docker/Dockerfile
This will allow us to analyze hangs in ci jobs. …
=> [GEODE-4265] Add dunit progress tool to docker image.

geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/JdbcDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ExportLogsDUnitTest.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/MemberVM.java
=> GEODE-3539: Rule cleanup. delete all files in the workingDir when cleaning up MemberVM

ci/pipelines/develop.yml, ci/scripts/build-examples.sh
* TestExamples checks out the geode-examples repo and runs tests against
it. …
=> [GEODE-4274] Add TestExamples job.

geode-core/src/main/java/org/apache/geode/management/MemberMXBean.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/MemberMBean.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/MemberMBeanBridge.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ConnectCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/converters/ConnectionEndpointConverter.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/shell/JmxOperationInvoker.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/shell/OperationInvoker.java, geode-core/src/main/java/org/apache/geode/management/internal/web/controllers/ShellCommandsController.java, geode-core/src/main/java/org/apache/geode/management/internal/web/shell/HttpOperationInvoker.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ConnectCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ConnectCommandTest.java, geode-core/src/test/java/org/apache/geode/test/dunit/standalone/VersionManager.java
=> GEODE-3946: add version check when connect to cluster using gfsh

geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/GfshScript.java
to avoid false failures on slow machines
=> GEODE-4236: Increase default timeout for await methods

ci/pipelines/develop.yml
=> [GEODE-4279] Add tag to DistributedTest so it runs on a different worker class.

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneCreateIndexFunction.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneDescribeIndexFunction.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneDestroyIndexFunction.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneListIndexFunction.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneSearchIndexFunction.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/directory/DumpDirectoryFiles.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/distributed/LuceneQueryFunction.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/distributed/WaitUntilFlushedFunction.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/results/LuceneGetPageFunction.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/test/LuceneFunctionSecurityTest.java
=> GEODE-3974: Improve permissions for geode-lucene functions

geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandTest.java, geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartServerCommandTest.java, geode-core/src/main/java/org/apache/geode/internal/OSProcess.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartServerCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java, geode-core/src/test/java/org/apache/geode/distributed/LocatorLauncherBuilderTest.java, geode-core/src/test/java/org/apache/geode/distributed/ServerLauncherBuilderTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/GfshParserAutoCompletionTest.java, geode-pulse/build.gradle, geode-web-api/build.gradle
To avoid major code changes the start commands check the new flag and
set as `true` a new system property, `DISABLE_REDIRECTION_CONFIGURATION`,
which disables the other two (now deprecated) properties. In the next
major release, the properties and the related logic should be deleted.
The integration between log4j2 and geode-pulse was also incomplete.
When ran in embedded mode, some messages were totally swallowed and the
actual logging was split between the member's log and pulse.log file.
- Added flag `--redirect-ouput` to `StartServerCommand`.
- Added flag `--redirect-ouput` to `StartLocatorCommand`.
- Added tests to verify the behavior of the commands/builders.
- Added `OSProcess.DISABLE_REDIRECTION_CONFIGURATION` internal property.
- Property `OSProcess.ENABLE_OUTPUT_REDIRECTION` …
=> GEODE-4101: Add --redirect-output flag to GFSH

build.gradle
=> GEODE-4286: Use canonical path for docker mounted volumes

extensions/geode-modules/src/test/java/org/apache/geode/modules/util/ModuleFunctionsSecurityTest.java, geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/JDBCConnectorFunctionsSecurityTest.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ExecuteFunctionCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/UserFunctionExecution.java, geode-core/src/test/java/org/apache/geode/internal/cache/functions/TestFunction.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ExecuteFunctionCommandSecurityTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/FunctionCommandsDUnitTest.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/test/LuceneFunctionSecurityTest.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/ExecuteFunctionCommandWithSecurityDUnitTest.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/FunctionCommandsOverHttpDUnitTest.java
- Also produce tabulated output
=> GEODE-4252: User function execution produces correct errors

geode-core/src/main/java/org/apache/geode/distributed/ServerLauncher.java
=> GEODE-4298: Restore public access to StartServer method.

geode-core/src/main/java/org/apache/geode/management/internal/security/ResourcePermissions.java, geode-core/src/test/java/org/apache/geode/management/internal/security/ResourcePermissionTest.java
* Slight correction of test logic.
---
- [n/a - testing issue] Have you written or updated unit tests to verify your changes?
=> GEODE-4303: Add assertions to nil test.

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DeployWithGroupsDUnitTest.java
- Ensure that undeployed function remain gone after server restart.
=> GEODE-4316: Additional function deploy tests

geode-docs/getting_started/15_minute_quickstart_gfsh.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/list.html.md.erb, geode-docs/tools_modules/gfsh/tour_of_gfsh.html.md.erb
include membership coordinator in the output
@bschuchardt @upthewaterspout @davebarnes97 @joeymcallister Please review to make sure the new output and explanation of
gfsh list members
looks correct for the addition of the membership coordinator.
=> GEODE-4061 Update docs output for gfsh list members;

geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/RegisterInterestKeysDUnitTest.java, geode-wan/src/test/java/org/apache/geode/internal/cache/wan/CacheClientNotifierDUnitTest.java
=> GEODE-4251: Removed the 2 second client timeout from the test

geode-core/src/main/java/org/apache/geode/internal/cache/ha/HARegionQueue.java, geode-core/src/test/java/org/apache/geode/internal/cache/ha/HARegionQueueTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ConflationDUnitTest.java
=> GEODE-4015: Rewrite queue conflation tests

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ShutdownCommandDUnitTest.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/ShutdownCommandOverHttpDUnitTest.java
=> GEODE-4138: Move http related test to geode-web

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/QueryCommandTest.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/QueryCommandOverHttpTest.java
=> GEODE-4136: Move http related test to geode-web

geode-core/src/main/java/org/apache/geode/internal/cache/EntryEventImpl.java, geode-core/src/test/java/org/apache/geode/internal/cache/EntryEventImplTest.java
=> GEODE-4306: Added concurrent checks enabled test to event time

geode-core/src/main/java/org/apache/geode/cache/client/internal/QueueConnectionImpl.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/QueueManagerImpl.java, geode-core/src/test/java/org/apache/geode/cache/client/internal/QueueConnectionImplJUnitTest.java
=> GEODE-4358: Added check for null updater

geode-core/src/main/java/org/apache/geode/management/internal/GeodeRemoteStreamExporter.java, geode-core/src/main/java/org/apache/geode/management/internal/ManagementAgent.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DeployCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/functions/DownloadJarFunction.java
=> GEODE-4370: Ensure that rmi-io uses the JMX/RMI port

geode-lucene/src/test/java/org/apache/geode/cache/lucene/RebalanceWithRedundancyDUnitTest.java
=> GEODE-4223: Test now waits until internal lucene regions are ready

geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/JdbcAsyncWriterTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/EvictionAttributesMutatorImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalDistributedRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/LatestLastAccessTimeMessage.java, geode-core/src/main/java/org/apache/geode/internal/cache/LatestLastAccessTimeOperation.java, geode-core/src/main/java/org/apache/geode/internal/cache/RegionStatus.java, geode-core/src/main/java/org/apache/geode/internal/cache/VMCachedDeserializable.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/MemberMBeanBridge.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/RegionMBeanBridge.java, geode-core/src/test/java/org/apache/geode/internal/cache/CacheWriterGetOldValueIntegrationTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/DeltaFaultInDUnitTest.java
=> GEODE-4369: remove generics from InternalRegion and InternalDistributedRegion

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/RegionCreateFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/RegionFunctionArgs.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java, geode-core/src/main/java/org/apache/geode/redis/internal/RegionProvider.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/GfshParserAutoCompletionTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandIntegrationTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandTest.java
- This supercedes and deprecates --skip-if-exists
=> GEODE-4354: Add --if-not-exists option to create region

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/AcceptorImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifier.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientHealthMonitor.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/HandShake.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionCollection.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerHandShakeProcessor.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionTest.java
- minor refactoring of AcceptorImpl and Handshake to improve testability
- added a unit test to demonstrate race condition
- refactored connection map into a new object to prevent race
=> GEODE-4094: ClientHealthMonitor may cause an NPE in a ServerConnection

geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/GMSEncrypt.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/gms/messenger/GMSEncryptJUnitTest.java
This includes removal of code that does not test `GMSEncrypt` and renaming of variables for clarity.
=> GEODE-4417: Remove support for DES.

ci/pipelines/develop.yml
@upthewaterspout @rhoughton-pivot @smgoller
=> GEODE-4380: Trigger build of geode-examples off geode success.

geode-core/src/test/java/org/apache/geode/internal/cache/ha/HARegionQueueDUnitTest.java
* Removed sleep
* Added check that each thread has done at least one operation
=> GEODE-4219: Test will properly shutdown listeners

ci/pipelines/develop.yml, ci/scripts/capture-call-stacks.sh, ci/scripts/test-run.sh
=> [GEODE-4371] Add callstack tracing to CI jobs

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeRegionCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/domain/RegionDescriptionPerMember.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeRegionDUnitTest.java
Fixed describe region to return region descriptions from all members
that host the region and from accessors(if any).
=> GEODE-4373: gfsh 'describe region' not showing accessor region description

geode-core/src/main/java/org/apache/geode/cache/client/internal/PoolImpl.java, geode-core/src/main/java/org/apache/geode/cache/query/QueryService.java, geode-core/src/main/java/org/apache/geode/internal/cache/PoolFactoryImpl.java, geode-core/src/main/java/org/apache/geode/internal/i18n/LocalizedStrings.java
=> GEODE-3966: Avoid singletons by passing distributed system and cache.

geode-core/src/main/java/org/apache/geode/internal/DSFIDFactory.java, geode-core/src/main/java/org/apache/geode/internal/DataSerializableFixedID.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/AbortBackup.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/AbortBackupFactory.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/AbortBackupOperation.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/AbortBackupRequest.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupDataStoreHelper.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupResponse.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupService.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupTask.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/FinishBackupFactory.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/MemberMBeanBridge.java, geode-core/src/test/java/org/apache/geode/internal/cache/backup/AbortBackupFactoryTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/backup/AbortBackupOperationTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/backup/AbortBackupRequestTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/backup/BackupDistributedTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/backup/BackupIntegrationTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/backup/BackupPrepareAndFinishMsgDUnitTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/backup/BackupServiceTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/backup/FinishBackupFactoryTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/backup/FinishBackupOperationTest.java, geode-core/src/test/java/org/apache/geode/management/internal/beans/DistributedSystemBridgeJUnitTest.java, geode-core/src/test/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
Abort was previously part of the FinishBackup message.
=> GEODE-4442: Move abort of backups to separate message

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/AlterCompressorDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/TestCompressor1.java
Added a new DUnit to test adding and removing a compressor to an
existing persistent region.
=> GEODE-4499: Test adding a compressor to an existing persistent region.

geode-core/src/main/java/org/apache/geode/internal/cache/eviction/EvictionListBuilder.java, geode-core/src/main/java/org/apache/geode/internal/cache/eviction/LRUListWithAsyncSorting.java, geode-core/src/main/java/org/apache/geode/internal/lang/SystemPropertyHelper.java, geode-core/src/test/java/org/apache/geode/internal/cache/eviction/EvictionListBuilderTest.java, geode-core/src/test/java/org/apache/geode/internal/lang/SystemPropertyHelperTest.java
* This replaces the previous LRUListWithSyncSorting as the default for
eviction and also removes the experimental tag for its parameters
=> GEODE-4598: Make LRUListWithAsyncSorting the default eviction list

ci/docker/Dockerfile, ci/scripts/capture-call-stacks.sh
* Fix directory in which find is executed
* Adjust docker image to name dunit-progress properly
Signed-off-by: Vince Ford <vford@pivotal.io>
- [ N/A ] If adding new dependencies to the code, are these dependencies licensed in a way that is …
=> [GEODE-4616] Fix capture_call_stacks.sh

ci/scripts/test-archive.sh
=> [GEODE-4616] Final update for collecting artifacts.

ci/docker/Dockerfile, ci/pipelines/docker-images.yml
=> [GEODE-4623] Use openjdk:8 for base docker image.

geode-core/src/test/java/org/apache/geode/cache/query/internal/types/TypeUtilsJUnitTest.java
=> GEODE-4631: need a public class to mock

geode-core/src/main/java/org/apache/geode/internal/cache/DiskRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java, geode-core/src/test/java/org/apache/geode/internal/cache/DiskStoreImplIntegrationTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/FlusherThreadTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/OplogFlushTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/OplogJUnitTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/SimpleDiskRegionJUnitTest.java
Most of these changes are to get the flusher thread under test. The fix is just moving where the queueSize stat is updated.
=> GEODE-4435 Move queueSize stat increment to after writing to disk.

geode-core/src/test/java/org/apache/geode/security/ClientDataAuthorizationUsingLegacySecurityDUnitTest.java, geode-core/src/test/java/org/apache/geode/security/ClientDataAuthorizationUsingLegacySecurityWithFailoverDUnitTest.java, geode-old-versions/build.gradle
=> Adding 1.4.0 as an old version to test against

geode-core/src/main/java/org/apache/geode/cache/client/ClientCacheFactory.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/ClientRegionFactoryImpl.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/InternalClientCache.java, geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/PoolFactoryImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/xmlcache/ClientCacheCreation.java, geode-core/src/test/java/org/apache/geode/cache/client/ClientCacheFactoryJUnitTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscDUnitTest.java, geode-core/src/test/java/org/apache/geode/security/ClientAuthDUnitTest.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java
=> GEODE-4511: Switch to lazy initialization of the default pool.

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ClientHealthMonitor.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientHealthMonitorIntegrationTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientHealthMonitorJUnitTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientHealthMonitorSelectorIntegrationTest.java
- renamed ClientHealthMonitorJUnitTest to ClientHealthMonitorIntegrationTest
- added new ClientHealthMonitorJUnitTest
=> GEODE-3616: Clean up ClientHealthMonitorJUnitTest

geode-core/src/main/java/org/apache/geode/internal/admin/remote/ShutdownAllRequest.java
=> remove getInstance calls in ShutdownAllRequest

geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java
=> GEODE-4645: Update help string for create region --if-not-exists

geode-core/src/main/java/org/apache/geode/internal/cache/MemberFunctionStreamingMessage.java
=> GEODE-3974: revert a change to log the exception in the server logs

geode-book/config.yml, geode-docs/configuring/cluster_config/persisting_configurations.html.md.erb, geode-docs/configuring/running/running_the_locator.html.md.erb, geode-docs/getting_started/15_minute_quickstart_gfsh.html.md.erb, geode-docs/getting_started/system_requirements/host_machine.html.md.erb, geode-docs/managing/management/jmx_manager_operations.html.md.erb, geode-docs/tools_modules/gfsh/tour_of_gfsh.html.md.erb, geode-docs/tools_modules/http_session_mgmt/tc_additional_info.html.md.erb, geode-docs/tools_modules/http_session_mgmt/tc_setting_up_the_module.html.md.erb, geode-docs/tools_modules/http_session_mgmt/weblogic_setting_up_the_module.html.md.erb
- Use a variable to represent the minimum update value
- Explicitly state the minimum update value in the host requirements
=> GEODE-4649 Specify minimum java update version

geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/PoolManagerImpl.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/RegisterInterestIntegrationTest.java
=> GEODE-4511: Ensure a pool is available for durable client subscription.

geode-core/src/test/java/org/apache/geode/internal/cache/DiskRegionJUnitTest.java
=> GEODE-4655: Use smaller eviction limit to avoid async scanning.

geode-core/src/main/java/org/apache/geode/cache/query/internal/DefaultQueryService.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/ExecutionContext.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/QueryMonitor.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/AbstractIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/AbstractMapIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/CompactMapRangeIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/CompactRangeIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/HashIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/IndexManager.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/IndexUtils.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/MapRangeIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/PartitionedIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/PrimaryKeyIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/RangeIndex.java, geode-core/src/main/java/org/apache/geode/internal/cache/EntryEventImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/control/HeapMemoryMonitor.java, geode-core/src/test/java/org/apache/geode/cache/query/dunit/ResourceManagerWithQueryMonitorDUnitTest.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/index/DeclarativeIndexCreationJUnitTest.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/index/IndexCreationInternalsJUnitTest.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/index/NewDeclarativeIndexCreationJUnitTest.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/index/PartitionedIndexJUnitTest.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/index/ProgRegionCreationIndexUpdateTypeJUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/dunit/QueryMonitorDUnitTest.java
* Also removed test variables from product code
* Tests will now set a property that allows tests to test query cancellation
=> GEODE-4476: Remove getInstance() calls from org.apache.geode.cache.query

geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqDataUsingPoolDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqStatsDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqStatsUsingPoolDUnitTest.java
* Removed from CqDataUsingPoolDUnitTest
* Removed from CqStatsDUnitTest
* Removed from CqStatsUsingPoolDUnitTest
=> GEODE-4473: Removed GemFireCacheImpl.getInstance() calls

geode-core/src/test/java/org/apache/geode/pdx/JSONFormatterBasicJUnitTest.java, geode-core/src/test/java/org/apache/geode/pdx/JSONFormatterFailuresTest.java, geode-core/src/test/java/org/apache/geode/pdx/JSONFormatterJUnitTest.java, geode-core/src/test/java/org/apache/geode/pdx/JSONPdxClientServerDUnitTest.java
do some code cleanup of JSONFormatter tests while I'm at it.
=> GEODE-4653: Add JSONFormatterFailuresTest with simple examples.

gradle.properties, gradle/test.gradle
=> GEODE-3: Enabling property to run tests with a different JVM

geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java
=> GEODE-4626: Indicate the region creation from a template is deprecated

geode-docs/developing/eviction/chapter_overview.html.md.erb, geode-docs/developing/eviction/configuring_data_eviction.html.md.erb, geode-docs/developing/eviction/how_eviction_works.html.md.erb, geode-docs/developing/expiration/chapter_overview.html.md.erb, geode-docs/developing/expiration/configuring_data_expiration.html.md.erb, geode-docs/developing/expiration/how_expiration_works.html.md.erb, geode-docs/developing/general_region_data_management.html.md.erb, geode-docs/reference/topics/cache_xml.html.md.erb, geode-docs/reference/topics/chapter_overview_cache_xml.html.md.erb, geode-docs/reference/topics/client-cache.html.md.erb
Changes to docs relating to eviction and expiration especially:
- Developing with Apache Geode -> General Region Data Management -> Eviction
- Developing with Apache Geode -> General Region Data Management -> Expiration
- Reference -> cache.xml -> <cache> Element Reference -> lru-*
=> Feature/geode 4325: User Guide - Clarify eviction actions

ci/bin/concourse_job_performance.py, ci/pipelines/meta.yml, ci/pipelines/metrics.yml, ci/scripts/concourse_job_performance.sh
* Create new pipeline that provides success metrics on develop pipeline
jobs.
* For each job, display percentage success over last 50 jobs, as well as
enumerate test failures and the builds they occurred in.
Co-authored-by: Vince Ford <vford@pivotal.io>
- [ N/A ] Have you written or updated unit tests to verify your …
=> [GEODE-4688] Add metrics pipeline.

ci/pipelines/meta.yml
=> [GEODE-4688] Pipeline testing references made it into the commit.

geode-core/src/main/antlr/org/apache/geode/cache/query/internal/parse/oql.g, geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledAddition.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledArithmetic.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledDivision.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledMod.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledMultiplication.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledSubtraction.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledValue.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/QCompiler.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/parse/ASTArithmeticOp.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/ArithmeticOperationsIntegrationTest.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/index/CompactRangeIndexQueryIntegrationTest.java, geode-core/src/test/resources/org/apache/geode/codeAnalysis/excludedClasses.txt, geode-cq/src/test/java/org/apache/geode/cache/query/cq/CQDistributedTest.java
=> GEODE-4327: Added mod and arithmetic functionality to oql engine

geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfigImpl.java, geode-core/src/main/java/org/apache/geode/internal/InternalDataSerializer.java, geode-core/src/test/java/org/apache/geode/internal/cache/execute/ClientFunctionTimeoutRegressionTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyIndexCommandsDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/IndexCommandsShareConfigurationDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/LocateEntryDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/RemoveCommandJsonDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ShowDeadlockDUnitTest.java, geode-core/src/test/java/org/apache/geode/security/ClientDataAuthorizationUsingLegacySecurityDUnitTest.java, geode-core/src/test/java/org/apache/geode/security/ClientDataAuthorizationUsingLegacySecurityWithFailoverDUnitTest.java, geode-core/src/test/java/org/apache/geode/security/ClientExecuteFunctionAuthDUnitTest.java, geode-core/src/test/java/org/apache/geode/test/dunit/rules/DistributedRestoreSystemProperties.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsDUnitTest.java
=> GEODE-4690: ClusterStartupRule causes System properties to 'disappear'

geode-core/src/main/java/org/apache/geode/cache/RegionShortcut.java, geode-core/src/main/java/org/apache/geode/management/DistributedRegionMXBean.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/DistributedRegionBridge.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/RegionClusterStatsMonitor.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/exceptions/EntityExistException.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/exceptions/EntityExistsException.java, geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt, geode-core/src/test/java/org/apache/geode/cache/RegionShortcutTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionSecurityTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommandDUnitTest.java
=> GEODE-4625: name collision check when create region through gfsh

geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionSecurityTest.java
=> GEODE-4625: Add missing @Category to test.

geode-core/src/main/java/org/apache/geode/cache/wan/GatewayReceiver.java
=> GEODE-2667: Improved javaDoc for GatewayReceiver.destroy()

geode-core/src/main/java/org/apache/geode/internal/datasource/AbstractPoolCache.java, geode-core/src/main/java/org/apache/geode/internal/datasource/ConfiguredDataSourceProperties.java, geode-core/src/main/java/org/apache/geode/internal/datasource/ManagedPoolCacheImpl.java, geode-core/src/main/java/org/apache/geode/internal/datasource/TranxPoolCacheImpl.java, geode-core/src/main/java/org/apache/geode/internal/jndi/JNDIInvoker.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CommandAvailabilityIndicator.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateJndiBindingCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/converters/ConfigPropertyConverter.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/CreateJndiBindingFunction.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/JndiBindingConfiguration.java, geode-core/src/main/java/org/apache/geode/management/internal/configuration/domain/Configuration.java, geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateAsyncEventQueueCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateDefinedIndexesCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateJndiBindingCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateJndiBindingCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateJndiCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/converters/ConfigPropertyConverterTest.java
=> GEODE-3875: gfsh command to create jndi binding

geode-docs/developing/query_additional/operators.html.md.erb, geode-docs/developing/query_select/the_where_clause.html.md.erb, geode-docs/developing/querying_basics/query_grammar_and_reserved_words.html.md.erb, geode-docs/developing/querying_basics/reserved_words.html.md.erb
I also made an unrelated table of comparison operators more readable.
=> GEODE-4327 Document new OQL operators

geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/ExecuteFunctionOnRegionRequestOperationHandler.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/GetAllRequestOperationHandler.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/GetRequestOperationHandler.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/PutAllRequestOperationHandler.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/PutRequestOperationHandler.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/RemoveRequestOperationHandler.java
=> GEODE-4638: Standardize hanlding of region-not-found errors.

geode-core/src/main/java/org/apache/geode/cache/wan/GatewayReceiver.java
=> GEODE-2667: Reword javaDoc for destroy gateway receiver

geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/ProtobufOpsProcessor.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/GetAllRequestOperationHandler.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/GetRequestOperationHandler.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/PutAllRequestOperationHandler.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/PutRequestOperationHandler.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/RemoveRequestOperationHandler.java
Updating statistics in one place, rather than in each operation.
=> GEODE-4736: Updating statistics in ProtobufOpsProcessor

geode-core/src/main/java/org/apache/geode/cache/RegionShortcut.java, geode-core/src/main/java/org/apache/geode/management/DistributedRegionMXBean.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java, geode-core/src/main/java/org/apache/geode/redis/internal/RegionProvider.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandIntegrationTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionSecurityDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommandDUnitTest.java
=> GEODE-4625: rework name collision check logic and add more tests

geode-core/src/main/java/org/apache/geode/cache/query/internal/RestrictedMethodInvocationAuthorizer.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/RestrictedMethodInvocationAuthorizerTest.java, geode-core/src/test/java/org/apache/geode/security/query/QuerySecurityAllowedQueriesDUnitTest.java, geode-core/src/test/java/org/apache/geode/security/query/data/QueryTestObject.java
=> GEODE-4744: Allow java.util.Map#get in OQL when security is enabled

geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/registry/ProtobufOperationContextRegistry.java
=> GEODE-4753: fix permission for GetServer operation

geode-protobuf-messages/src/main/proto/v1/basicTypes.proto, geode-protobuf-messages/src/main/proto/v1/clientProtocol.proto, geode-protobuf-messages/src/main/proto/v1/region_API.proto, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/OqlQueryRequestOperationHandler.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/registry/ProtobufOperationContextRegistry.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/serialization/exception/DecodingException.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/serialization/exception/EncodingException.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/OqlQueryRequestOperationHandlerIntegrationTest.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/OqlQueryRequestOperationHandlerJUnitTest.java
Adding an oql query request and response to the new protocol.
=> GEODE-3126: Adding a query message to the protobuf protocol

geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/Driver.java, geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/ProtobufChannel.java, geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/ProtobufDriver.java, geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/ProtobufQueryService.java, geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/ProtobufRegion.java, geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/Query.java, geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/QueryService.java, geode-experimental-driver/src/test/java/org/apache/geode/experimental/driver/IntegrationTestBase.java, geode-experimental-driver/src/test/java/org/apache/geode/experimental/driver/QueryServiceIntegrationTest.java, geode-experimental-driver/src/test/java/org/apache/geode/experimental/driver/RegionIntegrationTest.java
Adding a QueryService and query operations to the experimental client.
=> GEODE-3126: Adding a query command to the experimental driver

ci/docker/initdocker, ci/pipelines/develop.yml
* Exclude ci directory from counting as changes on the geode resource
* Change storage driver for dockerd from aufs to overlay2.
Signed-off-by: Dick Cavender <dcavender@pivotal.io>
- [ N/A ] If adding new dependencies to the code, are these …
=> [GEODE-4760] CI maintenance fixes.

geode-docs/reference/topics/client-cache.html.md.erb, geode-docs/topologies_and_comm/topology_concepts/how_the_pool_manages_connections.html.md.erb
See client-cache element reference for <pool>
and Topologies and Communication -> Client/Server Configuration -> How Client/Server Connections Work
=> GEODE-3948 Document subscription timeout multiplier

geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/ProtobufRegion.java, geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/Region.java, geode-experimental-driver/src/test/java/org/apache/geode/experimental/driver/RegionIntegrationTest.java, geode-protobuf-messages/src/main/proto/v1/clientProtocol.proto, geode-protobuf-messages/src/main/proto/v1/region_API.proto, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/KeySetOperationHandler.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/registry/ProtobufOperationContextRegistry.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/acceptance/CacheOperationsJUnitTest.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/KeySetOperationHandlerJUnitTest.java
=> GEODE-4661: Implement KeySet protobuf message and handler

geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/GetServerOperationHandler.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/utilities/ProtobufRequestUtilities.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/GetServerOperationHandlerJUnitTest.java
@bschuchardt had already implemented the feature just after the first of the year. This PR just adds some testing.
=> GEODE-3465: Enhance error message and add tests for when group is specified.

geode-core/src/main/java/org/apache/geode/internal/jndi/JNDIInvoker.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListJndiBindingCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/ListJndiBindingFunction.java, geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListJndiBindingCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/CreateJndiBindingFunctionTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/ListJndiBindingFunctionTest.java
=> GEODE-4385: Add list jndi-binding option

geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/LonerDistributionManager.java, geode-core/src/main/java/org/apache/geode/internal/cache/execute/AbstractExecution.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteFunction66.java
=> GEODE-4759: Fix typo of getFunctionExcecutor

geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java, geode-wan/src/main/java/org/apache/geode/internal/cache/wan/GatewayReceiverImpl.java, geode-wan/src/test/java/org/apache/geode/internal/cache/wan/serial/GatewayReceiverDUnitTest.java
=> GEODE-2667: Added more logs and tests for GatewayReceiver destroy

geode-assembly/build.gradle
=> Stop generating md5 checksums for distribution archives

geode-core/src/main/java/org/apache/geode/management/internal/cli/util/ThreePhraseGenerator.java
=> GEODE-182: Use of neutral words

geode-cq/src/test/java/org/apache/geode/cache/query/cq/CQDistributedTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/CQJUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqDataDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqDataOptimizedExecuteDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqDataUsingPoolDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqDataUsingPoolOptimizedExecuteDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqPerfDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqPerfUsingPoolDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqQueryDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqQueryOptimizedExecuteDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqQueryUsingPoolDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqQueryUsingPoolOptimizedExecuteDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqResultSetUsingPoolDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqResultSetUsingPoolOptimizedExecuteDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqStateDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqStatsDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqStatsOptimizedExecuteDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqStatsUsingPoolDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqStatsUsingPoolOptimizedExecuteDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/PartitionedRegionCqQueryDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/PartitionedRegionCqQueryOptimizedExecuteDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/PrCqUsingPoolDUnitTest.java, geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/PrCqUsingPoolOptimizedExecuteDUnitTest.java, gradle/test.gradle
=> GEODE-4780: Categorized cq tests under ClientSubscriptionTest

geode-wan/src/main/java/org/apache/geode/internal/cache/wan/GatewayReceiverImpl.java, geode-wan/src/test/java/org/apache/geode/internal/cache/wan/serial/GatewayReceiverDUnitTest.java
=> GEODE-4770: Destroying unstarted GatewayReceiver is now supported

geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/LogsAndDescribeConfigAreFullyRedactedAcceptanceTest.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/locator/LocatorStatusResponse.java, geode-core/src/main/java/org/apache/geode/internal/Banner.java, geode-core/src/main/java/org/apache/geode/internal/util/ArgumentRedactor.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeConfigCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/domain/MemberConfigurationInfo.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/GetMemberConfigInformationFunction.java
=> GEODE-4775: Apply ArgumentRedactor to JVM arguments.

ci/docker/Dockerfile
Updated ci Dockerfile to have both chrome and chromedriver
binaries installed.
=> GEODE-4777: Add UITest job to concourse develop pipeline

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateConnectionCommand.java, geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/CreateConnectionCommandDUnitTest.java
* Do not allow creation of connection if user is null but password is not
=> GEODE-4217: Add validation to CreateConnectionCommand

geode-core/src/main/java/org/apache/geode/internal/cache/DiskStoreImpl.java
- This was causing some DUnits to fail on Windows.
=> GEODE-4793: Ensure that Files.list() closes resources

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListJndiBindingCommand.java, geode-core/src/test/java/org/apache/geode/management/internal/security/TestCommand.java
- Also add ResourcePermission for the same command
=> GEODE-4385: Update help message for list jndi-binding

geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterConfigurationService.java, geode-core/src/main/java/org/apache/geode/internal/jndi/JNDIInvoker.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CommandAvailabilityIndicator.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateJndiBindingCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyJndiBindingCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DestroyJndiBindingFunction.java, geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateJndiBindingCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyJndiBindingCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyJndiBindingCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/DestroyJndiBindingFunctionTest.java
=> GEODE-4384: gfsh command to destroy jndi binding

build.gradle, gradle.properties, gradle/java.gradle, gradle/wrapper/gradle-wrapper.properties
=> GEODE-4791: Upgrading gradle from 3.5.1 to 4.5.1

geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/Driver.java, geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/Function.java, geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/FunctionService.java, geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/ProtobufDriver.java, geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/ProtobufFunction.java, geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/ProtobufFunctionService.java, geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/Query.java, geode-experimental-driver/src/test/java/org/apache/geode/experimental/driver/FunctionServiceIntegrationTest.java, geode-experimental-driver/src/test/java/org/apache/geode/experimental/driver/IntegrationTestBase.java
- Introduce function and function service interfaces.
- Enhance driver to produce function service.
=> GEODE-4751: Modify experimental driver to support function execution.

geode-core/src/main/java/org/apache/geode/cache/query/internal/DefaultQuery.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/AbstractFunctionRequestOperationHandler.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/operations/OqlQueryRequestOperationHandler.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/registry/ProtobufOperationContextRegistry.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/AuthorizationIntegrationTest.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/ExecuteFunctionOnGroupRequestOperationHandlerJUnitTest.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/ExecuteFunctionOnMemberRequestOperationHandlerJUnitTest.java, geode-protobuf/src/test/java/org/apache/geode/internal/protocol/protobuf/v1/operations/ExecuteFunctionOnRegionRequestOperationHandlerJUnitTest.java
=> GEODE-4750: Allow region level authorization for OQL queries

README.md
To encourage contributions by new community members this adds a link
from the readme to the "how to contribute" page in the wiki.
This also changes a few `http://` links to `https://`.
=> GEODE-4801 Readme links to "how to contribute"

geode-core/src/main/java/org/apache/geode/cache/asyncqueue/internal/AsyncEventQueueFactoryImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueue.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderQueue.java, geode-core/src/main/java/org/apache/geode/management/AsyncEventQueueMXBean.java, geode-core/src/main/java/org/apache/geode/management/GatewaySenderMXBean.java, geode-core/src/main/java/org/apache/geode/management/internal/ManagementStrings.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/AsyncEventQueueMBean.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/AsyncEventQueueMBeanBridge.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/GatewaySenderMBean.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/GatewaySenderMBeanBridge.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/GatewaySenderOverflowMonitor.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/StatsKey.java, geode-core/src/test/java/org/apache/geode/internal/cache/wan/AsyncEventQueueTestBase.java, geode-core/src/test/java/org/apache/geode/internal/cache/wan/MyGatewaySenderEventListener.java, geode-core/src/test/java/org/apache/geode/internal/cache/wan/asyncqueue/AsyncEventListenerDUnitTest.java, geode-wan/src/test/java/org/apache/geode/internal/cache/wan/AsyncEventQueueOverflowMBeanAttributesDistributedTest.java, geode-wan/src/test/java/org/apache/geode/internal/cache/wan/GatewaySenderOverflowMBeanAttributesDistributedTest.java
=> GEODE-4716: Added overflow attributes to gateway mbeans

geode-assembly/build.gradle, geode-assembly/src/test/java/org/apache/geode/tools/pulse/ui/PulseAcceptanceAuthTest.java, geode-assembly/src/test/java/org/apache/geode/tools/pulse/ui/PulseAcceptanceNoAuthTest.java, geode-assembly/src/test/java/org/apache/geode/tools/pulse/ui/PulseAcceptanceTestBase.java
These UI tests uses locator and cluster rules to setup VMs with integrated security.
* Added selenium based pulse UI tests to setup using locator and cluster rules
* Added pulse as a test dependency to geode-assembly
* Added selenium and chrome driver dependency to geode-assembly
* Added uiTest task to geode-assembly gradle
=> GEODE-4807: Pulse UI tests using locator/cluster rule.

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/IndexRepositoryFactory.java
=> GEODE-4825: Lucene Index should reset pdx read serialized

geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/HAInterestTestCase.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/RegisterInterestIntegrationTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/RegisterInterestServerMetaDataDistributedTest.java
=> GEODE-4813: Categorize remaining register interest tests

geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/ProtobufChannel.java
=> GEODE-4768: Close the socket to the locator in the experimental driver

geode-core/src/main/java/org/apache/geode/internal/cache/entries/AbstractRegionEntry.java, geode-core/src/test/java/org/apache/geode/internal/cache/entries/AbstractRegionEntryTest.java
* If the region entry is a tombstone then OQL indexes are not updated
* The operation extracted to a external method.
=> GEODE-4823: OQL index not updated for tombstone

geode-assembly/src/test/java/org/apache/geode/rest/internal/web/controllers/RestAPIsWithSSLDUnitTest.java, geode-core/src/main/java/org/apache/geode/management/internal/JettyHelper.java, geode-core/src/main/java/org/apache/geode/management/internal/SSLUtil.java
=> GEODE-3891: Cannot enable ciphers for REST interface

extensions/geode-modules-session/src/test/java/org/apache/geode/modules/session/installer/InstallerJUnitTest.java, extensions/geode-modules-session/src/test/java/org/apache/geode/modules/session/internal/filter/SessionReplicationIntegrationJUnitTest.java, extensions/geode-modules-session/src/test/java/org/apache/geode/modules/session/internal/filter/SessionReplicationJUnitTest.java, extensions/geode-modules-session/src/test/java/org/apache/geode/modules/session/internal/filter/SessionReplicationLocalCacheJUnitTest.java, extensions/geode-modules-tomcat7/src/test/java/org/apache/geode/modules/session/Tomcat7SessionsJUnitTest.java, extensions/geode-modules-tomcat8/src/test/java/org/apache/geode/modules/session/Tomcat8SessionsClientServerDUnitTest.java, extensions/geode-modules-tomcat8/src/test/java/org/apache/geode/modules/session/Tomcat8SessionsDUnitTest.java, extensions/geode-modules/src/test/java/org/apache/geode/modules/util/ClassLoaderObjectInputStreamTest.java, extensions/geode-modules/src/test/java/org/apache/geode/modules/util/ModuleFunctionsSecurityTest.java, geode-junit/src/main/java/org/apache/geode/test/junit/categories/SessionTest.java, gradle/test.gradle
=> GEODE-4824: Categorized Session state tests

geode-junit/src/main/java/org/apache/geode/test/junit/categories/GfshTest.java
This PR just creates the category annotation.
=> GEODE-4782: Add category annotation for Gfsh tests

geode-junit/src/main/java/org/apache/geode/test/junit/categories/ManagementTest.java
This PR just adds the new category annotation for management component integration and distributed tests.
=> GEODE-4783: Add category annotation for Management tests

geode-assembly/src/test/java/org/apache/geode/tools/pulse/ui/PulseAcceptanceTestBase.java
=> GEODE-4880: Ignore Pulse UI acceptance tests that are flaky

geode-core/src/main/java/org/apache/geode/distributed/ClusterConfigurationService.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalClusterConfigurationService.java, geode-core/src/main/java/org/apache/geode/internal/cache/configuration/RegionConfig.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateJndiBindingCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyJndiBindingCommand.java, geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt, geode-core/src/test/java/org/apache/geode/distributed/internal/InternalClusterConfigurationServiceTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateJndiBindingCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyJndiBindingCommandTest.java
=> GEODE-4857: add interface methods to ClusterConfigurationService

ci/bin/concourse_job_performance.py
* Generate concourse job URL because the url field was removed in
Concourse 3.9.2. …
=> [GEODE-4891] Fixes for concourse API changes.

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CommandAvailabilityIndicator.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyJndiBindingCommand.java
=> GEODE-4898: Fix field names in DestroyJndiBindingCommand

geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/utilities/ProtobufUtilities.java
=> GEODE-4873: Remove link to test code from main code.

geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt
=> GEODE-4907: Fix analyze serializables for moved enum RefusalReason

geode-core/src/main/java/org/apache/geode/cache/configuration/JndiBindingsType.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeJndiBindingCommand.java, geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt, geode-core/src/test/java/org/apache/geode/management/internal/cli/GfshParserAutoCompletionTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeJndiBindingCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ManagedConnectionFactoryForTesting.java
=> GEODE-4386: Add gfsh command to describe jndi-binding

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneServiceImpl.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/RebalanceWithRedundancyWithRegionCreatedBeforeReindexDUnitTest.java
* LuceneServiceImpl changes to support AEQ addition to existing region (after index initialized)
* Testing with and without redundancy
=> GEODE-4881: Support lucene reindexing (of existing data) with rebalance

geode-core/src/main/java/org/apache/geode/redis/GeodeRedisServer.java, geode-core/src/test/java/org/apache/geode/redis/SetsJUnitTest.java
=> GEODE-3881: Prevent illegal region names in the unit tests.

geode-core/src/main/java/org/apache/geode/cache/Region.java
=> GEODE-4910: Modify method description to mention exception.

geode-connectors/src/test/java/org/apache/geode/codeAnalysis/AnalyzeConnectorsSerializablesJUnitTest.java, geode-core/src/test/java/org/apache/geode/codeAnalysis/AnalyzeSerializablesJUnitTest.java
=>  GEODE-4882: Prevent intermittent test failure from CacheClosedException

geode-assembly/src/main/dist/bin/gfsh.bat
- Fixes formatting
- Removes extra @ (echo suppression)
=> GEODE-4924: Fixes JAVA_ARGS environemnt parameter.

ci/pipelines/develop.yml
=> GEODE-4941: Increase UITests timeout to 2h

ci/docker/Dockerfile
=> GEODE-4973: Add docker-compose to pipeline docker image

geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/data/PulseConstants.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/service/ClusterDetailsService.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/service/ClusterMembersRGraphService.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/service/ClusterRegionService.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/service/ClusterRegionsService.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/service/ClusterSelectedRegionService.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/service/MemberDetailsService.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/service/MemberRegionsService.java, geode-pulse/src/test/java/org/apache/geode/tools/pulse/tests/ui/PulseBase.java
- Ensure that all number formatting is consistent. Formatting, as it exists,
will be according to the US locale.
- This also fixes GEODE-1409
=> GEODE-2321: Pulse application works incorrectly in some locales

geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/GfshRule.java
The conjecture is that we're missing shutdown problems with a test
that can cause problems in later tests. This change is an attempt
to catch the real error in the sporadic AcceptanceTest failures.
=> GEODE-4934: Throw exception if shutdown fails in GfshRule

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/AbstractJdbcCallback.java, geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/DataSourceManager.java, geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/JdbcConnectorService.java, geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/JdbcConnectorServiceImpl.java, geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/SqlHandler.java, geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/AbstractJdbcCallbackTest.java, geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/DataSourceManagerUnitTest.java, geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/JdbcConnectorServiceTest.java, geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/SqlHandlerTest.java
=> GEODE-4974: Create single connection pool per cache

geode-cq/src/test/java/org/apache/geode/internal/cache/PutAllCSDUnitTest.java
=> GEODE-4976: Fix misspelling and misattribution in test logging.

geode-core/src/test/java/org/apache/geode/TestDataSerializer.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/DataSerializerPropagationDUnitTest.java
=> GEODE-3820: Remove all invocations of Wait.pause() in DataSerializerPropagationDUnitTest.

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CommandAvailabilityIndicator.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DescribeJndiBindingCommand.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DescribeJndiBindingCommandDUnitTest.java
- Return with an error code if the JNDI binding is not found
- Add availability indication
- Adjust help text
=> GEODE-4386: Return 'not found' if the JNDI binding does not exist

geode-experimental-driver/src/main/java/org/apache/geode/experimental/driver/SocketFactory.java, geode-experimental-driver/src/test/java/org/apache/geode/experimental/driver/SSLTest.java
=> GEODE-4817: Fix SSLTest.

geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionQueryEvaluator.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/QueryMessage.java, geode-core/src/test/java/org/apache/geode/cache/query/dunit/ResourceManagerWithQueryMonitorDUnitTest.java
=> GEODE-4867: Query execution time expiration checked

geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/data/JMXDataUpdater.java
=> GEODE-3456: Fix display of 'null' hosts in Pulse UI

geode-docs/managing/security/implementing_authorization.html.md.erb
- [N/A] Does `gradlew build` run cleanly?
=> GEODE-4979: Incorrect description in docs of ResourcePermission in OQL

build.gradle, gradle/spotless.gradle
- [n/a - build] Have you written or updated unit tests to verify your changes?
=> Geode-4950 + GEODE-4951: Upgrade spotless version and reduce run time.

geode-core/src/test/java/org/apache/geode/management/internal/cli/domain/MyCacheListener.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/domain/MyCacheLoader.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/domain/MyCacheWriter.java, geode-core/src/test/java/org/apache/geode/management/internal/configuration/ClusterConfigWithCallbacksDUnitTest.java
=> GEODE-4893: add test to make sure the callbacks will be loaded correctly

geode-core/src/main/java/org/apache/geode/cache/client/internal/ClientSideHandshakeImpl.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
=> GEODE-4644: Move static to member of distributed system.

geode-core/src/test/java/org/apache/geode/management/internal/cli/result/CompositeResultDataTest.java
=> GEODE-5003: Add tests for CompositeResultData

geode-core/src/test/java/org/apache/geode/management/internal/cli/result/InfoResultDataTest.java
=> GEODE-5005: Add unit tests for InfoResultData

geode-core/src/test/java/org/apache/geode/management/internal/cli/result/ErrorResultDataTest.java
=> GEODE-5004: Add unit tests for ErrorResultData

geode-core/src/test/java/org/apache/geode/management/internal/cli/result/TabularResultDataTest.java
=> GEODE-5007: Add unit tests to TabularResultData

geode-core/src/main/java/org/apache/geode/management/internal/cli/json/GfJsonArray.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/json/GfJsonArrayTest.java
- Remove some unused methods from GfJsonArray
=> GEODE-5008: Add unit tests for GfJsonArray

geode-core/src/main/java/org/apache/geode/management/internal/cli/json/GfJsonObject.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/json/GfJsonObjectTest.java
=> GEODE-5009: Add unit tests for GfJsonObject

geode-core/src/test/java/org/apache/geode/management/internal/configuration/ClusterConfigLocatorRestartDUnitTest.java
=> GEODE-4915: Ignore the 'for testing' exception

extensions/geode-modules-assembly/build.gradle, extensions/geode-modules-assembly/release/tcserver/geode-cs-tomcat-85/context-fragment.xml, extensions/geode-modules-assembly/release/tcserver/geode-p2p-tomcat-85/context-fragment.xml
=> GEODE-4999: Added tomcat 8.5 directory for tcserver support

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListGatewayCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListGatewayCommandTest.java
=> GEODE-4962: Fix typo and output format from 'list gateways' gfsh command

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateJndiBindingCommand.java
=> GEODE-4874: Inconsistency in gfsh help for create jndi-binding

geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/DataSerializerPropagationDUnitTest.java
=> GEODE-5065: Add awaitability to testServerUpFirstClientLater

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyJndiBindingCommand.java
=> GEODE-5051: Improve gfsh destroy jndi-binding help prose

geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/ProtobufOpsProcessor.java, geode-protobuf/src/main/java/org/apache/geode/internal/protocol/protobuf/v1/ProtobufStreamProcessor.java
We were just logging the exception message, not the stack trace.
=> GEODE-5044: Correctly log stack trace on the protobuf server

geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySenderEventProcessor.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderQueue.java, geode-wan/src/test/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderOperationsDUnitTest.java, geode-wan/src/test/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderOperationsDUnitTest.java
QueueRemovalMessage for it
@boglesby @jhuynh1 
=> GEODE-5056: when found the dropped events at primary sender, send

geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegionArguments.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java
=> GEODE-5064: Removed unused code in LocalRegion

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/PartitionedRepositoryManager.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/PartitionedRepositoryManagerJUnitTest.java
=> GEODE-3926: Catching exception in lucene query computing thread

geode-core/src/main/java/org/apache/geode/internal/cache/ClusterConfigurationLoader.java
=> GEODE-5000: fix logging message.

geode-core/src/main/java/org/apache/geode/management/internal/cli/result/CommandResult.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateDefinedIndexesCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateIndexCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ShowMetricsJUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/configuration/ClusterConfigImportDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/security/GfshCommandsSecurityTest.java, geode-core/src/test/java/org/apache/geode/management/internal/security/MultiGfshDUnitTest.java, geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshCommandRule.java
=> GEODE-5088: Remove getContentAsString from CommandResult

geode-core/src/main/java/org/apache/geode/distributed/ClusterConfigurationService.java, geode-core/src/test/java/org/apache/geode/distributed/internal/InternalClusterConfigurationServiceTest.java
=> GEODE-4858: add test for custom cache elements not properly registered

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/CreateConnectionCommand.java, geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/JDBCCommandsAvailabilityTest.java, geode-core/src/main/java/org/apache/geode/management/cli/GfshCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CommandAvailabilityIndicator.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListJndiBindingCommand.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CommandAvailabilityIndicatorTest.java
=> GEODE-5048: add missing availability indicators for certain commands

geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/GMSEncrypt.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/GMSEncryptionCipherPool.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessenger.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/gms/messenger/GMSEncryptJUnitTest.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessengerJUnitTest.java
=> GEODE-4986: refactoring GMS encryption

geode-core/src/test/java/org/apache/geode/internal/cache/PRQueryWithIndexAndPdxDistributedTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/PRQueryWithIndexDistributedTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/PRQueryWithOrderByDistributedTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/PRQueryWithPdxDuringRebalanceRegressionTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/PRWithIndexAfterRebalanceRegressionTest.java
=> GEODE-5077: Categorized newly added oql tests

geode-book/master_middleman/source/subnavs/geode-subnav.erb, geode-docs/managing/management/list_of_mbeans_full.html.md.erb, geode-docs/reference/statistics_list.html.md.erb
- found and fixed a subnav typo for a link to the MXBean doc
- corrected a bad Object Name for the AsyncEventQueueMXBean
=> GEODE-4716 Document new stats and missing gateway sender/receiver MXBean

geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/GatewayReceiverCreateFunction.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/GatewayReceiverCreateFunctionTest.java
=> GEODE-5095: Fix output for create gateway-receiver (port number)

geode-core/src/main/java/org/apache/geode/pdx/internal/PdxInstanceImpl.java, geode-core/src/main/java/org/apache/geode/pdx/internal/WritablePdxInstanceImpl.java, geode-core/src/test/java/org/apache/geode/pdx/internal/PdxInstanceImplTest.java
=> GEODE-5038: Improve human-readable formatting of arrays in PdxInstance.toString().

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/AlterConnectionCommand.java, geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/AlterMappingCommand.java, geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeConnectionCommand.java, geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommand.java, geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyConnectionCommand.java, geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DestroyMappingCommand.java, geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/AlterConnectionCommandTest.java, geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/AlterMappingCommandTest.java, geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeConnectionCommandTest.java, geode-connectors/src/test/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommandTest.java, geode-core/src/main/java/org/apache/geode/cache/configuration/CacheElement.java, geode-core/src/main/java/org/apache/geode/distributed/ClusterConfigurationService.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateJndiBindingCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyJndiBindingCommand.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateJndiBindingCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyJndiBindingCommandTest.java
=> GEODE-4858: move the utility methods out of ClusterConfigurationService

ci/docker/Dockerfile, ci/docker/docker.list
Signed-off-by: Robert Houghton <rhoughton@pivotal.io> …
=> GEODE-5119 - add spruce to ci docker image.

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneServiceImpl.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneSearchWithRollingUpgradeDUnit.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/LuceneServiceImplJUnitTest.java
=> GEODE-5082: Added rolling upgrade tests for reindex

ci/pipelines/develop.yml
=> GEODE-5114: Archive UITest results

geode-core/src/test/java/org/apache/geode/security/ClientDataAuthorizationUsingLegacySecurityWithFailoverDUnitTest.java
=> GEODE-4890: use awaitility to reduce flakiness.

geode-core/src/main/java/org/apache/geode/cache/asyncqueue/internal/AsyncEventQueueStats.java, geode-core/src/main/java/org/apache/geode/internal/cache/AbstractBucketRegionQueue.java, geode-core/src/main/java/org/apache/geode/internal/cache/BucketRegionQueue.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySender.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySenderEventProcessor.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/GatewaySenderStats.java, geode-core/src/main/java/org/apache/geode/internal/cache/wan/parallel/ParallelQueueRemovalMessage.java, geode-core/src/test/java/org/apache/geode/cache/asyncqueue/internal/SerialAsyncEventQueueImplJUnitTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/wan/AsyncEventQueueTestBase.java, geode-core/src/test/java/org/apache/geode/internal/cache/wan/parallel/ParallelQueueRemovalMessageJUnitTest.java, geode-core/src/test/java/org/apache/geode/management/bean/stats/AsyncEventQueueStatsJUnitTest.java, geode-wan/src/test/java/org/apache/geode/internal/cache/wan/WANTestBase.java, geode-wan/src/test/java/org/apache/geode/internal/cache/wan/parallel/ParallelWANConflationDUnitTest.java
=> GEODE-4624: add a stats to trace total event removed by PQRM

geode-core/src/test/java/org/apache/geode/cache/RegionExpirationDistributedTest.java
Use Awaitility and avoid invoking assertThat(Map) for Region (which is a Map).
The expiration action is happening asynchronously (from the JUnit main thread). For destroy, the Region is destroyed (which means ops will starting throwing RegionDestroyedException) and then it's removed from the Cache region map (after which it will be null).
The test should have theoretically failed with a simpler error message about the Region not being null, but AssertJ treated Region as a Map and attempted to invoke size() which then threw RegionDestroyedException.
Please review @dhemery!
=> GEODE-5040: Fix intermittent RegionExpirationDistributedTest failure

geode-core/src/main/java/org/apache/geode/management/internal/cli/domain/DurableCqNamesResult.java
=> GEODE-3438: Removed unused constructor and method

geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegionMap.java, geode-core/src/main/java/org/apache/geode/internal/cache/HARegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/ha/HARegionQueue.java, geode-core/src/test/java/org/apache/geode/internal/cache/ha/HARegionDUnitTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/ha/HARegionQueueDUnitTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/ha/HARegionQueueIntegrationTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/HABug36738DUnitTest.java
=> GEODE-4996: Addressed NPE by always using the region entry key

geode-core/src/test/java/org/apache/geode/test/dunit/rules/DistributedTestRule.java, geode-core/src/test/java/org/apache/geode/test/dunit/standalone/DUnitLauncher.java
=> GEODE-5129 Amend DistributedTestRule to honor the vmCount parameter when < 4 hosts

geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/distributed/LuceneQueryFunctionJUnitTest.java
* Removed the type argument from the raw type.
* This was coming up as an error in IDE.
=> GEODE-5122: Removed the type argument

geode-core/src/test/java/org/apache/geode/cache/query/dunit/QueryDataInconsistencyDUnitTest.java
Replaced all Wait.pause with Awaitility. 
Replaced all ThreadUtils.join with an Awaitility. 
General code and lambda clean up
=> GEODE-925: QueryDataInconsistencyDUnitTest.testRangeIndexWithIndexAndQueryFromCluaseMisMatch

ci/pipelines/geode-build/deploy_pipeline.sh
=> GEODE-5130 introducing spruce and deploy-pipeline script for branch-agnostic deployments

geode-cq/src/test/java/org/apache/geode/cache/query/cq/dunit/CqPerfUsingPoolDUnitTest.java
=> GEODE-4172: Simplified test and increase wait timeout

ci/scripts/test-run.sh
=> [GEODE-5130] Fix docker image reference in test-run.sh

geode-core/src/main/java/org/apache/geode/cache/configuration/StringType.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ConfigurePDXCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/i18n/CliStrings.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ConfigurePDXCommandIntegrationTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ConfigurePDXCommandTest.java
=> GEODE-4794: ConfigurePDXCommand Fails When Using Defaults

geode-core/src/main/java/org/apache/geode/redis/internal/RegionProvider.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/util/ThreePhraseGeneratorTest.java, geode-core/src/test/java/org/apache/geode/redis/SetsJUnitTest.java
- Add unit test for three-phrase generator to ensure compatibility with region names.
- Rename parameter to improve clarity.
- Remove dead code.
=> GEODE-3881: Replace bespoke random string generation with extant three-phrase generator.

geode-core/src/test/java/org/apache/geode/test/dunit/IgnoredException.java
=> GEODE-5153: Remove uses of the internal distributed system's log writer and the log writer utils' log writer.

geode-core/src/test/java/org/apache/geode/internal/cache/AbstractRegionMapTest.java
=> GEODE-5152: add unit tests for txApplyPut

geode-wan/src/test/java/org/apache/geode/internal/cache/wan/WANTestBase.java, geode-wan/src/test/java/org/apache/geode/internal/cache/wan/parallel/ParallelGatewaySenderOperationsDUnitTest.java
* Joining async thread before doing any validation
* Removed some dead code
=> GEODE-5131: Fixing testParallelPropagationSenderResume test

geode-core/src/test/java/org/apache/geode/cache30/ShorteningExpirationTimeRegressionTest.java
Fix all flakiness in ShorteningExpirationTimeRegressionTest.
Fix GEODE-924 and GEODE-1139.
@dhemery Please review.
=> GEODE-924: GEODE-1139: Fix ShorteningExpirationTimeRegressionTest

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/AlterRegionCommand.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/AlterRegionCommandTest.java
=> GEODE-5083: Alter region --name option no longer auto completes

geode-core/src/test/java/org/apache/geode/security/ClientDataAuthorizationUsingLegacySecurityWithFailoverDUnitTest.java
Just saw this failed again in my precheckin, wondering if this change would help.
=> GEODE-4890: fix to reduce flakiness

geode-core/src/main/java/org/apache/geode/cache/configuration/DeclarableType.java, geode-core/src/main/java/org/apache/geode/cache/configuration/ParameterType.java, geode-core/src/main/java/org/apache/geode/cache/configuration/RegionConfig.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ConfigurePDXCommand.java, geode-core/src/test/java/org/apache/geode/cache/configuration/CacheConfigTest.java
=> GEODE-5032: massage StringType configuration objects for better usability.

geode-core/src/main/java/org/apache/geode/management/internal/cli/CliAroundInterceptor.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ExecuteFunctionCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ExportConfigCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ExportImportClusterConfigurationCommands.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ExportLogsInterceptor.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/QueryInterceptor.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/result/AbstractResultData.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/result/CompositeResultData.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/result/LegacyCommandResult.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/result/ModelCommandResult.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/result/ResultData.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/result/model/AbstractResultModel.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/result/model/FileResultModel.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/result/model/ResultModel.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/shell/GfshExecutionStrategy.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ExecuteFunctionCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ExportConfigCommandTest.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/CommandOverHttpTest.java, geode-web/src/test/java/org/apache/geode/management/internal/cli/commands/ExportConfigCommandDUnitTest.java
=> GEODE-5011: Convert ExecuteFunctionCommand and ExportConfigCommand to use ResultModel

geode-lucene/src/main/java/org/apache/geode/cache/lucene/LuceneIndexFactory.java
=> GEODE-5141: Adding @since tag to setLuceneSerializer method

geode-core/src/main/java/org/apache/geode/cache/configuration/DeclarableType.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ConfigurePDXCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/exceptions/EntityExistsException.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/remote/CommandExecutor.java, geode-core/src/test/java/org/apache/geode/cache/configuration/CacheConfigTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ConfigurePDXCommandTest.java
=> GEODE-4858: refactor ConfigurePdxCommand

geode-core/src/main/java/org/apache/geode/internal/DataSerializableFixedID.java, geode-core/src/main/java/org/apache/geode/internal/cache/CreateRegionProcessor.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/main/java/org/apache/geode/internal/i18n/LocalizedStrings.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/CreateRegionProcessorForLucene.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneServiceImpl.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneQueriesReindexDUnitTest.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/LuceneServiceImplJUnitTest.java
=> GEODE-5109: Overriding the check compatibility of createRegionMessage

geode-core/src/main/java/org/apache/geode/internal/cache/InternalRegion.java, geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/test/java/org/apache/geode/cache30/DiskRegionDistributedTest.java
I finished cleaning up DiskRegionDistributedTest. This is the test that I was using in a talk about dunit with @srikanthmanvi @lgallinat @pivotal-eshu.
=> GEODE-5177: Clean up DiskRegionDistributedTest

geode-docs/developing/outside_data_sources/implementing_data_loaders.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/alter.html.md.erb, geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb
- update gfsh create region and gfsh alter region command
reference pages to specify Declarable.initialize, instead
of deprecated Declarable.init
=> GEODE-5150 Revise how to implement a cache loader docs

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ConnectCommand.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ConnectCommandTest.java
=> GEODE-5194: Relax Gfsh connection version check to exclude patch version

geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeConnectionCommand.java, geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/DescribeMappingCommand.java, geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/ListConnectionCommand.java, geode-connectors/src/main/java/org/apache/geode/connectors/jdbc/internal/cli/ListMappingCommand.java
=> GEODE-4858 refactor jdbc describe & list commands to use result model

geode-core/src/main/java/org/apache/geode/internal/cache/persistence/PersistenceInitialImageAdvisor.java, geode-core/src/test/java/org/apache/geode/internal/cache/persistence/PersistenceInitialImageAdvisorTest.java
@kirklund @dschneider-pivotal @pivotal-eshu @lgallinat @agingade Please review.
=> GEODE-5184 Add unit tests for PersistenceInitialImageAdvisor

geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySender.java, geode-wan/src/test/java/org/apache/geode/internal/cache/wan/WANTestBase.java, geode-wan/src/test/java/org/apache/geode/internal/cache/wan/serial/SerialWANPropagationsFeatureDUnitTest.java
@boglesby @jhuynh1 @ladyVader 
=> GEODE-5144: The test should wait for secondary queue to drain

geode-core/src/main/java/org/apache/geode/internal/cache/ha/HARegionQueue.java, geode-core/src/test/java/org/apache/geode/internal/cache/ha/HARegionQueueIntegrationTest.java
* When draining events from the giiQueue, the msg field of HAEventWrapper may be null.
Update the HAEventWrapper to point to the message in the HAContainer vs. calling
putEventInHARegion with the original HAContainer message (a ClientUpdateMessageImpl).
This is necessary as the ClientUpdateMessageImpl does not have the eventId (this is not
serialized/deserialized in toData/fromData).  The HAEventWrapper is required on the
remote side to reconstruct the event.
* Updated log messages to include the HARegionQueue.regionName
* Added corresponding IntegrationTest
Please ensure that once the PR is submitted, you check travis-ci …
=> GEODE-5187: clients can miss events when servers recycled

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/DestroyGatewayReceiverCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/DestroyGatewayReceiverFunction.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/DestroyGatewayReceiverCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/functions/DestroyGatewayReceiverFunctionTest.java, geode-wan/src/test/java/org/apache/geode/internal/cache/wan/wancommand/DestroyGatewayReceiverCommandDUnitTest.java
Refactored to use SingleGfshCommand and ResultModel
=> GEODE-4858: Refactor destroy gateway-receiver command

ci/pipelines/deploy_meta.sh, ci/pipelines/geode-build/deploy_pipeline.sh, ci/pipelines/meta.yml
* Sanitize pipeline names to handle slashes
* deploy release branches to main instead of support branches.
=> [GEODE-5243] Fix deploy scripts and pipeline definitions for releases.

geode-assembly/src/test/java/org/apache/geode/test/junit/rules/GfshRuleTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ExportConfigCommandTest.java
=> GEODE-5245: Unit tests fail on windows due to assertions on paths

geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/ListAsyncEventQueuesCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/domain/AsyncEventQueueDetails.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/functions/ListAsyncEventQueuesFunction.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListAsyncEventQueuesCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ListAsyncEventQueuesTest.java, geode-core/src/test/java/org/apache/geode/test/junit/assertions/CommandResultAssert.java
* Command refactored for cleaner flow
* Command refactored to return ResultModel
* Function refactored to extend CliFunction
-----
=> GEODE-4858: Refactor 'list async-event-queue' command and function

geode-core/src/main/java/org/apache/geode/internal/cache/TXManagerImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/FetchKeysMessage.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/KeySet.java, geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/FetchKeysMessageTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/KeySetTest.java
Please review: @pivotal-eshu @kirklund @agingade @dschneider-pivotal
=> GEODE-5186: set operation in a client transaction could cause the transaction to hang

geode-core/src/main/java/org/apache/geode/management/internal/cli/domain/DataCommandResult.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/QueryCommandIntegrationTest.java
=> GEODE-5247: Gfsh query results contain json instead of object references

etc/eclipse-java-google-style.xml
=> GEODE-5254: Configure spotless to refrain from joining wrapped lines

geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitor.java, geode-core/src/test/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitorJUnitTest.java
Signed-off-by: Michael Oleske <moleske@pivotal.io>
=> GEODE-5268: fixing race condition in GMSHealthMonitor

geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledIteratorDef.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/CompiledIteratorDefJUnitTest.java
=> GEODE-5272: CacheClosedException not wrapped in TypeMismatchException

geode-core/src/main/java/org/apache/geode/internal/i18n/LocalizedStrings.java, geode-cq/src/main/java/org/apache/geode/cache/query/internal/cq/CqServiceImpl.java, geode-cq/src/test/java/org/apache/geode/cache/query/internal/cq/CqServiceImplJUnitTest.java
=> GEODE-5274: Null check for closing CacheClientProxy

geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderEventProcessor.java
=> GEODE-5249: should sync on this.unprocessedEventsLock when iterating

geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunctionSingleHop.java
* This will be visible if debug mode is set.
=> GEODE-3013: Prevent multiple node found error to be displayed in the log

geode-core/src/main/java/org/apache/geode/internal/cache/tx/ClientTXStateStub.java, geode-core/src/test/java/org/apache/geode/internal/cache/tx/ClientTXStateStubTest.java
[GEODE-5277]
Signed-off-by: Jianxia Chen <jchen@pivotal.io>
- [ x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?
- [ x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?
- [x ] Have you written or updated unit tests to verify your changes?
=> GEODE-5277: Release server affinity immediately after commit

geode-core/src/main/java/org/apache/geode/internal/Version.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/CommandInitializer.java
=> Adding 1.8 as a version in Version.java

geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/GfshRule.java
=> GEODE-5212: Fix gfsh rule to use gfsh.bat on windows

geode-core/src/main/java/org/apache/geode/management/internal/cli/result/model/ResultModel.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/result/model/TabularResultModel.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/CreateIndexCommandTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/commands/ExecuteFunctionCommandDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/result/model/ResultModelTest.java, geode-core/src/test/java/org/apache/geode/management/internal/cli/result/model/TabularResultModelTest.java, geode-core/src/test/java/org/apache/geode/test/junit/assertions/AbstractResultModelAssert.java, geode-core/src/test/java/org/apache/geode/test/junit/assertions/CommandResultAssert.java, geode-core/src/test/java/org/apache/geode/test/junit/assertions/DataResultModelAssert.java, geode-core/src/test/java/org/apache/geode/test/junit/assertions/InfoResultModelAssert.java, geode-core/src/test/java/org/apache/geode/test/junit/assertions/TabularResultModelAssert.java, geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshParserRule.java
=> Improving CommandResultAssert

geode-core/src/main/java/org/apache/geode/internal/cache/TXManagerImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXState.java, geode-core/src/test/java/org/apache/geode/internal/cache/TXManagerImplTest.java
…lover.
Co-authored-by: Bradford D. Boyle <bboyle@pivotal.io>
@dhemery Please review.
=> GEODE-5312: Cleanup transaction if it is removed by the client tx failover

geode-core/src/main/java/org/apache/geode/internal/cache/partitioned/PartitionMessage.java, geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/PartitionMessageTest.java
=> GEODE-5310: Modified to check for initialized RegionAdvisor

geode-core/src/test/java/org/apache/geode/cache/client/internal/LocatorSSLJUnitTest.java
=> GEODE-5319: Mark test as integration test.

geode-core/src/main/java/org/apache/geode/internal/InternalDataSerializer.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXCommitMessage.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXRegionState.java, geode-core/src/test/java/org/apache/geode/internal/cache/TxCommitMessageTest.java, geode-core/src/test/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
=>  GEODE-5305: Add flag to TXCommitMessage to indicate the use of shadow key

geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java
=> Geode-5317: Add null check around reconnectDS

geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/DataSerializerPropagationDUnitTest.java
DataSerializerPropagationDUnitTest.testServerUpFirstClientLater didn't
wait for the event to be propagated before checking its value.
Signed-off-by: Scott Jewell <sjewell@pivotal.io>
=> GEODE-5065: fix a race condition in a test.

geode-core/src/main/java/org/apache/geode/internal/util/Hex.java, geode-core/src/main/java/org/apache/geode/pdx/internal/LonerTypeRegistration.java, geode-core/src/main/java/org/apache/geode/pdx/internal/PeerTypeRegistration.java, geode-core/src/main/java/org/apache/geode/pdx/internal/TypeRegistry.java, geode-core/src/test/java/org/apache/geode/pdx/internal/PdxInstanceImplTest.java
Used quite a bit of mocking to remove the dependency on an instance of the cache.
=> GEODE-5285: Make PdxInstanceImplTest a unit test instead of an integration test.

geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/StringQueryProvider.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneIntegerRangeDUnitTest.java
=> Adds in a test for int range lucene query

geode-core/src/test/java/org/apache/geode/test/junit/rules/GfshCommandRule.java
One temp folder will be left after tests complete. This was the behavior
that GfshCommandRule had prior to GEODE-5327. It is caused by the
creation of the temp directory in the constructor of GfshCommandRule. If
the creation happened only in before(), only one temp directory would be
created and cleaned up. However, this would cause some existing DUnit
tests to break, as they use the GfshCommandRule in a way that never
calls before().
The creation of the temp folder was added to before() as part of
GEODE-5327 so that IntelliJ could run DUnit tests multiple times.
Please ensure that once the PR is submitted, you check …
=> GEODE-5330: only create one temp folder

geode-core/src/test/java/org/apache/geode/internal/tcp/TCPConduitDUnitTest.java, geode-core/src/test/java/org/apache/geode/test/dunit/DistributedTestUtils.java
Signed-off-by: Bruce Schuchardt <bschuchardt@pivotal.io>
=> Write a test that hangs without the fix for GEODE-3563.

geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/LauncherLifecycleCommandsDUnitTest.java
=> GEODE-5346: Fix race in LauncherLifecycleCommandsDUnitTest

geode-core/src/test/java/org/apache/geode/pdx/internal/PdxInstanceImplTest.java
- Add unit test for PdxInstance.getField().
- Add unit test for PdxInstance.hasField().
- Add unit test for PdxInstance.isEnum().
- Add unit test for PdxInstance.getClassName().
- Add unit test for PdxInstance.getFieldNames().
- Add unit test for PdxInstance.isIdentityField(). …
=> GEODE-5285: Improve unit test coverage for PdxInstanceImpl.

geode-core/src/test/java/org/apache/geode/internal/cache/execute/PRFunctionExecutionDUnitTest.java
* The test will now wait for result before shutting down
=> GEODE-5352: fixed testLocalDataContextWithColocation 

geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StatusLocatorRealGfshTest.java, geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/GfshScript.java
Signed-off-by: Jens Deppe <jdeppe@pivotal.io>
=> GEODE-5212: Ensure that paths on Windows don't end up with spaces

ci/pipelines/pull-request/base.yml, ci/pipelines/pull-request/pr-template.yml
=> [GEODE-5380] Don't send email on failure as it's unnecessary.

geode-core/src/main/java/org/apache/geode/distributed/internal/direct/DirectChannel.java
=> GEODE-5359: Clear interrupt bit on retry in DirectChannel.sendToMany

ci/pipelines/pull-request/base.yml
=> [GEODE-5380] Missed some email references.

geode-core/src/test/java/org/apache/geode/management/JMXMBeanReconnectDUnitTest.java
=> GEODE-5361: Add wait for MBean federation after member restarts

geode-core/src/main/java/org/apache/geode/management/internal/FederatingManager.java, geode-core/src/main/java/org/apache/geode/management/internal/MBeanJMXAdapter.java, geode-core/src/main/java/org/apache/geode/management/internal/MBeanProxyFactory.java, geode-core/src/main/java/org/apache/geode/management/internal/MBeanProxyInvocationHandler.java, geode-core/src/test/java/org/apache/geode/management/internal/JMXMBeanFederationDUnitTest.java, geode-core/src/test/java/org/apache/geode/management/internal/MBeanFederationErrorPathDUnitTest.java, geode-core/src/test/java/org/apache/geode/test/junit/rules/MemberStarterRule.java
- replicate the bad timing using a DUnit test
- fix the bug by only doing one lookup of MBeans
- add more tests
- fix potential NPE in waiting for regions to be ready on servers
Co-authored-by: Kenneth Howe <khowe@pivotal.io>
=> GEODE-5281: replicate failure and fix bug

geode-core/src/test/java/org/apache/geode/distributed/internal/DlockAndTxlockRegressionTest.java
the test hangs because occasionally performOps would throw an exception before setting the committing flag, and in the finally block, when we tried to do a forceDisconnect to do clean up, we are waiting for that flag to become true to disconnect. Change the test so that at clean up we do forceDisconnect no matter what the flag is.
=> GEODE-5375: fix the test hang when a CommitFailedException happens

geode-core/src/main/java/org/apache/geode/admin/internal/AdminDistributedSystemImpl.java, geode-core/src/main/java/org/apache/geode/internal/SystemAdmin.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/AbortBackupFactory.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupOperation.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/FinishBackupFactory.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/FlushToDiskFactory.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/PrepareBackupFactory.java, geode-core/src/main/java/org/apache/geode/management/internal/BackupStatusImpl.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/DistributedSystemBridge.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/BackupDiskStoreCommand.java, geode-core/src/test/java/org/apache/geode/internal/cache/backup/BackupDistributedTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/backup/BackupOperationTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/backup/IncrementalBackupDistributedTest.java, geode-core/src/test/java/org/apache/geode/internal/cache/partitioned/PersistentPartitionedRegionTestBase.java, geode-core/src/test/java/org/apache/geode/management/internal/BackupStatusImplTest.java
Refactor BackupOperation to make it easier to unit test.
=> GEODE-5398: Add BackupOperationTest and BackupStatusImplTest

geode-core/src/main/java/org/apache/geode/internal/cache/DiskInitFile.java, geode-core/src/main/java/org/apache/geode/internal/cache/Oplog.java, geode-core/src/main/java/org/apache/geode/internal/cache/persistence/DiskInitFileParser.java, geode-core/src/main/java/org/apache/geode/internal/cache/versions/RegionVersionHolder.java, geode-core/src/main/resources/org/apache/geode/internal/sanctioned-geode-core-serializables.txt, geode-core/src/test/java/org/apache/geode/test/dunit/AsyncInvocation.java
Handful of improvements to fix annotations, locations of inner classes, log statements, toString and javadocs.
Each change is in its own commit to facilitate review.
=> GEODE-5390, 5391, 5392: fixup minor issues found during debugging

geode-core/src/test/java/org/apache/geode/test/dunit/rules/MemberVM.java
The test was failing due to insufficient timeout period.
=> GEODE-5407: increase timeout and provide more logging

geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsIntegrationTest.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsWithReindexAllowedIntegrationTest.java
* more test clean up as what was done in GEODE-4989
* Change Dunit tests to integration tests
=> GEODE-5369: fix for Lucene Stats

geode-core/src/main/java/org/apache/geode/cache/client/internal/OpExecutorImpl.java, geode-core/src/main/java/org/apache/geode/cache/client/internal/TXFailoverOp.java, geode-core/src/test/java/org/apache/geode/cache/client/internal/OpExecutorImplJUnitTest.java
=> GEODE-5379: Do not reset affinityRetryCount after executeOnServer successfully to avoid stack overflow

geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneQueriesReindexDUnitTest.java
=> GEODE-5377: wait till threads to finish before exiting the test

geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscDUnitTest.java
=> GEODE-5394: Change to add additional logging in the event of a failure.

buildSrc/src/main/groovy/org/apache/geode/gradle/RepeatTest.groovy, buildSrc/src/main/java/org/apache/geode/gradle/OverriddenTestExecutor.java, gradle.properties, gradle/docker.gradle, gradle/test.gradle
Example
./gradlew repeatTest --tests
PartitionedRegionHADUnitTest.testBucketFailOverDuringCacheClose
-Prepeat=100
=> GEODE-5388: Adding a gradle task to repeat a test

geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-core/src/main/java/org/apache/geode/internal/i18n/LocalizedStrings.java, geode-core/src/main/java/org/apache/geode/management/cli/GfshCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/CliUtil.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/LuceneIndexDestroyedException.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/DestroyLuceneIndexMessage.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneIndexCreationProfile.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneIndexForPartitionedRegion.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneIndexImpl.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneRegionListener.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneServiceImpl.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/LuceneCliStrings.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommands.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneDestroyIndexFunction.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/LuceneIndexDestroyDUnitTest.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/DestroyLuceneIndexCommandsDUnitTest.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsIntegrationTest.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/LuceneIndexCommandsJUnitTest.java, geode-lucene/src/test/java/org/apache/geode/cache/lucene/internal/cli/functions/LuceneDestroyIndexFunctionJUnitTest.java
=> GEODE-5145: Added support for destroying an index during region creation

geode-core/src/test/java/org/apache/geode/pdx/internal/PdxFieldTest.java
=> GEODE-5356: Add unit test for PdxField.

geode-core/src/main/java/org/apache/geode/pdx/internal/PdxReaderImpl.java, geode-core/src/main/java/org/apache/geode/pdx/internal/PdxType.java, geode-core/src/test/java/org/apache/geode/pdx/internal/PdxTypeTest.java
=> GEODE-5357: Add unit test for PdxType.

geode-core/src/test/java/org/apache/geode/pdx/internal/EnumIdTest.java
=> GEODE-5362: Add unit test for EnumId.

geode-core/src/test/java/org/apache/geode/pdx/internal/EnumInfoTest.java
=> GEODE-5367: Add unit test for EnumInfo.

geode-assembly/src/test/java/org/apache/geode/rest/internal/web/RestRegionAPIDUnitTest.java, geode-assembly/src/test/java/org/apache/geode/rest/internal/web/RestSecurityIntegrationTest.java, geode-assembly/src/test/java/org/apache/geode/rest/internal/web/RestSecurityPostProcessorTest.java, geode-assembly/src/test/java/org/apache/geode/rest/internal/web/RestServersIntegrationTest.java, geode-assembly/src/test/java/org/apache/geode/rest/internal/web/SwaggerVerificationIntegrationTest.java, geode-assembly/src/test/java/org/apache/geode/rest/internal/web/controllers/RestAPITestBase.java, geode-assembly/src/test/java/org/apache/geode/rest/internal/web/controllers/RestAPIsAndInterOpsDUnitTest.java, geode-assembly/src/test/java/org/apache/geode/rest/internal/web/controllers/RestAPIsWithSSLDUnitTest.java, geode-assembly/src/test/java/org/apache/geode/rest/internal/web/controllers/RestQueryAndFunctionIntegrationTest.java, geode-assembly/src/test/java/org/apache/geode/test/junit/rules/HttpResponseAssert.java
=> GEODE-5014: Remove usage of org.json from geode-assembly module

geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/GfshRule.java
=> GEODE-5441: Use cmd.exe when invoking gfsh.bat in GfshRule

build.gradle, extensions/geode-modules-session/build.gradle, extensions/geode-modules-tomcat7/build.gradle, extensions/geode-modules-tomcat8/build.gradle, extensions/geode-modules/build.gradle, geode-assembly/build.gradle, geode-connectors/build.gradle, geode-core/build.gradle, geode-cq/build.gradle, geode-experimental-driver/build.gradle, geode-junit/build.gradle, geode-lucene/build.gradle, geode-old-client-support/build.gradle, geode-protobuf/build.gradle, geode-pulse/build.gradle, geode-rebalancer/build.gradle, geode-wan/build.gradle, geode-web-api/build.gradle, geode-web/build.gradle, gradle/test.gradle
=> GEODE-5363: Use nebula.facet plugin to simplify test modules.

geode-core/src/main/java/org/apache/geode/management/internal/cli/util/LogExporter.java
=> GEODE-5448: LogExporter estimates log file size incorrectly on Windows

geode-pulse/src/test/java/org/apache/geode/tools/pulse/tests/Server.java, geode-pulse/src/test/java/org/apache/geode/tools/pulse/tests/rules/ServerRule.java, geode-pulse/src/test/java/org/apache/geode/tools/pulse/tests/rules/WebDriverRule.java, geode-pulse/src/test/java/org/apache/geode/tools/pulse/tests/ui/PulseTestUtils.java
See pull request 2136 for previous pass of comments. Renamed branch due to naming conflict.
=> Geode-5396

geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/StartMemberUtilsTest.java
=> GEODE-5452: StartMemberUtilsTest is not platform agnostic

geode-experimental-driver/src/integrationTest/java/org/apache/geode/experimental/driver/SSLTest.java
=> GEODE-5456: Exceptions during SSL handshake are different for Windows

ci/images/google-geode-builder/scripts/setup.sh
=> [GEODE-5449] Remove unnecessary command and exit if an error occurs.

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/DeprecatedCacheServerLauncherIntegrationTest.java, geode-core/src/test/java/org/apache/geode/test/process/ProcessWrapper.java
- This avoids too long command lines in Windows
=> GEODE-5459: Convert the classpath into a manifest jar for ProcessWrapper

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/backup/BackupIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/internal/cache/backup/UnixScriptGeneratorTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/UnixScriptGenerator.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/WindowsScriptGenerator.java
=> GEODE-5463: Generated restore.bat script is incorrect for Windows

geode-core/src/integrationTest/java/org/apache/geode/distributed/LauncherMemberMXBeanIntegrationTest.java
Verify that JMX MXBean proxy reconstructs correct return type from
CompositeDataSupport. Correct type recontruction of types such as OSMetrics
requires that the mxbean proxy is intantiated from JMX.newMXBeanProxy() not
javax.management.MBeanServerInvocationHandler.newProxyInstance(), which
returns an mbean proxy
=> GEODE-5455: add new tests to verify MemberMXBean method return types

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/wan/asyncqueue/AsyncEventQueueStatsDUnitTest.java
=> GEODE-5097: Wait for dispatcher to pause in AsyncEventQueue test

gradle/test.gradle
* This new task will be used to run GfshTest category tests
on windows.
* Also removed a duplicate integrationTest task
=> GEODE-5212: Added a test task to run Gfsh distributed tests

geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/GfshParserAutoCompletionTest.java, geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/GfshParserParsingTest.java, geode-core/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/HistoryCommandIntegrationTest.java
=> GEODE-5468: Make line separators platform independent

gradle/test.gradle
=> GEODE-5212: Consider property testCategory for upgradeTest gradle task

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitorJUnitTest.java
=> GEODE-5465: prevent calling socket.accept in GMSHealthMonitorJUnitTest

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ExportLogsStatsDUnitTest.java
=> GEODE-5212: Fix ExportLogsStatsDunit on windows

ci/images/alpine-tools/Dockerfile, ci/images/concourse-metadata-resource/Dockerfile, ci/images/concourse-metadata-resource/files/check, ci/images/concourse-metadata-resource/files/in, ci/images/concourse-metadata-resource/files/out, ci/images/google-geode-builder/packer.json, ci/images/google-geode-builder/scripts/cache_dependencies.sh, ci/images/google-geode-builder/scripts/setup.sh, ci/pipelines/clean_fork_pipelines.sh, ci/pipelines/deploy_meta.sh, ci/pipelines/geode-build/base.yml, ci/pipelines/geode-build/deploy_pipeline.sh, ci/pipelines/geode-build/test-stubs/distributed.yml, ci/pipelines/geode-build/test-stubs/integration.yml, ci/pipelines/geode-build/test-stubs/ui.yml, ci/pipelines/geode-build/test-stubs/upgrade.yml, ci/pipelines/geode-build/test-template.yml, ci/pipelines/images/deploy_images_pipeline.sh, ci/pipelines/images/images.yml, ci/pipelines/pull-request/deploy_pr_pipeline.sh, ci/scripts/archive_results.sh, ci/scripts/capture-call-stacks.sh, ci/scripts/execute_tests.sh, ci/scripts/prepopulate_build.sh, ci/scripts/rsync_code_down.sh, ci/scripts/rsync_code_up.sh, ci/scripts/start_instance.sh, ci/scripts/stop_instance.sh, gradle/test.gradle
* Build Google Cloud-based images for launching during test jobs
* refactor test template to use new images.
Signed-off-by: Dick Cavender <dcavender@pivotal.io>
=> [GEODE-5476] Refactor CI to use external instances for test execution.

ci/pipelines/pull-request/base.yml
=> [GEODE-5476] Fix groups definition.

geode-core/src/distributedTest/java/org/apache/geode/management/ClientHealthStatsDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java, geode-core/src/distributedTest/java/org/apache/geode/test/dunit/rules/MemberVM.java, geode-core/src/distributedTest/java/org/apache/geode/test/dunit/rules/tests/MemberStarterRuleTest.java, geode-core/src/integrationTest/java/org/apache/geode/test/junit/rules/LocatorStarterRule.java, geode-core/src/integrationTest/java/org/apache/geode/test/junit/rules/MemberStarterRule.java
500 repeated runs without failure.
=> GEODE-4118/GEODE-5406: rework ClientHealthStatsDUnitTest

geode-core/build.gradle
=> GEODE-5489 Create version properties file less

gradle/test.gradle
=> GEODE-5476: Reduce build output while preserving some sense of progress.

geode-core/src/distributedTest/java/org/apache/geode/distributed/DistributedMemberDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/management/ManagementTestRule.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ClusterDistributionManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionMessage.java, geode-core/src/main/java/org/apache/geode/distributed/internal/InternalDistributedSystem.java, geode-core/src/main/java/org/apache/geode/distributed/internal/LonerDistributionManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/OverflowQueueWithDMStats.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ReplySender.java, geode-core/src/main/java/org/apache/geode/distributed/internal/StartupMessage.java, geode-core/src/main/java/org/apache/geode/distributed/internal/StartupMessageReplyProcessor.java, geode-core/src/main/java/org/apache/geode/distributed/internal/StartupOperation.java, geode-core/src/main/java/org/apache/geode/distributed/internal/ThrottlingMemLinkedQueueWithDMStats.java, geode-core/src/main/java/org/apache/geode/distributed/internal/locks/DLockService.java, geode-core/src/main/java/org/apache/geode/distributed/internal/locks/GrantorRequestProcessor.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/MembershipManager.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/interfaces/Messenger.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/JGroupsMessenger.java, geode-core/src/main/java/org/apache/geode/distributed/internal/membership/gms/mgr/GMSMembershipManager.java, geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java, geode-core/src/main/java/org/apache/geode/internal/tcp/ConnectExceptions.java, geode-core/src/main/java/org/apache/geode/internal/tcp/DirectReplySender.java, geode-core/src/main/java/org/apache/geode/management/internal/FederatingManager.java, geode-core/src/main/java/org/apache/geode/management/internal/MemberMessenger.java, geode-core/src/main/java/org/apache/geode/management/internal/messages/CompactRequest.java, geode-lucene/src/distributedTest/java/org/apache/geode/cache/lucene/internal/management/LuceneManagementDUnitTest.java, geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/GatewayReceiverMBeanDUnitTest.java
* Augment various collections to use generics
* Inline some iterator loops that were trivially "foreach" loops
* remove unused code
* Inline some redundant local variables
* make some methods more private
* change some tests to use `InternalDistributedMember` instead of
`DistributedMember`.
* Make  `ThrottlingMemLinkedQueueWithDMStats` generic and use atomic.
- The previous synchronization looked quite wrong.
In particular, there are some (I'm pretty sure more correct) functional changes to  `ThrottlingMemLinkedQueueWithDMStats`. Some of the unused methods were on interfaces, but they were on internal interfaces so I don't think it should be an issue.
- [n/a] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF …
=> GEODE-5464: Generify DistributionManager and related classes

ci/pipelines/meta.yml, ci/pipelines/reaper.yml, ci/scripts/start_instance.sh
concourse instances now have ttl
and are stopped and eventually
deleted by a reaper pipline
=> GEODE-5496 create reaper pipeline

geode-core/src/distributedTest/java/org/apache/geode/internal/jta/ClientServerJTAFailoverDistributedTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXState.java, geode-core/src/test/java/org/apache/geode/internal/cache/TXStateTest.java
=> GEODE-5400: Cleanup locks if held during TXState.close.

geode-protobuf/src/distributedTest/java/org/apache/geode/internal/protocol/protobuf/v1/acceptance/LocatorConnectionDUnitTest.java
=> GEODE-5451: Use awaitility to resolve race condition in test

ci/pipelines/geode-build/test-template.yml, ci/pipelines/pull-request/pr-template.yml, ci/scripts/start_instance.sh
=> GEODE-5500 retry start_instance on failure

gradle/test.gradle
=> GEODE-5510 remove bad dependency between acceptanceTest and upgradeTest

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/backup/BackupIntegrationTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/BackupWriter.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/FileSystemBackupWriter.java, geode-core/src/main/java/org/apache/geode/internal/cache/backup/UnixScriptGenerator.java
=> GEODE-5497: Generated restore.sh script fails when incremental backups are restored

geode-core/src/integrationTest/java/org/apache/geode/internal/statistics/GemFireStatSamplerIntegrationTest.java, geode-core/src/integrationTest/java/org/apache/geode/test/dunit/standalone/ProcessManager.java
=> GEODE-5512: Do not test for OS process stats on Windows

gradle/java.gradle
=> GEODE-5508: Fix encoding build errors on Windows

geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/PartitionedRegionCompactRangeIndexDUnitTest.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/CompactMapRangeIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/CompactRangeIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/HashIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/IndexProtocol.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/MapRangeIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/RangeIndex.java, geode-core/src/main/java/org/apache/geode/internal/cache/AbstractRegionMap.java, geode-core/src/test/java/org/apache/geode/internal/cache/AbstractRegionMapTest.java, geode-core/src/test/resources/org/apache/geode/cache/query/dunit/PersistentPartitionWithIndex.xml
* Removed no-op method and method call
* Added tests and refactored to use ClusterStarterRule
=> GEODE-5433: Indexes are updated with the correct old value from gii

ci/images/google-geode-builder/packer.json, ci/images/google-geode-builder/scripts/setup.sh, ci/scripts/start_instance.sh
* Add stackdriver agent to google-geode-builder.
* Add labels identifying heavy-lifters
Signed-off-by: Patrick Rhomberg <prhomberg@pivotal.io>
=> [GEODE-5519] Add stackdriver monitoring to instances.

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ClientServerTransactionFailoverWithMixedVersionServersDistributedTest.java
=> GEODE-5524: Fix a race by waiting on correct condition.

geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/ResourceManagerWithQueryMonitorDUnitTest.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/DefaultQuery.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/QueryMonitor.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionQueryEvaluator.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/QueryMonitorTest.java, geode-cq/src/distributedTest/java/org/apache/geode/cache/query/dunit/QueryMonitorDUnitTest.java
* reuse common vms among all the tests. start/stop additional clients and servers as needed in the tests.
* code cleanup.
* add QueryMonitor unit test
* do not add cq query to the monitor queue
=> GEODE-577: rewrite QueryMonitorDUnitTest

geode-core/src/main/java/org/apache/geode/internal/cache/LocalRegion.java, geode-lucene/src/main/java/org/apache/geode/cache/lucene/internal/LuceneServiceImpl.java
=> Revert "GEODE-5197: Synchronized update cache service profile in lucene"

geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/ResourceManagerWithQueryMonitorDUnitTest.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/DefaultQuery.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/QueryMonitor.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionQueryEvaluator.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/QueryMonitorTest.java, geode-cq/src/distributedTest/java/org/apache/geode/cache/query/dunit/QueryMonitorDUnitTest.java
The previous change was reverted due to test pollution.
This is a resubmission of the PR and proper cleanup of the junit test
=>  GEODE-577: rewrite QueryMonitorDUnitTest and fix QueryMonitorTest

geode-core/src/integrationTest/java/org/apache/geode/distributed/LocatorLauncherRemoteIntegrationTest.java
Signed-off-by: Sai Boorlagadda <sboorlagadda@pivotal.io>
=> GEODE-5212: Fix launcher test failures

geode-core/src/integrationTest/java/org/apache/geode/cache30/MultiVMRegionTestCase.java
=> GEODE-5499: Changing testTxRmtMirror to use awaitility, not 200 ms sleep

ci/pipelines/pull-request/base.yml, ci/pipelines/pull-request/deploy_pr_pipeline.sh, ci/pipelines/pull-request/pr-template.yml
Signed-off-by: Dick Cavender <dcavender@pivotal.io>
=> [GEODE-5539] remove pr tags from jobs, provide sane defaults.

ci/scripts/start_instance.sh
* Explicitly state what network and subnet to launch the instance in.
=> [GEODE-5545] Modify instance creation.

ci/pipelines/pull-request/base.yml, ci/pipelines/pull-request/pr-template.yml
=> [GEODE-5545] Use develop branch for executing scripts.

geode-junit/src/main/java/org/apache/geode/util/test/TestUtil.java
=> GEODE-5212: use Paths.get to retrieve resourcePath

geode-core/src/integrationTest/java/org/apache/geode/distributed/LauncherMemberMXBeanIntegrationTest.java
=> GEODE-5212: Account for dynamic values returned from metrics MBean

ci/pipelines/geode-build/windows-test-template.yml
=> GEODE-5212: run windows jobs in serial

ci/images/test-container/Dockerfile
Signed-off-by: Dick Cavender <dcavender@pivotal.io>
=> [GEODE-5580] Convert test-container image to use alpine.

geode-junit/src/main/java/org/apache/geode/test/junit/rules/ConcurrencyRule.java, geode-junit/src/test/java/org/apache/geode/test/junit/rules/ConcurrencyRuleTest.java
=> GEODE-5438: Add rule for running threads in tests

geode-core/src/main/java/org/apache/geode/management/internal/JettyHelper.java
=> GEODE-5587: Randomize HTTP service working directory

geode-core/src/main/java/org/apache/geode/internal/cache/TXManagerImpl.java, geode-core/src/test/java/org/apache/geode/internal/cache/TXManagerImplTest.java
=> GEODE-5592: Release the lock in a finally block.

geode-pulse/src/integrationTest/java/org/apache/geode/tools/pulse/controllers/PulseControllerJUnitTest.java, geode-pulse/src/main/java/org/apache/geode/tools/pulse/internal/controllers/PulseController.java, geode-pulse/src/main/webapp/scripts/pulsescript/pages/DataBrowserQuery.js
=> GEODE-5571: Added query to history before query execution

geode-core/src/main/java/org/apache/geode/internal/cache/versions/RVVExceptionB.java, geode-core/src/test/java/org/apache/geode/internal/cache/versions/RVVExceptionJUnitTest.java
=> GEODE-5612: Fix RVVExceptionB.writeReceived()

ci/docker/Dockerfile
=> GEODE-5613: Add winrm-cli utility to apachegeode-build image

gradle/test.gradle
=> GEODE-5620: Adds project property to control test forking.

ci/docker/Dockerfile, ci/images/alpine-tools/Dockerfile
- This also reverts the previous commit which changed the wrong docker image.
=> GEODE-5613: Add winrm-cli for Windows CI support

geode-core/src/distributedTest/java/org/apache/geode/management/internal/pulse/TestFunctionsDUnitTest.java, geode-dunit/src/main/java/org/apache/geode/internal/cache/functions/TestFunction.java
The base issue was a timing issue in the way the code was setup. Made the code more deterministic
=> GEODE-5460: Fixing a timing issue.

geode-assembly/src/integrationTest/java/org/apache/geode/AssemblyContentsIntegrationTest.java
=> GEODE-5597 let AssemblyContentsIntegrationTest pass on windows

geode-core/src/integrationTest/java/org/apache/geode/distributed/internal/membership/gms/messenger/GMSEncryptJUnitTest.java
This test was not capturing exceptions from the background threads.
Using ConcurrenyRule to execute the background tests.
=> GEODE-5629: Changing GMSEncryptJUnitTest to use ConcurrencyRule

geode-connectors/src/acceptanceTest/java/org/apache/geode/test/junit/rules/MySqlConnectionRule.java, geode-connectors/src/acceptanceTest/java/org/apache/geode/test/junit/rules/SqlDatabaseConnectionRule.java, geode-core/src/distributedTest/java/org/apache/geode/cache/client/internal/AutoConnectionSourceDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/QueryIndexUsingXMLDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/EntriesDoNotExpireDuringGiiRegressionTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/wan/asyncqueue/ParallelAsyncEventListenerDistributedTest.java, geode-core/src/distributedTest/java/org/apache/geode/management/JMXMBeanReconnectDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/management/internal/pulse/TestClientIdsDUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/internal/cache/tier/sockets/CacheClientNotifierIntegrationTest.java, geode-core/src/test/java/org/apache/geode/cache/client/internal/SingleHopClientExecutorSubmitTaskWithExceptionTest.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/QueryMonitorTest.java, geode-cq/src/distributedTest/java/org/apache/geode/cache/ClientStatisticsPublicationSecurityDUnitTest.java, geode-cq/src/upgradeTest/java/org/apache/geode/internal/cache/tier/sockets/ClientServerMiscBCDUnitTest.java, geode-lucene/src/distributedTest/java/org/apache/geode/cache/lucene/ExpirationDUnitTest.java, geode-lucene/src/integrationTest/java/org/apache/geode/cache/lucene/LuceneIndexCreationPersistenceIntegrationTest.java, geode-lucene/src/upgradeTest/java/org/apache/geode/cache/lucene/LuceneSearchWithRollingUpgradeDUnit.java
I reviewed all usages of Awaitility untilAsserted and found a couple more that should be using until. I also found a couple usages that I decided to tidy up just a bit.
=> GEODE-5630: fixup usage of Awaitility

build.gradle
=> GEODE-5642 remove gradle task :cleanAll

ci/images/google-geode-builder/build_image.sh, ci/pipelines/README.md, ci/pipelines/clean_fork_pipelines.sh, ci/pipelines/deploy_meta.sh, ci/pipelines/examples/deploy_pipeline.sh, ci/pipelines/geode-build/deploy_pipeline.sh, ci/pipelines/images/deploy_images_pipeline.sh, ci/pipelines/meta.yml, ci/pipelines/pull-request/deploy_pr_pipeline.sh, ci/pipelines/render.py, ci/pipelines/shared/shared_jinja.yml, ci/pipelines/shared/utilities.sh, ci/scripts/start_instance.sh
=> Geode 5608 2 truncate fork/branch names in image/instance naming

geode-dunit/src/main/java/org/apache/geode/test/dunit/rules/ClusterStartupRule.java
=> GEODE-5650: Improve ClusterStartupRule tear down

geode-cq/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DescribeClientCommandDUnitTest.java
=> GEODE-5636: DescribeClientCommandDUnitTest fails on Windows

geode-assembly/src/integrationTest/java/org/apache/geode/test/junit/rules/GeodeHttpClientRule.java, geode-assembly/src/integrationTest/java/org/apache/geode/tools/pulse/PulseSecurityWithSSLTest.java, geode-core/src/main/java/org/apache/geode/management/internal/ManagementAgent.java
=> GEODE-5661: Pulse does not work when legacy SSL options are used

geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/CqDataDUnitTest.java, geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/CqPerfDUnitTest.java, geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/dunit/CqQueryDUnitTest.java
- Code modernization and cleanup
Key changes are the Awaitility calls at line 976 and 986 in CqPerfDUnitTest.java
=> GEODE-5411: Fixing timing issue

ci/scripts/start_instance.sh
=> [GEODE-5664] delete instance before trying to create it.

ci/pipelines/pull-request/jinja.template.yml
- [ x Does `gradlew build` run cleanly?
=> GEODE-5600: Update pull-request template to expected environment.

ci/pipelines/geode-build/deploy_pipeline.sh, ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/shared/jinja.variables.yml, ci/pipelines/shared/shared_jinja.yml, ci/scripts/archive_results.sh, ci/scripts/build.sh, ci/scripts/execute_build.sh, ci/scripts/shared_utilities.sh
* Build now provisions an external worker, similar to other testing
jobs.
* Add execute_build.sh, to be combined with existing execute_tests.sh in
GEODE-5659.
* Increase verbosity during testing
* Correct issue with extra newline in Jinja templating of pipelines
* Introduce a shared_utilities.sh for bash functions
* Multiple whitespace adjustments
* Build artifacts are now tar'd in archive_results.sh
* * This is achieved with the test env parameter
TAR_GEODE_BUILD_ARTIFACTS
* Remove block for sending build-success email, as this is never done
------
The spin-out of `shared_utilities.sh` helped to understand the script during iteration.  However, as it stands, the utility of that file is not, in fact, shared.  It wasn't clear to me whether or not it improves readability within the script …
=> GEODE-5657: Build job now behaves like test job.

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionIntegrationTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/OriginalServerConnection.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/ServerConnection.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/AddPdxEnum.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/AddPdxType.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/GetFunctionAttribute.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/GetPDXEnumById.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/GetPDXIdForEnum.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/GetPdxEnums70.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/GetPdxTypes70.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/RegisterInstantiators.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/ServerConnectionTest.java, geode-cq/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/MonitorCQ.java
- also cleaned up naming and modernized sections that were able to be more modern
- also apparently forgot that force pushing over a branch while a PR is closed makes github unhappy, so opening a new one (and hopefully test issues were resolved this time around)
The original ticket calls out two things
1. Removing `authzrequest` private variable which is no longer used in any meaningful way
1. Checking if `getAuthzRequest` is used
`getAuthzRequest` is used in quite a lot of spots, but the second commit removes calls that do not care about the result.  If the maintainers end up not liking that but like the remove of private …
=> GEODE-3200 remove authzrequest

geode-core/src/main/java/org/apache/geode/cache/query/internal/index/AbstractIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/CompactRangeIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/HashIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/PrimaryKeyIndex.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/index/PrimaryKeyIndexTest.java, geode-cq/src/distributedTest/java/org/apache/geode/cache/query/cq/CQDistributedTest.java
=> GEODE-5678: Primary key index results are wrapped in CqEntry for cq

geode-junit/src/main/java/org/apache/geode/test/junit/rules/ConcurrencyRule.java, geode-junit/src/test/java/org/apache/geode/test/junit/rules/ConcurrencyRuleTest.java
=> GEODE-5684: Add option to check type of cause

ci/images/google-geode-builder/build_image.sh, ci/pipelines/clean_fork_pipelines.sh, ci/pipelines/examples/deploy_pipeline.sh, ci/pipelines/geode-build/deploy_pipeline.sh, ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/images/deploy_images_pipeline.sh, ci/pipelines/meta/deploy_meta.sh, ci/pipelines/meta/jinja.template.yml, ci/pipelines/pull-request/deploy_pr_pipeline.sh, ci/pipelines/shared/utilities.sh
* Use jinja templating with meta pipeline deployment.
* Remove unnecessary jobs from deployed pipelines for forks.
* Move meta pipeline into its own subdirectory.
=> GEODE-5687 - Improve pipeline deployment for forks.

ci/pipelines/shared/utilities.sh, ci/scripts/start_instance.sh
=> GCP instances dont like underscores either? Using hyphen

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/PersistentRegionTransactionDUnitTest.java
=> GEODE-5527: get an available port at server start

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandDUnitTest.java, geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/StartServerCommandDUnitTest.java
=> GEODE-5212: use Paths instead of hardcoded file separator

geode-core/src/integrationTest/java/org/apache/geode/distributed/LocatorLauncherJmxManagerLocalRegressionTest.java
- Other threads that might be messing up this test are Gradle worker threads
that may not be present at the end.
=> GEODE-5673: Adjust for new Awaitility thread count

geode-core/src/main/java/org/apache/geode/DataSerializer.java, geode-core/src/main/java/org/apache/geode/internal/InternalDataSerializer.java, geode-core/src/main/java/org/apache/geode/internal/util/DscodeHelper.java, geode-core/src/test/java/org/apache/geode/internal/DSCODETest.java
=> GEODE-5705: Improve basicReadObject to use switch statement rather than if

ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/shared/jinja.variables.yml, ci/scripts/execute_tests.sh, ci/scripts/rsync_code_down.sh, ci/scripts/start_instance.sh, gradle.properties
=> GEODE-5668: Switch Windows build jobs to 'heavy-lifter' model

ci/images/google-windows-geode-builder/build_image.sh, ci/images/google-windows-geode-builder/windows-packer.json, ci/pipelines/images/images.yml
=> GEODE-5709: Add CI job to build Windows images

geode-assembly/build.gradle
Zip archive is removed from publication list.
Zip distribution tasks are disabled by default, but may be explicitly
asked for on the command line.
Combined taskGraph tasks in the same Gradle file into one call.
=> GEODE-5694 Do not create or publish zip distributions

gradle/publish.gradle
=> GEODE-5723: Don't publish to maven repo unless SNAPSHOT.

geode-core/src/distributedTest/java/org/apache/geode/distributed/GrantorFailoverDUnitTest.java
=> GEODE-5712: Increase Awaitility timeout

BUILDING.md
=> Adding IntelliJ setup instructions to BUILDING.md

geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
=> GEODE-5725: Using string values to exercise off-heap

geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/GfshExecution.java, geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/GfshRule.java, geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/GfshScript.java, geode-junit/src/main/java/org/apache/geode/test/junit/rules/gfsh/internal/ProcessLogger.java
* makes the output of the process easier to read.
* add the capability to chain commands into one GfshScript
* add the capability to specify debug port in GfshScript
* reworked the code a bit for easy reading.
=> GEODE-5716: GfshRule improvement

buildSrc/src/test/java/org/apache/geode/javac/CompilerException.java, buildSrc/src/test/java/org/apache/geode/javac/TestAnnotationProcessor.java, buildSrc/src/test/java/org/apache/geode/javac/TestCompiler.java
=> GEODE-3: remove dependency on sun.tools.java.CompilerError

geode-core/src/main/java/org/apache/geode/internal/SharedLibrary.java, geode-core/src/main/java/org/apache/geode/internal/lang/SystemUtils.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/util/JdkTool.java, geode-core/src/test/java/org/apache/geode/internal/lang/SystemUtilsJUnitTest.java, geode-junit/src/main/java/org/apache/geode/codeAnalysis/AnalyzeSerializablesJUnitTestBase.java
=> GEODE-3: not use our own SystemUtils to find java version

geode-core/src/main/java/org/apache/geode/internal/cache/DistributedCacheOperation.java, geode-core/src/test/java/org/apache/geode/internal/cache/CacheOperationMessageTest.java
the notifyOnly message to trigger callbacks
And computeCompressedShort should not pack inhibitAllNotifications
=> GEODE-5729: when DistributedCacheOperation needs 2 messages, should let

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandDUnitTest.java
Tests using relative paths had depended on running as a user other than root.
The tests expected that file or directory creation would fail because the user
would not have permission to write to '/'.
A further problem was the several tests had hard-coded '/' in pathnames,
which is incompatible with running on Windows.
=> GEODE-5741: Modified tests to be independant of environment

geode-core/src/integrationTest/java/org/apache/geode/internal/cache/DiskRegionJUnitTest.java
=> GEODE-4273: Fix failing testBug41822 on windows

README.md, TESTING.md
=> Adding TESTING.md

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientQueueSizeDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientReconnectDUnitTest.java, geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientCQDUnitTest.java, geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientCrashDUnitTest.java, geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientHAQueuedDUnitTest.java, geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientNetDownDUnitTest.java, geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientSimpleDUnitTest.java, geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientTestBase.java, geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientTestCase.java, geode-dunit/src/main/java/org/apache/geode/internal/cache/tier/sockets/CacheServerTestUtil.java
This code was not in a good state. So the code has been refactored to not only address issues
where the code was giving bad feedback, but to address the impressive structural duplication.
Things done:
-Extracted a bunch of methods
-Added new Test files for test subjects that should have been separate
-Split out a base class so there was no inheritance of test classes to do basic things.
-Reparented classes that were inheriting from test classes
Co-Authored-By: Galen O'Sullivan <gosullivan@pivotal.io> …
=> Geode 5428: Refactored DurableClientTests due to massive duplication

geode-web/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ConnectCommandWithSSLTest.java
- Adding a pattern to match which is the bugfix
- Duplication reduction for readability
=> GEODE-3720: adding more error conditions

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/RedundancyLevelPart1DUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/RedundancyLevelPart2DUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/RedundancyLevelPart3DUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/RedundancyLevelTestBase.java
Co-Authored-By: Bill Burcham <bburcham@pivotal.io>
=> GEODE-369: wait for primary to be available when going from 0 to 1 server

geode-assembly/build.gradle
=> GEODE-5694: fix zip disable now after removal of maven plugin

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ExportLogsOnServerManagerDUnit.java, geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/ExportLogsWithMemberGroupDUnitTest.java
=> GEODE-5212: Make paths platform agnostic

geode-core/src/distributedTest/java/org/apache/geode/cache30/DistributedAckRegionCCEDUnitTest.java
* The revert of previous code was missing test changes due to geode test structure changes
=> GEODE-3967: Cleaning up of revert issues

geode-core/src/distributedTest/java/org/apache/geode/cache/client/internal/ClientServerHostNameVerificationDistributedTest.java
=> GEODE-5212: Also use the host's canonical (fully qualified) name as a SAN in the certificate

geode-core/src/distributedTest/java/org/apache/geode/management/JMXMBeanReconnectDUnitTest.java
These tests are failing and causing CI job to hang. So
ignoring them until they are fixed.
=> GEODE-5794: ignore JMXMBeanRecommentDUnitTest on windows

geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/AggregateRegionStatsMonitor.java, geode-core/src/main/java/org/apache/geode/management/internal/beans/stats/MemberLevelDiskMonitor.java, geode-core/src/test/java/org/apache/geode/management/internal/beans/stats/AggregateRegionStatsMonitorTest.java, geode-core/src/test/java/org/apache/geode/management/internal/beans/stats/MemberLevelDiskMonitorTest.java
=> GEODE-5523: Fixed NPE by converting remaining getOrDefault calls

geode-core/src/main/java/org/apache/geode/distributed/internal/RuntimeDistributionConfigImpl.java
One more config class to cleanup before logging changes are made.
=> GEODE-2644: Cleanup RuntimeDistributionConfigImpl

geode-web/src/test/java/org/apache/geode/management/internal/web/controllers/support/LoginHandlerInterceptorTest.java
Several of the tests in `LoginHandlerInterceptorTests` each exercised multiple responsibilities, making it harder to diagnose failures.
This commit extracts those multiple responsibilities into focused tests of their own.
@kirklund @mhansonp @balesh2
=> GEODE-5805: Extract LoginHandlerInterceptor tests

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ClientServerTransactionDUnitTest.java
=> GEODE-5792: ClientServerTransactionDUnitTest occasionally fails on Windows

build.gradle, gradle/resolve-dependencies.gradle
=> GEODE-5812: Adds task to resolve and download dependencies.

ci/pipelines/geode-build/jinja.template.yml
=> GEODE-5814: Move Windows CI jobs to 'main' group

ci/bin/concourse_job_performance.py
=> GEODE-5777: Improvements for concourse_job_performance

geode-core/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/DestroyRegionCommandDUnitTest.java
=> GEODE-5824: DestroyRegionCommandDUnitTest tests failed in java 10

geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/WANTestBase.java
=> GEODE-5829: Bind locator to 0.0.0.0 instead of localhost

geode-core/src/test/java/org/apache/geode/internal/cache/BeforeCompletionTest.java
Signed-off-by: Kirk Lund <klund@apache.org>
=> GEODE-5212: fix timing issues in BeforeCompletionTest

geode-core/src/distributedTest/java/org/apache/geode/management/JMXMBeanReconnectDUnitTest.java
=> GEODE-5794: fix failing JMXMBeanReconnectDUnitTest

geode-core/src/main/java/org/apache/geode/internal/SystemAdmin.java
- [] Have you written or updated unit tests to verify your changes?
=> GEODE-5844: Eliminating String.Format() calls from initHelpMap()

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/ClientServerTransactionFailoverDistributedTest.java, geode-core/src/main/java/org/apache/geode/internal/cache/TXCommitMessage.java
Co-authored-by: @pivotal-eshu 
This ticket is already closed by the checkin db8ba67d98d75aeb0e72b55274757e67f69c9c51
This PR is to add a dunit test to reproduce and verify the fix.
Also, incorporated the release comments missed out in the previous checkin.
- [Yes] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?
- [No] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?
- [Yes] Is your initial contribution a single, squashed commit?
- [Yes] Does `gradlew build` run cleanly?
- [Yes] Have you written or updated unit tests to verify your changes?
- [NA] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF …
=> GEODE-5828: Add dunit test reproducing the issue and incorporate review changes

geode-core/src/main/java/org/apache/geode/management/internal/beans/ManagementListener.java
Should not block the system notifications for membership changes.
@boglesby @sboorlagadda 
Co-authored-by: Sai Boorlagadda <sboorlagadda@pivotal.io>
=> GEODE-5252: handleCacheRemoval() could wait for distribution's replies.

geode-core/src/test/java/org/apache/geode/internal/cache/AfterCompletionTest.java
=> GEODE-5212:  fix timing issues in AfterCompletionTest

ci/scripts/execute_tests.sh, gradle.properties, gradle/test.gradle
=> GEODE-5848 conditionally add --add-opens for test jvm versions 9 and up

geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandDUnitTest.java, geode-assembly/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/StartServerCommandDUnitTest.java, geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandTest.java, geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandWorkingDirectoryTest.java, geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartServerCommandTest.java, geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartServerCommandWorkingDirectoryTest.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommand.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartMemberUtils.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/StartServerCommand.java
* Added unit tests to cover different working directory cases
* Removed acceptance tests related to working directory as they
seem to be fragile as paths are environment specific
Signed-off-by: Kirk Lund <klund@apache.org>
=> GEODE-5212: fix failing StartLocator and Server command DUnit tests

geode-dunit/src/main/java/org/apache/geode/security/templates/SimpleAccessController.java, geode-dunit/src/main/java/org/apache/geode/security/templates/SimpleAuthenticator.java
GEODE-5838: Fix warnings in javadocs generation
=> GEODE-5838: Fix warnings in javadocs generation

geode-junit/src/main/java/org/apache/geode/test/dunit/standalone/VersionManager.java
=> GEODE-5821: exclude geode 1.4 when testing with java 9+

geode-cq/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/DurableClientTestCase.java
On windows it is observed that asserting the queue size to be 1
fails sometimes as it can be 2. So a wait is added to make sure
the queue sz becomes zero before a durable client is restarted.
=> GEODE-5858: fix failing DurableClientTestCase on Windows

build.gradle, ci/pipelines/shared/jinja.variables.yml, gradle/docker.gradle
=> GEODE-5851 use gradle-dockerized-test-plugin compiled with Java 8

ci/pipelines/geode-build/jinja.template.yml
=> GEODE-5855 hide jobs that are not gating in default pipeline view

geode-assembly/geode-assembly-test/src/main/java/org/apache/geode/session/tests/ContainerInstall.java
- Convert to URL in the form file:/c:/foo/bar instead of file://c:/foo/bar
=> GEODE-5811: Fix failing test on windows

ci/pipelines/meta/jinja.template.yml, ci/pipelines/pull-request/deploy_pr_pipeline.sh
=> [GEODE-5864] Fix render.py call.

ci/pipelines/meta/jinja.template.yml, ci/pipelines/pull-request/deploy_pr_pipeline.sh
=> [GEODE-5864] Change pr pipeline deploy model to match other pipelines.

ci/pipelines/meta/jinja.template.yml
=> [GEODE-5864] Fix template yaml.

ci/images/alpine-tools/Dockerfile, ci/pipelines/geode-build/deploy_pipeline.sh, ci/pipelines/meta/jinja.template.yml
=> Fix up variables and base alpine-tools on openjdk:8-alpine.

ci/images/alpine-tools/Dockerfile
=> [GEODE-5864] Remove go and make once we're done with them.

ci/pipelines/geode-build/deploy_pipeline.sh
=> [GEODE-5864] We lost version-bucket somehow.

ci/pipelines/geode-build/deploy_pipeline.sh
=> [GEODE-5864] We lost dumping out the pipeline somehow. Put it back.

ci/pipelines/geode-build/jinja.template.yml
=> [GEODE-5864] Fix trigger indentation.

ci/pipelines/geode-build/jinja.template.yml
=> [GEODE-5864] Indentation is still hard.

ci/pipelines/geode-build/jinja.template.yml
=> [GEDOE-5864] Iteration over indentation will eventually succeed.

ci/scripts/execute_publish.sh
=> [GEODE-5864] Remove unnecessary echo.

ci/pipelines/geode-build/jinja.template.yml
=> [GEODE-5864] Add missing input to publish task.

ci/pipelines/geode-build/jinja.template.yml
=> [GEODE-5864] We need the java build version now.

geode-assembly/build.gradle, geode-core/src/main/java/org/apache/geode/internal/cache/EntriesSet.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegion.java, geode-core/src/main/java/org/apache/geode/internal/net/SocketCreator.java, geode-core/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java
=> GEODE-5880: fix IDEA compiling error when using jdk11

ci/scripts/start_instance.sh
=> [GEODE-5864] Add storage-rw to scopes when launching instances.

ci/pipelines/geode-build/jinja.template.yml
=> [GEODE-5864] Use alpine-tools for UpdatePassingRef.

ci/pipelines/meta/jinja.template.yml
=> [GEODE-5864] Remove old set-metrics-pipeline job.

ci/pipelines/meta/jinja.template.yml
=> [GEODE-5864] Fix name of create yml job.

ci/pipelines/meta/jinja.template.yml
=> [GEODE-5864] Fix script call.

ci/pipelines/meta/jinja.template.yml
=> [GEODE-5864] Fix up final changes to metrics.

ci/pipelines/meta/jinja.template.yml
=> [GEODE-5864] Fix metrics pipeline resource paths value.

ci/pipelines/meta/jinja.template.yml, ci/pipelines/metrics/deploy_metrics_pipeline.sh
=> [GEODE-5864] push concourse-url down to metrics pipeline.

geode-old-versions/build.gradle
* as 1.7.0 has been released, this version must be tested against the current snapshot
* thus 1.7.0 has been added to the build.gradle file of the geode-old-version project.
=> GEODE-5852: Adding 1.7.0 to old version

ci/scripts/stop_instance.sh
=> Delete instances, don't stop them.

ci/scripts/execute_tests.sh
=> GEODE-5907 patch gradle in a cross-platform-friendly way

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/NetSearchMessagingDUnitTest.java
In several tests, a listener calls disconnectFromDS() to disconnect its member when a certain event occurs.
The tests do not wait for the listener to finish disconnecting.
When the tests end, the cleanup also calls `disconnectFromDS()` to disconnect the same member.
Within `disconnectFromDS()`, `InternalDistributedSystem.disconnect()` is called twice, once on the system the test framework knows about, and once on whatever system `InternalDistributedSystem.getConnectedInstance()` returns.
If two calls to `disconnect()` are in progress at the same time, one blocks until the other finishes.
If the test ends before the listener finishes, the listener appears to wait until a later test reuses the same VM, at which time it disconnects whatever system it finds there. We do not know why it waits. …
=> GEODE-5501: Wait for listener to disconnect

geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/cli/commands/ConnectCommandAcceptanceTest.java
=> GEODE-5846: can not start 1.3 gfsh with jdk9.

ci/pipelines/meta/deploy_meta.sh
* explain how to install gcloud, if it isn't already installed
* work around concourse hiccups like reg/orange/brown jobs by retriggering them (once per invocation of deploy_meta)
* ensure window image is ready before starting windows jobs for the first time
* print nice progress indicators rather than spewing pages of debug while waiting for jobs
* display the correct URL when the pipeline is up
* don't pause golden reaper, and don't pause already-unpaused jobs on re-deploy
- [n/a] If adding new dependencies to …
=> GEODE-5889 deploy_meta improvements

ci/pipelines/examples/deploy_pipeline.sh, ci/pipelines/meta/jinja.template.yml
* Change examples pipeline deployment method to match other pipelines.
=> [GEODE-5916] Refactor examples pipeline definition.

ci/pipelines/examples/jinja.template.yml, ci/pipelines/shared/jinja.variables.yml, ci/scripts/execute_build_examples.sh
=> GEODE-5916: more refactoring.

ci/pipelines/examples/jinja.template.yml, ci/pipelines/shared/jinja.variables.yml, ci/scripts/execute_build_examples.sh
=> Geode 5916

ci/pipelines/examples/jinja.template.yml
=> GEODE-5916: Add concourse-metadata-resource.

ci/pipelines/examples/jinja.template.yml
=> GEODE-5916: Indentation is SUPER HARD.

ci/pipelines/examples/jinja.template.yml
=> GEODE-5916: Indentation insanity.

ci/pipelines/examples/jinja.template.yml
=> GEODE-5916: Indentation.

ci/pipelines/examples/jinja.template.yml
=> GEODE-5916: Fix concourse-metadata-resource.

ci/pipelines/examples/jinja.template.yml, ci/scripts/execute_build_examples.sh
=> Change geode-examples path to geode so it's compatible with scripts.

ci/pipelines/examples/jinja.template.yml
=> GEODE-5916: path is applied to inputs not gets.

ci/pipelines/examples/jinja.template.yml
=> GEODE-5916: INDENTATION!

extensions/geode-modules-session-internal/build.gradle, extensions/geode-modules-session/build.gradle, extensions/geode-modules-test/build.gradle, extensions/geode-modules-tomcat7/build.gradle, extensions/geode-modules-tomcat8/build.gradle, extensions/geode-modules/build.gradle, extensions/session-testing-war/build.gradle
=> GEODE-5886: Make dependencies explicit in extensions modules.

ci/pipelines/meta/deploy_meta.sh
=> GEODE-5933 make it easier to use deploy_meta with forks

ci/pipelines/examples/jinja.template.yml, ci/pipelines/geode-build/jinja.template.yml, ci/pipelines/pull-request/jinja.template.yml
=> GEODE-5930 clean up dangling outputs in concourse

ci/pipelines/examples/jinja.template.yml
=> GEODE-5934 change start/stop instance to create/delete instance

ci/scripts/capture-call-stacks.sh
=> GEODE-5913 resolve jstack using JAVA_HOME, if set

ci/scripts/create_instance.sh
=> Echo out pre and post hashing name for instances.

ci/pipelines/geode-build/jinja.template.yml
=> Restore UpdatePassingRef for now.

ci/pipelines/geode-build/jinja.template.yml, ci/scripts/update-passing-ref.sh
=> Restore update passing ref

geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/QueryUsingPoolDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/wan/asyncqueue/ParallelAsyncEventListenerDistributedTest.java, geode-core/src/main/java/org/apache/geode/distributed/internal/locks/DLockGrantor.java, geode-core/src/main/java/org/apache/geode/distributed/internal/locks/DLockService.java, geode-core/src/main/java/org/apache/geode/distributed/internal/locks/ElderState.java, geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java, geode-core/src/main/java/org/apache/geode/internal/logging/log4j/LogWriterAppenders.java, geode-core/src/main/java/org/apache/geode/internal/offheap/OffHeapStoredObject.java, geode-core/src/performanceTest/java/org/apache/geode/internal/logging/LoggingPerformanceTestCase.java
This removes all mention of KIRK. There are still other developer
names present in comments.
=> GEODE-5941: Remove comments containing developer name

ci/pipelines/meta/deploy_meta.sh
* currently deploy_meta infers the branch name with no way to override.  print this with the other default variables and allow to be overridden if necessary like the other defaults (for example if your local branch name is tracking a remote branch that is named differently)
* when local overrides are not set up, print a kinder message about how to set them up
* handle 'pending' status for concourse jobs
- [n/a] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible …
=> deploy_meta enhancements

geode-core/src/distributedTest/java/org/apache/geode/cache/query/dunit/ResourceManagerWithQueryMonitorDUnitTest.java, geode-core/src/integrationTest/java/org/apache/geode/cache/query/internal/QueryMonitorIntegrationTest.java, geode-core/src/jmh/java/org/apache/geode/cache/query/internal/MonitorQueryUnderContentionBenchmark.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledIteratorDef.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/CompiledSelect.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/DefaultQuery.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/QueryExecutionCanceledException.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/QueryMonitor.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/QueryUtils.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/SortedStructBag.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/StructBag.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/AbstractIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/CompactRangeIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/HashIndex.java, geode-core/src/main/java/org/apache/geode/cache/query/internal/index/PrimaryKeyIndex.java, geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java, geode-core/src/main/java/org/apache/geode/internal/cache/PRQueryProcessor.java, geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionQueryEvaluator.java, geode-core/src/main/java/org/apache/geode/internal/cache/control/HeapMemoryMonitor.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/BaseCommandQuery.java, geode-core/src/test/java/org/apache/geode/cache/query/internal/QueryMonitorTest.java, geode-cq/src/distributedTest/java/org/apache/geode/cache/query/dunit/QueryMonitorDUnitTest.java
Eliminate notify/wait bugs and improve hot-path performance.
Co-authored-by: Ryan McMahon <rmcmahon@pivotal.io>
=> GEODE-5568: Rewrite QueryMonitor to use ScheduledThreadPoolExecutor

geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/DistributedRegionFunctionExecutionDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/execute/PRClientServerRegionFunctionExecutionDUnitTest.java, geode-core/src/distributedTest/java/org/apache/geode/internal/cache/functions/DistributedRegionFunctionFunctionInvocationException.java, geode-core/src/main/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunction66.java, geode-core/src/test/java/org/apache/geode/internal/cache/tier/sockets/command/ExecuteRegionFunction66Test.java
=> GEODE-5884: Non HA Function waits for all results if exception occurs

ci/bin/concourse_job_performance.py
Co-Authored-By: Patrick Rhomberg <prhomberg@pivotal.io>
=> GEODE-5948: Updated the cookie name

geode-core/build.gradle
=> GEODE-5803: Remove dependencies resulting from bad merge.

geode-core/src/main/java/org/apache/geode/datasource/PooledDataSourceFactory.java
=> GEODE-5966: mark PooledDataSourceFactory experimental
